### DISCUSSION TITLE
Can't reach SOLR admin page; works in Drupal

### DISCUSSION THREAD

**Discussion by miramar-webmaster** [docksal/docksal#1611] [Q&A] [answered]
Running SOLR 8 and Drupal 8.9. Everything is set up properly, SOLR works with Drupal, but when I go to my admin page "solr.local.sdmc.com/solr," I get "Page Not Found." Trying to go directly to port 8983 gets a "Refused To Connect."

One more thing, in the Drupal settings, "/solr" does not work as the path. It must be "/"

Any advice would be much appreciated, as I am completely frustrated at this time. TIA

In my ~/.docksal/stacks/services.yml:
 ```
 solr:
    hostname: solr
    image: ${SOLR_IMAGE:-docksal/solr:1.0-solr4}
    volumes:
      - project_root:/var/www:ro,nocopy  # Project root volume (read-only)
    labels:
      - io.docksal.virtual-host=solr.local.sdmc.com,solr.local.sdmc.com.*
      - io.docksal.virtual-port=8983
      - io.docksal.cert-name=${VIRTUAL_HOST_CERT_NAME:-none}
    << : *dns
    << : *logging
    << : *healthcheck
```

In my project root's .docksal/docksal.yml:
 ```
 solr:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
    hostname: solr
    image: ${SOLR_IMAGE:-docksal/solr:latest}
    volumes:
      - ${HOME}/web-projects/miraweb2021/.docksal/etc/solr/conf:/opt/server/solr/collection1/:ro
```
