### DISCUSSION TITLE
how to setup xdebug for vscode on a mac

### DISCUSSION THREAD

**Discussion by blu-regard** [docksal/docksal#1682] [Q&A]
I've tried to follow the steps here but they don't work:
https://docs.docksal.io/tools/xdebug/

here's my docksal.yml:

```
version: "3.9"
services:
  cli:
    environment:
      - REDIS_HOST
      - REDIS_KEY
      - REDIS_PORT
      - "XDEBUG_CONFIG=client_host=${DOCKSAL_HOST_IP} client_port=9000"
      - "XDEBUG_MODE=debug"
  redis:
    hostname: redis
    image: redis:latest
    command: redis-server --requirepass ${REDIS_KEY:-redis}
    volumes:
      - redis_data:/data
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
    ports:
      - ${REDIS_PORT}
volumes:
  redis_data:
```

docksal.env:
```
# Docksal configuration
PROJECT_ROOT=/var/www
DOCKSAL_STACK=default
DOCROOT=web

# Xdebug settings
XDEBUG_ENABLED=1

# Redis
REDIS_HOST=redis
REDIS_KEY=redis
REDIS_PORT=6379

XDEBUG_ENABLED="1"
PHP_IDE_CONFIG=serverName=${VIRTUAL_HOST}
```

and the local .vscode launch.json file:
```
{
  "version": "0.2.0",
  "hostname": "localhost",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9000,
      "pathMappings": {
        "/var/www/": "${workspaceFolder}",
        "/usr/local/bin/drush": "${workspaceFolder}/vendor/bin/drush"
      }
    },
    {
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 9000,
      "pathMappings": {
        "/var/www/": "${workspaceFolder}"
      }
    }
  ]
}
```
