### DISCUSSION TITLE
Custom command is not executed upon project start

### DISCUSSION THREAD

**Discussion by taskindrp** [docksal/docksal#1747] [Q&A]
Hello, 

I'm trying to run Nextjs project on Docksal using below configurations here is the docksal.yml:

```
version: "3.9"

services:
  ssm:
    command: ["bash", "-lc", "yarn install && yarn build && yarn start"]
    ports:
      - "8000:80"
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST},*.${VIRTUAL_HOST},${VIRTUAL_HOST}.*
      - io.docksal.virtual-port=8000
```

I want to execute `yarn install && yarn build && yarn start` upon project start but It does not do anything, just start the project.

What am I missing?
