### ISSUE TITLE
Enabling x-debug on cli:2.6-php7.3 results in FastCGI error in web container.

### ISSUE THREAD

**Issue by nagytomas** [docksal/docksal#1015]
**Description**

Switched to 7.3 all other version of php7 work as expected with x-debug. 7.3 only works without x-debug enabled though. Tried with both web:2.1-apache2.2 and web:2.2-apache2.2, same result.

**Steps to reproduce the issue:**

1. Switch 7.0, 7.1 or 7.2 to the new 7.3 cli image.
2. Enable x-debug
3. Try to access page.

**Describe the results you received:**

503 in browser.
Web container log: 
web_1_48c7929517a2 | [Thu Mar 28 09:21:36 2019] [error] [client 172.20.0.2] AH01067: Failed to read FastCGI header
web_1_48c7929517a2 | [Thu Mar 28 09:21:36 2019] [error] [client 172.20.0.2] (104)Connection reset by peer: AH01075: Error dispatching request to :
web_1_48c7929517a2 | 172.20.0.2 - - [28/Mar/2019:09:21:36 +0000] "GET / HTTP/1.1" 503 323

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: vok_digit
COMPOSE_FILE:
/Users/app/.docksal/stacks/volumes-bind.yml
/Users/app/.docksal/stacks/stack-default.yml
/Users/app/Sites/appnovation/VOK_digit/.docksal/docksal.yml
ENV_FILE:
/Users/app/Sites/appnovation/VOK_digit/.docksal/docksal.env

PROJECT_ROOT: /Users/app/Sites/appnovation/VOK_digit
DOCROOT: www
VIRTUAL_HOST: vok-digit.docksal
VIRTUAL_HOST_ALIASES: *.vok-digit.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: www
      GIT_USER_EMAIL: tomas.nagy@appnovation.com
      GIT_USER_NAME: Tomas Nagy
      HOST_GID: '20'
      HOST_UID: '501'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: vok-digit.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.6-php7.3
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  elasticsearch:
    hostname: elasticsearch
    image: elasticsearch:2.3.3
    ports:
    - 9200:9200/tcp
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/www
    hostname: web
    image: docksal/web:2.2-apache2.2
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/app/Sites/appnovation/VOK_digit
      io.docksal.virtual-host: vok-digit.docksal,*.vok-digit.docksal,vok-digit.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/app/Sites/appnovation/VOK_digit
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.14.3
Darwin appnovations-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH :
NFS EXPORTS:

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.80.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.1
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.06.1-ce

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKER MACHINE
EXPECTED VERSION: 0.15.0
docker-machine version 0.15.0, build b48dc28d

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.06.1-ce

███  DOCKSAL: PROJECTS
project             STATUS                   virtual host                                                project root
vok_digit           Up 6 minutes (healthy)   vok-digit.docksal,*.vok-digit.docksal,vok-digit.docksal.*   /Users/app/Sites/appnovation/VOK_digit

███  DOCKSAL: VIRTUAL HOSTS
*.vok-digit.docksal
vok-digit.docksal.*
vok-digit.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                       PORTS                                                    NAMES
7971f8f7dda7        docksal/web:2.2-apache2.2   "httpd-foreground"       6 minutes ago       Up 6 minutes (healthy)       80/tcp, 443/tcp                                          vok_digit_web_1_3b25c65f050a
d9b127c789c9        docksal/cli:2.6-php7.3      "/opt/startup.sh sup…"   14 minutes ago      Up 14 minutes (healthy)      22/tcp, 3000/tcp, 9000/tcp                               vok_digit_cli_1_4aa288589986
6e3c47235ad1        docksal/ssh-agent:1.2       "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)                                                            docksal-ssh-agent
8f6bcaf5c5c6        docksal/dns:1.1             "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)   192.168.64.100:53->53/udp                                docksal-dns
c507f9888f7a        docksal/vhost-proxy:1.4     "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
9983b7d04f4e        elasticsearch:2.3.3         "/docker-entrypoint.…"   8 days ago          Up About an hour             0.0.0.0:9200->9200/tcp, 9300/tcp                         vok_digit_elasticsearch_1_a78314fd285f
779faca9d9f3        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   8 days ago          Up About an hour             0.0.0.0:32768->3306/tcp                                  vok_digit_db_1_56817a157868

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
bc5c9e2efc3d        _default            bridge              local
20967bae99e9        bridge              bridge              local
81cf82800e62        host                host                local
f4a4921a1910        none                null                local
3bef4fe63b91        vok_digit_default   bridge              local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.20
5.2.20r125813

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/app/Sites/appnovation/VOK_digit on /mnt/sda1/var/lib/docker/volumes/vok_digit_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G      5.4G     38.4G  12% /mnt/sda1
  ```

</details>
