### ISSUE TITLE
Compatibility with VirtualBox 6.0

### ISSUE THREAD

**Issue by macmladen** [docksal/docksal#1021]
### Description

Starting of **Docksal** fails after `fin update`, Mac OS X 10.11.6:

* **previously, working:** fin 1.80.1, docker 18.06.1-ce
* **updated, NOT working:** fin 1.85.0, docker 18.09.2-ce

### Steps to reproduce the issue:

I've done only `fin update`, but later tried to rebuild with same outcome

1. `fin vm stop`
2. `fin vm remove`
3. `VBoxManage hostonlyif remove vboxnet0`
4. `fin system start`

### Describe the results you received:

<details>
  <summary>`fin` commands and response in recreation</summary>

```
~
mladen@Fish3 10:34:06 $ fin vm stop
Deprecated. Please use fin system stop instead.
Press any key to continue...
Stopping Docksal VM...
Stopping "docksal"...
Machine "docksal" was stopped.
Disabling automatic *.docksal DNS resolver...
Password:
Clearing DNS cache...
Removing NFS exports...
Writing and applying /etc/exports...
Configuring network settings...
~
mladen@Fish3 10:35:05 $ fin vm remove
Disabling automatic *.docksal DNS resolver...
Clearing DNS cache...
Removing NFS exports...
Configuring network settings...
Remove docksal? [y/n]: y
About to remove docksal
WARNING: This action will delete both local reference and remote instance.
Successfully removed docksal
~
mladen@Fish3 10:35:16 $ VBoxManage hostonlyif remove vboxnet0
VBoxManage: error: The host network interface named 'vboxnet0' could not be found
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component HostWrap, interface IHost, callee nsISupports
VBoxManage: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).raw(), hif.asOutParam())" at line 139 of file VBoxManageHostonly.cpp
~
mladen@Fish3 10:35:27 $ fin system start
Configuring network settings...
Creating docker machine 'docksal'...
Running pre-create checks...
Creating machine...
(docksal) Downloading /Users/mladen/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v18.09.2/boot2docker.iso...
(docksal) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(docksal) Creating VirtualBox VM...
(docksal) Creating SSH key...
(docksal) Starting the VM...
(docksal) Check network to re-create if needed...
(docksal) Found a new host-only adapter: "vboxnet0"
(docksal) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env docksal
Configuring network settings...
Configuring NFS shares...
Writing /etc/exports...
Restarting nfsd...
Mounting NFS shares...
Mounting local /Users to /Users
mount.nfs: access denied by server while mounting 192.168.64.1:/Users
exit status 32
Retrying mounting local /Users to /Users
mount.nfs: access denied by server while mounting 192.168.64.1:/Users
exit status 32
 ERROR:  NFS share mount failed.
         Try fin vm mount or fin vm restart.
Resetting Docksal system services...
 * proxy
Unable to find image 'docksal/vhost-proxy:1.5' locally
1.5: Pulling from docksal/vhost-proxy
4fe2ade4980c: Pulling fs layer
...
13b81fedd052: Pull complete
Digest: sha256:d43b777a80f441c86f836404d9fe47936f131fcb96da2365e57e8282b85469b4
Status: Downloaded newer image for docksal/vhost-proxy:1.5
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (83f4b5838b91342a17c7913091cfbafc8cc6ff6183c07d5693d61c07b2fc9ada): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 ERROR:  Failed starting the proxy service.
```

</details>

### Describe the results you expected:

<details>
  <summary>Started docksal as previously</summary>

```
~/Sites/
mladen@Fish3 22:13:28 $ fin vm start
Starting "docksal"...
(docksal) Check network to re-create if needed...
(docksal) Waiting for an IP...
Machine "docksal" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
Configuring NFS shares...
NFS shares are already configured
Mounting NFS shares...
Starting nfs client utilities.
Mounting local /Users to /Users
Importing ssh keys...
Identity added: id_rsa (id_rsa)
~/Sites/
mladen@Fish3 22:14:30 $ 
```
</details>

### Output of `fin config`:

<details>
  <summary>fin config 1.80.1, docker 18.06.1 working</summary>

```
~/Sites/vinci
mladen@Fish3 22:14:30 $ fin config
---------------------
COMPOSE_PROJECT_NAME_SAFE: vinci
COMPOSE_FILE:
/Users/mladen/.docksal/stacks/volumes-bind.yml
/Users/mladen/.docksal/stacks/stack-default.yml
/Users/mladen/Sites/vinci/.docksal/docksal.yml
ENV_FILE:
/Users/mladen/Sites/vinci/.docksal/docksal.env

PROJECT_ROOT: /Users/mladen/Sites/vinci
DOCROOT: web
VIRTUAL_HOST: vinci.docksal
VIRTUAL_HOST_ALIASES: *.vinci.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: web
      GIT_USER_EMAIL: mladen@bluefish.rs
      GIT_USER_NAME: Mladen Đurić
      HOST_GID: '20'
      HOST_UID: '501'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: vinci.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.4-php5.6
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.vinci.docksal
    user: root
  pma:
    environment:
      PMA_HOST: db
      PMA_PASSWORD: root
      PMA_USER: root
    hostname: pma
    image: phpmyadmin/phpmyadmin
    labels:
      io.docksal.virtual-host: pma.vinci.docksal
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/web
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/mladen/Sites/vinci
      io.docksal.virtual-host: vinci.docksal,*.vinci.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/mladen/Sites/vinci
      o: bind
      type: none

---------------------
~/Sites/vinci
mladen@Fish3 22:15:20 $
```

</details>

<details>
  <summary>fin config 1.85.0, docker 18.09.2 <strong>NOT</strong> working</summary>

```
~/Sites/
mladen@Fish3 11:05:58 $ fin config
 ALERT:  Some Docksal services were not running
         Restarting Docksal system services...
Configuring network settings...
Configuring NFS shares...
NFS shares are already configured
Mounting NFS shares...
Mounting local /Users to /Users
mount.nfs: access denied by server while mounting 192.168.64.1:/Users
exit status 32
Retrying mounting local /Users to /Users
mount.nfs: access denied by server while mounting 192.168.64.1:/Users
exit status 32
 ERROR:  NFS share mount failed.
         Try fin vm mount or fin vm restart.
Resetting Docksal system services...
 * proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (15fc2d7979c16fbf008a9e35f7cfeeb44addf2c9681a2385acfc5dc9d6a8a2e0): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 ERROR:  Failed starting the proxy service.
~/Sites/
mladen@Fish3 11:06:08 $ fin config

```

</details>

### Output of `fin sysinfo`:

<details>
  <summary>fin sysinfo 1.80.1, docker 18.06.1 working</summary>

  ```
~/Sites/vinci
mladen@Fish3 22:18:06 $ fin sysinfo
███  OS
Darwin Mac OS X 10.11.6
Darwin Fish3.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : 
NFS EXPORTS:

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.80.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.1
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.06.1-ce

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKER MACHINE
EXPECTED VERSION: 0.15.0
docker-machine version 0.16.1, build cce350d7

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.06.1-ce   

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                   PORTS                                                    NAMES
47b95d95ee29        docksal/ssh-agent:1.2     "docker-entrypoint.s…"   9 days ago          Up 4 minutes (healthy)                                                            docksal-ssh-agent
68fde8c3312c        docksal/dns:1.1           "docker-entrypoint.s…"   9 days ago          Up 4 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
1b6de4df11ca        docksal/vhost-proxy:1.4   "docker-entrypoint.s…"   9 days ago          Up 4 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                     DRIVER              SCOPE
7356236f7851        _default                 bridge              local
eb766c61db60        bridge                   bridge              local
ccf6febd5740        frd_default              bridge              local
d800810fca83        host                     host                local
d0fb806bf6f0        koder_default            bridge              local
c85a552efbc0        none                     null                local
919a8b1524d9        vinci-belgrade_default   bridge              local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.20
6.0.0r127566

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G      4.5G     39.3G  10% /mnt/sda1
~/Sites/vinci
mladen@Fish3 22:18:42 $ 
  ```

</details>

<details>
  <summary>fin sysinfo 1.85.0, docker 18.09.2 <strong>NOT</strong> working</summary>

```
~
mladen@Fish3 11:03:12 $ fin sysinfo
███  OS
Darwin Mac OS X 10.11.6
Darwin Fish3.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.104:2376
DOCKSAL_NFS_PATH : /Users
NFS EXPORTS:

# <ds-nfs docksal
/Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.85.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:20:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.1
docker-machine version 0.16.1, build cce350d7

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.104:2376           v18.09.2   

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS
Error response from daemon: Container 4495180b91354688c8252cf6e42ff37df6dff9bddd412e397a348d89f2ca2d20 is not running
No virtual hosts found

███  DOCKSAL: DNS
curl: (6) Could not resolve host: dns-test.docksal
ERROR: Requesting http://dns-test.docksal failed!

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
fcc7196e78c0        bridge              bridge              local
cc20262ba83e        host                host                local
ada67c80fcf1        none                null                local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.26
6.0.0r127566

███  DOCKSAL MOUNTS
 ERROR:  Mounts matching 192.168.64* were not found!

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G    214.2M     43.5G   0% /mnt/sda1
~
mladen@Fish3 11:04:07 $ 
```

</details>
