### ISSUE TITLE
"Repository does not have a release file" when running "apt-get update" from extended Dockerfile

### ISSUE THREAD

**Issue by mikecrittenden** [docksal/docksal#1028]
**Description**

Problem/feature description...

**Steps to reproduce the issue:**

1. Start an empty Docksal project
2. Set your `.docksal/docksal.yml` to this:
    ```
    version: '2.1'
    services:
      cli:
        build: services/cli
        image: ${COMPOSE_PROJECT_NAME_SAFE}_cli
    ```
3. Create `.docksal/services/cli/Dockerfile` like so:
    ```
    FROM docksal/cli:php7.2
    RUN set -xe; \
	sudo apt-get update;
    ```
4. Run `fin up`

**Describe the results you received:**

I get this output (note the error message at the end):

```
❯ fin up
Key 'id_rsa' already loaded in the agent. Skipping.
Starting services...
Building cli
Step 1/2 : FROM docksal/cli:php7.2
 ---> c7c1df819f79
Step 2/2 : RUN set -xe; 	sudo apt-get update;
 ---> Running in 6c0119e0841e
+ sudo apt-get update
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:2 http://deb.debian.org/debian stretch InRelease
Get:3 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 https://packages.microsoft.com/debian/8/prod jessie InRelease [3226 B]
Ign:6 http://ftp.debian.org/debian jessie-backports InRelease
Get:7 http://deb.debian.org/debian stretch Release.gpg [2434 B]
Get:8 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [484 kB]
Get:9 http://security.debian.org/debian-security stretch/updates/non-free amd64 Packages [1600 B]
Get:10 http://security.debian.org/debian-security stretch/updates/contrib amd64 Packages [1760 B]
Ign:11 http://ftp.debian.org/debian jessie-backports Release
Ign:13 http://ftp.debian.org/debian jessie-backports/main amd64 Packages
Get:14 http://deb.debian.org/debian stretch-updates/main amd64 Packages [11.1 kB]
Get:15 https://packages.microsoft.com/debian/8/prod jessie/main amd64 Packages [29.8 kB]
Ign:16 http://ftp.debian.org/debian jessie-backports/main all Packages
Get:17 http://deb.debian.org/debian stretch/non-free amd64 Packages [78.3 kB]
Get:18 http://deb.debian.org/debian stretch/contrib amd64 Packages [50.9 kB]
Get:19 http://deb.debian.org/debian stretch/main amd64 Packages [7084 kB]
Get:12 https://packagecloud.io/github/git-lfs/debian jessie InRelease [23.2 kB]
Ign:13 http://ftp.debian.org/debian jessie-backports/main amd64 Packages
Ign:16 http://ftp.debian.org/debian jessie-backports/main all Packages
Ign:13 http://ftp.debian.org/debian jessie-backports/main amd64 Packages
Ign:12 https://packagecloud.io/github/git-lfs/debian jessie InRelease
Ign:16 http://ftp.debian.org/debian jessie-backports/main all Packages
Ign:13 http://ftp.debian.org/debian jessie-backports/main amd64 Packages
Ign:16 http://ftp.debian.org/debian jessie-backports/main all Packages
Ign:13 http://ftp.debian.org/debian jessie-backports/main amd64 Packages
Get:20 https://packagecloud.io/github/git-lfs/debian jessie/main amd64 Packages [8107 B]
Ign:16 http://ftp.debian.org/debian jessie-backports/main all Packages
Err:13 http://ftp.debian.org/debian jessie-backports/main amd64 Packages
  404  Not Found
Ign:16 http://ftp.debian.org/debian jessie-backports/main all Packages
Get:21 https://packages.blackfire.io/debian any InRelease [23.2 kB]
Ign:21 https://packages.blackfire.io/debian any InRelease
Get:22 https://packages.blackfire.io/debian any/main amd64 Packages [1199 B]
Fetched 8106 kB in 2s (2911 kB/s)
Reading package lists...
W: The repository 'http://ftp.debian.org/debian jessie-backports Release' does not have a Release file.
W: GPG error: https://packagecloud.io/github/git-lfs/debian jessie InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: The repository 'https://packagecloud.io/github/git-lfs/debian jessie InRelease' is not signed.
W: GPG error: https://packages.blackfire.io/debian any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 696DBE66A72D76DA
W: The repository 'https://packages.blackfire.io/debian any InRelease' is not signed.
E: Failed to fetch http://ftp.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'cli' failed to build: The command '/bin/sh -c set -xe; 	sudo apt-get update;' returned a non-zero code: 100
```

**Describe the results you expected:**

I'd expect it to build successfully, and have no issues running apt-get update.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
❯ fin config
---------------------
COMPOSE_PROJECT_NAME_SAFE: myproject
COMPOSE_FILE:
/Users/mcrittenden/.docksal/stacks/overrides-osxfs.yml
/Users/mcrittenden/.docksal/stacks/volumes-bind.yml
/Users/mcrittenden/Dropbox/Code/myproject/.docksal/docksal.yml
ENV_FILE:
/Users/mcrittenden/Dropbox/Code/myproject/.docksal/docksal.env

PROJECT_ROOT: /Users/mcrittenden/Dropbox/Code/myproject
DOCROOT: docroot
VIRTUAL_HOST: myproject.docksal
VIRTUAL_HOST_ALIASES: *.myproject.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    build:
      context: /Users/mcrittenden/Dropbox/Code/myproject/.docksal/services/cli
    image: myproject_cli
    volumes:
    - /Users/mcrittenden/Dropbox/Code/myproject:/var/www:rw,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/mcrittenden/Dropbox/Code/myproject
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  ███  OS
Darwin Mac OS X 10.14.3
Darwin Mike-Crittendens-New-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.85.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS
[0;32mwebui.docksal[0m

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                   PORTS                                                    NAMES
6ad7043c6f6e        docksal/ssh-agent:1.2     "docker-entrypoint.s…"   5 minutes ago       Up 5 minutes (healthy)                                                            docksal-ssh-agent
c48803ee4371        docksal/dns:1.1           "docker-entrypoint.s…"   5 minutes ago       Up 5 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
accf20ba99c0        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   5 minutes ago       Up 5 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
29c9393933c2        postgres                  "docker-entrypoint.s…"   4 weeks ago         Up About an hour         0.0.0.0:5432->5432/tcp                                   clay-starter_postgres_1
4c6693f632c4        docksal/webui             "supervisord -n"         4 months ago        Up About an hour         80/tcp, 443/tcp                                          webui

███  DOCKER: NETWORKS
NETWORK ID          NAME                                                                         DRIVER              SCOPE
b224e98fdda1        _default                                                                     bridge              local
710943d98afb        bostonvocations_default                                                      bridge              local
e1442bdf411a        bridge                                                                       bridge              local
5e2db1312c85        clay-starter_default                                                         bridge              local
41066da053d2        docksaltest_default                                                          bridge              local
9996a58b411a        dosomethingindonesia_default                                                 bridge              local
5001d9692258        faithmag_default                                                             bridge              local
20655834de6a        fanniemae_default                                                            bridge              local
b58d3d9f5e4b        haxcms_default                                                               bridge              local
4d5fcec96029        host                                                                         host                local
9bf681ca0a21        lando_bridge_network                                                         bridge              local
c317fee5918f        landocasetupkenobi38ahsokabb021307b4190300c7b11bea76bb7c78b8e0feb4_default   bridge              local
18df2abfe561        landoinitdosomethingindonesia_default                                        bridge              local
36805f8848f9        landoproxyhyperion5000gandalfedition_edge                                    bridge              local
1cce3f8d7aca        mp7_default                                                                  bridge              local
b50901d01b34        mp8_default                                                                  bridge              local
e5dbd15d735b        none                                                                         null                local
8fcf455fa8d9        particle-docksal_default                                                     bridge              local
26ff77bc12c8        particle_default                                                             bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3
2.0.0.3

███  HDD Usage
Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1   234Gi  207Gi   21Gi    91% 3651427 9223372036851124380    0%   /
devfs          188Ki  188Ki    0Bi   100%     649                   0  100%   /dev
/dev/disk1s4   234Gi  5.0Gi   21Gi    20%       5 9223372036854775802    0%   /private/var/vm
map -hosts       0Bi    0Bi    0Bi   100%       0                   0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0                   0  100%   /home
  ```

</details>
