### ISSUE TITLE
Docksal install fails on WSL 17758.4 Ubuntu 18.04 LTS on docker-machine symlink

### ISSUE THREAD

**Issue by cybtachyon** [docksal/docksal#1053]
**Description**

Docksal install fails on WSL 17758.4 Ubuntu 18.04 LTS on docker-machine symlink

**Steps to reproduce the issue:**
Assuming a working WSL install.
```bash
bash <(curl -fsSL https://get.docksal.io)`
```

**Describe the results you received:**

```bash
...Invalid argument to docker-machine...
```

```bash
$ cd /c/Users/username/.docksal/bin
$ ./docker-machine
Invalid argument(s)...
```

**Describe the results you expected:**

Installation succeeds and `fin system start` succeeds.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: myproject
COMPOSE_FILE:
/mnt/c/Users/username/.docksal/stacks/volumes-bind.yml
/mnt/c/Users/username/.docksal/stacks/stack-default.yml
/c/Users/username/projects/myproject/.docksal/docksal.yml
ENV_FILE:
/c/Users/username/projects/myproject/.docksal/docksal.env

PROJECT_ROOT: /c/Users/username/projects/myproject
DOCROOT: docroot
VIRTUAL_HOST: myproject.docksal
VIRTUAL_HOST_ALIASES: *.myproject.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:30339

Docker Compose configuration
---------------------
services:
  browser:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    hostname: browser
    image: selenium/standalone-chrome
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '1'
      GIT_USER_EMAIL: cyb.tachyonATgmail
      GIT_USER_NAME: Derek Reese
      HOST_GID: '1000'
      HOST_UID: '1000'
      PHP_IDE_CONFIG: serverName=myproject.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: myproject.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.4-php7.2
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: drupal_lanfest
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 30339:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /c/Users/username/projects/myproject
      io.docksal.virtual-host: myproject.docksal,*.myproject.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/username/projects/myproject
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
WSL Ubuntu 16.04
Linux pc 4.4.0-17758-Microsoft #1-Microsoft Fri Sep 07 15:36:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376

███  FIN
fin version: 1.85.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:11:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:20:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.1
docker-machine.exe version 0.16.1, build cce350d7

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
docksal   -        virtualbox   Running   tcp://192.168.64.100:2376           v18.09.2   

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                        project root
myproject             Up 40 minutes       myproject.docksal,*.myproject.docksal   /c/Users/username/projects/myproject/repos/lfestorg/lfestorg

███  DOCKSAL: VIRTUAL HOSTS
[0;32m*.myproject.docksal[0m
[0;32mmyproject.docksal[0m

███  DOCKSAL: DNS
ERROR: Requesting http://dns-test.docksal failed!

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                       PORTS                                                    NAMES
ee68f3f95728        docksal/web:2.1-apache2.4    "httpd-foreground"       40 minutes ago      Up 40 minutes                80/tcp, 443/tcp                                          myproject_web_1
204805afda1b        docksal/cli:2.4-php7.2       "/opt/startup.sh sup…"   40 minutes ago      Up 40 minutes (healthy)      22/tcp, 3000/tcp, 9000/tcp                               myproject_cli_1
7db45d270322        memcached:1.4-alpine         "docker-entrypoint.s…"   40 minutes ago      Up 40 minutes                11211/tcp                                                myproject_memcached_1
e0d7f6814ff5        selenium/standalone-chrome   "/opt/bin/entry_poin…"   40 minutes ago      Up 40 minutes                4444/tcp                                                 myproject_browser_1
ae8b21673892        docksal/db:1.1-mysql-5.6     "/entrypoint.sh mysq…"   40 minutes ago      Up 40 minutes                0.0.0.0:30339->3306/tcp                                  myproject_db_1
01be885fbfaa        docksal/ssh-agent:1.2        "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)                                                            docksal-ssh-agent
eff2434db802        docksal/dns:1.1              "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)   192.168.64.100:53->53/udp                                docksal-dns
41f0bf8de0da        docksal/vhost-proxy:1.5      "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
53c38e3b67c7        _default            bridge              local
e0abea4ca6b6        bridge              bridge              local
4bb955ac3e46        host                host                local
1da323675e5d        myproject_default     bridge              local
17ed237416f9        none                null                local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.26
5.2.28r130011

███  DOCKSAL MOUNTS
//192.168.64.1/docksal-c on /c type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=cybta,domain=pc,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,soft,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//192.168.64.1/docksal-d on /d type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=cybta,domain=pc,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,soft,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G      3.7G     40.0G   9% /mnt/sda1
  ```

</details>

**Suggested Resolution**
Do not remove docksal vm after failed install.
```bash
rm /c/Users/username/.docksal/bin/docker-machine
printf 'exec /mnt/c/Users/myuser/.docksal/bin/docker-machine.exe "$@"' &1>> /c/Users/username/.docksal/bin/docker-machine
sudo chmod +x /c/Users/username/.docksal/bin/docker-machine
fin system start
```

Possible related issues:
- https://github.com/docksal/docksal/issues/251
- https://github.com/Microsoft/WSL/issues/3611
- https://github.com/microsoft/WSL/issues/3999
