### ISSUE TITLE
Database servers randomly crash and disappear saying ERROR: for db  Cannot start service db: network <uuid> not found

### ISSUE THREAD

**Issue by chadmandoo** [docksal/docksal#1063]
**Description**

Docksal with Docker randomly crashes the database server and never comes back up. Its not a matter of if it will crash but when. I have had this happen 3-5 within the past month alone.

**Steps to reproduce the issue:**

1. You can't. You are working and randomly the database container goes down and stops working

**Describe the results you received:**

Starting marvelcomicdb_db_1_10cc56d0ec09 ... error

ERROR: for marvelcomicdb_db_1_10cc56d0ec09  Cannot start service db: network 49094e244ea55c28da7f090d4ff827237bfbbf150538ac98319484e2c2667da3 not found

ERROR: for db  Cannot start service db: network 49094e244ea55c28da7f090d4ff827237bfbbf150538ac98319484e2c2667da3 not found
ERROR: Encountered errors while bringing up the project.

**Describe the results you expected:**
The database container to come up.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: marvelcomicdb
COMPOSE_FILE:
/Users/cpeppers/.docksal/stacks/overrides-osxfs.yml
/Users/cpeppers/.docksal/stacks/volumes-bind.yml
/Users/cpeppers/.docksal/stacks/stack-default.yml
/Users/cpeppers/Documents/Dev/php/marvelcomicdb/.docksal/docksal.yml
ENV_FILE:
/Users/cpeppers/Documents/Dev/php/marvelcomicdb/.docksal/docksal.env

PROJECT_ROOT: /Users/cpeppers/Documents/Dev/php/marvelcomicdb
DOCROOT: web
VIRTUAL_HOST: marvelcomicdb.docksal
VIRTUAL_HOST_ALIASES: *.marvelcomicdb.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: web
      GIT_USER_EMAIL: chad.peppers@avagate.com
      GIT_USER_NAME: cpeppers
      HOST_GID: '1146701519'
      HOST_UID: '1793721006'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: marvelcomicdb.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.5-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /Users/cpeppers/Documents/Dev/php/marvelcomicdb:/var/www:rw,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/web
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/cpeppers/Documents/Dev/php/marvelcomicdb
      io.docksal.virtual-host: marvelcomicdb.docksal,*.marvelcomicdb.docksal,marvelcomicdb.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/cpeppers/Documents/Dev/php/marvelcomicdb
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.14.5
Darwin GSCMACLC02XR2EWJG5M.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker for Mac

███  FIN
fin version: 1.80.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.1
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.06.1-ce

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                   PORTS                                                    NAMES
017ddc2cc029        docksal/ssh-agent:1.2     "docker-entrypoint.s…"   9 minutes ago       Up 9 minutes (healthy)                                                            docksal-ssh-agent
55d94fdaa08d        docksal/dns:1.1           "docker-entrypoint.s…"   9 minutes ago       Up 9 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
d519d703cf47        docksal/vhost-proxy:1.4   "docker-entrypoint.s…"   9 minutes ago       Up 9 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                               DRIVER              SCOPE
12fcc9f830d2        _default                           bridge              local
a6484f3ae2f2        aaanational_default                bridge              local
22c25ee0fd0d        alf_default                        bridge              local
107f68b1ecba        bridge                             bridge              local
cb250fc0c01b        client-portal-management_default   bridge              local
ed81b6b6f801        client-portal-new_default          bridge              local
1e978f7a4bf5        d8_default                         bridge              local
51014e63e1b3        directlink-admin_default           bridge              local
92595c1036d6        ecf_default                        bridge              local
e62894f5c9c2        globalmands_default                bridge              local
a1c53c3b7144        host                               host                local
47904aefaf3d        littler-home_default               bridge              local
1ed1fe98e20d        littlerwalmartvmlkit_default       bridge              local
39dd203aac07        none                               null                local

███  HDD Usage
Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1   466Gi  132Gi  332Gi    29% 1509327 9223372036853266480    0%   /
devfs          188Ki  188Ki    0Bi   100%     651                   0  100%   /dev
/dev/disk1s4   466Gi  1.0Gi  332Gi     1%       1 9223372036854775806    0%   /private/var/vm
map -hosts       0Bi    0Bi    0Bi   100%       0                   0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0                   0  100%   /home
map -fstab       0Bi    0Bi    0Bi   100%       0                   0  100%   /Network/Servers

  ```

</details>
