### ISSUE TITLE
Docksal CI Agent on GitLab issues

### ISSUE THREAD

**Issue by ArtuGit** [docksal/docksal#1065]
I use https://github.com/docksal/ci-agent/blob/develop/README.md as an instruction to establish Docksal CI Agent on GitLab. I have a sandbox server in Digital Ocean, 

1.  I set up `DOCKSAL_HOST_SSH_KEY` as a variable in GitLab CI / CD Setting which contains  *private* key for the Sandbox server `build` account. Is this correct? I have this 

![image](https://user-images.githubusercontent.com/10816446/58466701-dd2c3f80-8142-11e9-9d45-71a953909076.png)

2. There is no GitLab example in [Project configuration](https://github.com/docksal/ci-agent/blob/develop/README.md#project-configuration). I suggest adding such an example to the `README.md`.

I use the following `.gitlab-ci.yml`:
```
build_test:
  image: docksal/ci-agent:php
  script:
    - source build-env  # Initialize the agent configuration
    - build-init  # Initialize the remote sandbox environment
    - build-exec "cd www && fin drush st"  # Test performing within the build 
  when: manual
```
