### ISSUE TITLE
Emails are not sent

### ISSUE THREAD

**Issue by ArtuGit** [docksal/docksal#1068]
I faced that MailHog does not catch emails in my Drupal 8 project.
I tried different Docksal installations, but it looks emails are not sent with default `DOCKSAL_STACK`.
In order to prove it simply, I created a project with `fin init` in an empty folder.      

I use [this script](https://github.com/docksal/docksal/issues/248#issuecomment-306537211) to test email sending.
I return `bool(false)`. I have a Drupal 7 project where this script returns `bool(true)`, but I suppose it has to work with the default Docksal Stack.
 
**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: email-test
COMPOSE_FILE:
/home/artu/.docksal/stacks/volumes-bind.yml
/home/artu/.docksal/stacks/stack-default.yml
/data/projects/email-test/.docksal/docksal.yml
ENV_FILE:
/data/projects/email-test/.docksal/docksal.env

PROJECT_ROOT: /data/projects/email-test
DOCROOT: docroot
VIRTUAL_HOST: email-test.docksal
VIRTUAL_HOST_ALIASES: *.email-test.docksal
IP: 192.168.64.100                                                                                                                                                                              
MYSQL: 192.168.64.100:32768                                                                                                                                                                     
                                                                                                                                                                                                
Docker Compose configuration                                                                                                                                                                    
---------------------                                                                                                                                                                           
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      GIT_USER_EMAIL: artuon@gmail.com
      GIT_USER_NAME: Artu
      HOST_GID: '1000'
      HOST_UID: '1000'
      PHP_IDE_CONFIG: serverName=email-test.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: email-test.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.6-php7.2
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /data/projects/email-test
      io.docksal.virtual-host: email-test.docksal,*.email-test.docksal,email-test.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /data/projects/email-test
      o: bind
      type: none

---------------------

```
</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Linux Debian GNU/Linux 9
Linux laptop 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST : 

███  FIN
fin version: 1.85.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

███  DOCKER
EXPECTED VERSION: 18.09.2

Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKSAL: PROJECTS
project             STATUS                    virtual host                                                   project root
email-test          Up 29 minutes (healthy)   email-test.docksal,*.email-test.docksal,email-test.docksal.*   /data/projects/email-test

███  DOCKSAL: VIRTUAL HOSTS
*.email-test.docksal
email-test.docksal.*
email-test.docksal

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
1273d9938939        docksal/apache:2.4-2.3    "httpd-foreground"       29 minutes ago      Up 29 minutes (healthy)   80/tcp, 443/tcp                                          email-test_web_1
a1adb1c7cd71        docksal/mysql:5.6-1.4     "docker-entrypoint.s…"   29 minutes ago      Up 29 minutes (healthy)   0.0.0.0:32768->3306/tcp                                  email-test_db_1
bbb0038c518a        docksal/cli:2.6-php7.2    "/opt/startup.sh sup…"   29 minutes ago      Up 29 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               email-test_cli_1
97ad5135c10a        docksal/ssh-agent:1.2     "docker-entrypoint.s…"   12 hours ago        Up 43 minutes (healthy)                                                            docksal-ssh-agent
355f1ee149c5        docksal/dns:1.1           "docker-entrypoint.s…"   12 hours ago        Up 43 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
c1205d160706        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   12 hours ago        Up 43 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                   DRIVER              SCOPE
79ad4bc68ee7        _default               bridge              local
1ff7c6e068d5        bridge                 bridge              local
d112d4f0fc8d        d8_default             bridge              local
30903047ee0f        demo-project_default   bridge              local
01ea2ca3c9d4        drupal7_default        bridge              local
a3cf00539645        email-test_default     bridge              local
5f46ab7a69d4        host                   host                local
77d38e841b18        itcross_default        bridge              local
0e5ed1e6a803        mystipendium_default   bridge              local
05589652a051        none                   null                local
64a678d576bb        starter_default        bridge              local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.26
6.0.4r128413

███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           790M   18M  772M   3% /run
/dev/sda1       212G   93G  109G  47% /
tmpfs           3.9G  175M  3.7G   5% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs           790M   16K  790M   1% /run/user/1000
  ```

</details>
