### ISSUE TITLE
Support: Composer is always installing from cache, even after the cli container is nuked

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#1083]
**Description**

After removing containers and then re-creating, and after removing all previously installed Composer packages (deleting vendor, docroot/core, docroot/modules/contrib, etc.), I run `fin exec composer install`, and every single package says "Installing blabla/blabla (version): Loading from cache".

I have no idea why this is happening, given that the cache dir is set to /home/docker/.composer/cache and after resetting the container that directory is empty. After removing the cli container, I would expect this directory gets nuked. I can confirm that cache directory does not exist after re-creating the containers. So, I would expect to see "Downloading..." for each package that is being installed, but I'm not, it's loading from cache every time.

I googled around quite a bit last night trying to figure out why this could be happening, but I haven't been able to find anything definitive. I'm wondering if I'm just fundamentally misunderstanding something about Composer, or if there is something sinister going on with Docker volumes that I'm just not piecing together.

Any thoughts at all?

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: corvette
COMPOSE_FILE:
/Users/les.peabody/.docksal/stacks/volumes-nfs.yml
/Users/les.peabody/.docksal/stacks/stack-acquia.yml
/Users/les.peabody/Sites/corvette/.docksal/docksal.yml
/Users/les.peabody/Sites/corvette/.docksal/docksal-local.yml
ENV_FILE:
/Users/les.peabody/Sites/corvette/.docksal/docksal.env
/Users/les.peabody/Sites/corvette/.docksal/docksal-local.env

PROJECT_ROOT: /Users/les.peabody/Sites/corvette
DOCROOT: docroot
VIRTUAL_HOST: baxter.docksal
VIRTUAL_HOST_ALIASES: *.baxter.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32778

Docker Compose configuration
---------------------
services:
  browser:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    hostname: browser
    image: selenium/standalone-chrome
  cli:
    build:
      context: /Users/les.peabody/Sites/corvette/.docksal/services/cli
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DEFAULT_BUILD_THEME_PROFILE: bax_base
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      GIT_USER_EMAIL: null
      GIT_USER_NAME: null
      HOST_GID: '1106437719'
      HOST_UID: '1729411499'
      PHP_IDE_CONFIG: serverName=baxter.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: baxter.docksal
      XDEBUG_CONFIG: idekey=PHPSTORM remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: corvette_cli
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: solr
    image: docksal/solr:1.0-solr4
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: solr.baxter.docksal,solr.baxter.docksal.*
      io.docksal.virtual-port: '8983'
    volumes:
    - project_root:/var/www:ro,nocopy
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:1.1-varnish4
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: varnish.com.baxter.docksal,varnish.edu.baxter.docksal,varnish.special.baxter.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/les.peabody/Sites/corvette
      io.docksal.virtual-host: baxter.docksal,*.baxter.docksal,www.baxter.com
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: :/Users/les.peabody/Sites/corvette
      o: addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,actimeo=1
      type: nfs

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.12.6
Darwin BOSGEN-NMX0813.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : /Users
NFS EXPORTS:

# <ds-nfs docksal
/Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.85.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:20:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.1
docker-machine version 0.16.1, build cce350d7

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.09.2   
jira      -        virtualbox   Stopped                                       Unknown    
wiki      -        virtualbox   Stopped                                       Unknown    

███  DOCKSAL: PROJECTS
project             STATUS                   virtual host                                     project root
corvette            Up 6 seconds (healthy)   baxter.docksal,*.baxter.docksal,www.baxter.com   /Users/les.peabody/Sites/corvette

███  DOCKSAL: VIRTUAL HOSTS
[0;32m*.baxter.docksal[0m
[0;32mbaxter.docksal[0m
[0;32msolr.baxter.docksal.*[0m
[0;32msolr.baxter.docksal[0m
[0;32mvarnish.com.baxter.docksal[0m
[0;32mvarnish.edu.baxter.docksal[0m
[0;32mvarnish.special.baxter.docksal[0m
[0;32mwww.baxter.com[0m

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                             PORTS                                                    NAMES
d62a0862bfd8        docksal/varnish:1.1-varnish4   "/opt/startup.sh"        7 seconds ago       Up 6 seconds                       80/tcp, 6082/tcp                                         corvette_varnish_1
6c865df69033        docksal/apache:2.4-2.3         "httpd-foreground"       8 seconds ago       Up 7 seconds (healthy)             80/tcp, 443/tcp                                          corvette_web_1
ccb6afd03ac2        corvette_cli                   "/opt/startup.sh sup…"   12 seconds ago      Up 8 seconds (healthy)             22/tcp, 3000/tcp, 9000/tcp                               corvette_cli_1
cabe0cef18a6        docksal/mysql:5.6-1.4          "docker-entrypoint.s…"   12 seconds ago      Up 11 seconds (health: starting)   0.0.0.0:32779->3306/tcp                                  corvette_db_1
a255723cd145        memcached:1.4-alpine           "docker-entrypoint.s…"   12 seconds ago      Up 11 seconds                      11211/tcp                                                corvette_memcached_1
181e3517cfe4        docksal/solr:1.0-solr4         "/opt/solr/bin/solr …"   12 seconds ago      Up 11 seconds                      8983/tcp                                                 corvette_solr_1
ae36b35fff68        selenium/standalone-chrome     "/opt/bin/entry_poin…"   12 seconds ago      Up 11 seconds                      4444/tcp                                                 corvette_browser_1
1c5ff9194d9f        docksal/ssh-agent:1.2          "docker-entrypoint.s…"   20 hours ago        Up 20 hours (healthy)                                                                       docksal-ssh-agent
878684af1a1f        docksal/dns:1.1                "docker-entrypoint.s…"   20 hours ago        Up 20 hours (healthy)              192.168.64.100:53->53/udp                                docksal-dns
ad3bb131467b        docksal/vhost-proxy:1.5        "docker-entrypoint.s…"   20 hours ago        Up 20 hours (healthy)              192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                   DRIVER              SCOPE
6b8f85a0dcd0        _default               bridge              local
de4517e3364a        bridge                 bridge              local
a5257169b262        corvette_default       bridge              local
f787c288c801        emulsify_default       bridge              local
035533aa214d        host                   host                local
e1b3d65ee9b7        lespeabodyme_default   bridge              local
d944d8d50fa4        none                   null                local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.26
5.2.26r128414

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.64.1,mountvers=3,mountport=690,mountproto=udp,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/les.peabody/Sites/corvette on /mnt/sda1/var/lib/docker/volumes/corvette_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.64.1,mountvers=3,mountport=690,mountproto=udp,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G     12.9G     30.8G  30% /mnt/sda1

  ```

</details>
