### ISSUE TITLE
 Disk space leak on some container 

### ISSUE THREAD

**Issue by ArtuGit** [docksal/docksal#1089]
I use Docksal on a server for builds without `docksal/ci-agent`.

This is very simple, and it works in one directory - `~/builds/master`.

Some `fin` commands are executed from GitlLab CI/CD through SSH on every build including a custom command which gets files and DB from a remote server. 

```
build_test:

  script:
    - ssh -o StrictHostKeyChecking=no "$BUILD_USER_HOST_NAME" "cd $BUILD_DIR/master && fin up"
    - ssh -o StrictHostKeyChecking=no "$BUILD_USER_HOST_NAME" "cd $BUILD_DIR/master && fin <something>"
```

Some builds are failed.

I have one container which is continuously increased, up to the whole disk space.

![image](https://user-images.githubusercontent.com/10816446/60032679-5f0e7a80-96a7-11e9-9072-1b26c47dd808.png)

It is ok if the folder with the container is deleted, but I would like to do it purer.

Where can be leaking in Docksal? How can I solve this without recreating the project each time?

**Comment by ArtuGit** [comment]
I found this is a container with Backstop JS (`backstop_1`). I use this configuration in `docksal.yml`:

```
  # BackstopJS
  backstop:
    hostname: backstop
    image: backstopjs/backstopjs
    volumes:
      - ${PROJECT_ROOT}/tests/backstop:/src
    # Keep the container running
    entrypoint: "top -b"
    shm_size: 1g  
```

How to clean tit properly?
