### ISSUE TITLE
`fin up` never completes when using unison

### ISSUE THREAD

**Issue by MKorostoff** [docksal/docksal#1090]
**Description**

When using the unison file management paradigm, `fin up` runs forever. It continues giving output like this and never stops:

<img width="660" alt="unison" src="https://user-images.githubusercontent.com/1197335/60193496-c6424100-9805-11e9-89ac-8f0bff6cdb82.png">

<img width="660" alt="readme" src="https://user-images.githubusercontent.com/1197335/60194676-cc392180-9807-11e9-9b7c-3c1401bde263.png">

If I abort the process with `^C` it stops, and my site works.  So it seems to me that `fin up` is actually working, I'm just getting an output error.  The longest I have attempted to run this before aborting was 46 minutes.

**Steps to reproduce the issue:**

1. Setup a new project 
2. In docksal.env set `DOCKSAL_VOLUMES=unison`
3. Run `fin up`
4. Change any other setting in docksal.env
5. Run `fin up` again
6. See that the command runs forever

**Describe the results you received:**

`fin up` runs forever and never exits

**Describe the results you expected:**

`fin up` would exit after starting all containers

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: newell
COMPOSE_FILE:
/Users/matt/.docksal/stacks/volumes-unison.yml
/Users/matt/.docksal/stacks/stack-default.yml
/Users/matt/Sites/Newell/.docksal/docksal.yml
ENV_FILE:
/Users/matt/Sites/Newell/.docksal/docksal.env
/Users/matt/Sites/Newell/.docksal/docksal-local.env

PROJECT_ROOT: /Users/matt/Sites/Newell
DOCROOT: docroot
VIRTUAL_HOST: newell.docksal
VIRTUAL_HOST_ALIASES: *.newell.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32769

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      GIT_USER_EMAIL: null
      GIT_USER_NAME: null
      HOST_GID: '20'
      HOST_UID: '501'
      PHP_IDE_CONFIG: serverName=newell.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: newell.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.6-php7.1
    labels:
      io.docksal.virtual-host: react.newell.docksal
      io.docksal.virtual-port: '3000'
    ports:
    - 9001:9001/tcp
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: solr
    image: docksal/solr:1.0-solr4
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: solr.newell.docksal
      io.docksal.virtual-port: '8983'
    volumes:
    - project_root:/var/www:ro,nocopy
  unison:
    environment:
      SYNC_DESTINATION: /destination
      SYNC_MAX_INOTIFY_WATCHES: '524288'
      SYNC_NODELETE_SOURCE: '0'
      SYNC_PREFER: newer
      SYNC_VERBOSE: '1'
      UNISON_GID: '20'
      UNISON_UID: '501'
    image: docksal/unison
    privileged: true
    volumes:
    - project_root:/destination:rw
    - /Users/matt/Sites/Newell:/source:rw
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/matt/Sites/Newell
      io.docksal.virtual-host: newell.docksal,*.newell.docksal,newell.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root: {}
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.14.5
Darwin Matts-MBP.fios-router.home 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : /Users
NFS EXPORTS:

# <ds-nfs docksal
/Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.86.2

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:20:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.1
docker-machine version 0.16.1, build cce350d7

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.09.2   

███  DOCKSAL: PROJECTS
project             STATUS                   virtual host                                       project root
newell              Up 8 minutes (healthy)   newell.docksal,*.newell.docksal,newell.docksal.*   /Users/matt/Sites/Newell

███  DOCKSAL: VIRTUAL HOSTS
  ```

</details>

Possibly related to #486
