### ISSUE TITLE
global custom command not work on container

### ISSUE THREAD

**Issue by Flower7C3** [docksal/docksal#1091]
**Description**

Custom command with defined exec_target are not executed

**Steps to reproduce the issue:**

1. Copy example command from https://docs.docksal.io/fin/custom-commands/#target_cli
2. Save it as `~/.docksal/commands/foo`
3. Go to project and run `fin foo`

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/3767861/60256526-04a53200-98d2-11e9-8a28-ed178bd37219.png)

**Describe the results you expected:**

Show directory path from cli container.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: example
COMPOSE_FILE:
/Users/bartlomiej.kwiatek/.docksal/stacks/overrides-osxfs.yml
/Users/bartlomiej.kwiatek/.docksal/stacks/volumes-bind.yml
/Users/bartlomiej.kwiatek/.docksal/stacks/stack-default.yml
/Users/bartlomiej.kwiatek/Documents/example/.docksal/docksal.yml
ENV_FILE:
/Users/bartlomiej.kwiatek/Documents/example/.docksal/docksal.env

PROJECT_ROOT: /Users/bartlomiej.kwiatek/Documents/example
DOCROOT: docroot
VIRTUAL_HOST: example.docksal
VIRTUAL_HOST_ALIASES: *.example.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32776

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      GIT_USER_EMAIL: null
      GIT_USER_NAME: null
      HOST_GID: '20'
      HOST_UID: '501'
      PHP_IDE_CONFIG: serverName=example.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: example.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.6-php7.2
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /Users/bartlomiej.kwiatek/Documents/example:/var/www:rw,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/bartlomiej.kwiatek/Documents/example
      io.docksal.virtual-host: example.docksal,*.example.docksal,example.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/bartlomiej.kwiatek/Documents/example
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
fin sysinfo
███  OS
Darwin Mac OS X 10.14.5
Darwin KRKPC000011.pl.vml.lan 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.86.2

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKSAL: PROJECTS
project                       STATUS                       virtual host                                                                                                         project root
example                       Up 5 minutes (healthy)       example.docksal,*.example.docksal,example.docksal.*                                                                  /Users/bartlomiej.kwiatek/Documents/example

███  DOCKSAL: VIRTUAL HOSTS
*.example.docksal
example.docksal.*
example.docksal

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                       PORTS                                                    NAMES
a6fb0d9a21c4        docksal/apache:2.4-2.3            "httpd-foreground"       5 minutes ago       Up 5 minutes (healthy)       80/tcp, 443/tcp                                          example_web_1
200ef4a13162        docksal/cli:2.6-php7.2            "/opt/startup.sh sup…"   5 minutes ago       Up 5 minutes (healthy)       22/tcp, 3000/tcp, 9000/tcp                               example_cli_1
5c02ec22cbbc        docksal/mysql:5.6-1.4             "docker-entrypoint.s…"   5 minutes ago       Up 5 minutes (healthy)       0.0.0.0:32776->3306/tcp                                  example_db_1
718a3f17bca8        docksal/apache:2.4-2.3            "httpd-foreground"       7 days ago          Up 2 days (healthy)          80/tcp, 443/tcp                                          mercedes_actros_goldedition_web_1
ad0dccbe2784        docksal/ssh-agent:1.2             "docker-entrypoint.s…"   13 days ago         Up 10 days (healthy)                                                                  docksal-ssh-agent
3558d83725dc        docksal/dns:1.1                   "docker-entrypoint.s…"   13 days ago         Up 10 days (healthy)         192.168.64.100:53->53/udp                                docksal-dns
2db6cd2f1a18        docksal/vhost-proxy:1.5           "docker-entrypoint.s…"   13 days ago         Up 10 days (healthy)         192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
34bd9938f13b        docksal/apache:2.4-2.3            "httpd-foreground"       2 weeks ago         Up About an hour (healthy)   80/tcp, 443/tcp                                          fbtabpraca_vmlpoland_com_web_1
4cf2c757e563        docksal/mysql:5.6-1.4             "docker-entrypoint.s…"   2 weeks ago         Up About an hour (healthy)   0.0.0.0:32775->3306/tcp                                  fbtabpraca_vmlpoland_com_db_1
cb354586d96d        docksal/cli:2.5-php5.6            "/opt/startup.sh sup…"   2 weeks ago         Up About an hour (healthy)   22/tcp, 3000/tcp, 9000/tcp                               fbtabpraca_vmlpoland_com_cli_1
9d8723e7b747        docksal/web:2.1-apache2.4         "httpd-foreground"       5 weeks ago         Up 2 days                    80/tcp, 443/tcp                                          zywiec_zdroj_pl_web_1
69b226e25583        docksal/db:1.1-mysql-5.7          "/entrypoint.sh mysq…"   5 weeks ago         Up 2 days                    0.0.0.0:32774->3306/tcp                                  zywiec_zdroj_pl_db_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                                  DRIVER              SCOPE
c1dee24dcb78        _default                              bridge              local
11ebb82c3a1c        bridge                                bridge              local
5732cc35fbd9        example_default                       bridge              local
845cfa034e9a        host                                  host                local
b3529e112e7a        none                                  null                local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3
2.0.0.3

███  HDD Usage
Filesystem                                                                                                           Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1                                                                                                        466Gi  303Gi  158Gi    66% 6128779 9223372036848647028    0%   /
devfs                                                                                                               338Ki  338Ki    0Bi   100%    1170                   0  100%   /dev
/dev/disk1s4                                                                                                        466Gi  4.0Gi  158Gi     3%       6 9223372036854775801    0%   /private/var/vm
map -hosts                                                                                                            0Bi    0Bi    0Bi   100%       0                   0  100%   /net
map auto_home                                                                                                         0Bi    0Bi    0Bi   100%       0                   0  100%   /home


  ```

</details>
