### ISSUE TITLE
Behat scenarios tagged as @javascript fail on Digitalocean server

### ISSUE THREAD

**Issue by andrnimch** [docksal/docksal#1096]
I have created a website using the [`boilerplate-drupal7-advanced`](https://github.com/docksal/boilerplate-drupal7-advanced)  on the Digitalocean. The `base_url` setting was properly changed in the `behat.common.yml` file.

All scenarios are successful (`fin behat` command)  but for scenarios tagged as `@javascript`.

![Selection_197](https://user-images.githubusercontent.com/9386857/60822068-6eb0b780-a1ad-11e9-9f9a-12e42951509b.png)

At the same time, the heading `Welcome to My Drupal 7 Site` is present in the screenshot and on the page.

What problem can it be? Maybe the `wd_host` parameter?

**Output of `fin config`:**
```
---------------------
COMPOSE_PROJECT_NAME_SAFE: drupal7-advanced
COMPOSE_FILE:
/home/build/.docksal/stacks/volumes-bind.yml
/home/build/builds/drupal7-advanced/.docksal/docksal.yml
ENV_FILE:
/home/build/builds/drupal7-advanced/.docksal/docksal.env

PROJECT_ROOT: /home/build/builds/drupal7-advanced
DOCROOT: docroot
VIRTUAL_HOST: drupal7-advanced.188.166.8.36.sslip.io
VIRTUAL_HOST_ALIASES: *.drupal7-advanced.188.166.8.36.sslip.io
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  browser:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    hostname: browser
    image: selenium/standalone-chrome
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      GIT_USER_EMAIL: ''
      GIT_USER_NAME: ''
      HOST_GID: '1000'
      HOST_UID: '1000'
      PHP_IDE_CONFIG: serverName=drupal7-advanced.188.166.8.36.sslip.io
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: drupal7-advanced.188.166.8.36.sslip.io
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /home/build/builds/drupal7-advanced
      io.docksal.virtual-host: drupal7-advanced.188.166.8.36.sslip.io,*.drupal7-advanced.188.166.8.36.sslip.io,drupal7-advanced.188.166.8.36.sslip.io.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/build/builds/drupal7-advanced
      o: bind
      type: none

---------------------

```

**Output of `fin sysinfo`:**
```
███  OS
Linux Ubuntu 18.04
Linux itcross-builds 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST : 

███  FIN
fin version: 1.85.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

███  DOCKER
EXPECTED VERSION: 18.09.2

Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKSAL: PROJECTS
project             STATUS                   virtual host                                                                                                               project root
drupal7-advanced    Up 3 minutes (healthy)   drupal7-advanced.188.166.8.36.sslip.io,*.drupal7-advanced.188.166.8.36.sslip.io,drupal7-advanced.188.166.8.36.sslip.io.*   /home/build/builds/drupal7-advanced

███  DOCKSAL: VIRTUAL HOSTS
*.drupal7-advanced.188.166.8.36.sslip.io
drupal7-advanced.188.166.8.36.sslip.io.*
drupal7-advanced.188.166.8.36.sslip.io

███  DOCKSAL: DNS
curl: (6) Could not resolve host: dns-test.docksal
ERROR: Requesting http://dns-test.docksal failed!

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                       PORTS                                      NAMES
6b64c27370db        docksal/ssh-agent:1.2        "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)                                              docksal-ssh-agent
9ce7ef96d795        docksal/dns:1.1              "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)   192.168.64.100:53->53/udp                  docksal-dns
65e37398a385        docksal/vhost-proxy:1.5      "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy
cc4c5def0fc9        docksal/apache:2.4-2.3       "httpd-foreground"       2 days ago          Up 3 minutes (healthy)       80/tcp, 443/tcp                            drupal7-advanced_web_1
325004e6b786        docksal/cli:php7.1           "/opt/startup.sh sup…"   2 days ago          Up 3 minutes (healthy)       22/tcp, 3000/tcp, 9000/tcp                 drupal7-advanced_cli_1
242a0779d7e7        selenium/standalone-chrome   "/opt/bin/entry_poin…"   2 days ago          Up 3 minutes                 4444/tcp                                   drupal7-advanced_browser_1
23b5857e9a7b        docksal/mysql:5.6-1.4        "docker-entrypoint.s…"   2 days ago          Up 3 minutes (healthy)       0.0.0.0:32770->3306/tcp                    drupal7-advanced_db_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                       DRIVER              SCOPE
b651586ea24d        _default                   bridge              local
840b39beb7e3        bridge                     bridge              local
c148cf037a6e        drupal7-advanced_default   bridge              local
efe0e89440a3        host                       host                local
72db46750899        none                       null                local

███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G     0  2.0G   0% /dev
tmpfs           395M  1.1M  394M   1% /run
/dev/vda1        78G   20G   58G  26% /
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/vda15      105M  3.6M  101M   4% /boot/efi
tmpfs           395M     0  395M   0% /run/user/1000

```
