### ISSUE TITLE
How to specify hosts record

### ISSUE THREAD

**Issue by AndriySvirin** [docksal/docksal#1102]
Hi,
I do not know: how to specify hosts record.

I have added new map into /etc/hosts file in my parent system but inside the container i can not resolve the new domain entrance.

**Comment by achekulaev** [comment]
Containers cannot see or use custom records specified in the /etc/hosts on the host. You need to edit /etc/hosts inside the container.

**Comment by AndriySvirin** [comment]
ok, but if i loged in by fin bash command i have not permissions to edit hosts file inside container

**Comment by achekulaev** [comment]
sudo vim /etc/hosts

**Comment by AndriySvirin** [comment]
Found solution with add extra_hosts to web directive in docksal.env.

**Comment by achekulaev** [comment]
sharing your solution here might help others who will be looking for this in future

**Comment by mikispeed** [comment]
Had similar need recently and this is how to add entries to hosts file via `docksal.yml`:
```
version: "2.1"

services:
  # CLI
  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    extra_hosts:
      - "www.example.com:127.0.0.1"
      - "example.com:127.0.0.1"
```
