### ISSUE TITLE
Xdebug is not working in PHP 7.3

### ISSUE THREAD

**Issue by danielnv18** [docksal/docksal#1105]
**Description**

Xdebug is not working in PHP 7.3. It looks like there is a fix here https://github.com/docksal/service-cli/pull/127 but it needs a release. 

**Steps to reproduce the issue:**

1. Run `fin project create` and create a Drupal 8 composer version
2. Enable xdebug `fin config set XDEBUG_ENABLED=1`
3. Set PHP version to 7.3:  `fin config set CLI_IMAGE='docksal/cli:2.6-php7.3'`
4. Make sure that it is running php 7.3 and xdebug
5. Visit the site

I uploaded the result of those steps [here](https://github.com/danielnv18/docksal-php-version)

**Describe the results you received:**

When I try to visit any page, I get an 503 error - Service Unavailable

**Describe the results you expected:**

The site should work as usual with xdebug enable

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: php_testing
COMPOSE_FILE:
/Users/danielnv18/.docksal/stacks/overrides-osxfs.yml
/Users/danielnv18/.docksal/stacks/volumes-bind.yml
/Users/danielnv18/.docksal/stacks/stack-default.yml
/Users/danielnv18/Projects/examples/php_testing/.docksal/docksal.yml
ENV_FILE:
/Users/danielnv18/Projects/examples/php_testing/.docksal/docksal.env

PROJECT_ROOT: /Users/danielnv18/Projects/examples/php_testing
DOCROOT: web
VIRTUAL_HOST: php-testing.docksal
VIRTUAL_HOST_ALIASES: *.php-testing.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32787

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: web
      DRUSH_ALLOW_XDEBUG: '1'
      GIT_USER_EMAIL: null
      GIT_USER_NAME: null
      HOST_GID: '20'
      HOST_UID: '501'
      PHP_IDE_CONFIG: serverName=php-testing.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: php-testing.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.6-php7.3
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /Users/danielnv18/Projects/examples/php_testing:/var/www:rw,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/web
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/danielnv18/Projects/examples/php_testing
      io.docksal.virtual-host: php-testing.docksal,*.php-testing.docksal,php-testing.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/danielnv18/Projects/examples/php_testing
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.14.6
Darwin Daniels-MBP 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.86.2

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKSAL: PROJECTS
project             STATUS                   virtual host                                                      project root
php_testing         Up 6 minutes (healthy)   php-testing.docksal,*.php-testing.docksal,php-testing.docksal.*   /Users/danielnv18/Projects/examples/php_testing

███  DOCKSAL: VIRTUAL HOSTS
*.php-testing.docksal
php-testing.docksal.*
php-testing.docksal

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                                                                       NAMES
bd9aa7731336        docksal/apache:2.4-2.3    "httpd-foreground"       6 minutes ago       Up 6 minutes (healthy)    80/tcp, 443/tcp                                                                             php_testing_web_1
0c272518fd96        docksal/cli:2.6-php7.3    "/opt/startup.sh sup…"   6 minutes ago       Up 6 minutes (healthy)    22/tcp, 3000/tcp, 9000/tcp                                                                  php_testing_cli_1
87d402e349ec        docksal/mysql:5.6-1.4     "docker-entrypoint.s…"   40 minutes ago      Up 6 minutes (healthy)    0.0.0.0:32787->3306/tcp                                                                     php_testing_db_1
36c818ea4fd1        docksal/ssh-agent:1.2     "docker-entrypoint.s…"   40 minutes ago      Up 40 minutes (healthy)                                                                                               docksal-ssh-agent
eb5fe990f253        docksal/dns:1.1           "docker-entrypoint.s…"   40 minutes ago      Up 40 minutes (healthy)   192.168.64.100:53->53/udp                                                                   docksal-dns
79777373cf7b        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   40 minutes ago      Up 40 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp                                      docksal-vhost-proxy
4105ac74534b        traefik:1.6.3-alpine      "/lando-entrypoint.s…"   2 weeks ago         Up 26 hours               0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:32768->443/tcp, 0.0.0.0:58087->8080/tcp   landoproxyhyperion5000gandalfedition_proxy_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                                                                         DRIVER              SCOPE
05640ea44efe        _default                                                                     bridge              local
b5999175a5d1        bridge                                                                       bridge              local
39643021cc74        cms_default                                                                  bridge              local
66d791cf9ae7        host                                                                         host                local
1a0d66d30873        none                                                                         null                local
f2337d529453        php_testing_default                                                          bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3
2.0.0.3

███  HDD Usage
Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1   466Gi  215Gi  250Gi    47% 3200969 9223372036851574838    0%   /
devfs          188Ki  188Ki    0Bi   100%     650                   0  100%   /dev
/dev/disk1s4   466Gi   20Ki  250Gi     1%       0 9223372036854775807    0%   /private/var/vm
map -hosts       0Bi    0Bi    0Bi   100%       0                   0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0                   0  100%   /home
  ```

</details>
