### ISSUE TITLE
.docksal dns resolver not works

### ISSUE THREAD

**Issue by Flower7C3** [docksal/docksal#1109]
**Description**

Automatic .docksal DNS resolver not works.

**Steps to reproduce the issue:**

1. Create new project with `fin project create` command
2. Try top open its URL - not works
3. Add manually to /etc/hosts with `fin hosts add` and then open URL - it works

or

Connect to DNS via telnet `telnet 192.168.64.100 53`

**Describe the results you received:**

```
Trying 192.168.64.100...
telnet: Unable to connect to remote host: Connection refused
```

**Describe the results you expected:**

Resolve .docksal domains automatically.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: test
COMPOSE_FILE:
/Users/bartlomiej.kwiatek/.docksal/stacks/overrides-osxfs.yml
/Users/bartlomiej.kwiatek/.docksal/stacks/volumes-bind.yml
/Users/bartlomiej.kwiatek/.docksal/stacks/stack-default-nodb.yml
/Users/bartlomiej.kwiatek/Desktop/test/.docksal/docksal.yml
ENV_FILE:
/Users/bartlomiej.kwiatek/Desktop/test/.docksal/docksal.env

PROJECT_ROOT: /Users/bartlomiej.kwiatek/Desktop/test
DOCROOT: docroot
VIRTUAL_HOST: test.docksal
VIRTUAL_HOST_ALIASES: *.test.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      GIT_USER_EMAIL: null
      GIT_USER_NAME: null
      HOST_GID: '20'
      HOST_UID: '501'
      PHP_IDE_CONFIG: serverName=test.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: test.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.6-php7.2
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /Users/bartlomiej.kwiatek/Desktop/test:/var/www:rw,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/bartlomiej.kwiatek/Desktop/test
      io.docksal.virtual-host: test.docksal,*.test.docksal,test.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/bartlomiej.kwiatek/Desktop/test
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
 fin sysinfo
███  OS
Darwin Mac OS X 10.14.5
Darwin KRKPC000011.pl.vml.lan 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.86.2

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
project             STATUS                   virtual host                                                                  project root
test                Up 8 minutes (healthy)   test.docksal,*.test.docksal,test.docksal.*                                    /Users/bartlomiej.kwiatek/Desktop/test
zywiec_zdroj_pl     Up About an hour         zywiec-zdroj-pl.docksal,*.zywiec-zdroj-pl.docksal,zywiec-zdroj-pl.docksal.*   /Users/bartlomiej.kwiatek/www/domains/zywiec_zdroj_pl

███  DOCKSAL: VIRTUAL HOSTS
*.test.docksal
test.docksal.*
test.docksal

███  DOCKSAL: DNS
curl: (28) Resolving timed out after 2519 milliseconds
ERROR: Requesting http://dns-test.docksal failed!

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                       PORTS                                                    NAMES
7255bbce123c        docksal/dns:1.1             "docker-entrypoint.s…"   5 minutes ago       Up 4 minutes (healthy)       192.168.64.100:53->53/udp                                docksal-dns
276f81ecbff9        docksal/ssh-agent:1.2       "docker-entrypoint.s…"   6 minutes ago       Up 6 minutes (healthy)                                                                docksal-ssh-agent
8d7329cab65c        docksal/vhost-proxy:1.5     "docker-entrypoint.s…"   6 minutes ago       Up 6 minutes (healthy)       192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
20a788698edf        docksal/apache:2.4-2.3      "httpd-foreground"       9 minutes ago       Up 9 minutes (healthy)       80/tcp, 443/tcp                                          test_web_1
64b1f9001003        docksal/cli:2.6-php7.2      "/opt/startup.sh sup…"   9 minutes ago       Up 9 minutes (healthy)       22/tcp, 3000/tcp, 9000/tcp                               test_cli_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                                  DRIVER              SCOPE
c1dee24dcb78        _default                              bridge              local
7ff58063b643        bridge                                bridge              local
5ca5d15f1008        domains_default                       bridge              local
845cfa034e9a        host                                  host                local
b3529e112e7a        none                                  null                local
c91cd0fb1a2c        test_default                          bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3
2.1.0.0

███  HDD Usage
Filesystem                                                                                                           Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1                                                                                                        466Gi  250Gi  212Gi    55% 4860667 9223372036849915140    0%   /
devfs                                                                                                               334Ki  334Ki    0Bi   100%    1154                   0  100%   /dev
/dev/disk1s4                                                                                                        466Gi  3.0Gi  212Gi     2%       5 9223372036854775802    0%   /private/var/vm
map -hosts                                                                                                            0Bi    0Bi    0Bi   100%       0                   0  100%   /net
map auto_home                                                                                                         0Bi    0Bi    0Bi   100%       0                   0  100%   /home
  ```

</details>
