### ISSUE TITLE
Unable to pull PHP 7.3

### ISSUE THREAD

**Issue by Flower7C3** [docksal/docksal#1111]
**Description**

I am unable to create new project with PHP 7.3

**Steps to reproduce the issue:**

1. Create project `fin project create`
2. Set PHP version to 7.3 `fin config set CLI_IMAGE='docksal/cli:2.6-php7.3'`
3. Try start docksal with `fin start`

**Describe the results you received:**

```
$ fin start

Key 'id_rsa' already loaded in the agent. Skipping.
Starting services...
Pulling cli (docksal/cli:2.6-php7.3)...
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1080, in up
  File "compose/cli/main.py", line 1076, in up
  File "compose/project.py", line 475, in up
  File "compose/service.py", line 352, in ensure_image_exists
  File "compose/service.py", line 1217, in pull
  File "compose/progress_stream.py", line 101, in get_digest_from_pull
  File "compose/service.py", line 1182, in _do_pull
  File "site-packages/docker/api/image.py", line 381, in pull
  File "site-packages/docker/auth.py", line 48, in get_config_header
  File "site-packages/docker/auth.py", line 96, in resolve_authconfig
  File "site-packages/docker/auth.py", line 127, in _resolve_authconfig_credstore
  File "site-packages/dockerpycreds/store.py", line 25, in __init__
dockerpycreds.errors.InitializationError: docker-credential-desktop not installed or not available in PATH
[48612] Failed to execute script docker-compose
```

**Describe the results you expected:**

Download image.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: test
COMPOSE_FILE:
/Users/bartlomiej.kwiatek/.docksal/stacks/overrides-osxfs.yml
/Users/bartlomiej.kwiatek/.docksal/stacks/volumes-bind.yml
/Users/bartlomiej.kwiatek/.docksal/stacks/stack-default-nodb.yml
/Users/bartlomiej.kwiatek/Desktop/test/.docksal/docksal.yml
ENV_FILE:
/Users/bartlomiej.kwiatek/Desktop/test/.docksal/docksal.env

PROJECT_ROOT: /Users/bartlomiej.kwiatek/Desktop/test
DOCROOT: docroot
VIRTUAL_HOST: test.docksal
VIRTUAL_HOST_ALIASES: *.test.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      GIT_USER_EMAIL: null
      GIT_USER_NAME: null
      HOST_GID: '20'
      HOST_UID: '501'
      PHP_IDE_CONFIG: serverName=test.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: test.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.6-php7.3
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /Users/bartlomiej.kwiatek/Desktop/test:/var/www:rw,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/bartlomiej.kwiatek/Desktop/test
      io.docksal.virtual-host: test.docksal,*.test.docksal,test.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/bartlomiej.kwiatek/Desktop/test
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
 fin sysinfo output
███  OS
Darwin Mac OS X 10.14.5
Darwin KRKPC000011.pl.vml.lan 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.86.2

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                  PORTS                                                    NAMES
046d4f2ce52d        docksal/dns:1.1           "docker-entrypoint.s…"   47 hours ago        Up 45 hours (healthy)   192.168.64.100:53->53/udp                                docksal-dns
276f81ecbff9        docksal/ssh-agent:1.2     "docker-entrypoint.s…"   47 hours ago        Up 45 hours (healthy)                                                            docksal-ssh-agent
8d7329cab65c        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   47 hours ago        Up 45 hours (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                                  DRIVER              SCOPE
c1dee24dcb78        _default                              bridge              local
9f004caef6ef        bridge                                bridge              local
845cfa034e9a        host                                  host                local
b3529e112e7a        none                                  null                local
95cce36c9610        test_default                          bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3
2.0.0.3

███  HDD Usage
Filesystem                                                                                                           Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1                                                                                                        466Gi  254Gi  208Gi    55% 4866642 9223372036849909165    0%   /
devfs                                                                                                               333Ki  333Ki    0Bi   100%    1152                   0  100%   /dev
/dev/disk1s4                                                                                                        466Gi  3.0Gi  208Gi     2%       5 9223372036854775802    0%   /private/var/vm
map -hosts                                                                                                            0Bi    0Bi    0Bi   100%       0                   0  100%   /net
map auto_home                                                                                                         0Bi    0Bi    0Bi   100%       0                   0  100%   /home
  ```

</details>
