### ISSUE TITLE
docksal not working anymore after docker update

### ISSUE THREAD

**Issue by renatoniola** [docksal/docksal#1112]
Hi there,

my issue is that I had a working installation of a docksal website , but after an update to a new version of docker ( 2.0.0.1 -> 2.1.0.0) and after updating docksal as well, the site , which is a local site for testing purpose is not working anymore.

I get a : This site can’t be reached page 

in the project I left the same configuration I had before the update

<details>
  <summary>fin config output</summary>

```
COMPOSE_PROJECT_NAME_SAFE: companynl
COMPOSE_FILE:
/Users/mynameatcompany/.docksal/stacks/overrides-osxfs.yml
/Users/mynameatcompany/.docksal/stacks/volumes-bind.yml
/Users/mynameatcompany/.docksal/stacks/stack-default.yml
/Users/mynameatcompany/Desktop/company_projects/company.nl/.docksal/docksal.yml
/Users/mynameatcompany/Desktop/company_projects/company.nl/.docksal/docksal-local.yml
ENV_FILE:
/Users/mynameatcompany/Desktop/company_projects/company.nl/.docksal/docksal.env

PROJECT_ROOT: /Users/mynameatcompany/Desktop/company_projects/company.nl
DOCROOT: docroot
VIRTUAL_HOST: companynl.docksal
VIRTUAL_HOST_ALIASES: *.companynl.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32772

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      GIT_USER_EMAIL: null
      GIT_USER_NAME: null
      HOST_GID: '20'
      HOST_UID: '501'
      PHP_IDE_CONFIG: serverName=companynl.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: companynl.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.2-php7.1
    ports:
    - 2222:22/tcp
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /Users/mynameatcompany/Desktop/company_projects/company.nl:/var/www:rw,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: drupal_db
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: DontLookAtThis
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
    hostname: db
    image: docksal/db:1.1-mysql-5.7
    ports:
    - 0:3306/tcp
    volumes:
    - /Users/mynameatcompany/Desktop/company_projects/company.nl/db:/docker-entrypoint-initdb.d:ro
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/mynameatcompany/Desktop/company_projects/company.nl
      io.docksal.virtual-host: companynl.docksal,*.companynl.docksal,companynl.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/mynameatcompany/Desktop/company_projects/company.nl
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  ███  OS
Darwin Mac OS X 10.13.6
Darwin MacBook-Pro-van-myname.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.86.2

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                             project root
companynl            Up 13 minutes       companynl.docksal,*.companynl.docksal,companynl.docksal.*   /Users/mynameatcompany/Desktop/company_projects/company.nl

███  DOCKSAL: VIRTUAL HOSTS
*.companynl.docksal
companynl.docksal.*
companynl.docksal

███  DOCKSAL: DNS
curl: (28) Resolving timed out after 2526 milliseconds
ERROR: Requesting http://dns-test.docksal failed!

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
b160c0d23b37        docksal/ssh-agent:1.2       "docker-entrypoint.s…"   14 minutes ago      Up 14 minutes (healthy)                                                            docksal-ssh-agent
750873416cc6        docksal/vhost-proxy:1.5     "docker-entrypoint.s…"   14 minutes ago      Up 14 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
53f7ddde924b        docksal/dns:1.1             "docker-entrypoint.s…"   16 minutes ago      Up 16 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
c18337b3e597        docksal/web:2.1-apache2.4   "httpd-foreground"       42 minutes ago      Up 13 minutes             80/tcp, 443/tcp                                          companynl_web_1
1a1b5f285b79        docksal/cli:2.2-php7.1      "/opt/startup.sh sup…"   42 minutes ago      Up 13 minutes (healthy)   3000/tcp, 9000/tcp, 0.0.0.0:2222->22/tcp                 companynl_cli_1
c412b31965aa        docksal/db:1.1-mysql-5.7    "/entrypoint.sh mysq…"   42 minutes ago      Up 13 minutes             0.0.0.0:32772->3306/tcp                                  companynl_db_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                        DRIVER              SCOPE
50d1b9b7fb32        _default                    bridge              local
5f300dccb71a        bridge                      bridge              local
2c3c5718ecd5        companycom-website_default   bridge              local
99a58870518f        companynl-new_default        bridge              local
de74f1c5f04d        companynl_default            bridge              local
f0e77c39d530        host                        host                local
50d936859078        none                        null                local
535879a643cd        test_default                bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3
2.1.0.0

███  HDD Usage
Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1   234Gi  195Gi   36Gi    85% 3892102 9223372036850883705    0%   /
devfs          186Ki  186Ki    0Bi   100%     644                   0  100%   /dev
/dev/disk1s4   234Gi  2.0Gi   36Gi     6%       2 9223372036854775805    0%   /private/var/vm
map -hosts       0Bi    0Bi    0Bi   100%       0                   0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0                   0  100%   /home
  ```

</details>
