### ISSUE TITLE
Adding an additional host to nxing 

### ISSUE THREAD

**Issue by ArtuGit** [docksal/docksal#1120]
I would like to have an additional host for BackStopJS report.

I have brought nxginx to Docksal:
```
  # Web: Nginx
  nginx:
    hostname: web
    image: ${WEB_IMAGE:-docksal/nginx:1.14-1.0}
    volumes:
      - project_root:/var/www:ro,nocopy  # Project root volume (read-only)
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST},*.${VIRTUAL_HOST},${VIRTUAL_HOST}.*
      - io.docksal.cert-name=${VIRTUAL_HOST_CERT_NAME:-none}
      - io.docksal.project-root=${PROJECT_ROOT}
      - io.docksal.permanent=${SANDBOX_PERMANENT:-false}
    environment:
      - NGINX_VHOST_PRESET=drupal
      - NGINX_FCGI_HOST_PORT=cli:9000
      - NGINX_SERVER_ROOT=/var/www/${DOCROOT}
      - NGINX_BASIC_AUTH_USER
      - NGINX_BASIC_AUTH_PASS
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
```

`myproject.docksal` is ok.

I have added `.docksal/etc/nginx/vhosts.conf` according to https://github.com/docksal/service-nginx#configuration-overrides
 
```vhosts.conf
server
{
    listen 80;
    server_name backstop.myproject.docksal;
    root /var/www/tests/backstop/backstop_data/html_report;
    index index.html;
}
```
then `fin project reset nginx`. 

On `backstop.myproject.docksal` I have the main project without CSS.
