### ISSUE TITLE
Problem with Mariadb image

### ISSUE THREAD

**Issue by andrnimch** [docksal/docksal#1123]
I need to use the `docksal/mariabdb:10.2` image in the project. 

When I add:
```
db:
    hostname: db
    image: ${DB_IMAGE:-docksal/mariadb:10.2}
    ports:
    - "${MYSQL_PORT_MAPPING:-3306}"
    volumes:
    - project_root:/var/www:ro,nocopy  # Project root volume (read-only)
    - db_data:/var/lib/mysql  # Database data volume
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    - MYSQL_USER=${MYSQL_USER:-user}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user}
    - MYSQL_DATABASE=${MYSQL_DATABASE:-default}
    - MYSQL_ALLOW_EMPTY_PASSWORD
    - MYSQL_RANDOM_ROOT_PASSWORD
    - MYSQL_ONETIME_PASSWORD
    - MYSQL_INITDB_SKIP_TZINFO
    dns:
    - ${DOCKSAL_DNS1}
    - ${DOCKSAL_DNS2}
```
It creates container but i get `ERROR 2013 (HY000) at line 22: Lost connection to MySQL server during query` error.

At the same time this works fine with the string ` image: ${DB_IMAGE:-docksal/mariadb:10.3-1.0}`:
```
db:
    hostname: db
    image: ${DB_IMAGE:-docksal/mariadb:10.3-1.0}
    ports:
    - "${MYSQL_PORT_MAPPING:-3306}"
    volumes:
    - project_root:/var/www:ro,nocopy  # Project root volume (read-only)
    - db_data:/var/lib/mysql  # Database data volume
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    - MYSQL_USER=${MYSQL_USER:-user}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user}
    - MYSQL_DATABASE=${MYSQL_DATABASE:-default}
    - MYSQL_ALLOW_EMPTY_PASSWORD
    - MYSQL_RANDOM_ROOT_PASSWORD
    - MYSQL_ONETIME_PASSWORD
    - MYSQL_INITDB_SKIP_TZINFO
    dns:
    - ${DOCKSAL_DNS1}
    - ${DOCKSAL_DNS2}
```
These strings are added from the `${HOME}/.docksal/stacks/services.yml` file. Is it possible to use the `docksal/mariabdb:10.2` image?
