### ISSUE TITLE
Elasticsearch doesn't work

### ISSUE THREAD

**Issue by drubage** [docksal/docksal#1132]
**Description**

I am following these instructions but elasticsearch service will not start:

https://docs.docksal.io/tools/elasticsearch/

**Steps to reproduce the issue:**

1. Set up a basic Docksal project with elasticseach added per https://docs.docksal.io/tools/elasticsearch/
2. fin up
3. See that elasticsearch fails:

xxxxxxxx_elasticsearch_1   /usr/local/bin/docker-entr ...   Exit 78   

**Describe the results you received:**

Elasticsearch won't run.

**Describe the results you expected:**

A working elasticsearch service.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: xxxxxxxx
COMPOSE_FILE:
/Users/drewmichael/.docksal/stacks/volumes-bind.yml
/Users/drewmichael/.docksal/stacks/stack-default.yml
/Users/drewmichael/projects/xxxxxxxx/.docksal/docksal.yml
ENV_FILE:
/Users/drewmichael/projects/xxxxxxxx/.docksal/docksal.env
/Users/drewmichael/projects/xxxxxxxx/.docksal/docksal-local.env

PROJECT_ROOT: /Users/drewmichael/projects/xxxxxxxx
DOCROOT: docroot
VIRTUAL_HOST: xxxxxxxx.docksal
VIRTUAL_HOST_ALIASES: *.xxxxxxxx.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32809

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DB_DATABASE: default
      DB_HOST: db
      DB_PASSWORD: user
      DB_PREFIX: ''
      DB_USER: user
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '1'
      ENVIRONMENT: DOCKSAL
      GIT_USER_EMAIL: null
      GIT_USER_NAME: null
      HOST_GID: '20'
      HOST_UID: '502'
      PHP_IDE_CONFIG: serverName=xxxxxxxx.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: xxxxxxxx.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.6-php7.2
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  elasticsearch:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      bootstrap.memory_lock: "true"
    hostname: elasticsearch
    image: elasticsearch:6.5.3
    ports:
    - 9200/tcp
    ulimits:
      memlock:
        hard: -1
        soft: -1
  mail:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: mail.xxxxxxxx.docksal,mail.xxxxxxxx.docksal.*
      io.docksal.virtual-port: '8025'
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/drewmichael/projects/xxxxxxxx
      io.docksal.virtual-host: xxxxxxxx.docksal,*.xxxxxxxx.docksal,xxxxxxxx.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/drewmichael/projects/xxxxxxxx
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.14.5
Darwin Drews-MacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : /Users
NFS EXPORTS:

# <ds-nfs docksal
/Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.86.2

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:20:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.1
docker-machine version 0.16.1, build cce350d7

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.09.2   

███  DOCKSAL: PROJECTS
project             STATUS                        virtual host                                                                        project root
xxxxxxxx   Up About a minute (healthy)   xxxxxxxx.docksal,*.xxxxxxxx.docksal,xxxxxxxx.docksal.*   /Users/drewmichael/projects/xxxxxxxx

███  DOCKSAL: VIRTUAL HOSTS
*.xxxxxxxx.docksal
mail.xxxxxxxx.docksal.*
mail.xxxxxxxx.docksal
xxxxxxxx.docksal.*
xxxxxxxx.docksal

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                        PORTS                                                    NAMES
1a23dfc5bd00        docksal/apache:2.4-2.3    "httpd-foreground"       3 minutes ago       Up About a minute (healthy)   80/tcp, 443/tcp                                          xxxxxxxx_web_1
3ec6df3ff5b0        docksal/cli:2.6-php7.2    "/opt/startup.sh sup…"   3 minutes ago       Up About a minute (healthy)   22/tcp, 3000/tcp, 9000/tcp                               xxxxxxxx_cli_1
2ac3896e6a1d        mailhog/mailhog           "MailHog"                2 days ago          Up About a minute             1025/tcp, 8025/tcp                                       xxxxxxxx_mail_1
921d9e077d91        docksal/mysql:5.6-1.4     "docker-entrypoint.s…"   2 days ago          Up About a minute (healthy)   0.0.0.0:32809->3306/tcp                                  xxxxxxxx_db_1
9bf20b83bc5f        docksal/ssh-agent:1.2     "docker-entrypoint.s…"   5 days ago          Up 5 days (healthy)                                                                    docksal-ssh-agent
d30945c9ad7d        docksal/dns:1.1           "docker-entrypoint.s…"   5 days ago          Up 5 days (healthy)           192.168.64.100:53->53/udp                                docksal-dns
f79054d7eff3        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   5 days ago          Up 5 days (healthy)           192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
b953991bc735        blackfire/blackfire       "blackfire-agent"        3 months ago        Up 2 days                                                                              golfzing_blackfire_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                                  DRIVER              SCOPE
d086a8bb4f28        _default                              bridge              local
39261a0a15de        agc-reserve_default                   bridge              local
f0f3a378463f        bridge                                bridge              local
df9d45d6f3e7        host                                  host                local
a4e9134601f9        none                                  null                local
aa5669af5671        xxxxxxxx_default             bridge              local
9eff38259ce5        ontario-d8_default                    bridge              local
695ba48fea2c        ontario-wordpress-multisite_default   bridge              local
be0aa28d82ae        resilience-fruition_default           bridge              local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.26
6.0.0r127566

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.64.1,mountvers=3,mountport=716,mountproto=udp,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/drewmichael/projects/xxxxxxxx on /mnt/sda1/var/lib/docker/volumes/xxxxxxxx_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.64.1,mountvers=3,mountport=716,mountproto=udp,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                74.2G     62.2G      8.2G  88% /mnt/sda1
  ```

</details>
