### ISSUE TITLE
Use docksal/cli image in Bitbucket Pipelines

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#1133]
Howdy gents,

I'm testing a Bitbucket pipelines file with the following configuration:

```
image:
  name: docksal/cli:2.6-php7.2

pipelines:
  branches:
    develop:
      - step:
          script:
            - whoami
            - npm ci
            - npx gulp build
```

When it runs, the output from whoami shows root and then npm isn't found (because it's running as root, and not docker). So, I'm trying to get it to run as the docker user.

Have you successfully used this image directly in pipelines before? If so, how did you do it? I tried following the steps for overriding the default user of an image [here](https://confluence.atlassian.com/bitbucket/use-docker-images-as-build-environments-792298897.html), but was met without success.

**Comment by lmakarov** [comment]
@lpeabody internally, we don't use `docksal/cli` as the build environment image. We use https://github.com/docksal/ci-agent instead with a sandbox server. The agent provisions the codebase on the sandbox server, runs `fin init`/etc. As the result, everything acts the same way as on your local (using the same project stack).

`docksal/cli` is a heavy weight image. In CI, you can use images tailored for a specific purpose instead. For `npm` tasks you can use the official `node` image.

Another problem with using `docksal/cli` with Bitbucket Pipelines specifically is the way BBP starts containers - it overrides the image entrypoint and thus any initialization logic built into the image. You then have to trigger it manually as the first step in the build.

**Comment by lpeabody** [comment]
@lmakarov yeah it is kinda heavyweight, I just like the idea of using the "same image everywhere", but I'm coming around on the notion of using tailor-built images for CI-purposes.

I was able to work around the issue of BPP overriding the entry point with the following bitbucket-pipelines.yml.

```
image:
  name: docksal/cli:2.6-php7.2
  run-as-user: 1000

pipelines:
  branches:
    develop:
      - step:
          script:
            - . ~/.profile
            - npm ci
            - composer install
            - npx gulp build
```

The trick was figuring out what that run-as-user id should be, and then knowing to source ~/.profile. I had to include `id -u docker` in the script at one point to see the id of the docker user of the container in the BPP environment, it turned out to be the default of 1000 but I wanted to make sure since that value is different on multiple of my colleague's systems.

Anyway, not sure if this is documentation worthy, maybe though? I leave that up to the fine Docksal maintainer folk :)
