### ISSUE TITLE
OSX - issue if the containing folder has a space in the name

### ISSUE THREAD

**Issue by liezie** [docksal/docksal#1134]
I have 2 docksal projects.  My folder structure is like this:
/Users/username/Development/Company Projects/project1
/Users/username/Development/Company Projects/project2

(where username is my username, company the name of the place where i work)

when i start the docksal system and project on the first project, there is no issue.
when i then try to start the second project, i get errors: 

Another project is already using the name 'company'
        Change the name of the current project by renaming the project folder (folder name defines the project name and has to be unique)
        or remove the other project's stack by running fin project remove in /Users/username/Development/Company

When I then do "fin ps" on the first project, i get the exact same error. 

As you can see, in the error, it only mentions part of the folder name.  It mentions Company instead of Company Projects. 

I can fix it by doing "fin cleanup" but it breaks immediately when I do "fin ps".  

**Steps to reproduce the issue:**
1. put 2 project folders in a containing folder with a space in the foldername on OSX
2. start the first project
3. start the second project
4. do "fin ps"

**Describe the results you received:**

Another project is already using the name 'company'
        Change the name of the current project by renaming the project folder (folder name defines the project name and has to be unique)
        or remove the other project's stack by running fin project remove in /Users/username/Development/Company

**Describe the results you expected:**

no error :)

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
COMPOSE_PROJECT_NAME_SAFE: Company
COMPOSE_FILE:
/Users/username/.docksal/stacks/volumes-bind.yml
/Users/username/.docksal/stacks/stack-default.yml
/Users/username/Development/Company Projects/project1/.docksal/docksal.yml
ENV_FILE:
/Users/username/Development/Company Projects/project1/.docksal/docksal.env

PROJECT_ROOT: /Users/username/Development/Company Projects/project1
DOCROOT: web
VIRTUAL_HOST: Company.docksal
VIRTUAL_HOST_ALIASES: *.Company.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: web
      DRUSH_ALLOW_XDEBUG: '0'
      GIT_USER_EMAIL: null
      GIT_USER_NAME: null
      HOST_GID: '20'
      HOST_UID: '501'
      PHP_IDE_CONFIG: serverName=Company.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: Company.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.6-php7.2
    ports:
    - 3000:3000/tcp
    - 3001:3001/tcp
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: docksal
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: docksal
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docksal
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  mail:
    dns:
    - 8.8.8.8
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: mail.Company.docksal,mail.Company.docksal.*
      io.docksal.virtual-port: '8025'
    volumes:
    - project_root:/var/www:ro,nocopy
  solr:
    image: solr:5.5-alpine
    ports:
    - 8983:8983/tcp
    volumes:
    - /Users/username/Development/Company Projects/project1/.docksal/etc/solr/conf:/opt/solr/server/solr/conf:ro
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/web
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/username/Development/Company Projects/project1
      io.docksal.virtual-host: Company.docksal,*.Company.docksal,Company.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/username/Development/Company Projects/project2
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.14.5
Darwin blabla.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://x.x.x.x:2376
DOCKSAL_NFS_PATH : /Users
NFS EXPORTS:

# <ds-nfs docksal
/Users x.x.x.1 x.x.x.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.86.2

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:20:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.1
docker-machine version 0.16.1, build cce350d7

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
docksal   *        virtualbox   Running   tcp://x.x.x.100:2376           v18.09.2   

███  DOCKSAL: PROJECTS
project             STATUS                    virtual host                                          project root
Company             Up 16 minutes (healthy)   Company.docksal,*.Company.docksal,Company.docksal.*   /Users/username/Development/Company Projects/project1

███  DOCKSAL: VIRTUAL HOSTS
*.Company.docksal
Company.docksal.*
Company.docksal
mail.Company.docksal.*
mail.Company.docksal

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
392ce76cdf84        docksal/apache:2.4-2.3    "httpd-foreground"       16 minutes ago      Up 16 minutes (healthy)   80/tcp, 443/tcp                                          Company_web_1
96620addf707        docksal/cli:2.6-php7.2    "/opt/startup.sh sup…"   16 minutes ago      Up 16 minutes (healthy)   22/tcp, 9000/tcp, 0.0.0.0:3000-3001->3000-3001/tcp       Company_cli_1
4e82f379cd83        docksal/mysql:5.6-1.4     "docker-entrypoint.s…"   16 minutes ago      Up 16 minutes (healthy)   0.0.0.0:32768->3306/tcp                                  Company_db_1
c964aaf84e83        solr:5.5-alpine           "docker-entrypoint.s…"   16 minutes ago      Up 16 minutes             0.0.0.0:8983->8983/tcp                                   Company_solr_1
38e4bf1bd9f7        mailhog/mailhog           "MailHog"                16 minutes ago      Up 16 minutes             1025/tcp, 8025/tcp                                       Company_mail_1
0aeaf9a50150        docksal/ssh-agent:1.2     "docker-entrypoint.s…"   17 minutes ago      Up 17 minutes (healthy)                                                            docksal-ssh-agent
5e38c26443e9        docksal/dns:1.1           "docker-entrypoint.s…"   17 minutes ago      Up 17 minutes (healthy)   x.x.x.100:53->53/udp                                docksal-dns
307817a0135d        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   17 minutes ago      Up 17 minutes (healthy)   x.x.x.100:80->80/tcp, x.x.x.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
c99d46f878d1        _default            bridge              local
728c174e30a2        bridge              bridge              local
1a853015942d        host                host                local
0fc3946dea56        Company_default     bridge              local
45afe4f54b56        none                null                local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.26
6.0.12r133076

███  DOCKSAL MOUNTS
x.x.x.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=x.x.x.1,mountvers=3,mountport=856,mountproto=udp,local_lock=all,addr=x.x.x.1)
x.x.x.1:/Users/username/Development/Company Projects/project1 on /mnt/sda1/var/lib/docker/volumes/Company_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=x.x.x.1,mountvers=3,mountport=856,mountproto=udp,local_lock=all,addr=x.x.x.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G      2.3G     41.4G   5% /mnt/sda1


  ```

</details>
