### ISSUE TITLE
Docksal requires server version 19.03.4, but fin update updated to version 19.03.5

### ISSUE THREAD

**Issue by TrevorBradleyCDN** [docksal/docksal#1244]
**Description**

Docksal requires server version 19.03.4, but fin update updated to version 19.03.5

**Steps to reproduce the issue:**

1.  run "fin update"

**Describe the results you received:**

fin attempts to update to the latest version (19.03.5)
after fin update, see message "ALERT:  Required Docker server version is 19.03.4"

**Describe the results you expected:**

docksal should either forbid update to 19.03.5, or change requirements as to which version should be running.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
(release/0.8.0 $=) trevor@lowell:~/docksal/qciw$ fin config
 ALERT:  Required Docker server version is 19.03.4
         Run fin update to update to the required version.
          
---------------------
COMPOSE_PROJECT_NAME_SAFE: qciw
COMPOSE_FILE:
/home/trevor/.docksal/stacks/volumes-bind.yml
/home/trevor/.docksal/stacks/stack-default.yml
/home/trevor/docksal/qciw/.docksal/docksal.yml
ENV_FILE:
/home/trevor/docksal/qciw/.docksal/docksal.env

PROJECT_ROOT: /home/trevor/docksal/qciw
DOCROOT: build/html
VIRTUAL_HOST: qciw.docksal
VIRTUAL_HOST_ALIASES: *.qciw.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '1'
      COMPOSER_DISABLE_XDEBUG_WARN: '1'
      DOCROOT: build/html
      DRUSH_ALLOW_XDEBUG: '1'
      DRUSH_OPTIONS_URI: qciw.docksal
      GIT_USER_EMAIL: trevor@digilynx.com
      GIT_USER_NAME: Trevor Bradley
      HOST_GID: '1000'
      HOST_UID: '1000'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: serverName=qciw.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: qciw.docksal
      XDEBUG_CONFIG: remote_host=192.168.64.1 remote_port=9000
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.10-php7.3
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 3306/tcp
    volumes:
    - /home/trevor/docksal/qciw/build/backups:/docker-entrypoint-initdb.d:ro
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: solr
    image: solr:8.1
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: solr.qciw.docksal,solr.qciw.docksal.*
      io.docksal.virtual-port: '8983'
    volumes:
    - /home/trevor/docksal/qciw/env/solr/cores/qciw:/var/solr/data/cores/qciw:rw
    - /home/trevor/docksal/qciw/env/solr/data/qciw:/var/solr/data/data/qciw:rw
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/build/html
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /home/trevor/docksal/qciw
      io.docksal.virtual-host: qciw.docksal,*.qciw.docksal,qciw.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/trevor/docksal/qciw
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
(release/0.8.0 $=) trevor@lowell:~/docksal/qciw$ fin sysinfo
███  OS
Linux Ubuntu 18.04
Linux lowell 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST : 

███  FIN
fin version: 1.92.2

███  DOCKER COMPOSE
EXPECTED VERSION: 1.24.1
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

███  DOCKER
EXPECTED VERSION: 19.03.4

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKSAL: PROJECTS
 ALERT:  Required Docker server version is 19.03.4
         Run fin update to update to the required version.
          
project             STATUS                       virtual host                                 project root
qciw                Up About an hour (healthy)   qciw.docksal,*.qciw.docksal,qciw.docksal.*   /home/trevor/docksal/qciw

███  DOCKSAL: VIRTUAL HOSTS
*.qciw.docksal
qciw.docksal.*
qciw.docksal
solr.qciw.docksal.*
solr.qciw.docksal

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                       PORTS                                                    NAMES
d806bb071601        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   47 minutes ago      Up About an hour (healthy)                                                            docksal-ssh-agent
3cd9b18db812        docksal/dns:1.1           "docker-entrypoint.s…"   47 minutes ago      Up About an hour (healthy)   192.168.64.100:53->53/udp                                docksal-dns
4116a61e4fbb        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   47 minutes ago      Up About an hour (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
c1111a478797        docksal/apache:2.4-2.3    "httpd-foreground"       49 minutes ago      Up About an hour (healthy)   80/tcp, 443/tcp                                          qciw_web_1
7397e2b25704        docksal/cli:2.10-php7.3   "/opt/startup.sh sup…"   49 minutes ago      Up About an hour (healthy)   22/tcp, 3000/tcp, 9000/tcp                               qciw_cli_1
930bddb86d5d        solr:8.1                  "docker-entrypoint.s…"   49 minutes ago      Up About an hour             8983/tcp                                                 qciw_solr_1
ca9286639dbe        docksal/mysql:5.6-1.4     "docker-entrypoint.s…"   49 minutes ago      Up About an hour (healthy)   0.0.0.0:32768->3306/tcp                                  qciw_db_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
d1001d66e0c6        _default            bridge              local
1bc877285aea        bridge              bridge              local
899b1d8978b7        docksal_default     bridge              local
cdbf57a6812d        host                host                local
d191e5ad8055        none                null                local
940dc21b9628        qciw_default        bridge              local
834dcc47a836        yin_default         bridge              local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.34
5.2.34_Ubuntur133883

███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           796M  2.5M  794M   1% /run
/dev/sda1       213G  103G  100G  51% /
tmpfs           3.9G  498M  3.4G  13% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/loop0      218M  218M     0 100% /snap/atom/242
/dev/loop1      221M  221M     0 100% /snap/atom/241
/dev/sdb1       885G  224G  617G  27% /home
/dev/loop3       90M   90M     0 100% /snap/core/8039
/dev/loop5      8.7M  8.7M     0 100% /snap/canonical-livepatch/88
tmpfs           796M   16K  796M   1% /run/user/126
tmpfs           796M   72K  796M   1% /run/user/1000
/dev/loop6      8.7M  8.7M     0 100% /snap/canonical-livepatch/90
/dev/loop4       90M   90M     0 100% /snap/core/8213

  ```

</details>
