### ISSUE TITLE
Allow overriding or hooking into "fin start" and "fin stop"

### ISSUE THREAD

**Issue by mike-potter** [docksal/docksal#1259]
Feature request:  I'd like a way to hook into the "fin project start" and "fin project stop" commands.  I'm in the middle of adding support for Mutagen to replace Unison (I'll have a blog in a week or two I hope) because it's a game-changer for docker file system performance.  However, similar to unison, it requires a "sync" to start when you start a project (and terminate the sync when stopping the project).

So yes, I know I can create my own "pstart" or "pstop" commands, but I'm trying to do something for our dozens of existing projects that doesn't change our normal workflow.

**Comment by achekulaev** [comment]
There is a ticket for the hooks system, that I have essentially abandoned. This case is one of a handful ones, when implementing hooks in addition to commands does really make sense. However since it is so rare I would rather include that into `fin` itself. 

That is provided you succeed, of course. Because I tried mutagen before and it has [design issues](https://github.com/mutagen-io/mutagen/issues/33#issuecomment-489333328) regarding the propagation of the 'x' bit that rendered it non-useful for Docksal purposes.

**Comment by mike-potter** [comment]
I can post a separate topic on Mutagen, but it is working extremely well for us here.  I saw your issue about the `x` bit but I don't see where that affects us at all.  We are setting the default file permission to 644 and it's working just like `git` in how it handles the `x` bit.  Drupal sites working fine, and our builds are working fine.

Also, we do not try running Mutagen within a container (like Docksal does with unison) since that seems to defeat the purpose of speeding up file system access.  No need to another intermediate container that will cause the initial sync to take forever (unison in Docksal takes >10min for the initial file sync, whereas local Mutagen takes <2min).

This is a game changer for us because our project builds became 10x faster with Mutagen vs the "nfs" option in Docksal and doesn't have any of the crashing and unstable problems that "unison" has.

No Docksal changes are actually needed for Mutagen.  We use the existing `DOCKSAL_VOLUMES=none` option and then just have a `mutagen.yml` file and do a `mutagen project start` right after we do a `fin project start`.

If you look into the hooks again for this, maybe you can better abstract what is already in `fin` regarding the unison-sync-wait command.  Given how unreliable unison is for real-life projects (anybody with a /node_modules or /vendor folder) I really don't see ever using unison again in Docksal, and yet you have that support hard-coded in a way that doesn't allow alternatives to be hooked in.

**Comment by achekulaev** [comment]
Could you share the example of mutagen.yml?

**Comment by mike-potter** [comment]
Sure:
```
sync:
  defaults:
    mode: "two-way-resolved"
    ignore:
      vcs: true
      paths:
        - "*.sql"
    permissions:
      defaultFileMode: 644
      defaultDirectoryMode: 755
  mySyncSession:
    alpha: "."
    # CHANGE THIS to the name of your project CLI container.
    beta: "docker://docker@myproject_cli_1/var/www"
```
