### ISSUE TITLE
DB and CLI containers fail to launch when using NFS

### ISSUE THREAD

**Issue by jajajaime** [docksal/docksal#1261]
**Description**

When I try to use NFS, the db and cli containers fail to start. This happened on Mojave and it still happens on Catalina for me.

Using bind or unison start the project normally.

**Steps to reproduce the issue:**

1. Set DOCKSAL_VOLUMES="nfs" on project or ~/.docksal .env file

**Describe the results you received:**

Output:

Starting services...
Creating network "imprint-plus_default" with the default driver
Starting imprint-plus_elasticsearch_1 ...
Starting imprint-plus_db_1            ...
Starting imprint-plus_cli_1           ... error

ERROR: for imprint-plus_cli_1  Cannot start service cli: error while mounting volume '/var/lib/docker/volumes/imprint-plus_project_root/_data': failed to mount local volume: mount :/Users/jaime/beargroup/imprint-plus:/var/lib/docker/volumesStarting imprint-plus_db_1            ... error
e or directory

ERROR: for imprint-plus_db_1  Cannot start service db: error while mounting volume '/var/lib/docker/volumes/imprint-plusStarting imprint-plus_elasticsearch_1 ... done
mprint-plus_project_root/_data, flags: 0xc00, data: addr=192.168.64.1,vers=3,nolock,noacl,nocto,actimeo=1: no such file or directory

ERROR: for cli  Cannot start service cli: error while mounting volume '/var/lib/docker/volumes/imprint-plus_project_root/_data': failed to mount local volume: mount :/Users/jaime/beargroup/imprint-plus:/var/lib/docker/volumes/imprint-plus_project_root/_data, flags: 0xc00, data: addr=192.168.64.1,vers=3,nolock,noacl,nocto,actimeo=1: no such file or directory

ERROR: for db  Cannot start service db: error while mounting volume '/var/lib/docker/volumes/imprint-plus_project_root/_data': failed to mount local volume: mount :/Users/jaime/beargroup/imprint-plus:/var/lib/docker/volumes/imprint-plus_project_root/_data, flags: 0xc00, data: addr=192.168.64.1,vers=3,nolock,noacl,nocto,actimeo=1: no such file or directory
ERROR: Encountered errors while bringing up the project.

**Describe the results you expected:**

Containers to launch normally.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: imprint-plus
COMPOSE_FILE:
/Users/jaime/.docksal/stacks/volumes-nfs.yml
/Users/jaime/.docksal/stacks/stack-default.yml
/Users/jaime/beargroup/imprint-plus/.docksal/docksal.yml
ENV_FILE:
/Users/jaime/beargroup/imprint-plus/.docksal/docksal.env
/Users/jaime/beargroup/imprint-plus/.docksal/docksal-local.env

PROJECT_ROOT: /Users/jaime/beargroup/imprint-plus
DOCROOT: .
VIRTUAL_HOST: imprint-plus.docksal
VIRTUAL_HOST_ALIASES: *.imprint-plus.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: .
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: imprint-plus.docksal
      GIT_USER_EMAIL: jaimelopezav@gmail.com
      GIT_USER_NAME: Jaime
      HOST_GID: '20'
      HOST_UID: '501'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: serverName=imprint-plus.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: imprint-plus.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.10-php7.2
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.3-mysql-5.6
    ports:
    - 33078:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  elasticsearch:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    entrypoint: /usr/share/elasticsearch/docksal/entrypoints/elasticsearch.sh
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      bootstrap.memory_lock: "true"
    hostname: elasticsearch
    image: elasticsearch:6.5.3
    ports:
    - 9200/tcp
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
    - /Users/jaime/beargroup/imprint-plus/.docksal:/usr/share/elasticsearch/docksal:rw
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/.
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/jaime/beargroup/imprint-plus
      io.docksal.virtual-host: imprint-plus.docksal,*.imprint-plus.docksal,imprint-plus.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: :/Users/jaime/beargroup/imprint-plus
      o: addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,actimeo=1
      type: nfs

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.15.2
Darwin Macbearth.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.93.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.24.1
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

███  DOCKER
EXPECTED VERSION: 19.03.4

Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Fri Oct 18 15:48:38 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS
No virtual hosts found

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                       PORTS                                                    NAMES
3b8b6882352a        elasticsearch:6.5.3       "/usr/share/elastics…"   9 minutes ago       Up 56 seconds                9300/tcp, 0.0.0.0:32774->9200/tcp                        imprint-plus_elasticsearch_1
fff7e7953029        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)                                                            docksal-ssh-agent
583a3cd01479        docksal/dns:1.1           "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)   192.168.64.100:53->53/udp                                docksal-dns
ac34873c48b6        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                   DRIVER              SCOPE
596ba49a2edc        _default               bridge              local
76ecad989ac5        bridge                 bridge              local
e265e809d4c6        everymanjack_default   bridge              local
78678b4ed24a        host                   host                local
13bb98c779f5        imprint-plus_default   bridge              local
48e12c474945        none                   null                local
c83eefef59b8        sub_default            bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3
2.1.0.5

███  HDD Usage
Filesystem      Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1s6   466Gi   10Gi  249Gi     4%  484040 4881968840    0%   /
devfs          191Ki  191Ki    0Bi   100%     660          0  100%   /dev
/dev/disk1s1   466Gi  186Gi  249Gi    43% 1260314 4881192566    0%   /System/Volumes/Data
/dev/disk1s4   466Gi  1.0Gi  249Gi     1%       1 4882452879    0%   /private/var/vm
map auto_home    0Bi    0Bi    0Bi   100%       0          0  100%   /System/Volumes/Data/home
/dev/disk1s5   466Gi   19Gi  249Gi     8% 1276439 4881176441    0%   /Volumes/dev
  ```

</details>

<br>

**Contents of my /etc/exports for extra credit**
```
% cat /etc/exports

# <ds-nfs docksal
/Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
```

**Comment by achekulaev** [comment]
I have a supposition why it happens. Could you try `fin project remove` and then rename `imprint-plus` to `imprintplus` and try again and tell if there is any error?

**Comment by jajajaime** [comment]
I tried with multiple projects but the same was happening. It turns out that if you have the projects on a different volume, the global DOCKSAL_NFS_PATH var needs to be set to that volume for the containers to work. The docs make mention of it only for VirtualBox, but this solved it for Docker for me.

You can close this at your convenience.

**Comment by shelane** [comment]
I just had this happen for me as well. I previously had NFS mount working. I made no changes, but my computer was restarted.

```
fin up
Starting services...
Starting matomo_db_1 ... 
Starting matomo_cli_1 ... error

Starting matomo_db_1  ... error
mo_project_root/_data, flags: 0xc00, data: addr=192.168.64.1,vers=3,nolock,noacl,nocto,actimeo=1: operation not supported

ERROR: for matomo_db_1  Cannot start service db: error while mounting volume '/var/lib/docker/volumes/matomo_project_root/_data': failed to mount local volume: mount :/Users/french8/Sites/docksal/matomo:/var/lib/docker/volumes/matomo_project_root/_data, flags: 0xc00, data: addr=192.168.64.1,vers=3,nolock,noacl,nocto,actimeo=1: operation not supported

ERROR: for cli  Cannot start service cli: error while mounting volume '/var/lib/docker/volumes/matomo_project_root/_data': failed to mount local volume: mount :/Users/french8/Sites/docksal/matomo:/var/lib/docker/volumes/matomo_project_root/_data, flags: 0xc00, data: addr=192.168.64.1,vers=3,nolock,noacl,nocto,actimeo=1: operation not supported

ERROR: for db  Cannot start service db: error while mounting volume '/var/lib/docker/volumes/matomo_project_root/_data': failed to mount local volume: mount :/Users/french8/Sites/docksal/matomo:/var/lib/docker/volumes/matomo_project_root/_data, flags: 0xc00, data: addr=192.168.64.1,vers=3,nolock,noacl,nocto,actimeo=1: operation not supported
ERROR: Encountered errors while bringing up the project.
```
fin config:
```
COMPOSE_PROJECT_NAME_SAFE: matomo
COMPOSE_FILE:
/Users/french8/.docksal/stacks/volumes-nfs.yml
/Users/french8/.docksal/stacks/stack-default.yml
/Users/french8/Sites/docksal/matomo/.docksal/docksal.yml
ENV_FILE:
/Users/french8/Sites/docksal/matomo/.docksal/docksal.env

PROJECT_ROOT: /Users/french8/Sites/docksal/matomo
DOCROOT: web
VIRTUAL_HOST: matomo.docksal
VIRTUAL_HOST_ALIASES: *.matomo.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: web
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: matomo.docksal
      HOST_GID: '49799'
      HOST_UID: '49799'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: matomo.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.10-php7.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/web
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/french8/Sites/docksal/matomo
      io.docksal.virtual-host: matomo.docksal,*.matomo.docksal,matomo.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: :/Users/french8/Sites/docksal/matomo
      o: addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,actimeo=1
      type: nfs
```
