### ISSUE TITLE
Problems with internet when run docksal 

### ISSUE THREAD

**Issue by alex-belyaev** [docksal/docksal#1262]
**Description**
when i run docksal i got problems with internet. Some app dont work like slack, some random sites from search don't work. No problems with internet on other devices in same local network.
I use Windows 10 pro version 1903 (build 18362.535)

**Steps to reproduce the issue:**
Didn't do anything besides fin system start and fin init

**Describe the results you received:**
Got internet problems 

**Describe the results you expected:**
all works like a magic

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: womenlift
COMPOSE_FILE:
/home/alex/.docksal/stacks/volumes-bind.yml
/home/alex/.docksal/stacks/stack-default.yml
/f/work/womenlift/.docksal/docksal.yml
ENV_FILE:
/f/work/womenlift/.docksal/docksal.env

PROJECT_ROOT: /f/work/womenlift
DOCROOT: .
VIRTUAL_HOST: womenlift.docksal
VIRTUAL_HOST_ALIASES: *.womenlift.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: .
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: womenlift.docksal
      GIT_USER_EMAIL: ''
      GIT_USER_NAME: ''
      HOST_GID: '1000'
      HOST_UID: '1000'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: womenlift.docksal
      WP_ADMIN_EMAIL: admin@ffwagency.com
      WP_ADMIN_PASS: admin
      WP_ADMIN_USER: superuser
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.10-php7.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  redis:
    hostname: redis
    image: redis:4.0
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/.
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/web:2.2-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /f/work/womenlift
      io.docksal.virtual-host: womenlift.docksal,*.womenlift.docksal
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /f/work/womenlift
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
WSL Ubuntu 18.04
Linux Umbrella 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376

███  FIN
fin version: 1.93.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.24.1
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

███  DOCKER
EXPECTED VERSION: 19.03.4

Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:49:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:55:51 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.2
docker-machine.exe version 0.16.2, build bd45ab13

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
docksal   -        virtualbox   Running   tcp://192.168.64.100:2376           v19.03.4

███  DOCKSAL: PROJECTS
project             STATUS                    virtual host                            project root
womenlift           Up 11 minutes (healthy)   womenlift.docksal,*.womenlift.docksal   /f/work/womenlift

███  DOCKSAL: VIRTUAL HOSTS
*.womenlift.docksal
womenlift.docksal

███  DOCKSAL: DNS
curl: (6) Could not resolve host: dns-test.docksal
ERROR: Requesting http://dns-test.docksal failed!

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
300fd3b2be44        docksal/ssh-agent:1.3       "docker-entrypoint.s…"   11 minutes ago      Up 11 minutes (healthy)                                                            docksal-ssh-agent
57335ca599a4        docksal/dns:1.1             "docker-entrypoint.s…"   12 minutes ago      Up 12 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
739bb0f1ccf6        docksal/vhost-proxy:1.5     "docker-entrypoint.s…"   12 minutes ago      Up 12 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
55822be9b0c4        docksal/web:2.2-apache2.4   "httpd-foreground"       4 days ago          Up 11 minutes (healthy)   80/tcp, 443/tcp                                          womenlift_web_1
7b6e4161cf84        docksal/cli:2.10-php7.3     "/opt/startup.sh sup…"   4 days ago          Up 11 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               womenlift_cli_1
7fc3260f0adf        redis:4.0                   "docker-entrypoint.s…"   4 days ago          Up 11 minutes             6379/tcp                                                 womenlift_redis_1
7f43472279a2        docksal/mysql:5.6-1.4       "docker-entrypoint.s…"   4 days ago          Up 11 minutes (healthy)   0.0.0.0:32768->3306/tcp                                  womenlift_db_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
10252aeb3e2a        _default            bridge              local
ad09a54cdd80        bridge              bridge              local
def1667e6333        host                host                local
d53cd909fda8        none                null                local
02f707a5a081        womenlift_default   bridge              local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.34
5.2.34r133893

███  DOCKSAL MOUNTS
//192.168.64.1/docksal-c on /c type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=Alex,domain=UMBRELLA,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,soft,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//192.168.64.1/docksal-d on /d type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=Alex,domain=UMBRELLA,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,soft,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//192.168.64.1/docksal-e on /e type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=Alex,domain=UMBRELLA,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,soft,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//192.168.64.1/docksal-f on /f type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=Alex,domain=UMBRELLA,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,soft,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//192.168.64.1/docksal-g on /g type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=Alex,domain=UMBRELLA,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,soft,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//192.168.64.1/docksal-f on /mnt/sda1/var/lib/docker/volumes/womenlift_project_root/_data type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=Alex,domain=UMBRELLA,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,soft,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
  ```

</details>
