### ISSUE TITLE
`fin project start` does not setup NFS shares

### ISSUE THREAD

**Issue by JDDoesDev** [docksal/docksal#1265]
**Description**

When trying to start a project using `fin project start` the NFS shares are not setup appropriately.  This usually happens after a full system reboot.

**Steps to reproduce the issue:**

1. Run `fin system stop`or reboot the computer
2. Go to a project and run `fin project start`

**Describe the results you received:**

When starting after a reboot, the system starts as expected, but NFS share are not setup.

When starting after `fin system stop` the system will attempt to start the project, but fail due to permissions issues.

**Describe the results you expected:**

System to start with all volumes working as expected.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: ul-platform-drupal
COMPOSE_FILE:
/Users/james.flynn/.docksal/stacks/volumes-nfs.yml
/Users/james.flynn/.docksal/stacks/stack-acquia.yml
/Users/james.flynn/git/ul-platform-drupal/.docksal/docksal.yml
/Users/james.flynn/git/ul-platform-drupal/.docksal/docksal-local.yml
ENV_FILE:
/Users/james.flynn/git/ul-platform-drupal/.docksal/docksal.env
/Users/james.flynn/git/ul-platform-drupal/.docksal/docksal-local.env

PROJECT_ROOT: /Users/james.flynn/git/ul-platform-drupal
DOCROOT: docroot
VIRTUAL_HOST: site.docksal
VIRTUAL_HOST_ALIASES: *.site.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32769

Docker Compose configuration
---------------------
services:
  cli:
    build:
      context: /Users/james.flynn/git/sitel/.docksal/services/cli
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '1'
      COMPOSER_DISABLE_XDEBUG_WARN: '1'
      DEFAULT_BUILD_THEME_PROFILE: ul_base
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '1'
      GIT_USER_NAME: JD Flynn
      HOST_GID: '20'
      HOST_UID: '502'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: site.docksal
      XDEBUG_CONFIG: idekey=PHPSTORM remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: drupal_cli
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: solr
    image: docksal/solr:1.0-solr4
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: solr.site.docksal,solr.site.docksal.*
      io.docksal.virtual-port: '8983'
    volumes:
    - project_root:/var/www:ro,nocopy,cached
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:4.1-2.0
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: varnish.site.docksal,varnish.site.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/james.flynn/git/site
      io.docksal.virtual-host: site.docksal,*.site.docksal
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: :/Users/james.flynn/git/site
      o: addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,actimeo=1
      type: nfs

---------------------
```

</details>
