### ISSUE TITLE
Xdebug freezing on Mac and latest cli containers

### ISSUE THREAD

**Issue by Lazur** [docksal/docksal#1286]
Hello, I have a problem with Xdebug on Mac. With the option "break on first line" debugger has been run successfully but after step forward nothing happens, site is freezing, no further steps happens.
My very old cli that I used before the update is cli:1.3-php7 working well on the same configuration. That allow me to exclude incorrect IDE config. Any others cli have the same issue with debug for me. Without debuting they are working fine.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: immunoconnect-adempass
COMPOSE_FILE:
/Users/kyrylo_popov/.docksal/stacks/volumes-bind.yml
/Users/kyrylo_popov/.docksal/stacks/stack-default.yml
/Users/kyrylo_popov/Projects/customer/immunoconnect-adempass/.docksal/docksal.yml
/Users/kyrylo_popov/Projects/customer/immunoconnect-adempass/.docksal/docksal-local.yml
ENV_FILE:
/Users/kyrylo_popov/Projects/customer/immunoconnect-adempass/.docksal/docksal.env
/Users/kyrylo_popov/Projects/customer/immunoconnect-adempass/.docksal/docksal-local.env

PROJECT_ROOT: /Users/kyrylo_popov/Projects/customer/immunoconnect-adempass
DOCROOT: docroot
VIRTUAL_HOST: immunoconnect-adempass.docksal
VIRTUAL_HOST_ALIASES: *.immunoconnect-adempass.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:33065

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 10.6.0.16
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '1'
      COMPOSER_DISABLE_XDEBUG_WARN: '1'
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '1'
      DRUSH_OPTIONS_URI: immunoconnect-adempass.docksal
      GIT_USER_EMAIL: kyrylo_popov@company.com
      GIT_USER_NAME: Kir
      HOST_GID: '1080604409'
      HOST_UID: '1584838351'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: immunoconnect-adempass.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.10-php7.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 10.6.0.16
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.7
    ports:
    - 33065:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  mail:
    dns:
    - 192.168.64.100
    - 10.6.0.16
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: mail.immunoconnect-adempass.docksal,mail.immunoconnect-adempass.docksal.*
      io.docksal.virtual-port: '8025'
    volumes:
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 10.6.0.16
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/kyrylo_popov/Projects/customer/immunoconnect-adempass
      io.docksal.virtual-host: immunoconnect-adempass.docksal,*.immunoconnect-adempass.docksal,immunoconnect-adempass.docksal.*
    ports:
    - 81:80/tcp
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/kyrylo_popov/Projects/customer/immunoconnect-adempass
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  ███  OS
Darwin Mac OS X 10.14.6
Darwin EPBYMINW0888 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : /Users
NFS EXPORTS:

# <ds-nfs docksal
/Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.93.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.24.1
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

███  DOCKER
EXPECTED VERSION: 19.03.4

Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Fri Oct 18 15:48:38 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:55:51 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.2
docker-machine version 0.16.2, build bd45ab13

NAME       ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
default    -        virtualbox   Stopped                                       Unknown    
docksal    *        virtualbox   Running   tcp://192.168.64.100:2376           v19.03.4   
manager1   -        virtualbox   Stopped                                       Unknown    
worker1    -        virtualbox   Stopped                                       Unknown    
worker2    -        virtualbox   Stopped                                       Unknown    

███  DOCKSAL: PROJECTS
project                  STATUS                   virtual host                                                                                       project root
immunoconnect-adempass   Up 8 minutes (healthy)   immunoconnect-adempass.docksal,*.immunoconnect-adempass.docksal,
immunoconnect-adempass.docksal.*   /Users/kyrylo_popov/Projects/customer/immunoconnect-adempass

███  DOCKSAL: VIRTUAL HOSTS
[0;32m*.immunoconnect-adempass.docksal[0m
[0;32mimmunoconnect-adempass.docksal.*[0m
[0;32mimmunoconnect-adempass.docksal[0m
[0;32mmail.immunoconnect-adempass.docksal.*[0m
[0;32mmail.immunoconnect-adempass.docksal[0m

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                   PORTS                                                    NAMES
5006c1206ce3        docksal/apache:2.4-2.3     "httpd-foreground"       8 minutes ago       Up 8 minutes (healthy)   443/tcp, 0.0.0.0:81->80/tcp                              immunoconnect-adempass_web_1
52c8d3712cf2        docksal/cli:2.10-php7.3    "/opt/startup.sh sup…"   8 minutes ago       Up 8 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               immunoconnect-adempass_cli_1
194f2151e3c5        docksal/ssh-agent:1.3      "docker-entrypoint.s…"   18 hours ago        Up 18 hours (healthy)                                                             docksal-ssh-agent
b49386b889d0        docksal/dns:1.1            "docker-entrypoint.s…"   18 hours ago        Up 18 hours (healthy)    192.168.64.100:53->53/udp                                docksal-dns
a8b2a8c3de8f        docksal/vhost-proxy:1.5    "docker-entrypoint.s…"   18 hours ago        Up 18 hours (healthy)    192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
b91ca6dd005c        docksal/db:1.1-mysql-5.7   "/entrypoint.sh mysq…"   6 days ago          Up 8 minutes             0.0.0.0:33065->3306/tcp                                  immunoconnect-adempass_db_1
ad9c83dbbdff        mailhog/mailhog            "MailHog"                6 days ago          Up 8 minutes             1025/tcp, 8025/tcp                                       immunoconnect-adempass_mail_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                             DRIVER              SCOPE
ac5e42706591        _default                         bridge              local
526286a1e329        bridge                           bridge              local
113acce74032        host                             host                local
935c612828a5        immunoconnect-adempass_default   bridge              local
f4e15f96bbc8        none                             null                local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.34
6.0.8r130520

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.64.1,mountvers=3,mountport=601,mountproto=udp,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/kyrylo_popov/Projects/customer/immunoconnect-adempass on /mnt/sda1/var/lib/docker/volumes/immunoconnect-adempass_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.64.1,mountvers=3,mountport=601,mountproto=udp,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G      7.4G     36.3G  17% /mnt/sda1

  ```

</details>
