### ISSUE TITLE
The Varnish control terminal is not responding at varnish:6082

### ISSUE THREAD

**Issue by drubage** [docksal/docksal#1294]
**Description**

Varnish does not seem to work or be accessible within the containers.

**Steps to reproduce the issue:**

1. Start a project with varnish service.
2. Set up a vanilla Wordpress site with the "Purge Varnish" plugin installed.
3. Attempt to connect to the varnish control terminal at varnish:6082.
4. See the error "The Varnish control terminal is not responding at varnish:6082".

**Describe the results you received:**

The Varnish control terminal is not responding at varnish:6082

**Describe the results you expected:**

A working Varnish control terminal.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: wordpress-cloud-example
COMPOSE_FILE:
/Users/drewmichael/.docksal/stacks/volumes-nfs.yml
/Users/drewmichael/.docksal/stacks/stack-default.yml
/Users/drewmichael/projects/wordpress-cloud-example/.docksal/docksal.yml
ENV_FILE:
/Users/drewmichael/projects/wordpress-cloud-example/.docksal/docksal.env
/Users/drewmichael/projects/wordpress-cloud-example/.docksal/docksal-local.env

PROJECT_ROOT: /Users/drewmichael/projects/wordpress-cloud-example
DOCROOT: docroot
VIRTUAL_HOST: wordpress-cloud-example.docksal
VIRTUAL_HOST_ALIASES: *.wordpress-cloud-example.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32811

Docker Compose configuration
---------------------
services:
  cli:
    build:
      context: /Users/drewmichael/projects/wordpress-cloud-example/.docksal/services/cli
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      AUTH_KEY: generateme
      AUTH_SALT: generateme
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '1'
      COMPOSER_DISABLE_XDEBUG_WARN: '1'
      CRON_OK: "FALSE"
      DB_DATABASE: default
      DB_HOST: db
      DB_PASSWORD: user
      DB_PREFIX: wp_
      DB_USER: user
      DISALLOW_FILE_EDIT: "false"
      DISALLOW_FILE_MODS: "false"
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '1'
      DRUSH_OPTIONS_URI: wordpress-cloud-example.docksal
      ENVIRONMENT: DOCKSAL
      GIT_USER_EMAIL: ''
      GIT_USER_NAME: ''
      HOST_GID: '20'
      HOST_UID: '502'
      HTPASSWD_PASSWORD: null
      HTPASSWD_USER: null
      LOGGED_IN_KEY: generateme
      LOGGED_IN_SALT: generateme
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      NONCE_KEY: generateme
      NONCE_SALT: generateme
      PHP_IDE_CONFIG: null
      SAVEQUERIES: "true"
      SCRIPT_DEBUG: "true"
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SECURE_AUTH_KEY: generateme
      SECURE_AUTH_SALT: generateme
      SERVER_ADMIN: webmaster@fruition.net
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VARNISH_SECRET: wpsecretkeyI9hZt0S0YcuQ
      VIRTUAL_HOST: wordpress-cloud-example.docksal
      WP_DEBUG: "true"
      WP_DEBUG_DISPLAY: "true"
      WP_ENV: DEV
      WP_HOME: http://wordpress-cloud-example.docksal
      WP_MULTISITE: "false"
      WP_SITEURL: http://wordpress-cloud-example.docksal/wp
      WP_VARNISH_PURGE_DEBUG: "true"
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: wordpress-cloud-example_cli
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  mail:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: mail.wordpress-cloud-example.docksal,mail.wordpress-cloud-example.docksal.*
      io.docksal.virtual-port: '8025'
    volumes:
    - project_root:/var/www:ro,nocopy,cached
  varnish:
    environment:
      VARNISH_BACKEND_HOST: web
      VARNISH_SECRET: wpsecretkeyI9hZt0S0YcuQ
      VARNISH_VARNISHD_PARAMS: -T :6082
    expose:
    - '6082'
    hostname: varnish
    image: docksal/varnish:1.0-varnish4
    labels:
      io.docksal.virtual-host: varnish.wordpress-cloud-example.docksal
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/drewmichael/projects/wordpress-cloud-example
      io.docksal.virtual-host: wordpress-cloud-example.docksal,*.wordpress-cloud-example.docksal,wordpress-cloud-example.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: :/Users/drewmichael/projects/wordpress-cloud-example
      o: addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,actimeo=1
      type: nfs

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.14.5
Darwin Drews-MacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.93.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.24.1
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

███  DOCKER
EXPECTED VERSION: 19.03.4

Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Fri Oct 18 15:48:38 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
project                   STATUS                    virtual host                                                                                          project root
wordpress-cloud-example   Up 10 minutes (healthy)   wordpress-cloud-example.docksal,*.wordpress-cloud-example.docksal,wordpress-cloud-example.docksal.*   /Users/drewmichael/projects/wordpress-cloud-example

███  DOCKSAL: VIRTUAL HOSTS
*.wordpress-cloud-example.docksal
mail.wordpress-cloud-example.docksal.*
mail.wordpress-cloud-example.docksal
varnish.wordpress-cloud-example.docksal
wordpress-cloud-example.docksal.*
wordpress-cloud-example.docksal

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
cae3873d4258        docksal/apache:2.4-2.3         "httpd-foreground"       10 minutes ago      Up 10 minutes (healthy)   80/tcp, 443/tcp                                          wordpress-cloud-example_web_1
d0dbe771ab64        wordpress-cloud-example_cli    "/opt/startup.sh sup…"   11 minutes ago      Up 10 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               wordpress-cloud-example_cli_1
21488a208003        docksal/varnish:1.0-varnish4   "/opt/startup.sh"        11 minutes ago      Up 11 minutes             80/tcp, 6082/tcp                                         wordpress-cloud-example_varnish_1
0602af13a684        docksal/mysql:5.6-1.4          "docker-entrypoint.s…"   2 days ago          Up 11 minutes (healthy)   0.0.0.0:32811->3306/tcp                                  wordpress-cloud-example_db_1
f5438f5ebfc2        mailhog/mailhog                "MailHog"                2 days ago          Up 10 minutes             1025/tcp, 8025/tcp                                       wordpress-cloud-example_mail_1
b90d35518779        docksal/ssh-agent:1.3          "docker-entrypoint.s…"   3 days ago          Up 3 days (healthy)                                                                docksal-ssh-agent
ed17c2a87d56        docksal/dns:1.1                "docker-entrypoint.s…"   3 days ago          Up 3 days (healthy)       192.168.64.100:53->53/udp                                docksal-dns
d7ea1c90c156        docksal/vhost-proxy:1.5        "docker-entrypoint.s…"   3 days ago          Up 3 days (healthy)       192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                              DRIVER              SCOPE
90f6c742903d        _default                          bridge              local
8d316de954ea        accessibility-scanner_default     bridge              local
6c5c3c7c27dc        bridge                            bridge              local
3e84eee9f16b        host                              host                local
e263163465c5        none                              null                local
9e378f0190fe        trimblemicro_default              bridge              local
c3dfda34ea3e        wordpress-cloud-example_default   bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3
2.1.0.5

███  HDD Usage
Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1   234Gi  214Gi   15Gi    94% 3398747 9223372036851377060    0%   /
devfs          187Ki  187Ki    0Bi   100%     647                   0  100%   /dev
/dev/disk1s4   234Gi  4.0Gi   15Gi    22%       4 9223372036854775803    0%   /private/var/vm
map -hosts       0Bi    0Bi    0Bi   100%       0                   0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0                   0  100%   /home

  ```

</details>

FYI we are currently testing with a Wordpress site and the "Purge Varnish" plugin. When we run the same codebase but in a Google Cloud Kubernets project then the site can connect to varnish just fine at varnish:6082. Our local Docksal builds, however, are unable to connect it seems.

**Comment by achekulaev** [comment]
> Attempt to connect to the varnish control terminal at varnish:6082.

From where?

**Comment by drubage** [comment]
`Drews-MacBook-Pro:wordpress-cloud-example drewmichael$ fin ps
              Name                            Command                State                 Ports           
-----------------------------------------------------------------------------------------------------------
wordpress-cloud-example_cli_1       /opt/startup.sh supervisord   Up (healthy)   22/tcp, 3000/tcp, 9000/tcp
wordpress-cloud-example_db_1        docker-entrypoint.sh mysqld   Up (healthy)   0.0.0.0:32811->3306/tcp   
wordpress-cloud-example_mail_1      MailHog                       Up             1025/tcp, 8025/tcp        
wordpress-cloud-example_varnish_1   /opt/startup.sh               Up             6082/tcp, 80/tcp          
wordpress-cloud-example_web_1       httpd-foreground              Up (healthy)   443/tcp, 80/tcp       `

**Comment by drubage** [comment]
I am checking on the plugin settings page (which works in our Kubernetes environment):

![Terminal ‹ Wordpress Cloud Example — WordPress](https://user-images.githubusercontent.com/2574144/76239864-e2510b80-61f7-11ea-8fbe-cd76a59a601e.png)

**Comment by drubage** [comment]
Working site looks like this...

![Terminal ‹ Wordpress Cloud Example — WordPress (1)](https://user-images.githubusercontent.com/2574144/76240129-525f9180-61f8-11ea-8d22-f86fb3ef3b16.png)

**Comment by achekulaev** [comment]
Kubernetes? So it's external to Docker?

**Comment by drubage** [comment]
No, I am running the project locally with Docksal and Varnish and the Varnish control server does not respond. We also have this project running on Kubernetes with Varnish service and it connects fine. I can see the varnish service running okay in Docksal but the web container does not seem to be able to connect to it.

**Comment by achekulaev** [comment]
I am not sure how we can help in this case. The container is running. Everything beyond is application level and configuration. I would check the logs of Varnish and debug from there.

**Comment by drubage** [comment]
I have not been able to get it to work with a basic vanilla Drupal install and the varnish module either. Are you confident it works at all?

**Comment by achekulaev** [comment]
I followed manual from [here](https://docs.docksal.io/tools/varnish/), which downloaded me version `docksal/varnish:6.1-2.0` (not the one you use), and then I exposed port on the localhost to quickly test if varnish is working (because there is no telnet in `cli`)

```yaml
services:
  # Varnish
  varnish:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: varnish
    depends_on:
      - web
    ports:
      - "10888:6082"
```

Checked it is working from the localhost:

```
17:32:39 ~/Projects/docksal/example-grav
§ telnet localhost 10888
Trying ::1...
Connected to localhost.
Escape character is '^]'.
107 59      
olrmfypcbhzsgabskaxbxcrravtkrqtd

Authentication required.
```

Seems to be working.

**Comment by drubage** [comment]
Thanks for your help, you guys are the best!

I do not think that it is working because you did not specify a VARNISH_SECRET did you? It's asking you for authentication even though the secret is not there. With or without the secret it can't connect to the control server from my testing.

**Comment by achekulaev** [comment]
1. I do not do Wordpress, I do Drupal
2. I do not usually install Varnish locally at all, I just checked that Varnish runs and responds, and considered that it would be enough. I did not catch that you questioned workability of varnish image to begin with.
3. I do not understand the frustration in a ticket in a free open source project.

With that said. 

1. I set up a copy of Wordpress using `fin project create` command
2. I added [Purge Varnish](https://wordpress.org/plugins/purge-varnish/) plugin and activated it
3. I added varnish service 4.x because Purge Varnish does not support 6.x

```yaml
  varnish:
    image: docksal/varnish:4.1
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: varnish
    environment:
      - VARNISH_SECRET=olrmfypcbhzsgabskaxbxcrravtkrqtd
    depends_on:
      - web
```

4. I could not make Purge Varnish plugin to work by hostname, it says it's an invalid IP, but when I use varnish service IP it goes green.

<img width="1680" alt="Terminal ‹ My WordPress Site" src="https://user-images.githubusercontent.com/402007/76367228-d3a34b00-6302-11ea-8ffa-eb8f20efbb22.png">

I guess that's more that enough proof of the fact that Varnish works, and you need to replicate the steps and find the error in your configuration.
