### ISSUE TITLE
No internet from my container web and Cli ?

### ISSUE THREAD

**Issue by acteg** [docksal/docksal#1298]
**Description**

I can't connect to internet from my cli or web container. i think i have issue with dns, i tried all solutions from #770 but noting work.

From my contaner i have this dns server :
  ```
cat /etc/resolv.conf
search dev.company.lan.net
nameserver 127.0.0.11
options ndots:0
  ```
And from my host nslookup google.com return this result : 
  ```
nslookup google.com
Server:         172.20.100.10
Address:        172.20.100.10#53

Non-authoritative answer:
Name:   google.com
Address: 172.217.22.142
  ```

I tried to add custom dns but don't work.

**Steps to reproduce the issue:**

1. fin composer -vvv install

**Describe the results you received:**
  ```
[Composer\Downloader\TransportException]
  The "https://packages.drupal.org/8/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
  ```

**Describe the results you expected:**

Expected behavior...

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: contrib
COMPOSE_FILE:
/home/admin/.docksal/stacks/volumes-bind.yml
/home/admin/.docksal/stacks/stack-default.yml
/home/admin/projects/contrib/.docksal/docksal.yml
ENV_FILE:
/home/admin/projects/contrib/.docksal/docksal.env

PROJECT_ROOT: /home/admin/projects/contrib
DOCROOT: web
VIRTUAL_HOST: contrib.docksal
VIRTUAL_HOST_ALIASES: *.contrib.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32770

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: web
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: contrib.docksal
      GIT_USER_EMAIL: abdou.teguia-ext@kleegroup.com
      GIT_USER_NAME: Teguia Abdou
      HOST_GID: '100'
      HOST_UID: '1001'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: contrib.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.10-php7.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/web
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /home/admin/projects/contrib
      io.docksal.virtual-host: contrib.docksal,*.contrib.docksal,contrib.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/admin/projects/contrib
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  ███  OS
Linux Debian GNU/Linux 9
Linux contrib.company.lan.net 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST :

███  FIN
fin version: 1.93.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.24.1
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

███  DOCKER
EXPECTED VERSION: 19.03.4

Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:26:02 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:36 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
project             STATUS                    virtual host                                          project root
contrib             Up 41 minutes (healthy)   contrib.docksal,*.contrib.docksal,contrib.docksal.*   /home/admin/projects/contrib

███  DOCKSAL: VIRTUAL HOSTS
*.contrib.docksal
contrib.docksal.*
contrib.docksal

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
cf8db0bc9836        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   24 minutes ago      Up 24 minutes (healthy)                                                            docksal-ssh-agent
1d924804cf0d        docksal/dns:1.1           "docker-entrypoint.s…"   25 minutes ago      Up 25 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
1eb19cf8502f        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   25 minutes ago      Up 25 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
85aef6d2d6c5        docksal/apache:2.4-2.3    "httpd-foreground"       59 minutes ago      Up 41 minutes (healthy)   80/tcp, 443/tcp                                          contrib_web_1
ac771dc32416        docksal/cli:2.10-php7.3   "/opt/startup.sh sup…"   About an hour ago   Up 41 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               contrib_cli_1
1054e4ef5a82        docksal/mysql:5.6-1.4     "docker-entrypoint.s…"   About an hour ago   Up 41 minutes (healthy)   0.0.0.0:32770->3306/tcp                                  contrib_db_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
0d9252e71cc5        _default            bridge              local
5ebfa73ac029        bridge              bridge              local
e3055db84c32        contrib_default     bridge              local
ff5d7f2f98b3        host                host                local
e377c0c8faf5        none                null                local

███  HDD Usage
Sys. de fichiers      Taille Utilisé Dispo Uti% Monté sur
udev                    3,9G       0  3,9G   0% /dev
tmpfs                   798M    9,3M  789M   2% /run
/dev/mapper/vg01-root   6,6G    5,0G  1,7G  76% /
tmpfs                   3,9G       0  3,9G   0% /dev/shm
tmpfs                   5,0M       0  5,0M   0% /run/lock
tmpfs                   3,9G       0  3,9G   0% /sys/fs/cgroup
/dev/sda1               484M     86M  399M  18% /boot
tmpfs                   798M       0  798M   0% /run/user/1001

  ```

</details>
