### ISSUE TITLE
fin db import not working

### ISSUE THREAD

**Issue by arc113** [docksal/docksal#1300]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

fin db import --db=xyz /path/to/db.sql no longer works. Earlier when I used to run this command, it would start to import the db. After recent update I noticed that It asks for a password, which it didn't before.

**Steps to reproduce the issue:**

1. fin db import --db=cloned db/db_name.sql OR fin mysql-import --db=cloned cpact_department.sql 

**Describe the results you received:**

Truncating cloned database...
Enter password: 
Importing cpact_department.sql...
Enter password: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
read unix @->/var/run/docker.sock: read: connection reset by peer
Import failed
This is the result i received.

**Describe the results you expected:**

It should've imported the database.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: snu
COMPOSE_FILE:
/home/innoraft/.docksal/stacks/volumes-bind.yml
/home/innoraft/.docksal/stacks/stack-default.yml
/home/innoraft/Project2/snu/.docksal/docksal.yml
ENV_FILE:
/home/innoraft/Project2/snu/.docksal/docksal.env
/home/innoraft/Project2/snu/.docksal/docksal-local.env

PROJECT_ROOT: /home/innoraft/Project2/snu
DOCROOT: docroot
VIRTUAL_HOST: snu.docksal
VIRTUAL_HOST_ALIASES: *.snu.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: snu.docksal
      GIT_USER_EMAIL: archit.bohra@innoraft.com
      GIT_USER_NAME: arc113
      HOST_GID: '1000'
      HOST_UID: '1000'
      MYSQL_DATABASE: null
      MYSQL_HOST: null
      MYSQL_PASSWORD: null
      MYSQL_ROOT_PASSWORD: null
      MYSQL_USER: null
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
      VIRTUAL_HOST: snu.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.5-php5.6
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - cli_home:/home/docker:rw
    - /run/user/1000/keyring/ssh:/run/user/1000/keyring/ssh:ro
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: null
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: null
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: null
      MYSQL_USER: null
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  pma:
    environment:
      PMA_HOST: db
      PMA_PASSWORD: root
      PMA_USER: root
    hostname: pma
    image: phpmyadmin/phpmyadmin
    labels:
      io.docksal.virtual-host: pma.snu.docksal
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /home/innoraft/Project2/snu
      io.docksal.virtual-host: snu.docksal,*.snu.docksal,snu.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/innoraft/Project2/snu
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Linux Linux Mint 19.1
Linux innoraft-Vostro-3558 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST : 

███  FIN
fin version: 1.86.2

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

███  DOCKER
EXPECTED VERSION: 18.09.2

Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:41:45 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd
  Built:            Wed Jul 17 17:07:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKSAL: PROJECTS
project             STATUS                  virtual host                              project root
snu                 Up 25 hours (healthy)   snu.docksal,*.snu.docksal,snu.docksal.*   /home/innoraft/Project2/snu

███  DOCKSAL: VIRTUAL HOSTS
*.snu.docksal
pma.snu.docksal
snu.docksal.*
snu.docksal

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
65aa6fe707de        docksal/apache:2.4-2.3    "httpd-foreground"       10 days ago         Up 25 hours (healthy)     80/tcp, 443/tcp                                          snu_web_1
e4ec234de353        docksal/mysql:5.6-1.4     "docker-entrypoint.s…"   10 days ago         Up 25 hours (unhealthy)   0.0.0.0:32768->3306/tcp                                  snu_db_1
37d066711755        docksal/cli:2.5-php5.6    "/opt/startup.sh sup…"   10 days ago         Up 25 hours (healthy)     22/tcp, 3000/tcp, 9000/tcp                               snu_cli_1
a5aa5e2b6a46        phpmyadmin/phpmyadmin     "/docker-entrypoint.…"   10 days ago         Up 25 hours               80/tcp                                                   snu_pma_1
38abf4b104f8        docksal/ssh-agent:1.2     "docker-entrypoint.s…"   10 days ago         Up 25 hours (unhealthy)                                                            docksal-ssh-agent
76b444197853        docksal/dns:1.1           "docker-entrypoint.s…"   10 days ago         Up 25 hours (healthy)     192.168.64.100:53->53/udp                                docksal-dns
19f56dcf3f7a        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   10 days ago         Up 25 hours (healthy)     192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                          DRIVER              SCOPE
84f5929468b9        _default                      bridge              local
55c73c4df899        bridge                        bridge              local
f7e8887093b1        d8_default                    bridge              local
054eabf56464        example_default               bridge              local
dbc439375749        exp1_default                  bridge              local
1d89707686d7        host                          host                local
a624844d1019        iarc13_default                bridge              local
e1469b47b33d        iarchit_default               bridge              local
6a6761787f35        iiimit_default                bridge              local
fe8238353aae        ms_default                    bridge              local
52f19246e7d0        none                          null                local
c49ed2e40fc3        np_default                    bridge              local
c70215383c86        shivnadaruniversity_default   bridge              local
e1c0553286d8        snu_default                   bridge              local
8bc53e492119        sto2_default                  bridge              local
3a0fc159bb8e        stu_default                   bridge              local
de8dc2e2fc4f        sxu_default                   bridge              local
8365c2c9e37b        test_default                  bridge              local
e24b0c7cc9c9        tx_default                    bridge              local
a170775c15ba        x_default                     bridge              local
e4826fee905a        xa_default                    bridge              local
b19f0d80835b        xnu_default                   bridge              local
476688b92415        xxx_default                   bridge              local
dd46010df6e3        xyz_default                   bridge              local

███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           790M  6.2M  784M   1% /run
/dev/sda5       183G  166G  8.0G  96% /
tmpfs           3.9G  266M  3.6G   7% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs           790M   76K  790M   1% /run/user/1000
/dev/sda2       267G  143G  111G  57% /media/innoraft/4fd9aa14-7bc6-4a8e-9deb-82cd17afcc91

  ```

</details>
