### ISSUE TITLE
macOS Catalina VM – NFS share mount failed

### ISSUE THREAD

**Issue by laurelstreng** [docksal/docksal#1310]
**Description**

Just trying to get a brand new Docksal setup up and running. After I run `fin system start` everything seems to be happy, except for NFS. I am constantly getting the following error:
```
Configuring network settings...
Configuring NFS shares...
Writing /etc/exports...
Restarting nfsd...
Mounting NFS shares...
Mounting local /Users/lstreng/Projects to /Users/lstreng/Projects
mount.nfs: requested NFS version or transport protocol is not supported
exit status 32
Retrying mounting local /Users/lstreng/Projects to /Users/lstreng/Projects
mount.nfs: requested NFS version or transport protocol is not supported
exit status 32
 ERROR:  NFS share mount failed.
        Try fin vm mount or fin vm restart.
```

Any help would be much appreciated.

**I have tried the following:**
- `fin vm mount`
- `fin vm restart`
- `fin system reset`
- Checked my `etc/exports` file and that it is getting updated. Tried deleting it as well.
- I have also remove/uninstalled all of docksal and started over with the VM docksal installation and still have the same issue.

**Steps to reproduce the issue:**

1. Install docksal VM
2. Run `fin system start`

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: relias
COMPOSE_FILE:
/Users/lstreng/.docksal/stacks/volumes-bind.yml
/Users/lstreng/.docksal/stacks/stack-default.yml
/Users/lstreng/Projects/relias/.docksal/docksal.yml
ENV_FILE:
/Users/lstreng/Projects/relias/.docksal/docksal.env

PROJECT_ROOT: /Users/lstreng/Projects/relias
DOCROOT: .
VIRTUAL_HOST: relias.docksal
VIRTUAL_HOST_ALIASES: *.relias.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: .
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: relias.docksal
      GIT_USER_EMAIL: lstreng@relias.com
      GIT_USER_NAME: Laurel Streng
      HOST_GID: '20'
      HOST_UID: '502'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: relias.docksal
      WP_ADMIN_EMAIL: info@example.com
      WP_ADMIN_PASS: admin
      WP_ADMIN_USER: admin
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.10-php7.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 1:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/.
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/lstreng/Projects/relias
      io.docksal.virtual-host: relias.docksal,*.relias.docksal,relias.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/lstreng/Projects/relias
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.15.3
Darwin RELIAS-C02ZF7ASLVDQ 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : /Users/lstreng/Projects
NFS EXPORTS:

# <ds-nfs docksal
/Users/lstreng/Projects 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.93.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.24.1
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

███  DOCKER
EXPECTED VERSION: 19.03.4

Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Fri Oct 18 15:48:38 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:55:51 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.2
docker-machine version 0.16.2, build bd45ab13

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v19.03.4   

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS
No virtual hosts found

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
3bd6ed17d2a6        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   46 seconds ago      Up 45 seconds (healthy)                                                            docksal-ssh-agent
4c3a635890a5        docksal/dns:1.1           "docker-entrypoint.s…"   46 seconds ago      Up 45 seconds (healthy)   192.168.64.100:53->53/udp                                docksal-dns
e2720610b9f4        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   47 seconds ago      Up 46 seconds (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
01d18004e514        _default            bridge              local
b4b280df8749        bridge              bridge              local
148d28e1789e        host                host                local
9a13b5cb98c4        none                null                local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.34
5.2.34r133893

███  DOCKSAL MOUNTS
 ERROR:  Mounts matching 192.168.64* were not found!

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G    311.9M     43.4G   1% /mnt/sda1
  ```

</details>
