### ISSUE TITLE
macOS Catalina (10.15) breaks access to certain folders via NFS

### ISSUE THREAD

**Issue by gonzamace** [docksal/docksal#1350]
**Description**

When I try to use NFS by default, the CLI container fails in many different ways.

**Here are the sequential steps, command after command to be as clear as possible.**

### 1 `fin project create`

 Step 1  Initializing stack...
 ALERT:  Please update Docker Desktop to the latest version manually.
         Expected Docker Desktop version: 2.0.0.3
 ALERT:  Some Docksal services were not running
         Restarting Docksal system services...
Configuring network settings...
Password:
Configuring NFS shares...
Writing /etc/exports...
Restarting nfsd...
Resetting Docksal system services...
 * proxy
 * dns
   upstream 10.28.3.2
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
 * ssh-agent
Identity added: id_rsa (gn.rodriguez@AR-IT18203)
Removing containers...
Removing network test_default
WARNING: Network test_default not found.
Removing volume test_cli_home
WARNING: Volume test_cli_home not found.
Removing volume test_project_root
WARNING: Volume test_project_root not found.
Removing volume test_db_data
WARNING: Volume test_db_data not found.
Volume docksal_ssh_agent is external, skipping
Starting services...
Creating network "test_default" with the default driver
Creating volume "test_cli_home" with default driver
Creating volume "test_project_root" with local driver
Creating volume "test_db_data" with default driver
Creating test_db_1  ... done
Creating test_cli_1 ... error

ERROR: for test_cli_1  Cannot start service cli: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"mkdir /var/www: file exists\"": unknown

ERROR: for cli  Cannot start service cli: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"mkdir /var/www: file exists\"": unknown
ERROR: Encountered errors while bringing up the project.

### 2 `fin project restart`

Disconnecting project network...
Stopping services...
Starting services...
Creating network "sites_default" with the default driver
Creating volume "sites_cli_home" with default driver
Creating volume "sites_project_root" with local driver
Creating volume "sites_db_data" with default driver
Creating sites_cli_1 ... error
Creating sites_db_1  ... done

ERROR: for sites_cli_1  Cannot start service cli: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/docker/volumes/sites_project_root/_data\\\" to rootfs \\\"/var/lib/docker/overlay2/8ada6ece83a83fa6b1233dcf7ff1ae78e458014b24299a04d25b43cc1ccb3334/merged\\\" at \\\"/var/www\\\" caused \\\"stat /var/lib/docker/volumes/sites_project_root/_data: stale NFS file handle\\\"\"": unknown

ERROR: for cli  Cannot start service cli: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/docker/volumes/sites_project_root/_data\\\" to rootfs \\\"/var/lib/docker/overlay2/8ada6ece83a83fa6b1233dcf7ff1ae78e458014b24299a04d25b43cc1ccb3334/merged\\\" at \\\"/var/www\\\" caused \\\"stat /var/lib/docker/volumes/sites_project_root/_data: stale NFS file handle\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.

### 3 `fin project restart`

Disconnecting project network...
Stopping services...
Stopping sites_db_1 ... done
Starting services...
Creating network "sites_default" with the default driver
Starting sites_db_1  ... done
Starting sites_cli_1 ... done
Creating sites_web_1 ... done
Connected vhost-proxy to "sites_default" network.
Waiting for project stack to become ready...

### 4 `fin bash`

Error: Unknown system error -116: Unknown system error -116, scandir '/var/www'
TypeError: Cannot read property 'loaded' of undefined
    at exit (/home/docker/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/utils/error-handler.js:97:27)
    at errorHandler (/home/docker/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at /home/docker/.nvm/versions/node/v12.13.0/lib/node_modules/npm/bin/npm-cli.js:78:20
    at cb (/home/docker/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/npm.js:225:22)
    at /home/docker/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/npm.js:263:24
    at /home/docker/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at /home/docker/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/config/core.js:80:13
    at f (/home/docker/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at /home/docker/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/config/core.js:110:20
TypeError: Cannot read property 'loaded' of undefined
    at exit (/home/docker/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/utils/error-handler.js:97:27)
    at process.errorHandler (/home/docker/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at process.emit (events.js:210:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
/home/docker/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/utils/error-handler.js:97
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (/home/docker/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/utils/error-handler.js:97:27)
    at process.errorHandler (/home/docker/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at process.emit (events.js:210:5)
    at process._fatalException (internal/process/execution.js:150:25)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v12.13.0 --silent` to unset it.

### 5 `ls`

ls: cannot open directory '.': Stale file handle

--------------------------

So CLI container cannot perform rwx and browser throw 403 (Don´t have permissions to access this server / )
After the steps listed, I have tried: 

1. `fin system reset`
2. `fin project remove`
3. Removing volumes, containers, etc.
4. Starting all over again and again.
5. Switching to a large variety of Docker Desktop versions (18.0.6 - 2.0.0.3 - 2.1.0.3 - 2.1.0.4 - 2.1.0.5 - 2.3.0.2)
6. `DOCKSAL_NFS_PATH=/Users/gn.rodriguez/Documents/Sites/test`
7. and `DOCKSAL_NFS_PATH=/System/Volumes/Data/Users/gn.rodriguez/Documents/Sites/test`
8. `/etc/exports`
```
# <ds-nfs docksal
/System/Volumes/Data/Users/Users/gn.rodriguez/Documents/Sites/ 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
```
and 

```
# <ds-nfs docksal
/Users/gn.rodriguez/Documents/Sites/ 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
```

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
COMPOSE_FILE:
/Users/gn.rodriguez/.docksal/stacks/volumes-nfs.yml
/Users/gn.rodriguez/.docksal/stacks/stack-default.yml
/Users/gn.rodriguez/Documents/Sites/.docksal/docksal.yml
ENV_FILE:
/Users/gn.rodriguez/Documents/Sites/.docksal/docksal.env

PROJECT_ROOT: /Users/gn.rodriguez/Documents/Sites
DOCROOT: docroot
VIRTUAL_HOST: sites.docksal
VIRTUAL_HOST_ALIASES: *.sites.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32774

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: sites.docksal
      GIT_USER_EMAIL: ''
      GIT_USER_NAME: ''
      HOST_GID: '20'
      HOST_UID: '504'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: sites.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.10-php7.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/gn.rodriguez/Documents/Sites
      io.docksal.virtual-host: sites.docksal,*.sites.docksal,sites.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: :/Users/gn.rodriguez/Documents/Sites
      o: addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,actimeo=1
      type: nfs

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.15.4
Darwin AR-IT18203 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.95.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.24.1
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

███  DOCKER
EXPECTED VERSION: 19.03.4

Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Fri Oct 18 15:48:38 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
 ALERT:  Please update Docker Desktop to the latest version manually.
         Expected Docker Desktop version: 2.0.0.3
project             STATUS                    virtual host                                    project root
sites               Up 35 minutes (healthy)   sites.docksal,*.sites.docksal,sites.docksal.*   /Users/gn.rodriguez/Documents/Sites

███  DOCKSAL: VIRTUAL HOSTS
*.sites.docksal
sites.docksal.*
sites.docksal

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                      NAMES
e4a4bf212c61        docksal/apache:2.4-2.3    "httpd-foreground"       35 minutes ago      Up 35 minutes (healthy)   80/tcp, 443/tcp                            sites_web_1
d7e186a102e8        docksal/mysql:5.6-1.4     "docker-entrypoint.s…"   36 minutes ago      Up 35 minutes (healthy)   0.0.0.0:32774->3306/tcp                    sites_db_1
d4d884bd26e3        docksal/cli:2.10-php7.3   "/opt/startup.sh sup…"   36 minutes ago      Up 35 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                 sites_cli_1
46976b8c4410        docksal/mysql:5.6-1.4     "docker-entrypoint.s…"   41 minutes ago      Up 41 minutes (healthy)   0.0.0.0:32772->3306/tcp                    test_db_1
b42bd136f047        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   41 minutes ago      Up 41 minutes (healthy)                                              docksal-ssh-agent
3ea412d3b8cb        docksal/dns:1.1           "docker-entrypoint.s…"   41 minutes ago      Up 41 minutes (healthy)   0.0.0.0:53->53/udp                         docksal-dns
4cd3ee46e933        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   41 minutes ago      Up 41 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
5f9bf6a5e379        _default            bridge              local
8e00b0816253        bridge              bridge              local
29fed7e7ac7f        host                host                local
0e63e5d06486        none                null                local
5783d05b0da3        sites_default       bridge              local
2549dcf49a6f        test_default        bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3
DETECTED VERSION: 2.1.0.3

███  HDD Usage
Filesystem      Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1s1   466Gi   10Gi  411Gi     3%  487562 4881965318    0%   /
devfs          195Ki  195Ki    0Bi   100%     676          0  100%   /dev
/dev/disk1s2   466Gi   43Gi  411Gi    10%  424548 4882028332    0%   /System/Volumes/Data
/dev/disk1s5   466Gi  1.0Gi  411Gi     1%       1 4882452879    0%   /private/var/vm
map auto_home    0Bi    0Bi    0Bi   100%       0          0  100%   /System/Volumes/Data/home
map -fstab       0Bi    0Bi    0Bi   100%       0          0  100%   /System/Volumes/Data/Network/Servers
/dev/disk1s4   466Gi  504Mi  411Gi     1%      43 4882452837    0%   /Volumes/Recovery
  ```

</details>
