### ISSUE TITLE
MacOs Catalina 10.15: Permissions issue with a shared folder 

### ISSUE THREAD

**Issue by ddrozdik** [docksal/docksal#1351]
**Description**

I can't recall when the first time I got this issue, probably 2-3 months before. 

Everything works fine except one thing when PHP inside the container is trying to create anything (folder or file) with write permission (0777), files or folders are created with reading and execution permissions only (0755). 

See example: 
I have a `cache` folder with 777 permissions
![image](https://user-images.githubusercontent.com/6285570/82445118-f4c7ab00-9aac-11ea-9593-448c3d28ab5c.png)
then via PHP, my application creates `assetic` folder with 777 permissions. 
![image](https://user-images.githubusercontent.com/6285570/82445228-1fb1ff00-9aad-11ea-9f1e-09c87ea6b776.png)

When I set 0777 permissions outside of the container then the application can write into this directory, but again all files or folders are created with 755 permissions. 

Have you ever seen anything like this? 

**Shared folder configuration in VirtualBox:**
<details>
  <summary>see screenshot</summary>

![image](https://user-images.githubusercontent.com/6285570/82445438-77506a80-9aad-11ea-99c0-cb66a986364c.png)

</details>

**Output of `fin config`:**
<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: projectname
COMPOSE_FILE:
/Users/dmitry/.docksal/stacks/volumes-bind.yml
/Users/dmitry/.docksal/stacks/stack-default.yml
/Users/dmitry/Projects/projectname/.docksal/docksal.yml
ENV_FILE:
/Users/dmitry/Projects/projectname/.docksal/docksal.env
/Users/dmitry/Projects/projectname/.docksal/docksal-local.env

PROJECT_ROOT: /Users/dmitry/Projects/projectname
DOCROOT: .
VIRTUAL_HOST: projectname.docksal
VIRTUAL_HOST_ALIASES: *.projectname.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    build:
      context: /Users/dmitry/Projects/projectname/.docksal/services/cli
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '1'
      COMPOSER_DISABLE_XDEBUG_WARN: '1'
      DOCROOT: .
      DRUSH_ALLOW_XDEBUG: '1'
      DRUSH_OPTIONS_URI: projectname.docksal
      GIT_USER_EMAIL: null
      GIT_USER_NAME: null
      HOST_GID: '20'
      HOST_UID: '501'
      HTTPS: "on"
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SITE_DIRECTORY: null
      SITE_ENVIRONMENT: dev
      SOURCE_ALIAS: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: projectname.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: projectname_cli
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.7
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: mv2020pass
      APACHE_BASIC_AUTH_USER: mv
      APACHE_DOCUMENTROOT: /var/www/.
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/dmitry/Projects/projectname
      io.docksal.virtual-host: projectname.docksal,*.projectname.docksal,projectname.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/dmitry/Projects/projectname
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>

  <summary>fin sysinfo output</summary>

```
███  OS
Darwin Mac OS X 10.15.4
Darwin ddrozdik-2.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : /System/Volumes/Data/Users
NFS EXPORTS:

# <ds-nfs docksal
/System/Volumes/Data/Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.95.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.24.1
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

███  DOCKER
EXPECTED VERSION: 19.03.4

Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Fri Oct 18 15:48:38 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:55:51 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.2
docker-machine version 0.16.2, build bd45ab13

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
default   -        virtualbox   Error                                         Unknown    machine does not exist
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v19.03.4

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                                      project root
projectname      Up 24 minutes       projectname.docksal,*.projectname.docksal,projectname.docksal.*   /Users/dmitry/Projects/projectname

███  DOCKSAL: VIRTUAL HOSTS
*.projectname.docksal
projectname.docksal.*
projectname.docksal

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                      NAMES
cde1feba6c7a        docksal/web:2.1-apache2.4   "httpd-foreground"       25 minutes ago      Up 24 minutes             80/tcp, 443/tcp                            projectname_web_1
0a73d5a53aa9        projectname_cli          "/opt/startup.sh sup…"   25 minutes ago      Up 25 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                 projectname_cli_1
37e16802a190        docksal/db:1.2-mysql-5.7    "/entrypoint.sh mysq…"   25 minutes ago      Up 25 minutes             0.0.0.0:32768->3306/tcp                    projectname_db_1
d76938c8a228        docksal/ssh-agent:1.3       "docker-entrypoint.s…"   27 minutes ago      Up 27 minutes (healthy)                                              docksal-ssh-agent
e9adb08392f5        docksal/dns:1.1             "docker-entrypoint.s…"   27 minutes ago      Up 27 minutes (healthy)   0.0.0.0:53->53/udp                         docksal-dns
e59283a4293c        docksal/vhost-proxy:1.5     "docker-entrypoint.s…"   27 minutes ago      Up 27 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                       DRIVER              SCOPE
626d962e0c32        _default                   bridge              local
8040ca8b764f        bridge                     bridge              local
c78ee610dc85        website_default   bridge              local
ed02cb857b23        host                       host                local
518c341ede12        projectname_default     bridge              local
207d88a6eb5e        none                       null                local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.34
5.2.40r137108

███  DOCKSAL MOUNTS
192.168.64.1:/System/Volumes/Data/Users on /System/Volumes/Data/Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.64.1,mountvers=3,mountport=669,mountproto=udp,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G      9.3G     34.4G  21% /mnt/sda1
```

</details>
