### ISSUE TITLE
Windows server IP address could not be found.

### ISSUE THREAD

**Issue by jakewhiteley-gc** [docksal/docksal#1352]
**Description**

I had a lot of issues installing so far. First I tried the virtualbox version and would get forbidden errors when accessing the *.docksal url. I decided to try the docker version instead.

No issues during install, but now the dns does not seem to be working.

When running `fin up` there are no errors and everything is reported as being successful.

I have run `fin hosts add` but still not working.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
COMPOSE_PROJECT_NAME_SAFE: test
COMPOSE_FILE:
/home/jake/.docksal/stacks/volumes-bind.yml
/home/jake/.docksal/stacks/stack-default-nodb.yml
/c/Users/twent/sites/test/.docksal/docksal.yml
ENV_FILE:
/c/Users/twent/sites/test/.docksal/docksal.env

PROJECT_ROOT: /c/Users/twent/sites/test
DOCROOT: docroot
VIRTUAL_HOST: test.docksal
VIRTUAL_HOST_ALIASES: *.test.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: test.docksal
      GIT_USER_EMAIL: ''
      GIT_USER_NAME: ''
      HOST_GID: '1000'
      HOST_UID: '1000'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: test.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.10-php7.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /c/Users/twent/sites/test
      io.docksal.virtual-host: test.docksal,*.test.docksal,test.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/twent/sites/test
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  OS
WSL Ubuntu 18.04
Linux DESKTOP-DALKDS6 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.95.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.24.1
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

███  DOCKER
EXPECTED VERSION: 19.03.4

Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:49:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
 ALERT:  Please update Docker Desktop to the latest version manually.
         Expected Docker Desktop version: 2.0.0.3
project             STATUS                   virtual host                                 project root
test                Up 9 minutes (healthy)   test.docksal,*.test.docksal,test.docksal.*   /c/Users/twent/sites/test

███  DOCKSAL: VIRTUAL HOSTS
*.test.docksal
test.docksal.*
test.docksal

███  DOCKSAL: DNS
curl: (6) Could not resolve host: dns-test.docksal
ERROR: Requesting http://dns-test.docksal failed!

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                   PORTS                                      NAMES
fa4813d16a42        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   5 minutes ago       Up 5 minutes (healthy)                                              docksal-ssh-agent
b93c3eb29269        docksal/dns:1.1           "docker-entrypoint.s…"   6 minutes ago       Up 6 minutes (healthy)   0.0.0.0:53->53/udp                         docksal-dns
05ade9936dc6        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   6 minutes ago       Up 6 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy
ad8834665b78        docksal/apache:2.4-2.3    "httpd-foreground"       9 minutes ago       Up 9 minutes (healthy)   80/tcp, 443/tcp                            test_web_1
7c53577aa526        docksal/cli:2.10-php7.3   "/opt/startup.sh sup…"   9 minutes ago       Up 9 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                 test_cli_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
2c239136f0f6        _default            bridge              local
4f8922b9d251        bridge              bridge              local
9644974a3fdf        host                host                local
acb8b98b0f85        none                null                local
b8d8e732685c        test_default        bridge              local
cd1e073d9bec        twent_default       bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3
DETECTED VERSION: 2.1.0.3

███  HDD Usage
Caption  FreeSpace     Size
C:       211012501504  478923128832
  ```

</details>

<br>

**other outputs**

<details>
<summary>ipconfig /all</summary>

```
Windows IP Configuration

   Host Name . . . . . . . . . . . . : DESKTOP-DALKDS6
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : lan

Ethernet adapter vEthernet (DockerNAT):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #2
   Physical Address. . . . . . . . . : 00-15-5D-01-52-02
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 10.0.75.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
   Default Gateway . . . . . . . . . :
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : lan
   Description . . . . . . . . . . . : Realtek PCIe GbE Family Controller
   Physical Address. . . . . . . . . : E0-D5-5E-64-B2-F8
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::60a1:d089:a3f3:c4bf%19(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.1.82(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : 22 May 2020 12:48:45
   Lease Expires . . . . . . . . . . : 23 May 2020 12:49:02
   Default Gateway . . . . . . . . . : 192.168.1.254
   DHCP Server . . . . . . . . . . . : 192.168.1.254
   DHCPv6 IAID . . . . . . . . . . . : 115397982
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-23-E6-27-49-E0-D5-5E-64-B2-F8
   DNS Servers . . . . . . . . . . . : 192.168.1.254
   NetBIOS over Tcpip. . . . . . . . : Enabled

Wireless LAN adapter Local Area Connection* 9:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
   Physical Address. . . . . . . . . : 7E-8B-CA-0F-0A-1A
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Local Area Connection* 10:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2
   Physical Address. . . . . . . . . : 7C-8B-CA-0F-0A-1A
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter WiFi:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : lan
   Description . . . . . . . . . . . : TP-Link Wireless USB Adapter
   Physical Address. . . . . . . . . : 7C-8B-CA-0F-0A-1A
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Ethernet adapter vEthernet (Default Switch):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   Physical Address. . . . . . . . . : 00-15-5D-71-DE-41
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::8876:bf26:f087:3e95%25(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.17.6.129(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 419435869
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-23-E6-27-49-E0-D5-5E-64-B2-F8
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled
```
</details>

<details>
<summary>netsh interface ip show config</summary>

```
Configuration for interface "Loopback Pseudo-Interface 1"
    DHCP enabled:                         No
    IP Address:                           192.168.64.1
    Subnet Prefix:                        192.168.64.0/24 (mask 255.255.255.0)
    IP Address:                           192.168.64.100
    Subnet Prefix:                        192.168.64.0/24 (mask 255.255.255.0)
    IP Address:                           127.0.0.1
    Subnet Prefix:                        127.0.0.0/8 (mask 255.0.0.0)
    InterfaceMetric:                      10
    Statically Configured DNS Servers:    192.168.64.100
    Register with which suffix:           None
    Statically Configured WINS Servers:   None

Configuration for interface "vEthernet (DockerNAT)"
    DHCP enabled:                         No
    IP Address:                           10.0.75.1
    Subnet Prefix:                        10.0.75.0/28 (mask 255.255.255.240)
    InterfaceMetric:                      15
    Statically Configured DNS Servers:    None
    Register with which suffix:           Primary only
    Statically Configured WINS Servers:   None

Configuration for interface "Ethernet"
    DHCP enabled:                         Yes
    IP Address:                           192.168.1.82
    Subnet Prefix:                        192.168.1.0/24 (mask 255.255.255.0)
    Default Gateway:                      192.168.1.254
    Gateway Metric:                       0
    InterfaceMetric:                      25
    DNS servers configured through DHCP:  192.168.1.254
    Register with which suffix:           Primary only
    WINS servers configured through DHCP: None

Configuration for interface "Local Area Connection* 9"
    DHCP enabled:                         Yes
    InterfaceMetric:                      25
    DNS servers configured through DHCP:  None
    Register with which suffix:           Primary only
    WINS servers configured through DHCP: None

Configuration for interface "Local Area Connection* 10"
    DHCP enabled:                         Yes
    InterfaceMetric:                      25
    DNS servers configured through DHCP:  None
    Register with which suffix:           Primary only
    WINS servers configured through DHCP: None

Configuration for interface "WiFi"
    DHCP enabled:                         Yes
    IP Address:                           192.168.1.69
    Subnet Prefix:                        192.168.1.0/24 (mask 255.255.255.0)
    Default Gateway:                      192.168.1.254
    Gateway Metric:                       0
    InterfaceMetric:                      50
    DNS servers configured through DHCP:  192.168.1.254
    Register with which suffix:           Primary only
    WINS servers configured through DHCP: None

Configuration for interface "vEthernet (Default Switch)"
    DHCP enabled:                         No
    IP Address:                           172.17.6.129
    Subnet Prefix:                        172.17.6.128/28 (mask 255.255.255.240)
    InterfaceMetric:                      5000
    Statically Configured DNS Servers:    None
    Register with which suffix:           None
    Statically Configured WINS Servers:   None

```
</details>
