### ISSUE TITLE
Unable to disable docksal-dns

### ISSUE THREAD

**Issue by kwiechmann** [docksal/docksal#1375]
**Description**

Background: I work for a large company that uses Cisco AnyConnect. A special DNS server (dnscrypt-proxy AKA "Umbrella") is used to protect Macs centrally. If this DNS server is not killed (breaks company's AUP) before starting fin, startup fails with: 

```
docker: Error response from daemon: Ports are not available: listen udp 0.0.0.0:53: bind: address already in use.
```

Although killing the process identified with the lsof command works before fin start, the central IT group "understands" but are nonetheless very happy about it. Furthermore I have been warned that in the future disabling Umbrella will eventually not be possible. 

I would love to continue to use the docksal DNS solution but to be compliant I am exploring disabling the automatic solution and working with fin hosts. To do so, I am following these instructions which do not seem to any effect: https://v1-11-0.docs.docksal.io/core/system-dns/#disabling-the-resolver

**Steps to reproduce the issue:**

1. Open $HOME/.docksal/docksal.env and add DOCKSAL_NO_DNS_RESOLVER=true
2. cd docksal project directory
3. fin start

**Describe the results you received:**
```
$ sudo lsof -i :53
COMMAND         PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
dnscrypt-proxy 1255 nobody   44u  IPv4 0xae2a6d4bfbf90edb      0t0  UDP localhost:domain
dnscrypt-proxy 1255 nobody   45u  IPv4 0xae2a6d4c0cbe2b83      0t0  TCP localhost:domain (LISTEN)

$fin start
 ALERT:  Some Docksal services were not running
         Restarting Docksal system services...
Configuring network settings...
Configuring NFS shares...
NFS shares are already configured
Resetting Docksal system services...
 * proxy
 * dns
   upstream 10.0.0.1
docker: Error response from daemon: Ports are not available: listen udp 0.0.0.0:53: bind: address already in use.
 ERROR:  Failed starting the DNS service.
```

**Describe the results you expected:**

Project environment starts when the corporate "Umbrella" DNS is enabled.

**Output of `fin config`:**

<details>
  <summary>fin config output (to get this output, had to kill Umbrella so I could get past the "bind already in use error")</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: jnjbrqc
COMPOSE_FILE:
/Users/kwiechma/.docksal/stacks/volumes-bind.yml
/Users/kwiechma/.docksal/stacks/stack-default.yml
/Users/kwiechma/docksal-sites/jnjbrqc/.docksal/docksal.yml
ENV_FILE:
/Users/kwiechma/docksal-sites/jnjbrqc/.docksal/docksal.env
/Users/kwiechma/docksal-sites/jnjbrqc/.docksal/docksal-local.env

PROJECT_ROOT: /Users/kwiechma/docksal-sites/jnjbrqc
DOCROOT: docroot
VIRTUAL_HOST: jnjbrqc.docksal
VIRTUAL_HOST_ALIASES: *.jnjbrqc.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:33888

Docker Compose configuration
---------------------
services:
  cli:
    build:
      context: /Users/kwiechma/docksal-sites/jnjbrqc/.docksal/services/cli
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '1'
      COMPOSER_DISABLE_XDEBUG_WARN: '1'
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '1'
      DRUSH_OPTIONS_URI: jnjbrqc.docksal
      GIT_USER_EMAIL: kwiechma@ITS.JNJ.com
      GIT_USER_NAME: Wiechmann, Kevin [ITSUS]
      HOST_GID: '20'
      HOST_UID: '501'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: jnjbrqc.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: jnjbrqc_cli
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 33888:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  solr:
    build:
      context: /Users/kwiechma/docksal-sites/jnjbrqc/.docksal/services/solr
    image: jnjbrqc_solr
    ports:
    - 8983:8983/tcp
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/kwiechma/docksal-sites/jnjbrqc
      io.docksal.virtual-host: jnjbrqc.docksal,*.jnjbrqc.docksal,jnjbrqc.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/kwiechma/docksal-sites/jnjbrqc
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output (same comment as above for fin config)</summary>

  ```
███  OS
Darwin Mac OS X 10.15.5
Darwin WITSC02VT0PDHTD 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.95.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.24.1
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

███  DOCKER
EXPECTED VERSION: 19.03.4

Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Fri Oct 18 15:48:38 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
project             STATUS                   virtual host                                          project root
jnjbrqc             Up 2 minutes (healthy)   jnjbrqc.docksal,*.jnjbrqc.docksal,jnjbrqc.docksal.*   /Users/kwiechma/docksal-sites/jnjbrqc

███  DOCKSAL: VIRTUAL HOSTS
*.jnjbrqc.docksal
jnjbrqc.docksal.*
jnjbrqc.docksal

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                   PORTS                                      NAMES
84205ca3c0b4        docksal/ssh-agent:1.3          "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes (healthy)                                              docksal-ssh-agent
2271a64871bb        docksal/dns:1.1                "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes (healthy)   0.0.0.0:53->53/udp                         docksal-dns
6884b686b8eb        docksal/vhost-proxy:1.5        "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy
acc9574e6b94        jnjbrqc_solr                   "/usr/bin/supervisor…"   40 hours ago        Up 2 minutes             0.0.0.0:8983->8983/tcp                     jnjbrqc_solr_1
eb918e0e6cbd        docksal/apache:2.4-2.3         "httpd-foreground"       2 weeks ago         Up 2 minutes (healthy)   80/tcp, 443/tcp                            jnjbrqc_web_1
6d4665393ccf        jnjbrqc_cli                    "/opt/startup.sh sup…"   2 weeks ago         Up 2 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                 jnjbrqc_cli_1
efef2e9c3311        docksal/mysql:5.6-1.4          "docker-entrypoint.s…"   2 weeks ago         Up 2 minutes (healthy)   0.0.0.0:33888->3306/tcp                    jnjbrqc_db_1
ad3cac845c25        bosolutions/os-l1-cli:prod     "/bin/docker-entrypo…"   9 months ago        Up 4 hours                                                          os_cli
6cbf787e43f9        bosolutions/os-l1-mysql:prod   "docker-entrypoint.s…"   9 months ago        Up 4 hours               0.0.0.0:3307->3306/tcp                     os_db
fd061f675cb8        memcached                      "docker-entrypoint.s…"   9 months ago        Up 4 hours               11211/tcp                                  os_memcached

███  DOCKER: NETWORKS
NETWORK ID          NAME                            DRIVER              SCOPE
dcc9bbe26770        _default                        bridge              local
3d1d62e606b6        bridge                          bridge              local
6ea65146e08e        brqc_default                    bridge              local
cb36981eb947        config_canvas_ops               bridge              local
b0886c43844a        graphql_default                 bridge              local
3b2c6da6eae2        host                            host                local
98450e6102ba        iq2_default                     bridge              local
cdad10c47fae        jnjbrqc_default                 bridge              local
03c55b55a30f        jnjhwsch88-2_default            bridge              local
80bb0bbb04fe        jnjhwsch-stage_default          bridge              local
763b7e0dddfc        jnjhwsch_default                bridge              local
371dd97032d3        jnjinnovation-classic_default   bridge              local
2532c0122269        jnjinnovation-old_default       bridge              local
ed768222b205        jnjinnovation_default           bridge              local
4b5b53eb6a3f        jnjinnovationold2_default       bridge              local
c80674ea518b        none                            null                local
a2d9bbc159df        planyo2_default                 bridge              local
b9899d727d8c        planyo3_default                 bridge              local
3663e362d350        planyo_default                  bridge              local
b24a60a63d52        umami-search_default            bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3
DETECTED VERSION: 2.3.0.3

███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
/dev/disk1s5    466G   11G   36G  23% /
/dev/disk1s4    466G  1.1G   36G   3% /private/var/vm
/dev/disk1s3    466G  505M   36G   2% /Volumes/Recovery

  ```

</details>
