### ISSUE TITLE
test.docksal will not resolve

### ISSUE THREAD

**Issue by jtjones3** [docksal/docksal#1378]
**Description**

test.docksal is suddenly not working anymore.

**Steps to reproduce the issue:**

1. local Drupal docksal site was working fine until a couple of weeks ago and then could not be found by the browser
2. Did some research and have noticed test.docksal will not resolve - "ping: cannot resolve test.docksal: Unknown host"
3. 

**Describe the results you received:**

"ping: cannot resolve test.docksal: Unknown host"

**Describe the results you expected:**

Expected behavior...

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: ucd-dice
COMPOSE_FILE:
/Users/xxxxx/.docksal/stacks/volumes-bind.yml
/Users/xxxxx/.docksal/stacks/stack-default.yml
/Users/xxxxx/Sites/Drupal/ucd-dice/.docksal/docksal.yml
ENV_FILE:
/Users/xxxxx/Sites/Drupal/ucd-dice/.docksal/docksal.env
/Users/xxxxx/Sites/Drupal/ucd-dice/.docksal/docksal-local.env

PROJECT_ROOT: /Users/xxxxx/Sites/Drupal/ucd-dice
DOCROOT: web
VIRTUAL_HOST: ucd-dice.docksal
VIRTUAL_HOST_ALIASES: *.ucd-dice.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: web
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: ucd-dice.docksal
      GIT_USER_EMAIL: xxxxx
      GIT_USER_NAME: xxxxx
      HOST_GID: '20'
      HOST_UID: '504'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_PORT: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PANTHEON_ENV: test
      PANTHEON_SITE: ucd-dice
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_ACQUIACLI_KEY: null
      SECRET_ACQUIACLI_SECRET: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: 0oxMl*****a57fI
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: ucd-dice.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.6-php7.2
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /Users/xxxxxxx/.docksal/tmp/ucd-dice:/Users/xxxxx/.docksal/tmp/ucd-dice:ro
    - /Users/xxxxxx/Sites/Drupal/ucd-dice/.docksal/etc/drush:/etc/drush:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.5
    logging:
      options:
        max-file: '10'
        max-size: 1m
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/web
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/xxxxxxx/Sites/Drupal/ucd-dice
      io.docksal.virtual-host: ucd-dice.docksal,*.ucd-dice.docksal,ucd-dice.docksal.*
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/xxxxxx/Sites/Drupal/ucd-dice
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.14.6
Darwin C02L714EFFT3 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.97.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.26.0
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

███  DOCKER
EXPECTED VERSION: 19.03.5

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
project             STATUS                    virtual host                                             project root
ucd-dice            Up 26 minutes (healthy)   ucd-dice.docksal,*.ucd-dice.docksal,ucd-dice.docksal.*   /Users/xxxxx/Sites/Drupal/ucd-dice

███  DOCKSAL: VIRTUAL HOSTS
*.ucd-dice.docksal
ucd-dice.docksal.*
ucd-dice.docksal

███  DOCKSAL: DNS
curl: (6) Could not resolve host: dns-test.docksal
ERROR: Requesting http://dns-test.docksal failed!

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                        NAMES
80af35c02cfb        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   37 minutes ago      Up 28 minutes (healthy)                                                docksal-ssh-agent
b7af589d83b3        docksal/dns:1.1           "docker-entrypoint.s…"   38 minutes ago      Up 28 minutes (healthy)   0.0.0.0:53->53/udp                           docksal-dns
b70ebfff59de        docksal/vhost-proxy:1.6   "docker-entrypoint.s…"   38 minutes ago      Up 28 minutes (healthy)   0.0.0.0:443->443/tcp, 0.0.0.0:8080->80/tcp   docksal-vhost-proxy
e4a4fd13426a        docksal/apache:2.4-2.3    "httpd-foreground"       2 hours ago         Up 26 minutes (healthy)   80/tcp, 443/tcp                              ucd-dice_web_1
3c3b38711ce3        docksal/cli:2.6-php7.2    "/opt/startup.sh sup…"   2 hours ago         Up 26 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                   ucd-dice_cli_1
ade99ab6a36f        docksal/mysql:5.6-1.5     "docker-entrypoint.s…"   2 hours ago         Up 26 minutes (healthy)   0.0.0.0:32768->3306/tcp                      ucd-dice_db_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
6b36a24a124b        _default            bridge              local
e27e21c5c779        bridge              bridge              local
c7bd103e8fc9        host                host                local
9f962036422d        none                null                local
1f6350b7014c        ucd-dice_default    bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3
DETECTED VERSION: 2.3.0.3

███  HDD Usage
Filesystem                                             Size   Used  Avail Capacity  iused               ifree %iused  Mounted on
/dev/disk1s1                                          466Gi  410Gi   53Gi    89%  8400662 9223372036846375145    0%   /
devfs                                                 200Ki  200Ki    0Bi   100%      691                   0  100%   /dev
/dev/disk1s4                                          466Gi  2.0Gi   53Gi     4%        2 9223372036854775805    0%   /private/var/vm
/dev/disk2s1                                          932Gi  610Gi  321Gi    66% 25996873          4268970406    1%   /Volumes/work_backup
map -hosts                                              0Bi    0Bi    0Bi   100%        0                   0  100%   /net
map auto_home                                           0Bi    0Bi    0Bi   100%        0                   0  100%   /home
map -fstab                                              0Bi    0Bi    0Bi   100%        0                   0  100%   /Network/Servers
com.apple.TimeMachine.2020-07-16-125723@/dev/disk1s1  466Gi  409Gi   53Gi    89%  8402394 9223372036846373413    0%   /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/C02V82MCHTD5/2020-07-16-125723/Macintosh HD
com.apple.TimeMachine.2020-07-16-091106@/dev/disk1s1  466Gi  402Gi   53Gi    89%  8472875 9223372036846302932    0%   /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/C02V82MCHTD5/2020-07-16-091106/Macintosh HD
  ```

</details>
