### ISSUE TITLE
[1.14]  php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by ApacheEx** [docksal/docksal#1382]
**Description**

I'm not sure where exactly this issue was introduced (1.13.3 or 1.14). 
But, after upgrading from fin 1.93 to 1.97 I face a problem with access between two docksal projects.

**Steps to reproduce the issue:**

1. Install latest docksal (1.14)
2. Create project-x and project-y with stack (`DOCKSAL_STACK="default-nodb"`, can be whatever)
3. in project-x run:
```
fin drush php
Psy Shell v0.9.9 (PHP 7.3.11 — cli) by Justin Hileman
>>> file_get_contents('http://project-y.docksal')
PHP Warning:  file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known in phar://eval()'d code on line 1
```

**Describe the results you expected:**

```
fin drush php
Psy Shell v0.9.9 (PHP 7.3.11 — cli) by Justin Hileman
>>> file_get_contents('http://project-y.docksal')
=> "<html><body>Hello, Docksal!</body></html>\n"
```

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: project-x
COMPOSE_FILE:
/Users/apacheex/.docksal/stacks/volumes-nfs.yml
/Users/apacheex/.docksal/stacks/stack-default-nodb.yml
/Users/apacheex/WEB/project-x/.docksal/docksal.yml
ENV_FILE:
/Users/apacheex/WEB/project-x/.docksal/docksal.env

PROJECT_ROOT: /Users/apacheex/WEB/project-x
DOCROOT: docroot
VIRTUAL_HOST: project-x.docksal
VIRTUAL_HOST_ALIASES: *.project-x.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: project-x.docksal
      GIT_USER_EMAIL: olegkuzava@gmail.com
      GIT_USER_NAME: ApacheEx
      HOST_GID: '20'
      HOST_UID: '501'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_ACQUIACLI_KEY: null
      SECRET_ACQUIACLI_SECRET: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: project-x.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.11-php7.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /Users/apacheex/.docksal/tmp/project-x:/Users/apacheex/.docksal/tmp/project-x:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/apacheex/WEB/project-x
      io.docksal.virtual-host: project-x.docksal,*.project-x.docksal,project-x.docksal.*
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: :/Users/apacheex/WEB/project-x
      o: addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,actimeo=1
      type: nfs

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.15.5
Darwin mb15.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : /Users
NFS EXPORTS:

# <ds-nfs docksal
/Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.97.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.26.0
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

███  DOCKER
EXPECTED VERSION: 19.03.5

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.2
docker-machine version 0.16.2, build bd45ab13

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v19.03.5   

███  DOCKSAL: PROJECTS
project             STATUS                    virtual host                                                         project root
project-y           Up 2 minutes (healthy)    project-y.docksal,*.project-y.docksal,project-y.docksal.*            /Users/apacheex/WEB/project-y
project-x           Up 3 minutes (healthy)    project-x.docksal,*.project-x.docksal,project-x.docksal.*            /Users/apacheex/WEB/project-x
ywv-react        Up 33 minutes (healthy)   ywv-react.docksal,*.ywv-react.docksal,ywv-react.docksal.*   /Users/apacheex/WEB/ywv-react
ywv              Up 30 minutes (healthy)   ywv.docksal,*.ywv.docksal,ywv.docksal.*                     /Users/apacheex/WEB/ywv

███  DOCKSAL: VIRTUAL HOSTS
*.project-x.docksal
*.project-y.docksal
*.ywv-react.docksal
*.ywv.docksal
pma.ywv.docksal
project-x.docksal.*
project-x.docksal
project-y.docksal.*
project-y.docksal
ywv-react.docksal.*
ywv-react.docksal
ywv.docksal.*
ywv.docksal

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                      NAMES
36aa93c8f248        docksal/apache:2.4-2.3    "httpd-foreground"       2 minutes ago       Up 2 minutes (healthy)    80/tcp, 443/tcp                            project-y_web_1
d7f43f765383        docksal/cli:2.11-php7.3   "/opt/startup.sh sup…"   2 minutes ago       Up 2 minutes (healthy)    22/tcp, 3000/tcp, 9000/tcp                 project-y_cli_1
faad29d99a6c        docksal/apache:2.4-2.3    "httpd-foreground"       3 minutes ago       Up 3 minutes (healthy)    80/tcp, 443/tcp                            project-x_web_1
9066cb3c054b        docksal/cli:2.11-php7.3   "/opt/startup.sh sup…"   3 minutes ago       Up 3 minutes (healthy)    22/tcp, 3000/tcp, 9000/tcp                 project-x_cli_1
950f98842eda        docksal/cli:2.10-php7.2   "/opt/startup.sh sup…"   7 minutes ago       Up 6 minutes (healthy)    22/tcp, 3000/tcp, 9000/tcp                 ywv_cli_1
1e42381e7879        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   32 minutes ago      Up 32 minutes (healthy)                                              docksal-ssh-agent
b7f58298a276        docksal/dns:1.1           "docker-entrypoint.s…"   32 minutes ago      Up 32 minutes (healthy)   0.0.0.0:53->53/udp                         docksal-dns
73f7eff1d990        docksal/vhost-proxy:1.6   "docker-entrypoint.s…"   32 minutes ago      Up 32 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy
51397d99fe2e        docksal/mysql:5.7-1.4     "docker-entrypoint.s…"   9 hours ago         Up 30 minutes (healthy)   33060/tcp, 0.0.0.0:33061->3306/tcp         ywv_db_1
dd575c4f99cf        docksal/apache:2.4-2.3    "httpd-foreground"       2 days ago          Up 33 minutes (healthy)   80/tcp, 443/tcp                            ywv-react_web_1
168643f9782e        docksal/cli:2.11-php7.3   "/opt/startup.sh sup…"   2 days ago          Up 33 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                 ywv-react_cli_1
d48cb0620eb1        docksal/apache:2.4-2.3    "httpd-foreground"       2 days ago          Up 30 minutes (healthy)   80/tcp, 443/tcp                            ywv_web_1
43a760f57aaf        adminer                   "entrypoint.sh docke…"   2 days ago          Up 30 minutes             8080/tcp                                   ywv_adminer_1
a5f7e79506cd        memcached:1.5             "docker-entrypoint.s…"   2 days ago          Up 30 minutes             11211/tcp                                  ywv_memcached_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                   DRIVER              SCOPE
995d1d9f4144        _default               bridge              local
f10a13a203ec        bridge                 bridge              local
67f4ddaa51ad        d8_default             bridge              local
63d9e7217982        host                   host                local
95ac090941bb        hybridauth_default     bridge              local
407bfeab6ff3        none                   null                local
f09a93f7fbf0        project-x_default      bridge              local
03f346390ee5        project-y_default      bridge              local
943a623b1704        ywv-app_default     bridge              local
84da10f15ad6        ywv-react_default   bridge              local
d08b88492aec        ywv-sdk_default     bridge              local
e72e1e400d2a        ywv_default         bridge              local

███  VIRTUALBOX
EXPECTED VERSION: 6.1.10
6.1.12r139181

███  DOCKSAL MOUNTS
192.168.64.1:/Users/apacheex/WEB/ywv-react on /mnt/sda1/var/lib/docker/volumes/ywv-react_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.64.1,mountvers=3,mountport=865,mountproto=udp,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.64.1,mountvers=3,mountport=865,mountproto=udp,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/apacheex/WEB/ywv on /mnt/sda1/var/lib/docker/volumes/ywv_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.64.1,mountvers=3,mountport=865,mountproto=udp,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/apacheex/WEB/project-x on /mnt/sda1/var/lib/docker/volumes/project-x_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.64.1,mountvers=3,mountport=865,mountproto=udp,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/apacheex/WEB/project-y on /mnt/sda1/var/lib/docker/volumes/project-y_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.64.1,mountvers=3,mountport=865,mountproto=udp,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G     12.6G     31.1G  29% /mnt/sda1
  ```

</details>

probably related: https://github.com/docksal/docksal/issues/1378
after `DOCKSAL_VERSION=v1.13.2 fin update` all work fine.
