### ISSUE TITLE
REQUIREMENTS_DOCKER set to REQUIREMENTS_DOCKER_DEBIAN too late to affect URL_DOCKER_NIX etc.

### ISSUE THREAD

**Issue by ethanbb** [docksal/docksal#1383]
**Description**

The recent update to support Ubuntu 20.04 and related distros breaks `fin update` for all Debian systems because currently, it requires Docker server version 19.03.9, but only downloads version 19.03.5.

Line 138, we have:
```bash
REQUIREMENTS_DOCKER='19.03.5'
REQUIREMENTS_DOCKER_DEBIAN='19.03.9'  # This is the earliest version available for Ubuntu 20.04 (focal) LTS
```

Then line 323:
```bash
URL_DOCKER_NIX="https://download.docker.com/linux/static/stable/x86_64/docker-${REQUIREMENTS_DOCKER}.tgz"
```

So at this point, the URL is still for version 19.03.5.

Then finally at line 7642:
```bash
# Use newer docker version on debian like systems
is_debian && REQUIREMENTS_DOCKER=${REQUIREMENTS_DOCKER_DEBIAN}
```

But when an update is triggered, the old download URL will still be used.

(I'd make a PR for this since it's fairly simple, but I'm really new to looking at the fin source and I'd rather not jump in and edit it yet.)

**Steps to reproduce the issue:**

1. Run `fin update` on a Debian-flavored system (including Ubuntu on WSL) with Docker server 19.03.9 not installed

**Describe the results you received:**

```
[STEP 3/4] Updating tools...
Installing docker client v19.03.9...
Downloading docker-19.03.5.tgz...
[...]
Running post update checks...
 ALERT:  Required Docker server version is 19.03.9
         Run fin update to update to the required version.
```

**Describe the results you expected:**

```
[STEP 3/4] Updating tools...
Installing docker client v19.03.9...
Downloading docker-19.03.9.tgz...
```

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: neuronet-composer
COMPOSE_FILE:
/home/ethan/.docksal/stacks/volumes-bind.yml
/home/ethan/.docksal/stacks/stack-default.yml
/d/DocksalProjects/neuronet-composer/.docksal/docksal.yml
/d/DocksalProjects/neuronet-composer/.docksal/docksal-local.yml
ENV_FILE:
/d/DocksalProjects/neuronet-composer/.docksal/docksal.env
/d/DocksalProjects/neuronet-composer/.docksal/docksal-local.env

PROJECT_ROOT: /d/DocksalProjects/neuronet-composer
DOCROOT: web
VIRTUAL_HOST: neuronet-composer.docksal
VIRTUAL_HOST_ALIASES: *.neuronet-composer.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '1'
      COMPOSER_DISABLE_XDEBUG_WARN: '1'
      DOCROOT: web
      DRUSH_ALLOW_XDEBUG: '1'
      DRUSH_OPTIONS_URI: neuronet-composer.docksal
      GIT_USER_EMAIL: ethanbblackwood@gmail.com
      GIT_USER_NAME: Ethan Blackwood
      HOST_GID: '1000'
      HOST_UID: '1000'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      NEURONET_SSH_USER: ethanbb
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_ACQUIACLI_KEY: null
      SECRET_ACQUIACLI_SECRET: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: neuronet-composer.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    extra_hosts:
      hosting.pmacs.upenn.edu: 172.16.100.203
    hostname: cli
    image: docksal/cli:2.11-php7.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    logging:
      options:
        max-file: '10'
        max-size: 1m
    ports:
    - 2222:22/tcp
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /c/Users/ethan/.ssh/id_rsa.pub:/home/docker/.ssh/host_key.pub:ro
    - /home/ethan/.docksal/tmp/neuronet-composer:/home/ethan/.docksal/tmp/neuronet-composer:ro
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.5
    logging:
      options:
        max-file: '10'
        max-size: 1m
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/web
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /d/DocksalProjects/neuronet-composer
      io.docksal.virtual-host: neuronet-composer.docksal,*.neuronet-composer.docksal,neuronet-composer.docksal.*
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /d/DocksalProjects/neuronet-composer
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
WSL Ubuntu 20.04
Linux Ethan-Dell 4.4.0-19041-Microsoft #1-Microsoft Fri Dec 06 14:06:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376

███  FIN
fin version: 1.97.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.26.0
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

███  DOCKER
EXPECTED VERSION: 19.03.9

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.2
docker-machine.exe version 0.16.2, build bd45ab13

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
docksal   -        virtualbox   Running   tcp://192.168.64.100:2376           v19.03.5

███  DOCKSAL: PROJECTS
 ALERT:  Required Docker server version is 19.03.9
         Run fin update to update to the required version.

project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS

███  DOCKSAL: DNS
curl: (6) Could not resolve host: dns-test.docksal
ERROR: Requesting http://dns-test.docksal failed!

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                      NAMES
71b95a23e6c4        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   50 minutes ago      Up 42 seconds (healthy)                                              docksal-ssh-agent
fe73a23f8191        docksal/dns:1.1           "docker-entrypoint.s…"   50 minutes ago      Up 42 seconds (healthy)   0.0.0.0:53->53/udp                         docksal-dns
35666232fb01        docksal/vhost-proxy:1.6   "docker-entrypoint.s…"   50 minutes ago      Up 42 seconds (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
ca756f96ee42        _default            bridge              local
91e3ccd6c35b        bridge              bridge              local
61d0ea773151        host                host                local
2423261e618f        neuronet_default    bridge              local
8741122ac06d        none                null                local

███  VIRTUALBOX
EXPECTED VERSION: 6.1.10
6.1.10r138449

███  DOCKSAL MOUNTS
^C ERROR:  Mounts matching 192.168.64* were not found!

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G      6.5G     37.2G  15% /mnt/sda1
  ```

</details>
