### ISSUE TITLE
server IP address could not be found

### ISSUE THREAD

**Issue by jtjones3** [docksal/docksal#1393]
I inherited a Drupal 8.7.11 site and obviously I need to upgrade the site to Drupal 8.8 (at least). The site works fine locally when running 8.7.11 but as soon as I start the upgraded process I get the following browser error on Chrome: `server IP address could not be found`

Problem/feature description...

**Describe the results you received:**

server IP address could not be found

**Describe the results you expected:**

display of the website locally

**Output of `fin config`:**

<details>
  <summary>---------------------
fin config output
</summary>

```
COMPOSE_PROJECT_NAME_SAFE: xxxxx
COMPOSE_FILE:
/Users/xxxxx/.docksal/stacks/volumes-nfs.yml
/Users/xxxxx/.docksal/stacks/stack-pantheon.yml
/Users/xxxxx/Sites/Drupal/xxxxx/.docksal/docksal.yml
ENV_FILE:
/Users/xxxxx/Sites/Drupal/xxxxx/.docksal/docksal.env
/Users/xxxxx/Sites/Drupal/xxxxx/.docksal/docksal-local.env

PROJECT_ROOT: /Users/xxxxx/Sites/Drupal/xxxxx
DOCROOT: web
VIRTUAL_HOST: a26.local
VIRTUAL_HOST_ALIASES: *.a26.local
IP: 192.168.64.100
MYSQL: 192.168.64.100:32769

Docker Compose configuration
---------------------
services:
  browser:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    hostname: browser
    image: selenium/standalone-chrome-debug:3.141.59-oxygen
    ports:
    - 59003:5900/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: web
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: a26.local
      GIT_USER_EMAIL: 
      GIT_USER_NAME: 
      HOST_GID: '20'
      HOST_UID: '504'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_PORT: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PANTHEON_ENV: dev
      PANTHEON_SITE: xxxxx
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: 0oxMl*****a57fI
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: a26.local
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.11-php7.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /Users/xxxxx/Sites/Drupal/xxxxx/.docksal/etc/drush:/etc/drush:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.7-1.5
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  redis:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      REDIS_MAXMEMORY: 256m
    hostname: redis
    image: wodby/redis:4.0
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: solr
    image: docksal/solr:1.0-solr3
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: solr.a26.local,solr.a26.local.*
      io.docksal.virtual-port: '8983'
    volumes:
    - project_root:/var/www:ro,nocopy,cached
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:4.1-2.0
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: varnish.a26.local,varnish.a26.local.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_FILE_PROXY:
      NGINX_BASIC_AUTH_PASS: null
      NGINX_BASIC_AUTH_USER: null
      NGINX_FCGI_HOST_PORT: cli:9000
      NGINX_SERVER_ROOT: /var/www/web
      NGINX_VHOST_PRESET: drupal
    hostname: web
    image: docksal/nginx:1.14-edge
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/xxxxx/Sites/Drupal/xxxxx
      io.docksal.virtual-host: a26.local,*.a26.local,a26.local,*.a26.local
    volumes:
    - /Users/xxxxx/Sites/Drupal/xxxxx/.docksal/etc/apache/host.conf:/usr/local/apache2/conf/extra/includes/host.conf:ro
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: :/Users/xxxxx/Sites/Drupal/xxxxx
      o: addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,actimeo=1
      type: nfs

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.14.6
Darwin C02L714EFFT3 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.93.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.24.1
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

███  DOCKER
EXPECTED VERSION: 19.03.4

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
project              STATUS                    virtual host                                  project root
xxxxx   Up 16 minutes (healthy)   a26.local,*.a26.local,a26.local,*.a26.local   /Users/xxxxx/Sites/Drupal/xxxxx

███  DOCKSAL: VIRTUAL HOSTS
*.a26.local
a26.local
solr.a26.local.*
solr.a26.local
varnish.a26.local.*
varnish.a26.local

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
da8ad8e6959c        selenium/standalone-chrome-debug:3.141.59-oxygen   "/opt/bin/entry_poin…"   23 hours ago        Up 16 minutes             4444/tcp, xxxxx_browser_1
520feac94d28        docksal/ssh-agent:1.3                              "docker-entrypoint.s…"   47 hours ago        Up 2 hours (healthy)                                                               docksal-ssh-agent
63f54879268d        docksal/dns:1.1                                    "docker-entrypoint.s…"   47 hours ago        Up 2 hours (healthy)      192.168.64.100:53->53/udp                                docksal-dns
d5e7e95cd6b1        docksal/vhost-proxy:1.5                            "docker-entrypoint.s…"   47 hours ago        Up 2 hours (healthy)      192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
567a85b757e1        docksal/varnish:4.1-2.0                            "docker-entrypoint.s…"   2 days ago          Up 16 minutes (healthy)   80/tcp, 6082/tcp                                         xxxxx_varnish_1
0d18561db369        docksal/nginx:1.14-edge                            "docker-entrypoint.s…"   2 days ago          Up 16 minutes (healthy)   80/tcp, 443/tcp                                          xxxxx_web_1
f9a2dbbd647f        docksal/mysql:5.7-1.5                              "docker-entrypoint.s…"   2 days ago          Up 16 minutes (healthy)   33060/tcp, 0.0.0.0:32769->3306/tcp                       xxxxx_db_1
e9240ec1a3bd        docksal/cli:2.11-php7.3                            "/opt/startup.sh sup…"   2 days ago          Up 16 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               xxxxx_cli_1
70b9e54e3a61        wodby/redis:4.0                                    "/docker-entrypoint.…"   2 days ago          Up 16 minutes             6379/tcp                                                 xxxxx_redis_1
277b9262d07c        docksal/solr:1.0-solr3                             "java -jar start.jar"    2 days ago          Up 16 minutes             8983/tcp                                                 xxxxx_solr_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                         DRIVER              SCOPE
12de6058766e        _default                     bridge              local
db7182acccf2        xxxxx_default   bridge              local
58286760d3af        bridge                       bridge              local
464ddea7d08e        host                         host                local
16071738f47a        none                         null                local
f18e4e800f45        ucd-dice_default             bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3
2.1.0.4

███  HDD Usage
Filesystem                                             Size   Used  Avail Capacity  iused               ifree %iused  Mounted on
/dev/disk1s1                                          466Gi  411Gi   49Gi    90%  8567881 9223372036846207926    0%   /
devfs                                                 200Ki  200Ki    0Bi   100%      692                   0  100%   /dev
/dev/disk1s4                                          466Gi  5.0Gi   49Gi    10%        5 9223372036854775802    0%   /private/var/vm
/dev/disk2s1                                          932Gi  620Gi  312Gi    67% 28247958          4266719321    1%   /Volumes/work_backup
map -hosts                                              0Bi    0Bi    0Bi   100%        0                   0  100%   /net
map auto_home                                           0Bi    0Bi    0Bi   100%        0                   0  100%   /home
map -fstab                                              0Bi    0Bi    0Bi   100%        0                   0  100%   /Network/Servers
com.apple.TimeMachine.2020-07-23-095548@/dev/disk1s1  466Gi  411Gi   49Gi    90%  8567782 9223372036846208025    0%   /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/C02V82MCHTD5/2020-07-23-095548/Macintosh HD
com.apple.TimeMachine.2020-07-23-072233@/dev/disk1s1  466Gi  413Gi   49Gi    90%  8564584 9223372036846211223    0%   /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/C02V82MCHTD5/2020-07-23-072233/Macintosh HD
  ```

</details>
