### ISSUE TITLE
This site can’t be reached - Win10

### ISSUE THREAD

**Issue by alexvrrb** [docksal/docksal#1404]
**Description**

I can't open any docksal website on my windows 10 laptop.

**Steps to reproduce the issue:**

1.  fin project create to create fresh d8 install
2.  Access http://testd8.docksal/
3.  Can't access the site

**Describe the results you received:**

`This site can’t be reachedtestd8.docksal’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN`

**Describe the results you expected:**

Expected website to load.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
 ALERT:  Running as root is not recommended
 ALERT:  Please update Docker Desktop to the latest version manually.
         Expected Docker Desktop version: 2.1.0.5
---------------------
COMPOSE_PROJECT_NAME_SAFE: testd8
COMPOSE_FILE:
/root/.docksal/stacks/volumes-bind.yml
/root/.docksal/stacks/stack-default.yml
/c/Users/Codena/d8/testd8/.docksal/docksal.yml
ENV_FILE:
/c/Users/Codena/d8/testd8/.docksal/docksal.env

PROJECT_ROOT: /c/Users/Codena/d8/testd8
DOCROOT: docroot
VIRTUAL_HOST: testd8.docksal
VIRTUAL_HOST_ALIASES: *.testd8.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32769

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: testd8.docksal
      GIT_USER_EMAIL: alexandar87@gmail.com
      GIT_USER_NAME: Alex
      HOST_GID: null
      HOST_UID: null
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_ACQUIACLI_KEY: null
      SECRET_ACQUIACLI_SECRET: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: testd8.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.11-php7.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /root/.docksal/tmp/testd8:/root/.docksal/tmp/testd8:ro
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.5
    logging:
      options:
        max-file: '10'
        max-size: 1m
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /c/Users/Codena/d8/testd8
      io.docksal.virtual-host: testd8.docksal,*.testd8.docksal,testd8.docksal.*
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/Codena/d8/testd8
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
   ALERT:  Running as root is not recommended
███  OS
WSL Ubuntu 18.04
Linux Codena-Win 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.99.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.26.0
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

███  DOCKER
EXPECTED CLIENT VERSION: 19.03.9
EXPECTED SERVER VERSION: 19.03.8

Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:22:47 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
 ALERT:  Please update Docker Desktop to the latest version manually.
         Expected Docker Desktop version: 2.1.0.5
project             STATUS                    virtual host                                       project root
testd8              Up 17 minutes (healthy)   testd8.docksal,*.testd8.docksal,testd8.docksal.*   /c/Users/Codena/d8/testd8

███  DOCKSAL: VIRTUAL HOSTS
*.testd8.docksal
testd8.docksal.*
testd8.docksal

███  DOCKSAL: NETWORKING

DOCKSAL_IP: 192.168.64.100
DOCKSAL_VHOST_PROXY_IP:
DOCKSAL_DNS_IP:
DOCKSAL_DNS_DISABLED: 0
DOCKSAL_NO_DNS_RESOLVER: 0
DOCKSAL_DNS_UPSTREAM:
DOCKSAL_DNS_DOMAIN: docksal

Checking connectivity to http://dns-test.docksal...
Host: FAIL
Containers: PASS

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
b0321a0611a7        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   11 minutes ago      Up 11 minutes (healthy)                                                            docksal-ssh-agent
8c0e55f1dec7        docksal/dns:1.1           "docker-entrypoint.s…"   11 minutes ago      Up 11 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
daa267b9caea        docksal/vhost-proxy:1.6   "docker-entrypoint.s…"   11 minutes ago      Up 11 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
8ed23980e294        docksal/apache:2.4-2.3    "httpd-foreground"       17 minutes ago      Up 17 minutes (healthy)   80/tcp, 443/tcp                                          testd8_web_1
b52c241a4694        docksal/cli:2.11-php7.3   "/opt/startup.sh sup…"   17 minutes ago      Up 17 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               testd8_cli_1
12d9abf80241        docksal/mysql:5.6-1.5     "docker-entrypoint.s…"   26 minutes ago      Up 26 minutes (healthy)   0.0.0.0:32769->3306/tcp                                  testd8_db_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
0354bdf0e7de        _default            bridge              local
1fd41a1f8829        bridge              bridge              local
819adbb96faf        host                host                local
9443c4429521        none                null                local
0643d73c5076        testd8_default      bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.1.0.5
DETECTED VERSION: 2.1.0.5

███  HDD Usage
Caption  FreeSpace    Size
C:       53121257472  255060865024
  ```

</details>

Few more commands that I saw you requested on other similar issues:

ping -t 1 dns-test.docksal
`ping: dns-test.docksal: Name or service not known`

curl -L http://testd8.docksal/
`curl: (6) Could not resolve host: testd8.docksal`

ping 192.168.64.100
```PING 192.168.64.100 (192.168.64.100) 56(84) bytes of data.
64 bytes from 192.168.64.100: icmp_seq=1 ttl=128 time=0.377 ms
64 bytes from 192.168.64.100: icmp_seq=2 ttl=128 time=0.222 ms
64 bytes from 192.168.64.100: icmp_seq=3 ttl=128 time=0.384 ms
64 bytes from 192.168.64.100: icmp_seq=4 ttl=128 time=0.440 ms
64 bytes from 192.168.64.100: icmp_seq=5 ttl=128 time=0.385 ms
--- 192.168.64.100 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4004ms
rtt min/avg/max/mdev = 0.222/0.361/0.440/0.076 ms
```

netstat -nr -f inet
```Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
255.255.255.255 0.0.0.0         255.255.255.255 U         0 0          0 eth2
224.0.0.0       0.0.0.0         240.0.0.0       U         0 0          0 eth2
192.168.146.255 0.0.0.0         255.255.255.255 U         0 0          0 eth2
192.168.146.240 0.0.0.0         255.255.255.240 U         0 0          0 eth2
192.168.146.241 0.0.0.0         255.255.255.255 U         0 0          0 eth2
127.0.0.0       0.0.0.0         255.0.0.0       U         0 0          0 lo
127.0.0.1       0.0.0.0         255.255.255.255 U         0 0          0 lo
127.255.255.255 0.0.0.0         255.255.255.255 U         0 0          0 lo
224.0.0.0       0.0.0.0         240.0.0.0       U         0 0          0 lo
255.255.255.255 0.0.0.0         255.255.255.255 U         0 0          0 lo
192.168.64.255  0.0.0.0         255.255.255.255 U         0 0          0 lo
192.168.64.0    0.0.0.0         255.255.255.0   U         0 0          0 lo
192.168.64.100  0.0.0.0         255.255.255.255 U         0 0          0 lo
192.168.64.1    0.0.0.0         255.255.255.255 U         0 0          0 lo
224.0.0.0       0.0.0.0         240.0.0.0       U         0 0          0 wifi0
255.255.255.255 0.0.0.0         255.255.255.255 U         0 0          0 wifi0
0.0.0.0         192.168.43.1    255.255.255.255 U         0 0          0 wifi0
192.168.43.255  0.0.0.0         255.255.255.255 U         0 0          0 wifi0
192.168.43.0    0.0.0.0         255.255.255.0   U         0 0          0 wifi0
192.168.43.178  0.0.0.0         255.255.255.255 U         0 0          0 wifi0
255.255.255.255 0.0.0.0         255.255.255.255 U         0 0          0 eth3
224.0.0.0       0.0.0.0         240.0.0.0       U         0 0          0 eth3
10.0.75.15      0.0.0.0         255.255.255.255 U         0 0          0 eth3
10.0.75.0       0.0.0.0         255.255.255.240 U         0 0          0 eth3
10.0.75.1       0.0.0.0         255.255.255.255 U         0 0          0 eth3
```
