### ISSUE TITLE
Solr is not using custom config files

### ISSUE THREAD

**Issue by batigolix** [docksal/docksal#1406]
**Description**

When I add a Solr service to Docksal, I can not let Solr use the custom config files that I have stored in .docksal/etc/solr/conf

I am adding Solr via the docksal.yml as follows:

```
  solr:
    hostname: solr
    image: docksal/solr:7.5-2.0
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/conf:/var/lib/solr/conf:ro
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
```
.docksal/etc/solr/conf contains the files I copied from the search_api_solr module.

If I check the files used by the core in the solr UI at http://solr.myproject.docksal/solr/ I do not see the files from /var/lib/solr/conf (mounted from .docksal/etc/solr/conf). 
Instead the files in use by Solr are the ones from /opt/docker-solr/configsets/search_api_solr_8.x-2.0/conf/

Do you have an idea why the custom configuration files are not being loaded?

**Steps to reproduce the issue:**

1. Add the snippet above to docksal.yml
2. Add custom config files to .docksal/etc/solr/conf
3. Restart Docksal
4. Check Files in the Solr UI at http://solr.myproject.docksal/solr/

**Describe the results you received:**

I see the files from the folder /opt/docker-solr/configsets/search_api_solr_8.x-2.0/conf/ from the solr docker container

**Describe the results you expected:**

I want to see the files from the folder /var/lib/solr/conf/ from the solr docker container (mounted from the local .docksal/etc/solr/conf)

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: loketgezondleven
COMPOSE_FILE:
/home/boris/.docksal/stacks/volumes-bind.yml
/home/boris/.docksal/stacks/stack-default.yml
/home/boris/Sites/loketgezondleven/.docksal/docksal.yml
ENV_FILE:
/home/boris/Sites/loketgezondleven/.docksal/docksal.env
/home/boris/Sites/loketgezondleven/.docksal/docksal-local.env

PROJECT_ROOT: /home/boris/Sites/loketgezondleven
DOCROOT: web
VIRTUAL_HOST: loketgezondleven.docksal
VIRTUAL_HOST_ALIASES: *.loketgezondleven.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32786

Docker Compose configuration
---------------------
services:
  adminer:
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: price
      ADMINER_PLUGINS: tables-filter tinymce
    hostname: adminer
    image: adminer
    labels:
      io.docksal.virtual-host: adminer.loketgezondleven.docksal
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '1'
      COMPOSER_DISABLE_XDEBUG_WARN: '1'
      DOCROOT: web
      DRUSH_ALLOW_XDEBUG: '1'
      DRUSH_OPTIONS_URI: loketgezondleven.docksal
      GIT_USER_EMAIL: bdoesborg@gmail.com
      GIT_USER_NAME: Boris Doesborg
      HOST_GID: '1000'
      HOST_UID: '1000'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: serverName=loketgezondleven.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: loketgezondleven.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.6-php7.1
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  mail:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: mail.loketgezondleven.docksal,mail.loketgezondleven.docksal.*
      io.docksal.virtual-port: '8025'
    volumes:
    - project_root:/var/www:ro,nocopy,cached
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: solr
    image: docksal/solr:7.5-2.0
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: solr.loketgezondleven.docksal,solr.loketgezondleven.docksal.*
      io.docksal.virtual-port: '8983'
    volumes:
    - /home/boris/Sites/loketgezondleven/.docksal/etc/solr/conf:/var/lib/solr/conf:ro
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/web
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /home/boris/Sites/loketgezondleven
      io.docksal.virtual-host: loketgezondleven.docksal,*.loketgezondleven.docksal,loketgezondleven.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/boris/Sites/loketgezondleven
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  (paste your output here)
  ```

</details>
