### ISSUE TITLE
MailHog listen tcp 0.0.0.0:80: bind: permission denied

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#142]
After following the MailHog [setup instructions](http://docksal.readthedocs.io/en/master/tools/mailhog/) for Docksal MailHog fails to start:

```
$ fin logs mail
Attaching to drupal8_mail_1
mail_1  | [HTTP] Binding to address: 0.0.0.0:80
mail_1  | Creating API v1 with WebPath: 
mail_1  | Creating API v2 with WebPath: 
mail_1  | [HTTP] Error binding to address 0.0.0.0:80: listen tcp 0.0.0.0:80: bind: permission denied
mail_1  | 2017/03/08 02:28:33 Using in-memory storage
mail_1  | 2017/03/08 02:28:33 [SMTP] Binding to address: 0.0.0.0:1025
mail_1  | 2017/03/08 02:28:33 Serving under http://0.0.0.0:80/
```

This looks to be a regression recently introduced upstream in Docker
https://github.com/docker/docker/issues/8460
https://github.com/docker/docker/pull/27737

**Comment by lmakarov** [comment]
As a workaround MailHog can be run as root:

```
version: "2.1"

services:
  mail:
    hostname: mail
    image: mailhog/mailhog
    expose:
      - "80"
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:80
      - MH_UI_BIND_ADDR=0.0.0.0:80
    labels:
      - io.docksal.virtual-host=webmail.${VIRTUAL_HOST}
    user: root
    working_dir: /mailhog
```

The last two lines overrides the settings in the stock image. Running as root allows binding to privileged ports (80).
