### ISSUE TITLE
Problems with Docksal on windows 10 Home (build 19041)

### ISSUE THREAD

**Issue by ilariacuccaro** [docksal/docksal#1462]
**Description**

I have installed Docksal in Windows but the visit of the project URL in my browser results in a “site can’t be reached” message.
I opened explorer and navigate to \\192.168.64.1\, it shows "no items matching the search criteria".
I have tried to install -reinstall Ubuntu and Docksal (both Virtualbox and Docker Desktop), disable Firewall and Windows defender, test printer setting.
I can never see the contents of the url "http: //drupal8. docksal"

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
COMPOSE_PROJECT_NAME_SAFE: drupal8
COMPOSE_FILE:
/home/ilaria/.docksal/stacks/volumes-bind.yml
/home/ilaria/.docksal/stacks/stack-default.yml
/home/ilaria/drupal8/.docksal/docksal.yml
ENV_FILE:
/home/ilaria/drupal8/.docksal/docksal.env

PROJECT_ROOT: /home/ilaria/drupal8
DOCROOT: docroot
VIRTUAL_HOST: drupal8.docksal
VIRTUAL_HOST_ALIASES: *.drupal8.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DEFAULT_VERSION: null
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: drupal8.docksal
      GIT_USER_EMAIL: ''
      GIT_USER_NAME: ''
      HOST_GID: '1000'
      HOST_UID: '1000'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_ACQUIACLI_KEY: null
      SECRET_ACQUIACLI_SECRET: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: drupal8.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    extra_hosts:
      drupal8.docksal: 127.0.0.1
    healthcheck:
      interval: 10s
    hostname: cli
    image: docksal/cli:2.12-php7.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /tmp/.docksal/drupal8:/tmp/.docksal/drupal8:ro
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    healthcheck:
      interval: 10s
    hostname: db
    image: docksal/mysql:5.6-1.5
    logging:
      options:
        max-file: '10'
        max-size: 1m
    ports:
    - published: 0
      target: 3306
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    healthcheck:
      interval: 10s
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /home/ilaria/drupal8
      io.docksal.virtual-host: drupal8.docksal,*.drupal8.docksal,drupal8.docksal.*
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/ilaria/drupal8
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  FIN
fin version: 1.103.0

███  OS
Linux Ubuntu 18.04
Linux DESKTOP-IC 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST :

███  DOCKER
EXPECTED CLIENT VERSION: 19.03.13
EXPECTED SERVER VERSION: 19.03.13

Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKER COMPOSE
EXPECTED VERSION: 1.27.4
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

███  DOCKSAL: PROJECTS
project             STATUS                       virtual host                                          project root
drupal8             Up About an hour (healthy)   drupal8.docksal,*.drupal8.docksal,drupal8.docksal.*   /home/ilaria/drupal8

███  DOCKSAL: VIRTUAL HOSTS
*.drupal8.docksal
drupal8.docksal.*
drupal8.docksal

███  DOCKSAL: NETWORKING

DOCKSAL_IP: 192.168.64.100
DOCKSAL_HOST_IP: 192.168.64.1
DOCKSAL_VHOST_PROXY_IP: 0.0.0.0
DOCKSAL_DNS_IP:
DOCKSAL_DNS_DISABLED: 0
DOCKSAL_NO_DNS_RESOLVER: 1
DOCKSAL_DNS_UPSTREAM:
DOCKSAL_DNS_DOMAIN: docksal

███  DOCKSAL: CONNECTIVITY

Host to 192.168.64.100:         PASS
Container to 192.168.64.100:    PASS
Container to 192.168.64.1:      PASS

Checking connectivity to http://dns-test.docksal...
Host: FAIL

Debug info:
----------
+ cat /etc/resolv.conf
+ grep 192.168.64.100
nameserver 192.168.64.100
+ ping -c 1 -W 1 dns-test.docksal
PING dns-test.docksal (192.168.64.100) 56(84) bytes of data.
64 bytes from docksal (192.168.64.100): icmp_seq=1 ttl=64 time=0.126 ms

--- dns-test.docksal ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.126/0.126/0.126/0.000 ms
+ nslookup -timeout=1 dns-test.docksal 192.168.64.100
Server:         192.168.64.100
Address:        192.168.64.100#53

Name:   dns-test.docksal
Address: 192.168.64.100

+ set +x
----------

Containers: FAIL

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                       PORTS                                        NAMES
3efa5bdd02ba        docksal/apache:2.4-2.3    "httpd-foreground"       About an hour ago   Up About an hour (healthy)   80/tcp, 443/tcp                              drupal8_web_1
431659e8f849        docksal/cli:2.12-php7.3   "/opt/startup.sh sup…"   About an hour ago   Up About an hour (healthy)   22/tcp, 3000/tcp, 9000/tcp                   drupal8_cli_1
794a2969616d        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)                                                docksal-ssh-agent
fe05db45f21f        docksal/dns:1.1           "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)   192.168.64.100:53->53/udp                    docksal-dns
1f2084f28e16        docksal/vhost-proxy:1.6   "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)   0.0.0.0:443->443/tcp, 0.0.0.0:8080->80/tcp   docksal-vhost-proxy
362fbbf9d722        docksal/mysql:5.6-1.5     "docker-entrypoint.s…"   19 hours ago        Up About an hour (healthy)   0.0.0.0:32768->3306/tcp                      drupal8_db_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
40ca326cd059        _default            bridge              local
4475ca65c75d        bridge              bridge              local
bf01c98593c8        drupal8_default     bridge              local
910b1993785b        host                host                local
69e7aaab3c85        none                null                local

███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb        251G  4.7G  234G   2% /
tmpfs           2.7G     0  2.7G   0% /mnt/wsl
tools           426G  180G  246G  43% /init
none            2.7G     0  2.7G   0% /dev
none            2.7G  432K  2.7G   1% /run
none            2.7G     0  2.7G   0% /run/lock
none            2.7G     0  2.7G   0% /run/shm
none            2.7G     0  2.7G   0% /run/user
tmpfs           2.7G     0  2.7G   0% /sys/fs/cgroup
C:\             426G  180G  246G  43% /mnt/c
  ```

</details>
