### ISSUE TITLE
fin share does not work if --auth parameter is provided

### ISSUE THREAD

**Issue by retif** [docksal/docksal#1487]
**Description**

Fin share stops working if ngrok auth token is provided.

**Steps to reproduce the issue:**

run command
fin share --auth=qwerty
or add auth token to a config with
fin config set NGROK_AUTH=qwerty
or
fin config set NGROK_AUTH=qwerty --global

**Describe the results you received:**

fin share failed to launch.

ERROR:  You must specify a single argument: a port or address to tunnel to.
ERROR:  You specified 0 arguments: []
ERROR:  For example, to expose port 80, run 'ngrok http 80'.

**Describe the results you expected:**

Launch fin share

fin version: 1.103.0

**Comment by lpeabody** [comment]
Fixing the share command is on the todo list. As a workaround you can use an ngrok configuration file.

Contents of `$PROJECT_ROOT/.docksal/etc/ngrok/ngrok-local.yml`:

```
authtoken: fasdfsadfasdfdsafasdafsdf

tunnels:
  tunnel-id:
    proto: http
    addr: project-name_web_1.project-name_default:80
    host_header: project.docksal.site # Whatever your $VIRTUAL_HOST value is for the project
```

If you have a plan that supports custom hostnames, you can also do something like:

```
authtoken: fasdfsadfasdfdsafasdafsdf

tunnels:
  tunnel-id:
    proto: http
    addr: project-name_web_1.project-name_default:80
    hostname: mydomain.net
    host_header: project.docksal.site # Whatever your $VIRTUAL_HOST value is for the project
```

See https://ngrok.com/docs#tunnel-definitions for more info about what you can put in the configuration file.
