### ISSUE TITLE
`fin share` no longer working

### ISSUE THREAD

**Issue by MKorostoff** [docksal/docksal#151]
I have a docksal site installed locally at http://example.docksal.  I can run `fin share` within this project and start an ngrok session:

![ngrok](https://cloud.githubusercontent.com/assets/1197335/24165175/1c5b8ca0-0e46-11e7-8cc7-e982141562cf.png)

However, when I attempt to view this page in ngrok, I get the following:

![ngrok2](https://cloud.githubusercontent.com/assets/1197335/24165271/52b2dca4-0e46-11e7-8223-8425ed97b43e.png)

The site does work when viewed locally at http://example.docksal, however

**Comment by MKorostoff** [comment]
I'm using Docker version 1.10.3, build 20f81dd

**Comment by lmakarov** [comment]
@MKorostoff 

Check ngrok's web ui to see the actual request/response headers.

I've just tested `fin share` with a fresh setup and everything worked as expected.

**Comment by MKorostoff** [comment]
@lmakarov how do you access the ngrok web ui?  When I try, I get this:

![refused](https://cloud.githubusercontent.com/assets/1197335/24169891/571db82c-0e55-11e7-9a2c-f13ae89a3d4a.png)

This is after mapping port 4040, by the way:

![mapped](https://cloud.githubusercontent.com/assets/1197335/24169940/7b827e00-0e55-11e7-9b82-c9645e5e7224.png)

I'm guessing the issue here is that traffic is forwarded to `example_web_1.example_default` which is not the url of my site.

**Comment by achekulaev** [comment]
Looks like ngrok is working (you can see requests for favicon) but your site is set up in a way, that it is not working when accessed by ngrok's public url and only works when accessed as  http://example.docksal. Probably because you had set up multi-site and it's not a default one?

**Comment by lmakarov** [comment]
@MKorostoff
> how do you access the ngrok web ui? When I try, I get this:

Looks like the current `fin share` implementation does not expose access to ngrok web ui.

As a quick and dirty fix you can add the following line right after this line in `fin`
https://github.com/docksal/docksal/blob/v1.1.0/bin/fin#L2920

```
--publish 4040:4040 \
```

Then run `fin share` again. This will start the ngrok service with port `4040` published as `4040` on the host. ngrkok web ui will be accessible at http://192.168.64.100:4040/

**Comment by MKorostoff** [comment]
@achekulaev:

> Probably because you had set up multi-site and it's not a default one?

I do not have a multisite.  There is only one settings file in my installation:

![sites](https://cloud.githubusercontent.com/assets/1197335/24205104/d0e2622a-0ef0-11e7-8b59-dad3e679e599.png)


@lmakarov:

> As a quick and dirty fix you can add the following line right after this line in fin

When I did this, I was able to access the ngrok web UI.  This allowed me to capture the following request/response:

**Request**
```
GET / HTTP/1.1
Host: example.docksal,*.example.docksal
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 72.76.121.141
X-Original-Host: 046ef604.ngrok.io
```

**Response:**
```
HTTP/1.1 400 Bad Request
Date: Wed, 22 Mar 2017 15:07:20 GMT
Server: Apache/2.2.22 (Debian)
Vary: Accept-Encoding
Content-Encoding: gzip
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8

f
ãˇˇ
a

0


```

**Comment by lmakarov** [comment]
@MKorostoff please run `fin config` and post the output here.

The problem is that you have an incorrectly defined virtual host `example.com,*.example.com`.
There was a change in one of the recent Docksal versions regarding how wildcard domains are handled.

You may have an outdated config somewhere. Check you `docksal.env` or `docksal.yml` file and remove `*.example.com` from it.

I'd also recommend updating Docksal to the latest version by running `fin update`.

**Comment by MKorostoff** [comment]
@lmakarov 

Here is the output of `fin config`:

```
---------------------
COMPOSE_PROJECT_NAME: example
COMPOSE_PROJECT_NAME_SAFE: example
COMPOSE_FILE:
/Users/matt/.docksal/stacks/volumes-bind.yml
/Users/matt/Sites/example/.docksal/docksal.yml
ENV_FILE:
/Users/matt/Sites/example/.docksal/docksal.env
/Users/matt/Sites/example/.docksal/docksal-local.env

PROJECT_ROOT: /Users/matt/Sites/example
DOCROOT: docroot
VIRTUAL_HOST: example.docksal,*.example.docksal
VIRTUAL_HOST_ALIASES: *.example.docksal,*.example.docksal
IP: 127.0.0.1
MYSQL: 127.0.0.1:33066

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    environment:
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:1.0-php5
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 33066:3306
    volumes:
    - project_root:/var/www:ro
  web:
    depends_on:
      cli:
        condition: service_started
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
      VIRTUAL_HOST: example.docksal,*.example.docksal
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/matt/Sites/example
      io.docksal.virtual-host: example.docksal,*.example.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/matt
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/matt/Sites/example
      o: bind
      type: none

---------------------
```

I have inspected `docksal.yml` and `docksal.env` and have not found any instance of the string "example.com"
