### ISSUE TITLE
XDebug only hits in index.php

### ISSUE THREAD

**Issue by jovansremacki** [docksal/docksal#1585]
**Description**
I am trying to debug PHP file that is inside my project but the break-point doesn't stop in a certain file. I've put the break-point in the index.php file and it stops in that file.

Problem/feature description...

**Steps to reproduce the issue:**

1. Setup PHP Server for debugging
2. Place break-point in a certain PHP file
3. Run debugger

**Describe the results you received:**

Xdebug doesn't run, only in index.php

**Describe the results you expected:**

Xdebug runs in a PHP script.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
COMPOSE_PROJECT_NAME_SAFE: myproject
COMPOSE_FILE:
  /home/wtf/.docksal/stacks/volumes-bind.yml
  /home/wtf/.docksal/stacks/stack-default.yml
  /home/wtf/Projects/BeeIT/myproject/.docksal/docksal.yml
  /home/wtf/Projects/BeeIT/myproject/.docksal/docksal-local.yml
ENV_FILE:
  /home/wtf/Projects/BeeIT/myproject/.docksal/docksal.env
  /home/wtf/Projects/BeeIT/myproject/.docksal/docksal-local.env

PROJECT_ROOT: /home/wtf/Projects/BeeIT/myproject
DOCROOT: docroot/drupalCurtains
VIRTUAL_HOST: myproject.docksal
VIRTUAL_HOST_ALIASES: *.myproject.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:49166

  Docker Compose configuration
  ---------------------
services:
  cli:
    dns:
      - 192.168.64.100
      - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '1'
      COMPOSER_DEFAULT_VERSION: '1'
      COMPOSER_DISABLE_XDEBUG_WARN: '1'
      DOCROOT: docroot/drupalCurtains
      DRUSH_ALLOW_XDEBUG: '1'
      DRUSH_OPTIONS_URI: myproject.docksal
      GIT_USER_EMAIL: j.sremacki@beeit.rs
      GIT_USER_NAME: Jovan
      HOST_GID: '1000'
      HOST_UID: '1000'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: serverName=myproject.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_ACQUIACLI_KEY: null
      SECRET_ACQUIACLI_SECRET: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: myproject.docksal
      XDEBUG_CONFIG: client_host=192.168.64.1
      XDEBUG_ENABLED: '1'
      XDEBUG_MODE: debug
    healthcheck:
      interval: 10s
    hostname: cli
    image: docksal/cli:php7.4-3.0
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
      - docksal_ssh_agent:/.ssh-agent:ro
      - cli_home:/home/docker:rw
      - /tmp/.docksal/myproject:/tmp/.docksal/myproject:ro
      - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
      - 192.168.64.100
      - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    healthcheck:
      interval: 10s
    hostname: db
    image: docksal/mysql:5.7-1.5
    logging:
      options:
        max-file: '10'
        max-size: 1m
    ports:
      - published: 0
        target: 3306
    volumes:
      - db_data:/var/lib/mysql:rw
      - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
      - 192.168.64.100
      - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot/drupalCurtains
      APACHE_FCGI_HOST_PORT: cli:9000
    healthcheck:
      interval: 10s
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /home/wtf/Projects/BeeIT/myproject
      io.docksal.virtual-host: myproject.docksal,*.myproject.docksal,myproject.docksal.*
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
      - project_root:/var/www:ro,nocopy,cached
version: '2.13'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/wtf/Projects/BeeIT/myproject
      o: bind
      type: none


```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  ███  FIN
  fin version: 1.107.1

    ███  OS
    Linux Linux Mint 20.2
    Linux wtf-Aspire-A315-42G 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

    ███  ENVIRONMENT
  MODE : Linux Kernel
  DOCKER_HOST :

    ███  DOCKER
  EXPECTED CLIENT VERSION: 20.10.7
  EXPECTED SERVER VERSION: 20.10.7

  Client: Docker Engine - Community
    Version:           20.10.9
    API version:       1.41
    Go version:        go1.16.8
    Git commit:        c2ea9bc
    Built:             Mon Oct  4 16:08:29 2021
    OS/Arch:           linux/amd64
    Context:           default
    Experimental:      true

  Server: Docker Engine - Community
    Engine:
      Version:          20.10.9
      API version:      1.41 (minimum version 1.12)
      Go version:       go1.16.8
      Git commit:       79ea9d3
      Built:            Mon Oct  4 16:06:37 2021
      OS/Arch:          linux/amd64
      Experimental:     false
    containerd:
      Version:          1.4.11
      GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
    runc:
      Version:          1.0.2
      GitCommit:        v1.0.2-0-g52b36a2
    docker-init:
      Version:          0.19.0
      GitCommit:        de40ad0

    ███  DOCKER COMPOSE
  EXPECTED VERSION: 1.29.2
    docker-compose version 1.29.2, build 5becea4c
  docker-py version: 5.0.0
  CPython version: 3.7.10
  OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

  ███  DOCKSAL: PROJECTS
    project   STATUS                    virtual host                                       project root
    myproject    Up 17 minutes (healthy)   myproject.docksal,*.myproject.docksal,myproject.docksal.*   /home/wtf/Projects/BeeIT/myproject
    bicw      Exited (0) 6 days ago     bicw.docksal,*.bicw.docksal,bicw.docksal.*         /home/wtf/Projects/BeeIT/bicw

  ███  DOCKSAL: VIRTUAL HOSTS
    *.myproject.docksal
    myproject.docksal.*
    myproject.docksal

  ███  DOCKSAL: NETWORKING

  DOCKSAL_IP: 192.168.64.100
  DOCKSAL_HOST_IP: 192.168.64.1
  DOCKSAL_VHOST_PROXY_IP:
  DOCKSAL_DNS_IP:
  DOCKSAL_DNS_DISABLED: 0
  DOCKSAL_NO_DNS_RESOLVER: 0
  DOCKSAL_DNS_UPSTREAM:
  DOCKSAL_DNS_DOMAIN: docksal

  ███  DOCKSAL: CONNECTIVITY

  Host to 192.168.64.100: 	PASS
  Container to 192.168.64.100: 	PASS
  Container to 192.168.64.1: 	PASS

    Checking connectivity to http://dns-test.docksal...
  Host: PASS
  Containers: PASS

  ███  DOCKER: RUNNING CONTAINERS
    CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS                    PORTS                                                    NAMES
    8703ba707357   docksal/cli:php7.4-3.0    "/opt/startup.sh sup…"   18 minutes ago   Up 17 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               myproject_cli_1
    c7859af2f3ea   docksal/apache:2.4-2.3    "httpd-foreground"       13 hours ago     Up 17 minutes (healthy)   80/tcp, 443/tcp                                          myproject_web_1
    0c3ccbf8f06e   docksal/mysql:5.7-1.5     "docker-entrypoint.s…"   18 hours ago     Up 17 minutes (healthy)   33060/tcp, 0.0.0.0:49166->3306/tcp, :::49166->3306/tcp   myproject_db_1
    39019aff700c   docksal/ssh-agent:1.3     "docker-entrypoint.s…"   18 hours ago     Up 18 hours (healthy)                                                              docksal-ssh-agent
    91f856894dbf   docksal/dns:1.1           "docker-entrypoint.s…"   18 hours ago     Up 18 hours (healthy)     192.168.64.100:53->53/udp                                docksal-dns
    0ca2adccec15   docksal/vhost-proxy:1.7   "docker-entrypoint.s…"   18 hours ago     Up 18 hours (healthy)     192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

  ███  DOCKER: NETWORKS
    NETWORK ID     NAME             DRIVER    SCOPE
    2e57e83492fb   _default         bridge    local
    8e57d7b8b6dd   bicw_default     bridge    local
    1ee3bd7f7d7b   bridge           bridge    local
    52266e84a405   myproject_default   bridge    local
    bd6ece732601   host             host      local
    6bce3317fbe4   none             null      local

    ███  HDD Usage
    Filesystem      Size  Used Avail Use% Mounted on
    udev            2,9G     0  2,9G   0% /dev
    tmpfs           595M  2,3M  593M   1% /run
    /dev/nvme0n1p7   72G   31G   37G  46% /
    tmpfs           3,0G  141M  2,8G   5% /dev/shm
    tmpfs           5,0M  4,0K  5,0M   1% /run/lock
    tmpfs           3,0G     0  3,0G   0% /sys/fs/cgroup
    /dev/loop2       56M   56M     0 100% /snap/core18/2246
    /dev/loop1      100M  100M     0 100% /snap/core/11993
    /dev/loop3       62M   62M     0 100% /snap/core20/1169
    /dev/loop0      128K  128K     0 100% /snap/bare/5
    /dev/loop4      151M  151M     0 100% /snap/firefox/631
    /dev/loop6       66M   66M     0 100% /snap/gtk-common-themes/1519
    /dev/loop5       56M   56M     0 100% /snap/core18/2128
    /dev/loop7      219M  219M     0 100% /snap/gnome-3-34-1804/72
    /dev/loop8      412M  412M     0 100% /snap/onlyoffice-desktopeditors/81
    /dev/loop9      106M  106M     0 100% /snap/mailspring/506
    /dev/loop10     165M  165M     0 100% /snap/gnome-3-28-1804/161
    /dev/loop11     169M  169M     0 100% /snap/postman/148
    /dev/loop13     243M  243M     0 100% /snap/gnome-3-38-2004/76
    /dev/loop12     296M  296M     0 100% /snap/vlc/2344
    /dev/loop15     140M  140M     0 100% /snap/skype/187
    /dev/loop14      11M   11M     0 100% /snap/nvim/1395
    /dev/loop16     9,3M  9,3M     0 100% /snap/httpstat/1
    /dev/nvme0n1p1 1020M   32M  989M   4% /boot/efi
    tmpfs           595M   80K  595M   1% /run/user/1000
    /dev/loop17     169M  169M     0 100% /snap/postman/149

  ```

</details>
