### ISSUE TITLE
[Linux] `fin hosts add` points to `192.168.64.100` instead of `127.0.0.1`

### ISSUE THREAD

**Issue by alexander-danilenko** [docksal/docksal#1662]
## Description

The wrong IP address is assigned to the host when I run `fin hosts add` in Linux: 
- Actual address: `192.168.64.100`
- Expected address: `127.0.0.1`

Linux does not have any Docker Desktop or Virtualbox additional layers, so it's safe to just point to `127.0.0.1`. 

When I changed this value manually to `127.0.0.1`, the project started to work as expected.

## Steps to reproduce the issue:

1. `cd <repo>`
2. `fin hosts add`

## Actual result

I'm getting the following in the terminal:

```
Backing up to /tmp/hosts.bak.25701
Adding: 192.168.64.100 myproject.docksal.site
Adding: ::2 myproject.docksal.site
```

Also `/etc/hosts` contain the wrong IP address:

```
192.168.64.100 myproject.docksal.site
::2 myproject.docksal.site
```

## Expected result

```
127.0.0.1 myproject.docksal.site
::2 myproject.docksal.site
```

## Docksal config and sysinfo

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: myproject
COMPOSE_FILE:
/home/alex/.docksal/stacks/volumes-bind.yml
/home/alex/.docksal/stacks/stack-node.yml
/home/alex/Projects/myproject/.docksal/docksal.yml
ENV_FILE:
/home/alex/Projects/myproject/.docksal/docksal.env
/home/alex/Projects/myproject/.docksal/docksal-local.env

PROJECT_ROOT: /home/alex/Projects/myproject
DOCROOT: .
VIRTUAL_HOST: myproject.docksal.site
VIRTUAL_HOST_ALIASES: *.myproject.docksal.site
IP: 192.168.64.100

MySQL endpoint: :0
Public URL:

Docker Compose configuration
---------------------
services:
  cli:
    build:
      context: /home/alex/Projects/myproject/.docksal/services/cli
      dockerfile: Dockerfile
    dns:
    - 192.168.64.100
    - 1.1.1.1
    - 192.168.64.100
    - 1.1.1.1
    - 192.168.64.100
    - 1.1.1.1
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: "0"
      COMPOSER_DEFAULT_VERSION: null
      COMPOSER_DISABLE_XDEBUG_WARN: "0"
      DB_IMAGE: postgres:14-alpine
      DOCKSAL_STACK: node
      DOCROOT: .
      DRUSH_ALLOW_XDEBUG: "0"
      DRUSH_OPTIONS_URI: myproject.docksal.site
      GIT_USER_EMAIL: ""
      GIT_USER_NAME: ""
      HOST_GID: "1000"
      HOST_UID: "1000"
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      POSTGRES_DB: default
      POSTGRES_PASSWORD: user
      POSTGRES_PORT_MAPPING: 5432:5432
      POSTGRES_USER: user
      REDIS_IMAGE: wodby/redis:6
      SECRET_ACQUIA_CLI_KEY: null
      SECRET_ACQUIA_CLI_SECRET: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: myproject.docksal.site
      XDEBUG_CONFIG: client_host=192.168.64.1 remote_host=192.168.64.1
      XDEBUG_ENABLED: "0"
    env_file:
    - docksal.env
    - docksal.env
    extends:
      file: /home/alex/.docksal/stacks/services.yml
      service: cli
    hostname: cli
    healthcheck:
      interval: 5s
    image: docksal/cli:php8.1-3.2
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /home/alex/Projects/myproject
      io.docksal.shell: bash
      io.docksal.user: docker
      io.docksal.virtual-host: myproject.docksal.site,*.myproject.docksal.site,myproject.docksal.site.*
      io.docksal.virtual-port: "3000"
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: 8080
      protocol: tcp
    - mode: ingress
      target: 9229
      published: 9229
      protocol: tcp
    volumes:
    - type: volume
      source: docksal_ssh_agent
      target: /.ssh-agent
      read_only: true
      volume: {}
    - type: volume
      source: cli_home
      target: /home/docker
      volume: {}
    - type: bind
      source: /tmp/.docksal/myproject
      target: /tmp/.docksal/myproject
      read_only: true
      bind:
        create_host_path: true
    - type: volume
      source: project_root
      target: /var/www
      volume:
        nocopy: true
  db:
    dns:
    - 192.168.64.100
    - 1.1.1.1
    - 192.168.64.100
    - 1.1.1.1
    environment:
      POSTGRES_DB: default
      POSTGRES_PASSWORD: user
      POSTGRES_USER: user
    extends:
      file: /home/alex/.docksal/stacks/services.yml
      service: pgsql
    hostname: db
    healthcheck:
      interval: 5s
    image: postgres:14-alpine
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    ports:
    - mode: ingress
      target: 5432
      protocol: tcp
    - mode: ingress
      target: 5432
      published: 5821
      protocol: tcp
    volumes:
    - type: bind
      source: /home/alex/Projects/myproject/.docksal/db
      target: /dumps
      bind:
        create_host_path: true
    - type: volume
      source: db_data
      target: /var/lib/postgresql/data
      volume: {}
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
  redis:
    dns:
    - 192.168.64.100
    - 1.1.1.1
    - 192.168.64.100
    - 1.1.1.1
    environment:
      REDIS_MAXMEMORY: 2096m
    extends:
      file: /home/alex/.docksal/stacks/services.yml
      service: redis
    hostname: redis
    healthcheck:
      interval: 5s
    image: wodby/redis:6
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
    - type: bind
      source: /home/alex/Projects/myproject/var/redis-data
      target: /data
      bind:
        create_host_path: true
  redis-commander:
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    image: rediscommander/redis-commander:latest
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8081
      published: 8081
      protocol: tcp
    restart: always
networks:
  default:
    name: myproject_default
volumes:
  cli_home:
    name: myproject_cli_home
  db_data:
    name: myproject_db_data
  docksal_ssh_agent:
    name: docksal_ssh_agent
    external: true
  project_root:
    name: myproject_project_root
    driver: local
    driver_opts:
      device: /home/alex/Projects/myproject
      o: bind
      type: none
---------------------

```

</details>

<details>
  <summary>fin sysinfo output</summary>

  ```

███  DOCKSAL
Docksal version: v1.17.0
fin version:     1.110.1

███  OS
Linux Ubuntu 20.04
Linux Astra 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST :

███  DOCKER
Expected client version: 20.10.12
Expected server version: 20.10.12

Installed versions:

Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:48:02 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:53 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

███  DOCKER COMPOSE
Expected version:  2.1.0
Installed version: v2.1.0

███  DOCKSAL: PROJECTS
project                 STATUS                 virtual host                                             project root
myproject   Up 4 hours (healthy)   myproject.docksal.site,*.myproject.docksal.site,myproject.docksal.site.*   /home/alex/Projects/myproject

███  DOCKSAL: VIRTUAL HOSTS
[0;32;49m*.myproject.docksal.site[0m
[0;32;49mmyproject.docksal.site.*[0m
[0;32;49mmyproject.docksal.site[0m

███  DOCKSAL: NETWORKING

DOCKSAL_IP: 192.168.64.100
DOCKSAL_HOST_IP: 192.168.64.1
DOCKSAL_VHOST_PROXY_IP:
DOCKSAL_DNS_IP:
DOCKSAL_DNS_DISABLED: 0
DOCKSAL_NO_DNS_RESOLVER: 0
DOCKSAL_DNS_UPSTREAM: 1.1.1.1
DOCKSAL_DNS_DOMAIN: docksal

███  DOCKSAL: CONNECTIVITY

Host to 192.168.64.100: 	PASS
Container to 192.168.64.100: 	PASS
Container to 192.168.64.1: 	PASS

Checking connectivity to http://dns-test.docksal...
Host: PASS
Containers: PASS

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID   IMAGE                                   COMMAND                  CREATED        STATUS                  PORTS                                                                                                              NAMES
dd99d621012a   docksal/cli:php8.1-3.2                  "/opt/startup.sh sup…"   4 hours ago    Up 4 hours (healthy)    22/tcp, 3000/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 9000/tcp, 0.0.0.0:9229->9229/tcp, :::9229->9229/tcp   myproject_cli_1
0f4c995dd5f4   postgres:14-alpine                      "docker-entrypoint.s…"   4 hours ago    Up 4 hours              0.0.0.0:5821->5432/tcp, 0.0.0.0:49158->5432/tcp, :::5821->5432/tcp, :::49158->5432/tcp                             myproject_db_1
8aeebb6d89c2   wodby/redis:6                           "/docker-entrypoint.…"   4 hours ago    Up 4 hours              6379/tcp                                                                                                           myproject_redis_1
2556402e914d   rediscommander/redis-commander:latest   "/usr/bin/dumb-init …"   11 hours ago   Up 11 hours (healthy)   0.0.0.0:8081->8081/tcp, :::8081->8081/tcp                                                                          myproject_redis-commander_1
67c8ec555063   docksal/ssh-agent:1.4                   "docker-entrypoint.s…"   11 hours ago   Up 11 hours (healthy)                                                                                                                      docksal-ssh-agent
838d32ec365b   docksal/dns:1.2                         "docker-entrypoint.s…"   11 hours ago   Up 11 hours (healthy)   192.168.64.100:53->53/udp                                                                                          docksal-dns
64530512d5a9   docksal/vhost-proxy:1.8                 "docker-entrypoint.s…"   11 hours ago   Up 11 hours (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp                                                             docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID     NAME                            DRIVER    SCOPE
fdfedf90dc37   _default                        bridge    local
9a1de2f5d2aa   bridge                          bridge    local
206e104bba4d   myproject_default   bridge    local
309b858c9099   host                            host      local
6030ec343b63   none                            null      local

███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
udev             32G     0   32G   0% /dev
tmpfs           6.3G  3.0M  6.3G   1% /run
/dev/nvme1n1p2  457G   83G  352G  19% /
tmpfs            32G  278M   32G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs            32G     0   32G   0% /sys/fs/cgroup
/dev/loop0      128K  128K     0 100% /snap/bare/5
/dev/loop1       62M   62M     0 100% /snap/core20/1328
/dev/loop2       66M   66M     0 100% /snap/gtk-common-themes/1519
/dev/loop3       62M   62M     0 100% /snap/core20/1405
/dev/loop4       55M   55M     0 100% /snap/snap-store/558
/dev/loop5      249M  249M     0 100% /snap/gnome-3-38-2004/99
/dev/loop6       44M   44M     0 100% /snap/snapd/15177
/dev/loop7       44M   44M     0 100% /snap/snapd/14978
/dev/nvme1n1p1  511M  5.3M  506M   2% /boot/efi
/dev/nvme0n1p2  1.9T  1.2T  717G  62% /mnt/D
tmpfs           6.3G  216K  6.3G   1% /run/user/1000
/dev/sda2       8.1T  5.1T  3.1T  63% /mnt/E
/dev/sda3      1007G  309G  648G  33% /run/timeshift/backup
  ```

</details>
