### ISSUE TITLE
DNS can't be reached and cannot access to dockerhub when on ipv6 hotspot.

### ISSUE THREAD

**Issue by bryanmanalo** [docksal/docksal#1673]
**Description**
On fin system reset, it says dns (8.8.8.8 or other dns IPs i tried) unreacheable.
On fin up -d, cannot connect to docker.io

This only happens on MacOs M1 chip when connected to my phone's hotspot (ios) which has ipv6 (not sure if related).  On Wifi, the issue is not replicatable.

As a result, I cannot acccess my site.  If I tried conencting to Wifi first, to start it succesfully, then switch to hotspot, I can no longer access my site.  Also tried doing fin system reset on hotspot, but same result.

This issue could not be common.  But just raising it here, if others can also experience it.  Tested on a non m1 mac, the issue is not replicatable.

**Steps to reproduce the issue:**

1. Connect to my phone's hotspot
2. Try fin system reset, or fin up -d

**Describe the results you received:**

I cannot start the site, nor access it even if I tried starting on Wifi first then switching to hotspot.

**Describe the results you expected:**

I can start the site and access it even if I am connected to a hotspot.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
(paste your output here)
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
COMPOSE_PROJECT_NAME_SAFE: bryanmanalo-d9
COMPOSE_FILE:
/Users/bryanmanalo/.docksal/stacks/volumes-nfs.yml
/Users/bryanmanalo/.docksal/stacks/stack-acquia.yml
/Users/bryanmanalo/websites/bryanmanalo-d9/.docksal/docksal.yml
ENV_FILE:
/Users/bryanmanalo/websites/bryanmanalo-d9/.docksal/docksal.env

PROJECT_ROOT: /Users/bryanmanalo/websites/bryanmanalo-d9
DOCROOT: docroot
VIRTUAL_HOST: bryanmanalo-d9.docksal
VIRTUAL_HOST_ALIASES: *.bryanmanalo-d9.docksal
IP: 192.168.64.100

MySQL endpoint: 192.168.64.100:49992
Public URL:

Docker Compose configuration
---------------------
services:
  cli:
    build:
      context: /Users/bryanmanalo/websites/bryanmanalo-d9/.docksal/services/cli
      dockerfile: Dockerfile
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: "0"
      COMPOSER_DEFAULT_VERSION: null
      COMPOSER_DISABLE_XDEBUG_WARN: "0"
      COMPOSER_MEMORY_LIMIT: "-1"
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: "0"
      DRUSH_OPTIONS_URI: bryanmanalo-d9.docksal
      GIT_USER_EMAIL: bri.manalo@gmail.com
      GIT_USER_NAME: Bryan Manalo
      HOST_GID: "20"
      HOST_UID: "501"
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACQUIA_CLI_KEY: null
      SECRET_ACQUIA_CLI_SECRET: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: bryanmanalo-d9.docksal
      XDEBUG_CONFIG: client_host=192.168.64.1 remote_host=192.168.64.1
      XDEBUG_ENABLED: "0"
    extends:
      file: /Users/bryanmanalo/.docksal/stacks/services.yml
      service: cli
    hostname: cli
    healthcheck:
      interval: 10s
    image: bryanmanalo-d9_cli
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
    - type: volume
      source: docksal_ssh_agent
      target: /.ssh-agent
      read_only: true
      volume: {}
    - type: volume
      source: cli_home
      target: /home/docker
      volume: {}
    - type: bind
      source: /tmp/.docksal/bryanmanalo-d9
      target: /tmp/.docksal/bryanmanalo-d9
      read_only: true
      bind:
        create_host_path: true
    - type: volume
      source: project_root
      target: /var/www
      volume:
        nocopy: true
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    extends:
      file: /Users/bryanmanalo/.docksal/stacks/services.yml
      service: mariadb
    hostname: db
    healthcheck:
      interval: 10s
    image: docksal/mariadb:10.4-1.3
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3306
      protocol: tcp
    volumes:
    - type: volume
      source: db_data
      target: /var/lib/mysql
      volume: {}
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
  memcached:
    command:
    - -m
    - "128"
    dns:
    - 192.168.64.100
    - 8.8.8.8
    extends:
      file: /Users/bryanmanalo/.docksal/stacks/services.yml
      service: memcached
    hostname: memcached
    healthcheck:
      interval: 10s
    image: memcached:1.6-alpine
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
  pma:
    environment:
      PMA_HOST: db
      PMA_PASSWORD: root
      PMA_USER: root
    hostname: pma
    image: phpmyadmin/phpmyadmin
    labels:
      io.docksal.virtual-host: pma.bryanmanalo-d9.docksal
    networks:
      default: null
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    extends:
      file: /Users/bryanmanalo/.docksal/stacks/services.yml
      service: solr
    hostname: solr
    healthcheck:
      interval: 10s
    image: docksal/solr:1.0-solr4
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: solr.bryanmanalo-d9.docksal,solr.bryanmanalo-d9.docksal.*
      io.docksal.virtual-port: "8983"
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      VARNISH_BACKEND_HOST: web
    extends:
      file: /Users/bryanmanalo/.docksal/stacks/services.yml
      service: varnish
    hostname: varnish
    healthcheck:
      interval: 10s
    image: docksal/varnish:6.6-3.1
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: varnish.bryanmanalo-d9.docksal,varnish.bryanmanalo-d9.docksal.*
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    extends:
      file: /Users/bryanmanalo/.docksal/stacks/services.yml
      service: apache
    hostname: web
    healthcheck:
      interval: 10s
    image: docksal/apache:2.4-2.5
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/bryanmanalo/websites/bryanmanalo-d9
      io.docksal.virtual-host: bryanmanalo-d9.docksal,*.bryanmanalo-d9.docksal,bryanmanalo-d9.docksal.*
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
networks:
  default:
    name: bryanmanalo-d9_default
volumes:
  cli_home:
    name: bryanmanalo-d9_cli_home
  db_data:
    name: bryanmanalo-d9_db_data
  docksal_ssh_agent:
    name: docksal_ssh_agent
    external: true
  project_root:
    name: bryanmanalo-d9_project_root
    driver: local
    driver_opts:
      device: :/Users/bryanmanalo/websites/bryanmanalo-d9
      o: addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,actimeo=1
      type: nfs
---------------------
  ```

</details>
