### ISSUE TITLE
Project autostart disabled error

### ISSUE THREAD

**Issue by paulsheldrake** [docksal/docksal#1680]
**Description**

If I spin up a project and it automatically goes to sleep it won't start up again

**Steps to reproduce the issue:**

1. `fin config set --global PROJECT_INACTIVITY_TIMEOUT 2h`
2. `fin up`
3. Wait for the project to go to sleep.
4. `fin up`
5. Get the following screen even though the fin output shows all the containers have started. "Project autostart disabled"
<img width="779" alt="Screenshot 2022-05-10 at 5 59 30 AM" src="https://user-images.githubusercontent.com/1062456/167637476-52180239-74b5-4ba2-9049-59ced16acfd0.png">

**Describe the results you expected:**

I would expect the project to be accessible even after it goes to sleep when it's restarted

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: ncbi-bookshare
COMPOSE_FILE:
/Users/paul/.docksal/stacks/volumes-nfs.yml
/Users/paul/.docksal/stacks/stack-pantheon.yml
/Users/paul/work/kanopi/benetech/ncbi-bookshare/.docksal/docksal.yml
ENV_FILE:
/Users/paul/work/kanopi/benetech/ncbi-bookshare/.docksal/docksal.env
/Users/paul/work/kanopi/benetech/ncbi-bookshare/.docksal/docksal-local.env

PROJECT_ROOT: /Users/paul/work/kanopi/benetech/ncbi-bookshare
DOCROOT: web
VIRTUAL_HOST: ncbi-bookshare.docksal.site
VIRTUAL_HOST_ALIASES: *.ncbi-bookshare.docksal.site
IP: 192.168.64.100

MySQL endpoint: 127.0.0.1:55044
Public URL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 8.8.8.8
    - 9.9.9.9
    - 8.8.8.8
    - 9.9.9.9
    - 8.8.8.8
    - 9.9.9.9
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: "0"
      COMPOSER_DEFAULT_VERSION: null
      COMPOSER_DISABLE_XDEBUG_WARN: "0"
      DOCROOT: web
      DRUSH_ALLOW_XDEBUG: "0"
      DRUSH_OPTIONS_URI: ncbi-bookshare.docksal.site
      GIT_USER_EMAIL: paul.sheldrake@gmail.com
      GIT_USER_NAME: Paul Sheldrake
      HOST_GID: "20"
      HOST_UID: "501"
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PANTHEON_ENV: live
      PANTHEON_SITE: ncbi-bookshare
      PHP_IDE_CONFIG: null
      SECRET_ACQUIA_CLI_KEY: 2e7d4*****1b701
      SECRET_ACQUIA_CLI_SECRET: 6qmXB*****GoxUA
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: VB0Q_*****iVsX1
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: ncbi-bookshare.docksal.site
      XDEBUG_CONFIG: client_host=192.168.64.1 client_port=9000
      XDEBUG_ENABLED: "0"
      XDEBUG_MODE: debug
    extends:
      file: /Users/paul/.docksal/stacks/services.yml
      service: cli
    hostname: cli
    healthcheck:
      interval: 10s
    image: docksal/cli:2-php7.4
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3070
      published: 3070
      protocol: tcp
    - mode: ingress
      target: 3071
      published: 3071
      protocol: tcp
    - mode: ingress
      target: 9003
      published: 9000
      protocol: tcp
    volumes:
    - type: volume
      source: docksal_ssh_agent
      target: /.ssh-agent
      read_only: true
      volume: {}
    - type: bind
      source: /Users/paul/work/kanopi/benetech/ncbi-bookshare/.docksal/etc/drush
      target: /etc/drush
      read_only: true
      bind:
        create_host_path: true
    - type: volume
      source: cli_home
      target: /home/docker
      volume: {}
    - type: bind
      source: /tmp/.docksal/ncbi-bookshare
      target: /tmp/.docksal/ncbi-bookshare
      read_only: true
      bind:
        create_host_path: true
    - type: volume
      source: project_root
      target: /var/www
      volume:
        nocopy: true
  db:
    dns:
    - 8.8.8.8
    - 9.9.9.9
    - 8.8.8.8
    - 9.9.9.9
    - 8.8.8.8
    - 9.9.9.9
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    extends:
      file: /Users/paul/.docksal/stacks/services.yml
      service: mysql
    hostname: db
    healthcheck:
      interval: 10s
    image: docksal/mariadb:10.4
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3306
      protocol: tcp
    volumes:
    - type: volume
      source: db_data
      target: /var/lib/mysql
      volume: {}
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - "80"
    - "80"
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.ncbi-bookshare.docksal.site
    networks:
      default: null
    user: root
  pma:
    environment:
      PMA_HOST: db
      PMA_PASSWORD: root
      PMA_USER: root
    hostname: pma
    image: phpmyadmin/phpmyadmin
    labels:
      io.docksal.virtual-host: pma.ncbi-bookshare.docksal.site
    networks:
      default: null
  redis:
    dns:
    - 8.8.8.8
    - 9.9.9.9
    environment:
      REDIS_MAXMEMORY: 256m
    extends:
      file: /Users/paul/.docksal/stacks/services.yml
      service: redis
    hostname: redis
    healthcheck:
      interval: 10s
    image: wodby/redis:5.0
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
  solr:
    dns:
    - 8.8.8.8
    - 9.9.9.9
    extends:
      file: /Users/paul/.docksal/stacks/services.yml
      service: solr
    hostname: solr
    healthcheck:
      interval: 10s
    image: docksal/solr:1.0-solr3
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: solr.ncbi-bookshare.docksal.site,solr.ncbi-bookshare.docksal.site.*
      io.docksal.virtual-port: "8983"
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 8.8.8.8
    - 9.9.9.9
    environment:
      VARNISH_BACKEND_HOST: web
    extends:
      file: /Users/paul/.docksal/stacks/services.yml
      service: varnish
    hostname: varnish
    healthcheck:
      interval: 10s
    image: docksal/varnish:6.6-3.1
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: varnish.ncbi-bookshare.docksal.site,varnish.ncbi-bookshare.docksal.site.*
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 8.8.8.8
    - 9.9.9.9
    environment:
      NGINX_BASIC_AUTH_PASS: null
      NGINX_BASIC_AUTH_USER: null
      NGINX_FCGI_HOST_PORT: cli:9000
      NGINX_SERVER_ROOT: /var/www/web
      NGINX_VHOST_PRESET: drupal
    extends:
      file: /Users/paul/.docksal/stacks/services.yml
      service: nginx
    hostname: web
    healthcheck:
      interval: 10s
    image: docksal/nginx:1.20-1.2
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/paul/work/kanopi/benetech/ncbi-bookshare
      io.docksal.virtual-host: ncbi-bookshare.docksal.site,*.ncbi-bookshare.docksal.site,ncbi-bookshare.docksal.site.*
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
networks:
  default:
    name: ncbi-bookshare_default
volumes:
  cli_home:
    name: ncbi-bookshare_cli_home
  db_data:
    name: ncbi-bookshare_db_data
  docksal_ssh_agent:
    name: docksal_ssh_agent
    external: true
  project_root:
    name: ncbi-bookshare_project_root
    driver: local
    driver_opts:
      device: :/Users/paul/work/kanopi/benetech/ncbi-bookshare
      o: addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,actimeo=1
      type: nfs
---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  (paste your output here)
  ```

</details>
