### ISSUE TITLE
Gateway timeout after upgrading to MacOS Ventura

### ISSUE THREAD

**Issue by robertromore** [docksal/docksal#1727]
**Description**

Hi, just opening this issue to bring awareness to an issue I and others are experiencing with Ventura + Docker + NFS. After upgrading to MacOS Ventura, my projects were no longer accessible and I was receiving a 504 gateway timeout message. I believe the reason is due to NFS and large files (specifically Composer's autoload_*.php files). [Doing what this comment described](https://github.com/docker/for-mac/issues/6544#issuecomment-1297240885), I was finally able to access my projects. Specifically, I added `,wsize=32768,rsize=32768` to the end of the `volumes.project_root.driver_opts.o` in `~/.docksal/stacks/volumes-nfs.yml`:

```yml
# Mount project volumes with NFS
# For use on Mac with VirtualBox or Docker for Mac
# Pros: very good performance, almost realtime file sync 
# Cons: no inotify/fs watchers

version: "3.9"

volumes:
  cli_home:  # /home/docker volume in cli
  project_root:  # Project root volume (NFS)
    driver: local
    driver_opts:
      type: nfs
      device: :${PROJECT_ROOT}
      o: addr=${DOCKSAL_HOST_IP},vers=3,nolock,noacl,nocto,noatime,nodiratime,actimeo=1,wsize=32768,rsize=32768
  db_data:  # Database data volume (bind)
  docksal_ssh_agent:  # Shared ssh-agent volume
    external: true
```

**Steps to reproduce the issue:**

1. Be on MacOS Ventura
2. Start a project 
3. Access project's URL

**Describe the results you received:**

Gateway timeout 504

https://github.com/drud/ddev/issues/4122 has further discussion and information.
