### ISSUE TITLE
Dockerfile not used during project start since v1.18.x 

### ISSUE THREAD

**Issue by tomclopez** [docksal/docksal#1774]
**Description**

Since v1.18.x, changes made in a Dockerfile are not present in containers following "fin project start"

**Steps to reproduce the issue:**

<details>
  <summary>.docksal/docksal.yml:</summary>

  ```
services:
 ....
    cli:
      build: services/cli
      extends:
        file: ${HOME}/.docksal/stacks/services.yml
        service: cli
...
  ```
</details>
<details>
  <summary>.docksal/services/cli/Dockerfile:</summary>

  ```
  # Use a stock Docksal image as the base
FROM docksal/cli:php8.1-3.3

# nvm/node/npm are only available in the docker user context
USER docker

# Install additional global npm dependencies
RUN set -e; \
	# Initialize the user environment (this loads nvm)
	. $HOME/.profile; \
	# Install the necessary nodejs version
	nvm install 16.16.0; \
	nvm alias default 16.16.0; \
	# Install packages
	npm install -g nodemon;

# Always switch back to root in the end
USER root
  ```

</details>

<details>
  <summary>.docksal/commands/init:</summary>

  ```

#!/usr/bin/env bash

fin project rm -f
fin project start

  ```

</details>

1. Run "fin init"
2. Run "fin exec node -v"

**Describe the results you received:**
Node 18 is used "v18.13.0"

**Describe the results you expected:**
Node 16 should be used "v16.16.0"
