### ISSUE TITLE
Use tmpfs for mysql

### ISSUE THREAD

**Issue by attiks** [docksal/docksal#1793]
**Description**

For testing I want to use tmpfs to store mysql

I've change docksal.yml as follows

```yaml
services:
  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mysql
    volumes:
      - project_root:/var/www:ro,nocopy,cached  # Project root volume (read-only)
      - db_data:/var/lib/mysql  # Database data volume
    tmpfs:
      - /var/lib/mysql:uid=999,gid=999

volumes:
  db_data:
    driver_opts:
      type: tmpfs
      device: tmpfs
```

But not sure if that's sufficient, anybody tried this before?

Inspect still shows

```
        "Mounts": [
            {
                "Type": "volume",
                "Name": "hrinfo_db_data",
                "Source": "/var/lib/docker/volumes/hrinfo_db_data/_data",
                "Destination": "/var/lib/mysql",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "hrinfo_project_root",
                "Source": "/var/lib/docker/volumes/hrinfo_project_root/_data",
                "Destination": "/var/www",
                "Driver": "local",
                "Mode": "z",
                "RW": false,
                "Propagation": ""
            }
        ],
```
