### ISSUE TITLE
Error response from daemon: error while mounting volume: permission denied.

### ISSUE THREAD

**Issue by alexcracea** [docksal/docksal#1800]
**Description**

After updating docker and Docksal I started having an error with volume mounting during `fin up` command:
```
Starting services...
[+] Running 1/3
 ⠿ Container <project-name>_cli_1  Starting                                                                                                              0.7s
 ⠿ Container <project-name>_web_1  Recreated                                                                                                             0.1s
 ⠼ Container <project-name>_db_1   Starting                                                                                                              0.4s
Error response from daemon: error while mounting volume '/var/lib/docker/volumes/<project-name>_project_root/_data': failed to mount local volume: mount :/Users/<user>/sites/<project-name>:/var/lib/docker/volumes/<project-name>_project_root/_data, flags: 0xc00, data: addr=192.168.64.1,vers=3,nolock,noacl,nocto,actimeo=1,wsize=32768,rsize=32768: permission denied
```

Context: I initially updated Docker to latest version and immediately started having issues with DNS, this error:
```docker: Error response from daemon: Ports are not available: exposing port UDP 0.0.0.0:53 -> 0.0.0.0:0: listen udp 0.0.0.0:53: bind: address already in use.```
which I fixed with `fin config set --global DOCKSAL_DNS_DISABLED=1`, the main error appeared right after that

**System info**

Docksal version: 1.18.2
Docker version:
```
Engine: 24.0.6
Compose: v2.22.0-desktop.2
Credential Helper: v0.7.0
Kubernetes: v1.27.2
```

My system is:
MacBook Pro 2020: 2 GHz Quad-Core Intel Core i5
macOS Ventura 13.6 (22G120)

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: <project-name>
COMPOSE_FILE:
/Users/<user>/.docksal/stacks/volumes-nfs.yml
/Users/<user>/.docksal/stacks/stack-default.yml
/Users/<user>/sites/<project-name>/.docksal/docksal.yml
ENV_FILE:
/Users/<user>/sites/<project-name>/.docksal/docksal.env

PROJECT_ROOT: /Users/<user>/sites/<project-name>
DOCROOT: web
VIRTUAL_HOST: <project-name>.docksal.site
VIRTUAL_HOST_ALIASES: *.<project-name>.docksal.site
IP: 192.168.64.100

MySQL endpoint:
Public URL:

Docker Compose configuration
---------------------
name: <project-name>
services:
  cli:
    dns:
    - 8.8.8.8
    - 9.9.9.9
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: "0"
      COMPOSER_DEFAULT_VERSION: null
      COMPOSER_DISABLE_XDEBUG_WARN: "0"
      DOCROOT: web
      DRUSH_ALLOW_XDEBUG: "0"
      DRUSH_OPTIONS_URI: <project-name>.docksal.site
      GIT_USER_EMAIL: alexandru.cracea@ffwagency.com
      GIT_USER_NAME: alexcracea
      HOST_GID: "20"
      HOST_UID: "501"
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: serverName=<project-name>.docksal.site
      SECRET_ACQUIA_CLI_KEY: null
      SECRET_ACQUIA_CLI_SECRET: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: <project-name>.docksal.site
      XDEBUG_CONFIG: client_host=192.168.64.1 client_port=9003
      XDEBUG_ENABLED: "0"
      XDEBUG_MODE: debug
    expose:
    - "9000"
    - "9003"
    extends:
      file: /Users/<user>/.docksal/stacks/services.yml
      service: cli
    hostname: cli
    healthcheck:
      interval: 10s
    image: docksal/cli:php8.1-3.4
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    ports:
    - mode: ingress
      target: 9000
      protocol: tcp
    - mode: ingress
      target: 9003
      protocol: tcp
    volumes:
    - type: volume
      source: docksal_ssh_agent
      target: /.ssh-agent
      read_only: true
      volume: {}
    - type: volume
      source: cli_home
      target: /home/docker
      volume: {}
    - type: bind
      source: /tmp/.docksal/<project-name>
      target: /tmp/.docksal/<project-name>
      read_only: true
      bind:
        create_host_path: true
    - type: volume
      source: project_root
      target: /var/www
      volume:
        nocopy: true
  db:
    dns:
    - 8.8.8.8
    - 9.9.9.9
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    extends:
      file: /Users/<user>/.docksal/stacks/services.yml
      service: mariadb
    hostname: db
    healthcheck:
      interval: 10s
    image: docksal/mariadb:10.6-1.3
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3306
      protocol: tcp
    volumes:
    - type: volume
      source: db_data
      target: /var/lib/mysql
      volume: {}
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 8.8.8.8
    - 9.9.9.9
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/web
      APACHE_FCGI_HOST_PORT: cli:9000
    extends:
      file: /Users/<user>/.docksal/stacks/services.yml
      service: apache
    hostname: web
    healthcheck:
      interval: 10s
    image: docksal/apache:2.4-2.5
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/<user>/sites/<project-name>
      io.docksal.virtual-host: <project-name>.docksal.site,*.<project-name>.docksal.site,<project-name>.docksal.site.*
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
networks:
  default:
    name: <project-name>_default
volumes:
  cli_home:
    name: <project-name>_cli_home
  db_data:
    name: <project-name>_db_data
  docksal_ssh_agent:
    name: docksal_ssh_agent
    external: true
  project_root:
    name: <project-name>_project_root
    driver: local
    driver_opts:
      device: :/Users/<user>/sites/<project-name>
      o: addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,actimeo=1,wsize=32768,rsize=32768
      type: nfs
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  (paste your output here)
  ```

</details>
