### ISSUE TITLE
`fin share` Does Not Work

### ISSUE THREAD

**Issue by vaza18** [docksal/docksal#181]
**`fin share` Does Not Work**

`fin share`seems to be not working: http://pix.toile-libre.org/upload/original/1492605728.png
It returns white screen in browser and "400 Bad Request" error in terminal.

**Steps to reproduce the issue:**
1. Install the site using Docksal
2. cd project_dir
3. Run `fin share`
4. Copy Url from console and try to open it in browser.

**Describe the results you received:**

White screen in browser and error 400 in console.
Error in console: http://pix.toile-libre.org/upload/original/1492606012.png

**Describe the results you expected:**

The site should be opened in browser.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
vasiliy@vaza-laptop /media/vasiliy/shared/www/pfizer/da247ru (dev) $ fin config
---------------------
COMPOSE_PROJECT_NAME_SAFE: da247ru
COMPOSE_FILE:
/home/vasiliy/.docksal/stacks/volumes-bind.yml
/media/vasiliy/shared/www/pfizer/da247ru/.docksal/docksal.yml
ENV_FILE:
/media/vasiliy/shared/www/pfizer/da247ru/.docksal/docksal.env
/media/vasiliy/shared/www/pfizer/da247ru/.docksal/docksal-local.env

PROJECT_ROOT: /media/vasiliy/shared/www/pfizer/da247ru
DOCROOT: docroot
VIRTUAL_HOST: da247ru.docksal,*.da247ru.docksal
VIRTUAL_HOST_ALIASES: *.da247ru.docksal,*.da247ru.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32789

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:1.0-php5
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 32789:3306/tcp
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: ''
      APACHE_BASIC_AUTH_USER: ''
      APACHE_DOCUMENTROOT: /var/www/docroot
      VIRTUAL_HOST: da247ru.docksal,*.da247ru.docksal
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /media/vasiliy/shared/www/pfizer/da247ru
      io.docksal.virtual-host: da247ru.docksal,*.da247ru.docksal,*.da247ru.docksal,*.da247ru.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /home/vasiliy
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /media/vasiliy/shared/www/pfizer/da247ru
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
 vasiliy@vaza-laptop /media/vasiliy/shared/www/pfizer/da247ru (dev) $ fin sysinfo
███  OS & BASICS
Linux vaza-laptop 4.8.0-46-generic #49-Ubuntu SMP Fri Mar 31 13:57:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 16.10
fin version: 1.6.0
Mode:  Native / Docker for Mac/Windows
███  DOCKER
DOCKER_HOST:	

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:14:53 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:14:53 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
myimages/web          latest              73ac4ffe6955        4 weeks ago         188MB
wernight/ngrok        latest              de17e6990f7b        4 weeks ago         26.7MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        6 weeks ago         164MB
docksal/cli           1.1-php7            bdac44fe25f1        6 weeks ago         777MB
docksal/cli           1.1-php5            1d82105244d1        6 weeks ago         834MB
docksal/dns           1.0                 20c7a535479d        2 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        2 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        2 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        2 months ago        255MB
docksal/cli           1.0-php5            bde35eb43ad7        2 months ago        801MB
memcached             latest              e6b578fa744c        3 months ago        126MB
busybox               latest              7968321274dc        3 months ago        1.11MB
docksal/solr          1.0-solr4           fa6b236caf06        3 months ago        546MB
docksal/varnish       1.0-varnish4        35dae6b91ff9        3 months ago        99.5MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                      NAMES
a80c5a888e36        docksal/web:1.0-apache2.2   "/opt/startup.sh a..."   30 minutes ago      Up 30 minutes       80/tcp, 443/tcp                            pfpfproru_web_1
92672903ca35        memcached                   "docker-entrypoint..."   30 minutes ago      Up 30 minutes       11211/tcp                                  pfpfproru_memcached_1
8fc7cfcfd9c2        docksal/db:1.0-mysql-5.5    "/entrypoint.sh my..."   30 minutes ago      Up 30 minutes       0.0.0.0:32798->3306/tcp                    pfpfproru_db_1
a5eb14337eeb        docksal/cli:1.0-php5        "/opt/startup.sh g..."   30 minutes ago      Up 30 minutes       9000/tcp, 0.0.0.0:32770->22/tcp            pfpfproru_cli_1
b705ba333ed0        docksal/web:1.0-apache2.2   "/opt/startup.sh a..."   4 hours ago         Up 4 hours          80/tcp, 443/tcp                            da247ru_web_1
f9ddc41aca2f        docksal/cli:1.0-php5        "/opt/startup.sh g..."   4 hours ago         Up 4 hours          22/tcp, 9000/tcp                           da247ru_cli_1
3197bea39104        memcached                   "docker-entrypoint..."   4 hours ago         Up 4 hours          11211/tcp                                  da247ru_memcached_1
bed2472004d1        docksal/db:1.0-mysql-5.5    "/entrypoint.sh my..."   4 hours ago         Up 4 hours          0.0.0.0:32789->3306/tcp                    da247ru_db_1
34fad4adbad3        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      5 hours ago         Up 5 hours                                                     docksal-ssh-agent
b19b65ffab6c        docksal/dns:1.0             "/opt/entrypoint.s..."   5 hours ago         Up 5 hours          192.168.64.100:53->53/udp                  docksal-dns
1f08d57113d0        docksal/vhost-proxy:1.0     "/usr/local/bin/st..."   5 hours ago         Up 5 hours          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy
  ```

</details>
