### ISSUE TITLE
docksal website cannot be reached - trying to launch a project with WSL, Ubuntu 20.04 and Docker Desktop 4.17.0

### ISSUE THREAD

**Issue by sakethram171** [docksal/docksal#1815]
**Description**

Docksal website cannot be reached - trying to launch a project with Ubuntu 20.04 and Docker Desktop 4.17.0. Tried all possible approaches mentioned in the tickets.

**Steps to reproduce the issue:**

1.  Followed instructions here: https://docs.docksal.io/getting-started/setup/
2.  Launching a project using: https://docs.docksal.io/getting-started/project-setup/
3.  I tried browsing "http://myproject.docksal" in Chrome and it spins infinitely and throws "site can't be reached"

**Describe the results you received:**

Docksal website unreachable.

**Describe the results you expected:**

I wanted to verify the project launched by accessing the url, and further install and setup Drupal 10 project. Pinging 192.168.64.100 worked. Updated hosts file, flushed dns. I tried almost all possible solutions mentioned in the Github solutions, but it still shows site unreachable.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
COMPOSE_PROJECT_NAME_SAFE: myproject
COMPOSE_FILE:
/home/user/.docksal/stacks/volumes-bind.yml
/home/user/.docksal/stacks/stack-default.yml
/home/user/Projects/myproject/.docksal/docksal.yml
ENV_FILE:
/home/user/Projects/myproject/.docksal/docksal.env

PROJECT_ROOT: /home/user/Projects/myproject
DOCROOT: docroot
VIRTUAL_HOST: myproject.docksal
VIRTUAL_HOST_ALIASES: *.myproject.docksal
IP: 192.168.64.100

MySQL endpoint: 192.168.64.100:32769
Public URL:

Docker Compose configuration
---------------------
name: myproject
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: "0"
      COMPOSER_DEFAULT_VERSION: null
      COMPOSER_DISABLE_XDEBUG_WARN: "0"
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: "0"
      DRUSH_OPTIONS_URI: myproject.docksal
      GIT_USER_EMAIL: ""
      GIT_USER_NAME: ""
      HOST_GID: "1000"
      HOST_UID: "1000"
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACQUIA_CLI_KEY: null
      SECRET_ACQUIA_CLI_SECRET: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: myproject.docksal
      XDEBUG_CONFIG: client_host=192.168.64.1
      XDEBUG_ENABLED: "0"
    extends:
      file: /home/user/.docksal/stacks/services.yml
      service: cli
    hostname: cli
    healthcheck:
      interval: 10s
    image: docksal/cli:php8.1-3.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
    - type: volume
      source: docksal_ssh_agent
      target: /.ssh-agent
      read_only: true
      volume: {}
    - type: volume
      source: cli_home
      target: /home/docker
      volume: {}
    - type: bind
      source: /tmp/.docksal/myproject
      target: /tmp/.docksal/myproject
      read_only: true
      bind:
        create_host_path: true
    - type: volume
      source: project_root
      target: /var/www
      volume:
        nocopy: true
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    extends:
      file: /home/user/.docksal/stacks/services.yml
      service: mariadb
    hostname: db
    healthcheck:
      interval: 10s
    image: docksal/mariadb:10.6-1.3
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3306
      protocol: tcp
    volumes:
    - type: volume
      source: db_data
      target: /var/lib/mysql
      volume: {}
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    extends:
      file: /home/user/.docksal/stacks/services.yml
      service: apache
    hostname: web
    healthcheck:
      interval: 10s
    image: docksal/apache:2.4-2.5
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /home/user/Projects/myproject
      io.docksal.virtual-host: myproject.docksal,*.myproject.docksal,myproject.docksal.*
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
networks:
  default:
    name: myproject_default
volumes:
  cli_home:
    name: myproject_cli_home
  db_data:
    name: myproject_db_data
  docksal_ssh_agent:
    name: docksal_ssh_agent
    external: true
  project_root:
    name: myproject_project_root
    driver: local
    driver_opts:
      device: /home/user/Projects/myproject
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  DOCKSAL
Docksal version: v1.18.2
fin version:     v1.113.2

███  OS
Linux Ubuntu 22.04
Linux LAPTOP 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST :

███  DOCKER
Expected client version: 20.10.23
Expected server version: 20.10.23

Installed versions:

Client: Docker Engine - Community
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:45:08 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:42:57 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

███  DOCKER COMPOSE
Expected version:  2.15.1
Installed version: 2.15.1

███  DOCKSAL: PROJECTS
project     STATUS                 virtual host                                                project root
myproject   Up 6 hours (healthy)   myproject.docksal,*.myproject.docksal,myproject.docksal.*   /home/user/Projects/myproject

███  DOCKSAL: VIRTUAL HOSTS
*.myproject.docksal
myproject.docksal.*
myproject.docksal

███  DOCKSAL: NETWORKING

DOCKSAL_IP: 192.168.64.100
DOCKSAL_HOST_IP: 192.168.64.1
DOCKSAL_VHOST_PROXY_IP:
DOCKSAL_DNS_IP:
DOCKSAL_DNS_DISABLED: 0
DOCKSAL_NO_DNS_RESOLVER: 0
DOCKSAL_DNS_UPSTREAM:
DOCKSAL_DNS_DOMAIN: docksal

███  DOCKSAL: CONNECTIVITY

Host to 192.168.64.100:         PASS
Container to 192.168.64.100:    PASS
Container to 192.168.64.1:      PASS

Checking connectivity to http://dns-test.docksal...
Host: PASS
Containers: PASS

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID   IMAGE                      COMMAND                  CREATED             STATUS                       PORTS
                 NAMES
0e234205531c   docksal/ssh-agent:1.4      "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)
                 docksal-ssh-agent
617707ec6217   docksal/dns:1.2            "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)   192.168.64.100:53->53/udp
                 docksal-dns
e4bbea8b1414   docksal/vhost-proxy:1.8    "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
943ad985f0d9   docksal/apache:2.4-2.5     "httpd-foreground"       27 hours ago        Up 6 hours (healthy)         80/tcp, 443/tcp
                 myproject_web_1
3492a80fd283   docksal/cli:php8.1-3.3     "/opt/startup.sh sup…"   27 hours ago        Up 6 hours (healthy)         22/tcp, 3000/tcp, 9000/tcp
                 myproject_cli_1
568d8177cde9   docksal/mariadb:10.6-1.3   "docker-entrypoint.s…"   27 hours ago        Up 6 hours (healthy)         0.0.0.0:32769->3306/tcp, :::32769->3306/tcp              myproject_db_1


███  DOCKER DESKTOP
EXPECTED VERSION: 4.17.0
DETECTED VERSION:

███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
none            3.9G  4.0K  3.9G   1% /mnt/wsl
/dev/sde       1007G  1.5G  955G   1% /mnt/wsl/docker-desktop-data/isocache
none            3.9G   12K  3.9G   1% /mnt/wsl/docker-desktop/shared-sockets/host-services
/dev/sdd       1007G   60M  956G   1% /mnt/wsl/docker-desktop/docker-desktop-user-distro
/dev/loop0      476M  476M     0 100% /mnt/wsl/docker-desktop/cli-tools
none            397G   75G  322G  19% /usr/lib/wsl/drivers
/dev/sdc       1007G  5.0G  951G   1% /
none            3.9G  164K  3.9G   1% /mnt/wslg
none            3.9G     0  3.9G   0% /usr/lib/wsl/lib
rootfs          3.9G  2.1M  3.9G   1% /init
none            3.9G  1.4M  3.9G   1% /run
none            3.9G     0  3.9G   0% /run/lock
none            3.9G     0  3.9G   0% /run/shm
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
none            3.9G   76K  3.9G   1% /mnt/wslg/versions.txt
none            3.9G   76K  3.9G   1% /mnt/wslg/doc
drvfs           397G   75G  322G  19% /mnt/c
snapfuse        128K  128K     0 100% /snap/bare/5
snapfuse         74M   74M     0 100% /snap/core22/864
snapfuse         92M   92M     0 100% /snap/gtk-common-themes/1535
snapfuse         41M   41M     0 100% /snap/snapd/20290
snapfuse        132M  132M     0 100% /snap/ubuntu-desktop-installer/1276
snapfuse         41M   41M     0 100% /snap/snapd/20671
snapfuse        131M  131M     0 100% /snap/ubuntu-desktop-installer/1284
  ```

</details>
