### ISSUE TITLE
"fin up" is slow

### ISSUE THREAD

**Issue by MKorostoff** [docksal/docksal#182]
**Description**

When I run `fin up` it takes about 1 minute and 30 seconds to start up.  Here is a video showing this http://www.youtube.com/watch?v=0VLgTgKETwg.

**Steps to reproduce the issue:**

I don't know for sure that this reproduces on every system, but:

1. Create a new docksal site with the CLI container and Apache containers only.
2. Start the site.
3. Reboot the physical computer (so virtual box is stopped)
4. Give the command `fin up`

**Describe the results you received:**

The site starts, after about 1 minute and 30 seconds

**Describe the results you expected:**

The site would start in under 10 seconds (which used to be the case)

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME: game
COMPOSE_PROJECT_NAME_SAFE: game
COMPOSE_FILE:
/Users/matt/.docksal/stacks/volumes-bind.yml
/Users/matt/Misc/game/.docksal/docksal.yml
ENV_FILE:
/Users/matt/Misc/game/.docksal/docksal.env

PROJECT_ROOT: /Users/matt/Misc/game
DOCROOT: docroot
VIRTUAL_HOST: game.docksal
VIRTUAL_HOST_ALIASES: *.game.docksal
IP: 127.0.0.1
MYSQL:

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    environment:
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.1-php7
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  web:
    depends_on:
      cli:
        condition: service_started
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/matt/Misc/game
      io.docksal.virtual-host: game.docksal,*.game.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/matt
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/matt/Misc/game
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin Matts-MBP-3.fios-router.home 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
fin version: 1.1.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v1.13.1   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.11.1, build 7c5d5e4
docker-py version: 2.0.2
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.9.0, build 15fd4c7
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
memcached             latest              a5cffa71b5af        4 weeks ago         83.7 MB
wernight/ngrok        latest              de17e6990f7b        4 weeks ago         26.7 MB
busybox               latest              00f017a8c2a6        5 weeks ago         1.11 MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        6 weeks ago         164 MB
docksal/cli           1.1-php7            bdac44fe25f1        6 weeks ago         777 MB
docksal/cli           1.1-php5            1d82105244d1        6 weeks ago         834 MB
docksal/cli           php7                11437672cdfc        6 weeks ago         777 MB
docksal/dns           1.0                 20c7a535479d        2 months ago        61.6 MB
docksal/ssh-agent     1.0                 148220cc033d        2 months ago        12.2 MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        2 months ago        188 MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        2 months ago        255 MB
docksal/cli           1.0-php5            bde35eb43ad7        2 months ago        801 MB
mailhog/mailhog       latest              b1ce818de155        3 months ago        18.9 MB
docksal/cli           stable              87fa37d69264        3 months ago        804 MB
docksal/solr          1.0-solr4           fa6b236caf06        3 months ago        546 MB
docksal/varnish       1.0-varnish4        35dae6b91ff9        3 months ago        99.5 MB
docksal/apache        2.2-stable          f478c360dd98        6 months ago        201 MB
docksal/mysql         5.5                 98fbd291860c        6 months ago        325 MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                      NAMES
808a2e2715a5        docksal/web:1.0-apache2.2   "/opt/startup.sh a..."   2 weeks ago         Up 7 minutes        80/tcp, 443/tcp                            game_web_1
e6710bb902e2        docksal/cli:1.1-php7        "/opt/startup.sh g..."   2 weeks ago         Up 7 minutes        22/tcp, 9000/tcp                           game_cli_1
896a8b162da2        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      3 weeks ago         Up 7 minutes                                                   docksal-ssh-agent
2d8e300f21cd        docksal/dns:1.0             "/opt/entrypoint.s..."   3 weeks ago         Up 7 minutes        192.168.64.100:53->53/udp                  docksal-dns
960f3c9fba94        docksal/vhost-proxy:1.0     "/usr/local/bin/st..."   3 weeks ago         Up 7 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.10.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.88.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

███  NFS EXPORTS





# VAGRANT-BEGIN: 503 3a8891c7-7709-4aaa-bf5f-33043da335cd
"/private/var/www/amd" 192.168.88.88 -alldirs -mapall=503:0
# VAGRANT-END: 503 3a8891c7-7709-4aaa-bf5f-33043da335cd
# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917696k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/0832ad0d667b02a581f3d41bb134a95c3b8ae9702e80d90618324f365f2b9621 type aufs (rw,relatime,si=2a2996937219a9ed,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/4c09225676e5f369c988eb0fb0a6897fb5715934eeef485bc9e468b1b2c1b559 type aufs (rw,relatime,si=2a29969372d919ed,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/6bcfd774ed6d028f366c664a46671d9efe0fcb9f6f19eab065467024ba2d9a9b type aufs (rw,relatime,si=2a2996934b4eb9ed,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/896a8b162da2425601fb84b773b0c460c8350e242cd9232c3b7f5934a5a61566/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/2d8e300f21cd2e041ca680750f20f827660f545c84bbb361584a10af18b9c831/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/960f3c9fba947f481dd9d1a0867d56068339956d81d55a07a6a6ce4a262cf313/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/7d609c1b2837 type nsfs (rw)
nsfs on /var/run/docker/netns/d89d861e1869 type nsfs (rw)
nsfs on /var/run/docker/netns/5a8b9979b5b9 type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/4f631a8ed23c0ecee4da3ab41125136e42f65e53361c520e5be6629cfa4b8859 type aufs (rw,relatime,si=2a299693718429ed,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/e6710bb902e22f363416c5a9e364d87605a04619c3bb6c1063884b64351c3168/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/matt on /mnt/sda1/var/lib/docker/volumes/game_host_home/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/matt/Misc/game on /mnt/sda1/var/lib/docker/volumes/game_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/f680477bbd0b type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/d5eb25ca4c1dd0fc7d24272b7acce9a3df794dc0ef9f988f56bacfd52c1c2d97 type aufs (rw,relatime,si=2a299693719d29ed,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/808a2e2715a5b73f1e4314988fd619242a337d6bac480115a36c6cb75522c90b/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/0d8c8cf672df type nsfs (rw)

  ```

</details>
