### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#193]
We need to create `docksal/db-postgres` container and make functions in fin to perform same `import`, `dump`, `list` and `cli` commands on it. With new signature for db commands that appeared in 3cdf1889f8902bf2aa7e4d0b935eda5f979af382 it should be transparent for a user regardless of whether mysql or postgresql is used.

**Comment by lmakarov** [comment]
I would wait for this issue to collect some thumbs up before doing anything about PostgreSQL. Definitely not mainstream.

**Comment by attiks** [comment]
I needed this for a couple of projects, biggest changes is needed to the cli image, but is pretty straight forward

````
sudo apt-get update
sudo apt-get install postgresql-client
sudo apt-get install php7.0-pgsql
```

I didn't bother changing the fin db commands, I just connect directly into the postgres container to create database, role and do the import

**Comment by achekulaev** [comment]
Thanks for feedback @attiks.
What Docker image did you use for the PostreSQL database?

**Comment by attiks** [comment]
An internal one from the client, so cannot really share it, based on Alpine and postgres 9.3, nothing fancy AFAIK

**Comment by tjb328** [comment]
@lmakarov any chance that you are still considering PostreSQL support?

**Comment by lmakarov** [comment]
@tjb328 yes. There are several pieces in the scope of this integration.

1. `pgsql` and `pdo_pgsql` were added in the edge image versions of docksal/cli (https://github.com/docksal/service-cli/issues/31). So, basic PostreSQL support is coming and will be as basic/simple as using the [stock](https://hub.docker.com/_/postgres/) postres image from Docker Hub.  I just noticed, that we should probably the `postgresql-client` client as well in cli (`sudo apt-get install postgresql-client`). These are a **must have**, but easy to achieve.

2. `fin db` commands will need to be able to speak PostreSQL. This is a **should have** and will take most fo the effort, but does not need to happen right away.

3. Default settings. Can someone, who thumbed up this issue, provide any guidance in terms of what settings overrides should be included out of the box? That would help with a more fine tuned integration, similar to the one we offer with the customized MySQL images (`docksal/db:mysql-x.y`). This is a **nice to have**.

**Comment by attiks** [comment]
My experience

1/ Simulated using
```
sudo apt-get update
sudo apt-get install php7.0-pgsql postgresql-client
```

2/ Agreed, we just use fin drush sqlc to do the import, but not all drush commands work when using drush 8, so we installed drush 6 directly inside the cli container. Easiest test is running `drush cc`, which will return the following with drush 8

```
Enter a number to choose which cache to clear.
 [0]  :  Cancel   
 [1]  :  drush    
 [2]  :  registry
```

3/ I assume you mean settings for postgres?

**Comment by lmakarov** [comment]
@attiks 

> 3/ I assume you mean settings for postgres?

Yes. See how we alter the MySQL defaults [here](https://github.com/docksal/service-db/blob/master/mysql-5.5/default.cnf).

**Comment by attiks** [comment]
Only thing I could find is `max_locks_per_transaction = 256`, but not sure if it's needed

**Comment by lmakarov** [comment]
Here's the bare-bones using the latest Docksal 1.7.0  + docksal/cli edge images.

**docksal.env**

```bash
...
# Use nodb stack which does not include MySQL
DOCKSAL_STACK=default-nodb

# Override image versions
CLI_IMAGE='docksal/cli:edge-php7.1'
DB_IMAGE='postgres:9.6-alpine'

# PostgreSQL port mapping
PGSQL_PORT_MAPPING='0:5432'
...
```

**docksal.yml**

```yaml
version: "2.1"

services:
  db:
    hostname: db
    image: ${DB_IMAGE:-postgres:9.6-alpine}
    ports:
      - "${PGSQL_PORT_MAPPING:-5432}"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
```

**settings.local.php** (Drupal 8)

```
$databases['default']['default'] = array (
  'database' => 'postgres',
  'username' => 'postgres',
  'password' => 'postgres',
  'host' => 'db',
  'driver' => 'pgsql',
);
```

**Result**

![image](https://user-images.githubusercontent.com/1205005/37938123-7887aea2-3111-11e8-98a2-529750776498.png)

**Comment by tjb328** [comment]
@lmakarov  That worked great. Thank you for the interim solution.

**Comment by achekulaev** [comment]
Should we create `stack-lapp.yml`?

```yaml
version: "2.1"

services:
  # Web
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: web
    depends_on:
      - cli

  # DB
  db:
    hostname: db
    image: ${DB_IMAGE:-postgres:9.6-alpine}
    ports:
      - "${PGSQL_PORT_MAPPING:-5432}"
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # CLI
  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
```

**Comment by lmakarov** [comment]
@achekulaev I think that's a good idea and will make it even easier to use PostreSQL :)

**Comment by lmakarov** [comment]
After discussing this further with @achekulaev we came to an agreement, that it will be better to have an simple way to configure flexible stacks with swappable components, instead of producing many combinations (e.g. apache vs nginx, mysql vs pgsql vs mariadb vs xyz, etc.).

For now, I've added `pgsql` service to `services.yml`. It can be used in custom stacks like this:

**docksal.yml**
```yaml
version: "2.1"

services:
  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: pgsql
```

The rest stays the same as described in https://github.com/docksal/docksal/issues/193#issuecomment-376343111
