### ISSUE TITLE
Docksal project not shutting down properly?

### ISSUE THREAD

**Issue by ComboPrime** [docksal/docksal#201]
**Description**

Even though I run `fin stop` and `fin vm stop` after finishing each Docksal session, every time I then try to start up again I get the following error:

`ERROR:  Another project is already using the name 'project'
         Change the name of the current project by renaming the project folder (folder name defines the project name and has to be unique)
         or remove the other project's stack by running fin rm in /Users/username/Sites/project`

Trying to run `fin rm` as suggested just returns the same error. The only thing that works is removing the entire vm and re-creating.

This just started a week or so ago, possibly after upgrading to 1.6.0?

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
COMPOSE_PROJECT_NAME_SAFE: project
COMPOSE_FILE:
/Users/username/.docksal/stacks/volumes-bind.yml
/Users/username/sites/project/.docksal/docksal.yml
ENV_FILE:
/Users/username/sites/project/.docksal/docksal.env

PROJECT_ROOT: /Users/username/sites/project
DOCROOT: Docs
VIRTUAL_HOST: project.docksal,*.project.docksal
VIRTUAL_HOST_ALIASES: *.project.docksal,*.project.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    environment:
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.1-php7
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 33062:3306/tcp
  web:
    depends_on:
      cli:
        condition: service_started
    environment:
      APACHE_DOCUMENTROOT: /var/www/Docs
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/username/sites/project
      io.docksal.virtual-host: project.docksal,*.project.docksal,*.project.docksal,*.project.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/username
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/username/sites/project
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin A56330 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
Mac OS X 10.12.4
fin version: 1.6.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        2 months ago        164MB
docksal/cli           1.1-php7            bdac44fe25f1        2 months ago        777MB
docksal/dns           1.0                 20c7a535479d        3 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        3 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        3 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        3 months ago        255MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                      NAMES
4ffae803b6ca        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      24 hours ago        Up 3 minutes                                                   docksal-ssh-agent
8de15a3394be        docksal/dns:1.0           "/opt/entrypoint.s..."   24 hours ago        Up 3 minutes        192.168.64.100:53->53/udp                  docksal-dns
d732b81f2f92        docksal/vhost-proxy:1.0   "/usr/local/bin/st..."   24 hours ago        Up 3 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.88.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/45e5e6ca6d8e7da4a1ffc8f3e284fdf52168af9f90222749d1ca20b550701499 type aufs (rw,relatime,si=924de945011aaaaf,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/d422987bd0b55255f7e74bfad20ca8580d75a437bff8a5accf225f573cdade99 type aufs (rw,relatime,si=924de94517f05aaf,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/c9147f10dc65bbc6c869377eed0af488f039f4bac1491608bf115fc9b12e7036 type aufs (rw,relatime,si=924de945010d8aaf,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/8de15a3394be2d0b312908f3b1fbd54374dc378b442dae2b1443ff1546e4c448/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/b681cc3a0b68 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/4ffae803b6ca5644c5a3e6fa40bb831f8cf636ec9c07f509ec0f2234ca526334/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/d732b81f2f92ca1ed046953214fd8b6275d3f90b18cea1268b634158743c6041/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/444ed052c355 type nsfs (rw)
nsfs on /var/run/docker/netns/d500a3a975b3 type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
  ```

</details>
