### ISSUE TITLE
SOLR configuration not creating on Windows 7

### ISSUE THREAD

**Issue by drubage** [docksal/docksal#213]
After following [these instructions](http://docksal.readthedocs.io/en/master/tools/apache-solr/) I get the following error on my windows 7 machine:

```
ERROR: for solr  Cannot create container for service solr: create \c\Users\drew.michael\.babun\cygwin\home\drew.michael\projects\test-project\.docksal\etc\solr\conf: "\\c\\Users\\drew.michael\\.babun\\cygwin\\home\\drew.michael\\projects\\test-project\\.docksal\\etc\\solr\\conf" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path
Encountered errors while bringing up the project.
```

If I remove these lines from the docksal.yml file it seems to create SOLR okay but it won't import the configuration with those lines included:

```
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/conf:/var/lib/solr/conf:ro
```

**Comment by achekulaev** [comment]
Hello @drubage 
Thanks for reporting issues.
Please follow issue template and include `fin config` and `fin sysinfo` outputs

**Comment by drubage** [comment]
My bad!

**Description**

After following [these instructions](http://docksal.readthedocs.io/en/master/tools/apache-solr/) I get the following error on my windows 7 machine:

```
ERROR: for solr  Cannot create container for service solr: create \c\Users\drew.michael\.babun\cygwin\home\drew.michael\projects\test-project\.docksal\etc\solr\conf: "\\c\\Users\\drew.michael\\.babun\\cygwin\\home\\drew.michael\\projects\\test-project\\.docksal\\etc\\solr\\conf" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path
Encountered errors while bringing up the project.
```

If I remove these lines from the docksal.yml file it seems to create SOLR okay but it won't import the configuration with those lines included:

```
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/conf:/var/lib/solr/conf:ro
```

**Steps to reproduce the issue:**

1. Follow [these instructions](http://docksal.readthedocs.io/en/master/tools/apache-solr/)
2. Run fin up

**Describe the results you received:**

SOLR does not install properly.

**Describe the results you expected:**

A SOLR container.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: testproject
COMPOSE_FILE:
C:/Users/drew.michael/.babun/cygwin/home/drew.michael/.docksal/stacks/volumes-bind.yml
C:/Users/drew.michael/.babun/cygwin/home/drew.michael/projects/test-project/.docksal/docksal.yml
ENV_FILE:
C:/Users/drew.michael/.babun/cygwin/home/drew.michael/projects/test-project/.docksal/docksal.env

PROJECT_ROOT: /c/Users/drew.michael/.babun/cygwin/home/drew.michael/projects/test-project
DOCROOT: docroot
VIRTUAL_HOST: test-project.docksal
VIRTUAL_HOST_ALIASES: *.test-project.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - 10.0.2.3
    environment:
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.2-php7
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - 10.0.2.3
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.7
    ports:
    - 0:3306/tcp
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.test-project.docksal
    user: root
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached
  solr:
    hostname: solr
    image: docksal/solr:1.0-solr4
    volumes:
    - \c\Users\drew.michael\.babun\cygwin\home\drew.michael\projects\test-project\.docksal\etc\solr\conf:/var/lib/solr/conf:ro
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 10.0.2.3
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /c/Users/drew.michael/.babun/cygwin/home/drew.michael/projects/test-project
      io.docksal.virtual-host: test-project.docksal,*.test-project.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /c/Users/drew.michael/.babun/cygwin/home/drew.michael
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/drew.michael/.babun/cygwin/home/drew.michael/projects/test-project
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
CYGWIN_NT-6.1-WOW drfrulpt-PC 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
 Microsoft Windows [Version 6.1.7601]
fin version: 1.6.1
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   -        virtualbox   Error                                         Unknown       machine does not exist
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce
███  DOCKER
DOCKER_HOST:    tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build ee0f34e1
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine.exe version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
memcached             latest              c483d9f54256        2 weeks ago         83.7MB
mailhog/mailhog       latest              669347153085        3 weeks ago         19.1MB
docksal/cli           1.2-php7            aef362412c9f        4 weeks ago         787MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        2 months ago        164MB
docksal/dns           1.0                 20c7a535479d        3 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        3 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        3 months ago        188MB
docksal/db            1.0-mysql-5.7       35f1494f03b6        3 months ago        400MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        3 months ago        255MB
docksal/solr          1.0-solr4           fa6b236caf06        4 months ago        546MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                      NAMES
74bf18989d67        docksal/db:1.0-mysql-5.7   "/entrypoint.sh my..."   3 minutes ago       Up 3 minutes        0.0.0.0:32768->3306/tcp                    testproject_db_1
9918d2bc2f19        memcached                  "docker-entrypoint..."   2 hours ago         Up 3 minutes        11211/tcp                                  testproject_memcached_1
d87b108d92a8        mailhog/mailhog            "MailHog"                2 hours ago         Up 3 minutes        80/tcp, 1025/tcp, 8025/tcp                 testproject_mail_1
6988e2c02228        docksal/ssh-agent:1.0      "/run.sh ssh-agent"      22 hours ago        Up 6 minutes                                                   docksal-ssh-agent
bdddd2507890        docksal/dns:1.0            "/opt/entrypoint.s..."   22 hours ago        Up 6 minutes        192.168.64.100:53->53/udp                  docksal-dns
29885903c954        docksal/vhost-proxy:1.0    "/usr/local/bin/st..."   22 hours ago        Up 6 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.22r115126
███  NETWORK INTERFACES
Name:            VirtualBox Host-Only Ethernet Adapter #3
GUID:            460e711e-a9ce-4d94-859d-688b4c72c5dd
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:a0e5:db19:4d6d:c6ed
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:3a
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #3

Name:            VirtualBox Host-Only Ethernet Adapter #5
GUID:            04a45e75-8f4f-43d5-b64a-39cfefe14441
DHCP:            Enabled
IPAddress:       169.254.215.240
NetworkMask:     255.255.0.0
IPV6Address:     fe80:0000:0000:0000:0c22:c105:01df:d7f0
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:36
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #5

Name:            VirtualBox Host-Only Ethernet Adapter #4
GUID:            055ec56b-bdd7-4a00-95d2-1d2e3e751213
DHCP:            Enabled
IPAddress:       169.254.223.221
NetworkMask:     255.255.0.0
IPV6Address:     fe80:0000:0000:0000:c4db:ef70:c434:dfdd
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:34
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #4

Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            a57ef571-f08d-40fe-9967-a9ed529a803b
DHCP:            Disabled
IPAddress:       192.168.88.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:91e1:009e:8725:60a5
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:1c
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2

Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            58be5bf6-a111-43be-9723-1da59beb5683
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:6c34:cc99:0894:a7c0
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:10
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter

███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/0fc7c21a659477e7d0c10da55d22020fdbb6595d6fb6495f69280ffd55418cfe type aufs (rw,relatime,si=2924d62ef04dff1f,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/509ce1a2fd16cd7b7b3a5b03e8bd7e77d3f60848cee7fe817ceb7d1d972d9906 type aufs (rw,relatime,si=2924d62ef1d6af1f,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/391235890cc2af1632abf90fc37517588a81f087e1664c01de95d488001fa5d8 type aufs (rw,relatime,si=2924d62ef1c54f1f,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/bdddd2507890c97f2d79b98db2c13553121dc4d72ae1d3758af2b981690a0c51/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/6988e2c02228934631326dabac3cdc3267fb193fa15db413feecf75b4e494c0c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/29885903c954a12c40058fb1a06fc00757d5c68a0a291d0364d4688273127e7e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/85bd2ec4de90 type nsfs (rw)
nsfs on /var/run/docker/netns/4696bc2a116a type nsfs (rw)
nsfs on /var/run/docker/netns/0f2547d25dd4 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/71117a84b65549e661d305c0d00a2fb7e3b2a2c680c1aa788ec5004f480203c9 type aufs (rw,relatime,si=2924d62ef0905f1f,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/16c2cdd16f3c8a7992759c66dfda1c9c9adc48d050207eb9c82343440b41c412 type aufs (rw,relatime,si=2924d62ef3060f1f,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/9918d2bc2f190113f94b8bafff3c3d20d8ec258bc697a251d6698096f0472573/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/d87b108d92a8040d0345c3f862da635a299bbb71b6fac412bfd341589644c909/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/eb658ad5020c6e617d6301eda382c3a27876f60cfdc60f897ba87e06df26b90a type aufs (rw,relatime,si=2924d62ef0a73f1f,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/74bf18989d671e6c88fcc51d20fb7a4d402bfa88aaa2e950ee3ee0d0d72a2359/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/29e211dc49a7 type nsfs (rw)
nsfs on /var/run/docker/netns/9e8a15884baf type nsfs (rw)
nsfs on /var/run/docker/netns/3284b41f55ca type nsfs (rw)
  ```

</details>
