### ISSUE TITLE
Unable to create a project

### ISSUE THREAD

**Issue by alexdesignworks** [docksal/docksal#217]
**Description**
Following steps to create a project in empty directory, I'm unable to start containers due to the following error:
```
ERROR: for cli  Cannot create container for service cli: error while mounting volume with options: type='none' device='/www/ds1/d7' o='bind': no such file or directory
``` 
**Steps to reproduce the issue:**

1. `fin create project`
2. select d7
3. Wait for process to fail.

**Describe the results you received:**

Output:
```
alex:/www/ds1 $ fin project create
Please enter the name of your project (all one word, no spaces or slashes): d7

What would you like to install?
[1] Drupal 7
[2] Drupal 8
[3] Wordpress
[4] Magento

: 1

Your site will be created at /www/ds1/d7
Your site will run Drupal 7
The URL of your site will be http://d7.docksal

Do you wish to proceed? [y/n]: y
 Cloning repository...
Cloning into 'd7'...
remote: Counting objects: 2107, done.
remote: Total 2107 (delta 0), reused 0 (delta 0), pack-reused 2107
Receiving objects: 100% (2107/2107), 3.80 MiB | 314.00 KiB/s, done.
Resolving deltas: 100% (691/691), done.
 Step 1  Initializing local project configuration...
Making site directory writable...
Copying /www/ds1/d7/docroot/sites/default/settings.local.php...
 Step 2  Recreating services...
Removing containers...
Removing d7_db_1 ... done
Removing network d7_default
Removing volume d7_project_root
Volume docksal_ssh_agent is external, skipping
Removing volume d7_host_home
Starting services...
Creating network "d7_default" with the default driver
Creating volume "d7_project_root" with local driver
Creating volume "d7_host_home" with local driver
Creating d7_db_1
Creating d7_cli_1

ERROR: for db  Cannot start service db: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/d7_project_root/_data': error while mounting volume with options: type='none' device='/www/ds1/d7' o='bind': no such file or directory

ERROR: for cli  Cannot create container for service cli: error while mounting volume with options: type='none' device='/www/ds1/d7' o='bind': no such file or directory
ERROR: Encountered errors while bringing up the project.
```

**Describe the results you expected:**

Built project and started containers.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: d7
COMPOSE_FILE:
/Users/alex/.docksal/stacks/volumes-bind.yml
/Users/alex/.docksal/stacks/stack-default.yml
ENV_FILE:
/www/ds1/d7/.docksal/docksal.env

PROJECT_ROOT: /www/ds1/d7
DOCROOT: docroot
VIRTUAL_HOST: d7.docksal
VIRTUAL_HOST_ALIASES: *.d7.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - 10.0.2.3
    environment:
      HOST_GID: '20'
      HOST_UID: '501'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.2-php5
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - 10.0.2.3
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 10.0.2.3
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /www/ds1/d7
      io.docksal.virtual-host: d7.docksal,*.d7.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/alex
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /www/ds1/d7
      o: bind
      type: none

---------------------
```
</details>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin O-o.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
Mac OS X 10.12.4
fin version: 1.6.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/cli           1.2-php5            11f47dc7d024        4 weeks ago         845MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        2 months ago        164MB
docksal/dns           1.0                 20c7a535479d        3 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        3 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        3 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        3 months ago        255MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                      NAMES
9514f7bb26fa        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      24 minutes ago      Up 24 minutes                                                  docksal-ssh-agent
a10013a6341d        docksal/dns:1.0           "/opt/entrypoint.s..."   24 minutes ago      Up 24 minutes       192.168.64.100:53->53/udp                  docksal-dns
5843aa9e5676        docksal/vhost-proxy:1.0   "/usr/local/bin/st..."   24 minutes ago      Up 24 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.20r114629
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       10.20.1.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       10.71.34.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

███  NFS EXPORTS
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/e2602ae9103ab76465aaf46b2197101617a9ea4f2faf20dfa604d65c757a8ebc type aufs (rw,relatime,si=cfdab2b43971650b,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/5843aa9e56768352fedc3b4a0b962305a83961def330086193d3f8dcb6841e2d/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/69b4c10ccda3 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/5f7f2febf482a43c995b822cc194e1378242c986a19062d271a0feebd9f02a76 type aufs (rw,relatime,si=cfdab2b439f4450b,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/a10013a6341d172cd6a19ab3e95dd92f7e7be18236ff8b5e85f6d73da60c5e5b/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/f3a588be6fd5 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/a1297e2c521383c5aa27c1bf09a96afc9dea0ce7f740ecd6fc4e2b3f8f3f9ec9 type aufs (rw,relatime,si=cfdab2b43a86850b,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/9514f7bb26faf0376c090f0a2b4ec1660d34210a655f53246f387452de0b7e1e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/28dc955194c6 type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
  ```

</details>
