### ISSUE TITLE
Cannot start service db and cannot create container for service cli errors on OSX install

### ISSUE THREAD

**Issue by cedewey** [docksal/docksal#226]
**Description**

When trying to start my first container, I get two errors. This is on OSX 10.12.4

**Steps to reproduce the issue:**

1. Created project directory structure as documented at http://docksal.readthedocs.io/en/master/getting-started/project-setup/
2. Moved into the project directory
3. Ran `fin start`

**Errors I received:**

```
ERROR: for db  Cannot start service db: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/drutopia_project_root/_data': error while mounting volume with options: type='none' device='/Users/claytondewey/projects/drutopia' o='bind': no such file or directory

ERROR: for cli  Cannot create container for service cli: error while mounting volume with options: type='none' device='/Users/claytondewey/projects/drutopia' o='bind': no such file or directory
ERROR: Encountered errors while bringing up the project. 
```

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: drutopia
COMPOSE_FILE:
/Users/claytondewey/.docksal/stacks/volumes-bind.yml
/Users/claytondewey/.docksal/stacks/stack-default.yml

PROJECT_ROOT: /Users/claytondewey/projects/drutopia
DOCROOT: docroot
VIRTUAL_HOST: drutopia.docksal
VIRTUAL_HOST_ALIASES: *.drutopia.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - ''
    environment:
      HOST_GID: '20'
      HOST_UID: '501'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.2-php7
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - ''
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - ''
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/claytondewey/projects/drutopia
      io.docksal.virtual-host: drutopia.docksal,*.drutopia.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/claytondewey
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/claytondewey/projects/drutopia
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin MacBook-Pro-5.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
Mac OS X 10.12.4
fin version: 1.9.0
Mode:  VirtualBox VM
███  INSTANCES
NAME       ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default    -        virtualbox   Saved                                         Unknown
docksal    *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce
Kalabox2   -        virtualbox   Stopped                                       Unknown
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/cli           1.2-php7            aef362412c9f        6 weeks ago         787MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        2 months ago        164MB
docksal/dns           1.0                 20c7a535479d        3 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        3 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        3 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        3 months ago        255MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
84640e991d02        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      26 minutes ago      Up 26 minutes                                                                docksal-ssh-agent
99cc72d6a129        docksal/dns:1.0           "/opt/entrypoint.s..."   26 minutes ago      Up 26 minutes       192.168.64.100:53->53/udp                                docksal-dns
8e61f9e4cd91        docksal/vhost-proxy:1.0   "/usr/local/bin/st..."   26 minutes ago      Up 26 minutes       192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.50.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.33.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       192.168.44.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

Name:            vboxnet3
GUID:            786f6276-656e-4374-8000-0a0027000003
DHCP:            Disabled
IPAddress:       192.168.88.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:03
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet3

Name:            vboxnet4
GUID:            786f6276-656e-4474-8000-0a0027000004
DHCP:            Disabled
IPAddress:       192.168.89.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:04
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet4

Name:            vboxnet5
GUID:            786f6276-656e-4574-8000-0a0027000005
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:05
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet5

Name:            vboxnet6
GUID:            786f6276-656e-4674-8000-0a0027000006
DHCP:            Disabled
IPAddress:       10.13.37.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:06
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet6

Name:            vboxnet7
GUID:            786f6276-656e-4774-8000-0a0027000007
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:07
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet7

███  NFS EXPORTS
# VAGRANT-BEGIN: 501 40c6b3ad-eff9-40a1-b0e0-7c811620216b
"/Users/claytondewey/htdocs/drutopia_sdk" 192.168.89.92 -alldirs -mapall=501:20
# VAGRANT-END: 501 40c6b3ad-eff9-40a1-b0e0-7c811620216b
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/522252d6bb9f17af4e977eac476e7d1170713463ed70ef5d9382a6dbbea30164 type aufs (rw,relatime,si=65f2de9360b21bdc,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/8e61f9e4cd91a43b9f891606bc55d5638d250896236c2a7511e3e936bfdee472/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/c1cd8635e3c7 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/2eca83491271699509868db932e112ebb6ad596c63f498e867421754581f4f8f type aufs (rw,relatime,si=65f2de9363c49bdc,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/99cc72d6a1292f3976870e50212bb3348065b54507bb9b09f5370112eb785e50/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/6608f179d979 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/c46e76389d5b1ae03966586a160993db9a1e783e96c5384bcb2e96908e9e98f4 type aufs (rw,relatime,si=65f2de9363c77bdc,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/84640e991d029735d3d733234508697117662048e1260b162d154d57cd280074/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/8cebc7c6fe09 type nsfs (rw)
  ```

</details>

**Comment by lmakarov** [comment]
Hi @cedewey, you have a conflict in your `/etc/exports` file.
Comment out the record you have there for the other, Vagrant based VM and try again:

```
"/Users/claytondewey/htdocs/drutopia_sdk"
```

We have already have a feature request to improve the compatibility with NFS exports and other software using it: #133

**Comment by cedewey** [comment]
Thanks for the assistance on this. I removed the conflicting record in /etc/exports but am now running into the same issue with a new project I created.

<details>
  <summary>fin config output</summary>

```
COMPOSE_PROJECT_NAME_SAFE: drutopiasite
COMPOSE_FILE:
/Users/claytondewey/.docksal/stacks/volumes-bind.yml
/Users/claytondewey/.docksal/stacks/stack-default.yml

PROJECT_ROOT: /Users/claytondewey/projects/drutopiasite
DOCROOT: docroot
VIRTUAL_HOST: drutopiasite.docksal
VIRTUAL_HOST_ALIASES: *.drutopiasite.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - ''
    environment:
      HOST_GID: '20'
      HOST_UID: '501'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.2-php7
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - ''
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - ''
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/claytondewey/projects/drutopiasite
      io.docksal.virtual-host: drutopiasite.docksal,*.drutopiasite.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/claytondewey
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/claytondewey/projects/drutopiasite
      o: bind
      type: none

---------------------

```

</details>

<details>
  <summary>fin sysinfo output</summary>

```
███  OS & BASICS
Darwin MacBook-Pro-5.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
Mac OS X 10.12.5
fin version: 1.9.0
Mode:  VirtualBox VM
███  INSTANCES
NAME       ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default    -        virtualbox   Saved                                         Unknown
docksal    *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce
Kalabox2   -        virtualbox   Stopped                                       Unknown
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/cli           1.2-php7            aef362412c9f        2 months ago        787MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        3 months ago        164MB
docksal/dns           1.0                 20c7a535479d        5 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        5 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        5 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        5 months ago        255MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
84640e991d02        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      4 weeks ago         Up 7 minutes                                                                 docksal-ssh-agent
99cc72d6a129        docksal/dns:1.0           "/opt/entrypoint.s..."   4 weeks ago         Up 7 minutes        192.168.64.100:53->53/udp                                docksal-dns
8e61f9e4cd91        docksal/vhost-proxy:1.0   "/usr/local/bin/st..."   4 weeks ago         Up 7 minutes        192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.50.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.33.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       192.168.44.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

Name:            vboxnet3
GUID:            786f6276-656e-4374-8000-0a0027000003
DHCP:            Disabled
IPAddress:       192.168.88.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:03
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet3

Name:            vboxnet4
GUID:            786f6276-656e-4474-8000-0a0027000004
DHCP:            Disabled
IPAddress:       192.168.89.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:04
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet4

Name:            vboxnet5
GUID:            786f6276-656e-4574-8000-0a0027000005
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:05
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet5

Name:            vboxnet6
GUID:            786f6276-656e-4674-8000-0a0027000006
DHCP:            Disabled
IPAddress:       10.13.37.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:06
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet6

Name:            vboxnet7
GUID:            786f6276-656e-4774-8000-0a0027000007
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:07
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet7

███  NFS EXPORTS
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/2eca83491271699509868db932e112ebb6ad596c63f498e867421754581f4f8f type aufs (rw,relatime,si=61c1a18d1e52f5ae,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/c46e76389d5b1ae03966586a160993db9a1e783e96c5384bcb2e96908e9e98f4 type aufs (rw,relatime,si=61c1a18d103ba5ae,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/522252d6bb9f17af4e977eac476e7d1170713463ed70ef5d9382a6dbbea30164 type aufs (rw,relatime,si=61c1a18d1ef1e5ae,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/84640e991d029735d3d733234508697117662048e1260b162d154d57cd280074/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/99cc72d6a1292f3976870e50212bb3348065b54507bb9b09f5370112eb785e50/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/8e61f9e4cd91a43b9f891606bc55d5638d250896236c2a7511e3e936bfdee472/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/fbbad202d4d6 type nsfs (rw)
nsfs on /var/run/docker/netns/6fbc777250a7 type nsfs (rw)
nsfs on /var/run/docker/netns/868ecfbf30c6 type nsfs (rw)
MacBook-Pro-5:drutopiasite claytondewey$

</details>
