### ISSUE TITLE
Running `fin vm env` does not output anything.

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#230]
**Description**

When I execute `fin vm env` I expect to see environment variables output so I can use the native docker client to interface with the machine. When I run the command, I see no output.

**Steps to reproduce the issue:**

1. Run `fin vm env`.
2. Confirm there is no output.

**Describe the results you received:**

`fin vm env` does not output anything.

**Describe the results you expected:**

I expected to see environment variables output such that I could set them and use `docker` to control the machine.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: docksalblt
COMPOSE_FILE:
/Users/les.peabody/.docksal/stacks/volumes-bind.yml
/Users/les.peabody/.docksal/stacks/stack-acquia.yml
ENV_FILE:
/Users/les.peabody/Sites/docksalblt/.docksal/docksal.env

PROJECT_ROOT: /Users/les.peabody/Sites/docksalblt
DOCROOT: docroot
VIRTUAL_HOST: docksalblt.docksal
VIRTUAL_HOST_ALIASES: *.docksalblt.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32774

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - ''
    environment:
      HOST_GID: '1106437719'
      HOST_UID: '1729411499'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.2-php7
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - ''
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro
  memcached:
    dns:
    - 192.168.64.100
    - ''
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached
  solr:
    dns:
    - 192.168.64.100
    - ''
    hostname: solr
    image: docksal/solr:1.0-solr4
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - ''
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:1.0-varnish4
    labels:
      io.docksal.virtual-host: varnish.docksalblt.docksal
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - ''
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/les.peabody/Sites/docksalblt
      io.docksal.virtual-host: docksalblt.docksal,*.docksalblt.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/les.peabody
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/les.peabody/Sites/docksalblt
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin BOSGEN-NMX0813.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
Mac OS X 10.12.5
fin version: 1.9.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   -        virtualbox   Stopped                                       Unknown       
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
memcached             latest              6c32c12d9101        2 weeks ago         83.9MB
docksal/cli           1.2-php7            aef362412c9f        6 weeks ago         787MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        2 months ago        164MB
docksal/dns           1.0                 20c7a535479d        4 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        4 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        4 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        4 months ago        255MB
docksal/solr          1.0-solr4           fa6b236caf06        4 months ago        546MB
docksal/varnish       1.0-varnish4        35dae6b91ff9        4 months ago        99.5MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
98efafb2b418        docksal/varnish:1.0-varnish4   "/opt/startup.sh"        About an hour ago   Up About an hour    80/tcp                                                   docksalblt_varnish_1
c7f88225bfd2        docksal/web:1.0-apache2.2      "/opt/startup.sh a..."   About an hour ago   Up About an hour    80/tcp, 443/tcp                                          docksalblt_web_1
f32231ee0747        docksal/cli:1.2-php7           "/opt/startup.sh s..."   About an hour ago   Up About an hour    22/tcp, 9000/tcp                                         docksalblt_cli_1
0a444e91410b        docksal/solr:1.0-solr4         "/opt/solr/bin/sol..."   About an hour ago   Up About an hour    8983/tcp                                                 docksalblt_solr_1
1f3e17f95b53        docksal/db:1.0-mysql-5.5       "/entrypoint.sh my..."   About an hour ago   Up About an hour    0.0.0.0:32774->3306/tcp                                  docksalblt_db_1
4eb9e6de49d0        memcached                      "docker-entrypoint..."   About an hour ago   Up About an hour    11211/tcp                                                docksalblt_memcached_1
1f0b08781d44        docksal/ssh-agent:1.0          "/run.sh ssh-agent"      6 hours ago         Up 6 hours                                                                   docksal-ssh-agent
9aeeb1f56038        docksal/dns:1.0                "/opt/entrypoint.s..."   6 hours ago         Up 6 hours          192.168.64.100:53->53/udp                                docksal-dns
b1545ff02c21        docksal/vhost-proxy:1.0        "/usr/local/bin/st..."   6 hours ago         Up 6 hours          192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

███  NFS EXPORTS

# docker-machine-nfs-begin default #
/Users 192.168.99.100 -alldirs -maproot=0
# docker-machine-nfs-end default #
# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/275055ea167f3696753069259986a4c8825987030d158cb0cb36e04e68b9a8ac type aufs (rw,relatime,si=c37266df4e389b31,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/b1545ff02c212166c700817b13ff9d65f0db4f7fcae257470f386d98887d3d4f/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/d3bc7d5eb263 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/2aa8168931155c9be6b226f6d7adb0a6c333373875a7c6fd4f586ac8231cc8aa type aufs (rw,relatime,si=c37266df4e501b31,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/9aeeb1f56038167ed7c8315b625cc95fa56d1add69dbea400e3b75de8108830e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/fdd0b8e5971e type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/2c444f910a6b0da4be1d34072156775ffa942912c0f4d8a953720f7835b1ea3a type aufs (rw,relatime,si=c37266df4ff47b31,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/1f0b08781d44e2682d5998e15d85721dd73c9035b98c825de22505db48faab69/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/65f151604347 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/c1e63635314aed2ae68edb25a5a11925eec99327f97e02b1f58fcfdeec1abdf9 type aufs (rw,relatime,si=c37266df66998b31,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/fea46e6c9842274869e815f910d73be365de8061e2a56d41d57a21c60a520b59 type aufs (rw,relatime,si=c37266df4eab2b31,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/431d022844e996dfabfd61f2e8724ef777397e534007826a9f523623d1d3ade8 type aufs (rw,relatime,si=c37266df4e2d7b31,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/333a124540a07b8b02c1cd893516a6af7c099411c7df7a910368143279369bdf type aufs (rw,relatime,si=c37266df4ea30b31,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/4eb9e6de49d0a30f91c88b30ad1df12fd016fa9d5bb7f646bc2a6f6815c88e4d/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/7073a0be1ab2 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/f32231ee0747e460f29e775b36cb1d033bce3f07a24df4304c75ee0f08df2d09/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/les.peabody on /mnt/sda1/var/lib/docker/volumes/docksalblt_host_home/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/les.peabody/Sites/docksalblt on /mnt/sda1/var/lib/docker/volumes/docksalblt_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
shm on /mnt/sda1/var/lib/docker/containers/1f3e17f95b53500e85c509b87c8f3701f9364874d6f3543e74b0d4c52e94116c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/0a444e91410b514e111d170a22ae984f9f0188248741242e12ce21b1e2890c6b/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/c277bda8262a type nsfs (rw)
nsfs on /var/run/docker/netns/e5183f6c2ea4 type nsfs (rw)
nsfs on /var/run/docker/netns/82aea60b3d3d type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/c6f67129a7860a211acb476d339d7c19c0f8f229492f86dd464c84201107a7c0 type aufs (rw,relatime,si=c37266df4dc37b31,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/c7f88225bfd20d3a43f0e238d377ee6037565271f21eb15abc9a1d88203f6e1d/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/aac23d96cc87 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/5b615681bf9906f32e990ea98efdd4e4b137c8f2bd61076f872a358b23ae01a5 type aufs (rw,relatime,si=c37266df4dbbab31,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/98efafb2b418e44a2dbe1e0cb8243363c908053f8fa0f018d949c6d54faed137/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/41d6f96113f2 type nsfs (rw)

  ```

</details>
