### ISSUE TITLE
Xdebug not working with docksal/cli:edge-php7

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#237]
**Description**

The tip of devel-php7 for docksal/service-cli does not support Xdebug execution.

**Steps to reproduce the issue:**

Assuming a Drupal 8 codebase.

1. Update docksal.yml to use docksal/cli:edge-php7.
2. `fin up`
3. Activate debug in browser/PHPStorm.
4. Place a breakpoint in index.php.
5. Reload page.
6. Confirm that the breakpoint is not hit.

**Describe the results you received:**

Breakpoint is not hit.

**Describe the results you expected:**

Execution should stop at breakpoint.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: docksalblt
COMPOSE_FILE:
/Users/les.peabody/.docksal/stacks/volumes-bind.yml
/Users/les.peabody/.docksal/stacks/stack-acquia.yml
/Users/les.peabody/Sites/docksalblt/.docksal/docksal.yml
ENV_FILE:
/Users/les.peabody/Sites/docksalblt/.docksal/docksal.env
/Users/les.peabody/Sites/docksalblt/.docksal/docksal-local.env

PROJECT_ROOT: /Users/les.peabody/Sites/docksalblt
DOCROOT: docroot
VIRTUAL_HOST: docksalblt.docksal
VIRTUAL_HOST_ALIASES: *.docksalblt.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32776

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - ''
    environment:
      HOST_GID: '1106437719'
      HOST_UID: '1729411499'
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:edge-php7
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - ''
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro
  memcached:
    dns:
    - 192.168.64.100
    - ''
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached
  solr:
    dns:
    - 192.168.64.100
    - ''
    hostname: solr
    image: docksal/solr:1.0-solr4
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - ''
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:1.0-varnish4
    labels:
      io.docksal.virtual-host: varnish.docksalblt.docksal
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - ''
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/les.peabody/Sites/docksalblt
      io.docksal.virtual-host: docksalblt.docksal,*.docksalblt.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/les.peabody
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/les.peabody/Sites/docksalblt
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin BOSGEN-NMX0813.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
Mac OS X 10.12.5
fin version: 1.9.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   -        virtualbox   Stopped                                       Unknown       
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
lpeabody/cli          latest              e78e39d53fef        29 minutes ago      837MB
lpeabody/cli          xdebug-fix          2d2a03f375c5        44 minutes ago      931MB
docksal/cli           edge-php7           b4c9fc6c5599        18 hours ago        842MB
lpeabody/cli          <none>              80dca81ae257        41 hours ago        931MB
memcached             latest              6c32c12d9101        2 weeks ago         83.9MB
debian                jessie              3e83c23dba6a        2 weeks ago         124MB
docksal/cli           1.2-php7            aef362412c9f        6 weeks ago         787MB
docksal/cli           latest              c192d7f5857a        7 weeks ago         786MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        2 months ago        164MB
docksal/dns           1.0                 20c7a535479d        4 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        4 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        4 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        4 months ago        255MB
docksal/solr          1.0-solr4           fa6b236caf06        4 months ago        546MB
docksal/varnish       1.0-varnish4        35dae6b91ff9        4 months ago        99.5MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
af34292d1afb        docksal/varnish:1.0-varnish4   "/opt/startup.sh"        17 minutes ago      Up 17 minutes       80/tcp                                                   docksalblt_varnish_1
ad482585c245        docksal/web:1.0-apache2.2      "/opt/startup.sh a..."   17 minutes ago      Up 17 minutes       80/tcp, 443/tcp                                          docksalblt_web_1
a5f2d00d97ca        docksal/cli:edge-php7          "/opt/startup.sh s..."   17 minutes ago      Up 17 minutes       22/tcp, 9000/tcp                                         docksalblt_cli_1
486f0ba73bd4        memcached                      "docker-entrypoint..."   27 minutes ago      Up 27 minutes       11211/tcp                                                docksalblt_memcached_1
233671d7ec2f        docksal/solr:1.0-solr4         "/opt/solr/bin/sol..."   27 minutes ago      Up 27 minutes       8983/tcp                                                 docksalblt_solr_1
8a3f61c572f5        docksal/db:1.0-mysql-5.5       "/entrypoint.sh my..."   27 minutes ago      Up 27 minutes       0.0.0.0:32776->3306/tcp                                  docksalblt_db_1
1f0b08781d44        docksal/ssh-agent:1.0          "/run.sh ssh-agent"      2 days ago          Up 19 hours                                                                  docksal-ssh-agent
9aeeb1f56038        docksal/dns:1.0                "/opt/entrypoint.s..."   2 days ago          Up 19 hours         192.168.64.100:53->53/udp                                docksal-dns
b1545ff02c21        docksal/vhost-proxy:1.0        "/usr/local/bin/st..."   2 days ago          Up 19 hours         192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

███  NFS EXPORTS

# docker-machine-nfs-begin default #
/Users 192.168.99.100 -alldirs -maproot=0
# docker-machine-nfs-end default #
# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/2c444f910a6b0da4be1d34072156775ffa942912c0f4d8a953720f7835b1ea3a type aufs (rw,relatime,si=a3d79a6f2248d280,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/1f0b08781d44e2682d5998e15d85721dd73c9035b98c825de22505db48faab69/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/2aa8168931155c9be6b226f6d7adb0a6c333373875a7c6fd4f586ac8231cc8aa type aufs (rw,relatime,si=a3d79a6f1a9f1280,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/9aeeb1f56038167ed7c8315b625cc95fa56d1add69dbea400e3b75de8108830e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/275055ea167f3696753069259986a4c8825987030d158cb0cb36e04e68b9a8ac type aufs (rw,relatime,si=a3d79a6f195ed280,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/b1545ff02c212166c700817b13ff9d65f0db4f7fcae257470f386d98887d3d4f/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/cab360e4713a type nsfs (rw)
nsfs on /var/run/docker/netns/17244cf5e813 type nsfs (rw)
nsfs on /var/run/docker/netns/72d90adf7992 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/195c79006f3fb0b84cf4880d1090d51d873c01b28ace0cad048fd5ccfa984ded type aufs (rw,relatime,si=a3d79a6f2306a280,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/059e923b8ac9ef2c65d3613123fe1c3c1c56335fb2ce78c0190cf344841aec72 type aufs (rw,relatime,si=a3d79a6f1812e280,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/eb6afb9a191d367359fbc2c74b70df7e9c2d9cbcdfe2e2c39f34ade8e533fddf type aufs (rw,relatime,si=a3d79a6f22d0e280,dio,dirperm1)
192.168.64.1:/Users/les.peabody/Sites/docksalblt on /mnt/sda1/var/lib/docker/volumes/docksalblt_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
shm on /mnt/sda1/var/lib/docker/containers/233671d7ec2ff90f9f6b4206c3f8536a4b9efe6eeb9eec158898969665777952/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/8a3f61c572f53113373536fd122171585dedc48da71f786c300fb399906b9c7f/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/486f0ba73bd484137118bdd119f54d56941fd2c150e5e63052786cb788541621/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/b1aba0f885f3 type nsfs (rw)
nsfs on /var/run/docker/netns/d83500b04bd9 type nsfs (rw)
nsfs on /var/run/docker/netns/95d80c30f12c type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/48c58b90547f3462a0ab718bdaf988b0aa06fda54be27cefd12289b6a0c7adab type aufs (rw,relatime,si=a3d79a6f2e5de280,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/a5f2d00d97cac71b8e91b6e3d244e322ee074a024900773b30396f8c0341d64a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/les.peabody on /mnt/sda1/var/lib/docker/volumes/docksalblt_host_home/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/4aa04e8c2f2a type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/596859a377db23b576727b4c600a06fab2228e0a1d215d58b6efc44d50885091 type aufs (rw,relatime,si=a3d79a6f289b2280,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/ad482585c2451603b75adef7109a2266ea8247b6703ed82df81a7d5d530eba1e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/6d3812563c94 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/9354bf385b618b9158d8bfc4ced127c788a9bccfcc41e6614685bc214615f0d4 type aufs (rw,relatime,si=a3d79a6f18675280,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/af34292d1afb4f2648c7f6374c12275f524a7b67887e381baede4997ae1d6e1d/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/ed6826312f23 type nsfs (rw)

  ```

</details>
