### ISSUE TITLE
VirtualBox Host-Only Network causing DNS errors

### ISSUE THREAD

**Issue by Martins15** [docksal/docksal#242]
**Description**

I have frequent errors in my browser:
![2017-05-15](https://cloud.githubusercontent.com/assets/4337733/26687558/afc207e0-46f8-11e7-9246-5ab4dc4efb94.png)

After I go to connection settings and disable all VirtualBox Host-Only Networks, the error disappears and the internet in working fine. But I get another errors in babun
![cyber desktop-3up385k_ _cygdrive_c_ffw_hcp_pfizerprouk 2017-06-01 18 34 11](https://cloud.githubusercontent.com/assets/4337733/26687637/eff2c6ce-46f8-11e7-9f5b-efd1bab27932.png)

fin reset system && fin cleanup --hard && fin vm restart helps but the original DNS error returns
  

**Steps to reproduce the issue:**

1. 
2. 
3. 

**Describe the results you received:**

Results...

**Describe the results you expected:**

Expected behavior...

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
COMPOSE_PROJECT_NAME_SAFE: pfizerprouk
COMPOSE_FILE:
C:/Users/cyber/.babun/cygwin/home/cyber/.docksal/stacks/volumes-bind.yml
C:/ffw/hcp/pfizerprouk/.docksal/docksal.yml
ENV_FILE:
C:/ffw/hcp/pfizerprouk/.docksal/docksal.env
C:/ffw/hcp/pfizerprouk/.docksal/docksal-local.env

PROJECT_ROOT: /c/ffw/hcp/pfizerprouk
DOCROOT: docroot
VIRTUAL_HOST: pfizerprouk.docksal,*.pfizerprouk.docksal
VIRTUAL_HOST_ALIASES: *.pfizerprouk.docksal,*.pfizerprouk.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
The APACHE_BASIC_AUTH_USER variable is not set. Defaulting to a blank string.
The APACHE_BASIC_AUTH_PASS variable is not set. Defaulting to a blank string.
networks: {}
services:
  cli:
    environment:
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.0-php5
    ports:
    - 0:22/tcp
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 0:3306/tcp
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached
  web:
    depends_on:
      cli:
        condition: service_started
    environment:
      APACHE_BASIC_AUTH_PASS: ''
      APACHE_BASIC_AUTH_USER: ''
      APACHE_DOCUMENTROOT: /var/www/docroot
      VIRTUAL_HOST: pfizerprouk.docksal,*.pfizerprouk.docksal
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /c/ffw/hcp/pfizerprouk
      io.docksal.virtual-host: pfizerprouk.docksal,*.pfizerprouk.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /c/Users/cyber/.babun/cygwin/home/cyber
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /c/ffw/hcp/pfizerprouk
      o: bind
      type: none

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
CYGWIN_NT-10.0-WOW DESKTOP-3UP385K 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
 Microsoft Windows [Version 10.0.15063]
fin version: 1.9.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce
███  DOCKER
DOCKER_HOST:    tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build ee0f34e1
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine.exe version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
memcached             latest              6c32c12d9101        3 weeks ago         83.9MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        3 months ago        164MB
docksal/dns           1.0                 20c7a535479d        4 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        4 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        4 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        4 months ago        255MB
docksal/cli           1.0-php5            bde35eb43ad7        4 months ago        801MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
fad2e7e335ea        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      2 hours ago         Up About a minute                                                            docksal-ssh-agent
b27686b4a308        docksal/dns:1.0           "/opt/entrypoint.s..."   2 hours ago         Up About a minute   192.168.64.100:53->53/udp                                docksal-dns
721452f52ed9        docksal/vhost-proxy:1.0   "/usr/local/bin/st..."   2 hours ago         Up About a minute   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            VirtualBox Host-Only Ethernet Adapter #8
GUID:            c06c0e34-114a-47d6-aed3-83d9a8199739
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:6c6d:bf45:3ef5:5642
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:2e
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #8

███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/711c2014e77a4a8c1f0de3fd797473452f2d2d55da46546c171f803322b585b3 type aufs (rw,relatime,si=dfbd651080c482c4,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/33bc3de82da9dd3fe404c7ec60dcd1137518bbae2b131f3906cd527635103325 type aufs (rw,relatime,si=dfbd651080f582c4,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/721452f52ed9ae2cb9d16ac90951ed0e623c4adea15e0d45631b8af6d951fa7e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/194a95eaf7d4a16d1ba13d55a5b2aab39c9a4467319de7ebe20d7fe12c5d07c7 type aufs (rw,relatime,si=dfbd65108060b2c4,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/b27686b4a308eb669c3b603723627e39f6dff0f850b52b36df7999aab8e9fa02/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/fad2e7e335ea4c33f0a8395e353b0c3a01e6442ca7c64d2116e1b0e78405ae68/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/3930333dd27c type nsfs (rw)
nsfs on /var/run/docker/netns/296cf43d0304 type nsfs (rw)
nsfs on /var/run/docker/netns/df81548fa0e8 type nsfs (rw)
//192.168.64.1/docksal-c on /c type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=cyber,domain=DESKTOP-3UP385K,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=61440,wsize=65536,actimeo=1)
//192.168.64.1/docksal-d on /d type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=cyber,domain=DESKTOP-3UP385K,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=61440,wsize=65536,actimeo=1)

  ```

</details>
