### ISSUE TITLE
ERROR: for cli  Cannot start service cli: error while mounting volume

### ISSUE THREAD

**Issue by ssudhak** [docksal/docksal#247]
Running fin init gives me following error.

ERROR: for cli  Cannot start service cli: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/fusion_project_sites/_data': error while mounting volume with options: type='none' device='/Users/a251267/Sites/platform/fusion/../../sites' o='bind': no such file or directory
ERROR: Encountered errors while bringing up the project.

checked other similar issue but cant find anything other than changing the project from /Users directory. Please help me

**Steps to reproduce the issue:**

1. run fin init
2. 
3. 

**Describe the results you received:**

ERROR: for cli  Cannot start service cli: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/fusion_project_sites/_data': error while mounting volume with options: type='none' device='/Users/a251267/Sites/platform/fusion/../../sites' o='bind': no such file or directory
ERROR: Encountered errors while bringing up the project.

**Describe the results you expected:**

Expected behavior...

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: fusion
COMPOSE_FILE:
/Users/a251267/.docksal/stacks/volumes-bind.yml
/Users/a251267/.docksal/stacks/stack-default.yml
/Users/a251267/Sites/platform/fusion/.docksal/docksal.yml
ENV_FILE:
/Users/a251267/Sites/platform/fusion/.docksal/docksal.env

PROJECT_ROOT: /Users/a251267/Sites/platform/fusion
DOCROOT: docroot
VIRTUAL_HOST: jjfusion.docksal,*.jjfusion.docksal
VIRTUAL_HOST_ALIASES: *.jjfusion.docksal,*.jjfusion.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      HOST_GID: '20'
      HOST_UID: '502'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.0-php5
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_sites:/sites:rw
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached:1.4-alpine
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/a251267/Sites/platform/fusion
      io.docksal.virtual-host: jjfusion.docksal,*.jjfusion.docksal,*.jjfusion.docksal,*.jjfusion.docksal
    volumes:
    - project_sites:/sites:ro
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/a251267
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/a251267/Sites/platform/fusion
      o: bind
      type: none
  project_sites:
    driver: local
    driver_opts:
      device: /Users/a251267/Sites/platform/fusion/../../sites
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin 02HW030478.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
Mac OS X 10.12.4
fin version: 1.10.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
memcached             1.4-alpine          e36e3b0dc88c        5 days ago          6.91MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        3 months ago        164MB
docksal/dns           1.0                 20c7a535479d        4 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        4 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        4 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        4 months ago        255MB
docksal/cli           1.0-php5            bde35eb43ad7        4 months ago        801MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
5e4fb517b88d        memcached:1.4-alpine       "docker-entrypoint..."   About an hour ago   Up 8 minutes        11211/tcp                                                fusion_memcached_1
fb03346fec8e        docksal/db:1.0-mysql-5.5   "/entrypoint.sh my..."   About an hour ago   Up 8 minutes        0.0.0.0:32768->3306/tcp                                  fusion_db_1
737a968e2bb1        docksal/ssh-agent:1.0      "/run.sh ssh-agent"      About an hour ago   Up 8 minutes                                                                 docksal-ssh-agent
1d8d80d526ad        docksal/dns:1.0            "/opt/entrypoint.s..."   About an hour ago   Up 8 minutes        192.168.64.100:53->53/udp                                docksal-dns
9ceb530d637a        docksal/vhost-proxy:1.0    "/usr/local/bin/st..."   About an hour ago   Up 8 minutes        192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/8b9eb232a70e641123b3f92702d9f3ed70e83e3f55d9a68a4cf026ea817fdf91 type aufs (rw,relatime,si=c7cc479e939b7f5d,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/9ceb530d637a1435951ff6254c3d3430601cc790ca2d7a4490a47e43e23fc75c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/bf22870f1fcfcecc2349fd6d13395bf0e4bba8f1d0f84bab89caac4dca8d5f91 type aufs (rw,relatime,si=c7cc479e938e8f5d,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/fdb9c83336b0c09bbed446bf9e86a8f4344d7e652c16dec9bb58b503b5dc247e type aufs (rw,relatime,si=c7cc479e92f47f5d,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/737a968e2bb14015f17b1e169626134ac5cd9c9d351cca0415d26fbbf964354c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/1d8d80d526ad595b915ed4733971a47970d8578bbc36bc4e9a225a76b894fb46/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/e04d121f87ee type nsfs (rw)
nsfs on /var/run/docker/netns/10ad37569230 type nsfs (rw)
nsfs on /var/run/docker/netns/c5a16ae2c2eb type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/bb1f8bdd7c4caaff056280575ff1bd9b8141d9d1868c6d2d8eb16e4de6c05774 type aufs (rw,relatime,si=c7cc479e93c39f5d,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/c5029df3f66603f5653abd4d4842fc1b65e91a7344404ab70c9afca10d2a5c9d type aufs (rw,relatime,si=c7cc479e93f3ff5d,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/fb03346fec8e9e1236993c35b4a711349ef5fb6cf3e872733130d6937c20e375/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/5e4fb517b88d4155e2286d18e9105c2449e8497002729d12a1e9ba6a9fb8517a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/a251267/Sites/platform/fusion on /mnt/sda1/var/lib/docker/volumes/fusion_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/b65f4cb6329e type nsfs (rw)
nsfs on /var/run/docker/netns/a05d0d97c67d type nsfs (rw)
  ```

</details>
