### ISSUE TITLE
MailHog isn't able to log emails

### ISSUE THREAD

**Issue by aczietlow** [docksal/docksal#248]
**Description**

After following the documentation [here](http://docksal.readthedocs.io/en/master/tools/mailhog/)  MailHog is unable to capture emails attempted to be sent.  [here](https://gist.github.com/aczietlow/943fb09a210c4fb3b5730b5c306e05c8) is a link to my full system info

 My docker.yml config for the mail container:
```
cli:
    hostname: cli
    image: docksal/cli:1.2-php7
    volumes:
      - project_root:/var/www:rw
      - host_home:/.home:ro
      - docksal_ssh_agent:/.ssh-agent:ro
    environment:
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
  mail:
    hostname: mail
    image: mailhog/mailhog
    expose:
      - "80"
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:80
      - MH_UI_BIND_ADDR=0.0.0.0:80
    labels:
      - io.docksal.virtual-host=webmail.${VIRTUAL_HOST}
    user: root
```

php.ini:
```
sendmail_path = '/usr/local/bin/mhsendmail --smtp-addr=mail:1025'
```

When I run the following test script I would expect to see TRUE returned and see my test email via the mailHog UI, instead it returns FALSE

```
<?php

$to = 'test@mailhog.local';
$subject = 'Test message';
$message = 'Test message.';
$headers = 'Some content!' . "\r\n" .
  'Reply-To: test@mailhog.local' . "\r\n" .
  'X-Mailer: PHP/' . phpversion();
$result = mail($to, $subject, $message, $headers);
var_dump($result); # /var/www/docroot/index.php:10:boolean false
```

I'm not sure if this is an issue with MailHog, the port bindings, or with the mhsendmail library. I'll try to dig more into tonight, but any help would be greatly appreciated.
