### ISSUE TITLE
Add MailHog usage example in docksal/drupal7-advanced

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#255]

**Comment by attiks** [comment]
To enable Mailhog I did the following

1. Create/edit .docksal/docksal-local.yml

```
version: "2.1"

services:
  mail:
    hostname: mail
    user: root
    image: mailhog/mailhog
    expose:
      - "80"
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:80
      - MH_UI_BIND_ADDR=0.0.0.0:80
    labels:
      - io.docksal.virtual-host=webmail.${VIRTUAL_HOST}
    
```

2. Edit .docksal/etc/php/php.ini

```
sendmail_path = '/usr/local/bin/mhsendmail --smtp-addr=mail:1025'
```

3. Restart

``
fin restart
```
