### ISSUE TITLE
Failed to execute script docker-compose

### ISSUE THREAD

**Issue by briancoffelt** [docksal/docksal#258]
**Description**

I’m encountering a docker-compose error when running `fin start`. I’m on a Mac running OS X Sierra and I’ve had success getting Drupal 8 sites up and running with Docksal. The main problem stems from installing Solr via docker-compose. If I comment out my **docksal-local.yml** file, `fin start` will successfully run. Lastly, the site I’m having trouble with is set up to run with a Pantheon remote environment.

**Steps to reproduce the issue:**

1. Pull down local copy of a Drupal 8 site from Pantheon.
2. Install this Docksal config: https://github.com/ultimike/drupaleasy-pantheon-docksal
3. Run `fin start`

**Description of the results I received:**

[~/Sites/testsite]$ fin start
Starting services...
Creating network “mysite_default" with the default driver
Creating volume “mysite_project_root" with local driver
Creating volume “mysite_host_home" with local driver
Pulling solr (docksal/solr:1.0-solr3)...
Traceback (most recent call last):
File "docker-compose", line 3, in 
File "compose/cli/main.py", line 67, in main
File "compose/cli/main.py", line 117, in perform_command
File "compose/cli/main.py", line 922, in up
File "compose/project.py", line 395, in up
File "compose/service.py", line 333, in ensure_image_exists
File "compose/service.py", line 938, in pull
File "site-packages/docker/api/image.py", line 358, in pull
File "site-packages/docker/auth.py", line 50, in get_config_header
File "site-packages/docker/auth.py", line 85, in resolve_authconfig
File "site-packages/docker/auth.py", line 129, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('docker-credential-osxkeychain not installed or not available in PATH',)
Failed to execute script docker-compose

**Description of the results I expected:**

I expected a functional running Docksal environment with Solr installed.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: testsite
COMPOSE_FILE:
/Users/me/.docksal/stacks/volumes-bind.yml
/Users/me/.docksal/stacks/stack-default.yml
/Users/me/Sites/mysite/.docksal/docksal-local.yml
ENV_FILE:

/Users/me/Sites/mysite/.docksal/docksal-local.env

PROJECT_ROOT: /Users/me/Sites/mysite
DOCROOT: web
VIRTUAL_HOST: mysite.docksal
VIRTUAL_HOST_ALIASES: *.mysite.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - ''
    environment:
      HOST_GID: '20'
      HOST_UID: '501'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:edge-php7
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - ''
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro
  solr:
    environment:
      DOMAIN_NAME: solr.testsite.docksal
    hostname: solr
    image: docksal/solr:1.0-solr3
    ports:
    - 8983:8983/tcp
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - ''
    environment:
      APACHE_DOCUMENTROOT: /var/www/web
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/me/Sites/mysite
      io.docksal.virtual-host: mysite.docksal,*.mysite.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/me
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/me/Sites/mysite
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  OS & BASICS
Darwin My-MacBook-Pro 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
Mac OS X 10.12.5
fin version: 1.9.0
Mode:  VirtualBox VM
INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   -        virtualbox   Error                                         Unknown       machine does not exist
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce   
DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/cli           1.2-php5            11f47dc7d024        2 months ago        845MB
docksal/cli           1.2-php7            aef362412c9f        2 months ago        787MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        3 months ago        164MB
docksal/dns           1.0                 20c7a535479d        4 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        4 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        4 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        4 months ago        255MB
DOCKER: CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
5f534605f612        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      2 weeks ago         Up 10 minutes                                                                docksal-ssh-agent
74ea197afbcb        docksal/dns:1.0           "/opt/entrypoint.s..."   2 weeks ago         Up 10 minutes       192.168.64.100:53->53/udp                                docksal-dns
d03e146d58ec        docksal/vhost-proxy:1.0   "/usr/local/bin/st..."   2 weeks ago         Up 10 minutes       192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
VIRTUALBOX
5.1.22r115126
NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/f9aaa6cae636d83a26071094acfdb9891337e5ed399080f55a40bcab8ebe6414 type aufs (rw,relatime,si=4aace9ed21111637,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/0a5c2ab0108f3f5f1e20179b8b3ee5fc7364986d450d281a47da526615f40972 type aufs (rw,relatime,si=4aace9ed2103b637,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/33c943b4e657a199293ce75119de4766d7d7e1f72786cd15bd327b856ac1f3f3 type aufs (rw,relatime,si=4aace9ed21281637,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/5f534605f612072d04ff9c1ceaabee7a959f3cefbfe2ce176b890748dfdc1c02/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/74ea197afbcb3818a220c67af1d52772f1dac6561b8e9e43b65ef5cdd2d9d559/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/a06adce0609d type nsfs (rw)
nsfs on /var/run/docker/netns/2272e9d02180 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/d03e146d58ec4a5e3287ddf03b37503bd88a01ae15ce0c4543bba626d92a3a6a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/c7f8ab99d937 type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
  ```

</details>
