### ISSUE TITLE
Behat running issues.

### ISSUE THREAD

**Issue by ssudhak** [docksal/docksal#259]
Not able to run behat from docksal.
its giving Site cant be reached in the screenshot.

yml file content.
default:
  extensions:
    Behat\MinkExtension:
      base_url: http://fusion-demo.jjfusion.docksal
      files_path: /var/www/docroot/sites/demo/tests/code/assets
      browser_name: chrome
      selenium2:
        wd_host: http://browser:4444/wd/hub
    Drupal\DrupalExtension:
      drupal:
        drupal_root: /var/www/docroot
      drush:
        alias: 'jjfusion.demo'
docker:
  extensions:
    Behat\MinkExtension:
      base_url: http://fusion-demo.jjfusion.docksal
      files_path: /var/www/docroot/sites/demo/tests/code/assets
      browser_name: chrome
      selenium2:
        wd_host: http://browser:4444/wd/hub
    Drupal\DrupalExtension:
      drupal:
        drupal_root: /var/www/docroot
      drush:
        alias: 'jjfusion.demo'

imports:
  - behat.common.yml

**Steps to reproduce the issue:**

1. 
2. 
3. 

**Describe the results you received:**

Results...
![2017-06-08-15 25 40-59396c74252fe](https://user-images.githubusercontent.com/7603029/26937145-9796e01e-4c3e-11e7-962b-60a99d389590.png)

**Describe the results you expected:**

Expected behavior...

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: fusion1291
COMPOSE_FILE:
/Users/a251267/.docksal/stacks/volumes-bind.yml
/Users/a251267/.docksal/stacks/stack-default.yml
/Users/a251267/Sites/fusion1291/.docksal/docksal.yml
ENV_FILE:
/Users/a251267/Sites/fusion1291/.docksal/docksal.env

PROJECT_ROOT: /Users/a251267/Sites/fusion1291
DOCROOT: docroot
VIRTUAL_HOST: jjfusion.docksal,*.jjfusion.docksal
VIRTUAL_HOST_ALIASES: *.jjfusion.docksal,*.jjfusion.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
networks: {}
services:
  browser:
    hostname: browser
    image: selenium/standalone-chrome-debug
    ports:
    - 4444/tcp
    - 5900:5900/tcp
    volumes:
    - project_root:/var/www:rw
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      HOST_GID: '20'
      HOST_UID: '502'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.0-php5
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_sites:/sites:rw
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached:1.4-alpine
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/a251267/Sites/fusion1291
      io.docksal.virtual-host: jjfusion.docksal,*.jjfusion.docksal,*.jjfusion.docksal,*.jjfusion.docksal
    volumes:
    - project_sites:/sites:ro
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/a251267
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/a251267/Sites/fusion1291
      o: bind
      type: none
  project_sites:
    driver: local
    driver_opts:
      device: /Users/a251267/Sites/fusion1291/../../sites
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  ███  OS & BASICS
Darwin 02HW030478.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
Mac OS X 10.12.4
fin version: 1.10.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
memcached                          1.4-alpine          e36e3b0dc88c        8 days ago          6.91MB
selenium/standalone-chrome-debug   latest              870685c556e8        7 weeks ago         858MB
docksal/vhost-proxy                1.0                 2c8a8b1e62c4        3 months ago        164MB
docksal/dns                        1.0                 20c7a535479d        4 months ago        61.6MB
docksal/ssh-agent                  1.0                 148220cc033d        4 months ago        12.2MB
docksal/web                        1.0-apache2.2       a9c03f8a5f0f        4 months ago        188MB
docksal/db                         1.0-mysql-5.5       9fb8c0aed5fc        4 months ago        255MB
docksal/cli                        1.0-php5            bde35eb43ad7        4 months ago        801MB
blinkreaction/drupal-solr          3.x-stable          bde45d55a9cc        20 months ago       474MB
selenium/standalone-firefox        2.47.1              136b59d63721        20 months ago       738MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
9a2f7359e880        docksal/web:1.0-apache2.2          "/opt/startup.sh a..."   14 hours ago        Up 14 hours         80/tcp, 443/tcp                                          fusion1291_web_1
f677ab132d70        selenium/standalone-chrome-debug   "/opt/bin/entry_po..."   14 hours ago        Up 14 hours         0.0.0.0:5900->5900/tcp, 0.0.0.0:32770->4444/tcp          fusion1291_browser_1
1043f4945aa9        docksal/db:1.0-mysql-5.5           "/entrypoint.sh my..."   2 days ago          Up 42 hours         0.0.0.0:32768->3306/tcp                                  fusion1291_db_1
adfa995f4ff1        docksal/cli:1.0-php5               "/opt/startup.sh g..."   2 days ago          Up 42 hours         22/tcp, 9000/tcp                                         fusion1291_cli_1
20a07fcfddc2        memcached:1.4-alpine               "docker-entrypoint..."   2 days ago          Up 42 hours         11211/tcp                                                fusion1291_memcached_1
737a968e2bb1        docksal/ssh-agent:1.0              "/run.sh ssh-agent"      2 days ago          Up 42 hours                                                                  docksal-ssh-agent
1d8d80d526ad        docksal/dns:1.0                    "/opt/entrypoint.s..."   2 days ago          Up 42 hours         192.168.64.100:53->53/udp                                docksal-dns
9ceb530d637a        docksal/vhost-proxy:1.0            "/usr/local/bin/st..."   2 days ago          Up 42 hours         192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=1845260k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/fdb9c83336b0c09bbed446bf9e86a8f4344d7e652c16dec9bb58b503b5dc247e type aufs (rw,relatime,si=b8918ae57d677268,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/bf22870f1fcfcecc2349fd6d13395bf0e4bba8f1d0f84bab89caac4dca8d5f91 type aufs (rw,relatime,si=b8918ae57530c268,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/8b9eb232a70e641123b3f92702d9f3ed70e83e3f55d9a68a4cf026ea817fdf91 type aufs (rw,relatime,si=b8918ae57a475268,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/737a968e2bb14015f17b1e169626134ac5cd9c9d351cca0415d26fbbf964354c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/04e88a15b9c9 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/9ceb530d637a1435951ff6254c3d3430601cc790ca2d7a4490a47e43e23fc75c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/1d8d80d526ad595b915ed4733971a47970d8578bbc36bc4e9a225a76b894fb46/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/ba070f5e84c4 type nsfs (rw)
nsfs on /var/run/docker/netns/2b7d4a91e113 type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/48600969e56b08e616c624242802f1aa9be1357bd28e27e7cd9aae815198fff7 type aufs (rw,relatime,si=b8918ae575f4c268,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/80b5b7e24d242a92340bf7333d3e069ae9a0681fb020ef163c8203537e52844d type aufs (rw,relatime,si=b8918ae5743be268,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/1a767aeac5a04124d748b7cccee872e2dfa805cc793b6ae3f8e06a9f7f1716a9 type aufs (rw,relatime,si=b8918ae57d650268,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/20a07fcfddc28d323ff1fa643e22661e99a6a91d1ba9bd72ba5ed3130fb20118/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/1043f4945aa9fd34fd19e645da5b2538af2f4efb765e3f7a3d14e8be6a3a5150/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/a251267/sites/fusion1291 on /mnt/sda1/var/lib/docker/volumes/fusion1291_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
shm on /mnt/sda1/var/lib/docker/containers/adfa995f4ff1d01b04489a3635b3a117cb214ac29b096f67e3014af2ab87ad40/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/a251267 on /mnt/sda1/var/lib/docker/volumes/fusion1291_host_home/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/a251267/sites on /mnt/sda1/var/lib/docker/volumes/fusion1291_project_sites/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/961fe5178276 type nsfs (rw)
nsfs on /var/run/docker/netns/bcdaf0a2df44 type nsfs (rw)
nsfs on /var/run/docker/netns/cc0ad25911ca type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/43fb72f67f267383c010736eb26ad7af955c819c750803803452350a221c50c2 type aufs (rw,relatime,si=b8918ae51c150268,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/f677ab132d70776b57f9089dad07a210be444823732d753abe011e074953d30e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/d6c22729b8bd type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/f487403575165a620819d05317db2d2ce912de02abb9b9f49fcc48787d3aeae3 type aufs (rw,relatime,si=b8918ae50e7ab268,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/9a2f7359e8809417d201e020260e481f3e359a311b57d13393e44e4722ad657a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/4409ee2d2781 type nsfs (rw)
  ```

</details>

**Comment by lmakarov** [comment]
Try adding the following section in your `docksal.yml` for the `browser` service:

```
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
```

So eventually it should look something like this:

```
  # Solr
  solr:
    hostname: solr
    ...
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
    ....
```

Then do `fin reset browser`.
