### ISSUE TITLE
Not seeing apache error logs

### ISSUE THREAD

**Issue by claytron5000** [docksal/docksal#260]
**Description**

I'm unable to view apache error logs, equivalent of `tail -f /var/log/apache2/error_log`.

**Steps to reproduce the issue:**

1. `fin start`
2. `fin logs -f`
3. Reload a page that throws an error

**Describe the results you received:**

The GET and POST requests are printed to the console, but no error information

**Describe the results you expected:**

Information on where errors are coming from.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: mysite
COMPOSE_FILE:
/Users/clayton.salem/.docksal/stacks/volumes-bind.yml
/Users/clayton.salem/Sites/mysite/.docksal/docksal.yml
ENV_FILE:
/Users/clayton.salem/Sites/mysite/.docksal/docksal.env

PROJECT_ROOT: /Users/clayton.salem/Sites/mysite
DOCROOT: docroot
VIRTUAL_HOST: mysite.docksal
VIRTUAL_HOST_ALIASES: *.mysite.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32771

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    environment:
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.0-php7
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 3306/tcp
    volumes:
    - /Users/clayton.salem/Sites/mysite/.docksal/db:/docker-entrypoint-initdb.d:ro
  web:
    depends_on:
      cli:
        condition: service_started
    environment:
      APACHE_DOCUMENTROOT: /var/www
      VIRTUAL_HOST: mysite.docksal
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/clayton.salem/Sites/mysite
      io.docksal.virtual-host: mysite.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/clayton.salem
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/clayton.salem/Sites/mysite      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin iR-157-Clayton.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
Mac OS X 10.12.4
fin version: 1.6.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        3 months ago        164MB
docksal/dns           1.0                 20c7a535479d        4 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        4 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        4 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        4 months ago        255MB
docksal/cli           1.0-php7            5bc490ae4d93        4 months ago        747MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                      NAMES
bcb6020576c0        docksal/web:1.0-apache2.2   "/opt/startup.sh a..."   2 days ago          Up 2 hours          80/tcp, 443/tcp                            anothersite_web_1
13d43d710b8e        docksal/cli:1.0-php7        "/opt/startup.sh g..."   2 days ago          Up 2 hours          22/tcp, 9000/tcp                           anothersite_cli_1
bc6a47aa1b7e        docksal/db:1.0-mysql-5.5    "/entrypoint.sh my..."   2 days ago          Up 2 hours          0.0.0.0:32770->3306/tcp                    anothersite_db_1
e055ae9c710f        docksal/web:1.0-apache2.2   "/opt/startup.sh a..."   12 days ago         Up 2 hours          80/tcp, 443/tcp                            mysite_web_1
2b6738693f97        docksal/cli:1.0-php7        "/opt/startup.sh g..."   12 days ago         Up 2 hours          22/tcp, 9000/tcp                           mysite_cli_1
d7fd1345c982        docksal/db:1.0-mysql-5.5    "/entrypoint.sh my..."   13 days ago         Up 2 hours          0.0.0.0:32771->3306/tcp                    mysite_db_1
dc5ec8fb63d6        docksal/web:1.0-apache2.2   "/opt/startup.sh a..."   2 weeks ago         Up 2 hours          80/tcp, 443/tcp                            schoolyarddrops7_web_1
95e78bcce333        docksal/cli:1.0-php7        "/opt/startup.sh g..."   2 weeks ago         Up 2 hours          22/tcp, 9000/tcp                           schoolyarddrops7_cli_1
cd122bdaccf6        docksal/db:1.0-mysql-5.5    "/entrypoint.sh my..."   4 weeks ago         Up 2 hours          0.0.0.0:32769->3306/tcp                    schoolyarddrops7_db_1
4818f884102d        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      4 weeks ago         Up 2 hours                                                     docksal-ssh-agent
bfc8f893e21e        docksal/dns:1.0             "/opt/entrypoint.s..."   4 weeks ago         Up 2 hours          192.168.64.100:53->53/udp                  docksal-dns
3d7f180957fe        docksal/vhost-proxy:1.0     "/usr/local/bin/st..."   4 weeks ago         Up 2 hours          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.22r115126
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917576k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/f3f6b91bc80bdceb3087b4104e134b65e28584cce4b0bd02d971a12cfa343235 type aufs (rw,relatime,si=15fe60016a0711bb,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/6e019cd1340105e3b6f9b7db26939c90309e4f3d98c36e518096d8c5242d7697 type aufs (rw,relatime,si=15fe6001642c91bb,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/b1d4d34b5d50bf760948fc19fc22ef4f6a51da6f568470fa395f4d2f603e317e type aufs (rw,relatime,si=15fe60016a8391bb,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/bfc8f893e21e3d05aee3a2d4720ca35a757871e18f7e0506fbd137185a97131e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/4818f884102dd44304029efab4f8590615436b694d7abd117cd083fb5b09704f/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/6a2c40c2471e type nsfs (rw)
nsfs on /var/run/docker/netns/b5f861594012 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/3d7f180957fe4566c8ce2919ec0eb96a2b255ce94dbf216a803eedee448f940f/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/9a50cace46bd type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/79a47a01d44e3f2a81e303f6c7757a2c4ba30644cdeb094847f69daffd87e29c type aufs (rw,relatime,si=15fe600162c6d1bb,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/2d86e30dd42e1d7bfb6b033de541e02ee48e275ef4d564e55d6b605deb7695fb type aufs (rw,relatime,si=15fe60016e5651bb,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/95e78bcce3339122f8377fc029c6e1707b8c3e0046413b20c727d073d410041a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/clayton.salem on /mnt/sda1/var/lib/docker/volumes/schoolyarddrops7_host_home/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/clayton.salem/Sites/schoolyard-drops-7 on /mnt/sda1/var/lib/docker/volumes/schoolyarddrops7_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
shm on /mnt/sda1/var/lib/docker/containers/cd122bdaccf685527f9de04058f68172a5acb0eec5c75c165a1ccb2fce41ce39/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/7e11c0a7b5cd type nsfs (rw)
nsfs on /var/run/docker/netns/7b3ac2aa803c type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/2b6b33047217b4cb331fb484f3dff8f276763d7f7c1497b37afb0c80387f1161 type aufs (rw,relatime,si=15fe600147c8d1bb,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/dc5ec8fb63d69249231590af39faa327973be885179e8d0860dbd52ac47d3f7f/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/d5379ba3c35d type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/b2c5ef875028844973d34386a5f038ba304d805f88dfaf5800b36145249dec50 type aufs (rw,relatime,si=15fe60016b0461bb,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/f3177e18d40adb6ca3bf7717e89ee35f202dbbade66f13f1eb4fbbc666101637 type aufs (rw,relatime,si=15fe600162d4d1bb,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/13d43d710b8e892074d88333180c992a927b669d2af2f16731cf2110e712b872/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/clayton.salem on /mnt/sda1/var/lib/docker/volumes/anothersite_host_home/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/clayton.salem/Sites/anothersite on /mnt/sda1/var/lib/docker/volumes/anothersite_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
shm on /mnt/sda1/var/lib/docker/containers/bc6a47aa1b7e40092b23229aaae2f21826f31ea1f691c13cfb7251580d8bd013/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/3d86cbb43326 type nsfs (rw)
nsfs on /var/run/docker/netns/73cc8ae7dbab type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/0805e65195a1764274fb8b4d1a3efc87a2fb315b6d65a6adcd4a6d619c5c7431 type aufs (rw,relatime,si=15fe600169ff91bb,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/bcb6020576c032711b70dc3492e36a73b6b4d438a938d02bcfc65821539e3b5c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/8f44428532cc type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/43e9c46cb880e9734629dbee483e5a16811843077025aebf89109075648dfded type aufs (rw,relatime,si=15fe600148a871bb,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/7186cb4e04e0e2ae56bc10a01cdb04f31ff6e30ea6ffc6af444672a0efbac97f type aufs (rw,relatime,si=15fe6001575c31bb,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/2b6738693f97eb3949db07d2ce6b7144b509773c2ce15613754fc96385b00664/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/clayton.salem on /mnt/sda1/var/lib/docker/volumes/mysite_host_home/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/clayton.salem/Sites/mysite on /mnt/sda1/var/lib/docker/volumes/mysite_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
shm on /mnt/sda1/var/lib/docker/containers/d7fd1345c982f67d5be20556764547727e6882c655f9265742fb52419c68f24c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/cf0786706ee5 type nsfs (rw)
nsfs on /var/run/docker/netns/29279adfead8 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/fd8ac553b52dbca19b5a1ee02d3296c2842fd95dfbb94d1f6500eedcf2e84bc9 type aufs (rw,relatime,si=15fe600148a811bb,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/e055ae9c710fdd4fcc81432950f4dd0c1ff8f24811b35b17f17a56fcf017e90f/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/a02561d4f8c4 type nsfs (rw)


  ```

</details>
NOTE: I've tried to obscure the names of client, so if there's inconsistencies in `anothesite` or `mysite` that's probably why
