### ISSUE TITLE
Sierra 10.12.2+ NFS bug affecting file permissions periodically.

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#265]
**UPDATED 6/20 12:14PM EST**: Affects all guests that are mounting via NFS on Sierra 10.12.2+. See https://github.com/mitchellh/vagrant/issues/8061#issuecomment-268412444. Resolution is to run `ls -aLR` in the project root directory on the host machine. See https://github.com/docksal/docksal/issues/265#issuecomment-309603327 and below for potential workarounds.

**Description**

When deleting or modifying certain files through the CLI container, I receive a permission denied message sporadically. These are files that have been installed via Composer through the container via **fin exec composer install**. This issue does not seem to exist for files that have not been installed by Composer. Note though, that if one file installed by Composer is being problematic, does not necessarily mean that all files installed via Composer are problematic (i.e. can be written/deleted without error).

And the issue is not always present. But once it appears, the only way to fix it is to delete all files in the codebase that are Composer managed and run **fin exec composer install** again. The issue goes away for a time, but then inevitably reappears.

I've tried bringing the containers down and up again. I've also tried restarting the VM. Neither helps.

I have verified that user docker and group users have the appropriate permissions to delete and write files. I have also verified that the uid/gid are mapped correctly.

**Steps to reproduce the issue:**

1. Run **fin exec composer install**.
2. Wait until you perform a delete/write operation on a file that is Composer manager for the error to produce itself.

**Describe the results you received:**

Could not write/delete the file. In the case of **fin exec composer install** you see a message like:

```
  [RuntimeException]                                                                          
  Could not delete docroot/modules/contrib/better_formats/.git/hooks/applypatch-msg.sample:
```

**Describe the results you expected:**

A clean installation process without errors saying permissions were stopping a file from being deleted.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: docksalblt
COMPOSE_FILE:
/Users/les.peabody/.docksal/stacks/volumes-bind.yml
/Users/les.peabody/.docksal/stacks/stack-acquia.yml
/Users/les.peabody/Sites/docksalblt/.docksal/docksal.yml
ENV_FILE:
/Users/les.peabody/Sites/docksalblt/.docksal/docksal.env

PROJECT_ROOT: /Users/les.peabody/Sites/docksalblt
DOCROOT: docroot
VIRTUAL_HOST: docksalblt.docksal
VIRTUAL_HOST_ALIASES: *.docksalblt.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      HOST_GID: '1106437719'
      HOST_UID: '1729411499'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: lpeabody/blt-cli
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro
  memcached:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: solr
    image: docksal/solr:1.0-solr4
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:1.0-varnish4
    labels:
      io.docksal.virtual-host: varnish.docksalblt.docksal
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/les.peabody/Sites/docksalblt
      io.docksal.virtual-host: docksalblt.docksal,*.docksalblt.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/les.peabody
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/les.peabody/Sites/docksalblt
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin BOSGEN-NMX0813.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
Mac OS X 10.12.5
fin version: 1.10.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   -        virtualbox   Stopped                                       Unknown       
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
lpeabody/blt-cli      latest              a607eef25ffc        4 days ago          982MB
memcached             latest              a3c61ffa242e        10 days ago         82.5MB
lpeabody/blt-cli      <none>              064e02735c36        12 days ago         978MB
wernight/ngrok        latest              7d0713e0e005        5 weeks ago         26.9MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        3 months ago        164MB
docksal/dns           1.0                 20c7a535479d        4 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        4 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        5 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        5 months ago        255MB
docksal/solr          1.0-solr4           fa6b236caf06        5 months ago        546MB
docksal/varnish       1.0-varnish4        35dae6b91ff9        5 months ago        99.5MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
a8e25e09225c        docksal/varnish:1.0-varnish4   "/opt/startup.sh"        3 days ago          Up 21 minutes             80/tcp                                                   docksalblt_varnish_1
7cf0c1b17841        docksal/web:1.0-apache2.2      "/opt/startup.sh a..."   3 days ago          Up 21 minutes             80/tcp, 443/tcp                                          docksalblt_web_1
99407125c5a0        lpeabody/blt-cli               "/opt/startup.sh s..."   3 days ago          Up 21 minutes (healthy)   22/tcp, 9000/tcp                                         docksalblt_cli_1
145eb61d7277        memcached                      "docker-entrypoint..."   3 days ago          Up 21 minutes             11211/tcp                                                docksalblt_memcached_1
2158323d39af        docksal/db:1.0-mysql-5.5       "/entrypoint.sh my..."   3 days ago          Up 21 minutes             0.0.0.0:32768->3306/tcp                                  docksalblt_db_1
89a2b6c2f719        docksal/solr:1.0-solr4         "/opt/solr/bin/sol..."   3 days ago          Up 21 minutes             8983/tcp                                                 docksalblt_solr_1
0d16b4febf22        docksal/ssh-agent:1.0          "/run.sh ssh-agent"      10 days ago         Up 24 minutes                                                                      docksal-ssh-agent
5f0c635e620c        docksal/dns:1.0                "/opt/entrypoint.s..."   10 days ago         Up 24 minutes             192.168.64.100:53->53/udp                                docksal-dns
ff6205366aaa        docksal/vhost-proxy:1.0        "/usr/local/bin/st..."   10 days ago         Up 24 minutes             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

███  NFS EXPORTS

# docker-machine-nfs-begin default #
/Users 192.168.99.100 -alldirs -maproot=0
# docker-machine-nfs-end default #
# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/574cf378c1e63de27a5f63cf377ca0d1d545852a90f3eb46a6f7c24c3f17aa7d type aufs (rw,relatime,si=3cfcb5dab572c9ec,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/3ecee0afc8366e740e607f4fc0936e3d7a1d99f720b24cc83a375cea237338c1 type aufs (rw,relatime,si=3cfcb5dab54219ec,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/6e27a8fa226319166788b93f9c577afbb9876dbad7eb445d7993d97156a1ae57 type aufs (rw,relatime,si=3cfcb5dab56559ec,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/0d16b4febf22c72b1fd9daa7e286d35cc900bfe73882361f103fc3e1c1ee316c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/5f0c635e620cda0b2053d39e3957d966fc1f3c9ea5d80d1fac463d78f7e5c92d/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/ff6205366aaaa2286e0ed0b0d804285dadf33667b3a21f4c5f7ed2d309ba9610/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/ab30eb6b09ba type nsfs (rw)
nsfs on /var/run/docker/netns/64fcef0c1470 type nsfs (rw)
nsfs on /var/run/docker/netns/cd11c90327e3 type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/0aa88c8bd99a1b5740dec0623ace015566447022492c8ac564fbbace8a88a602 type aufs (rw,relatime,si=3cfcb5dab607e9ec,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/d6138dc6b6b85bd4612ad8cb7702edbdfe93234eebe503f0f426c62f171b1393 type aufs (rw,relatime,si=3cfcb5dab62d89ec,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/9775e41d5c7c7cf6bc9c60dd03cef0c205b2f823147f75d52504cf0659278616 type aufs (rw,relatime,si=3cfcb5dab62429ec,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/ccc370f6152f772149d89baf2bc8e4385a41af1be50c91e85a4f058855501bc6 type aufs (rw,relatime,si=3cfcb5dab635c9ec,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/2158323d39afad726b383c55c81782105dafd31d87e06926d340e3bc80c13741/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/les.peabody/Sites/docksalblt on /mnt/sda1/var/lib/docker/volumes/docksalblt_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/7cae6b9d3f5f type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/145eb61d7277bc5dd25187db77705f201a5e94210366de16ed556a55e2351f31/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/89a2b6c2f7198e5926fd8df2d4cd232d152b869fe9308ccac6f9f529f3997f15/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/99407125c5a00022381cd149232cfd710cd8282c26968a1cb459963a0d93c475/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/les.peabody on /mnt/sda1/var/lib/docker/volumes/docksalblt_host_home/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/ad84085fa601 type nsfs (rw)
nsfs on /var/run/docker/netns/bee01b4eaf51 type nsfs (rw)
nsfs on /var/run/docker/netns/583dd786643b type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/b6c3119b73f7593aab051d85ae664983c2529daeb032057d266f223909c2cace type aufs (rw,relatime,si=3cfcb5dab6c659ec,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/7cf0c1b178410a36a4eea00e832c66247c1eefdaa781ad23d8eac46143e3071e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/b25a8ae8e9a3 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/6cf8c677a3805417c1fc21857afd8792f87be8a1f814a6469d12863d8d2b3d4d type aufs (rw,relatime,si=3cfcb5dab6c999ec,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/a8e25e09225cab33b92117d88d02680dc8f8b201a4d6250f2ee9d6ca28fe116e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/af7a38b39387 type nsfs (rw)

  ```

</details>
