### ISSUE TITLE
MySQL container dies periodically

### ISSUE THREAD

**Issue by Martins15** [docksal/docksal#266]
**Description**

From time to time (about 2-3 times a day) the mysql container stops to work. I have to restart fin to make it work again.

I often run multiple projects in different babun windows at the same time, can this cause the issue?

**Describe the results you received:**

http://take.ms/v2pFe

**Describe the results you expected:**

Expected behavior...

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
{ default } dev5 » fin config                 /cygdrive/c/ffw/hcp/pfpfproru/docroot/sites/default
---------------------
COMPOSE_PROJECT_NAME_SAFE: pfpfproru
COMPOSE_FILE:
C:/Users/cyber/.babun/cygwin/home/cyber/.docksal/stacks/volumes-bind.yml
C:/ffw/hcp/pfpfproru/.docksal/docksal.yml
ENV_FILE:
C:/ffw/hcp/pfpfproru/.docksal/docksal.env
C:/ffw/hcp/pfpfproru/.docksal/docksal-local.env

PROJECT_ROOT: /c/ffw/hcp/pfpfproru
DOCROOT: docroot
VIRTUAL_HOST: pfpfproru.docksal,*.pfpfproru.docksal
VIRTUAL_HOST_ALIASES: *.pfpfproru.docksal,*.pfpfproru.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
The APACHE_BASIC_AUTH_USER variable is not set. Defaulting to a blank string.
The APACHE_BASIC_AUTH_PASS variable is not set. Defaulting to a blank string.
networks: {}
services:
  cli:
    environment:
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.0-php5
    ports:
    - 0:22/tcp
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 32789:3306/tcp
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached
  web:
    depends_on:
      cli:
        condition: service_started
    environment:
      APACHE_BASIC_AUTH_PASS: ''
      APACHE_BASIC_AUTH_USER: ''
      APACHE_DOCUMENTROOT: /var/www/docroot
      VIRTUAL_HOST: pfpfproru.docksal,*.pfpfproru.docksal
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /c/ffw/hcp/pfpfproru
      io.docksal.virtual-host: pfpfproru.docksal,*.pfpfproru.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /c/Users/cyber/.babun/cygwin/home/cyber
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /c/ffw/hcp/pfpfproru
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
{ default } dev5 » fin sysinfo                /cygdrive/c/ffw/hcp/pfpfproru/docroot/sites/default
███  OS & BASICS
CYGWIN_NT-10.0-WOW DESKTOP-3UP385K 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
 Microsoft Windows [Version 10.0.15063]
fin version: 1.10.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce
███  DOCKER
DOCKER_HOST:    tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build ee0f34e1
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine.exe version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
memcached             latest              a3c61ffa242e        11 days ago         82.5MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        3 months ago        164MB
docksal/dns           1.0                 20c7a535479d        5 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        5 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        5 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        5 months ago        255MB
docksal/cli           1.0-php5            bde35eb43ad7        5 months ago        801MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
dc9301ab0e94        docksal/web:1.0-apache2.2   "/opt/startup.sh a..."   37 minutes ago      Up 37 minutes       80/tcp, 443/tcp                                          pfizerprouk_web_1
967bdce8a52e        docksal/cli:1.0-php5        "/opt/startup.sh g..."   37 minutes ago      Up 37 minutes       9000/tcp, 0.0.0.0:32795->22/tcp                          pfizerprouk_cli_1
b8ed5635d02c        docksal/db:1.0-mysql-5.5    "/entrypoint.sh my..."   37 minutes ago      Up 37 minutes       0.0.0.0:32769->3306/tcp                                  pfizerprouk_db_1
baf07f8cc348        memcached                   "docker-entrypoint..."   37 minutes ago      Up 37 minutes       11211/tcp                                                pfizerprouk_memcached_1
6cfbd3e62872        docksal/web:1.0-apache2.2   "/opt/startup.sh a..."   18 hours ago        Up 18 hours         80/tcp, 443/tcp                                          pfpfproru_web_1
dd8082ed451b        docksal/cli:1.0-php5        "/opt/startup.sh g..."   18 hours ago        Up 18 hours         9000/tcp, 0.0.0.0:32792->22/tcp                          pfpfproru_cli_1
73113c10162e        memcached                   "docker-entrypoint..."   18 hours ago        Up 18 hours         11211/tcp                                                pfpfproru_memcached_1
d721416ea5c8        docksal/web:1.0-apache2.2   "/opt/startup.sh a..."   7 days ago          Up 17 hours         80/tcp, 443/tcp                                          pfpfproes_web_1
6a294a969214        memcached                   "docker-entrypoint..."   7 days ago          Up 17 hours         11211/tcp                                                pfpfproes_memcached_1
91a962a61ca1        docksal/db:1.0-mysql-5.5    "/entrypoint.sh my..."   7 days ago          Up 17 hours         0.0.0.0:32779->3306/tcp                                  pfpfproes_db_1
9e2b4a288306        docksal/cli:1.0-php5        "/opt/startup.sh g..."   7 days ago          Up 17 hours         9000/tcp, 0.0.0.0:32793->22/tcp                          pfpfproes_cli_1
f382b1b7d6c8        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      7 days ago          Up 4 days                                                                    docksal-ssh-agent
19cac78f064a        docksal/dns:1.0             "/opt/entrypoint.s..."   7 days ago          Up 4 days           192.168.64.100:53->53/udp                                docksal-dns
281113274ebe        docksal/vhost-proxy:1.0     "/usr/local/bin/st..."   7 days ago          Up 4 days           192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            VirtualBox Host-Only Ethernet Adapter #12
GUID:            ba0311b2-2eb8-4c5f-8d2a-7625067ca830
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:a0eb:ef25:0948:faf5
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:18
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #12

███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/2054cf0c417cb0b20ebec309c611e1dd2178507b1519584438276fc3c7ede5e2 type aufs (rw,relatime,si=3e7229dfeb5f7c75,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/5406fcebf84516de207a49f3153a99fa0fe4818d28f04a068ba71c0334751097 type aufs (rw,relatime,si=3e7229dfe48bfc75,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/7b59eecf0d60b5f8c2bce7c922e3b6af47bfedb4e9f1af591e5ce4de945759de type aufs (rw,relatime,si=3e7229dfea44fc75,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/f382b1b7d6c8eb478f9752d6c9043429c098f5170086e6013600d2889e1bd93a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/9f499599665a type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/19cac78f064af023f4718fb4ed93320490eb392e72483c16f50cfda646123d1b/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/281113274ebe745dce65ade85ee51812e6b772df98c32a29b8e040855655173e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/a334099db1dd type nsfs (rw)
nsfs on /var/run/docker/netns/cfde87ba5339 type nsfs (rw)
//192.168.64.1/docksal-c on /c type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=cyber,domain=DESKTOP-3UP385K,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,nounix,mapposix,nobrl,mfsymlinks,noperm,rsize=61440,wsize=65536,actimeo=1)
//192.168.64.1/docksal-d on /d type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=cyber,domain=DESKTOP-3UP385K,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=61440,wsize=65536,actimeo=1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/1ffb5250d754e2c4089e25e67e51d7f4262b4ac79487f92b129e55bfd839c1aa type aufs (rw,relatime,si=3e7229dfe9faec75,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/73113c10162ea01befbb92e1c195ee601dbb1fa3abfb66502a3bd6d3b593e155/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/ac45e6948c75fa7a7ead554dc85c94cd6efc0ab924a304dada548535e95f29b4 type aufs (rw,relatime,si=3e7229dfda145c75,dio,dirperm1)
nsfs on /var/run/docker/netns/3c4f8f8d1604 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/dd8082ed451be21483772e099c4a397253c0572c9f78243fac2152362aaddd53/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
//192.168.64.1/docksal-c on /mnt/sda1/var/lib/docker/volumes/pfpfproru_host_home/_data type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=cyber,domain=DESKTOP-3UP385K,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,nounix,mapposix,nobrl,mfsymlinks,noperm,rsize=61440,wsize=65536,actimeo=1)
//192.168.64.1/docksal-c on /mnt/sda1/var/lib/docker/volumes/pfpfproru_project_root/_data type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=cyber,domain=DESKTOP-3UP385K,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,nounix,mapposix,nobrl,mfsymlinks,noperm,rsize=61440,wsize=65536,actimeo=1)
nsfs on /var/run/docker/netns/d75cd5b07fad type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/cb4f9e1150c31db54d811a1046591a1260c173ab508c0913aaa8a93965815e31 type aufs (rw,relatime,si=3e7229dfc1166c75,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/6cfbd3e62872383478d816b441bf2e12368c2de9140fdc2fe6e8a9a2945f3716/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/031e64f606d2 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/17818542725babb58eb589a8c43ed7d4ccd262046c43714c27ecc0bcd5eedbfd type aufs (rw,relatime,si=3e7229dfdc240c75,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/f416779983e1f49790e0913f04d33a8d6db614d5d498ad6215320d3396056583 type aufs (rw,relatime,si=3e7229dfda057c75,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/990da189076344d1528ca63e9f188793be7d0f13c99ab026ddb66441c80136df type aufs (rw,relatime,si=3e7229dfd55dcc75,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/91a962a61ca1db0f9b591a95afca39484c3c870fd7d7ae4b8379a68a8dab7d4e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/6a294a969214f604ce81cb2d4260970356bd00210aa2ca5a8416625bd52f2132/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/9e2b4a2883067c4a61101cd8e8823a59527e9215f7e5cf682c9b348b3156855a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
//192.168.64.1/docksal-c on /mnt/sda1/var/lib/docker/volumes/pfpfproes_host_home/_data type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=cyber,domain=DESKTOP-3UP385K,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,nounix,mapposix,nobrl,mfsymlinks,noperm,rsize=61440,wsize=65536,actimeo=1)
//192.168.64.1/docksal-c on /mnt/sda1/var/lib/docker/volumes/pfpfproes_project_root/_data type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=cyber,domain=DESKTOP-3UP385K,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,nounix,mapposix,nobrl,mfsymlinks,noperm,rsize=61440,wsize=65536,actimeo=1)
nsfs on /var/run/docker/netns/a0c227f06aa4 type nsfs (rw)
nsfs on /var/run/docker/netns/ef94536417e8 type nsfs (rw)
nsfs on /var/run/docker/netns/00a7f86b2142 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/8f9bc8340e16e07342fa5b78fccd4ab6f34a8536a678278578be9628555ed3f5 type aufs (rw,relatime,si=3e7229dfdee53c75,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/d721416ea5c8cc5815ad84a0c2ec252761d164f0ad233d4cbce84f6ed5edcf32/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/13beb66dee8d type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/2494ee704435dc9710281180bf86857d32b2caf4d5d835c918d5a7c4524a0f9f type aufs (rw,relatime,si=3e7229dfd5446c75,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/baf07f8cc3488351bbc7965d5012a86d8dc74c33499a00173537b626d65f402a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/59fd88b085a6c0d46e6d5664ea5058a311333741e23dbd788e6de95f7454c44d type aufs (rw,relatime,si=3e7229dfd174dc75,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/88c0312bd38196fa59c40c0ff1e6798bac8574f704139793ccd8599152c69bd5 type aufs (rw,relatime,si=3e7229dfcb936c75,dio,dirperm1)
nsfs on /var/run/docker/netns/e3659f622ada type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/b8ed5635d02c0d54e71b804dd1f79110a83faaf0a70df314f8dd3a03fb654b12/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/967bdce8a52e5a31cbbb9a082683262dfc6fe4b0f817524211d7ac608959dd14/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
//192.168.64.1/docksal-c on /mnt/sda1/var/lib/docker/volumes/pfizerprouk_host_home/_data type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=cyber,domain=DESKTOP-3UP385K,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,nounix,mapposix,nobrl,mfsymlinks,noperm,rsize=61440,wsize=65536,actimeo=1)
//192.168.64.1/docksal-c on /mnt/sda1/var/lib/docker/volumes/pfizerprouk_project_root/_data type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=cyber,domain=DESKTOP-3UP385K,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,nounix,mapposix,nobrl,mfsymlinks,noperm,rsize=61440,wsize=65536,actimeo=1)
nsfs on /var/run/docker/netns/dcc4c25251e9 type nsfs (rw)
nsfs on /var/run/docker/netns/eec839d8a0e6 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/e9f5a79bfa79df299adbea85e1c78d94da99fa507a93b31e9f9129235298b5ac type aufs (rw,relatime,si=3e7229dfe9b2ac75,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/dc9301ab0e94ed1d5b83efb25dd73127d202ec6146b36c1c99b42796a4e5890c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/7b190113c7f3 type nsfs (rw)

  ```

</details>
