### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by claytron5000** [docksal/docksal#268]
**Description**

I'm using docksal on virtualbox as a local development environment. Sites running locally are extremely slow, and when requests are made the VBoxHeadless CPU usage spikes above 100% for the entire request, often hovering around 120%. I've used other images, such as Windows 7, that don't exhibit high CPU usage (~30% under load).

I get that this is probably something that's specific to my machine, but I'm looking for help in debugging the issue.
**Steps to reproduce the issue:**

1. `fin vm start`
2. `fin start`
3. Browse to page.

**Describe the results you received:**

Extremely slow performance.

**Describe the results you expected:**

Reasonable response time/lower CPU usage.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: ksialgarve
COMPOSE_FILE:
/Users/clayton.salem/.docksal/stacks/volumes-bind.yml
/Users/clayton.salem/Sites/ksi-algarve/.docksal/docksal.yml
ENV_FILE:
/Users/clayton.salem/Sites/ksi-algarve/.docksal/docksal.env

PROJECT_ROOT: /Users/clayton.salem/Sites/ksi-algarve
DOCROOT: docroot
VIRTUAL_HOST: ksialgarve.docksal
VIRTUAL_HOST_ALIASES: *.ksialgarve.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    environment:
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.0-php7
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 3306/tcp
    volumes:
    - /Users/clayton.salem/Sites/ksi-algarve/.docksal/db:/docker-entrypoint-initdb.d:ro
  web:
    depends_on:
      cli:
        condition: service_started
    environment:
      APACHE_DOCUMENTROOT: /var/www
      VIRTUAL_HOST: ksialgarve.docksal
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/clayton.salem/Sites/ksi-algarve
      io.docksal.virtual-host: ksialgarve.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/clayton.salem
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/clayton.salem/Sites/ksi-algarve
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin iR-157-Clayton.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
Mac OS X 10.12.4
fin version: 1.10.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        3 months ago        164MB
docksal/dns           1.0                 20c7a535479d        5 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        5 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        5 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        5 months ago        255MB
docksal/cli           1.0-php7            5bc490ae4d93        5 months ago        747MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
ae6cbc8b0f40        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      5 days ago          Up 2 minutes                                                                 docksal-ssh-agent
21fe6b04523c        docksal/dns:1.0           "/opt/entrypoint.s..."   5 days ago          Up 2 minutes        192.168.64.100:53->53/udp                                docksal-dns
5eeca2038102        docksal/vhost-proxy:1.0   "/usr/local/bin/st..."   5 days ago          Up 2 minutes        192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/85cc69c2238d5b11ac5c30730279f8059fe6ac41e5578e3d1906c17ee63167e2 type aufs (rw,relatime,si=a72ab7c831e14409,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/e136bd1ac3a1a13c674d4fcf741ad4ffcbf64029342de5aab540b2d5d4a30fdb type aufs (rw,relatime,si=a72ab7c831db0409,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/a4c62a7d37015116ebfaa2ad24af1b170babeb4d72d1c4ee31fc3c30fbfaf7b5 type aufs (rw,relatime,si=a72ab7c8307ca409,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/ae6cbc8b0f40f56fff09ccde3f38a929523256c6a225e51725e2128392a79028/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/21fe6b04523c672216811537ee07b31f90bc82cf77925820333db6100f6d127c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/f25660f636e7 type nsfs (rw)
nsfs on /var/run/docker/netns/534a7b3860a0 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/5eeca2038102db305385accb7aaa6b0664ecef96fadc034f6ec9eccc8d385654/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/00158f66e865 type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)  ```

</details>

**Comment by achekulaev** [comment]
Most likely because it's you mapped your database volume over NFS and now your db is retained but it's performance has degraded significantly.

**Comment by achekulaev** [comment]
Also you can try increasing VM memory size with `fin vm ram 2048` if your site is RAM hungry. When Linux machine starts using swap it usually get very slow. This might also be the case.

**Comment by claytron5000** [comment]
@achekulaev Upping the memory provided some temporary relief, but degraded performance returned after getting a couple sites running. Can you speak more to database mapping, how it should be done? Also, were in the `sysinfo` do you find that information?

**Comment by achekulaev** [comment]
> but degraded performance returned after getting a couple sites running

Can you run those several sites, until performance visually degrades and then run this command:
```
fin vm ssh free
```
And paste output here? I'd like to see if your sites are just memory hungry.

---

> Can you speak more to database mapping

You have non-standard mapping in your `volumes` section of the `db` container. Did you make it?

```yaml
  db:
    ...
    volumes:
    - /Users/clayton.salem/Sites/ksi-algarve/.docksal/db:/docker-entrypoint-initdb.d:ro
```

By default this section looks like this:

```yaml
  db:
    ...
    volumes:
      # Project root volume
      - project_root:/var/www:ro,nocopy
```
