### ISSUE TITLE
Nginx support?

### ISSUE THREAD

**Issue by pratyushbarik** [docksal/docksal#270]
Is there an Nginx support? If yes, then how do I swap Apache for Nginx?

**Comment by lmakarov** [comment]
There is no nginx support at the moment. When the time comes, it is going to be address as part of #143.

**Comment by ArtuGit** [comment]
@lmakarov 
Nginx support still has not returned?

**Comment by lmakarov** [comment]
> Nginx support still has not returned?

@ArtuGit nope, has not been a priority, sorry.

If you want a quick a dirty solution with a "DO NOT USE THIS" disclaimer, then here's how one can use https://github.com/wodby/drupal-nginx (the Docker4Drupal image library) with Docksal.

**Step 1**
Assuming you are using the default Docksal stack (`DOCKSAL_STACK=default` is set in `docksal.env`), add the following overrides in `docksal(-local).yml`

```
version: "2.1"

services:
  web:
    image: wodby/drupal-nginx:latest
    volumes:
      # Suppress the permissions fixer script in wodby/drupal-nginx
      - ${PROJECT_ROOT}/.docksal/services/web/fix-permissions.sh:/usr/local/bin/fix-permissions.sh
    environment:
      - NGINX_BACKEND_HOST=cli
      - NGINX_SERVER_ROOT=/var/www/${DOCROOT}
    working_dir: /var/www/${DOCROOT}
```

If you are using a custom stack configuration (services are defined in full in `docksal.yml`), replace the `web` service definition with the following:

```
  web:
    image: wodby/drupal-nginx:latest
    volumes:
      - ${PROJECT_ROOT}:/var/www:ro
      # Suppress the permissions fixer script in wodby/drupal-nginx
      - ${PROJECT_ROOT}/.docksal/services/web/fix-permissions.sh:/usr/local/bin/fix-permissions.sh
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST},*.${VIRTUAL_HOST}
      - io.docksal.project-root=${PROJECT_ROOT}
    environment:
      - NGINX_BACKEND_HOST=cli
      - NGINX_SERVER_ROOT=/var/www/${DOCROOT}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
    working_dir: /var/www/${DOCROOT}
```

**Step 2**

Create `fix-permissions.sh` (this is a hack to suppress that script in `wodby/drupal-nginx`):

```
cd <project-root>
mkdir -p .docksal/services/web
echo 'echo "dummy script"' > .docksal/services/web/fix-permissions.sh
chmod +x .docksal/services/web/fix-permissions.sh
```

**Step 3**

`fin up`

The end result is usable, but remember the disclaimer above ;)

![image](https://user-images.githubusercontent.com/1205005/33338688-ac6a55b4-d42b-11e7-9193-c2cd1a2fa661.png)
