### ISSUE TITLE
mysql_import isn't reading from environment

### ISSUE THREAD

**Issue by loganyott** [docksal/docksal#276]
**Description**

`fin sqli` is not reading properly from `.docksal/docksal.env`

**Steps to reproduce the issue:**

1. Create a `.docksal/docksal.env` that inherits from the default stack
2. Add `MYSQL_DATABASE=drupal` to `.docksal/docksal.env`
3. Run `fin up`
4. Run `fin sqli some_db.sql.gz`

**Describe the results you received:**

Docksal tried to import into a database called `default`.

**Describe the results you expected:**

Docksal reads the environment config and imports into a database called `drupal`

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: myclient
COMPOSE_FILE:
/Users/loganyott/.docksal/stacks/volumes-bind.yml
/Users/loganyott/.docksal/stacks/stack-acquia.yml
/Users/loganyott/projects/myclient/.docksal/docksal.yml
ENV_FILE:
/Users/loganyott/projects/myclient/.docksal/docksal.env

PROJECT_ROOT: /Users/loganyott/projects/myclient
DOCROOT: docroot
VIRTUAL_HOST: myclient.docksal
VIRTUAL_HOST_ALIASES: *.myclient.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      HOST_GID: '20'
      HOST_UID: '501'
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:1.2-php7
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: drupal
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro
  memcached:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: solr
    image: docksal/solr:1.0-solr4
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:1.0-varnish4
    labels:
      io.docksal.virtual-host: varnish.myclient.docksal
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/loganyott/projects/myclient
      io.docksal.virtual-host: myclient.docksal,*.myclient.docksal
    ports:
    - 8080:80/tcp
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/loganyott
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/loganyott/projects/myclient
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin Logans-MacBook-Pro-2.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
Mac OS X 10.12.5
fin version: 1.10.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   -        virtualbox   Stopped                                       Unknown       
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
memcached             latest              c48072b41b4d        4 days ago          82.6MB
docksal/cli           1.2-php7            aef362412c9f        2 months ago        787MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        3 months ago        164MB
docksal/dns           1.0                 20c7a535479d        5 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        5 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        5 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        5 months ago        255MB
docksal/cli           1.0-php5            bde35eb43ad7        5 months ago        801MB
docksal/solr          1.0-solr4           fa6b236caf06        5 months ago        546MB
docksal/varnish       1.0-varnish4        35dae6b91ff9        5 months ago        99.5MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
463a44aa1a59        docksal/ssh-agent:1.0          "/run.sh ssh-agent"      8 minutes ago       Up 8 minutes                                                                 docksal-ssh-agent
aeca77e284da        docksal/dns:1.0                "/opt/entrypoint.s..."   8 minutes ago       Up 8 minutes        192.168.64.100:53->53/udp                                docksal-dns
6d8ca375c5d5        docksal/vhost-proxy:1.0        "/usr/local/bin/st..."   8 minutes ago       Up 8 minutes        192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
3403946bcf0c        docksal/varnish:1.0-varnish4   "/opt/startup.sh"        25 minutes ago      Up 25 minutes       80/tcp                                                   usc_varnish_1
288f51e79a12        docksal/web:1.0-apache2.2      "/opt/startup.sh a..."   25 minutes ago      Up 25 minutes       443/tcp, 0.0.0.0:8080->80/tcp                            usc_web_1
fa9fb25e9877        docksal/solr:1.0-solr4         "/opt/solr/bin/sol..."   25 minutes ago      Up 25 minutes       8983/tcp                                                 usc_solr_1
9498e7c70b7c        memcached                      "docker-entrypoint..."   25 minutes ago      Up 25 minutes       11211/tcp                                                usc_memcached_1
1410ea08fa94        docksal/cli:1.2-php7           "/opt/startup.sh s..."   25 minutes ago      Up 25 minutes       22/tcp, 9000/tcp                                         usc_cli_1
86ef6ceac8f6        docksal/db:1.0-mysql-5.5       "/entrypoint.sh my..."   25 minutes ago      Up 25 minutes       0.0.0.0:32768->3306/tcp                                  usc_db_1
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.10.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.205.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

Name:            vboxnet3
GUID:            786f6276-656e-4374-8000-0a0027000003
DHCP:            Disabled
IPAddress:       10.13.37.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:03
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet3

Name:            vboxnet4
GUID:            786f6276-656e-4474-8000-0a0027000004
DHCP:            Disabled
IPAddress:       192.168.33.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:04
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet4

Name:            vboxnet5
GUID:            786f6276-656e-4574-8000-0a0027000005
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:05
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet5

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/19f012224bf6599228099de7b351a96da94a85bace6fb8007f62de36563b127b type aufs (rw,relatime,si=c88f28959cb3d925,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/86ef6ceac8f6932f03e59d2a4554296530f31189b3505b604fe100deab32a64c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/loganyott/projects/usc on /mnt/sda1/var/lib/docker/volumes/usc_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/9326d08aa64cec704d016c543620fae7e93c9c576816a30dd507e014d5d6d461 type aufs (rw,relatime,si=c88f2895ab7d0925,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/a979f113fdf9dd90c68ddb633c70821e88774c6f3d0c5d8e4bf13877ae85d208 type aufs (rw,relatime,si=c88f2895a5498925,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/59b9d9fb09e59aa59259ddcafd5ff9ee34120a97b8978202faae16b02298ab1a type aufs (rw,relatime,si=c88f2895a68a8925,dio,dirperm1)
nsfs on /var/run/docker/netns/02141fb84ed5 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/fa9fb25e9877350fd100508debcf595d5859d7f168b3b52189e1542008b41678/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/f456ad18753c type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/1410ea08fa94ef262e5d7dd8cd1a6a6ff077939d1b88d36e8516f24c54057760/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/9498e7c70b7c192ebe16e9a9ddfbf324971fbef7a704c027324a4c1d8842281e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/loganyott on /mnt/sda1/var/lib/docker/volumes/usc_host_home/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/25506f016061 type nsfs (rw)
nsfs on /var/run/docker/netns/9f08026e76c7 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/d1366163f7fd3944b95bb37c867fd9b1c297855671eaf560dac19070cd7c665d type aufs (rw,relatime,si=c88f2895a66cd925,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/288f51e79a124516719ef2c69b53951a81a4357093566145ab8c0016156ec416/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/66f738317e6b type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/0cbfad25f7ab208d4832f35627db6a76f09d9651ed283aa7e25fc917b31e20d2 type aufs (rw,relatime,si=c88f2895bb239925,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/3403946bcf0c64303178ab769b60db5ba0d7d9dc714e900cf6b817ab1752a57d/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/4ce219bb9d12 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/f8a685afbd18e6a502fdcb6389af4d059e51fd3eb1b290a4c0e42e9e1e344175 type aufs (rw,relatime,si=c88f2895a7428925,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/6d8ca375c5d5c537e99c24ad39163376d6354bb0ed775f29aa13512e4a894760/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/1a6076ae6f65 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/edf0be0c3f0f16149ed2eba38c4149188f19f4e9e55eae287684856a008f2012 type aufs (rw,relatime,si=c88f2895a7f94925,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/aeca77e284da6a582e1956bc38ffde7aaa63562713d6711e2a82879e67e82260/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/d396136d3ffe type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/91f25ab97c4ec79f6dc31b9ee65eac1de3eeaedbac228cf386ca2f10f3169182 type aufs (rw,relatime,si=c88f2895a6a6b925,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/463a44aa1a59226667b693e0dabed66551b925c707bce74de1072e4c14b73666/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/55413b6f41c7 type nsfs (rw)
  ```

</details>
