### ISSUE TITLE
Docksal project runs out of space

### ISSUE THREAD

**Issue by drubage** [docksal/docksal#282]
Can you tell me what sort of space is allocated to each container? We have some projects with lots of files and large databases and we get errors while importing the databases like:

ERROR 1114 (HY000) at line 1042: The table 'drupal_cache_field' is full
Import failed

**Steps to reproduce the issue:**

1. Create a default project.
2. Download a lot of Drupal site files.
3. Import a large database via fin sqli ./database.sql

**Describe the results you received:**

ERROR 1114 (HY000) at line 1042: The table 'drupal_cache_field' is full
Import failed

**Describe the results you expected:**

A functioning site and database.

**Output of `fin config`:**

<details>
  <summary></summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: kulased
COMPOSE_FILE:
/Users/drew.michael/.docksal/stacks/volumes-bind.yml
/Users/drew.michael/projects/kula-sed/.docksal/docksal.yml
ENV_FILE:
/Users/drew.michael/projects/kula-sed/.docksal/docksal.env

PROJECT_ROOT: /Users/drew.michael/projects/kula-sed
DOCROOT: docroot
VIRTUAL_HOST: kulased.docksal
VIRTUAL_HOST_ALIASES: *.kulased.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32771

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.2-php5
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.6
    ports:
    - 3306/tcp
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.kulased.docksal
    user: root
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached
  solr:
    hostname: solr
    image: docksal/solr:1.0-solr4
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/drew.michael/projects/kula-sed
      io.docksal.virtual-host: kulased.docksal,*.kulased.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/drew.michael
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/drew.michael/projects/kula-sed
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  ---------------------
COMPOSE_PROJECT_NAME_SAFE: kulased
COMPOSE_FILE:
/Users/drew.michael/.docksal/stacks/volumes-bind.yml
/Users/drew.michael/projects/kula-sed/.docksal/docksal.yml
ENV_FILE:
/Users/drew.michael/projects/kula-sed/.docksal/docksal.env

PROJECT_ROOT: /Users/drew.michael/projects/kula-sed
DOCROOT: docroot
VIRTUAL_HOST: kulased.docksal
VIRTUAL_HOST_ALIASES: *.kulased.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32771

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.2-php5
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.6
    ports:
    - 3306/tcp
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.kulased.docksal
    user: root
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached
  solr:
    hostname: solr
    image: docksal/solr:1.0-solr4
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/drew.michael/projects/kula-sed
      io.docksal.virtual-host: kulased.docksal,*.kulased.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/drew.michael
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/drew.michael/projects/kula-sed
      o: bind
      type: none

---------------------
Spare-Mac-Book-Pro:kula-sed drew.michael$ fin sysinfo
███  OS & BASICS
Darwin Spare-Mac-Book-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64
Mac OS X 10.11.6
fin version: 1.10.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/cli           edge-php7           d35c1b40784d        9 days ago          749MB
memcached             latest              a3c61ffa242e        4 weeks ago         82.5MB
mailhog/mailhog       latest              669347153085        2 months ago        19.1MB
docksal/cli           1.2-php5            11f47dc7d024        3 months ago        845MB
docksal/cli           1.2-php7            aef362412c9f        3 months ago        787MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        4 months ago        164MB
docksal/dns           1.0                 20c7a535479d        5 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        5 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        5 months ago        188MB
docksal/web           1.0-apache2.4       1e2aa01c55d6        5 months ago        259MB
docksal/db            1.0-mysql-5.7       35f1494f03b6        5 months ago        400MB
docksal/db            1.0-mysql-5.6       7c932a2f6a71        5 months ago        328MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        5 months ago        255MB
docksal/solr          1.0-solr4           fa6b236caf06        6 months ago        546MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
9b7323d8eb4d        docksal/web:1.0-apache2.2   "/opt/startup.sh a..."   16 minutes ago      Up 16 minutes       80/tcp, 443/tcp                                          kulased_web_1
28cb9262a235        docksal/cli:1.2-php5        "/opt/startup.sh s..."   16 minutes ago      Up 16 minutes       22/tcp, 9000/tcp                                         kulased_cli_1
0a19929a2601        docksal/solr:1.0-solr4      "/opt/solr/bin/sol..."   16 minutes ago      Up 16 minutes       8983/tcp                                                 kulased_solr_1
4d1a1961b3df        mailhog/mailhog             "MailHog"                16 minutes ago      Up 16 minutes       80/tcp, 1025/tcp, 8025/tcp                               kulased_mail_1
dc8c6246704f        memcached                   "docker-entrypoint..."   16 minutes ago      Up 16 minutes       11211/tcp                                                kulased_memcached_1
80716e0bc122        docksal/db:1.0-mysql-5.6    "/entrypoint.sh my..."   16 minutes ago      Up 16 minutes       0.0.0.0:32771->3306/tcp                                  kulased_db_1
dc8dfbd5aae5        docksal/web:1.0-apache2.2   "/opt/startup.sh a..."   3 days ago          Up About an hour    80/tcp, 443/tcp                                          gzcentralgitlab_web_1
75a6b445a4ea        mailhog/mailhog             "MailHog"                3 days ago          Up About an hour    80/tcp, 1025/tcp, 8025/tcp                               gzcentralgitlab_mail_1
e8f04fd53a5f        docksal/db:1.0-mysql-5.6    "/entrypoint.sh my..."   3 days ago          Up About an hour    0.0.0.0:32768->3306/tcp                                  gzcentralgitlab_db_1
4d91ac53f5b0        docksal/cli:1.2-php5        "/opt/startup.sh s..."   3 days ago          Up About an hour    22/tcp, 9000/tcp                                         gzcentralgitlab_cli_1
4d06ea586205        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      3 days ago          Up About an hour                                                             docksal-ssh-agent
e3290b6571fa        docksal/dns:1.0             "/opt/entrypoint.s..."   3 days ago          Up About an hour    192.168.64.100:53->53/udp                                docksal-dns
697b183f20a5        docksal/vhost-proxy:1.0     "/usr/local/bin/st..."   3 days ago          Up About an hour    192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/20f58a340adc27c5e309a6910fa2c2532bcb214b6d131e34adceacadedd163e8 type aufs (rw,relatime,si=3669c94a09cf49d2,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/fafba0a7f381ea82fe57d012ebe5713f04c5a49540fed8ba0861105e42764556 type aufs (rw,relatime,si=3669c94a090159d2,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/b0a1253ea7bfbcf0f64213eaf6a133d65375b564c0a72a320307376bd39cb5fa type aufs (rw,relatime,si=3669c94a095e09d2,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/4d06ea5862050c413897741d1731bf76a4980829b9ff2d69f2080e7e04f2c204/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/e3290b6571faed78ecc85e66f1e6ce2cfa2c2503e9fe862330a4a7af74409d5c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/697b183f20a5f70a9c571478d34131205bace1503eeff914e85541ce094d6e79/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/ff0307327cc9 type nsfs (rw)
nsfs on /var/run/docker/netns/d3b8e4e8967f type nsfs (rw)
nsfs on /var/run/docker/netns/ee3e561c22ee type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/7b58a0baebe55f35c1605df2c70d3ca3d6306c2e6ade2f95eb41f1babe6a8ef8 type aufs (rw,relatime,si=3669c94a091469d2,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/75a6b445a4ea9e5e30c92f79c656180494af6bd3bef1e06835705b86fda5c463/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/bfad2c8a54d8 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/55ad81ef1a132afd380da08179dc57d5ead085f989f995fc833469f3b15d2f17 type aufs (rw,relatime,si=3669c94a09cb89d2,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/e8f04fd53a5fe40357a1b5caed382016de5c4b5d3294277ec4eff43d714a8e36/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/011964e40691 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/fc48c854b43d8fc59f9d1c0def4ff96c23150f5b0dcee6a4d22a00123989b015 type aufs (rw,relatime,si=3669c94a0acad9d2,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/4d91ac53f5b0a96cdaae2bc1b0341f6416a341157c087270167f6c809d533603/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/drew.michael on /mnt/sda1/var/lib/docker/volumes/gzcentralgitlab_host_home/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/drew.michael/projects/gzcentral-gitlab on /mnt/sda1/var/lib/docker/volumes/gzcentralgitlab_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/edffba351043 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/be7f8d3da4b7c46afb47cc553c3f6a8ea6de1f9f8adf0605ce291c5994716d28 type aufs (rw,relatime,si=3669c94a0addd9d2,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/dc8dfbd5aae5ef53479678642606a617d74156ebd996d767fba80d98da16ca3d/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/9e98812baad8 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/102f12b0d267ca8cc91538d9c3c413f34a2ba795d169e00775bdd8dd49a634ff type aufs (rw,relatime,si=3669c94a294249d2,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/d7b90ebc29b30cf1b4afc49b0f49e6a2044c48a8c5b1f50b9cc2fc9503265e50 type aufs (rw,relatime,si=3669c94a106309d2,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/e7dff86081fabdd74adb4132df6863270d768f2e982a95b62dcfd05eb2cf3795 type aufs (rw,relatime,si=3669c94a2941a9d2,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/dc8c6246704f3661d6097a6cbbb3b0505a592a73a901176f0b9404cda9cbae36/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/cbff47215709 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/80716e0bc1227b6b9a7626ee1918e52101af2c70abbac02bb976aaba701b9846/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/4d1a1961b3dfe51a464313137ae77117f4ca580ca7c59e241c9b2d635e902329/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/e493c39db8afc2882c505c6c495565c6d578374a69e7013a5ae3328281e188e1 type aufs (rw,relatime,si=3669c94a0bc999d2,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/c8d41191cc045d4684e9e6c7048a01000394765cb2bb99da5774ccdf4a7cca5a type aufs (rw,relatime,si=3669c94a0985e9d2,dio,dirperm1)
nsfs on /var/run/docker/netns/d28e367ce3e7 type nsfs (rw)
nsfs on /var/run/docker/netns/76d810b03dc6 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/28cb9262a2351e032040ade22f767522d72e0731e7f7352ecb5a825f3fadb243/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/drew.michael on /mnt/sda1/var/lib/docker/volumes/kulased_host_home/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/drew.michael/projects/kula-sed on /mnt/sda1/var/lib/docker/volumes/kulased_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
shm on /mnt/sda1/var/lib/docker/containers/0a19929a2601df64db876160f93b183019c52ea9b692cb515adddbf8a784b533/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/2eb24867648a type nsfs (rw)
nsfs on /var/run/docker/netns/c601697d694c type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/3f8cd9c2af4218796f9d8cbe8c903ca74b8334467de825fc8f510158c628df05 type aufs (rw,relatime,si=3669c94a09e9a9d2,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/9b7323d8eb4db8243d05df38efd648725da2bcf60bf32d66f6f534e5d3f91c42/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/c8c37db90d14 type nsfs (rw)
  ```

</details>
