### ISSUE TITLE
I am not sure that settings  in '.docksal/etc/mysql/my.cnf' work

### ISSUE THREAD

**Issue by ArtuGit** [docksal/docksal#283]
Just for case my DB config:
```
  # DB
  db:
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
      - "${MYSQL_PORT_MAPPING:-3306}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-default}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
    volumes:
      - ${PROJECT_ROOT}/db:/docker-entrypoint-initdb.d:ro   
```
In order to solve 'Multi-byte UTF-8 support in Drupal 7' issue i tried to implement such settings in `.docksal/etc/mysql/my.cnf`:
```
# Multi-byte UTF-8 support in Drupal 7
innodb_large_prefix=true
innodb_file_format=barracuda
innodb_file_per_table=true
```

But it seems they do not work.
Also, I tried #245 without result.

How to check: Do settings in `.docksal/etc/mysql/my.cnf` works at all or not?

P.S. I did `fin restart ` after changing this file, of course.
