### ISSUE TITLE
BrowserSync support

### ISSUE THREAD

**Issue by igorlakic** [docksal/docksal#285]
Hi!

I've been trying to configure BrowserSync on Docksal env but without success. Local and external BrowserSync URLs for the site are not working but URLs for BrowserSync UI are working (that's weird isn't it?!?) and I'm able to see BS dashboard.

Do I have to add something in the docksal.yml file so BrowserSync can proxy site correctly?

Values from terminal for BrowserSync:
```
 -----------------------------------
       Local: http://localhost:3010
    External: http://172.20.0.4:3010
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://172.20.0.4:3001
 -----------------------------------
[BS] Watching files...
[BS] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)
```

**Comment by achekulaev** [comment]
Never worked with BrowserSync but I guess you need to [expose port](http://docs.docksal.io/en/master/advanced/networking/#exposing-container-ports) 3001 of the `cli` container (as I suppose you installed it there) and then access it as `http://192.168.64.100:3001`.

**Comment by ilakic** [comment]
Browsersync is a part of a gulp task in my theme. Can I get a little bit of help here?
I tried to put this in docksal-local.yml:
```
version: "2"
  services:
    cli:
      ports:
        - "3000:3000"
```
and this:
```
version: "2"
  services:
    cli:
      ports:
        - "3000"
```
and I get this:
```
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "/[destination path]/.docksal/docksal-local.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/[destination path]/.docksal/docksal-local.yml", line 2, column 3
```

**Comment by ilakic** [comment]
There was a problem because on this example site in which I tried to make things to work I changed domain name to my custom one (so for example, I didn't use **example.docksal** but **dev.example.com** which I added correctly in my system hosts file but still -> **big mistake**; difference is that when you request example.docksal in your browser, Docksal's DNS resolves it to Docksal's IP and your request hits the docksal-vhost-proxy container). And because of that, Browsersync couldn't function properly.
Lesson learned, problem solved! :)

**Comment by achekulaev** [comment]
@ilakic so you ended up using `dev.example.com` to avoid hitting vhost-proxy?

**Comment by achekulaev** [comment]
@ilakic if you described steps you took to install browsersync I could create an automation for that everyone could benefit from.

**Comment by ilakic** [comment]
Sure, I'll help whenever I can but [Browsersync](https://www.browsersync.io/) isn't isolated piece of software that you install like php modules, it is a Gulp task (it cames as a node package). 

I'll try to explain it better this time. 
So, if you insert **domain.docksal** (for example: _example.docksal_) in the vhosts, everything works but if you change a domain name to something like dev.example.com (without docksal suffix), well that's the catch because then Docksal cannot resolve DNS so BrowserSync cannot work as it should. 

So it's important to know that when you configure VHOSTS that you always put in *.docksal suffix and everything should work just fine.

Browsersync is just a Gulp task and you need to install everything from package.json file and then install Gulp globally, configure everything in the gulpfile.js and it should work just fine (if configured correctly and that's not hard at all).

**Comment by esteinborn** [comment]
FYI to detail my setup to get this to work, I had to use the following gulp configuration to serve up my .docksal site:

```
var gulp = require('gulp');

var browserSync = require('browser-sync').create();

gulp.task('browser-sync', function() {
    browserSync.init({
        proxy: "https://mycoolsite.docksal"
    });
});
```

Kudos for this setup!

**Comment by lmakarov** [comment]
Cross posting the discussions that happened outside of the issue queue back here.

If you are on Linux/Docker for Mac, then running BrowserSync inside project container can be done like this:

```yaml
  ...
  browser-sync:
    image: ustwo/browser-sync
    command: start --proxy "${VIRTUAL_HOST}" --files "*.css" --no-open
    ports:
      - "3000:3000"
      - "3001:3001"
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
  ...
```

By default, `docksal-vhost-proxy` binds to `192.168.64.100:80, 192.168.64.100:443`.  
This way we avoid conflicts with other web servers you may have running. This, however, also prevents anyone else on the same LAN from accessing the environment.

It is possible to tell `docksal-vhost-proxy` to bind to 0.0.0.0 instead and it will listen on all interfaces:

```bash
$ DOCKSAL_VHOST_PROXY_IP=0.0.0.0 fin reset proxy
```

That variable can be added in the global `~/.docksal/docksal.env` to make it persistent.  
If you have anything else listening on ports 80 and 443 (e.g. local Apache), then `fin reset proxy` will fail. Shut down the other server and retry.

From there use your hosts LAN IP to access BS from the host and other devices on the same networks: `http://host_ip:3000`

**Comment by lmakarov** [comment]
Another variation of the setup can utilize `docksal-vhost-proxy` routing for BrowserSync itself.

```yaml
  ...
  browser-sync:
    image: ustwo/browser-sync
    command: start --port 80 --proxy "${VIRTUAL_HOST}" --files "*.css" --no-open
    ports:
      - "3000:80"
      - "3001:3001"
    labels:
      - io.docksal.virtual-host=bs.${VIRTUAL_HOST}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
  ...
```

`docksal-vhost-proxy` at the moment only supports destination ports 80 and 443. So we have to tell BS to listen on port `80` instead of `3000`. Then adding the `io.docksal.virtual-host=bs.${VIRTUAL_HOST}` label tells `docksal-vhost-proxy` to proxy `bs.${VIRTUAL_HOST}` accordingly. You can then access to site as before at `example.docksal` and via BS at `bs.example.docksal`.

The only problem here is that other devices on the same LAN won't know how to resolve `*.docksal` domains. You will have mess with the hosts file to let them know the IP of your host. Otherwise just use `http://host_ip:3000` as in my previous example.

**Comment by ilakic** [comment]
Thanks Leonid!
I'll definitely try this out tomorrow morning and will let you know if everything went well on my end (I don't doubt in positive outcome).

Thank you once again on your time!

**Comment by ilakic** [comment]
...I couldn't wait morning to test it... :-)
It works - I can connect with various devices and see the page. I will need to test if it refreshes when css changes but I cannot see a reason why that would not work.
Awesome! :-) 

1.) I added `DOCKSAL_VHOST_PROXY_IP=0.0.0.0` in the ./docksal/docksal.env
2.) `fin reset proxy`
3.) In the docksal.yml I added this (it has to be indented properly - 2 from start of the line, in line with cli, db and web services):
```
  browser-sync:
    image: ustwo/browser-sync
    command: start --proxy "${VIRTUAL_HOST}" --files "*.css" --no-open
    ports:
      - "3000:3000"
      - "3001:3001"
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
```
4.) `fin restart`

**Comment by lmakarov** [comment]
For VirtualBox users (Mac and Windows) - there will be an additional step on top of the steps outlined about for Linux.

The Docksal VM (VirtualBox) is accessible by the host only via the host-only VirtualBox network adapter. Other devices on the same LAN won't be able to access it. There are several ways around it.

**Option 1**

Use port mapping on the NAT interface of the VM - http://take.ms/zGING. This way you get port 3000 exposed on you host and can use that for other devices on your network (`host_ip:3000`). This will result in an identical to Linux and Docker for Mac experience. I'd recommend sticking with this option.

**Option 2**

Add a bridge network adapter - http://take.ms/xbFXQ. This way the Docksal VM will get a secondary IP address from your LAN. You can check, which IP was assigned by analyzing the output from `fin vm ssh ifconfig`.

Anyone on Mac or Windows please test and report back with the results.

**Comment by ilakic** [comment]
...after thoroughly testing this BrowserSync Docker image this weekend I'm still unable to make BrowserSync to work properly. Reload functionality after CSS change doesn't work. But it would be nice if more people could test this on their machines and write their feedback here...

For now, only viable solution (at least for me) to make BrowserSync to work properly is by running Gulp/Node from the local machine (outside Docksal environment).

**Comment by regenrek** [comment]
Hi

i also try to run browsersync with docksal. My setup is a bit different. 


**What I've tried**

1.) I added `DOCKSAL_VHOST_PROXY_IP=0.0.0.0` in the ./docksal/docksal.env
2.) fin reset proxy
3.) Seems Ok I can access the Site from local network also (See https://github.com/docksal/docksal/issues/310#issuecomment-321310463)
4.) Added a local `docksal.yml` (`fin config generate`) where I added `ports` to `web` service

```
    ports:
      - "3000:3000"
      - "3001:3001"
```

5.) fin init (installs wordpress, db ... )
6.) fin yarn start

```
[BS] [HTML Injector] Running...
[BS] Proxying: http://myproject.docksal
[BS] Access URLs:
 -----------------------------------
       Local: http://localhost:3000
    External: http://172.20.0.3:3000
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://172.20.0.3:3001
 -----------------------------------
[BS] Watching files...
[BS] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)
```

**commands/yarn (example: fin yarn start)**
```
#!/usr/bin/env bash
cd $PROJECT_ROOT_SITE/docroot/web/app/themes/mytheme
fin exec "yarn $1"
```

Relevant Parts of Code:

Path: docroot/web/app/themes/mytheme/package.json
```
{
  ...
  "scripts": {
    "start": "webpack --hide-modules --watch --config assets/build/webpack.config.js"
  }
  ...
}
```

https://github.com/roots/sage/blob/9.0.0-alpha.4/package.json
https://github.com/roots/sage/blob/9.0.0-alpha.4/assets/build/webpack.config.watch.js

**Conclusion**

```curl -sSf http://myproject.docksal:3000
curl: (7) Failed to connect to myproject.docksal port 3000:```

**Comment by achekulaev** [comment]
If I understand [this](https://github.com/ustwo/docker-browser-sync/blob/master/docker-compose.yml) and [this](https://hub.docker.com/r/ustwo/browser-sync/#how-to-use-this-image) right you need:

```
  browser-sync:
      image: ustwo/browser-sync
      command: start --hide-modules --watch --config /source/${DOCROOT:-docroot}/assets/build/webpack.config.js --no-open
      volumes:
        - project_root:/source:rw,nocopy
      ports:
        - "3000:3000"
        - "3001:3001"
      dns:
        - ${DOCKSAL_DNS1}
        - ${DOCKSAL_DNS2}
```

**Comment by regenrek** [comment]
@achekulaev Oh yes thank you. But after I run the thing I'll get the output like in my comment above - under "fin logs | grep 'browser-sync'".

Anyway why not exposing ports 3000 & 3001 at web service are there any problems here? 

```
  web:
    hostname: web
    image: docksal/web:2.0-apache2.4
    volumes:
      # Project root volume
      - project_root:/var/www:ro,nocopy
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST},*.${VIRTUAL_HOST}
      - io.docksal.project-root=${PROJECT_ROOT}
    environment:
      - APACHE_DOCUMENTROOT=/var/www/${DOCROOT:-docroot}
      - APACHE_BASIC_AUTH_USER
      - APACHE_BASIC_AUTH_PASS
    depends_on:
      - cli
      - webpack
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
    ports:
      - "3000:3000"
      - "3001:3001"  
```

Alternative possibility:  Also tried with `https://github.com/jmfirth/docker-webpack` to use `webpack`commando instead of browsersync as starting script. Fails also. Really difficult to get this set up.

Regards

**Comment by achekulaev** [comment]
> after I run the thing I'll get the output like in my comment above 

In your comment above you were not mapping to `/source`, you were mapping to `/var/www/`.

> Anyway why not exposing ports 3000 & 3001 at web service are there any problems here?

I don't see a reason why you would want to expose ports 3000 & 3001 of container that runs Apache.

**Comment by regenrek** [comment]
I'm almost there ... 

First I wrote my own Webpack Dockerfile

**Dockerfile**
```
FROM node:6
MAINTAINER Kevin Regenrek <hello@regenrek.at>

RUN npm install -g webpack yarn

WORKDIR /var/www/site/web/app/themes/mytheme/

#ENTRYPOINT ["webpack"]
```

**docksal.yml**
```
  webpack:
    image: mj-docker-webpack:latest
    command: webpack --hide-modules --watch --config ./assets/build/webpack.config.js
    volumes:
      - project_root:/var/www:rw,nocopy
    ports:
      - "3000:3000"
      - "3001:3001"
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
```

**Test**
```
http://mytheme.docksal [works as usual]
http://mytheme.docksal:3001 [works browsersync ui]
http://mytheme.docksal:3000 [runs endless... not working]
```

***fin status***
```
       Name                     Command               State                       Ports
------------------------------------------------------------------------------------------------------------
wpstack4_cli_1       /opt/startup.sh supervisord      Up      22/tcp, 9000/tcp
wpstack4_db_1        /entrypoint.sh mysqld            Up      0.0.0.0:32876->3306/tcp
wpstack4_web_1       httpd-foreground                 Up      443/tcp, 80/tcp
wpstack4_webpack_1   webpack --hide-modules --w ...   Up      0.0.0.0:3000->3000/tcp, 0.0.0.0:3001->3001/tcp
```

***netstat -tulpn | grep:30**
```
tcp6       0      0 :::3000                 :::*                    LISTEN      -
tcp6       0      0 :::3001                 :::*                    LISTEN      -
```

**fin logs**
```
webpack_1  | [BS] [HTML Injector] Running...
webpack_1  | [BS] Proxying: http://mytheme.docksal
webpack_1  | [BS] Access URLs:
webpack_1  |  -----------------------------------
webpack_1  |        Local: http://localhost:3000
webpack_1  |     External: http://172.20.0.5:3000
webpack_1  |  -----------------------------------
webpack_1  |           UI: http://localhost:3001
webpack_1  |  UI External: http://172.20.0.5:3001
webpack_1  |  -----------------------------------
webpack_1  | [BS] Watching files...
webpack_1  | [BS] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)
```

Seems all fine to me. Just  opening  with :3000 Port in Browser does an endless loop without any message.

Regards

**Comment by lmakarov** [comment]
Out of curiosity, if you change port mapping like this (map `3000` => `3001`), do you get the BrowserSync UI on both ports (`3000` and `3001`)?

**docksal.yml**

```
  webpack:
    image: mj-docker-webpack:latest
    command: webpack --hide-modules --watch --config ./assets/build/webpack.config.js
    volumes:
      - project_root:/var/www:rw,nocopy
    ports:
      - "3000:3001"
      - "3001:3001"
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
```

If so, there is no issue with exposing ports, but rather with BrowserSync connecting to `http://mytheme.docksal`.

Try entering the webpack container and pinging `mytheme.docksal` from there.

```
$ fin bash webpack (or $ fin docker exec -it mytheme_webpack_1 sh)
ping mytheme.docksal
```

Maybe, install `lynx` there (a text browser) and  and try `lynx http://mytheme.docksal`.

Another thing to try is to tell BrowserSync to proxy `http://web` instead of `http://mytheme.docksal` (go directly to the `web` container, skipping `vhost-proxy` routing).

If all of the above works, then BrowserSync settings are to be blamed.
