### ISSUE TITLE
Drush cache folder permissions problem

### ISSUE THREAD

**Issue by kovtunos** [docksal/docksal#296]
I get this error when using drush:

> Directory /home/docker/.drush/cache/default exists, but is not writable. Please check directory permissions.

It is can be cured for this session with:
`chown docker:users -R /home/docker/.drush/cache`
or
`rm -rf /home/docker/.drush/cache`
But this error returns after the next start.

I use Ubuntu LTS 16.04 and last version of Docksal.
The same error on 3 machines that run on Ubuntu 16.04.

**Steps to reproduce the issue:**

1. fin up (ubuntu 16.04)
2. fin drush dl, fin drush up or other comand that requires drush cache

**Describe the results you received:**

> Directory /home/docker/.drush/cache/default exists, but is not writable. Please check directory permissions.

Drush commands work but without involving the cache.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: drupal
COMPOSE_FILE:
/home/user/.docksal/stacks/volumes-bind.yml
/home/user/.docksal/stacks/stack-default.yml
/home/user/www/drupal/.docksal/docksal.yml
ENV_FILE:
/home/user/www/drupal/.docksal/docksal.env

PROJECT_ROOT: /home/user/www/drupal
DOCROOT: web
VIRTUAL_HOST: starter.docksal
VIRTUAL_HOST_ALIASES: *.starter.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      HOST_GID: '1000'
      HOST_UID: '1000'
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:1.2-php7
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_DOCUMENTROOT: /var/www/web
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /home/user/www/drupal
      io.docksal.virtual-host: starter.docksal,*.starter.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /home/user
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /home/user/www/drupal
      o: bind
      type: none
---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
    OS & BASICS
Linux desktop 4.4.0-88-generic #111-Ubuntu SMP Thu Jul 20 09:32:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 16.04
fin version: 1.10.0
Mode:  Native / Docker for Mac/Windows
    DOCKER
DOCKER_HOST:	

Docker: Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
    DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
    DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/cli           1.2-php5            11f47dc7d024        3 months ago        845MB
docksal/cli           1.2-php7            aef362412c9f        3 months ago        787MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        4 months ago        164MB
docksal/dns           1.0                 20c7a535479d        6 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        6 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        6 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        6 months ago        255MB
    DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
8008921df39f        docksal/web:1.0-apache2.2   "/opt/startup.sh a..."   5 weeks ago         Up 10 minutes       80/tcp, 443/tcp                                          drupal_web_1
7b61d496ad42        docksal/db:1.0-mysql-5.5    "/entrypoint.sh my..."   5 weeks ago         Up 10 minutes       0.0.0.0:32768->3306/tcp                                  drupal_db_1
41c7c998a817        docksal/cli:1.2-php7        "/opt/startup.sh s..."   5 weeks ago         Up 10 minutes       22/tcp, 9000/tcp                                         drupal_cli_1
21796edc3310        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      6 weeks ago         Up About an hour                                                             docksal-ssh-agent
919c2f6bf1d9        docksal/dns:1.0             "/opt/entrypoint.s..."   6 weeks ago         Up About an hour    192.168.64.100:53->53/udp                                docksal-dns
6dfa26e464bd        docksal/vhost-proxy:1.0     "/usr/local/bin/st..."   6 weeks ago         Up About an hour    192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
  ```

</details>
