### ISSUE TITLE
nfs mount problem on new install

### ISSUE THREAD

**Issue by ochenk** [docksal/docksal#299]
Hey there! I'm trying to install docksal for the first time but it's hanging when trying to mount the nfs share. The error that I'm getting is:

```
Configuring NFS shares...
NFS shares are already configured
Mounting NFS shares...
Starting nfs client utilities.
Mounting local /Users to /Users
mount: RPC: Remote system error - Connection timed out
mount: mounting 192.168.64.1:/Users on /Users failed: Bad file descriptor
exit status 110
Retrying mounting local /Users to /Users
mount: RPC: Remote system error - Connection timed out
mount: mounting 192.168.64.1:/Users on /Users failed: Bad file descriptor
exit status 110
 ERROR:  NFS share mount failed.
         Try fin vm restart.
```

I did see this previous issue https://github.com/docksal/docksal/issues/35 but none of the answers in that thread helped my issue. I have my firewall disabled while working on this, and my hosts file has the appropriate entry for localhost.

I posted my issue over on gitter. Based on help from @lmakarov I added ```nfs.server.mount.require_resv_port = 0``` to ```/etc/nfs.conf``` and ran ```fin vm restart``` but got the same error.

Here's the ouput from ```showmount -e```:
```
Exports list on localhost:
/Users                              127.0.0.1 192.168.64.100
```

and ```fin vm ssh ping -c 1 192.168.64.1``` outputs:
```
--- 192.168.64.1 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss
exit status 1
```

Here the Output of `fin config`:

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: doctest2
COMPOSE_FILE:
/Users/ochenk/.docksal/stacks/volumes-bind.yml
/Users/ochenk/.docksal/stacks/stack-default.yml

PROJECT_ROOT: /Users/ochenk/Sites/doctest2
DOCROOT: docroot
VIRTUAL_HOST: doctest2.docksal
VIRTUAL_HOST_ALIASES: *.doctest2.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      HOST_GID: '20'
      HOST_UID: '501'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.2-php7
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/ochenk/Sites/doctest2
      io.docksal.virtual-host: doctest2.docksal,*.doctest2.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/ochenk
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/ochenk/Sites/doctest2
      o: bind
      type: none

---------------------
```

</details>

<br>

And the output of `fin sysinfo`:

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin Ochens-MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
Mac OS X 10.12.5
fin version: 1.10.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        5 months ago        164MB
docksal/dns           1.0                 20c7a535479d        6 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        6 months ago        12.2MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
41788fa88c59        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      10 hours ago        Up 10 hours                                                                  docksal-ssh-agent
014af267c64a        docksal/dns:1.0           "/opt/entrypoint.s..."   10 hours ago        Up 10 hours         192.168.64.100:53->53/udp                                docksal-dns
ea99a44bed9a        docksal/vhost-proxy:1.0   "/usr/local/bin/st..."   10 hours ago        Up 10 hours         192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/1753a0da64557b7cb33c33fac7e94107c118e637f19f52dc60f40337c31ae259 type aufs (rw,relatime,si=93d8fb412f267b55,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/014af267c64a3843fb25bf6fa2ec7020b808c16c10ea605a7d7ecad42e23a642/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/632bce869bcfbe844acdf6a22fee1004bf6a3afd060df962d4fff68680c32b4a type aufs (rw,relatime,si=93d8fb412fda4b55,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/41788fa88c592873efb18b669deab4267e4d761bed152a09210cfaccec040940/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/0b0e165973dede4329b08e0d1dc874d3eb0f8db7ce380e1014f6c9df577ad9e4 type aufs (rw,relatime,si=93d8fb412f005b55,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/ea99a44bed9a726686aaad502be4c7322b60f31ddc10a64d72ffa3369096e102/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/7e08b4275670 type nsfs (rw)
nsfs on /var/run/docker/netns/2ad66ca1d413 type nsfs (rw)
nsfs on /var/run/docker/netns/fd7413005d65 type nsfs (rw)
  ```

</details>

Thanks!
