### ISSUE TITLE
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

### ISSUE THREAD

**Issue by ssudhak** [docksal/docksal#304]
**Description**

I am having a multi site installation. my first site is working fine. But when i am doing the second site installation, i am facing following issue while running make file.

sql-query: SELECT 1; [2.01 sec, 16.39 MB]                                                                        [notice]
Executing: mysql --defaults-extra-file=/tmp/drush_ws3UMe --database=www_invokana_com --host= --silent  < /tmp/drush_4StxRp > /dev/null
sql-query: DROP DATABASE IF EXISTS www_invokana_com; CREATE DATABASE www_invokana_com /*!40100 DEFAULT           [notice]
CHARACTER SET utf8 */; [2.02 sec, 16.4 MB]
Executing: mysql --defaults-extra-file=/tmp/drush_fGhAGS --database=information_schema --host= --silent  < /tmp/drush_5dmJJ3
  ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
                                                                                                              [error]
 [2.04 sec, 16.4 MB]
Returned from hook drush_core_pre_site_install [2.04 sec, 16.4 MB]                                                [debug]

** docksal.env in the main directory: **

DOCKSAL_STACK=default

VIRTUAL_HOST='jjfusion.docksal,*.jjfusion.docksal'
BASE_DOMAIN='jjfusion.docksal'
WEB_IMAGE='docksal/web:1.0-apache2.2'
DB_IMAGE='docksal/db:1.0-mysql-5.5'
CLI_IMAGE='docksal/cli:1.0-php5'

MYSQL_ROOT_PASSWORD=root
MYSQL_USER=user
MYSQL_PASSWORD=user
MYSQL_DATABASE=default

XDEBUG_ENABLED=1

** docksal.env in the subsite **

SITE_FEATURE='www_invokana_com'
SITE_DOMAIN='www_invokana_com.jjfusion.docksal'
SITE_NAME='www_invokana_com'
SITE_CONTENT='jcr'

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: fusion1291
COMPOSE_FILE:
/Users/a251267/.docksal/stacks/volumes-bind.yml
/Users/a251267/.docksal/stacks/stack-default.yml
/Users/a251267/Sites/fusion1291/.docksal/docksal.yml
ENV_FILE:
/Users/a251267/Sites/fusion1291/.docksal/docksal.env

PROJECT_ROOT: /Users/a251267/Sites/fusion1291
DOCROOT: docroot
VIRTUAL_HOST: jjfusion.docksal,*.jjfusion.docksal
VIRTUAL_HOST_ALIASES: *.jjfusion.docksal,*.jjfusion.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32769

Docker Compose configuration
---------------------
networks: {}
services:
  browser:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: browser
    image: selenium/standalone-chrome-debug
    ports:
    - 4444/tcp
    - 5900:5900/tcp
    volumes:
    - project_root:/var/www:rw
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      HOST_GID: '20'
      HOST_UID: '502'
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:1.0-php5
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_sites:/sites:rw
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached:1.4-alpine
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/a251267/Sites/fusion1291
      io.docksal.virtual-host: jjfusion.docksal,*.jjfusion.docksal,*.jjfusion.docksal,*.jjfusion.docksal
    volumes:
    - project_sites:/sites:ro
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/a251267
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/a251267/Sites/fusion1291
      o: bind
      type: none
  project_sites:
    driver: local
    driver_opts:
      device: /Users/a251267/Sites/fusion1291/../../sites
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin 02HW030478.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
Mac OS X 10.12.6
fin version: 1.10.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
memcached                          1.4-alpine          d323542b78b3        4 weeks ago         6.94MB
selenium/standalone-chrome-debug   latest              593e47f379db        5 weeks ago         890MB
docksal/vhost-proxy                1.0                 2c8a8b1e62c4        5 months ago        164MB
docksal/dns                        1.0                 20c7a535479d        6 months ago        61.6MB
docksal/ssh-agent                  1.0                 148220cc033d        6 months ago        12.2MB
docksal/web                        1.0-apache2.2       a9c03f8a5f0f        6 months ago        188MB
docksal/db                         1.0-mysql-5.5       9fb8c0aed5fc        6 months ago        255MB
docksal/cli                        1.0-php5            bde35eb43ad7        6 months ago        801MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
5872f3e774a7        docksal/web:1.0-apache2.2          "/opt/startup.sh a..."   2 weeks ago         Up 2 hours          80/tcp, 443/tcp                                          fusion1291_web_1
c8335039f2d2        memcached:1.4-alpine               "docker-entrypoint..."   2 weeks ago         Up 2 hours          11211/tcp                                                fusion1291_memcached_1
1b272512f924        selenium/standalone-chrome-debug   "/opt/bin/entry_po..."   2 weeks ago         Up 2 hours          0.0.0.0:5900->5900/tcp, 0.0.0.0:32768->4444/tcp          fusion1291_browser_1
d1a9c5588392        docksal/db:1.0-mysql-5.5           "/entrypoint.sh my..."   2 weeks ago         Up 2 hours          0.0.0.0:32769->3306/tcp                                  fusion1291_db_1
83c4e6aaddf0        docksal/cli:1.0-php5               "/opt/startup.sh g..."   2 weeks ago         Up 2 hours          22/tcp, 9000/tcp                                         fusion1291_cli_1
40c29cea1b1e        docksal/ssh-agent:1.0              "/run.sh ssh-agent"      2 weeks ago         Up 2 hours                                                                   docksal-ssh-agent
f843c175aa49        docksal/dns:1.0                    "/opt/entrypoint.s..."   2 weeks ago         Up 2 hours          192.168.64.100:53->53/udp                                docksal-dns
d0e7e00e781f        docksal/vhost-proxy:1.0            "/usr/local/bin/st..."   2 weeks ago         Up 2 hours          192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=1845260k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/82aaa5da35c4f97476f9c0f7241a72331baa389d1114a98716f53088316199d6 type aufs (rw,relatime,si=d6e78bbc046ea7bd,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/45ed5f69e48be5c33e8275271d225b663950e4a585bca6d1c709eb54d99e558c type aufs (rw,relatime,si=d6e78bbc0b9a87bd,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/c7658c09371b93a32b72e8dc32d236ef5e3cb3ba5bee9f0df79e7e0135d97d2b type aufs (rw,relatime,si=d6e78bbc0bdb47bd,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/40c29cea1b1e3a4d0b37b19ff80a0b24e131a50c1ff5685da2b83c9ee105772b/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/f843c175aa491b3c9f08ca60247ffd1bf8ab2d87b29cfa59be00541ced66c240/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/d0e7e00e781f4c3b37bb7c9a09c8342469d3f7c73e588006091f41a0287a7a18/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/2dd87835f9d1 type nsfs (rw)
nsfs on /var/run/docker/netns/e44e35675c31 type nsfs (rw)
nsfs on /var/run/docker/netns/c059aabcd1da type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/7b2d4ad70f88caa5baa034b23b9e3d1fb9af1b24fdcf2846acb3171a3c6efc66 type aufs (rw,relatime,si=d6e78bbc0bf6d7bd,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/d5142323c1fa3a10d96c8c14ae9fe9e242a0d0b7af6c985919fecf53e5bc4e1c type aufs (rw,relatime,si=d6e78bbc0547c7bd,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/b41e891f1470cf871e5d926ef7cc310a38e899349f0407a27f998c9307d89c89 type aufs (rw,relatime,si=d6e78bbc056067bd,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/c3b940dd55106966489d8ecdd94a7a7ff4dbc5590516d6829ce035aca2857eaa type aufs (rw,relatime,si=d6e78bbc0bbe57bd,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/83c4e6aaddf0145f55c1a842dc33235fee6890946e476a7ef77686d7e657cf4a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/a251267 on /mnt/sda1/var/lib/docker/volumes/fusion1291_host_home/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/a251267/Sites on /mnt/sda1/var/lib/docker/volumes/fusion1291_project_sites/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/a251267/Sites/fusion1291 on /mnt/sda1/var/lib/docker/volumes/fusion1291_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/fa06b55ad3b9 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/c8335039f2d2cb5436cbafac5187716ffdb3c3f9130f20763d1a8456678c5f69/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/1b272512f924512267b672db4db1b026db8488cc0d2ec15ac5f4db62e51aff15/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/dc6f6586f8b5 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/8677dce63440c63f5de98f592e4d00a485247812fdcf648f446e93b4197177f1 type aufs (rw,relatime,si=d6e78bbc055c57bd,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/d1a9c5588392496390d766e0921ada7d8feaa950648d4b4614cf6fe647a8b665/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/d9962446a284 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/5872f3e774a739073c0ab4cab954c233815c5391eda598654b8e95839b680c33/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/c96e47199073 type nsfs (rw)
nsfs on /var/run/docker/netns/5b8d944a136c type nsfs (rw)
  ```

</details>
