### ISSUE TITLE
Cannot use docksal without internet

### ISSUE THREAD

**Issue by thomscode** [docksal/docksal#313]
**Description**

When there is no internet connection my computer still doesn't find the Docksal DNS and cannot connect to docksal sites if there is no internet.

**Steps to reproduce the issue:**

1. Start a docksal project
2. Disconnect internet connection
3. Try to reach your docksal project

**Describe the results you received:**

I received an "no internet connection available"

**Describe the results you expected:**

Docksal is run completely on the local computer, I would expect that the DNS would work properly even without an internet connection.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: project
COMPOSE_FILE:
/Users/.../.docksal/stacks/volumes-bind.yml
/Users/.../.docksal/stacks/stack-default.yml
/Users/.../Code/sites/project/master/.docksal/docksal.yml
ENV_FILE:
/Users/.../Code/sites/project/master/.docksal/docksal.env
/Users/.../Code/sites/project/master/.docksal/docksal-local.env

PROJECT_ROOT: /Users/.../Code/sites/project/master
DOCROOT: docroot
VIRTUAL_HOST: project.docksal
VIRTUAL_HOST_ALIASES: *.project.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
networks: {}
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DBGP_IDEKEY: PHPSTORM
      HOST_GID: '20'
      HOST_UID: '501'
      PHP_IDE_CONFIG: serverName=project.docksal
      XDEBUG_CONFIG: remote_host=localhost remote_port=9000 remote_connect_back=1
        remote_autostart=0
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.2-php5
    volumes:
    - host_home:/.home:ro
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:mysql-5.7
    ports:
    - 0:3306/tcp
    volumes:
    - /Users/.../Code/sites/project/master/project.docksal/database:/var/lib/mysql:rw
    - project_root:/var/www:ro
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.4
    labels:
      io.docksal.project-root: /Users/.../Code/sites/project/master
      io.docksal.virtual-host: project.docksal,*.project.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  host_home:
    driver: local
    driver_opts:
      device: /Users/...
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/.../Code/sites/project/master
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin mymac.domain 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
Mac OS X 10.12.6
fin version: 1.10.0
Mode:  Native / Docker for Mac/Windows
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
docksal   -        virtualbox   Stopped                 Unknown   
███  DOCKER
DOCKER_HOST:	

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.1-ce-rc1
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   77b4dce
 Built:        Fri Jul 14 07:33:35 2017
 OS/Arch:      linux/amd64
 Experimental: true
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/web           2.0-apache2.4       38c223f7c3f9        5 days ago          87.5MB
docksal/cli           1.3-php7            1442dc481915        2 weeks ago         752MB
docksal/db            1.1-mysql-5.6       6feb79af9597        2 weeks ago         298MB
wernight/ngrok        latest              b8ff076d1ab1        5 weeks ago         26.9MB
docksal/cli           1.2-php5            11f47dc7d024        4 months ago        845MB
docksal/db            mysql-5.7           8a065493900b        5 months ago        406MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        5 months ago        164MB
docksal/dns           1.0                 20c7a535479d        6 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        6 months ago        12.2MB
docksal/web           1.0-apache2.4       1e2aa01c55d6        6 months ago        259MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
fb7a71015003        docksal/web:1.0-apache2.4   "/opt/startup.sh a..."   10 days ago         Up 6 days           80/tcp, 443/tcp                                          project_web_1
1cd3de119153        docksal/db:mysql-5.7        "/entrypoint.sh my..."   10 days ago         Up 6 days           0.0.0.0:32768->3306/tcp                                  project_db_1
8bd00ea29084        docksal/cli:1.2-php5        "/opt/startup.sh s..."   10 days ago         Up 6 days           22/tcp, 9000/tcp                                         project_cli_1
05da09fdaba4        docksal/web:1.0-apache2.4   "/opt/startup.sh a..."   10 days ago         Up 3 days           80/tcp, 443/tcp                                          projectdev_web_1
942f255bba4b        docksal/db:mysql-5.7        "/entrypoint.sh my..."   10 days ago         Up 3 days           0.0.0.0:32773->3306/tcp                                  projectdev_db_1
5377c33a4d1c        docksal/cli:1.2-php5        "/opt/startup.sh s..."   10 days ago         Up 3 days           22/tcp, 9000/tcp                                         projectdev_cli_1
0bc92d1078bc        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      10 days ago         Up 7 days                                                                    docksal-ssh-agent
3fc95fb50ce2        docksal/dns:1.0             "/opt/entrypoint.s..."   10 days ago         Up 7 days           192.168.64.100:53->53/udp                                docksal-dns
affc1607ca1a        docksal/vhost-proxy:1.0     "/usr/local/bin/st..."   10 days ago         Up 7 days           192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
  ```

</details>
