### ISSUE TITLE
Creating gudrupal8_cli_1 ... error

### ISSUE THREAD

**Issue by dealancer** [docksal/docksal#320]
Errors when creating a new project.

**Steps to reproduce the issue:**

1. Run `fin project create`
2. Enter a project name
3. See error message:

```
Creating gudrupal8_cli_1 ... error

ERROR: for gudrupal8_cli_1  Cannot start service cli: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/gudrupal8_project_root/_data': error while mounting volume with options: type='none' device='/Users/vadymmyrgorod/Sites/docksal/gudrupal8' o='bind': no suCreating gudrupal8_db_1 ... error

ERROR: for gudrupal8_db_1  Cannot start service db: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/gudrupal8_project_root/_data': error while mounting volume with options: type='none' device='/Users/vadymmyrgorod/Sites/docksal/gudrupal8' o='bind': no such file or directory

ERROR: for db  Cannot start service db: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/gudrupal8_project_root/_data': error while mounting volume with options: type='none' device='/Users/vadymmyrgorod/Sites/docksal/gudrupal8' o='bind': no such file or directory

ERROR: for cli  Cannot start service cli: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/gudrupal8_project_root/_data': error while mounting volume with options: type='none' device='/Users/vadymmyrgorod/Sites/docksal/gudrupal8' o='bind': no such file or directory
ERROR: Encountered errors while bringing up the project.
```

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
One second! Checking for updates...
---------------------
COMPOSE_PROJECT_NAME_SAFE: gudrupal8
COMPOSE_FILE:
/Users/vadymmyrgorod/.docksal/stacks/volumes-bind.yml
/Users/vadymmyrgorod/.docksal/stacks/stack-default.yml
/Users/vadymmyrgorod/Sites/docksal/gudrupal8/.docksal/docksal.yml
ENV_FILE:
/Users/vadymmyrgorod/Sites/docksal/gudrupal8/.docksal/docksal.env

PROJECT_ROOT: /Users/vadymmyrgorod/Sites/docksal/gudrupal8
DOCROOT: docroot
VIRTUAL_HOST: gudrupal8.docksal
VIRTUAL_HOST_ALIASES: *.gudrupal8.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '501'
      PROJECT_ROOT: /var/www
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php7
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 03306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.0-apache2.4
    labels:
      io.docksal.project-root: /Users/vadymmyrgorod/Sites/docksal/gudrupal8
      io.docksal.virtual-host: gudrupal8.docksal,*.gudrupal8.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /Users/vadymmyrgorod/Sites/docksal/gudrupal8
      o: bind
      type: none

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin Vadyms-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
Mac OS X 10.12.6
fin version: 1.22.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.06.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.12.0, build 45c69ad
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/web           2.0-apache2.4       7f75db9a6aa7        10 days ago         87.5MB
docksal/vhost-proxy   1.1                 898fb21e7f2d        2 weeks ago         158MB
docksal/cli           1.3-php7            1442dc481915        3 weeks ago         752MB
docksal/db            1.1-mysql-5.6       6feb79af9597        3 weeks ago         298MB
docksal/dns           1.0                 20c7a535479d        6 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        6 months ago        12.2MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
550ea69627fe        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      20 minutes ago      Up 17 minutes                                                                docksal-ssh-agent
cf6a930e9cea        docksal/dns:1.0           "/opt/entrypoint.s..."   20 minutes ago      Up 17 minutes       192.168.64.100:53->53/udp                                docksal-dns
733fd473d894        docksal/vhost-proxy:1.1   "docker-entrypoint..."   20 minutes ago      Up 16 minutes       192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.26r117224
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.44.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.100.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

███  NFS EXPORTS

# <ds-nfs docksal
/Users/vadymmyrgorod/Projects 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=1845260k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/92fcd99b04874e7e2d6006265baa9cc7ff36509d546a5c44f4bcfe0c465afa02 type aufs (rw,relatime,si=7248b39620c28f5b,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/5c84059fa66057ceebe4121daed764dc98259c2000a0c0bb2bed1064072811d1 type aufs (rw,relatime,si=7248b39620c88f5b,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/1f98317d6d4746287b494cca3dc1c6bbeeae07e08db90dd05d793d95ab56d972 type aufs (rw,relatime,si=7248b39620dbbf5b,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/550ea69627fe612d49e6470f8325891ebf4666d34068db4cae38353283d2f36a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/cf6a930e9cea784c9a1c379de404c35b78da696e4e357f25a8dd0efda9503533/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/733fd473d894dc18852da9ea8cbc2d4d2738cdd540cc411907f8231cc96f8146/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/b22989bb519d type nsfs (rw)
nsfs on /var/run/docker/netns/ee53642892fc type nsfs (rw)
nsfs on /var/run/docker/netns/d8eff5326627 type nsfs (rw)
192.168.64.1:/Users/vadymmyrgorod/Projects on /Users/vadymmyrgorod/Projects type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

  ```

</details>
