### ISSUE TITLE
Running custom command within another custom command within cli

### ISSUE THREAD

**Issue by dealancer** [docksal/docksal#322]
**Description**

Running custom command fails if run within another custom command that are called by another custom command.

**Steps to reproduce the issue:**

1. Use `https://github.com/docksal/drupal8`
2. Add to `fin ls db` to the begining of `.docksal/commands/init-site`
3. Run `fin init-site`

**Describe the results you received:**

Seeerror message:

```
/var/www/.docksal/commands/init-site: line 12: fin: command not found
```

**Describe the results you expected:**

No errors.

**Other information:**

If I place this command into `init` command, than everething works ok.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
fin config
---------------------
COMPOSE_PROJECT_NAME_SAFE: gud8
COMPOSE_FILE:
/Users/vadymmyrgorod/.docksal/stacks/volumes-bind.yml
/Users/vadymmyrgorod/.docksal/stacks/stack-default.yml
/Users/vadymmyrgorod/Projects/docksal/gud8/.docksal/docksal.yml
ENV_FILE:
/Users/vadymmyrgorod/Projects/docksal/gud8/.docksal/docksal.env

PROJECT_ROOT: /Users/vadymmyrgorod/Projects/docksal/gud8
DOCROOT: docroot
VIRTUAL_HOST: gud8.docksal
VIRTUAL_HOST_ALIASES: *.gud8.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32779

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '501'
      PROJECT_ROOT: /var/www
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php7
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 03306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.0-apache2.4
    labels:
      io.docksal.project-root: /Users/vadymmyrgorod/Projects/docksal/gud8
      io.docksal.virtual-host: gud8.docksal,*.gud8.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /Users/vadymmyrgorod/Projects/docksal/gud8
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
fin sysinfo
███  OS & BASICS
Darwin Vadyms-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
Mac OS X 10.12.6
fin version: 1.22.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.06.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.12.0, build 45c69ad
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/web           2.0-apache2.4       7f75db9a6aa7        2 weeks ago         87.5MB
docksal/vhost-proxy   1.1                 898fb21e7f2d        2 weeks ago         158MB
docksal/cli           1.3-php7            1442dc481915        3 weeks ago         752MB
docksal/db            1.1-mysql-5.6       6feb79af9597        4 weeks ago         298MB
docksal/dns           1.0                 20c7a535479d        7 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        7 months ago        12.2MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                 PORTS                                                    NAMES
37fa3c3b5149        docksal/web:2.0-apache2.4   "httpd-foreground"       3 hours ago         Up 3 hours             80/tcp, 443/tcp                                          gud8_web_1
13030e976090        docksal/db:1.1-mysql-5.6    "/entrypoint.sh my..."   3 hours ago         Up 3 hours             0.0.0.0:32779->3306/tcp                                  gud8_db_1
7c0f5e89a6c1        docksal/cli:1.3-php7        "/opt/startup.sh s..."   3 hours ago         Up 3 hours (healthy)   22/tcp, 9000/tcp                                         gud8_cli_1
550ea69627fe        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      3 days ago          Up 9 hours                                                                      docksal-ssh-agent
cf6a930e9cea        docksal/dns:1.0             "/opt/entrypoint.s..."   3 days ago          Up 9 hours             192.168.64.100:53->53/udp                                docksal-dns
733fd473d894        docksal/vhost-proxy:1.1     "docker-entrypoint..."   3 days ago          Up 9 hours             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.26r117224
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.44.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.100.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

███  NFS EXPORTS

# <ds-nfs docksal
/Users/vadymmyrgorod/Projects 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=1845260k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/5c84059fa66057ceebe4121daed764dc98259c2000a0c0bb2bed1064072811d1 type aufs (rw,relatime,si=33691f0a51d9967f,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/92fcd99b04874e7e2d6006265baa9cc7ff36509d546a5c44f4bcfe0c465afa02 type aufs (rw,relatime,si=33691f0a5167a67f,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/1f98317d6d4746287b494cca3dc1c6bbeeae07e08db90dd05d793d95ab56d972 type aufs (rw,relatime,si=33691f0a5160e67f,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/cf6a930e9cea784c9a1c379de404c35b78da696e4e357f25a8dd0efda9503533/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/550ea69627fe612d49e6470f8325891ebf4666d34068db4cae38353283d2f36a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/3365a1375f97 type nsfs (rw)
nsfs on /var/run/docker/netns/1f0cc55f163d type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/733fd473d894dc18852da9ea8cbc2d4d2738cdd540cc411907f8231cc96f8146/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/1ed84384b4e2 type nsfs (rw)
192.168.64.1:/Users/vadymmyrgorod/Projects on /Users/vadymmyrgorod/Projects type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/368f1e48c733d7bd6671eab3325544407f8a76b0582a04a6a566c4f6323af011 type aufs (rw,relatime,si=33691f0a506b567f,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/7c0f5e89a6c1314aa5a72181fd59077fb2a7d6761b92aa34289cf90df8c9eb50/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/vadymmyrgorod/Projects/docksal/gud8 on /mnt/sda1/var/lib/docker/volumes/gud8_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/61c1fd6650b9ebcf1b1d12e4caaf9238ba6391238c560d2430476b2bc8c2644d type aufs (rw,relatime,si=33691f0a501a767f,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/13030e9760904a35eb3915f44477152bc4b465f1e98374630061314b23d5983d/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/fc5558d6737c type nsfs (rw)
nsfs on /var/run/docker/netns/4c87cc62f972 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/5d9ac5c0c489f4c051f55eabbefed136cac76bed609bf977ba55c269e03288fc type aufs (rw,relatime,si=33691f0a0df6a67f,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/37fa3c3b5149f12b7ab6cfaae1395f6e3efd988477b8611d74c82ef98e8c5e03/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/efd975211395 type nsfs (rw)  ```

</details>

**Comment by achekulaev** [comment]
```bash
10:27:25 Alexei-Workstation /Users/alexei.chekulaev/Projects/demo-d7
$ cat .docksal/commands/command1 
#!/bin/bash

echo "Echo from Command 1"
fin command2
10:27:36 Alexei-Workstation /Users/alexei.chekulaev/Projects/demo-d7
$ cat .docksal/commands/command2
#!/bin/bash

echo "Echo from Command 2"
fin command3
10:27:41 Alexei-Workstation /Users/alexei.chekulaev/Projects/demo-d7
$ cat .docksal/commands/command3
#!/bin/bash

echo "Echo from Command 3"
10:27:42 Alexei-Workstation /Users/alexei.chekulaev/Projects/demo-d7
$ fin command1
Echo from Command 1
Echo from Command 2
Echo from Command 3
```

Can not reproduce. Most likely you have errors in your scripts, you run something that changes the PATH variable and it's not able to find `fin` anymore.

**Comment by dealancer** [comment]
@achekulaev.

You should still be able to reproduce if using same steps as I described. But I think I figured out the problem: `site-init` is a CLI command (`#: exec_target = cli`) so `fin` is not defined there.

**Comment by achekulaev** [comment]
I checked by the title that said it's not working when it's "custom command ... run within another custom command, that are called by another custom command".

**Comment by lmakarov** [comment]
@dealancer I'm actually dealing with the same use case right now and trying to figure out the best approach.

When using `#: exec_target = cli` for commands you have to consider the following:

1. there is no `fin` in cli
2. calling other commands can be done via `${PROJECT_ROOT}/.docksal/commands/my-command` (which resolves to `/var/www/.docksal/commands/my-command` inside cli)
3. the command being called cannot use fin (due to 1)
4. variables defined in `docksal.env` are not passed to `cli` (though, they can be passed selectively via `docksal.yml`)

Here's how 4 can be handled:

**docksal.yml**

```yaml

version: '2.1'

services:
  cli:
    environment:
      # These variables are set here
      - ACAPI_EMAIL=email
      - ACAPI_KEY=key
      # These variables are passed from the host (including values in `docksal.env`/`docksal-local.env`)
      - SOURCE_ALIAS
      - VIRTUAL_HOST
```
