### ISSUE TITLE
mysql-5.6: unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by jamessweeney** [docksal/docksal#333]
**Description**

I attempted to run the Drupal 7 [sample project](https://github.com/docksal/drupal7) having followed the setup instructions for [macOS](http://docksal.readthedocs.io/en/master/getting-started/env-setup/#macos). However I got the error below:
``ERROR: Get https://registry-1.docker.io/v2/docksal/db/manifests/1.1-mysql-5.6: unauthorized: incorrect username or password``

**Steps to reproduce the issue:**

1. Follow the instructions at (https://github.com/docksal/drupal7](https://github.com/docksal/drupal7)

**Describe the results you received:**

The following is the output I received
```
➜  drupal7 git:(master) fin init
 Step 1  Initializing local project configuration...
Making site directory writable...
Copying /Users/james/drupal7/docroot/sites/default/settings.local.php...
 Step 2  Recreating services...
Removing containers...
Removing network drupal7_default
WARNING: Network drupal7_default not found.
Removing volume drupal7_project_root
WARNING: Volume drupal7_project_root not found.
Volume docksal_ssh_agent is external, skipping
Starting services...
Creating network "drupal7_default" with the default driver
Creating volume "drupal7_project_root" with local driver
Pulling db (docksal/db:1.1-mysql-5.6)...
ERROR: Get https://registry-1.docker.io/v2/docksal/db/manifests/1.1-mysql-5.6: unauthorized: incorrect username or password
```

**Describe the results you expected:**

I expected the process to download MySQL and provision the containers.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
fin config
---------------------
COMPOSE_PROJECT_NAME_SAFE: drupal7
COMPOSE_FILE:
/Users/james/.docksal/stacks/volumes-bind.yml
/Users/james/.docksal/stacks/stack-default.yml
ENV_FILE:
/Users/james/drupal7/.docksal/docksal.env

PROJECT_ROOT: /Users/james/drupal7
DOCROOT: docroot
VIRTUAL_HOST: drupal7.docksal
VIRTUAL_HOST_ALIASES: *.drupal7.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '501'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 03306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.0-apache2.4
    labels:
      io.docksal.project-root: /Users/james/drupal7
      io.docksal.virtual-host: drupal7.docksal,*.drupal7.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /Users/james/drupal7
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
fin sysinfo
███  OS & BASICS
Darwin IT-10.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
Mac OS X 10.12.6
fin version: 1.26.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.06.1-ce
 API version:  1.28 (downgraded from 1.30)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:38 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.12.0, build 45c69ad
███  DOCKER: IMAGES
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
docksal/ssh-agent   1.0                 148220cc033d        7 months ago        12.2MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                   COMMAND               CREATED             STATUS              PORTS               NAMES
6db5d1de0cec        docksal/ssh-agent:1.0   "/run.sh ssh-agent"   5 weeks ago         Up 7 days                               docksal-ssh-agent
███  VIRTUALBOX
5.1.22r115126
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/8c0ef5bebb0239f8733de680a3143c7cf02a6cb6c787a2ba362e6196ae6f1ba3 type aufs (rw,relatime,si=8085f66bb007d7c6,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/6db5d1de0cec2a6da911a73ce1e77934b45cb040cf9d885013a72335d776964b/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/064b763951eb type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
  ```

</details>
