### ISSUE TITLE
'fin logs web' does not print anything

### ISSUE THREAD

**Issue by ArtuGit** [docksal/docksal#334]
![image](https://user-images.githubusercontent.com/10816446/29750557-5a7a6e80-8b4a-11e7-92b4-f06774d2e9bc.png)

**Comment by achekulaev** [comment]
Debugging information is missing.

**Comment by ArtuGit** [comment]
<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: myproject
COMPOSE_FILE:
/home/artu/.docksal/stacks/volumes-bind.yml
/data/Websites/myproject/.docksal/docksal.yml
/data/Websites/myproject/.docksal/docksal-local.yml
ENV_FILE:
/data/Websites/myproject/.docksal/docksal.env
/data/Websites/myproject/.docksal/docksal-local.env

PROJECT_ROOT: /data/Websites/myproject
DOCROOT: html
VIRTUAL_HOST: myproject.docksal
VIRTUAL_HOST_ALIASES: *.myproject.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:33061

Docker Compose configuration
---------------------
services:
  browser:
    hostname: browser
    image: selenium/standalone-chrome
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      HOST_GID: '1000'
      HOST_UID: '1000'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php5
    ports:
    - 2223:22/tcp
    - 8080:8080/tcp
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 33061:3306/tcp
    volumes:
    - project_root:/var/www:ro
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.myproject.docksal
    user: root
  memcached:
    command:
    - -m
    - '256'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/html
    hostname: web
    image: docksal/web:2.0-apache2.2
    labels:
      io.docksal.project-root: /data/Websites/myproject
      io.docksal.virtual-host: myproject.docksal,*.myproject.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /data/Websites/myproject
      o: bind
      type: none

---------------------

```

</details>

<br>

<details>
  <summary>fin sysinfo output</summary>

  ```
WARNING: No swap limit support
███  OS & BASICS
Linux Desktop 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 16.04
fin version: 1.22.0
Mode:  Native / Docker for Mac/Windows
███  DOCKER
DOCKER_HOST:    

Docker: Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
WARNING: No swap limit support
███  DOCKER: IMAGES
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
docksal/web                   2.0-apache2.2       914141c9e347        3 weeks ago         81MB
docksal/vhost-proxy           1.1                 898fb21e7f2d        3 weeks ago         158MB
docksal/cli                   1.3-php7            1442dc481915        4 weeks ago         752MB
docksal/cli                   1.3-php5            77f9a2e141fa        4 weeks ago         808MB
docksal/db                    1.1-mysql-5.6       6feb79af9597        5 weeks ago         298MB
docksal/db                    1.1-mysql-5.5       aa748dc21dd4        5 weeks ago         256MB
memcached                     1.4-alpine          273374b463b8        5 weeks ago         7.68MB
selenium/standalone-firefox   latest              813d29296f6b        8 weeks ago         631MB
ubuntu                        latest              d355ed3537e9        2 months ago        119MB
wernight/ngrok                latest              7d0713e0e005        3 months ago        26.9MB
docksal/web                   edge-apache2.2      474b0aad797d        3 months ago        188MB
docksal/web                   edge-apache2.4      963ff738c054        3 months ago        260MB
selenium/standalone-chrome    latest              62686d7c78de        4 months ago        835MB
mailhog/mailhog               latest              669347153085        4 months ago        19.1MB
docksal/cli                   1.2-php5            11f47dc7d024        4 months ago        845MB
docksal/cli                   1.2-php7            aef362412c9f        4 months ago        787MB
docksal/vhost-proxy           1.0                 2c8a8b1e62c4        5 months ago        164MB
docksal/dns                   1.0                 20c7a535479d        7 months ago        61.6MB
docksal/ssh-agent             1.0                 148220cc033d        7 months ago        12.2MB
docksal/web                   1.0-apache2.2       a9c03f8a5f0f        7 months ago        188MB
docksal/db                    1.0-mysql-5.5       9fb8c0aed5fc        7 months ago        255MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                 PORTS                                                    NAMES
643a12fe8a20        mailhog/mailhog              "MailHog"                2 days ago          Up 5 hours             80/tcp, 1025/tcp, 8025/tcp                               myproject_mail_1
51dac171c63a        memcached:1.4-alpine         "docker-entrypoint..."   6 days ago          Up 5 hours             11211/tcp                                                myproject_memcached_1
ddf1d3ae03b9        selenium/standalone-chrome   "/opt/bin/entry_po..."   12 days ago         Up 5 hours             4444/tcp                                                 myproject_browser_1
cb40f8dc547d        docksal/ssh-agent:1.0        "/run.sh ssh-agent"      2 weeks ago         Up 6 hours                                                                      docksal-ssh-agent
6e7c05e88948        docksal/dns:1.0              "/opt/entrypoint.s..."   2 weeks ago         Up 6 hours             192.168.64.100:53->53/udp                                docksal-dns
c38e0f313a63        docksal/vhost-proxy:1.1      "docker-entrypoint..."   2 weeks ago         Up 6 hours             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
6430544863aa        docksal/web:2.0-apache2.2    "httpd-foreground"       3 weeks ago         Up 5 hours             80/tcp, 443/tcp                                          myproject_web_1
d0001d089fe8        docksal/cli:1.3-php5         "/opt/startup.sh s..."   3 weeks ago         Up 5 hours (healthy)   0.0.0.0:8080->8080/tcp, 9000/tcp, 0.0.0.0:2223->22/tcp   myproject_cli_1
10b8c3bc7aa7        docksal/db:1.1-mysql-5.6     "/entrypoint.sh my..."   3 weeks ago         Up 5 hours             0.0.0.0:33061->3306/tcp                                  myproject_db_1
███  VIRTUALBOX
5.1.20r114628
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.88.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       10.0.0.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

  ```

</details>
