### ISSUE TITLE
Environment variables set via docksal.env and docksal-local.env should be accessible inside cli

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#335]
Sometimes there is a need to set environment variable in `cli` and there are several ways to do it now:
1. use a script
2. use advanced exec (`fin exec 'MYVAR=1 env'`)
3. alter `.bashrc` inside `cli`

It would make sense if `fin` exported environment variables set in ENV files so that they were automatically accessible in exec commands, custom commands and addons.

**Comment by lmakarov** [comment]
Setting variables in containers can be done in a much simpler way via docker-compose and yaml files. Variables set in `docksal.env` and `docksal-local.env` are already accessible in `fin` and custom commands. They are not automatically passed to `cli` or other containers, though.

Setting env variable or passing host env variables to containers can be done like this:

**docksal.yml**

```yaml
version: '2.1'

services:
  cli:
    environment:
      # These variables are set here
      - ACAPI_EMAIL=email
      - ACAPI_KEY=key
      # These variables are passed from the host (including values in `docksal.env`/`docksal-local.env`)
      - SOURCE_ALIAS
      - VIRTUAL_HOST
```
