### ISSUE TITLE
Drupal: Class 'Memcached' not found in /var/www/docroot/sites/default/settings.php

### ISSUE THREAD

**Issue by comxd** [docksal/docksal#336]
Hi,

Memcached working good but when include use some memcached options into my settings.php file I have a fatal error.

**Steps to reproduce the issue:**

Set some options into settings.php that use the Memcached constants:

```
$conf['memcache_options'] = array(
  Memcached::OPT_COMPRESSION => FALSE,
  Memcached::OPT_DISTRIBUTION => Memcached::DISTRIBUTION_CONSISTENT,
  Memcached::OPT_BINARY_PROTOCOL => FALSE,
);
```

**Describe the results you received:**

Fatal error: Drupal: Class 'Memcached' not found in /var/www/docroot/sites/default/settings.php

**Output of `fin config`:**

```
services:
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
```
