### ISSUE TITLE
Cannot start service db: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/project/_data': error while mounting volume with options: type='none' device='/Users/me/work/project' o='bind': no such file or directory

### ISSUE THREAD

**Issue by welly** [docksal/docksal#338]
**Description**

On cloning https://github.com/docksal/drupal7 and running fin init I get the following errors:

```
Creating network "project_default" with the default driver
Creating volume "project_project_root" with local driver
Creating project_db_1 ...
Creating project_db_1
Creating project_cli_1 ...
Creating project_db_1 ... error

ERROR: for project_db_1  Cannot start service db: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/project_project_root/_data': error while mounting volume with options: type='none' device='/Users/me/dev/work/project' o='bind': no such file or direCreating project_cli_1 ... error

ERROR: for project_cli_1  Cannot start service cli: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/project_project_root/_data': error while mounting volume with options: type='none' device='/Users/me/dev/work/project' o='bind': no such file or directory

ERROR: for db  Cannot start service db: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/project_project_root/_data': error while mounting volume with options: type='none' device='/Users/me/dev/work/project' o='bind': no such file or directory

ERROR: for cli  Cannot start service cli: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/project_project_root/_data': error while mounting volume with options: type='none' device='/Users/me/dev/work/project' o='bind': no such file or directory
ERROR: Encountered errors while bringing up the project.
```

**Steps to reproduce the issue:**

1. git clone https://github.com/docksal/drupal7.git project
2. fin init

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: project
COMPOSE_FILE:
/Users/me/.docksal/stacks/volumes-bind.yml
/Users/me/.docksal/stacks/stack-default.yml
ENV_FILE:
/Users/me/dev/work/project/.docksal/docksal.env

PROJECT_ROOT: /Users/me/dev/work/project
DOCROOT: docroot
VIRTUAL_HOST: drupal7.docksal
VIRTUAL_HOST_ALIASES: *.drupal7.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '501'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 03306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.0-apache2.4
    labels:
      io.docksal.project-root: /Users/me/dev/work/project
      io.docksal.virtual-host: drupal7.docksal,*.drupal7.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /Users/me/dev/work/project
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin mes-iMac.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
Mac OS X 10.12.6
fin version: 1.26.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.06.0-ce
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:38 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.12.0, build 45c69ad
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/web           2.0-apache2.4       7f75db9a6aa7        3 weeks ago         87.5MB
docksal/vhost-proxy   1.1                 898fb21e7f2d        4 weeks ago         158MB
docksal/cli           1.3-php5            77f9a2e141fa        5 weeks ago         808MB
docksal/db            1.1-mysql-5.6       6feb79af9597        5 weeks ago         298MB
docksal/dns           1.0                 20c7a535479d        7 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        7 months ago        12.2MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
b79dd91b9daf        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      10 minutes ago      Up 4 minutes                                                                 docksal-ssh-agent
8a641fcd5e23        docksal/dns:1.0           "/opt/entrypoint.s..."   10 minutes ago      Up 4 minutes        192.168.64.100:53->53/udp                                docksal-dns
77c584b45a31        docksal/vhost-proxy:1.1   "docker-entrypoint..."   10 minutes ago      Up 4 minutes        192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.22r115126
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       10.20.1.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.33.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

███  NFS EXPORTS

# <ds-nfs docksal
/Users/me/Projects 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=1845260k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/af7d2d00302fcfb4d1e2a4057e26946f75e7c253c7bda89ff1e86eab8534e8ac type aufs (rw,relatime,si=ec07341d90a4ec1,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/751f39c9e28884b23e1cb7f4e3fefb5d5494d4c7d27779d3a06ed74ee5238a81 type aufs (rw,relatime,si=ec07341d9be0ec1,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/6e67658146857816b05bffe249e449fa1483c1dbb04893d263a1c265bacac7e8 type aufs (rw,relatime,si=ec07341d9bdfec1,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/b79dd91b9dafff60b8d68b5b85a545266a1e52427b903e02df2aa6380ae6d33d/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/8b58f158be28 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/77c584b45a317f51102b4d324e9d4b51e4d61b37425b9a1c34997aa3f9ba9204/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/8d5cbb9429e3 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/8a641fcd5e236c488fb08769dd80e15543b0590f839f7639621a5fd1c2d3407b/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/53b9d767becf type nsfs (rw)
192.168.64.1:/Users/me/Projects on /Users/me/Projects type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
  ```

</details>
