### ISSUE TITLE
Failed to connect to your database server. The server reports the following message: SQLSTATE[HY000] [2002] No route to host.

### ISSUE THREAD

**Issue by bbonora** [docksal/docksal#347]
**Description**

I can't connect to the DB server from a PHP application (Drupal 7) using the docksal IP address. Specifically, when I attempt to do a fresh install using the install.php file within drupal I get the following error message:

```
Failed to connect to your database server. The server reports the following message: SQLSTATE[HY000] [2002] No route to host.
```
If I run the following from the command line I can connect, without any issues:

```
mysql -uroot -p123 -P5123 -h192.168.64.100
```
I'm sure this is a network/dns issue but I don't know how to resolve it. Any help would be greatly appreciated.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: docksaltest
COMPOSE_FILE:
/home/ben/.docksal/stacks/volumes-bind.yml
/home/ben/projects/docksal-test/.docksal/docksal.yml
/home/ben/projects/docksal-test/.docksal/docksal-local.yml
ENV_FILE:
/home/ben/projects/docksal-test/.docksal/docksal.env
/home/ben/projects/docksal-test/.docksal/docksal-local.env

PROJECT_ROOT: /home/ben/projects/docksal-test
DOCROOT: public
VIRTUAL_HOST: example.local
VIRTUAL_HOST_ALIASES: *.example.local
IP: 192.168.64.100
MYSQL: 192.168.64.100:5123

Docker Compose configuration
---------------------
services:
  cli:
    environment:
      PHP_IDE_CONFIG: serverName=example.local
      XDEBUG_CONFIG: idekey=PHPSTORM remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:1.2-php7
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    environment:
      MYSQL_DATABASE: example_database
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 5123:3306/tcp
    volumes:
    - project_root:/var/www:ro
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.example.local
    user: root
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached
  solr:
    hostname: solr
    image: docksal/solr:1.0-solr4
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:1.0-varnish4
    labels:
      io.docksal.virtual-host: varnish.example.local
  web:
    depends_on:
      cli:
        condition: service_started
    environment:
      APACHE_DOCUMENTROOT: /var/www/public
      VIRTUAL_HOST: example.local
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /home/ben/projects/docksal-test
      io.docksal.virtual-host: example.local,*.example.local
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /home/ben/projects/docksal-test
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
WARNING: No swap limit support
███  OS & BASICS
Linux ben-ThinkPad-S1-Yoga 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
LinuxMint 18.1
fin version: 1.26.0
Mode:  Native / Docker for Mac/Windows
███  DOCKER
DOCKER_HOST:

Docker: Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:17:22 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:16:12 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
WARNING: No swap limit support
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/vhost-proxy   1.1                 898fb21e7f2d        4 weeks ago         158MB
memcached             latest              4b6d78556a83        2 months ago        82.6MB
wernight/ngrok        latest              b8ff076d1ab1        2 months ago        26.9MB
mailhog/mailhog       latest              669347153085        4 months ago        19.1MB
docksal/cli           1.2-php5            11f47dc7d024        5 months ago        845MB
docksal/cli           1.2-php7            aef362412c9f        5 months ago        787MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        6 months ago        164MB
docksal/dns           1.0                 20c7a535479d        7 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        7 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        7 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        7 months ago        255MB
docksal/solr          1.0-solr4           fa6b236caf06        8 months ago        546MB
docksal/varnish       1.0-varnish4        35dae6b91ff9        8 months ago        99.5MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                   NAMES
c5f0d942fd2c        docksal/varnish:1.0-varnish4   "/opt/startup.sh"        31 minutes ago      Up 31 minutes       80/tcp                                   docksaltest_varnish_1
566b0f27866d        docksal/web:1.0-apache2.2      "/opt/startup.sh a..."   31 minutes ago      Up 31 minutes       80/tcp, 443/tcp                                   docksaltest_web_1
2514964eee2f        docksal/cli:1.2-php7           "/opt/startup.sh s..."   31 minutes ago      Up 31 minutes       22/tcp, 9000/tcp                                   docksaltest_cli_1
7ff139056742        mailhog/mailhog                "MailHog"                31 minutes ago      Up 31 minutes       80/tcp, 1025/tcp, 8025/tcp                               docksaltest_mail_1
00af7a2db6fb        docksal/solr:1.0-solr4         "/opt/solr/bin/sol..."   31 minutes ago      Up 31 minutes       8983/tcp                                   docksaltest_solr_1
f58a98279032        memcached                      "docker-entrypoint..."   31 minutes ago      Up 31 minutes       11211/tcp                                   docksaltest_memcached_1
0d13ff4f13e3        docksal/db:1.0-mysql-5.5       "/entrypoint.sh my..."   31 minutes ago      Up 31 minutes       0.0.0.0:5123->3306/tcp                                   docksaltest_db_1
74580651a260        docksal/ssh-agent:1.0          "/run.sh ssh-agent"      45 minutes ago      Up 34 minutes                                   docksal-ssh-agent
8939501baab5        docksal/dns:1.0                "/opt/entrypoint.s..."   45 minutes ago      Up 34 minutes       192.168.64.100:53->53/udp                                docksal-dns
9e5d484d178a        docksal/vhost-proxy:1.1        "docker-entrypoint..."   45 minutes ago      Up 34 minutes       192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.0.40_Ubuntur115130
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       12.12.12.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       12.12.12.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1
  ```

</details>
