### ISSUE TITLE
Spin up another Solr core?

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#348]
More of a support ticket here. With the new Search API Solr module that's out, they enforce one core per index, so now I need to spin up additional cores rather than just have the single core we've all had traditionally. What's the recommendation from you on spinning up additional cores in the Solr service?

**Comment by achekulaev** [comment]
I personally don't have any recommendations. I have no idea what are Solr best practices. Don't work with it much. 
I know though that you can spin up as many cores as you need via configuration.

**Comment by lmakarov** [comment]
@lpeabody I yet haven't run into this new requirement from Search API Solr module either.

Please post here when you figure it out. We'll want to include those instructions in the docs.

**Comment by lpeabody** [comment]
For reference, the Drupal issue can be followed here https://www.drupal.org/node/2896269

**Comment by SOMERSOFTAndrewCrook** [comment]
The following works for a Drupal 8 multisite installation with two independant solr instances for a.docksal and b.docksal using Solr 4.x.  I think for a single site, the labels configuration does not need to be present.
.docksal/docksal.yml
```
services:
  solr:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
    labels:
      io.docksal.virtual-host: solr.a.docksal,solr.b.docksal
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/a:/opt/solr/example/solr/a:ro
      - ${PROJECT_ROOT}/../data/a/solr:/var/lib/solr/a/data:rw
      - ${PROJECT_ROOT}/.docksal/etc/solr/b:/opt/solr/example/solr/b:ro
      - ${PROJECT_ROOT}/../data/b/solr:/var/lib/solr/b/data:rw
```
.docksal/etc/solr/a/core.properties
```
name=a
dataDir=/var/lib/solr/a/data
```
.docksal/etc/solr/b/core.properties
```
name=b
dataDir=/var/lib/solr/b/data
```
.docksal/etc/solr/a/conf: Solr configuration files for instance a
.docksal/etc/solr/b/conf: Solr configuration files for instance b

I hope this is a good starting point.

**Comment by lmakarov** [comment]
@SOMERSOFTAndrewCrook thanks for the example!

Unless you really want to store solr index on your host, I'd suggest the following change to the volumes section in your configuration:

```
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/a:/opt/solr/example/solr/a:ro
      - /var/lib/solr/a/data:rw
      - ${PROJECT_ROOT}/.docksal/etc/solr/b:/opt/solr/example/solr/b:ro
      - /var/lib/solr/b/data:rw
```

This will improve the fs performance greatly on Mac and Windows (with no difference on Linux).

**Comment by SOMERSOFTAndrewCrook** [comment]
Thank you for the suggested update. It provides a great example on how to do either for all.

**Comment by SOMERSOFTAndrewCrook** [comment]
Here are the updated changes to files to use solr 6.x 
docksal.yml
```
  solr:
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/a:/opt/solr/server/solr/a:ro
      - ${PROJECT_ROOT}/../data/a/solr:/var/solr/a/data:rw
      - ${PROJECT_ROOT}/.docksal/etc/solr/b:/opt/solr/server/solr/b:ro
      - ${PROJECT_ROOT}/../data/b/solr:/var/solr/b/data:rw
    image: solr:6.6-alpine
```
.docksal/etc/solr/a/core.properties
```
dataDir=/var/solr/a/data
```
.docksal/etc/solr/b/core.properties
```
dataDir=/var/solr/b/data
```
