### ISSUE TITLE
ngrok share to non-default domain?

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#363]
Currently `fin share` will only share out the domain controlled by the VIRTUAL_HOST environment variable. Can this command be expanded to connect to any domain controlled by a given project? Use case would be Drupal multi-site with many local sites running at once for a given project.

**Comment by lmakarov** [comment]
I don't think this is technically possible with ngrok.

This is the command used in fin to start ngrok:

```
ngrok http -host-header ${VIRTUAL_HOST} ${container_name}.${network}:80
```

Your can only pass a single `-host-header`, which makes sense, since how would ngrok know which header to use for a request if there were more than 1?

The only option I see would be to launch multiple ngrok instances with different host headers:

```
ngrok http -host-header subdomain1.${VIRTUAL_HOST} ${container_name}.${network}:80
ngrok http -host-header subdomain2.${VIRTUAL_HOST} ${container_name}.${network}:80
...
```

Ngrok also supports setting a custom subdomain, so instead of `http://d2517bcf.ngrok.io` for the public domain you would get `http://my-sub-domain.ngrok.io`, but that is only available on paid plans and would still require launching multiple ngrok instances to proxy a multisite.

Maybe try using a rewrite rule in `.htaccess` and rewrite a subfolder into a subdomain?

**Comment by lpeabody** [comment]
@lmakarov so a workaround for this, to still leverage the fin share command as written, is to set VIRTUAL_HOST=subdomain in docksal-local.env, launch fin-share, then remove VIRTUAL_HOST in docksal-local.env after the command has been run.

Works well enough. Is there a method for overriding docksal.env values from the command line? Something like `fin -d VIRTUAL_HOST=subdomain.site.docksal share`?

**Comment by achekulaev** [comment]
@lpeabody sure. The bash thing for overriding ENV vars works here as we don't force VIRTUAL_HOST inside `fin`

```
VIRTUAL_HOST=subdomain.site.docksal fin share
```

**Comment by lpeabody** [comment]
@achekulaev That didn't work for me, unfortunately. Using fin version 1.43.2. Can you confirm that works for you in your own test?

If I set in docksal.env:

```
...
VIRTUAL_HOST=com.domain.docksal
...
```

And run `fin share` it uses VIRTUAL_HOST as expected.

If I leave that out of docksal.env or docksal-local.env and instead run it on the command line as you indicated:

`VIRTUAL_HOST=com.domain.docksal fin share`

...it behaves as if VIRTUAL_HOST was not set and routes me to the default VIRTUAL_HOST domain.docksal.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: corvette
COMPOSE_FILE:
/Users/les.peabody/.docksal/stacks/volumes-bind.yml
/Users/les.peabody/.docksal/stacks/stack-acquia.yml
/Users/les.peabody/Sites/corvette/.docksal/docksal.yml
/Users/les.peabody/Sites/corvette/.docksal/docksal-local.yml
ENV_FILE:
/Users/les.peabody/Sites/corvette/.docksal/docksal.env
/Users/les.peabody/Sites/corvette/.docksal/docksal-local.env

PROJECT_ROOT: /Users/les.peabody/Sites/corvette
DOCROOT: docroot
VIRTUAL_HOST: baxter.docksal
VIRTUAL_HOST_ALIASES: *.baxter.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    build:
      context: /Users/les.peabody/Sites/corvette/.docksal/services/cli
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DEFAULT_BUILD_THEME_PROFILE: bax_base
      DOCROOT: docroot
      HOST_GID: '1106437719'
      HOST_UID: '1729411499'
      PHP_IDE_CONFIG: serverName=baxter.docksal
      XDEBUG_CONFIG: idekey=PHPSTORM remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: corvette_cli
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: solr
    image: docksal/solr:1.0-solr4
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:1.0-varnish4
    labels:
      io.docksal.virtual-host: varnish.baxter.docksal
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/les.peabody/Sites/corvette
      io.docksal.virtual-host: baxter.docksal,*.baxter.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/les.peabody/Sites/corvette
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Mac OS X 10.12.6
Darwin BOSGEN-NMX0813.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
Mode: VirtualBox VM

███  FIN
fin version: 1.43.2

███  ENVIRONMENT
DOCKER_HOST		| tcp://192.168.64.100:2376
------------------------------------------------------------
DOCKSAL_NFS_PATH	| 

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false

███  DOCKER INFO
Containers: 15
 Running: 15
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 162
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.89-boot2docker
Operating System: Boot2Docker 17.09.0-ce (TCL 7.2); HEAD : 06d5c35 - Wed Sep 27 23:22:43 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955GiB
Name: docksal
ID: MWTD:BCOD:22CK:P5PW:O4SP:J3UM:UWL7:SSWE:MZL6:UE6C:7FRI:KYZJ
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 169
 Goroutines: 123
 System Time: 2018-03-16T13:50:39.810159382Z
 EventsListeners: 2
Username: lpeabody
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.17.1
docker-compose version 1.17.1, build 6d101fb
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016

███  DOCKER MACHINE
EXPECTED VERSION: 0.13.0
docker-machine version 0.13.0, build 9ba6da9

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   -        virtualbox   Stopped                                       Unknown       
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.09.0-ce   

███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
corvette_cli          latest              4c683d131616        19 hours ago        1.02GB
wernight/ngrok        latest              8b0a114c44cf        2 weeks ago         27.1MB
docksal/cli           2.0-php7.1          a73758be696b        6 weeks ago         919MB
docksal/cli           1.3-php7            19bdddfeab89        5 months ago        759MB
docksal/web           2.1-apache2.4       32c1d32eba6d        6 months ago        87.5MB
docksal/vhost-proxy   1.1                 898fb21e7f2d        7 months ago        158MB
docksal/db            1.1-mysql-5.6       6feb79af9597        7 months ago        298MB
memcached             1.4-alpine          273374b463b8        8 months ago        7.68MB
docksal/dns           1.0                 20c7a535479d        13 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        13 months ago       12.2MB
docksal/solr          1.0-solr4           fa6b236caf06        14 months ago       546MB
docksal/varnish       1.0-varnish4        35dae6b91ff9        14 months ago       99.5MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
765bf4a0ea1e        docksal/varnish:1.0-varnish4   "/opt/startup.sh"        17 minutes ago      Up 17 minutes             80/tcp                                                   corvette_varnish_1
6d6405e87278        docksal/web:2.1-apache2.4      "httpd-foreground"       18 minutes ago      Up 18 minutes             80/tcp, 443/tcp                                          corvette_web_1
3f76cb564119        corvette_cli                   "/opt/startup.sh s..."   18 minutes ago      Up 18 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               corvette_cli_1
441815959bd2        docksal/varnish:1.0-varnish4   "/opt/startup.sh"        19 hours ago        Up 19 hours               80/tcp                                                   sensata_varnish_1
bbc6597e350b        docksal/web:2.1-apache2.4      "httpd-foreground"       19 hours ago        Up 19 hours               80/tcp, 443/tcp                                          sensata_web_1
12a7f358999a        memcached:1.4-alpine           "docker-entrypoint..."   19 hours ago        Up 19 hours               11211/tcp                                                sensata_memcached_1
3ac04c6519ae        docksal/db:1.1-mysql-5.6       "/entrypoint.sh my..."   19 hours ago        Up 19 hours               0.0.0.0:32770->3306/tcp                                  sensata_db_1
cd67ec99532b        docksal/solr:1.0-solr4         "/opt/solr/bin/sol..."   19 hours ago        Up 19 hours               8983/tcp                                                 sensata_solr_1
d82503de6b36        docksal/cli:2.0-php7.1         "/opt/startup.sh s..."   19 hours ago        Up 19 hours (healthy)     22/tcp, 3000/tcp, 9000/tcp                               sensata_cli_1
306ce649790a        docksal/solr:1.0-solr4         "/opt/solr/bin/sol..."   19 hours ago        Up 19 hours               8983/tcp                                                 corvette_solr_1
3c8d34fb2ff4        memcached:1.4-alpine           "docker-entrypoint..."   19 hours ago        Up 19 hours               11211/tcp                                                corvette_memcached_1
6bcd1c00d273        docksal/db:1.1-mysql-5.6       "/entrypoint.sh my..."   19 hours ago        Up 19 hours               0.0.0.0:32768->3306/tcp                                  corvette_db_1
48cb9cc1ef7d        docksal/ssh-agent:1.0          "/run.sh ssh-agent"      19 hours ago        Up 19 hours                                                                        docksal-ssh-agent
2fb3cbabe61b        docksal/dns:1.0                "/opt/entrypoint.s..."   19 hours ago        Up 19 hours               192.168.64.100:53->53/udp                                docksal-dns
2b924237d344        docksal/vhost-proxy:1.1        "docker-entrypoint..."   19 hours ago        Up 19 hours               192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.1.28r117968

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       192.168.25.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/les.peabody/Sites/corvette on /mnt/sda1/var/lib/docker/volumes/corvette_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/les.peabody/Sites/sensata on /mnt/sda1/var/lib/docker/volumes/sensata_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.3G      4.6G     39.2G  11% /mnt/sda1

███  RAM Usage
             total       used       free     shared    buffers     cached
Mem:       2050284    1705816     344468     129472      37072     527480
-/+ buffers/cache:    1141264     909020
Swap:      1443772    1438912       4860

███  RAM Usage per container
CONTAINER              CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
corvette_varnish_1     0.43%               2.504MiB / 1.955GiB   0.13%               1.31kB / 0B         23MB / 1.62MB       220
corvette_web_1         0.13%               4.812MiB / 1.955GiB   0.24%               505kB / 3.82MB      6.14MB / 0B         109
corvette_cli_1         0.02%               60.5MiB / 1.955GiB    3.02%               186MB / 149MB       109MB / 11.2MB      5
sensata_varnish_1      0.42%               2.492MiB / 1.955GiB   0.12%               1.07kB / 0B         27.3MB / 381kB      220
sensata_web_1          0.09%               4.168MiB / 1.955GiB   0.21%               107kB / 450kB       5.01MB / 0B         109
sensata_memcached_1    0.01%               556KiB / 1.955GiB     0.03%               1.67kB / 0B         471kB / 0B          7
sensata_db_1           0.04%               74.06MiB / 1.955GiB   3.70%               95.9MB / 123MB      50.5MB / 1.04GB     23
sensata_solr_1         0.09%               151.6MiB / 1.955GiB   7.57%               13kB / 9.54kB       95.1MB / 16.7MB     39
sensata_cli_1          0.02%               17.44MiB / 1.955GiB   0.87%               128MB / 96MB        178MB / 56.2MB      5
corvette_solr_1        0.13%               12.39MiB / 1.955GiB   0.62%               3.1kB / 0B          22.3MB / 81.9kB     37
corvette_memcached_1   0.01%               284KiB / 1.955GiB     0.01%               3.19kB / 0B         1.59MB / 0B         7
corvette_db_1          0.05%               440.5MiB / 1.955GiB   22.00%              1.24GB / 817MB      160MB / 10.6GB      23
docksal-ssh-agent      0.00%               664KiB / 1.955GiB     0.03%               2.65kB / 0B         9.39MB / 0B         2
docksal-dns            0.11%               8.336MiB / 1.955GiB   0.42%               39.4kB / 58.4kB     25.7MB / 0B         10
docksal-vhost-proxy    0.12%               14.7MiB / 1.955GiB    0.73%               17.4MB / 17.1MB     58.5MB / 1.52MB     12

  ```

</details>
