### ISSUE TITLE
Cannot use left arrow key from drush php

### ISSUE THREAD

**Issue by MKorostoff** [docksal/docksal#367]
**Description**

When you give the command `fin drush php` the [Psy shell](http://psysh.org/) opens.  However, when you use the left arrow key, it does not move the cursor around.  Instead, it prints that characters `^[[D` on screen.

**How it should work:**
![printr2](https://user-images.githubusercontent.com/1197335/30930601-27720a94-a390-11e7-8197-7b69d40b8d28.gif)

**How it actually works:**
![printr](https://user-images.githubusercontent.com/1197335/30930496-df6404dc-a38f-11e7-85a8-7452286ebebb.gif)

**Steps to reproduce the issue:**

1. From within your drupal docroot, give the command `fin drush php`
2. See that the Psy shell opens
3. Type some text
4. Push the left arrow key
5. See that the cursor does not move to the left, but instead prints the characters `^[[D`

**Describe the results you received:**

Terminal prints out `^[[D` each time the left arrow key is pressed.

**Describe the results you expected:**

That the cursor would move to the left when I push the left arrow key.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: nbcolympicslocal
COMPOSE_FILE:
/Users/matt/.docksal/stacks/volumes-bind.yml
/Users/matt/.docksal/stacks/stack-default.yml
ENV_FILE:
/Users/matt/Sites/nbcolympics.local/.docksal/docksal.env

PROJECT_ROOT: /Users/matt/Sites/nbcolympics.local
DOCROOT: docroot
VIRTUAL_HOST: oly.docksal
VIRTUAL_HOST_ALIASES: *.oly.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32769

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      HOST_GID: '20'
      HOST_UID: '503'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.1-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 03306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/matt/Sites/nbcolympics.local
      io.docksal.virtual-host: oly.docksal,*.oly.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /Users/matt/Sites/nbcolympics.local
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin Matts-MBP-3.fios-router.home 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
Mac OS X 10.12.6
fin version: 1.22.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.06.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.12.0, build 45c69ad
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/vhost-proxy   1.1                 898fb21e7f2d        8 weeks ago         158MB
docksal/cli           1.3-php7            1442dc481915        2 months ago        752MB
docksal/db            1.1-mysql-5.6       6feb79af9597        2 months ago        298MB
docksal/cli           1.2-php7            aef362412c9f        5 months ago        787MB
memcached             latest              a5cffa71b5af        6 months ago        83.7MB
wernight/ngrok        latest              de17e6990f7b        6 months ago        26.7MB
busybox               latest              00f017a8c2a6        6 months ago        1.11MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        6 months ago        164MB
docksal/cli           1.1-php7            bdac44fe25f1        6 months ago        777MB
docksal/cli           1.1-php5            1d82105244d1        6 months ago        834MB
docksal/cli           php7                11437672cdfc        6 months ago        777MB
docksal/dns           1.0                 20c7a535479d        8 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        8 months ago        12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        8 months ago        188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        8 months ago        255MB
docksal/cli           1.0-php5            bde35eb43ad7        8 months ago        801MB
mailhog/mailhog       latest              b1ce818de155        8 months ago        18.9MB
docksal/cli           stable              87fa37d69264        9 months ago        804MB
docksal/solr          1.0-solr4           fa6b236caf06        9 months ago        546MB
docksal/varnish       1.0-varnish4        35dae6b91ff9        9 months ago        99.5MB
docksal/apache        2.2-stable          f478c360dd98        12 months ago       201MB
docksal/mysql         5.5                 98fbd291860c        12 months ago       325MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
a8d9e2df8340        docksal/web:1.0-apache2.2   "/opt/startup.sh a..."   3 hours ago         Up 3 hours          80/tcp, 443/tcp                                          nbcolympicslocal_web_1
6038d964db9d        docksal/cli:1.1-php5        "/opt/startup.sh g..."   3 hours ago         Up 3 hours          22/tcp, 9000/tcp                                         nbcolympicslocal_cli_1
dedc314396ea        docksal/db:1.0-mysql-5.5    "/entrypoint.sh my..."   3 hours ago         Up 3 hours          0.0.0.0:32769->3306/tcp                                  nbcolympicslocal_db_1
201ef84a87f5        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      6 weeks ago         Up 6 days                                                                    docksal-ssh-agent
c0dca146de88        docksal/dns:1.0             "/opt/entrypoint.s..."   6 weeks ago         Up 6 days           192.168.64.100:53->53/udp                                docksal-dns
afc74bfcb279        docksal/vhost-proxy:1.1     "docker-entrypoint..."   6 weeks ago         Up 6 days           192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.22r115126
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.10.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.88.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

███  NFS EXPORTS





# VAGRANT-BEGIN: 503 3a8891c7-7709-4aaa-bf5f-33043da335cd
"/private/var/www/amd" 192.168.88.88 -alldirs -mapall=503:0
# VAGRANT-END: 503 3a8891c7-7709-4aaa-bf5f-33043da335cd
# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/d1110b2f3ae4214043a873137b9a1fe9c00c90522c43d29d587475c78ffa03bc type aufs (rw,relatime,si=9936e39e6410faa4,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/f3c577b906daa4ada9c8459860cca85e8c6c5e068c8c0733d9abc8e2e1d49293 type aufs (rw,relatime,si=9936e39e64318aa4,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/d2a7802257eda99035b527c528ce023688baa8f004580fd8603fd39ada159b1f type aufs (rw,relatime,si=9936e39e65a5caa4,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/201ef84a87f5f335a1b9ba5d077c592a7aed3721e7b2555b5dfe90ab23a4df7a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/30cdafc00148 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/afc74bfcb279c0126c8f2c20f15b641c2d16f89eddbea04a11fa035bd9c72529/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/c0dca146de88c51f7731cab43a54730e99fd4823743ee12c0e6be9261033525f/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/736a6b86a7df type nsfs (rw)
nsfs on /var/run/docker/netns/b5ee7fb791bd type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/33980ce1979ca6e86fc30abf28617477368ac162fdd804b849e4d0fe01c5df6c type aufs (rw,relatime,si=9936e39e66627aa4,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/d563e48e1bd588f3386d217e46586e01f128f608c3794560db9464fd60bf8fca type aufs (rw,relatime,si=9936e39e6663faa4,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/6038d964db9de76f2de8618fa01e9b618cfbf7195419282fb0653665eb94dc17/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/matt/Sites/nbcolympics.local on /mnt/sda1/var/lib/docker/volumes/nbcolympicslocal_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
shm on /mnt/sda1/var/lib/docker/containers/dedc314396eae2515843e07ca180c55a25936ef30fec3f4cfe11ae9f46b8a462/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/607d292ee70b type nsfs (rw)
nsfs on /var/run/docker/netns/0e9e556d5bce type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/3bcb01e604755d89e1c0a0f3f50c483966625b3285134dfb23920a616a8ec4e1 type aufs (rw,relatime,si=9936e39e66702aa4,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/a8d9e2df83403d70695e6a729f71730a4495a1150ccad465325d3ca136f48827/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/2f5ddd6c2c91 type nsfs (rw)

  ```

</details>
