### ISSUE TITLE
Project not mounting to CLI

### ISSUE THREAD

**Issue by sean-e-dietrich** [docksal/docksal#369]
**Description**
When starting a project the project code does not mount to the cli container. 

**Steps to reproduce the issue:**

On the host machine. Navigate into the project and into a subdirectory and run any sort of fin command that will interact with the project.

**Describe the results you received:**

When I am in any directory other then the project root and attempt to run fin commands I get a no such file or directory error

```
fin exec whoami
bash: cd: web: No such file or directory
```

Additionally, other commands do not work either.

```
fin exec “gulp sass”
bash: cd: web/themes/custom/support: No such file or directory
```

When running `fin bash` in the project root I am fine and actually ssh into the container. The issue is that when running `ls -la` I don't see any of the project has been brought over.

**Describe the results you expected:**

This does work on a different machine with no issues so expect the project to mount to the container and be usable.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: kanopisupport
COMPOSE_FILE:
/Users/Caryn/.docksal/stacks/volumes-bind.yml
/Users/Caryn/.docksal/stacks/stack-default.yml
/Users/Caryn/Sites/kanopi-support/.docksal/docksal.yml
ENV_FILE:
/Users/Caryn/Sites/kanopi-support/.docksal/docksal.env
/Users/Caryn/Sites/kanopi-support/.docksal/docksal-local.env
PROJECT_ROOT: /Users/Caryn/Sites/kanopi-support
DOCROOT: web
VIRTUAL_HOST: kanopi-support.docksal
VIRTUAL_HOST_ALIASES: *.kanopi-support.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32777
Docker Compose configuration
---------------------
services:
  behat:
    entrypoint: top -b
    hostname: behat
    image: docksal/behat
    volumes:
    - /Users/Caryn/Sites/kanopi-support/tests/behat:/src:rw
  browser:
    hostname: browser
    image: selenium/standalone-chrome
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: web
      HOST_GID: ‘20’
      HOST_UID: ‘501’
      XDEBUG_ENABLED: ‘0’
    hostname: cli
    image: docksal/cli:1.3-php7
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - /Users/Caryn/Sites/kanopi-support/db:/docker-entrypoint-initdb.d:ro
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/web
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/Caryn/Sites/kanopi-support
      io.docksal.virtual-host: kanopi-support.docksal,*.kanopi-support.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: ‘2.1’
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /Users/Caryn/Sites/kanopi-support
      o: bind
      type: none
---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin Caryns-MacBook-Pro-2.local 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64
Mac OS X 10.13
fin version: 1.27.0
Mode:  VirtualBox VM
███  INSTANCES
NAME       ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal    *        virtualbox   Running   tcp://192.168.64.100:2376           v17.06.0-ce   
Kalabox2   -        virtualbox   Stopped                                       Unknown       
███  DOCKER
DOCKER_HOST:    tcp://192.168.64.100:2376
Docker: Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64
Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.12.2, build 9371605
███  DOCKER: IMAGES
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
selenium/standalone-chrome   latest              a2d37ef3ac86        4 days ago          915MB
docksal/cli                  edge-php7           75890dfb6eb2        8 days ago          793MB
docksal/cli                  1.3-php7            19bdddfeab89        10 days ago         759MB
docksal/web                  2.1-apache2.4       32c1d32eba6d        5 weeks ago         87.5MB
docksal/vhost-proxy          1.1                 898fb21e7f2d        2 months ago        158MB
docksal/db                   1.1-mysql-5.6       6feb79af9597        2 months ago        298MB
docksal/dns                  1.0                 20c7a535479d        8 months ago        61.6MB
docksal/ssh-agent            1.0                 148220cc033d        8 months ago        12.2MB
docksal/behat                latest              4cbe834cc4d3        12 months ago       88MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                  PORTS                                                    NAMES
6e25ed1a6c82        docksal/web:2.1-apache2.4    “httpd-foreground”       17 hours ago        Up 17 hours             80/tcp, 443/tcp                                          kanopisupport_web_1
6cc44dcec6c9        docksal/cli:1.3-php7         “/opt/startup.sh s...”   17 hours ago        Up 17 hours (healthy)   22/tcp, 9000/tcp                                         kanopisupport_cli_1
e5516ffd3d3b        selenium/standalone-chrome   “/opt/bin/entry_po...”   17 hours ago        Up 17 hours             4444/tcp                                                 kanopisupport_browser_1
0ad32ed9d8de        docksal/behat                “top -b”                 17 hours ago        Up 17 hours                                                                      kanopisupport_behat_1
7bb4dc3e9e1b        docksal/db:1.1-mysql-5.6     “/entrypoint.sh my...”   17 hours ago        Up 17 hours             0.0.0.0:32777->3306/tcp                                  kanopisupport_db_1
cfe83dcf606a        docksal/ssh-agent:1.0        “/run.sh ssh-agent”      17 hours ago        Up 17 hours                                                                      docksal-ssh-agent
a7c0078341b2        docksal/dns:1.0              “/opt/entrypoint.s...”   17 hours ago        Up 17 hours             192.168.64.100:53->53/udp                                docksal-dns
648a85fde7d3        docksal/vhost-proxy:1.1      “docker-entrypoint...”   17 hours ago        Up 17 hours             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.22r115126
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       1.3.3.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0
Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.44.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1
Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       192.168.35.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet2
Name:            vboxnet3
GUID:            786f6276-656e-4374-8000-0a0027000003
DHCP:            Disabled
IPAddress:       192.168.111.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:03
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet3
Name:            vboxnet4
GUID:            786f6276-656e-4474-8000-0a0027000004
DHCP:            Disabled
IPAddress:       10.13.37.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:04
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet4
Name:            vboxnet5
GUID:            786f6276-656e-4574-8000-0a0027000005
DHCP:            Disabled
IPAddress:       192.168.88.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:05
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet5
Name:            vboxnet6
GUID:            786f6276-656e-4674-8000-0a0027000006
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:06
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet6
███  NFS EXPORTS
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=1845260k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/1ebd2dec771aec5053554de91850533c36ced76d4d4d72b4701c0cb531b38555 type aufs (rw,relatime,si=29d06e8529571717,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/648a85fde7d3c637a3ea5635f15b9410f6a3b67257b7a003743d59507d3d161c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/d17125d6693f type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/c6c61f7c3e9ef9af4cffca96bfb2f3f74df407d31ae3cb265056cc02cf33ea75 type aufs (rw,relatime,si=29d06e853f18e717,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/a7c0078341b2300ab8a8b231dfdf9a0c43323c11072d65594c23dbd3799ef870/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/e2d3adfcf709 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/7d5e4222a82e53502a35fc4c2ffdb38948e431221ac894fc2f91c4c5528fbb3d type aufs (rw,relatime,si=29d06e8529658717,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/cfe83dcf606a8b2208e56fcf7fd2d46dbefaf1f88d6110324f24d2c32236b56d/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/c51f1ec7f96a type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/89dd33893a3c61dc2f209323eebb59c5857bedb73c89fbbaf3e04143a9ba8302 type aufs (rw,relatime,si=29d06e8529f52717,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/4e128c2ff9ba0331ba9be1c64c99217258d2f51a621b1102448c8387f812958a type aufs (rw,relatime,si=29d06e853f179717,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/5b54b5805ebf1ea0fd6b288654521b205188840a4e62c94ecfb629818843029f type aufs (rw,relatime,si=29d06e8522332717,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/e5516ffd3d3b6c4f9696cc08fe2dbf08bf646dfedecc2c44cf2b09b907913e4f/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/0ad32ed9d8de3a0b90c819e42415b91ba846eb6f99f8543ccca20085fb800c66/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/7bb4dc3e9e1b8937d0b96b03f4b01e2451526a0c6e27de0389d8f24646ed6172/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
tmpfs on /mnt/sda1/var/lib/docker/volumes/kanopisupport_project_root/_data type tmpfs (rw,relatime,size=1845260k)
nsfs on /var/run/docker/netns/32fc07677720 type nsfs (rw)
nsfs on /var/run/docker/netns/bd6eb4ce9ca6 type nsfs (rw)
nsfs on /var/run/docker/netns/badbccdabd33 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/eff7fe047c0969f9d7269fe94d272aad4066b956f7a223b17d02cee3b8a10102 type aufs (rw,relatime,si=29d06e855fc66717,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/6cc44dcec6c96a169950338e4a560e0193a96e7f36b15005a832c16773556542/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/1c82702a6ea9 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/016d861c55f4b44dc8823207a3b1e1828256b5f24ecee3b37b15c44218e43081 type aufs (rw,relatime,si=29d06e853d5ba717,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/6e25ed1a6c82be7bf205711a88546e64b8ff7ea6a5e9337834d43fb7eaee1f47/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/14fdc5ad113e type nsfs (rw)
  ```

</details>
