### ISSUE TITLE
How to develop node app?

### ISSUE THREAD

**Issue by ygerasimov** [docksal/docksal#370]
I am planning to build front-end app based on vuejs.

One of the ways is to have nodejs and have "npm run dev" that creates webserver on 8080 port. See some instruction https://vue-loader.vuejs.org/en/start/setup.html.

I know cli container has node (even older version). But how to add tunelling 8080 port so development can be done in "node way"?

**Comment by achekulaev** [comment]
**docksal.yml**

```yml
version: "2.1"
  services:
    cli:
      ports:
        - "YOUR_LOCALHOST_PORT:8080"
```
