### ISSUE TITLE
Drush debug not working

### ISSUE THREAD

**Issue by ssudhak** [docksal/docksal#375]
drush debug is not working for me. i use php storm for debugging.

i have updated the cli container details as below

  cli:
    volumes:
      # Sites volume
      - project_sites:/sites:rw
    environment:
      - XDEBUG_ENABLED=1
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=192.168.64.1
      - PHP_IDE_CONFIG=serverName=jmc.docksal

there is something happening when i trigger drush commands.
some error like "cant find source position, server with jmc.docksal does'nt exist".
i am using a multi site set up. and have a subsite defined like "janssenemenavd2.jmc.docksal"
i had tried changing servername to values given in the root docksal.yml also. but no luck

values tried so far.
1. jmc.docksal
2. *.jmc.docksal
3. janssenemenavd2.jmc.docksal
4. demo.jmc.docksal

Not sure what all details can be given, let me know if any more details are required.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
DOCROOT: docroot
VIRTUAL_HOST: jmc.docksal,*.jmc.docksal
VIRTUAL_HOST_ALIASES: *.jmc.docksal,*.jmc.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32778

Docker Compose configuration
---------------------
services:
  browser:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: browser
    image: selenium/standalone-chrome-debug
    ports:
    - 4451/tcp
    - 5907:5907/tcp
    volumes:
    - project_root:/var/www:rw
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '502'
      PHP_IDE_CONFIG: serverName=jmc.docksal
      XDEBUG_CONFIG: idekey=PHPSTORM remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:1.0-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_sites:/sites:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: janssenemenavd2
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 03306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached:1.4-alpine
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/a251267/Sites/janssenemeavd2
      io.docksal.virtual-host: jmc.docksal,*.jmc.docksal,*.jmc.docksal,*.jmc.docksal
    volumes:
    - project_sites:/sites:ro
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /Users/a251267/Sites/janssenemeavd2
      o: bind
      type: none
  project_sites:
    driver: local
    driver_opts:
      device: /Users/a251267/Sites/janssenemeavd2/../../sites
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin 02HW030478.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
Mac OS X 10.12.6
fin version: 1.26.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.06.0-ce
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.12.0, build 45c69ad
███  DOCKER: IMAGES
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
selenium/standalone-chrome-debug   latest              b1704317205b        2 months ago        936MB
docksal/vhost-proxy                1.1                 898fb21e7f2d        2 months ago        158MB
memcached                          1.4-alpine          273374b463b8        3 months ago        7.68MB
docksal/dns                        1.0                 20c7a535479d        9 months ago        61.6MB
docksal/ssh-agent                  1.0                 148220cc033d        9 months ago        12.2MB
docksal/web                        1.0-apache2.2       a9c03f8a5f0f        9 months ago        188MB
docksal/db                         1.0-mysql-5.5       9fb8c0aed5fc        9 months ago        255MB
docksal/cli                        1.0-php5            bde35eb43ad7        9 months ago        801MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                                                                 NAMES
325bd962a44e        docksal/web:1.0-apache2.2          "/opt/startup.sh a..."   16 minutes ago      Up 16 minutes       80/tcp, 443/tcp                                                       janssenemeavd2_web_1
b8fe3e5c60c3        docksal/cli:1.0-php5               "/opt/startup.sh g..."   16 minutes ago      Up 16 minutes       22/tcp, 9000/tcp                                                      janssenemeavd2_cli_1
9789726b7d96        memcached:1.4-alpine               "docker-entrypoint..."   2 days ago          Up 16 minutes       11211/tcp                                                             janssenemeavd2_memcached_1
556ec0ade8ba        docksal/db:1.0-mysql-5.5           "/entrypoint.sh my..."   2 days ago          Up 16 minutes       0.0.0.0:32778->3306/tcp                                               janssenemeavd2_db_1
67fe04648313        selenium/standalone-chrome-debug   "/opt/bin/entry_po..."   2 days ago          Up 16 minutes       4444/tcp, 5900/tcp, 0.0.0.0:5907->5907/tcp, 0.0.0.0:32779->4451/tcp   janssenemeavd2_browser_1
a891fae77c0f        docksal/web:1.0-apache2.2          "/opt/startup.sh a..."   10 days ago         Up 16 minutes       80/tcp, 443/tcp                                                       jcr_web_1
da688b466ed3        docksal/cli:1.0-php5               "/opt/startup.sh g..."   10 days ago         Up 16 minutes       22/tcp, 9000/tcp                                                      jcr_cli_1
273d7582fd44        selenium/standalone-chrome-debug   "/opt/bin/entry_po..."   10 days ago         Up 16 minutes       4444/tcp, 5900/tcp, 0.0.0.0:5906->5906/tcp, 0.0.0.0:32776->4450/tcp   jcr_browser_1
6b96b26c653d        docksal/db:1.0-mysql-5.5           "/entrypoint.sh my..."   10 days ago         Up 16 minutes       0.0.0.0:32777->3306/tcp                                               jcr_db_1
b3a2743fa9b0        docksal/ssh-agent:1.0              "/run.sh ssh-agent"      2 months ago        Up 16 minutes                                                                             docksal-ssh-agent
5edfc05bf1de        docksal/dns:1.0                    "/opt/entrypoint.s..."   2 months ago        Up 16 minutes       192.168.64.100:53->53/udp                                             docksal-dns
8ca4b2b24b79        docksal/vhost-proxy:1.1            "docker-entrypoint..."   2 months ago        Up 16 minutes       192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp                docksal-vhost-proxy
███  VIRTUALBOX
5.1.22r115126
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=1845260k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/c950188b196c5eb01668eb09e35f43ee998f788b0fb1b8ed3efd90d7bce4cd80 type aufs (rw,relatime,si=8334733b3dfd4ead,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/a6bc5cdad00fffccac56c953867090e9ca0b0902c57610ff18089dc6350fada2 type aufs (rw,relatime,si=8334733b3dfdaead,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/b3a2743fa9b04618260a77bbbcb98434daa5a27810a3ea10f69b90d4b14d825e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/695cfb345d62 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/8ca4b2b24b790048ee6a785975c3b15ad9b06f47d24a3e2df06141fe3736c075/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/5edfc05bf1de3776353fa9bd5c61702afd58f232b84d8209318c7f3b9342103c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/88a75ae0eb33 type nsfs (rw)
nsfs on /var/run/docker/netns/52501f60b1cb type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/caf0b04a9637b6ad9d486a0e719dd6262a018507e56f6273a37a5f2327d8ab73 type aufs (rw,relatime,si=8334733b3df66ead,dio,dirperm1)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
shm on /mnt/sda1/var/lib/docker/containers/da688b466ed3681738db83e7a25cea1d0f0ab4be313fb074442f6687e528e557/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/a251267/sites/jcr on /mnt/sda1/var/lib/docker/volumes/jcr_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/d3d52f5cf7f9 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/4a3b2ea469c37baea62f4298e0ea22579727a79d9170cd8a0f6670eb68cc18b6 type aufs (rw,relatime,si=8334733b3c23cead,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/273d7582fd44dc4df666546e0b68f028a66928dd08a8d434d4802d7b4518dd38/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/e6114f716e63 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/0c9f42929b3e67d5753ce5b47193dbfefb4554873f93137d399d8d477ceba70a type aufs (rw,relatime,si=8334733b3f915ead,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/6b96b26c653dd25810ec0f6d5913a76510ba7f7335af101ee3ad42f3e5134e5b/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/8263cf709f88 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/5575042ec15e374029f6b2e98131068a9dcfb819b984ea2ae383cf2e907d1125 type aufs (rw,relatime,si=8334733b3d8adead,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/a891fae77c0f997407e2a7864b650b3459889999a4e8bb738a110f7e937be259/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/c1d25a6ff2d2 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/f3090127c00a06fc052704f0757918f3d97a36aadbcb1b14a69063955634eddc type aufs (rw,relatime,si=8334733b1f48eead,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/53f2c02cc4b9812462e6df8795a5dd1e688cae676da3d8b22c7ca7665da6ad46 type aufs (rw,relatime,si=8334733b3f096ead,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/3cd2e49bed9a726371fc24bbce210c3fd9ac5c7cbc8bb4960e686db323fbae52 type aufs (rw,relatime,si=8334733b12181ead,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/9789726b7d960963e78ce0773c26b52dd933cf40d4bd1f72800ba932c9fe5a4c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/44ee914e54fb type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/556ec0ade8ba6a79f1175f96bce2911ff1a3bc506b12d4729723f0ed334db26a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/a251267/sites/janssenemeavd2 on /mnt/sda1/var/lib/docker/volumes/janssenemeavd2_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/ac0508b6d314cc70921409f9a74f80d81dfe52e3f6567479e82b49ef4b9144fb type aufs (rw,relatime,si=8334733b12010ead,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/b8fe3e5c60c334298232851ab45aea7153f2711b3ccbb32b5d6f73b137a7820c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/a251267/sites on /mnt/sda1/var/lib/docker/volumes/janssenemeavd2_project_sites/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/ff2de4aa4d40 type nsfs (rw)
nsfs on /var/run/docker/netns/d81c885b3069 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/67fe046483132d3dac761e58353ce60e1f7562f7c6cc0e1a7869229cd5dd2f7b/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/1759940d49bb type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/401a38ad3ac95a513d162112165c492a5399b57670506fa90ac5d43148e6cb84 type aufs (rw,relatime,si=8334733b01797ead,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/325bd962a44e821731055cce6ddc204c7431bd2fcbdf1a789bd7717ca4aae12f/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/44e5e6925809 type nsfs (rw)
  ```

</details>
