### ISSUE TITLE
Extending Stock Docksal Images Does Not Work on Windows

### ISSUE THREAD

**Issue by vaza18** [docksal/docksal#398]
Hello, I have created custom extended CLI image as per instructions from here: [Extending stock images - Docksal Documentation](http://docksal.readthedocs.io/en/master/advanced/extend-images/#configuration-docksalyml).
My docksal.yml contains this config:
```
services:
  cli:
    image: ${COMPOSE_PROJECT_NAME_SAFE}_cli
    build: ${PROJECT_ROOT}/.docksal/services/cli
```
It worked perfectly on Linux but did not work on Windows 10 returning me the following error:
`build path C:\d\project_path\project_x\.docksal\services\cli either does not exist, is not accessible, or is not a valid URL.`
![image](https://user-images.githubusercontent.com/3902392/33129434-81f8a69c-cf98-11e7-84fc-617c7183aa5c.png)

**Comment by vaza18** [comment]
I found solution how to make extended Docksal image compatible between platforms:
![image](https://user-images.githubusercontent.com/3902392/33129501-be56b854-cf98-11e7-8671-4dbbfb50eb7a.png)

in docksal.env add:
```
# Path to custom CLI Container.
# Please keep it as is for compatibility with Windows.
CLI_DOCKER_FILE="$( get_project_path )/.docksal/services/cli"
is_windows && CLI_DOCKER_FILE="$( cygpath -w $( get_project_path ) )\.docksal\services\cli"
```
in docksal.yaml use:
```
  cli:
    hostname: cli
    image: ${COMPOSE_PROJECT_NAME_SAFE}_cli
    build: ${CLI_DOCKER_FILE}
```

**Comment by achekulaev** [comment]
fin 1.48.0 will allow to use path relative to the project root. There will not be a need in hack anymore.

```
services:
  cli:
    image: ${COMPOSE_PROJECT_NAME_SAFE}_cli
    build: .docksal/services/cli
```
