### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by attiks** [docksal/docksal#406]
Add redis docker image and support for local config file

Docker image at https://hub.docker.com/_/redis/

**Comment by attiks** [comment]
Did a quick manual test

in `docksal-local.yml` add
```
version: "2.1"

services:
  redis:
    hostname: redis
    image: redis:3.2.11
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
```
in `settings.local.php` add

```
  $conf['redis_client_interface'] = 'PhpRedis'; // Can be "Predis".
  $conf['redis_client_host']      = 'redis';  // Your Redis instance hostname.
  $conf['lock_inc']               = 'sites/all/modules/contrib/redis/redis.lock.inc';
  $conf['path_inc']               = 'sites/all/modules/contrib/redis/redis.path.inc';
  $conf['cache_backends'][]       = 'sites/all/modules/contrib/redis/redis.autoload.inc';
  $conf['cache_default_class']    = 'Redis_Cache';

```

Works like a charm

**Comment by achekulaev** [comment]
So looks like the default image provided by Redis works fine. What does "support for local config file" mean?

**Comment by attiks** [comment]
a way to override the redis config options in case somebody wants to change them, like is done for php.ini

Probably something like
`.docksal/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf`

**Comment by lmakarov** [comment]
I don't think it's worth maintaining our own version of the redis image(s).

If there is a need for custom configuration, then there are several options available.

1. Via `docksal.yml` and a custom config file (`.docksal/etc/redis/redis.conf`)

```yml
version: "2.1"

services:
  redis:
    hostname: redis
    image: redis:4.0-alpine
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
```

2. By [extending](https://docs.docksal.io/en/master/advanced/extend-images/) the stock image 

    This would probably be an overkill

3. Via env variables using [wodby/redis](https://github.com/wodby/redis) image

```yml
version: "2.1"

services:
  redis:
    hostname: redis
    image: wodby/redis:4.0
    environment:
      - REDIS_MAXMEMORY=256m
```

I'm going to mark this as a documentation effort.
