### ISSUE TITLE
ELOOP: too many symbolic links encountered, scandir

### ISSUE THREAD

**Issue by joncjordan** [docksal/docksal#408]
**Description**

Folders are not syncing between my local and the container. 

**Steps to reproduce the issue:**

1. fin drush en twilio

**Describe the results you received:**

Folder shows up on my local but I can't see it when I fin bash. Also, when I fin bash, I get the following error:

Error: ELOOP: too many symbolic links encountered, scandir '/var/www/docroot/sites/all/modules/contrib'
    at Error (native)
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/home/docker/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/utils/error-handler.js:213:17)
    at /home/docker/.nvm/versions/node/v6.10.3/lib/node_modules/npm/bin/npm-cli.js:83:20
    at cb (/home/docker/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/npm.js:215:22)
    at /home/docker/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/npm.js:253:24
    at /home/docker/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (native)
    at /home/docker/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/config/core.js:80:13
    at f (/home/docker/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at /home/docker/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/config/core.js:110:20
    at /home/docker/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/config/load-prefix.js:48:7
/home/docker/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/utils/error-handler.js:213
  if (npm.config.get('json')) {
                ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/home/docker/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/utils/error-handler.js:213:17)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:297:26)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v6.10.3 --silent` to unset it.

**Describe the results you expected:**

I expected the folder to show up when I was in fin bash.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: national
COMPOSE_FILE:
/Users/joncjordan/.docksal/stacks/volumes-bind.yml
/Users/joncjordan/projects/national/.docksal/docksal.yml
ENV_FILE:
/Users/joncjordan/projects/national/.docksal/docksal.env

PROJECT_ROOT: /Users/joncjordan/projects/national
DOCROOT: docroot
VIRTUAL_HOST: national.docksal
VIRTUAL_HOST_ALIASES: *.national.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.7
    ports:
    - 3306/tcp
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.national.docksal
    user: root
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.0-apache2.2
    labels:
      io.docksal.project-root: /Users/joncjordan/projects/national
      io.docksal.virtual-host: national.docksal,*.national.docksal,national-insurance.docksal,singlesourcesolution.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /Users/joncjordan/projects/national
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin Jons-MacBook-Pro.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
Mac OS X 10.13.1
fin version: 1.27.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.06.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.12.2, build 9371605
███  DOCKER: IMAGES
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
docksal/backstopjs           latest              b943a42c70b6        2 months ago        700MB
selenium/standalone-chrome   latest              c794bdb3d03c        2 months ago        913MB
docksal/web                  2.0-apache2.2       f5675d46dd96        3 months ago        81MB
docksal/vhost-proxy          1.1                 898fb21e7f2d        4 months ago        158MB
docksal/cli                  1.3-php7            1442dc481915        4 months ago        752MB
docksal/cli                  1.3-php5            77f9a2e141fa        4 months ago        808MB
docksal/db                   1.1-mysql-8.0       0d856a3ae270        4 months ago        266MB
docksal/db                   1.1-mysql-5.7       8d323c436c28        4 months ago        412MB
docksal/db                   1.1-mysql-5.5       aa748dc21dd4        4 months ago        256MB
memcached                    latest              4b6d78556a83        4 months ago        82.6MB
wernight/ngrok               latest              b8ff076d1ab1        4 months ago        26.9MB
docksal/cli                  edge-php7           d35c1b40784d        5 months ago        749MB
mailhog/mailhog              latest              669347153085        7 months ago        19.1MB
docksal/cli                  1.2-php5            11f47dc7d024        7 months ago        845MB
docksal/vhost-proxy          1.0                 2c8a8b1e62c4        9 months ago        164MB
docksal/dns                  1.0                 20c7a535479d        10 months ago       61.6MB
docksal/ssh-agent            1.0                 148220cc033d        10 months ago       12.2MB
docksal/web                  1.0-apache2.2       a9c03f8a5f0f        10 months ago       188MB
docksal/db                   1.0-mysql-5.7       35f1494f03b6        10 months ago       400MB
docksal/db                   1.0-mysql-5.6       7c932a2f6a71        10 months ago       328MB
docksal/db                   1.0-mysql-5.5       9fb8c0aed5fc        10 months ago       255MB
docksal/solr                 1.0-solr4           fa6b236caf06        11 months ago       546MB
docksal/solr                 1.0-solr3           628ee3683031        11 months ago       471MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
aaaaa5c4614c        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      12 minutes ago      Up 12 minutes                                                                      docksal-ssh-agent
433f3768067d        docksal/dns:1.0             "/opt/entrypoint.s..."   12 minutes ago      Up 12 minutes             192.168.64.100:53->53/udp                                docksal-dns
769f046084bf        docksal/vhost-proxy:1.1     "docker-entrypoint..."   12 minutes ago      Up 12 minutes             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
5444d3dfc2ec        docksal/web:2.0-apache2.2   "httpd-foreground"       4 weeks ago         Up 12 minutes             80/tcp, 443/tcp                                          national_web_1
2c11ecc4d10e        docksal/cli:1.3-php5        "/opt/startup.sh s..."   4 weeks ago         Up 12 minutes (healthy)   22/tcp, 9000/tcp                                         national_cli_1
a6e2456ab481        docksal/db:1.1-mysql-5.7    "/entrypoint.sh my..."   4 weeks ago         Up 12 minutes             0.0.0.0:32768->3306/tcp                                  national_db_1
f79680540bc0        mailhog/mailhog             "MailHog"                3 months ago        Up 12 minutes             80/tcp, 1025/tcp, 8025/tcp                               national_mail_1
███  VIRTUALBOX
5.1.22r115126
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=3641012k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/98bff4df56562fdce289d15ad8eb4e1fc6f6e17c06b31c4e5cce5ded90bb5368 type aufs (rw,relatime,si=570621b18892580e,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/769f046084bf980a6e0235f4a872e925b26cef9c9eb7677f6c5ccd3394415033/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/14cdfbf41adc type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/b4c8b4719d29a2972006173272e99508ecade05021bd92e5b79f453caaabbd02 type aufs (rw,relatime,si=570621b188f6a80e,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/433f3768067d6776429bafc40b06cc4257d33976a922fa43fdc7d77f09fba51d/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/7e80767521df type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/6565fe3df0f4f6dbf45a3b0bf5408b2aeded37e66a21450782c90319cb775190 type aufs (rw,relatime,si=570621b18958480e,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/aaaaa5c4614ceb030ae81f233eca63568eaa3ce5e5198a2c7d4d61adf831ba18/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/9ddde289765e type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/a5517462b6bd93fd2d4b2549c44777ed4dc219c5b723438cf56689dfda3fab35 type aufs (rw,relatime,si=570621b18960c80e,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/5f58d44be0a19f9c227779b5cf7c642da982c922d3d7e6b780894a427abec4cd type aufs (rw,relatime,si=570621b18841980e,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/f79680540bc003686091e492587649630ba147bc8882775ae7933f351e936e07/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/1884f3fc49e78f35dddea6446aa2807acf40beb6259822b4fdc43bd010ef6639 type aufs (rw,relatime,si=570621b04bda180e,dio,dirperm1)
nsfs on /var/run/docker/netns/8a4e79db597d type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/2c11ecc4d10ecf2a699d8fc328324755bb71229bcb6289311437cbb90beb2432/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/joncjordan/projects/national on /mnt/sda1/var/lib/docker/volumes/national_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/e9b22bb1ca45 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/a6e2456ab4815b34dcfd1edd23bcf834641e8230437cd21d9ef4e7f20f54b818/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/0fad1b16a457 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/eb2c9a9c0b54a13945ebd17e2a87adb91225f23c4816be209b539b4bb773067e type aufs (rw,relatime,si=570621b18be6f80e,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/5444d3dfc2ec924cd9bd1fb8881f52062334f29da624c672ab4abe0127daac44/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/90bf7d3d86bd type nsfs (rw)
  ```

</details>
