### ISSUE TITLE
Permission issues when updating "web" and "cli" images

### ISSUE THREAD

**Issue by ilakic** [docksal/docksal#410]
I've been trying to update one older Docksal stack... Here's docksal.yml:
```
services:
  # Web
  web:
    hostname: web
    image: docksal/web:1.0-apache2.2
    volumes:
      # Project root volume
      - project_root:/var/www:ro,nocopy
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST}
      - io.docksal.project-root=${PROJECT_ROOT}
    environment:
      - APACHE_DOCUMENTROOT=/var/www/${DOCROOT:-docroot}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    depends_on:
      - cli

  # DB
  db:
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
      - "${MYSQL_PORT_MAPPING:-3306}"
    volumes:
      # Project root volume
      - project_root:/var/www:ro,nocopy
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-default}

  # CLI
  # Used for all console commands and tools.
  cli:
    hostname: cli
    image: docksal/cli:1.0-php7
    volumes:
      # Project root volume
      - project_root:/var/www:rw
      # Shared ssh-agent socket
      - docksal_ssh_agent:/.ssh-agent:ro
    environment:
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}

```
With that setup Drupal site works great, but when I try to update to **docksal/web:2.1-apache2.4** and **docksal/cli:1.3-php7** I get all kind of permission issues. I saw that there was a change in the cli image so there are no "users" anymore (swaped with "docker") and that permissions on the root directory of the site ($DOCROOT) are 700, not 755 anymore.

I managed to fix permission issues (I guess) caused by "cli" image, I made these changes:
```
  # CLI
  # Used for all console commands and tools.
  cli:
    hostname: cli
    image: docksal/cli:1.3-php7
    volumes:
      # Project root volume
      - project_root:/var/www:rw,nocopy
      # Shared ssh-agent socket
      - docksal_ssh_agent:/.ssh-agent:ro
    environment:
     - DOCROOT
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}
```
but simply cannot update to **docksal/web:2.1-apache2.4**. Every time i try to do that I get big, fat "FORBIDDEN" message.

Can you please help me a little with this and gave some advice? I know that I'm making some dumb mistake... I can change all these permissions manually but that's doesn't make any sense because I'm sure there's another, better way to do this.

I also tried your D8 demo site but there's no docksal.yml file anymore - you're configured everything for that demo site in the docksal.env file so I couldn't compare my yml file...

Thanks in advance!

**Comment by lmakarov** [comment]
@ilakic you can always view the resulting docker-compose configuration with `fin config`.
Examples sites are using zero-configuration setup with the [default stack](https://github.com/docksal/docksal/blob/develop/stacks/stack-default.yml).

If the example site works for you without issues, then I'd recommend switching to the same model (using the default stack). You can also run `fin config generate` if you have complete control over the stack configuration (it uses [this](https://github.com/docksal/docksal/blob/develop/stacks/stack-default-static.yml) stack file).

BTW you did not post the actual error you are experiencing, so I cannot say anything to that.

**Comment by achekulaev** [comment]
@ilakic I don't see any modifications in your old `docksal.yml`. It looks pretty standard. And you say that D8 demo works for you. So instead of spending time pinpointing an issue I would recommend a different approach:

1) delete your old docksal.yml
2) create docksa.env and configure project to use the default stack via `docksal.env`:

**docksal.env**
```
DOCKSAL_STACK="default"
```

That should do it. (don't forget to `fin remove` old containers just in case).

**Comment by ilakic** [comment]
Many thanks for the prompt reply!

I've tried both propositions and I always get this warning: 
![Warning](http://i64.tinypic.com/102t34k.png)

And the result from a terminal window:
![Docksal permissions](http://i63.tinypic.com/2hia6gj.png)

And there is an added docroot directory which originates from default stack (I did define DOCROOT=web in docksal.env)

**Comment by achekulaev** [comment]
Your error says. Server unable to read .htaccess file (that's the one that should be in `docroot/.htaccess`)

**Comment by ilakic** [comment]
I've tried with this basic config and it works:
```
# Basic LAMP stack

version: "2.1"

services:
  # Web
  web:
    hostname: web
    image: docksal/web:1.0-apache2.2
    volumes:
      # Project root volume
      - project_root:/var/www:ro,nocopy
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST},*.${VIRTUAL_HOST}
      - io.docksal.project-root=${PROJECT_ROOT}
    environment:
      - APACHE_DOCUMENTROOT=/var/www/${DOCROOT:-docroot}
      - APACHE_BASIC_AUTH_USER
      - APACHE_BASIC_AUTH_PASS
    depends_on:
      - cli
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # DB
  db:
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
      - "${MYSQL_PORT_MAPPING:-3306}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-default}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # CLI
  # Used for all console commands and tools.
  cli:
    hostname: cli
    image: docksal/cli:1.3-php7
    volumes:
      # Project root volume
      - project_root:/var/www:rw,nocopy
      # Shared ssh-agent socket
      - docksal_ssh_agent:/.ssh-agent:ro
    environment:
      - HOST_UID
      - HOST_GID
      - DOCROOT
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
```
But when I try to bump docksal/web:1.0-apache2.2 to docksal/web:2.1-apache2.4, the same warning reappears... I simply cannot make a switch to another version of the web image.

UPDATE: When I made a change docksal/web:1.0-apache2.2 => docksal/web:2.1-apache2.4 and changed permissions on the "web" directory to 775, I got front page of the site without CSS... Definitely weird problem with permissions.
