### ISSUE TITLE
Character support issues in CLI

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#411]
**Description**

There seems to be character set data missing from the CLI container. Some foreign characters are not displayed properly. For example, when composer.lock gets updated, we see this in Drupal:

<img width="683" alt="corvette__git_" src="https://user-images.githubusercontent.com/419534/33494239-9d8edcce-d690-11e7-8506-5520bc9dab99.png">

**Steps to reproduce the issue:**

1. Run some composer operation via the CLI service that updates the .lock file.

**Describe the results you received:**

<img width="683" alt="corvette__git_" src="https://user-images.githubusercontent.com/419534/33494239-9d8edcce-d690-11e7-8506-5520bc9dab99.png">

**Describe the results you expected:**

I expect these author names to not be altered.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: corvette
COMPOSE_FILE:
/Users/les.peabody/.docksal/stacks/volumes-bind.yml
/Users/les.peabody/.docksal/stacks/stack-acquia.yml
/Users/les.peabody/Sites/corvette/.docksal/docksal.yml
ENV_FILE:
/Users/les.peabody/Sites/corvette/.docksal/docksal.env
/Users/les.peabody/Sites/corvette/.docksal/docksal-local.env

PROJECT_ROOT: /Users/les.peabody/Sites/corvette
DOCROOT: docroot
VIRTUAL_HOST: baxter.docksal
VIRTUAL_HOST_ALIASES: *.baxter.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DEFAULT_BUILD_THEME_PROFILE: bax_base
      DOCROOT: docroot
      HOST_GID: '1106437719'
      HOST_UID: '1729411499'
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: lpeabody/blt-cli:php7-1.3
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: solr
    image: docksal/solr:1.0-solr4
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:1.0-varnish4
    labels:
      io.docksal.virtual-host: varnish.baxter.docksal
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/les.peabody/Sites/corvette
      io.docksal.virtual-host: baxter.docksal,*.baxter.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /Users/les.peabody/Sites/corvette
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin BOSGEN-NMX0813.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
Mac OS X 10.12.6
fin version: 1.27.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   -        virtualbox   Stopped                                       Unknown       
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.06.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.12.2, build 9371605
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
lpeabody/blt-cli      php7-1.3            6df971e4d120        4 weeks ago         903MB
wernight/ngrok        latest              74fd35f6dafe        2 months ago        27.1MB
lpeabody/blt-cli      latest              1b259bc92a0f        2 months ago        932MB
docksal/cli           1.3-php7            19bdddfeab89        2 months ago        759MB
docksal/web           2.1-apache2.4       32c1d32eba6d        3 months ago        87.5MB
lpeabody/blt-cli      <none>              33518bbd76d3        3 months ago        893MB
docksal/web           2.0-apache2.4       7f75db9a6aa7        3 months ago        87.5MB
docksal/vhost-proxy   1.1                 898fb21e7f2d        4 months ago        158MB
docksal/db            1.1-mysql-5.6       6feb79af9597        4 months ago        298MB
memcached             1.4-alpine          273374b463b8        4 months ago        7.68MB
docksal/dns           1.0                 20c7a535479d        10 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        10 months ago       12.2MB
docksal/solr          1.0-solr4           fa6b236caf06        11 months ago       546MB
docksal/varnish       1.0-varnish4        35dae6b91ff9        11 months ago       99.5MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                  PORTS                                                    NAMES
bc52c03c4ca5        docksal/varnish:1.0-varnish4   "/opt/startup.sh"        21 hours ago        Up 21 hours             80/tcp                                                   corvette_varnish_1
99ed57da1b42        docksal/web:2.1-apache2.4      "httpd-foreground"       21 hours ago        Up 21 hours             80/tcp, 443/tcp                                          corvette_web_1
16faf3446c2b        lpeabody/blt-cli:php7-1.3      "/opt/startup.sh s..."   21 hours ago        Up 21 hours (healthy)   22/tcp, 9000/tcp                                         corvette_cli_1
161fd3bc932d        docksal/db:1.1-mysql-5.6       "/entrypoint.sh my..."   4 weeks ago         Up 7 days               0.0.0.0:32768->3306/tcp                                  corvette_db_1
215f91201bc3        docksal/solr:1.0-solr4         "/opt/solr/bin/sol..."   4 weeks ago         Up 7 days               8983/tcp                                                 corvette_solr_1
7f8be97dce32        memcached:1.4-alpine           "docker-entrypoint..."   4 weeks ago         Up 7 days               11211/tcp                                                corvette_memcached_1
2e8b3baa6370        docksal/ssh-agent:1.0          "/run.sh ssh-agent"      7 weeks ago         Up 7 days                                                                        docksal-ssh-agent
fd26178dbcf6        docksal/dns:1.0                "/opt/entrypoint.s..."   7 weeks ago         Up 7 days               192.168.64.100:53->53/udp                                docksal-dns
fb2301a80c5a        docksal/vhost-proxy:1.1        "docker-entrypoint..."   7 weeks ago         Up 7 days               192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.22r115126
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       192.168.25.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=2791696k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/6ea47126d64573fc1444454858750559313b7cd0813ef9997ed0f4cf89de1a49 type aufs (rw,relatime,si=f05a9959c4d2e1bc,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/fd26178dbcf6e546f0672dc39b9f77690115478dab42dc60e0fb02bc212ca365/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/ffa005340a8c1a9d0c17d451368c92a460ce560b42c82e609dc5cee0caf42f92 type aufs (rw,relatime,si=f05a9959c65071bc,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/2e8b3baa6370394bebc80c78a6fc105ab7a20e43ca3ac305278e3ac0c7bfbd64/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/fb2301a80c5ae11c73acc792c80bca47b2c99f0b1367880564e10e2197838e59/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/2174c52d6638 type nsfs (rw)
nsfs on /var/run/docker/netns/c25677f80b7f type nsfs (rw)
nsfs on /var/run/docker/netns/b6e16f215184 type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/ab2090f9f02b498920c409730528584e75f4f718fa57f1690286829f784eff43 type aufs (rw,relatime,si=f05a9959c57301bc,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/c3cea5992dba579bccbaa210d8aaf92f840cf0aef958f681046c578643eda97d type aufs (rw,relatime,si=f05a9959c75f11bc,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/c4363e94f85aad947ac89d6efdd6345266cc5ce85601dfb402bd6c01a463c1b6 type aufs (rw,relatime,si=f05a9959c59aa1bc,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/215f91201bc39471d2057e969f97d5688c03aa1495faa8335f36cb5f57422a72/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/d09de17e3fd1 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/161fd3bc932dec714504aedb87a63375d53400c95eac024458f1adacd2223564/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/les.peabody/Sites/corvette on /mnt/sda1/var/lib/docker/volumes/corvette_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
shm on /mnt/sda1/var/lib/docker/containers/7f8be97dce32762387541796645ccb396b7b5f578a19e34f3f22065b6140aa10/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/9ba9bc0ddb7c type nsfs (rw)
nsfs on /var/run/docker/netns/72f8b9e8be84 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/552e1b9f703d553423d213488fefe0992429d726eeff462b71bd60f58bb5dea7 type aufs (rw,relatime,si=f05a9959c06331bc,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/16faf3446c2bfe176390a092723e0c7fbd8a4367d8a5e44afce47f53375ad420/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/ed9ec11b6419 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/d6ae118cc74cdea620e456a325fc4037f95e3d85cb0e984d089b16351130b67a type aufs (rw,relatime,si=f05a9959c07f41bc,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/99ed57da1b422e48cae38d9898332b05037ebca62e3e180e3197b4eb77e1d732/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/12c3ebb1da35 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/4a2a5d2d225fe48639673162cd23c68e5a40322701a06540568cfa3c5021461f type aufs (rw,relatime,si=f05a99596d0281bc,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/bc52c03c4ca58539b065f0d000d28131a9c0caad00003c6f59096b4191f7d10c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/2583e2f898ea type nsfs (rw)

  ```

</details>

**Comment by lmakarov** [comment]
@lpeabody I'm not able to reproduce this with the sample docksal/drupal8 project, either with VirtualBox (NFS) or Docker for Mac (osxfs) on macOS 10.12.6.

The only way I was able to reproduce this is buy forcing `ASCII` encoding for `composer.lock`, but even after that composer resets it back to `UTF-8`.

Check the encoding settings in your Git/IDE/etc tools. I suspect the issues is there.

**Comment by achekulaev** [comment]
I created an empty project

```
14:37:51 Alexei-Workstation /Users/alexei.chekulaev/Projects/demo-composer
$ ls -la
total 0
drwxr-xr-x@  3 alexei.chekulaev  staff  102 Dec  1 14:37 .
drwxr-xr-x  26 alexei.chekulaev  staff  884 Dec  1 14:37 ..
drwxr-xr-x   2 alexei.chekulaev  staff   68 Dec  1 14:37 .docksal
```

Downloaded a single composer package

```
14:38:30 Alexei-Workstation /Users/alexei.chekulaev/Projects/demo-composer
$ fin bash
docker@cli:/var/www$ composer require symfony/css-selector
Using version ^3.4 for symfony/css-selector
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/css-selector (v3.4.0): Downloading (100%)         
Writing lock file
Generating autoload files
```

Checked for author name

```
docker@cli:/var/www$ cat composer.lock | grep Jean
                    "name": "Jean-François Simon",
```

Everything seems to be in order.

<details>
  <summary>fin config output</summary>

```
COMPOSE_PROJECT_NAME_SAFE: democomposer
COMPOSE_FILE:
/Users/alexei.chekulaev/.docksal/stacks/overrides-osxfs.yml
/Users/alexei.chekulaev/.docksal/stacks/volumes-bind.yml
/Users/alexei.chekulaev/.docksal/stacks/stack-default.yml

PROJECT_ROOT: /Users/alexei.chekulaev/Projects/demo-composer
DOCROOT: docroot
VIRTUAL_HOST: democomposer.docksal
VIRTUAL_HOST_ALIASES: *.democomposer.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '501'
      PHP_IDE_CONFIG: serverName=democomposer.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php7
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /Users/alexei.chekulaev/Projects/demo-composer:/var/www:rw,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/alexei.chekulaev/Projects/demo-composer
      io.docksal.virtual-host: democomposer.docksal,*.democomposer.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/alexei.chekulaev/Projects/demo-composer
      o: bind
      type: none
```

</details>

I see that you use your custom image for cli @lpeabody . I understand that you probably didn't change anything related however it's hard to know for sure. 

So could you repeat the steps I did (below) and tell if you still the the problem?

```
cd your_project_folder
mkdir -p demo-composer/.docksal
cd demo-composer
fin up
fin exec composer require symfony/css-selector
cat composer.lock | grep name
```
