### ISSUE TITLE
npm "onchange" not working outside of the container.

### ISSUE THREAD

**Issue by leopitt** [docksal/docksal#414]
We are using node with  node-sass to compile .scss files onchange. On my Mac OSX environment for some reason it does not respond to any changes made to files "outside" of the virtual machine.

**Steps to reproduce the issue:**

1. Run the node script: ``fin exec npm run watch:css``
2. Locate a watched .scss file in Mac OSX finder, and open it in text editor. Make a change. Save. 
3. The node script does not respond to the change.
4. Open a new terminal window. Use ``fin bash`` to enter the virtual machine.
5. use ``nano`` to edit the same watched .scss file, and save.
6. The node script does respond to the change.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: myproject
COMPOSE_FILE:
/Users/leopitt/.docksal/stacks/volumes-bind.yml
/Users/leopitt/docksal_projects/myproject/.docksal/docksal.yml
ENV_FILE:
/Users/leopitt/docksal_projects/myproject/.docksal/docksal.env

PROJECT_ROOT: /Users/leopitt/docksal_projects/myproject
DOCROOT: docroot
VIRTUAL_HOST: myproject.docksal
VIRTUAL_HOST_ALIASES: *.myproject.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      HOST_GID: '20'
      HOST_UID: '501'
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:1.3-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: myproject_db
      MYSQL_PASSWORD: myproject_pass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: myproject_user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - /Users/leopitt/docksal_projects/myproject/db:/docker-entrypoint-initdb.d:ro
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.myproject.docksal
    user: root
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.0-apache2.4
    labels:
      io.docksal.project-root: /Users/leopitt/docksal_projects/myproject
      io.docksal.virtual-host: myproject.docksal,*.myproject.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /Users/leopitt/docksal_projects/myproject
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin Leos-MacBook-Air.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Oct  2 22:20:08 PDT 2017; root:xnu-3248.71.4~1/RELEASE_X86_64 x86_64
Mac OS X 10.11.6
fin version: 1.27.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.06.0-ce   
███  DOCKER
DOCKER_HOST:  tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.12.2, build 9371605
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/cli           1.3-php5            80248f5ea845        2 months ago        814MB
docksal/web           2.0-apache2.4       7f75db9a6aa7        3 months ago        87.5MB
docksal/vhost-proxy   1.1                 898fb21e7f2d        4 months ago        158MB
docksal/db            1.1-mysql-5.6       6feb79af9597        4 months ago        298MB
mailhog/mailhog       latest              669347153085        7 months ago        19.1MB
docksal/dns           1.0                 20c7a535479d        10 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        10 months ago       12.2MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
21b595987d68        docksal/web:2.0-apache2.4   "httpd-foreground"       18 minutes ago      Up 18 minutes             80/tcp, 443/tcp                                          myproject_web_1
b4d1eff8e48f        mailhog/mailhog             "MailHog"                18 minutes ago      Up 18 minutes             80/tcp, 1025/tcp, 8025/tcp                               myproject_mail_1
fc4f419bcb08        docksal/cli:1.3-php5        "/opt/startup.sh s..."   18 minutes ago      Up 18 minutes (healthy)   22/tcp, 9000/tcp                                         myproject_cli_1
1c4fc3965c08        docksal/db:1.1-mysql-5.6    "/entrypoint.sh my..."   18 minutes ago      Up 18 minutes             0.0.0.0:32768->3306/tcp                                  myproject_db_1
279925ed37dc        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      24 minutes ago      Up 24 minutes                                                                      docksal-ssh-agent
8697e7dff425        docksal/dns:1.0             "/opt/entrypoint.s..."   24 minutes ago      Up 24 minutes             192.168.64.100:53->53/udp                                docksal-dns
70c2fc26a5b6        docksal/vhost-proxy:1.1     "docker-entrypoint..."   24 minutes ago      Up 24 minutes             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.22r115126
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       10.10.4.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=1845260k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/1074d5ef2243281b1cedacdcda854453932ee926a949d03f8c3d3178f0896658 type aufs (rw,relatime,si=86ead391a0d2483,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/70c2fc26a5b62f1972d97907709acc1e6a518f2c2874a54cd3eac68599391678/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/ef724a6e79a0 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/d12a1ae822c149c8a03d93e6e2b7d33e717c96eec3c4a7b9d5d0841512c4a110 type aufs (rw,relatime,si=86ead391a0f9483,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/8697e7dff4253018ebffb27dbed2800594eee1805541c40f2b5ebea96cc7d321/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/b010a1d79a7a type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/7b87e8f5f6fc0704ad331617da0734124fb11232e72eaee94a5f4e0a6c86cf89 type aufs (rw,relatime,si=86ead3917ce6483,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/279925ed37dc3b3984724baa8b58c92ee9ac8277c41afe01c4058e94ba9c952f/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/8af60e7f2b60 type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/3a575e915845c3129813c2f3bea826f499d3f307a13611ecf2024a3191354a59 type aufs (rw,relatime,si=86ead3915f2b483,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/fc4f419bcb08b151dc213da16081163ee8dc726e7455082c7150029e2a213967/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/leopitt/docksal_projects/myproject on /mnt/sda1/var/lib/docker/volumes/myproject_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/de33b07616ba4e413af933f8207e80e1fa3792fe70e1c9ea6adde51df1150fee type aufs (rw,relatime,si=86ead390c4e5483,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/e99e2b3018f84d1c1ed31d1ec714cc351291087b8d3afef5e7e4b0482b40f896 type aufs (rw,relatime,si=86ead391b884483,dio,dirperm1)
nsfs on /var/run/docker/netns/a432143b35d0 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/b4d1eff8e48fc26c3f9ae5eaa4fb5762b0a4a11ad70a1a7839f10e51799b5524/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/1c4fc3965c08ef6f841904ce65e02377d5038c0ca9264d7ea95b56c628990b07/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/246dc4c245d2 type nsfs (rw)
nsfs on /var/run/docker/netns/2ae67b5d94cf type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/46f45536c032c3a6e185b61ea45466751b0865103b6260733581535ff67dd04e type aufs (rw,relatime,si=86ead391af6c483,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/21b595987d683e2a2ae67e438ecc345f9a43f21340fa44376c7b78be5b8f7719/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/6a5dfd891b63 type nsfs (rw)
  ```

</details>
