### ISSUE TITLE
Services never start: linux spec user: unable to find user root

### ISSUE THREAD

**Issue by hamletta** [docksal/docksal#415]
**Description**

Can't start cli services.

**Steps to reproduce the issue:**

1. fin up/fin project create w/sample project

**Describe the results you received:**

Cli and web never start; get following error message:

ERROR: for cli  Cannot start service cli: linux spec user: unable to find user root: no matching entries in passwd file

**Describe the results you expected:**

Generic web site 

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: eight
COMPOSE_FILE:
/Users/rebeccaluxford/.docksal/stacks/volumes-bind.yml
/Users/rebeccaluxford/.docksal/stacks/stack-default.yml
ENV_FILE:
/Users/rebeccaluxford/Projects/eight/.docksal/docksal.env

PROJECT_ROOT: /Users/rebeccaluxford/Projects/eight
DOCROOT: docroot
VIRTUAL_HOST: eight.docksal
VIRTUAL_HOST_ALIASES: *.eight.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32780

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '501'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php7
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 03306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/rebeccaluxford/Projects/eight
      io.docksal.virtual-host: eight.docksal,*.eight.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /Users/rebeccaluxford/Projects/eight
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin Rebeccas-MBP.fios-router.home 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64
Mac OS X 10.12.6
fin version: 1.27.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.06.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.12.2, build 9371605
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/web           2.1-apache2.4       32c1d32eba6d        3 months ago        87.5MB
docksal/web           2.0-apache2.4       38c223f7c3f9        4 months ago        87.5MB
docksal/vhost-proxy   1.1                 898fb21e7f2d        4 months ago        158MB
docksal/cli           1.3-php7            1442dc481915        4 months ago        752MB
docksal/cli           1.3-php5            77f9a2e141fa        4 months ago        808MB
docksal/db            1.1-mysql-5.6       6feb79af9597        4 months ago        298MB
docksal/cli           1.2-php7            aef362412c9f        8 months ago        787MB
docksal/dns           1.0                 20c7a535479d        10 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        10 months ago       12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        10 months ago       188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        10 months ago       255MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                 PORTS                                                    NAMES
68dcf3a5b5cb        docksal/db:1.1-mysql-5.6    "/entrypoint.sh my..."   13 minutes ago      Up 13 minutes          0.0.0.0:32779->3306/tcp                                  tweety_db_1
0b3644719334        docksal/db:1.1-mysql-5.6    "/entrypoint.sh my..."   43 minutes ago      Up 10 minutes          0.0.0.0:32780->3306/tcp                                  eight_db_1
468b06f92ec0        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      About an hour ago   Up About an hour                                                                docksal-ssh-agent
1de59e11b930        docksal/dns:1.0             "/opt/entrypoint.s..."   About an hour ago   Up About an hour       192.168.64.100:53->53/udp                                docksal-dns
b01f2bd86eec        docksal/vhost-proxy:1.1     "docker-entrypoint..."   About an hour ago   Up About an hour       192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
7679a7ba3b03        docksal/db:1.1-mysql-5.6    "/entrypoint.sh my..."   About an hour ago   Up About an hour       0.0.0.0:32775->3306/tcp                                  nina_db_1
cae82b452921        docksal/web:2.1-apache2.4   "httpd-foreground"       2 hours ago         Up 2 hours             80/tcp, 443/tcp                                          seven_web_1
db81fd63735b        docksal/cli:1.3-php5        "/opt/startup.sh s..."   2 hours ago         Up 2 hours (healthy)   22/tcp, 9000/tcp                                         seven_cli_1
cf2268c0cfe0        docksal/db:1.1-mysql-5.6    "/entrypoint.sh my..."   7 hours ago         Up 7 hours             0.0.0.0:32770->3306/tcp                                  moore_db_1
422bc7b2debd        docksal/db:1.1-mysql-5.6    "/entrypoint.sh my..."   7 hours ago         Up 7 hours             0.0.0.0:32769->3306/tcp                                  melber_db_1
███  VIRTUALBOX
5.1.28r117968
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.81.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       192.168.86.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

███  NFS EXPORTS


# VAGRANT-BEGIN: 501 c1208c37-cfee-4b46-b4a3-a86edef12486
# VAGRANT-END: 501 c1208c37-cfee-4b46-b4a3-a86edef12486
# VAGRANT-BEGIN: 501 ff11265b-7b10-4814-90c7-457dc7d6e429
# "/Users/rebeccaluxford/work/ivan" 192.168.86.97 -alldirs -mapall=501:20
# VAGRANT-END: 501 ff11265b-7b10-4814-90c7-457dc7d6e429
# <ds-nfs docksal
/Users/rebeccaluxford/Projects 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=1845260k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/4121c9447e0a64ebd2917c26ee5dd7b7dc57eddf6d00f594a605f643141f2cff type aufs (rw,relatime,si=aaa46c3ce8ad3092,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/422bc7b2debd7801da9f9278a7f05218bad82afabfac3823b863a05160f7d23d/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/rebeccaluxford/Projects/melber on /mnt/sda1/var/lib/docker/volumes/melber_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/9520a75b0fa0 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/18ee9a67b1fd86eff74466183b82fac020ea3d8783ac4405efb096b5ec8b206e type aufs (rw,relatime,si=aaa46c3cab4d4092,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/cf2268c0cfe0e13a3fe08cdc1304d145afcf6e83ade6c06e412a898819dfcc65/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/rebeccaluxford/Projects/moore on /mnt/sda1/var/lib/docker/volumes/moore_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/98b492e880df type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/12826a350b3f49c4e4fac03b2713c276e5602b1594b019127713d89be4472e05 type aufs (rw,relatime,si=aaa46c3cccc93092,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/db81fd63735bf5292d4951fe8583981cc0354349d505820c297c09c0e80c620c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/rebeccaluxford/Projects/seven on /mnt/sda1/var/lib/docker/volumes/seven_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/40d4fef36fec type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/4246dc0b36781626e03cfba0339d3226aa26101613345e521950289adc60038b type aufs (rw,relatime,si=aaa46c3cc7cdc092,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/cae82b4529215247e69c531173952878f674df18946edd4f74f216ed9e0c6874/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/d658ba17b5a3 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/479a02c2e181868e36e7306d5ae29287b617b7eee29ff3cd4608751c4add57fd type aufs (rw,relatime,si=aaa46c3c8518a092,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/7679a7ba3b03486b4f3f5148168f585129bdaa709739f671d603cab8f12d4247/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/rebeccaluxford/Projects/nina on /mnt/sda1/var/lib/docker/volumes/nina_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/138c95d0bf48 type nsfs (rw)
192.168.64.1:/Users/rebeccaluxford/Projects on /Users/rebeccaluxford/Projects type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/ef6faf20d18a712f6ae424db465aee8d1b3d9aab60a8ab96e9c29011643aa64e type aufs (rw,relatime,si=aaa46c3cfd130092,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/b01f2bd86eec8d3c2805b8006362c64ad53e466538c50a325b2fd958a59d5147/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/895d4729817f type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/ab12d401679cc3736b5896e5e838489be3cbb95c4517e4a92f26c046a190b371 type aufs (rw,relatime,si=aaa46c3ce55b3092,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/1de59e11b930b65ca7460d11a0d92f5e0ba8e873d1fe4ac58882ad316e272601/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/58e43ac1933f type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/8a8b3a82c8b30c24cabab5f3ea27f46b10db9a08a865d6fa3996210f377cdc04 type aufs (rw,relatime,si=aaa46c3cea5f7092,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/468b06f92ec03e4cac3f1ab38e50d575bbea23c5c8802b3713d0a80a0196c43c/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/9d60261340b0 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/8777f17e7b51fc5006ff9d6269afdb1ea67c1f428f56d4c49dd6bcf136c151a2 type aufs (rw,relatime,si=aaa46c3ce5f46092,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/68dcf3a5b5cbd12e7154b510b691ef6d6411b4004b1aa844baaa08bc75c5084a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/rebeccaluxford/Projects/tweety on /mnt/sda1/var/lib/docker/volumes/tweety_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/6c7e4d02f3b3 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/3145488a36c399890ff8317ff549b36f131036fb7b50831b32f9892e362d390c type aufs (rw,relatime,si=aaa46c3cab578092,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/0b36447193343c08ed0971125fa3a70e49308a076115542bb64803e0c9889677/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/rebeccaluxford/Projects/eight on /mnt/sda1/var/lib/docker/volumes/eight_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
nsfs on /var/run/docker/netns/bcfcc03eeef9 type nsfs (rw)
  ```

</details>
