### ISSUE TITLE
[fin v1.41.0] Xdebug triggers on each page request (even when no breakpoints defined)

### ISSUE THREAD

**Issue by ApacheEx** [docksal/docksal#420]
Hi,
after upgrading to the newer version (v1.41.0) I've noticed that xdebug doesn't work as it was before. I think the issue can be related to these changes 9d24e39bb10a95184cc54995456904aca633668b (but not sure)

I'm using:
- PHPStorm 2017.3
- MacOS 10.13.2
- Docksal via VirtualBox (boot2docker)
- `DOCKSAL_STACK=default`

currently, it's quite hard to debug something. Any ideas?

**Comment by achekulaev** [comment]
So what is exactly the issue? Xdebug always triggers (triggers meaning works, not stops) per every page request. That's why it's best to disable it if you don't use it.

**Comment by ApacheEx** [comment]
@achekulaev 

somehow Xdebug can't stop on a breakpoint. I always see
![image](https://user-images.githubusercontent.com/1918108/33825102-30fb2e42-de69-11e7-8f02-2b0ea630384f.png)


My PHPStorm settings:
![image](https://user-images.githubusercontent.com/1918108/33825137-4fca9f7e-de69-11e7-8e1d-bd5b237aa76f.png)

**Comment by achekulaev** [comment]
@ApacheEx please post `fin config`

**Comment by ApacheEx** [comment]
<details> 
  <summary>Output for `fin config` </summary>
```
---------------------
COMPOSE_PROJECT_NAME_SAFE: yawave
COMPOSE_FILE:
/Users/apacheex/.docksal/stacks/volumes-bind.yml
/Users/apacheex/.docksal/stacks/stack-default.yml
/Users/apacheex/WEB/yawave/.docksal/docksal.yml
ENV_FILE:
/Users/apacheex/WEB/yawave/.docksal/docksal.env
/Users/apacheex/WEB/yawave/.docksal/docksal-local.env

PROJECT_ROOT: /Users/apacheex/WEB/yawave
DOCROOT: docroot
VIRTUAL_HOST: yawave.docksal
VIRTUAL_HOST_ALIASES: *.yawave.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:33061

Docker Compose configuration
---------------------
services:
  adminer:
    image: adminer
    labels:
      io.docksal.virtual-host: pma.yawave.docksal
    ports:
    - 8080:8080/tcp
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '501'
      PHP_IDE_CONFIG: serverName=yawave.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:1.3-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
    - /Users/apacheex/WEB/yawave-app/public:/var/www/docroot/yawave-app/public:rw
    - /Users/apacheex/WEB/yawave-sdk/build1:/var/www/docroot/yawave-sdk/build1:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.5
    ports:
    - 33061:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/apacheex/WEB/yawave
      io.docksal.virtual-host: yawave.docksal,*.yawave.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
    - /Users/apacheex/WEB/yawave-app/public:/var/www/docroot/yawave-app/public:rw
    - /Users/apacheex/WEB/yawave-sdk/build1:/var/www/docroot/yawave-sdk/build1:rw
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/apacheex/WEB/yawave
      o: bind
      type: none

---------------------
```
</details>
