### ISSUE TITLE
Containers die during long MySQL import

### ISSUE THREAD

**Issue by drubage** [docksal/docksal#426]
**Description**

I just switched to Docker for Mac instead of VirtualBox and it seems that containers are dying way more often now. I have a long running import script that dies with no error and then all of the containers are in exit state. Is there a timeout setting of some sort that might be killing those containers?

**Steps to reproduce the issue:**

1. Start a project with a large database backup.
2. Import the backup using fin sqli.
3. Backup dies and then all containers are exited.

**Describe the results you received:**

Importing database.sql...
ERROR 2013 (HY000) at line 12776: Lost connection to MySQL server during query
Import failed

Spare-Mac-Book-Pro:golfzing drew.michael$ fin status
        Name                      Command                State     Ports
------------------------------------------------------------------------
golfzing_backstop_1    top -b                           Exit 143        
golfzing_blackfire_1   blackfire-agent                  Exit 0          
golfzing_browser_1     /opt/bin/entry_point.sh          Exit 143        
golfzing_cli_1         /opt/startup.sh supervisord      Exit 137        
golfzing_db_1          /entrypoint.sh mysqld            Exit 137        
golfzing_mail_1        MailHog                          Exit 2          
golfzing_memcached_1   docker-entrypoint.sh memcached   Exit 0          
golfzing_web_1         httpd-foreground                 Exit 0          

**Describe the results you expected:**

A fully imported database. The import worked when I was using VirtualBox.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: golfzing
COMPOSE_FILE:
/Users/drew.michael/.docksal/stacks/overrides-osxfs.yml
/Users/drew.michael/.docksal/stacks/volumes-bind.yml
/Users/drew.michael/projects/golfzing/.docksal/docksal.yml
ENV_FILE:
/Users/drew.michael/projects/golfzing/.docksal/docksal.env

PROJECT_ROOT: /Users/drew.michael/projects/golfzing
DOCROOT: docroot
VIRTUAL_HOST: golfzing.docksal
VIRTUAL_HOST_ALIASES: *.golfzing.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  backstop:
    entrypoint: top -b
    hostname: backstop
    image: docksal/backstopjs
    volumes:
    - /Users/drew.michael/projects/golfzing/tests/backstop:/src:rw
  blackfire:
    environment:
      BLACKFIRE_SERVER_ID: ee03735e-4a15-4b5f-ba76-5d0bc7160dc8
      BLACKFIRE_SERVER_TOKEN: 982bdea3e43186a258b699944ef00deb7ad4a3c4b61c54cef99d581e4fd3499e
    image: blackfire/blackfire
  browser:
    hostname: browser
    image: selenium/standalone-chrome
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.5
    ports:
    - 3306/tcp
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.golfzing.docksal
    user: root
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.0-apache2.2
    labels:
      io.docksal.project-root: /Users/drew.michael/projects/golfzing
      io.docksal.virtual-host: golfzing.docksal,*.golfzing.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/drew.michael/projects/golfzing
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Mac OS X 10.11.6
Darwin Spare-Mac-Book-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64
Mode: Docker for Mac
/usr/local/bin/fin: line 4193: is_widows: command not found

███  FIN
fin version: 1.43.2

███  ENVIRONMENT
DOCKER_HOST		| 
 WARNING:  Non-default DOCKER_HOST
------------------------------------------------------------
DOCKSAL_NFS_PATH	| 

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

███  DOCKER INFO
Containers: 18
 Running: 6
 Paused: 0
 Stopped: 12
Images: 17
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 3.854GiB
Name: moby
ID: CRDS:DPRU:5NXX:VXUB:YONX:IWO3:WH7J:6LJY:WFW6:RZPO:KO6S:37DF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 115
 Goroutines: 92
 System Time: 2017-12-14T17:09:23.737274376Z
 EventsListeners: 3
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.17.1
docker-compose version 1.17.1, build 6d101fb
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016

███  DOCKER MACHINE
EXPECTED VERSION: 0.13.0
docker-machine version 0.13.0, build 9ba6da9

NAME      ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
docksal   -        virtualbox   Stopped                 Unknown   

███  DOCKER: IMAGES
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
selenium/standalone-chrome   latest              11258d1f9aba        2 days ago          826MB
memcached                    latest              269b8cdf044f        2 days ago          58.6MB
blackfire/blackfire          latest              cbaa06b10ada        3 weeks ago         21.4MB
docksal/cli                  1.3-php7            19bdddfeab89        2 months ago        759MB
docksal/cli                  1.3-php5            80248f5ea845        2 months ago        814MB
docksal/backstopjs           latest              b943a42c70b6        2 months ago        700MB
docksal/web                  2.1-apache2.4       32c1d32eba6d        3 months ago        87.5MB
cweagans/bg-sync             latest              a5a8ecf71a6e        4 months ago        16.7MB
docksal/web                  2.0-apache2.2       f5675d46dd96        4 months ago        81MB
docksal/vhost-proxy          1.1                 898fb21e7f2d        4 months ago        158MB
docksal/db                   1.1-mysql-5.7       8d323c436c28        4 months ago        412MB
docksal/db                   1.1-mysql-5.6       6feb79af9597        4 months ago        298MB
docksal/db                   1.1-mysql-5.5       aa748dc21dd4        4 months ago        256MB
mailhog/mailhog              latest              669347153085        8 months ago        19.1MB
docksal/vhost-proxy          1.0                 2c8a8b1e62c4        9 months ago        164MB
docksal/dns                  1.0                 20c7a535479d        10 months ago       61.6MB
docksal/ssh-agent            1.0                 148220cc033d        10 months ago       12.2MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                       PORTS                                      NAMES
68ba8223b560        docksal/web:2.1-apache2.4   "httpd-foreground"       13 hours ago        Up About an hour             80/tcp, 443/tcp                            bigpipe_web_1
e17c4a8e30f6        docksal/cli:1.3-php7        "/opt/startup.sh s..."   13 hours ago        Up About an hour (healthy)   22/tcp, 9000/tcp                           bigpipe_cli_1
1d5ed5518fe3        docksal/db:1.1-mysql-5.6    "/entrypoint.sh my..."   13 hours ago        Up About an hour             0.0.0.0:32786->3306/tcp                    bigpipe_db_1
fcc29405030e        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      13 hours ago        Up 13 hours                                                             docksal-ssh-agent
c96f1f0fb15e        docksal/dns:1.0             "/opt/entrypoint.s..."   13 hours ago        Up 13 hours                  192.168.64.100:53->53/udp                  docksal-dns
11968d1eea87        docksal/vhost-proxy:1.1     "docker-entrypoint..."   13 hours ago        Up 13 hours                  0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.1.22r115126

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  HDD Usage
Filesystem      Size   Used  Avail Capacity   iused   ifree %iused  Mounted on
/dev/disk1     465Gi  433Gi   31Gi    94% 113588897 8250717   93%   /
devfs          181Ki  181Ki    0Bi   100%       626       0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%         0       0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%         0       0  100%   /home

███  RAM Usage
Mach Virtual Memory Statistics: (page size of 4096 bytes)
Pages free:                                7488.
Pages active:                           1513518.
Pages inactive:                         1508991.
Pages speculative:                         3005.
Pages throttled:                              0.
Pages wired down:                        654565.
Pages purgeable:                         225720.
"Translation faults":                 235321030.
Pages copy-on-write:                   16348365.
Pages zero filled:                    117608347.
Pages reactivated:                     25937391.
Pages purged:                           1192648.
File-backed pages:                       408040.
Anonymous pages:                        2617474.
Pages stored in compressor:             1457432.
Pages occupied by compressor:            504503.
Decompressions:                         8589331.
Compressions:                          14442440.
Pageins:                               20313629.
Pageouts:                                578872.
Swapins:                                  75556.
Swapouts:                                248344.

███  RAM Usage per container
CONTAINER             CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
bigpipe_web_1         0.27%               6.922MiB / 3.854GiB   0.18%               34.3kB / 41kB       7.2MB / 0B          109
bigpipe_cli_1         0.02%               40.64MiB / 3.854GiB   1.03%               1.68MB / 235kB      69.8MB / 8.19kB     6
bigpipe_db_1          0.07%               455.2MiB / 3.854GiB   11.53%              238kB / 1.76MB      41.3MB / 10.9MB     23
docksal-ssh-agent     0.00%               1.086MiB / 3.854GiB   0.03%               54.7kB / 0B         9.7MB / 0B          2
docksal-dns           0.27%               7.672MiB / 3.854GiB   0.19%               153kB / 125kB       17MB / 0B           16
docksal-vhost-proxy   0.27%               15.27MiB / 3.854GiB   0.39%               124kB / 113kB       104MB / 176kB       19
  ```

</details>
