### ISSUE TITLE
Create stack-node and stack-default-nodb

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#427]
stack-node:

- only cli with labels from web for vhost-proxy

stack-default-nodb:

- only regular web & cli, no db

**Comment by achekulaev** [comment]
For node stack
1. `sudo node` should be working
2. It's better to create a separate image `docksal/node` derived from `cli` that would automatically run `node docroot/index.js` and that file to be configurable via env variable

**Comment by achekulaev** [comment]
Related https://stackoverflow.com/a/37976700/1359178

**Comment by lmakarov** [comment]
IIRC most node apps would bind to something like port 3000/etc.

If ports 80/443 are still desirable, then I see two options:
- use netcat inside the image to proxy 80/443
- enhance docksal-vhost-proxy to proxy arbitrary ports (right now it will only proxy 80 and 443)

Running as root is a bad practice and will cause permission issues on the host (files generated within the node container will be owned by root). Changing root UID/GUI is not an option either and causes other weird things (that why we do not recommend running fin as root).

**Comment by achekulaev** [comment]
Right... sudo is not an option. What stops vhost-proxy from proxying random ports? Is there a way to say nginx to proxy all of them?

**Comment by lmakarov** [comment]
> Is there a way to say nginx to proxy all of them?

Is there a way for an app to bind to all ports on the host? :)

**Comment by lmakarov** [comment]
It's just extending the configuration template and adding variables for HTTP/HTTPS destination ports (to override the default 80/443)

**Comment by achekulaev** [comment]
> Is there a way for an app to bind to all ports on the host?
funny :)
(Theoretically though vhost-proxy could discover open ports of container that has proper labels, but that's something for future)

**Comment by lmakarov** [comment]
Once https://github.com/docksal/service-vhost-proxy/issues/20 is resolved it will be possible to use vhost-proxy with arbitrary container ports. This way nodejs can run on an unprivileged port `3000`, which will be proxied by vhost-proxy.

**Comment by achekulaev** [comment]
@lmakarov maybe we better use this? https://stackoverflow.com/a/23281401/1359178 Allow regular use to use port 80.

**Comment by lmakarov** [comment]
> maybe we better use this?

@achekulaev that would be yet another hack like with netcat. But... it's still a valid option. Have you tried it?

BTW, I realized that vhost-proxy already supports routing non-default ports like this:

```
version: "2.1"

services:
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: web
  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    labels:
      - io.docksal.virtual-host=nodejs.${VIRTUAL_HOST},*.nodejs.${VIRTUAL_HOST}
    expose:
      - 8080
    environment:
      - VIRTUAL_PORT=8080
```

I'd still want `VIRTUAL_PORT` converted into a label to keep things consistent.

Other observations:

- Docksal depends on the `web` service being around - that's how we get the list of running projects in fin as well as in vhost-proxy.
- `cli` gets a special treatment in `fin bash`, so that one cannot be dropped either without consequences

We need a distinctive and universal way to define the primary ("anchor") container for a project.
The `io.docksal.project-root=${PROJECT_ROOT}` label looks to be the way to go. It is currently set on `web`, but can be instead set on any other service.
