### ISSUE TITLE
Make Acquia BLT friends with Docksal

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#428]
Make Acquia BLT run within Docksal.

**Comment by lpeabody** [comment]
So, I've done this and it works well. Link to the Docker Hub project https://hub.docker.com/r/lpeabody/blt-cli/.

**Comment by lpeabody** [comment]
More than that though, Acquia BLT should be updated to include an equivalent command to `blt vm`, so like `blt docksal` which would fire up a default project with, I would assume, the Acquia stack, or some set of configuration steps. For the last year my projects have used the following default setup:

docksal.env:
```
DOCKSAL_STACK="acquia"
```

dockal.yml:
```
version: "2.1"

services:
  cli:
    image: lpeabody/blt-cli:php7-1.3
```

example.docksal-local.env:
```
XDEBUG_ENABLED=1
```

example.docksal-local.yml:
```
version: "2.1"
services:
  cli:
    environment:
      - XDEBUG_ENABLED=1
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=192.168.64.1
      - PHP_IDE_CONFIG=serverName=${VIRTUAL_HOST}
```
