### ISSUE TITLE
Not all drives are properly mapped on Windows 10 Pro + WSL 

### ISSUE THREAD

**Issue by DenisSemerikov** [docksal/docksal#429]
**Description**

Windows 10 Pro + WSL + Docker for Windows always have virtual host = ".docksal"

**Steps to reproduce the issue:**

1.Fresh Windows Installation.
2. All software installed using this tutorial
https://blog.docksal.io/how-to-access-docker-for-windows-from-within-ubuntu-app-windows-services-for-linux-wsl-10ca8ef15b6e
3. fin project create

             -= Docksal project wizard =-

1. Enter the name of your project (no spaces or slashes): test-docksal

2. What would you like to install?
   [1] Drupal 7
   [2] Drupal 8
   [3] Wordpress
   [4] Magento
   [5] Static HTML site
   [6] Grav CMS
   [7] Gatsby JS
   [8] Laravel

Enter your choice (1-8): 5

Your site will be created at /d/Work/test-docksal
Your site will run Plain HTML
The URL of your site will be http://test-docksal.docksal

Do you wish to proceed? [y/n]: y
Starting services...
Creating stacks_db_1 ...
Creating stacks_cli_1 ...
Creating stacks_db_1
Creating stacks_cli_1 ... done
Creating stacks_web_1 ...
Creating stacks_web_1 ... done
Waiting 10s for container to start...
Virtual Host: .docksal
Done! Visit http://test-docksal.docksal
evildan@DESKTOP-K44LQNB:/mnt/d/Work$ fin pl
project             STATUS              virtual host          project root
stacks              Up 39 seconds       .docksal,*..docksal   /d/Work/test-docksal
evildan@DESKTOP-K44LQNB:/mnt/d/Work$ cd test-docksal/
evildan@DESKTOP-K44LQNB:/mnt/d/Work/test-docksal$ ls -la .docksal/
total 0
drwxrwxrwx 0 root root 4096 Dec 15 22:38 .
drwxrwxrwx 0 root root 4096 Dec 15 22:38 ..
evildan@DESKTOP-K44LQNB:/mnt/d/Work/test-docksal$ echo 'VIRTUAL_HOST=test.docksal' > .docksal/docksal.env
evildan@DESKTOP-K44LQNB:/mnt/d/Work/test-docksal$ cat .docksal/docksal.env
VIRTUAL_HOST=test.docksal

**Describe the results you received:**

http://test-docksal.docksal/ - Project Not Found.

**Describe the results you expected:**

Working site

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE:
COMPOSE_FILE:
/home/evildan/.docksal/stacks/volumes-bind.yml
/home/evildan/.docksal/stacks/stack-default.yml

PROJECT_ROOT: /d/Work/test-docksal
DOCROOT: docroot
VIRTUAL_HOST: .docksal
VIRTUAL_HOST_ALIASES: *..docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32772

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '1000'
      HOST_UID: '1000'
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php7
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /d/Work/test-docksal
      io.docksal.virtual-host: .docksal,*..docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /d/Work/test-docksal
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
 fin sysinfo
███  OS
Linux DESKTOP-K44LQNB 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
Mode: VirtualBox VM

███  FIN
fin version: 1.43.2

███  ENVIRONMENT
DOCKER_HOST             | 0.0.0.0:2375
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: true

███  DOCKER INFO
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: NLUS:RT6T:CMZN:PTVU:AKH2:MHME:ZBBK:XI7C:7NT3:QHWB:YFFP:ZM5Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 63
 Goroutines: 75
 System Time: 2017-12-15T20:52:34.494878Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.17.1
docker-compose version 1.17.1, build 6d101fb
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/cli           1.3-php7            19bdddfeab89        2 months ago        759MB
docksal/web           2.1-apache2.4       32c1d32eba6d        3 months ago        87.5MB
docksal/vhost-proxy   1.1                 898fb21e7f2d        4 months ago        158MB
docksal/db            1.1-mysql-5.6       6feb79af9597        4 months ago        298MB
docksal/dns           1.0                 20c7a535479d        10 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        10 months ago       12.2MB
d4w/nsenter           latest              9e4f13a0901e        14 months ago       83.8kB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
33a0368fd120        docksal/web:2.1-apache2.4   "httpd-foreground"       13 minutes ago      Up 13 minutes             80/tcp, 443/tcp                                          stacks_web_1
1bf61d83855c        docksal/db:1.1-mysql-5.6    "/entrypoint.sh my..."   13 minutes ago      Up 13 minutes             0.0.0.0:32772->3306/tcp                                  stacks_db_1
fe673903fbd0        docksal/cli:1.3-php7        "/opt/startup.sh s..."   13 minutes ago      Up 13 minutes (healthy)   22/tcp, 9000/tcp                                         stacks_cli_1
2a8f2b2a8030        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      14 minutes ago      Up 14 minutes                                                                      docksal-ssh-agent
80ff29f9da62        docksal/dns:1.0             "/opt/entrypoint.s..."   14 minutes ago      Up 14 minutes             192.168.64.100:53->53/udp                                docksal-dns
49c6c4a1d131        docksal/vhost-proxy:1.1     "docker-entrypoint..."   14 minutes ago      Up 14 minutes             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  HDD Usage
docker-machine executable was not found. (Try running 'fin update')
  ```

</details>
