### ISSUE TITLE
Databases not persisting after computer restart

### ISSUE THREAD

**Issue by drubage** [docksal/docksal#431]
**Description**

It seems like when I reboot my computer I lose all the databases in my projects. I go back to a project and "fin up" and all of the databases are gone. Docksal never did this to me before.

**Steps to reproduce the issue:**

1. Run "fin init" on a project that includes creating data in a database (via database import or via drush site-install, etc.)
2. Reboot computer
3. Run "fin up" in the project, the database is gone.

**Describe the results you received:**

There is no database anymore.

**Describe the results you expected:**

The same database with the same data in it as when the project was last run.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: golfzing
COMPOSE_FILE:
/Users/drew.michael/.docksal/stacks/volumes-bind.yml
/Users/drew.michael/.docksal/stacks/stack-default.yml
/Users/drew.michael/projects/golfzing/.docksal/docksal.yml
ENV_FILE:
/Users/drew.michael/projects/golfzing/.docksal/docksal.env

PROJECT_ROOT: /Users/drew.michael/projects/golfzing
DOCROOT: docroot
VIRTUAL_HOST: golfzing.docksal
VIRTUAL_HOST_ALIASES: *.golfzing.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  backstop:
    entrypoint: top -b
    hostname: backstop
    image: backstopjs/backstopjs
    volumes:
    - /Users/drew.michael/projects/golfzing/tests/backstop:/src:rw
  blackfire:
    environment:
      BLACKFIRE_SERVER_ID: ee03735e-4a15-4b5f-ba76-5d0bc7160dc8
      BLACKFIRE_SERVER_TOKEN: 982bdea3e43186a258b699944ef00deb7ad4a3c4b61c54cef99d581e4fd3499e
    image: blackfire/blackfire
  browser:
    hostname: browser
    image: selenium/standalone-chrome
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '502'
      HOST_UID: '503'
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.5
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.golfzing.docksal
    user: root
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.2
    labels:
      io.docksal.project-root: /Users/drew.michael/projects/golfzing
      io.docksal.virtual-host: golfzing.docksal,*.golfzing.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/drew.michael/projects/golfzing
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
 ███  OS
Mac OS X 10.11.6
Darwin Spare-Mac-Book-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64
Mode: VirtualBox VM

███  FIN
fin version: 1.43.2

███  ENVIRONMENT
DOCKER_HOST		| tcp://192.168.64.100:2376
------------------------------------------------------------
DOCKSAL_NFS_PATH	| 

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false

███  DOCKER INFO
Containers: 25
 Running: 11
 Paused: 0
 Stopped: 14
Images: 31
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 428
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.89-boot2docker
Operating System: Boot2Docker 17.09.0-ce (TCL 7.2); HEAD : 06d5c35 - Wed Sep 27 23:22:43 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.858GiB
Name: docksal
ID: LWS5:BTIT:WLKB:HOEQ:U34C:WAOU:KY3W:HZP3:AKHW:7J2V:WLRQ:2WHU
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 128
 Goroutines: 98
 System Time: 2017-12-26T20:02:27.824308791Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.17.1
docker-compose version 1.17.1, build 6d101fb
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016

███  DOCKER MACHINE
EXPECTED VERSION: 0.13.0
docker-machine version 0.13.0, build 9ba6da9

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.09.0-ce   

███  DOCKER: IMAGES
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
docksal/cli                  edge-php7.1         56ade5867600        6 days ago          907MB
backstopjs/backstopjs        latest              0ab1ada9bb16        12 days ago         694MB
docksal/cli                  edge-php7           1903c6086d28        7 weeks ago         799MB
docksal/cli                  1.3-php7            19bdddfeab89        3 months ago        759MB
docksal/cli                  1.3-php5            80248f5ea845        3 months ago        814MB
docksal/backstopjs           latest              b943a42c70b6        3 months ago        700MB
docksal/web                  2.1-apache2.4       32c1d32eba6d        4 months ago        87.5MB
docksal/web                  2.1-apache2.2       f64644fd6d46        4 months ago        81MB
wernight/ngrok               latest              7b56f07b2302        4 months ago        27.1MB
blackfire/blackfire          latest              b7c6980c1ce9        4 months ago        21.6MB
docksal/web                  2.0-apache2.4       7f75db9a6aa7        4 months ago        87.5MB
docksal/web                  2.0-apache2.2       f5675d46dd96        4 months ago        81MB
docksal/vhost-proxy          1.1                 898fb21e7f2d        4 months ago        158MB
docksal/db                   1.1-mysql-5.7       8d323c436c28        5 months ago        412MB
docksal/db                   1.1-mysql-5.6       6feb79af9597        5 months ago        298MB
docksal/db                   1.1-mysql-5.5       aa748dc21dd4        5 months ago        256MB
selenium/standalone-chrome   latest              1dec27211cb6        5 months ago        835MB
memcached                    latest              add80e4f4120        5 months ago        82.6MB
mailhog/mailhog              latest              669347153085        8 months ago        19.1MB
docksal/cli                  1.2-php5            11f47dc7d024        8 months ago        845MB
docksal/cli                  1.2-php7            aef362412c9f        8 months ago        787MB
docksal/vhost-proxy          1.0                 2c8a8b1e62c4        9 months ago        164MB
docksal/dns                  1.0                 20c7a535479d        11 months ago       61.6MB
docksal/ssh-agent            1.0                 148220cc033d        11 months ago       12.2MB
docksal/web                  1.0-apache2.2       a9c03f8a5f0f        11 months ago       188MB
docksal/web                  1.0-apache2.4       1e2aa01c55d6        11 months ago       259MB
docksal/db                   1.0-mysql-5.7       35f1494f03b6        11 months ago       400MB
docksal/db                   1.0-mysql-5.6       7c932a2f6a71        11 months ago       328MB
docksal/db                   1.0-mysql-5.5       9fb8c0aed5fc        11 months ago       255MB
docksal/solr                 1.0-solr4           fa6b236caf06        12 months ago       546MB
docksal/solr                 1.0-solr3           628ee3683031        12 months ago       471MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                   PORTS                                      NAMES
ef27e7589287        docksal/web:2.1-apache2.2    "httpd-foreground"       4 minutes ago       Up 4 minutes             80/tcp, 443/tcp                            golfzing_web_1
feb8b6d1e24b        blackfire/blackfire          "blackfire-agent"        4 minutes ago       Up 4 minutes             8707/tcp                                   golfzing_blackfire_1
9c26207a0fd6        docksal/cli:1.3-php5         "/opt/startup.sh s..."   4 minutes ago       Up 4 minutes (healthy)   22/tcp, 9000/tcp                           golfzing_cli_1
7c10c3037abe        selenium/standalone-chrome   "/opt/bin/entry_po..."   4 minutes ago       Up 4 minutes             4444/tcp                                   golfzing_browser_1
7a8cb6076273        backstopjs/backstopjs        "top -b"                 4 minutes ago       Up 4 minutes                                                        golfzing_backstop_1
1bbc03f18d04        memcached                    "docker-entrypoint..."   4 minutes ago       Up 4 minutes             11211/tcp                                  golfzing_memcached_1
98feacf94990        docksal/db:1.1-mysql-5.5     "/entrypoint.sh my..."   4 minutes ago       Up 4 minutes             0.0.0.0:32768->3306/tcp                    golfzing_db_1
19fefa40306b        mailhog/mailhog              "MailHog"                4 minutes ago       Up 4 minutes             80/tcp, 1025/tcp, 8025/tcp                 golfzing_mail_1
eebf1b10b8bd        docksal/ssh-agent:1.0        "/run.sh ssh-agent"      7 days ago          Up 4 minutes                                                        docksal-ssh-agent
e3650b9cd8b3        docksal/dns:1.0              "/opt/entrypoint.s..."   7 days ago          Up 4 minutes             192.168.64.100:53->53/udp                  docksal-dns
d49f2ac8f494        docksal/vhost-proxy:1.1      "docker-entrypoint..."   7 days ago          Up 4 minutes             0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.1.28r117968

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/drew.michael/projects/golfzing on /mnt/sda1/var/lib/docker/volumes/golfzing_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                93.6G     25.7G     63.0G  29% /mnt/sda1

███  RAM Usage
             total       used       free     shared    buffers     cached
Mem:       4045564    3593892     451672     203660      84740    2761988
-/+ buffers/cache:     747164    3298400
Swap:      1941560          0    1941560

███  RAM Usage per container
CONTAINER              CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
golfzing_web_1         0.00%               3.793MiB / 3.858GiB   0.10%               21.3kB / 65.9kB     6.4MB / 0B          9
golfzing_blackfire_1   0.17%               4.84MiB / 3.858GiB    0.12%               98.9kB / 3.68kB     8.11MB / 0B         6
golfzing_cli_1         1.49%               19.46MiB / 3.858GiB   0.49%               3.36kB / 3.87kB     49.1MB / 41kB       6
golfzing_browser_1     0.11%               56.39MiB / 3.858GiB   1.43%               1.16kB / 0B         68.9MB / 0B         21
golfzing_backstop_1    0.00%               64KiB / 3.858GiB      0.00%               1.25kB / 0B         1.49MB / 0B         1
golfzing_memcached_1   0.01%               608KiB / 3.858GiB     0.02%               1.37kB / 0B         3.1MB / 0B          7
golfzing_db_1          0.07%               314.8MiB / 3.858GiB   7.97%               1.9kB / 650B        25.5MB / 627MB      16
golfzing_mail_1        0.00%               1.637MiB / 3.858GiB   0.04%               1.46kB / 0B         8.9MB / 0B          4
docksal-ssh-agent      0.00%               636KiB / 3.858GiB     0.02%               1.66kB / 0B         5.82MB / 0B         2
docksal-dns            0.15%               17.11MiB / 3.858GiB   0.43%               1.74kB / 118B       14.8MB / 4.1kB      9
docksal-vhost-proxy    0.16%               21.01MiB / 3.858GiB   0.53%               85kB / 79.7kB       35.4MB / 24.6kB     12
  ```

</details>
