### ISSUE TITLE
Emails Not Being Sent Out In Drupal, Receive Error

### ISSUE THREAD

**Issue by fruitionaccounts** [docksal/docksal#441]
**Description**

Problem/feature description...

**Steps to reproduce the issue:**

1. Create an account, programmatically.  Save the account programatically
2. Plugin account variable into _user_mail_notify('register_no_approval_required', $account);
3. Run the code

**Describe the results you received:**

It does not send, and I get the error "Unable to send email. Contact the site administrator if the problem persists."

**Describe the results you expected:**

The email should have sent, and have been caught by mailhog

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: semdec22
COMPOSE_FILE:
/Users/scotttaylor/.docksal/stacks/volumes-bind.yml
/Users/scotttaylor/.docksal/stacks/stack-default.yml
/Users/scotttaylor/projects/sem-dec-22/.docksal/docksal.yml
ENV_FILE:
/Users/scotttaylor/projects/sem-dec-22/.docksal/docksal.env
/Users/scotttaylor/projects/sem-dec-22/.docksal/docksal-local.env

PROJECT_ROOT: /Users/scotttaylor/projects/sem-dec-22
DOCROOT: drupal/web
VIRTUAL_HOST: fruitionsem3.ddns.net
VIRTUAL_HOST_ALIASES: *.fruitionsem3.ddns.net
IP: 192.168.64.100
MYSQL: 192.168.64.100:32770

Docker Compose configuration
---------------------
services:
  blackfire:
    environment:
      BLACKFIRE_SERVER_ID: ee03735e-4a15-4b5f-ba76-5d0bc7160dc8
      BLACKFIRE_SERVER_TOKEN: 982bdea3e43186a258b699944ef00deb7ad4a3c4b61c54cef99d581e4fd3499e
    image: blackfire/blackfire
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: drupal/web
      HOST_GID: '20'
      HOST_UID: '501'
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:1.3-php7
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.fruitionsem3.ddns.net
    user: root
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/drupal/web
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/scotttaylor/projects/sem-dec-22
      io.docksal.virtual-host: fruitionsem3.ddns.net,*.fruitionsem3.ddns.net
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/scotttaylor/projects/sem-dec-22
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

```
███  OS
Mac OS X 10.13.2
Darwin scotts-mbp-2.lan 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
Mode: VirtualBox VM

███  FIN
fin version: 1.43.2

███  ENVIRONMENT
DOCKER_HOST		| tcp://192.168.64.100:2376
------------------------------------------------------------
DOCKSAL_NFS_PATH	|

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false

███  DOCKER INFO
Containers: 25
 Running: 9
 Paused: 0
 Stopped: 16
Images: 21
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 320
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.89-boot2docker
Operating System: Boot2Docker 17.09.0-ce (TCL 7.2); HEAD : 06d5c35 - Wed Sep 27 23:22:43 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.858GiB
Name: docksal
ID: ZQ42:U3U6:HSWB:XB3U:BUVB:2Y7Z:EGDG:3IAB:6Z4P:VAAF:WTXB:EFI2
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 102
 Goroutines: 86
 System Time: 2018-01-10T23:15:17.91804902Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.17.1
docker-compose version 1.17.1, build 6d101fb
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016

███  DOCKER MACHINE
EXPECTED VERSION: 0.13.0
docker-machine version 0.13.0, build 9ba6da9

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.09.0-ce

███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
blackfire/blackfire   latest              cbaa06b10ada        7 weeks ago         21.4MB
docksal/cli           edge-php7           1903c6086d28        2 months ago        799MB
docksal/cli           1.3-php7            19bdddfeab89        3 months ago        759MB
docksal/web           2.1-apache2.4       32c1d32eba6d        4 months ago        87.5MB
docksal/web           2.0-apache2.2       f5675d46dd96        5 months ago        81MB
docksal/vhost-proxy   1.1                 898fb21e7f2d        5 months ago        158MB
docksal/db            1.1-mysql-5.6       6feb79af9597        5 months ago        298MB
docksal/db            1.1-mysql-5.5       aa748dc21dd4        5 months ago        256MB
docksal/cli           <none>              d35c1b40784d        6 months ago        749MB
wernight/ngrok        latest              7d0713e0e005        8 months ago        26.9MB
memcached             latest              6c32c12d9101        8 months ago        83.9MB
mailhog/mailhog       latest              669347153085        8 months ago        19.1MB
docksal/cli           1.2-php5            11f47dc7d024        9 months ago        845MB
docksal/cli           1.2-php7            aef362412c9f        9 months ago        787MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        10 months ago       164MB
docksal/dns           1.0                 20c7a535479d        11 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        11 months ago       12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        11 months ago       188MB
docksal/db            1.0-mysql-5.7       35f1494f03b6        11 months ago       400MB
docksal/db            1.0-mysql-5.6       7c932a2f6a71        11 months ago       328MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        11 months ago       255MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                       PORTS                                                    NAMES
4506fff35388        docksal/web:2.1-apache2.4   "httpd-foreground"       About an hour ago   Up About an hour             80/tcp, 443/tcp                                          semdec22_web_1
b74b40660218        mailhog/mailhog             "MailHog"                About an hour ago   Up About an hour             80/tcp, 1025/tcp, 8025/tcp                               semdec22_mail_1
9b86d9a9eadb        docksal/cli:1.3-php7        "/opt/startup.sh s..."   2 weeks ago         Up About an hour (healthy)   22/tcp, 9000/tcp                                         semdec22_cli_1
52b7991c56c9        docksal/db:1.1-mysql-5.6    "/entrypoint.sh my..."   2 weeks ago         Up About an hour             0.0.0.0:32770->3306/tcp                                  semdec22_db_1
6253e9cfff1c        memcached                   "docker-entrypoint..."   2 weeks ago         Up About an hour             11211/tcp                                                semdec22_memcached_1
eb2750d2de4e        blackfire/blackfire         "blackfire-agent"        2 weeks ago         Up About an hour             8707/tcp                                                 semdec22_blackfire_1
39e9fbd71d0e        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      3 weeks ago         Up 2 days                                                                             docksal-ssh-agent
8ac75b0a24e9        docksal/dns:1.0             "/opt/entrypoint.s..."   3 weeks ago         Up 2 days                    192.168.64.100:53->53/udp                                docksal-dns
f70fed3429dc        docksal/vhost-proxy:1.1     "docker-entrypoint..."   3 weeks ago         Up 2 days                    192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.1.30r118389

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/scotttaylor/projects/sem-dec-22 on /mnt/sda1/var/lib/docker/volumes/semdec22_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.3G     19.2G     24.7G  44% /mnt/sda1

███  RAM Usage
             total       used       free     shared    buffers     cached
Mem:       4045564    1693900    2351664     236284     176216     626548
-/+ buffers/cache:     891136    3154428
Swap:      1917824          0    1917824

███  RAM Usage per container
CONTAINER              CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
semdec22_web_1         0.07%               6.176MiB / 3.858GiB   0.16%               814kB / 1.92MB      0B / 0B             109
semdec22_mail_1        0.00%               2.082MiB / 3.858GiB   0.05%               91.7kB / 5.03MB     0B / 0B             7
semdec22_cli_1         0.02%               69.61MiB / 3.858GiB   1.76%               95.4MB / 20.2MB     81.9kB / 45.1kB     7
semdec22_db_1          0.05%               525.1MiB / 3.858GiB   13.29%              12.9MB / 58.8MB     131kB / 81.1MB      24
semdec22_memcached_1   0.04%               29.73MiB / 3.858GiB   0.75%               5.05MB / 36.2MB     0B / 0B             7
semdec22_blackfire_1   0.26%               4.09MiB / 3.858GiB    0.10%               97.9kB / 2.81kB     0B / 0B             6
docksal-ssh-agent      0.00%               640KiB / 3.858GiB     0.02%               6.25kB / 0B         5.82MB / 0B         2
docksal-dns            0.14%               13.82MiB / 3.858GiB   0.35%               30.4kB / 29.3kB     14.8MB / 0B         10
docksal-vhost-proxy    0.14%               18.15MiB / 3.858GiB   0.46%               73MB / 72.4MB       35.7MB / 24.6kB     12
```

</details>
