### ISSUE TITLE
Can't connect to local MySQL server through socket

### ISSUE THREAD

**Issue by mardond** [docksal/docksal#469]
**Description**

I'm trying to pull down a site locally and receiving this error:

```PDOException: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) in lock_may_be_available() (line 167 of /var/www/docroot/includes/lock.inc).```

So I tried to use a standard install and then import my database, but the standard install would receive this error:

```
{ docroot } master » fin exec -T drush si standard -y
You are about to CREATE the '' database. Do you want to continue? (y/n): y
Failed to create database: ERROR 2002 (HY000): Can&#039;t connect to [error]
local MySQL server through socket
&#039;/var/run/mysqld/mysqld.sock&#039; (2)
```

After running fin diagnose:

```
{ bsc.ogs.ny.gov } master » fin diagnose
███  HDD Usage
Caption  FreeSpace     Size
C:       44722405376   254859333632
D:       915768688640  1000202039296
E:
O:
V:


███  RAM Usage
find: ‘Available Physical Memory’: No such file or directory

███  RAM Usage per container
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
f354d60d1291        bscogsnygov_web_1     0.15%               6.961MiB / 3.837GiB   0.18%               43.2kB / 339kB      0B / 0B             82
4ca268888ead        bscogsnygov_cli_1     0.02%               26.17MiB / 3.837GiB   0.67%               4.9kB / 9.02kB      0B / 8.19kB         6
08816c6bffce        bscogsnygov_db_1      0.07%               492.3MiB / 3.837GiB   12.53%              1.3kB / 0B          131kB / 49.2kB      21
a32383c00cc4        docksal-ssh-agent     0.00%               1.309MiB / 3.837GiB   0.03%               2.22kB / 0B         4.71MB / 0B         2
365daf52d900        docksal-dns           0.30%               16.48MiB / 3.837GiB   0.42%               93.9kB / 102kB      15.3MB / 4.1kB      11
161c7d3f50a3        docksal-vhost-proxy   0.26%               19.24MiB / 3.837GiB   0.49%               1.09MB / 1.09MB     35.5MB / 20.5kB     13
```

**Describe the results you expected:**

Expected behavior...

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
{ bsc.ogs.ny.gov } master » fin config output
---------------------
COMPOSE_PROJECT_NAME_SAFE: bscogsnygov
COMPOSE_FILE:
C:/Users/Dmardon/.docksal/stacks/volumes-bind.yml
C:/Users/Dmardon/.docksal/stacks/stack-default.yml
ENV_FILE:
C:/Users/Dmardon/projects/bsc.ogs.ny.gov/.docksal/docksal.env
C:/Users/Dmardon/projects/bsc.ogs.ny.gov/.docksal/docksal-local.env

PROJECT_ROOT: /c/Users/Dmardon/projects/bsc.ogs.ny.gov
DOCROOT: docroot
VIRTUAL_HOST: bsc.ogs.ny.gov.docksal
VIRTUAL_HOST_ALIASES: *.bsc.ogs.ny.gov.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32769

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: null
      HOST_UID: null
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /c/Users/Dmardon/projects/bsc.ogs.ny.gov
      io.docksal.virtual-host: bsc.ogs.ny.gov.docksal,*.bsc.ogs.ny.gov.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/Dmardon/projects/bsc.ogs.ny.gov
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
fin sysinfo
███  OS
 Microsoft Windows [Version 10.0.15063]
CYGWIN_NT-10.0-WOW W8B41X52 2.10.0(0.325/5/3) 2018-02-02 15:21 i686 Cygwin
Mode: /usr/local/bin/fin: line 4193: is_widows: command not found

███  FIN
fin version: 1.43.2

███  ENVIRONMENT
DOCKER_HOST             |
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true

███  DOCKER INFO
Containers: 24
 Running: 6
 Paused: 0
 Stopped: 18
Images: 8
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.837GiB
Name: linuxkit-00155d400100
ID: 4FTJ:JE7L:R7EU:LWZZ:Z5ZH:4NEW:LFRS:5I2J:53UW:WZRZ:LQT2:GSRC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 63
 Goroutines: 75
 System Time: 2018-02-28T16:34:22.9805047Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.17.1
docker-compose version 1.18.0, build 8dd22a96
docker-py version: 2.6.1
CPython version: 2.7.14
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

███  DOCKER MACHINE
EXPECTED VERSION: 0.13.0
docker-machine.exe version 0.13.0, build 9ba6da9

NAME    ACTIVE   DRIVER       STATE   URL   SWARM   DOCKER    ERRORS
test    -        virtualbox   Error                 Unknown   VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
test2   -        virtualbox   Error                 Unknown   VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
test3   -        virtualbox   Error                 Unknown   VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

███  DOCKER: IMAGES
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
docker4w/nsenter-dockerd   latest              cae870735e91        4 months ago        187kB
docksal/cli                1.3-php7            19bdddfeab89        5 months ago        759MB
docksal/cli                1.3-php5            80248f5ea845        5 months ago        814MB
docksal/web                2.1-apache2.4       32c1d32eba6d        6 months ago        87.5MB
docksal/vhost-proxy        1.1                 898fb21e7f2d        7 months ago        158MB
docksal/db                 1.1-mysql-5.6       6feb79af9597        7 months ago        298MB
docksal/dns                1.0                 20c7a535479d        13 months ago       61.6MB
docksal/ssh-agent          1.0                 148220cc033d        13 months ago       12.2MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
f354d60d1291        docksal/web:2.1-apache2.4   "httpd-foreground"       About an hour ago   Up 21 minutes             80/tcp, 443/tcp                                          bscogsnygov_web_1
4ca268888ead        docksal/cli:1.3-php5        "/opt/startup.sh sup…"   3 weeks ago         Up 21 minutes (healthy)   22/tcp, 9000/tcp                                         bscogsnygov_cli_1
08816c6bffce        docksal/db:1.1-mysql-5.6    "/entrypoint.sh mysq…"   3 weeks ago         Up 21 minutes             0.0.0.0:32769->3306/tcp                                  bscogsnygov_db_1
a32383c00cc4        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      4 weeks ago         Up 29 minutes                                                                      docksal-ssh-agent
365daf52d900        docksal/dns:1.0             "/opt/entrypoint.sh …"   4 weeks ago         Up 29 minutes             192.168.64.100:53->53/udp                                docksal-dns
161c7d3f50a3        docksal/vhost-proxy:1.1     "docker-entrypoint.s…"   4 weeks ago         Up 29 minutes             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  HDD Usage
Caption  FreeSpace     Size
C:       44720619520   254859333632
D:       915768688640  1000202039296
E:
O:
V:


███  RAM Usage
find: ‘Available Physical Memory’: No such file or directory

███  RAM Usage per container
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
f354d60d1291        bscogsnygov_web_1     0.12%               6.961MiB / 3.837GiB   0.18%               43.2kB / 339kB      0B / 0B             82
4ca268888ead        bscogsnygov_cli_1     0.04%               26.15MiB / 3.837GiB   0.67%               4.97kB / 9.02kB     0B / 8.19kB         6
08816c6bffce        bscogsnygov_db_1      0.05%               492.3MiB / 3.837GiB   12.53%              1.37kB / 0B         131kB / 49.2kB      21
a32383c00cc4        docksal-ssh-agent     0.00%               1.309MiB / 3.837GiB   0.03%               2.22kB / 0B         4.71MB / 0B         2
365daf52d900        docksal-dns           0.21%               16.48MiB / 3.837GiB   0.42%               112kB / 122kB       15.3MB / 4.1kB      11
161c7d3f50a3        docksal-vhost-proxy   0.27%               19.24MiB / 3.837GiB   0.49%               1.09MB / 1.09MB     35.5MB / 20.5kB     13

  ```

</details>
