### ISSUE TITLE
Mail hog is not running

### ISSUE THREAD

**Issue by dealancer** [docksal/docksal#470]
Mail hog is not running.

**Description**

Mail hog is not running.

**Steps to reproduce the issue:**

I have added following lines to `docksal.yml` and restarted Docksal:

```
  # Mail
  mail:
    hostname: mail
    image: mailhog/mailhog
    expose:
      - "80"
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:80
      - MH_UI_BIND_ADDR=0.0.0.0:80
      - VIRTUAL_HOST=webmail.${VIRTUAL_HOST}
    labels:
      - io.docksal.virtual-host=webmail.${VIRTUAL_HOST}
```

**Describe the results you received:**

When I open `webmail.<sitename>.docksal` I am seeing a website but not a mailhog.

Output of the `fin status` command:

```
        Name                      Command             State             Ports          
--------------------------------------------------------------------------------------
guwordpress_browser_1   /opt/bin/entry_point.sh       Up       4444/tcp                
guwordpress_cli_1       /opt/startup.sh supervisord   Up       22/tcp, 9000/tcp        
guwordpress_db_1        /entrypoint.sh mysqld         Up       0.0.0.0:32770->3306/tcp 
guwordpress_mail_1      MailHog                       Exit 1                           
guwordpress_web_1       httpd-foreground              Up       443/tcp, 80/tcp    
```

**Describe the results you expected:**

It should be running.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: guwordpress
COMPOSE_FILE:
/Users/vm386/.docksal/stacks/volumes-bind.yml
/Users/vm386/.docksal/stacks/stack-default.yml
/Users/vm386/Projects/docksal/guwordpress/.docksal/docksal.yml
ENV_FILE:
/Users/vm386/Projects/docksal/guwordpress/.docksal/docksal.env

PROJECT_ROOT: /Users/vm386/Projects/docksal/guwordpress
DOCROOT: docroot
VIRTUAL_HOST: guwordpress.docksal
VIRTUAL_HOST_ALIASES: *.guwordpress.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32770

Docker Compose configuration
---------------------
services:
  browser:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: browser
    image: selenium/standalone-chrome
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '502'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php7
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 03306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
      VIRTUAL_HOST: webmail.guwordpress.docksal
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.guwordpress.docksal
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.0-apache2.4
    labels:
      io.docksal.project-root: /Users/vm386/Projects/docksal/guwordpress
      io.docksal.virtual-host: guwordpress.docksal,*.guwordpress.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /Users/vm386/Projects/docksal/guwordpress
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin UIS-AL-LNFD58.local 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64
Mac OS X 10.12.6
fin version: 1.27.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.06.0-ce   
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.12.2, build 9371605
███  DOCKER: IMAGES
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
selenium/standalone-chrome   latest              825e97a855ef        4 weeks ago         825MB
guwordpress_cli              latest              c043f04e1d7e        2 months ago        818MB
docksal/cli                  1.3-php7            19bdddfeab89        5 months ago        759MB
docksal/web                  2.0-apache2.4       7f75db9a6aa7        6 months ago        87.5MB
docksal/vhost-proxy          1.1                 898fb21e7f2d        7 months ago        158MB
docksal/db                   1.1-mysql-5.6       6feb79af9597        7 months ago        298MB
mailhog/mailhog              latest              669347153085        10 months ago       19.1MB
docksal/dns                  1.0                 20c7a535479d        13 months ago       61.6MB
docksal/ssh-agent            1.0                 148220cc033d        13 months ago       12.2MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                   PORTS                                                    NAMES
4a9cad1edb5b        docksal/web:2.0-apache2.4    "httpd-foreground"       12 days ago         Up 5 minutes             80/tcp, 443/tcp                                          guwordpress_web_1
17d450eb7763        docksal/cli:1.3-php7         "/opt/startup.sh s..."   12 days ago         Up 5 minutes (healthy)   22/tcp, 9000/tcp                                         guwordpress_cli_1
908a572e537b        docksal/db:1.1-mysql-5.6     "/entrypoint.sh my..."   12 days ago         Up 5 minutes             0.0.0.0:32770->3306/tcp                                  guwordpress_db_1
019e7c9f9da0        selenium/standalone-chrome   "/opt/bin/entry_po..."   12 days ago         Up 5 minutes             4444/tcp                                                 guwordpress_browser_1
d1f49092effc        docksal/ssh-agent:1.0        "/run.sh ssh-agent"      2 months ago        Up 16 minutes                                                                     docksal-ssh-agent
9acda045e292        docksal/dns:1.0              "/opt/entrypoint.s..."   2 months ago        Up 16 minutes            192.168.64.100:53->53/udp                                docksal-dns
38c1466464e5        docksal/vhost-proxy:1.1      "docker-entrypoint..."   2 months ago        Up 16 minutes            192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.22r115126
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=1845260k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/dd5b090522ec31104e0d5934a490e66ca3dde6c12912473f29db683e3a03c87e type aufs (rw,relatime,si=9afe73eb320bfd01,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/5a09d06d9dd6512e0801bb8123d645358567d9b575d0e41205b3b78f5c3b0252 type aufs (rw,relatime,si=9afe73eb3db63d01,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/4df767afceac34de4195dd7e51836ba5c6e56dbb85f38653899c9c2af19e4d50 type aufs (rw,relatime,si=9afe73eb3d60ed01,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/9acda045e292d3269308ef47a278e30b0675d39bd4fc830362ac9957098e755b/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/d77e55a77a91 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/d1f49092effce03abd75bd7e5cebe7460b178a02ef5df72a0aed484282d0b42f/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/38c1466464e54966fb4e51c58961ff5e6d09162f16e41613140adde5df84a053/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/7bd36e32b860 type nsfs (rw)
nsfs on /var/run/docker/netns/bc8a85460dae type nsfs (rw)
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/44faa6e633879a70ff6e95563a3edb4af2340dcd76afab945092041791995e8f type aufs (rw,relatime,si=9afe73eb3c1abd01,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/4369f59388edb92a5703a3df82bab8ca4316b3b49b3c4ac8997ef9d90c63d81a type aufs (rw,relatime,si=9afe73eb3d39fd01,dio,dirperm1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/09765b2db4ebe58565d96853766e16a4c9565a7337477dcb3b7aebf2c81b31f7 type aufs (rw,relatime,si=9afe73eb3dce3d01,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/908a572e537bb73ec585d334bb2da84b3b197f438c96ad706bc6154597440a77/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
192.168.64.1:/Users/vm386/Projects/docksal/guwordpress on /mnt/sda1/var/lib/docker/volumes/guwordpress_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
shm on /mnt/sda1/var/lib/docker/containers/019e7c9f9da0a949cf2e0d4db7f14579dbf585c3f3ae852c305a2c859b733727/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /mnt/sda1/var/lib/docker/containers/17d450eb7763b02e50c249a347cca24f24d80ef2374d921c61272bd7b7417b1b/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/31309d03a815 type nsfs (rw)
nsfs on /var/run/docker/netns/71bcb548612d type nsfs (rw)
nsfs on /var/run/docker/netns/52de9f07dc0b type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/bcbe239451b1ca5c46459325721f716440bd088f7504346c95a8a84557f27801 type aufs (rw,relatime,si=9afe73eb68b88d01,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/4a9cad1edb5b891d8122ca63e1b61a17504a4e3ddfe78558fe9bc0a86e2cd150/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/ead6cf9dd14c type nsfs (rw)
  ```

</details>
