### ISSUE TITLE
Database Container is Unstable

### ISSUE THREAD

**Issue by nplowman** [docksal/docksal#471]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
I have been having pretty consistent stability issues with the mysql database container.

Examples of the symptoms I have been seeing are:
* A Docksal project will be running fine. When I switch to working on another Docksal project and return to the first project, I will find that the db container has crashed. If I try to run 'fin bash db' or 'fin sqlc' I get an error like:
```
Error response from daemon: Container f4c2e94773244262d13fd689b3576a97fb1be2555bde1e9e1d83bc403bbbc83a is not running
```
I'll have to run 'fin restart' 2-3 times to get the container back up and running.
* Database container will crash while importing larger databases, resulting in the same error shown above.

---------------------------------------------------
Debugging Information
---------------------------------------------------
I don't have a good working theory yet as to why the instability issues are happening. 
I originally suspected that I was running out of resources (i.e. not enough hard drive space or RAM). This does not seem to be the case. I'll post some information about the stack setup on the project I've been having problems with, in case it is helpful.

Project Database Stack:
```
  # DB
  db:
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
      - "${MYSQL_PORT_MAPPING:-3306}"
    volumes:
      - project_root:/var/www:ro,nocopy  # Project root volume
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-default}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
```

Docskal VM Hard Drive usage
```
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                74.6G     15.1G     55.6G  21% /mnt/sda1
```

Docksal VM RAM usage
```
Total Memory size:     2048MB
Available Memory:	940 MB
Available Swap:		11 MB
```
