### ISSUE TITLE
Install mssql_connect for PHP 5.6

### ISSUE THREAD

**Issue by budandbreakfast** [docksal/docksal#472]
We're looking for instructions on how to add PHP mssql connect to the current 5.6 image. We tried this which used to work on the 1.3 images:

sudo apt-get install -y freetds-common freetds-bin unixodbc php5-sybase

But it says:

E: Package 'php5-sybase' has no installation candidate

**Steps to reproduce the issue:**

1. Start an environement based off of these settings:

DOCKSAL_STACK=default
WEB_IMAGE='docksal/web:apache2.2'
DB_IMAGE='docksal/db:mysql-5.7'
CLI_IMAGE='docksal/cli:php5.6'

2. Run "sudo apt-get update"
3. Run "sudo apt-get install -y freetds-common freetds-bin unixodbc php5-sybase

**Describe the results you received:**

E: Package 'php5-sybase' has no installation candidate

**Describe the results you expected:**

Error "Call to undefined function mssql_connect" would go away

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: national
COMPOSE_FILE:
/Users/drew.michael/.docksal/stacks/volumes-bind.yml
/Users/drew.michael/.docksal/stacks/stack-default.yml
/Users/drew.michael/projects/national/.docksal/docksal.yml
ENV_FILE:
/Users/drew.michael/projects/national/.docksal/docksal.env

PROJECT_ROOT: /Users/drew.michael/projects/national
DOCROOT: docroot
VIRTUAL_HOST: national.docksal
VIRTUAL_HOST_ALIASES: *.national.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32776

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '502'
      HOST_UID: '503'
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:php5.6
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:mysql-5.7
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.national.docksal
    user: root
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:apache2.2
    labels:
      io.docksal.project-root: /Users/drew.michael/projects/national
      io.docksal.virtual-host: national.docksal,*.national.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/drew.michael/projects/national
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Mac OS X 10.11.6
Darwin Spare-Mac-Book-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64
Mode: VirtualBox VM

███  FIN
fin version: 1.43.2

███  ENVIRONMENT
DOCKER_HOST		| tcp://192.168.64.100:2376
------------------------------------------------------------
DOCKSAL_NFS_PATH	| 

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false

███  DOCKER INFO
Containers: 114
 Running: 25
 Paused: 0
 Stopped: 89
Images: 35
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 681
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.89-boot2docker
Operating System: Boot2Docker 17.09.0-ce (TCL 7.2); HEAD : 06d5c35 - Wed Sep 27 23:22:43 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.858GiB
Name: docksal
ID: LWS5:BTIT:WLKB:HOEQ:U34C:WAOU:KY3W:HZP3:AKHW:7J2V:WLRQ:2WHU
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 288
 Goroutines: 185
 System Time: 2018-03-05T21:02:11.467137461Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.17.1
docker-compose version 1.17.1, build 6d101fb
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016

███  DOCKER MACHINE
EXPECTED VERSION: 0.13.0
docker-machine version 0.13.0, build 9ba6da9

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.09.0-ce   

███  DOCKER: IMAGES
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
docksal/cli                  php5.6              79efc3c265e6        4 weeks ago         890MB
docksal/db                   mysql-5.7           6149fd825f49        8 weeks ago         408MB
docksal/cli                  edge-php7.1         4ac5775021df        8 weeks ago         910MB
backstopjs/backstopjs        latest              0ab1ada9bb16        2 months ago        694MB
docksal/cli                  edge-php7           1903c6086d28        4 months ago        799MB
docksal/cli                  edge-php5           7122bc26ad27        4 months ago        851MB
docksal/cli                  1.3-php7            19bdddfeab89        5 months ago        759MB
docksal/cli                  1.3-php5            80248f5ea845        5 months ago        814MB
docksal/backstopjs           latest              b943a42c70b6        5 months ago        700MB
docksal/web                  2.1-apache2.4       32c1d32eba6d        6 months ago        87.5MB
docksal/web                  2.1-apache2.2       f64644fd6d46        6 months ago        81MB
docksal/web                  apache2.2           831d93f02bc2        6 months ago        81MB
wernight/ngrok               latest              7b56f07b2302        6 months ago        27.1MB
blackfire/blackfire          latest              b7c6980c1ce9        6 months ago        21.6MB
docksal/web                  2.0-apache2.4       7f75db9a6aa7        7 months ago        87.5MB
docksal/web                  2.0-apache2.2       f5675d46dd96        7 months ago        81MB
docksal/vhost-proxy          1.1                 898fb21e7f2d        7 months ago        158MB
docksal/db                   1.1-mysql-5.7       8d323c436c28        7 months ago        412MB
docksal/db                   1.1-mysql-5.6       6feb79af9597        7 months ago        298MB
docksal/db                   1.1-mysql-5.5       aa748dc21dd4        7 months ago        256MB
selenium/standalone-chrome   latest              1dec27211cb6        8 months ago        835MB
memcached                    latest              add80e4f4120        8 months ago        82.6MB
mailhog/mailhog              latest              669347153085        10 months ago       19.1MB
docksal/cli                  1.2-php5            11f47dc7d024        11 months ago       845MB
docksal/cli                  1.2-php7            aef362412c9f        11 months ago       787MB
docksal/vhost-proxy          1.0                 2c8a8b1e62c4        12 months ago       164MB
docksal/dns                  1.0                 20c7a535479d        13 months ago       61.6MB
docksal/ssh-agent            1.0                 148220cc033d        13 months ago       12.2MB
docksal/web                  1.0-apache2.2       a9c03f8a5f0f        13 months ago       188MB
docksal/web                  1.0-apache2.4       1e2aa01c55d6        13 months ago       259MB
docksal/db                   1.0-mysql-5.7       35f1494f03b6        13 months ago       400MB
docksal/db                   1.0-mysql-5.6       7c932a2f6a71        13 months ago       328MB
docksal/db                   1.0-mysql-5.5       9fb8c0aed5fc        13 months ago       255MB
docksal/solr                 1.0-solr4           fa6b236caf06        14 months ago       546MB
docksal/solr                 1.0-solr3           628ee3683031        14 months ago       471MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                    PORTS                                      NAMES
83d451d98413        docksal/web:apache2.2        "httpd-foreground"       18 minutes ago      Up 18 minutes             80/tcp, 443/tcp                            national_web_1
1e1b1662bd40        docksal/cli:php5.6           "/opt/startup.sh s..."   18 minutes ago      Up 18 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                 national_cli_1
d5267f8287cf        docksal/db:mysql-5.7         "/entrypoint.sh my..."   18 minutes ago      Up 18 minutes             0.0.0.0:32776->3306/tcp                    national_db_1
03c041b1b961        docksal/web:2.1-apache2.2    "httpd-foreground"       31 minutes ago      Up 31 minutes             80/tcp, 443/tcp                            ogmailinglist_web_1
0e6334987d83        docksal/cli:1.3-php5         "/opt/startup.sh s..."   32 minutes ago      Up 31 minutes (healthy)   22/tcp, 9000/tcp                           ogmailinglist_cli_1
44ae658623e0        mailhog/mailhog              "MailHog"                32 minutes ago      Up 32 minutes             80/tcp, 1025/tcp, 8025/tcp                 ogmailinglist_mail_1
383ac9a88c28        docksal/db:1.1-mysql-5.5     "/entrypoint.sh my..."   32 minutes ago      Up 32 minutes             0.0.0.0:32774->3306/tcp                    ogmailinglist_db_1
3b9bcce3f922        mailhog/mailhog              "MailHog"                38 minutes ago      Up 27 minutes             80/tcp, 1025/tcp, 8025/tcp                 national_mail_1
0fcc91dd15f0        docksal/web:2.1-apache2.2    "httpd-foreground"       13 days ago         Up 2 hours                80/tcp, 443/tcp                            golfzingmaster_web_1
3bd65182acbc        docksal/cli:1.3-php5         "/opt/startup.sh s..."   13 days ago         Up 2 hours (healthy)      22/tcp, 9000/tcp                           golfzingmaster_cli_1
5a7169e7ee29        backstopjs/backstopjs        "top -b"                 2 weeks ago         Up 2 hours                                                           golfzingmaster_backstop_1
fbf75a4ca99c        mailhog/mailhog              "MailHog"                2 weeks ago         Up 2 hours                80/tcp, 1025/tcp, 8025/tcp                 golfzingmaster_mail_1
094312cb13d7        memcached                    "docker-entrypoint..."   2 weeks ago         Up 2 hours                11211/tcp                                  golfzingmaster_memcached_1
1dcdb240b184        selenium/standalone-chrome   "/opt/bin/entry_po..."   2 weeks ago         Up 2 hours                4444/tcp                                   golfzingmaster_browser_1
38408431978f        docksal/db:1.1-mysql-5.5     "/entrypoint.sh my..."   2 weeks ago         Up 2 hours                0.0.0.0:32769->3306/tcp                    golfzingmaster_db_1
6beaeb2a0c00        blackfire/blackfire          "blackfire-agent"        2 weeks ago         Up 2 hours                8707/tcp                                   golfzingmaster_blackfire_1
6a99cf2cb0af        docksal/web:2.1-apache2.4    "httpd-foreground"       4 weeks ago         Up 4 hours                80/tcp, 443/tcp                            sem_web_1
699de9273afd        docksal/cli:edge-php7.1      "/opt/startup.sh s..."   4 weeks ago         Up 4 hours (healthy)      22/tcp, 9000/tcp                           sem_cli_1
f5779681e5a9        mailhog/mailhog              "MailHog"                4 weeks ago         Up 4 hours                80/tcp, 1025/tcp, 8025/tcp                 sem_mail_1
c0858ebb3e63        blackfire/blackfire          "blackfire-agent"        4 weeks ago         Up 4 hours                8707/tcp                                   sem_blackfire_1
f164a8809c2e        docksal/db:1.1-mysql-5.6     "/entrypoint.sh my..."   4 weeks ago         Up 4 hours                0.0.0.0:32768->3306/tcp                    sem_db_1
831f887d1edd        memcached                    "docker-entrypoint..."   4 weeks ago         Up 4 hours                11211/tcp                                  sem_memcached_1
544d62e721ff        docksal/ssh-agent:1.0        "/run.sh ssh-agent"      4 weeks ago         Up 4 hours                                                           docksal-ssh-agent
80b7a2d21c99        docksal/dns:1.0              "/opt/entrypoint.s..."   4 weeks ago         Up 4 hours                192.168.64.100:53->53/udp                  docksal-dns
feba16cb9804        docksal/vhost-proxy:1.1      "docker-entrypoint..."   4 weeks ago         Up 4 hours                0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.1.28r117968

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/drew.michael/projects/sem on /mnt/sda1/var/lib/docker/volumes/sem_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/drew.michael/projects/golfzing-master on /mnt/sda1/var/lib/docker/volumes/golfzingmaster_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/drew.michael/projects/og-mailinglist on /mnt/sda1/var/lib/docker/volumes/ogmailinglist_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/drew.michael/projects/national on /mnt/sda1/var/lib/docker/volumes/national_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                93.6G     59.4G     29.3G  67% /mnt/sda1

███  RAM Usage
             total       used       free     shared    buffers     cached
Mem:       4045564    3831672     213892     256344     141640    1781808
-/+ buffers/cache:    1908224    2137340
Swap:      1941732    1941616        116

███  RAM Usage per container
CONTAINER                    CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
national_web_1               0.00%               3.781MiB / 3.858GiB   0.10%               243kB / 332kB       410kB / 0B          7
national_cli_1               0.00%               67.02MiB / 3.858GiB   1.70%               101MB / 3.89MB      41.6MB / 153MB      5
national_db_1                0.04%               313.8MiB / 3.858GiB   7.94%               2.61MB / 15.4MB     31.8MB / 300MB      28
ogmailinglist_web_1          0.00%               3.648MiB / 3.858GiB   0.09%               107kB / 226kB       3.99MB / 0B         7
ogmailinglist_cli_1          0.03%               32.69MiB / 3.858GiB   0.83%               46.7MB / 30.5MB     79.3MB / 7.76MB     6
ogmailinglist_mail_1         0.00%               1.648MiB / 3.858GiB   0.04%               1.46kB / 0B         7.07MB / 0B         4
ogmailinglist_db_1           0.05%               119.1MiB / 3.858GiB   3.02%               30.3MB / 39.8MB     24.8MB / 485MB      16
national_mail_1              0.00%               1.645MiB / 3.858GiB   0.04%               1.21kB / 0B         258kB / 0B          4
golfzingmaster_web_1         0.00%               1.215MiB / 3.858GiB   0.03%               11.4MB / 40.1MB     6.42MB / 0B         8
golfzingmaster_cli_1         0.03%               3.633MiB / 3.858GiB   0.09%               139MB / 79.3MB      106MB / 57.3kB      7
golfzingmaster_backstop_1    0.00%               64KiB / 3.858GiB      0.00%               1.15kB / 0B         1.5MB / 0B          1
golfzingmaster_mail_1        0.00%               340KiB / 3.858GiB     0.01%               1.2kB / 0B          4.1kB / 0B          4
golfzingmaster_memcached_1   0.00%               20.52MiB / 3.858GiB   0.52%               5.5MB / 23.7MB      4.1kB / 0B          7
golfzingmaster_browser_1     0.11%               38.36MiB / 3.858GiB   0.97%               1.2kB / 0B          73.2MB / 0B         21
golfzingmaster_db_1          0.06%               479.9MiB / 3.858GiB   12.15%              62.4MB / 58.9MB     1.03GB / 820MB      16
golfzingmaster_blackfire_1   0.22%               3.316MiB / 3.858GiB   0.08%               114kB / 7.06kB      5.34MB / 0B         6
sem_web_1                    0.07%               7.184MiB / 3.858GiB   0.18%               8.13MB / 12.7MB     8MB / 0B            109
sem_cli_1                    0.02%               44.88MiB / 3.858GiB   1.14%               476MB / 103MB       65.4MB / 8.19kB     7
sem_mail_1                   0.00%               1.668MiB / 3.858GiB   0.04%               1.79kB / 0B         8.99MB / 0B         4
sem_blackfire_1              0.20%               4.246MiB / 3.858GiB   0.11%               123kB / 8.89kB      14MB / 0B           6
sem_db_1                     0.04%               4.438MiB / 3.858GiB   0.11%               56.9MB / 239MB      53.6MB / 318MB      25
sem_memcached_1              0.01%               200KiB / 3.858GiB     0.00%               38.7MB / 232MB      3.24MB / 0B         7
docksal-ssh-agent            0.00%               584KiB / 3.858GiB     0.01%               2.15kB / 0B         5.82MB / 0B         2
docksal-dns                  0.11%               6.469MiB / 3.858GiB   0.16%               183kB / 248kB       30.8MB / 4.1kB      10
docksal-vhost-proxy          0.14%               11.93MiB / 3.858GiB   0.30%               64.9MB / 66.4MB     69.1MB / 184kB      12
Spare-Mac-Book-Pro:national drew.michael$ 
  ```

</details>

Side note, this all started because we're trying to connect to a MSSQL server that we need to be on a VPN to connect to. We can connect from our computers but from the container it just times out. I am not sure if it's a NAT issue with the container or something but being unable to install mssql on newer containers makes it hard for us to see if the newer containers work somehow (although a ping to the IP from the newer container also times out).
