### ISSUE TITLE
"fin system stop" stops non-Docksal containers too

### ISSUE THREAD

**Issue by BR0kEN-** [docksal/docksal#480]
**Description**

Running `fin system stop` we're getting all containers, that don't have the `system` word within labels, stopped.

```bash
Stopping all running services from all projects...
drupal8_web_1
drupal8_cli_1
drupal8_db_1
webserver.loc
Disabling automatic *.docksal DNS resolver...
Password:
Clearing DNS cache...
Stopping Docksal system services...
```

In the example above the `webserver.loc` is a custom container, created a long time before the Docksal has been installed on a host.

**Steps to reproduce the issue:**

1. Create your own container via `docker run ...`.
2. Setup a Docksal-based project via `fin init`.
3. Do the `fin system stop`.

**Describe the results you received:**

All the containers without the `system` word in labels are being stopped.

**Describe the results you expected:**

Only Docksal-related containers should be stopped.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: drupal8
COMPOSE_FILE:
/Users/BR0kEN/.docksal/stacks/overrides-osxfs.yml
/Users/BR0kEN/.docksal/stacks/volumes-bind.yml
/Users/BR0kEN/.docksal/stacks/stack-default.yml
/usr/local/share/cikit/drupal8/.docksal/docksal.yml
ENV_FILE:
/usr/local/share/cikit/drupal8/.docksal/docksal.env

PROJECT_ROOT: /usr/local/share/cikit/drupal8
DOCROOT: docroot
VIRTUAL_HOST: drupal8.docksal
VIRTUAL_HOST_ALIASES: *.drupal8.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32805

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '501'
      VIRTUAL_HOST: drupal8.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.0-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - /usr/local/share/cikit/drupal8:/var/www:rw,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /usr/local/share/cikit/drupal8
      io.docksal.virtual-host: drupal8.docksal,*.drupal8.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /usr/local/share/cikit/drupal8
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Mac OS X 10.12.6
Darwin Macintosh 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin
Mode: VirtualBox VM

███  FIN
fin version: 1.50.3

███  ENVIRONMENT
DOCKER_HOST		|
 WARNING:  Non-default DOCKER_HOST
seq: format ‘-’ has no % directive

DOCKSAL_NFS_PATH	|

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.12.0-ce
 API version:  1.35 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   c97c6d6
 Built:        Wed Dec 27 20:12:29 2017
 OS/Arch:      linux/amd64
 Experimental: true

███  DOCKER INFO
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 13
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: J5AQ:RAT6:7TBV:NHKR:54GV:SC65:ZRQP:AT43:O3XG:I7PH:IPML:EO2N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 79
 Goroutines: 103
 System Time: 2018-03-21T15:18:14.839005014Z
 EventsListeners: 4
Http Proxy: docker.for.mac.http.internal:3128
Https Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.19.0
docker-compose version 1.19.0, build 9e633ef
docker-py version: 2.7.0
CPython version: 2.7.10
OpenSSL version: OpenSSL 0.9.8zh 14 Jan 2016

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.2.8r121009

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.44.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       127.0.0.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

Name:            vboxnet10
GUID:            786f6276-656e-4174-b000-0a002700000a
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:0a
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet10

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       10.1.1.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

Name:            vboxnet3
GUID:            786f6276-656e-4374-8000-0a0027000003
DHCP:            Disabled
IPAddress:       10.0.33.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:03
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet3

Name:            vboxnet4
GUID:            786f6276-656e-4474-8000-0a0027000004
DHCP:            Disabled
IPAddress:       10.0.0.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:04
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet4

Name:            vboxnet5
GUID:            786f6276-656e-4574-8000-0a0027000005
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:05
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet5

Name:            vboxnet6
GUID:            786f6276-656e-4674-8000-0a0027000006
DHCP:            Disabled
IPAddress:       192.168.137.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:06
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet6

Name:            vboxnet7
GUID:            786f6276-656e-4774-8000-0a0027000007
DHCP:            Disabled
IPAddress:       192.168.198.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:07
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet7

Name:            vboxnet8
GUID:            786f6276-656e-4874-8000-0a0027000008
DHCP:            Disabled
IPAddress:       192.168.59.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:08
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet8

Name:            vboxnet9
GUID:            786f6276-656e-4974-8000-0a0027000009
DHCP:            Disabled
IPAddress:       172.28.128.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:09
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet9

███  NFS EXPORTS
# VAGRANT-BEGIN: 501 65cd4cfa-4bd5-41fe-87c5-858c5cd6367a
"/Users/BR0kEN/pfqaplatform" 192.168.56.132 192.168.56.133 -alldirs -mapall=501:20
# VAGRANT-END: 501 65cd4cfa-4bd5-41fe-87c5-858c5cd6367a
# VAGRANT-BEGIN: 501 186c7b63-1eff-4722-8b9d-a9fae9d80df6
"/Users/BR0kEN/pfviagractcouk" 192.168.99.99 -alldirs -mapall=501:20
# VAGRANT-END: 501 186c7b63-1eff-4722-8b9d-a9fae9d80df6
# VAGRANT-BEGIN: 501 2b8fdcaf-79e3-4c2e-81b9-5ad8fc977946
"/Users/BR0kEN/onlinevolunteering" 192.168.56.132 -alldirs -mapall=501:20
# VAGRANT-END: 501 2b8fdcaf-79e3-4c2e-81b9-5ad8fc977946

███  HDD Usage
Docker machine docksal is not created. Use 'fin vm start' or 'fin up'.

███  RAM Usage
Docker machine docksal is not created. Use 'fin vm start' or 'fin up'.

███  RAM Usage per container
CONTAINER             CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
drupal8_web_1         0.30%               5.52MiB / 1.952GiB    0.28%               1.08kB / 0B         7.5MB / 0B          82
drupal8_cli_1         0.03%               30.66MiB / 1.952GiB   1.53%               24.1MB / 54.3MB     70.3MB / 1.51MB     5
drupal8_db_1          0.09%               512.5MiB / 1.952GiB   25.64%              54.3MB / 23.9MB     42.5MB / 1.25GB     22
docksal-ssh-agent     0.00%               1.133MiB / 1.952GiB   0.06%               1.04kB / 0B         2.27MB / 0B         2
docksal-dns           0.45%               16.3MiB / 1.952GiB    0.82%               1.96kB / 1.17kB     18MB / 0B           12
docksal-vhost-proxy   0.49%               19.23MiB / 1.952GiB   0.96%               4.13kB / 0B         39.4MB / 8.19kB     13
dns                   0.02%               16.45MiB / 1.952GiB   0.82%               1.11kB / 0B         258kB / 0B          9
webserver.loc         0.00%               2.012MiB / 1.952GiB   0.10%               3.87kB / 0B         10.9MB / 24.6kB     0
  ```

</details>
