### ISSUE TITLE
Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy 

### ISSUE THREAD

**Issue by sean-e-dietrich** [docksal/docksal#482]
**Description**

**Steps to reproduce the issue:**

1. type `fin status` or `fin start` in any project

**Describe the results you received:**

Getting the following error message

```
fin start
 ALERT:  Some Docksal services were not running
         Restarting Docksal system services...
Resetting network settings...
Resetting Docksal services...
 * proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (0d18d6c321fd006ac0dc94620aa80de9f826e2366363a9c818ced82bfc5320b6): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 * dns and resolver for .docksal domain
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-dns (8083a6c34650b86943e4ae7eb022fc08558602d0c369f7496b5f2fa720d07af5): Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
 * ssh-agent
Identity added: id_rsa (id_rsa)
Starting services...
Starting wisconsinprivatecolleges_db_1 ...
Starting wisconsinprivatecolleges_cli_1 ...
Starting wisconsinprivatecolleges_cli_1 ... done
Starting wisconsinprivatecolleges_web_1 ... done
Waiting for wisconsinprivatecolleges_cli_1 to become ready...
Connected vhost-proxy to "wisconsinprivatecolleges_default" network.
Virtual Host: wisconsinprivatecolleges.docksal
```

**Describe the results you expected:**

Would assume the project would be starting. 

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
[101m ALERT: [0m [0;91mSome Docksal services were not running[0m
         Restarting Docksal system services...
[0;32mResetting network settings...[0m
[0;32mResetting Docksal services...[0m
 * proxy
 * dns and resolver for .docksal domain
[0;32mEnabling automatic *.docksal DNS resolver...[0m
[0;32mClearing DNS cache...[0m
 * ssh-agent
Identity added: id_rsa (id_rsa)
---------------------
COMPOSE_PROJECT_NAME_SAFE: wisconsinprivatecolleges
COMPOSE_FILE:
/Users/nikki/.docksal/stacks/volumes-bind.yml
/Users/nikki/docksal/wisconsin-private-colleges/.docksal/docksal.yml
ENV_FILE:
/Users/nikki/docksal/wisconsin-private-colleges/.docksal/docksal.env

PROJECT_ROOT: /Users/nikki/docksal/wisconsin-private-colleges
DOCROOT: .
VIRTUAL_HOST: wisconsinprivatecolleges.docksal
VIRTUAL_HOST_ALIASES: *.wisconsinprivatecolleges.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: .
      HOST_GID: '20'
      HOST_UID: '501'
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      VIRTUAL_HOST: wisconsinprivatecolleges.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /Users/nikki/docksal/wisconsin-private-colleges/.docksal/etc/drush:/etc/drush:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.wisconsinprivatecolleges.docksal
    user: root
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/.
      APACHE_FILE_PROXY: http://www.wisconsinsprivatecolleges.org
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/nikki/docksal/wisconsin-private-colleges
      io.docksal.virtual-host: wisconsinprivatecolleges.docksal,*.wisconsinprivatecolleges.docksal
    volumes:
    - /Users/nikki/docksal/wisconsin-private-colleges/.docksal/etc/apache:/usr/local/apache2/conf/extra/includes:ro
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/nikki/docksal/wisconsin-private-colleges
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Mac OS X 10.11.6
Darwin kanopi-mbp.3521.dhcp.asu.edu 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64
Mode: VirtualBox VM

███  FIN
fin version: 1.50.3

███  ENVIRONMENT
DOCKER_HOST		| tcp://192.168.64.102:2376
[43;90m WARNING: [0m [1;33mNon-default DOCKER_HOST[0m
------------------------------------------------------------
DOCKSAL_NFS_PATH	| /Users/nikki/docksal

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false

███  DOCKER INFO
Containers: 17
 Running: 5
 Paused: 0
 Stopped: 12
Images: 9
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 142
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.89-boot2docker
Operating System: Boot2Docker 17.09.0-ce (TCL 7.2); HEAD : 06d5c35 - Wed Sep 27 23:22:43 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955GiB
Name: docksal
ID: KIKG:DCQG:PAUT:4MNL:E35B:SAJW:FLG5:ECBV:FXQS:OFHO:PBPX:BDIR
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 60
 Goroutines: 56
 System Time: 2018-03-22T20:50:51.120752221Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.19.0
docker-compose version 1.19.0, build 9e633ef
docker-py version: 2.7.0
CPython version: 2.7.10
OpenSSL version: OpenSSL 0.9.8zh 14 Jan 2016

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.102:2376           v17.09.0-ce   

███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/vhost-proxy   1.2                 a1c980537985        7 days ago          166MB
docksal/cli           1.3-php7            19bdddfeab89        6 months ago        759MB
docksal/cli           1.3-php5            80248f5ea845        6 months ago        814MB
docksal/web           2.1-apache2.4       32c1d32eba6d        7 months ago        87.5MB
docksal/db            1.1-mysql-5.6       6feb79af9597        8 months ago        298MB
mailhog/mailhog       latest              669347153085        11 months ago       19.1MB
docksal/dns           1.0                 20c7a535479d        14 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        14 months ago       12.2MB
docksal/solr          1.0-solr3           628ee3683031        14 months ago       471MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                        NAMES
144e72c64837        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      53 seconds ago      Up 52 seconds                                          docksal-ssh-agent
a8d3cc3e15bc        docksal/web:2.1-apache2.4   "httpd-foreground"       9 minutes ago       Up 49 seconds             80/tcp, 443/tcp              wisconsinprivatecolleges_web_1
c5c4247b26c9        docksal/db:1.1-mysql-5.6    "/entrypoint.sh my..."   9 minutes ago       Up 50 seconds             0.0.0.0:32768->3306/tcp      wisconsinprivatecolleges_db_1
0402105c1420        mailhog/mailhog             "MailHog"                9 minutes ago       Up 50 seconds             80/tcp, 1025/tcp, 8025/tcp   wisconsinprivatecolleges_mail_1
7eff438454db        docksal/cli:1.3-php5        "/opt/startup.sh s..."   9 minutes ago       Up 50 seconds (healthy)   22/tcp, 9000/tcp             wisconsinprivatecolleges_cli_1

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.1.28r117968

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# VAGRANT-BEGIN: 501 52bdcb92-4bfa-4688-bc52-b86ff059c802
"/Users/nikki/Dropbox/work/kanopi/threshold/docroot" 192.168.85.101 -alldirs -mapall=501:20
"/Users/nikki/Dropbox/work/kanopi/threshold/drupal-vm" 192.168.85.101 -alldirs -mapall=501:20
# VAGRANT-END: 501 52bdcb92-4bfa-4688-bc52-b86ff059c802
# <ds-nfs docksal
/Users/nikki/docksal 127.0.0.1 192.168.64.102 -alldirs -maproot=0:0
# ds-nfs>

███  DOCKSAL MOUNTS
192.168.64.1:/Users/nikki/docksal on /Users/nikki/docksal type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/nikki/docksal/wisconsin-private-colleges on /mnt/sda1/var/lib/docker/volumes/wisconsinprivatecolleges_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.3G      3.6G     40.3G   8% /mnt/sda1

███  RAM Usage
             total       used       free     shared    buffers     cached
Mem:       2050284     989992    1060292     200248      28892     298100
-/+ buffers/cache:     663000    1387284
Swap:      1423020          0    1423020

███  RAM Usage per container
CONTAINER                         CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
docksal-ssh-agent                 0.00%               640KiB / 1.955GiB     0.03%               868B / 0B           0B / 0B             2
wisconsinprivatecolleges_web_1    0.07%               2.441MiB / 1.955GiB   0.12%               1.22kB / 0B         8MB / 0B            82
wisconsinprivatecolleges_db_1     0.04%               490.7MiB / 1.955GiB   24.51%              1.31kB / 0B         31.5MB / 45.1kB     21
wisconsinprivatecolleges_mail_1   0.00%               1.629MiB / 1.955GiB   0.08%               1.31kB / 0B         8.92MB / 0B         3
wisconsinprivatecolleges_cli_1    0.02%               16.98MiB / 1.955GiB   0.85%               1.31kB / 0B         55.2MB / 8.19kB     6
  ```

</details>

**Comment by lmakarov** [comment]
@sean-e-dietrich  do you get the same error from `fin system reset`?

`sudo lsof -n -P -i :80 | grep LISTEN` ?

**Comment by sean-e-dietrich** [comment]
@lmakarov when run `fin system reset`

```
➜  wisconsin-private-colleges git:(master) ✗ fin system reset
Resetting network settings...
Password:
Resetting Docksal services...
* proxy
* dns and resolver for .docksal domain
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
* ssh-agent
Identity added: id_rsa (id_rsa)
```

and nothing outputs when the `sudo lsof -n -P -i :80 | grep LISTEN` command is ran.

**Comment by lmakarov** [comment]
Looks like now you should have the vhost-proxy and dns services up and running. But that does not explain what caused the issue in the first place.

See if you can reproduce this by killing the system services

```
fin docker rm -f vhost-proxy
fin docker rm -f dns
```

then doing `fin status`.

If that does not trigger the same error, then you may have had another "stack" (?) binding to ports 80, 443 and 53 on a wildcard IP (`0.0.0.0`). Or maybe there was a glitch in the VirtualBox networking stack.

`sudo lsof -n -P -i :80 | grep LISTEN` would normally show what's using port 80, however, it won't show any of the VirtualBox processes/interfaces (it's a mystery to me why).

**Comment by drnikki** [comment]
Hi @lmakarov thanks for looking at this.  This is actually my system that sean has been helping me debug.  

```
➜  wisconsin-private-colleges git:(master) ✗ fin docker rm -f dns
Error response from daemon: No such container: dns
➜  wisconsin-private-colleges git:(master) ✗ fin status
Name   Command   State   Ports
------------------------------
➜  wisconsin-private-colleges git:(master) ✗
```

**Comment by lmakarov** [comment]
Hi @drnikki, my bad... these are the correct rm commands:

```
fin docker rm -f docksal-vhost-proxy
fin docker rm -f docksal-dns
```

**Comment by sean-e-dietrich** [comment]
@lmakarov I was just helping her out and realized that was the case. We ran those and then ran `fin status` and everything is all good now!

Is it possible it could have been the network causing an issue?

**Comment by lmakarov** [comment]
@sean-e-dietrich 

> Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address
> Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.

These usually mean that something is already listening on those ports, so another service cannot bind to those. In rare cases there may be issues in the VirtualBox network stack, when it does not release the ports properly, but I'm not 100% confident that was the case either.

`fin system reset` is the first thing to try to fix the Docksal system services.

**Comment by njbarrett** [comment]
Hello. I think i am having a similar issue.
Here is the output from `fin system reset`

```
Resetting network settings...
Resetting Docksal services...
 * proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (7a5b8d63544b76857aaa5df3d6a00a9bcd09dc7c3673a64fa9a1739939a0c119): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 * dns and resolver for .docksal domain
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-dns (13223f73ca9c0b9f1a91215297c1883c8a74f768f1c256695134c5c2aa2b6795): Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
 * ssh-agent
Identity added: id_rsa (id_rsa)
```

**Comment by njbarrett** [comment]
Here's the output from `fin status`

```
Nicholass-MacBook-Pro nick$ fin status
 ALERT:  Some Docksal services were not running
         Restarting Docksal system services...
Resetting network settings...
Resetting Docksal services...
 * proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (df1fbe36a892d9260154781286e06b776bf47e55c4d6a1016556af3c3de34a41): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 * dns and resolver for .docksal domain
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-dns (cbfad5318bea29747123ccd1189397ee7c84c2c99c749b68f0b253ee6dd6a8bb): Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
 * ssh-agent
Identity added: id_rsa (id_rsa)
Name   Command   State   Ports
------------------------------
```

**Comment by achekulaev** [comment]
@njbarrett apparently you have something listening on these ports. Try restarting your host. If the problem persists please post outputs of

1. `fin sysinfo`

2. `netstat -a -n tcp | grep -i listen`

**Comment by achekulaev** [comment]
Hey @sean-e-dietrich 
Can this one be closed?

**Comment by sean-e-dietrich** [comment]
@achekulaev yes, this is good to close. This was an issue with the network that the machine was one.

**Comment by svict4** [comment]
I'm encountering the same problem, could we reopen this issue?
Guessing it's unlikely to be an issue with Docksal specifically though.

Problem occured after PC went to sleep for the night.
I'm on WSL Ubuntu on Windows. I've turned off `fastboot` (as that seemed to be an issue with Docker when Googling a bit) and have done a restart. Ports are still in use and unsure how else to kill the program.

<details>
  <summary>fin config output</summary>

```
svict4@DESKTOP-4UL0CBL:/mnt/c/Users/email/Desktop/coding_projects/projectA$ fin config
 ALERT:  Some Docksal services were not running
         Restarting Docksal system services...
Configuring network settings...
Resetting Docksal services...
 * proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (ee3d33e32f860d9d353068d0233993a08fbb917635d1c102fae7910ebe92773c): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 * dns
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-dns (ffa5997c24c09248e21886f170a6a437722d36afc6c91616b124c18a257315e7): Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.
Enabling automatic *.docksal DNS resolver...
 * ssh-agent
---------------------
COMPOSE_PROJECT_NAME_SAFE: projectA
COMPOSE_FILE:
/home/svict4/.docksal/stacks/volumes-bind.yml
/home/svict4/.docksal/stacks/stack-default.yml
/c/Users/email/Desktop/coding_projects/projectA/.docksal/docksal.yml
ENV_FILE:
/c/Users/email/Desktop/coding_projects/projectA/.docksal/docksal.env

PROJECT_ROOT: /c/Users/email/Desktop/coding_projects/projectA
DOCROOT: docroot
VIRTUAL_HOST: projectA.docksal
VIRTUAL_HOST_ALIASES: *.projectA.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '1000'
      HOST_UID: '1000'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: projectA.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.1-php5.6
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - /c/Users/email/Desktop/coding_projects/projectA/db:/docker-entrypoint-initdb.d:ro
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /c/Users/email/Desktop/coding_projects/projectA
      io.docksal.virtual-host: projectA.docksal,*.projectA.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/email/Desktop/coding_projects/projectA
      o: bind
      type: none

---------------------
```

</details>

<details>
  <summary>fin sysinfo output</summary>

  ```
svict4@DESKTOP-4UL0CBL:/mnt/c/Users/email/Desktop/coding_projects/projectA$ fin sysinfo
███  OS
WSL Ubuntu 16.04
Linux DESKTOP-4UL0CBL 4.4.0-17134-Microsoft #48-Microsoft Fri Apr 27 18:06:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
Mode: VirtualBox VM

███  FIN
fin version: 1.60.0

███  ENVIRONMENT
DOCKER_HOST             | 0.0.0.0:2375
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true

███  DOCKER INFO
Containers: 9
 Running: 1
 Paused: 0
 Stopped: 8
Images: 12
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d580103
ID: IW77:NNLK:D2P5:7A4C:IJFN:B6H6:V2IP:3VST:ZZB6:I5CJ:ZLMI:WATB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 29
 Goroutines: 52
 System Time: 2018-06-07T01:47:31.4523224Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

███  DOCKER: IMAGES
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
docksal/cli                    2.1-php7.2          80320da88f6a        2 months ago        876MB
docksal/cli                    2.1-php5.6          f3fb24308f53        2 months ago        905MB
docksal/vhost-proxy            1.2                 a1c980537985        2 months ago        166MB
openaustralia/morph-mitmdump   latest              4a247802de87        3 months ago        462MB
postgres                       9.6                 e4a66744592b        3 months ago        266MB
getfider/fider                 stable              b6d3c51aaf6b        4 months ago        18.2MB
docker4w/nsenter-dockerd       latest              cae870735e91        7 months ago        187kB
docksal/web                    2.1-apache2.4       32c1d32eba6d        9 months ago        87.5MB
docksal/db                     1.1-mysql-5.7       8d323c436c28        10 months ago       412MB
docksal/db                     1.1-mysql-5.6       6feb79af9597        10 months ago       298MB
docksal/dns                    1.0                 20c7a535479d        16 months ago       61.6MB
docksal/ssh-agent              1.0                 148220cc033d        16 months ago       12.2MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                   COMMAND               CREATED             STATUS              PORTS               NAMES
9bacb638dc94        docksal/ssh-agent:1.0   "/run.sh ssh-agent"   12 seconds ago      Up 10 seconds                           docksal-ssh-agent

███  HDD Usage
docker-machine executable was not found. (Try running 'fin update')
  ```

</details>

<details>
<summary>fin system reset output</summary>

```
svict4@DESKTOP-4UL0CBL:/mnt/c/Users/email/Desktop/coding_projects/projectA$ fin system reset
Configuring network settings...
Resetting Docksal services...
 * proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (5a8a0c47127462f831f4e104a108c97aba32e92762d8e54c996d7059505de18a): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 * dns
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-dns (6f20575efe043728c5d37ed7825185fa72fb19803e485ba7db847d4ec7f44f4f): Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.
Enabling automatic *.docksal DNS resolver...
 * ssh-agent
```

</details>

<details>

<summary>fin cleanup output</summary>

```
svict4@DESKTOP-4UL0CBL:/mnt/c/Users/email/Desktop/coding_projects/projectA$ fin cleanup
Checking for orphaned projects...
Removing dangling images...
Total reclaimed space: 0B
Removing dangling volumes...
Total reclaimed space: 0B
Removing dangling networks...
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (9728e48e97052cc35f819c86a97d065ad5202c7ccfb3be4bf253353547c2180e): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
```

</details>

<details>
<summary>netstat -a -n tcp output</summary>

```
svict4@DESKTOP-4UL0CBL:/mnt/c/Users/email/Desktop/coding_projects/projectA$ netstat -a -n tcp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
```

</details>

<details>
<summary>fin status output</summary>

```
svict4@DESKTOP-4UL0CBL:/mnt/c/Users/email/Desktop/coding_projects/projectA$ fin status
 ALERT:  Some Docksal services were not running
         Restarting Docksal system services...
Configuring network settings...
Resetting Docksal services...
 * proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (b44a2aab920f5498b7809b1698f5804ab2d1cd9ec7c12cd488512366c6ec4684): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 * dns
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-dns (778d8cfd37fbc49aa5f2c0a1f55336cf189ac58e9015a120229bcf4e487c89d3): Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.
Enabling automatic *.docksal DNS resolver...
 * ssh-agent
Name   Command   State   Ports
------------------------------
```

</details>
