### ISSUE TITLE
Update Node.js to version 8.x LTS

### ISSUE THREAD

**Issue by maikel-cit** [docksal/docksal#484]
**Description**

Both CLI images _docksal/cli:1.3-php5_ and _docksal/cli:1.3-php7_ have Node.js version 6.x installed and latest LTS version is 8.x.

**Steps to reproduce the issue:**

1. Create a new .docksal environment using stack "default" or "node".
2. Open the console with _fin bash_
3. Check _node_ and _npm_ versions.

**Describe the results you received:**

```
docker@cli:/var/www$ node -v
v6.11.3
docker@cli:/var/www$ npm -v
5.8.0
```

**Describe the results you expected:**

```
docker@cli:/var/www$ node -v
v8.11.0
docker@cli:/var/www$ npm -v
5.8.0
```

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: node
COMPOSE_FILE:
/home/user/.docksal/stacks/volumes-bind.yml
/home/user/.docksal/stacks/stack-default.yml
/home/user/Projects/node/.docksal/docksal.yml
ENV_FILE:
/home/user/Projects/node/.docksal/docksal.env

PROJECT_ROOT: /home/user/Projects/node
DOCROOT: docroot
VIRTUAL_HOST: node.docksal
VIRTUAL_HOST_ALIASES: *.node.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:3308

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '543162881'
      HOST_UID: '543195382'
      VIRTUAL_HOST: node.docksal
      VIRTUAL_PORT: '3000'
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    expose:
    - '3000'
    hostname: cli
    image: docksal/cli:1.3-php7
    labels:
      io.docksal.project-root: /home/user/Projects/node
      io.docksal.virtual-host: node.docksal,*.node.docksal
      io.docksal.virtual-port: '3000'
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 3308:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /home/user/Projects/node
      io.docksal.virtual-host: node.docksal,*.node.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/user/Projects/node
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/cli           1.3-php7            19bdddfeab89        6 months ago        759MB
docksal/cli           1.3-php5            80248f5ea845        6 months ago        814MB
  ```

</details>
