### ISSUE TITLE
error while mounting volume Mac

### ISSUE THREAD

**Issue by rageshchalil** [docksal/docksal#505]
**Description**

installing multisite on Drupal with subsites as symlinks.

**Steps to reproduce the issue:**

1. fin init sitenmae
2. 
3. 

**Describe the results you received:**

Starting fusion_cli_1 ... 
Starting fusion_cli_1 ... error

ERROR: for fusion_cli_1  Cannot start service cli: error while mounting volume '/var/lib/docker/volumes/fusion_project_sites/_data': error while mounting volume with options: type='none' device='/Users/Ragesh/projects/fusion/../../sites' o='bind': no such file or directory

ERROR: for cli  Cannot start service cli: error while mounting volume '/var/lib/docker/volumes/fusion_project_sites/_data': error while mounting volume with options: type='none' device='/Users/Ragesh/projects/fusion/../../sites' o='bind': no such file or directory
ERROR: Encountered errors while bringing up the project.
Virtual Host: jjfusion.docksal,*.jjfusion.docksal
Waiting 10s for MySQL to start...
Creating DB: fusion-demo-site...
Error response from daemon: Container ce17ab31d2ec890c20d7dd20e15ef69111cc7eec7484c57aad4aed161247bf5e is not running
 ERROR:  DB creation failed.

**Describe the results you expected:**

should have configured the website

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
fin config
---------------------
COMPOSE_PROJECT_NAME_SAFE: fusion
COMPOSE_FILE:
/Users/Ragesh/.docksal/stacks/overrides-osxfs.yml
/Users/Ragesh/.docksal/stacks/volumes-bind.yml
/Users/Ragesh/.docksal/stacks/stack-default.yml
/Users/Ragesh/projects/fusion/.docksal/docksal.yml
ENV_FILE:
/Users/Ragesh/projects/fusion/.docksal/docksal.env

PROJECT_ROOT: /Users/Ragesh/projects/fusion
DOCROOT: docroot
VIRTUAL_HOST: jjfusion.docksal,*.jjfusion.docksal
VIRTUAL_HOST_ALIASES: *.jjfusion.docksal,*.jjfusion.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32774

Docker Compose configuration
---------------------
services:
  browser:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    hostname: browser
    image: selenium/standalone-chrome-debug
    ports:
    - 4444/tcp
    - 5900:5900/tcp
    volumes:
    - project_root:/var/www:rw
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '502'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: jjfusion.docksal,*.jjfusion.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.0-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_sites:/sites:rw
    - /Users/Ragesh/projects/fusion:/var/www:rw,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached:1.4-alpine
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/Ragesh/projects/fusion
      io.docksal.virtual-host: jjfusion.docksal,*.jjfusion.docksal,*.jjfusion.docksal,*.jjfusion.docksal
    volumes:
    - project_sites:/sites:ro
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/Ragesh/projects/fusion
      o: bind
      type: none
  project_sites:
    driver: local
    driver_opts:
      device: /Users/Ragesh/projects/fusion/../../sites
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
   fin sysinfo
███  OS
Mac OS X 10.13.3
Darwin 03HW048752.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
Mode: Docker for Mac

███  FIN
fin version: 1.52.0

███  ENVIRONMENT
DOCKER_HOST		| 
 WARNING:  Non-default DOCKER_HOST
------------------------------------------------------------
DOCKSAL_NFS_PATH	| 

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true

███  DOCKER INFO
Containers: 7
 Running: 6
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: EIOM:HZBI:C2AN:54AT:FBKO:P4ZY:Q2LE:ZG3H:A5AQ:47EM:TCGS:HSAE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 71
 Goroutines: 91
 System Time: 2018-04-23T20:34:20.7916158Z
 EventsListeners: 4
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.19.0
docker-compose version 1.20.1, build 5d8c71b
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2n  7 Dec 2017

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS

███  DOCKER: IMAGES
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
selenium/standalone-chrome-debug   latest              6082abcd21b4        29 hours ago        895MB
docksal/vhost-proxy                1.2                 a1c980537985        5 weeks ago         166MB
docksal/cli                        1.3-php5            80248f5ea845        7 months ago        814MB
docksal/web                        2.1-apache2.4       32c1d32eba6d        8 months ago        87.5MB
docksal/db                         1.1-mysql-5.6       6feb79af9597        9 months ago        298MB
memcached                          1.4-alpine          273374b463b8        9 months ago        7.68MB
docksal/dns                        1.0                 20c7a535479d        15 months ago       61.6MB
docksal/ssh-agent                  1.0                 148220cc033d        15 months ago       12.2MB
docksal/web                        1.0-apache2.2       a9c03f8a5f0f        15 months ago       188MB
docksal/db                         1.0-mysql-5.5       9fb8c0aed5fc        15 months ago       255MB
docksal/cli                        1.0-php5            bde35eb43ad7        15 months ago       801MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
be78f6c0f69e        docksal/ssh-agent:1.0              "/run.sh ssh-agent"      About an hour ago   Up About an hour                                                             docksal-ssh-agent
da838668c0bf        docksal/dns:1.0                    "/opt/entrypoint.sh …"   About an hour ago   Up About an hour    192.168.64.100:53->53/udp                                docksal-dns
07ace2788d9b        docksal/vhost-proxy:1.2            "docker-entrypoint.s…"   About an hour ago   Up About an hour    192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
821ed60ee5de        selenium/standalone-chrome-debug   "/opt/bin/entry_poin…"   About an hour ago   Up About an hour    0.0.0.0:5900->5900/tcp, 0.0.0.0:32775->4444/tcp          fusion_browser_1
683af000e976        docksal/db:1.0-mysql-5.5           "/entrypoint.sh mysq…"   About an hour ago   Up About an hour    0.0.0.0:32774->3306/tcp                                  fusion_db_1
ef0981af6ad7        memcached:1.4-alpine               "docker-entrypoint.s…"   About an hour ago   Up About an hour    11211/tcp                                                fusion_memcached_1

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.1.28r117968

███  VIRTUALBOX NETWORK INTERFACES
███  NFS EXPORTS


███  HDD Usage
Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1   466Gi  152Gi  312Gi    33% 3139339 9223372036851636468    0%   /
devfs          190Ki  190Ki    0Bi   100%     657                   0  100%   /dev
/dev/disk1s4   466Gi  2.0Gi  312Gi     1%       2 9223372036854775805    0%   /private/var/vm
map -hosts       0Bi    0Bi    0Bi   100%       0                   0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0                   0  100%   /home
/dev/disk2s1   1.6Gi  1.2Gi  371Mi    78%     415          4294966864    0%   /Volumes/Docker

███  RAM Usage
Mach Virtual Memory Statistics: (page size of 4096 bytes)
Pages free:                               15982.
Pages active:                           1767387.
Pages inactive:                         1709001.
Pages speculative:                         4653.
Pages throttled:                              0.
Pages wired down:                        599731.
Pages purgeable:                         153678.
"Translation faults":                  61083431.
Pages copy-on-write:                    5601181.
Pages zero filled:                     32742513.
Pages reactivated:                       868989.
Pages purged:                            918279.
File-backed pages:                      1168745.
Anonymous pages:                        2312296.
Pages stored in compressor:              340810.
Pages occupied by compressor:             96906.
Decompressions:                          269185.
Compressions:                            721520.
Pageins:                                1624698.
Pageouts:                                  5384.
Swapins:                                    512.
Swapouts:                                   512.

███  RAM Usage per container
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
be78f6c0f69e        docksal-ssh-agent     0.00%               1.086MiB / 1.952GiB   0.05%               1.14kB / 0B         0B / 0B             2
da838668c0bf        docksal-dns           0.49%               15.35MiB / 1.952GiB   0.77%               1.14kB / 0B         0B / 0B             12
07ace2788d9b        docksal-vhost-proxy   0.58%               17.73MiB / 1.952GiB   0.89%               2.46kB / 0B         139kB / 4.1kB       15
821ed60ee5de        fusion_browser_1      0.44%               72.41MiB / 1.952GiB   3.62%               1.39kB / 0B         7.17MB / 1.54MB     32
683af000e976        fusion_db_1           0.17%               87.91MiB / 1.952GiB   4.40%               1.32kB / 0B         4.29MB / 423MB      16
ef0981af6ad7        fusion_memcached_1    0.02%               968KiB / 1.952GiB     0.05%               1.3kB / 0B          975kB / 0B          7
03HW048752:fusion Ragesh$ 

  ```

</details>
