### ISSUE TITLE
Docksal is not working on Windows if connected to VPN

### ISSUE THREAD

**Issue by dealancer** [docksal/docksal#509]
**Description**

Docksal is not working on Windows if connected to VPN. I am using Docker Native mode for Docksal.

**Steps to reproduce the issue:**

1. Connect to VPN on Windows machine
2. Restart Docker
3. Run `fin system reset`
4. Run `fin up`
5. See am error message:
```
{ drupal8 } master » fin up
Starting services...
Starting drupal8_cli_1 ...
Starting drupal8_db_1  ... error

ERROR: for drupal8_db_1  Cannot start service db: error while mounting volume '/var/lib/docker/volumStarting drupal8_cli_1 ... error
rs/myrgorodvs/.babun/cygwin/home/myrgorodvs/Projects/drupal8' o='bind': no such file or directory

ERROR: for drupal8_cli_1  Cannot start service cli: error while mounting volume '/var/lib/docker/volumes/drupal8_project_root/_data': error while mounting volume with options: type='none' device='/c/Users/myrgorodvs/.babun/cygwin/home/myrgorodvs/Projects/drupal8' o='bind': no such file or directory

ERROR: for db  Cannot start service db: error while mounting volume '/var/lib/docker/volumes/drupal8_project_root/_data': error while mounting volume with options: type='none' device='/c/Users/myrgorodvs/.babun/cygwin/home/myrgorodvs/Projects/drupal8' o='bind': no such file or directory

ERROR: for cli  Cannot start service cli: error while mounting volume '/var/lib/docker/volumes/drupal8_project_root/_data': error while mounting volume with options: type='none' device='/c/Users/myrgorodvs/.babun/cygwin/home/myrgorodvs/Projects/drupal8' o='bind': no such file or directory
Encountered errors while bringing up the project.
Virtual Host: drupal8.docksal
```

**Describe the results you received:**

See error message above.

**Describe the results you expected:**

Docksal should work when connected to the VPN.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: drupal8
COMPOSE_FILE:
C:/Users/myrgorodvs/.babun/cygwin/home/myrgorodvs/.docksal/stacks/volumes-bind.yml
C:/Users/myrgorodvs/.babun/cygwin/home/myrgorodvs/.docksal/stacks/stack-default.yml
C:/Users/myrgorodvs/.babun/cygwin/home/myrgorodvs/Projects/drupal8/.docksal/docksal.yml
ENV_FILE:
C:/Users/myrgorodvs/.babun/cygwin/home/myrgorodvs/Projects/drupal8/.docksal/docksal.env

PROJECT_ROOT: /c/Users/myrgorodvs/.babun/cygwin/home/myrgorodvs/Projects/drupal8
DOCROOT: docroot
VIRTUAL_HOST: drupal8.docksal
VIRTUAL_HOST_ALIASES: *.drupal8.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: null
      HOST_UID: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: drupal8.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.0-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /c/Users/myrgorodvs/.babun/cygwin/home/myrgorodvs/Projects/drupal8
      io.docksal.virtual-host: drupal8.docksal,*.drupal8.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/myrgorodvs/.babun/cygwin/home/myrgorodvs/Projects/drupal8
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
 Microsoft Windows [Version 10.0.16299.371]
CYGWIN_NT-10.0-WOW NEIM1127VM45N 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
Mode: Docker for Windows

███  FIN
fin version: 1.52.0

███  ENVIRONMENT
DOCKER_HOST             |
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER INFO
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 7
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 2.915GiB
Name: linuxkit-00155d380101
ID: ISRY:I7T5:BWPI:CO4H:BKLR:AZSV:3NWC:O7J7:TQ6G:EJ6X:POHE:773U
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 44
 Goroutines: 68
 System Time: 2018-04-27T04:44:07.2555593Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.19.0
docker-compose version 1.21.0, build 5920eb08
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine.exe version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
docksal   -        virtualbox   Stopped                 Unknown

███  DOCKER: IMAGES
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
docksal/cli                2.0-php7.1          9ba7c35bb83f        5 weeks ago         914MB
docksal/vhost-proxy        1.2                 a1c980537985        6 weeks ago         166MB
docker4w/nsenter-dockerd   latest              cae870735e91        6 months ago        187kB
docksal/web                2.1-apache2.4       32c1d32eba6d        8 months ago        87.5MB
docksal/db                 1.1-mysql-5.6       6feb79af9597        9 months ago        298MB
docksal/dns                1.0                 20c7a535479d        15 months ago       61.6MB
docksal/ssh-agent          1.0                 148220cc033d        15 months ago       12.2MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
16fcfdff5b72        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      4 minutes ago       Up 4 minutes                                                                 docksal-ssh-agent
4ba3bc33b337        docksal/dns:1.0           "/opt/entrypoint.sh …"   4 minutes ago       Up 4 minutes        192.168.64.100:53->53/udp                                docksal-dns
86207d20014f        docksal/vhost-proxy:1.2   "docker-entrypoint.s…"   4 minutes ago       Up 4 minutes        192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.2.8r121009

███  VIRTUALBOX NETWORK INTERFACES
Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            0fbbbff9-712a-4359-bdd2-cfc76ea2a6f8
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::1801:7673:368a:48f0
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:03
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2

Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            115a6690-1748-4a5e-8832-50877717538f
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::5ccd:c4b0:466e:e020
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:05
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter


███  HDD Usage
Caption  FreeSpace     Size
C:       177741836288  252841029632


███  RAM Usage
find: ‘Available Physical Memory’: No such file or directory

███  RAM Usage per container
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
16fcfdff5b72        docksal-ssh-agent     0.00%               1.352MiB / 2.915GiB   0.05%               1.14kB / 0B         303kB / 0B          2
4ba3bc33b337        docksal-dns           0.26%               17.69MiB / 2.915GiB   0.59%               1.21kB / 0B         0B / 0B             10
86207d20014f        docksal-vhost-proxy   0.24%               19.4MiB / 2.915GiB    0.65%               2.46kB / 0B         0B / 4.1kB          14

  ```

</details>
