### ISSUE TITLE
DOCROOT variable not available in custom command with exec_target set

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#515]
Repeating a [ticket](https://github.com/docksal/drupal8/issues/22) from @opdavies in the proper repo 

---

If `exec_target` is set to `cli`, the `$DOCROOT` variable is not available.

I've tested it with a super simple command:

```bash
#!/usr/bin/env bash

#: exec_target = cli

echo $DOCROOT
```

This results in no output.

However, just this does:

```bash
#!/usr/bin/env bash

echo $DOCROOT
```

`DOCROOT` is defined in my `.docksal/docksal.env` file. Other variables such as `$PROJECT_ROOT` are fine.

**Comment by achekulaev** [comment]
@opdavies thanks again for the report. I have confirmed the issue.

As a workaround you can just use plain path to docroot in your custom command.

Why it's not bad? When a regular custom command is executed, it is executed on your host, so `$DOCROOT` will be different for different people. It is why this variable was introduced.

However, when `exec_target` is set, you know that docroot is `/var/www/docroot` (or `/var/www/customfolder` if you customized it in `docksal.env`). And it will be the same for everyone, regardless of OS. 

So as long as `docksal.env` and your command are in sync on what docroot is, everything will work as intended.

**Comment by achekulaev** [comment]
@opdavies if you pass it as an environment variable to the `cli` container, it will be available in your custom commands that execute inside `cli`.

**docksal.yml**

```yml
version: "2.1"

services:
  cli:
    environment:
      - DOCROOT
```

**Comment by opdavies** [comment]
Confirmed that this does fix the problem, and makes the variable available.

**Comment by sean-e-dietrich** [comment]
@opdavies are you running an older version by chance?

I ask because I don't have this issue and haven't been able to reproduce it. It also looks like @lmakarov this was added to the CLI image back in the following [commit](https://github.com/docksal/docksal/commit/74d859349d6b498240c57ec1790cb9caa44d6482#diff-7bb0846603b3ce473b27d928080e660d)

I also do not explicitly add the `DOCROOT` variable to my `.docksal/docksal.yml` file within my project.

I also get the following when executing `fin exec`

```
fin exec 'echo $DOCROOT'
docroot
```

Where my `DOCROOT=docroot`.  Also when running a custom command I don't seem to be running into this either.

My `docksal.yml`
```
...
  cli:
    extends:
      file: '${HOME}/.docksal/stacks/services.yml'
      service: cli
    environment:
      - VIRTUAL_HOST
    volumes:
      - '${PROJECT_ROOT}/.docksal/etc/drush:/etc/drush:ro'
...
```
