### ISSUE TITLE
Drush 9 Works on Mac, but not Windows

### ISSUE THREAD

**Issue by loopy3025** [docksal/docksal#520]
**Description**

Hey, folks. I've got a site using Composer and Drush 9. The site works in Docksal for mac, but not for Windows. I'm getting the "Warning: pcntl_exec(): Error has occurred: (errno 8)...." thing and I've tried all the possibilities that I could summon from google (for example https://github.com/geerlingguy/drupal-vm/issues/904). I'm just at a loss as to why it would work in Mac, but not Windows.

I do NOT have drush installed globally.

**Steps to reproduce the issue:**

1. Pull Drupal  site into windows project folder
2. Set up docksal for windowsas normal
3. Run composer update and composer install
4. Try to run a drush command

**Describe the results you received:**

My site runs in the browser (I can even clear cache) but I get an error when running drush. 

![image](https://user-images.githubusercontent.com/6729935/39636090-38374ea8-4f8d-11e8-86ad-948e6092a7b8.png)

**Describe the results you expected:**

Run Drush 9 commands successfully

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
COMPOSE_PROJECT_NAME_SAFE: regionalcouncilsnygov
COMPOSE_FILE:
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/.docksal/stacks/volumes-bind.yml
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/.docksal/stacks/stack-default.yml
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/regionalcouncils.ny.gov/.docksal/docksal.yml
ENV_FILE:
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/regionalcouncils.ny.gov/.docksal/docksal.env
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/regionalcouncils.ny.gov/.docksal/docksal-local.env

PROJECT_ROOT: /c/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/regionalcouncils.ny.gov
DOCROOT: docroot
VIRTUAL_HOST: regionalcouncilsnygov.docksal
VIRTUAL_HOST_ALIASES: *.regionalcouncilsnygov.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32770

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: null
      HOST_UID: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: regionalcouncilsnygov.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.0-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /c/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/regionalcouncils.ny.gov
      io.docksal.virtual-host: regionalcouncilsnygov.docksal,*.regionalcouncilsnygov.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/regionalcouncils.ny.gov
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
---------------------
$ Fri May 04 11:21 AM ~/projects/regionalcouncils.ny.gov [loopy3025-config-update ?] >:D fin sysinfo
███  OS
 Microsoft Windows [Version 10.0.15063]
CYGWIN_NT-10.0-WOW W2UA7502F80 2.10.0(0.325/5/3) 2018-02-02 15:21 i686 Cygwin
Mode: Docker for Windows

███  FIN
fin version: 1.52.0

███  ENVIRONMENT
DOCKER_HOST             |
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true

███  DOCKER INFO
Containers: 9
 Running: 6
 Paused: 0
 Stopped: 3
Images: 9
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.837GiB
Name: linuxkit-00155de68f3c
ID: WAR6:FTQG:W752:2SIB:OWHM:BYQD:UFFG:YJBW:KCIP:WK26:EL6Z:KPO4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 65
 Goroutines: 86
 System Time: 2018-05-04T15:22:31.6857607Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.19.0
docker-compose version 1.21.1, build 7641a569
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine.exe version 0.14.0, build 89b8332

NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS

███  DOCKER: IMAGES
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
docksal/cli                2.0-php7.1          9ba7c35bb83f        6 weeks ago         914MB
docksal/cli                2.0-php5.6          0fea463bfbd9        6 weeks ago         887MB
docksal/vhost-proxy        1.2                 a1c980537985        7 weeks ago         166MB
docker4w/nsenter-dockerd   latest              cae870735e91        6 months ago        187kB
docksal/cli                1.3-php7            19bdddfeab89        7 months ago        759MB
docksal/web                2.1-apache2.4       32c1d32eba6d        8 months ago        87.5MB
docksal/db                 1.1-mysql-5.6       6feb79af9597        9 months ago        298MB
docksal/dns                1.0                 20c7a535479d        15 months ago       61.6MB
docksal/ssh-agent          1.0                 148220cc033d        15 months ago       12.2MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                 PORTS                                                    NAMES
40d2dfb54767        docksal/web:2.1-apache2.4   "httpd-foreground"       2 hours ago         Up 2 hours             80/tcp, 443/tcp                                          regionalcouncilsnygov_web_1
47ada9055e08        docksal/cli:2.0-php7.1      "/opt/startup.sh sup…"   2 hours ago         Up 2 hours (healthy)   22/tcp, 3000/tcp, 9000/tcp                               regionalcouncilsnygov_cli_1
ac96436df4a4        docksal/db:1.1-mysql-5.6    "/entrypoint.sh mysq…"   2 hours ago         Up 2 hours             0.0.0.0:32770->3306/tcp                                  regionalcouncilsnygov_db_1
2519ed31825d        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      3 hours ago         Up 3 hours                                                                      docksal-ssh-agent
696db54b2993        docksal/dns:1.0             "/opt/entrypoint.sh …"   3 hours ago         Up 3 hours             192.168.64.100:53->53/udp                                docksal-dns
e11c23b68b3a        docksal/vhost-proxy:1.2     "docker-entrypoint.s…"   3 hours ago         Up 3 hours             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  HDD Usage
Caption  FreeSpace     Size
C:       161406087168  255086030848
D:       999846891520  1000068870144
E:


███  RAM Usage
find: ‘Available Physical Memory’: No such file or directory

███  RAM Usage per container
CONTAINER ID        NAME                          CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
40d2dfb54767        regionalcouncilsnygov_web_1   0.60%               18.31MiB / 3.837GiB   0.47%               1.33MB / 4.04MB     1.64MB / 0B         136
47ada9055e08        regionalcouncilsnygov_cli_1   0.07%               77.48MiB / 3.837GiB   1.97%               166MB / 27.5MB      51.2MB / 5.17MB     6
ac96436df4a4        regionalcouncilsnygov_db_1    0.21%               667.4MiB / 3.837GiB   16.99%              25.3MB / 128MB      49.2MB / 623MB      26
2519ed31825d        docksal-ssh-agent             0.00%               1.363MiB / 3.837GiB   0.03%               1.91kB / 0B         5.07MB / 0B         2
696db54b2993        docksal-dns                   0.53%               16.48MiB / 3.837GiB   0.42%               1.09MB / 1.31MB     14.9MB / 0B         13
e11c23b68b3a        docksal-vhost-proxy           0.64%               20.71MiB / 3.837GiB   0.53%               4.05MB / 5.2MB      40.2MB / 20.5kB     12

  ```

</details>
