### ISSUE TITLE
MACOS High Sierra "404 Project not found" when `fin project start`

### ISSUE THREAD

**Issue by powpow12** [docksal/docksal#521]
**Description**

I am having issues setting up with Docksal.  On my first pass, I was able to get [docksal/drupal](https://github.com/docksal/drupal8#setup-instructions) set up by the instructions laid out in the getting started.  All subsequent attempts to work with Dock would return this:

>  ERROR:  Your Docker client is unable to talk to the Docker server.
![image](https://user-images.githubusercontent.com/3721535/39673886-0b112a08-5112-11e8-8b30-8da1701b60c8.png)

I thought that was odd so I tried to `fin create project` which resulted in the same error message.  None of the troubleshooting steps in the prompt helped and the troubleshooting document doesn't mention this error.  When trying to visit the url for the project, I get a 404 Project not found.

![image](https://user-images.githubusercontent.com/3721535/39675168-3ec5800c-5125-11e8-9ab4-465874799773.png)

**Steps to reproduce the issue:**

1. Setup docker/drupal
2. Attempt to `fin create project` a new project

**Describe the results you received:**

Results...

>  ERROR:  Your Docker client is unable to talk to the Docker server.

See above screenshot of errors.

Expected behavior...

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
COMPOSE_PROJECT_NAME_SAFE: drupal8
COMPOSE_FILE:
/Users/rpowell/.docksal/stacks/volumes-bind.yml
/Users/rpowell/.docksal/stacks/stack-default.yml
/Users/rpowell/Projects/drupal8/.docksal/docksal.yml
ENV_FILE:
/Users/rpowell/Projects/drupal8/.docksal/docksal.env

PROJECT_ROOT: /Users/rpowell/Projects/drupal8
DOCROOT: docroot
VIRTUAL_HOST: drupal8.docksal
VIRTUAL_HOST_ALIASES: *.drupal8.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '502'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: drupal8.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.0-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/rpowell/Projects/drupal8
      io.docksal.virtual-host: drupal8.docksal,*.drupal8.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/rpowell/Projects/drupal8
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  ███  OS
Mac OS X 10.13.3
Darwin FA0026.fios-router.home 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
Mode: VirtualBox VM

███  FIN
fin version: 1.52.0

███  ENVIRONMENT
DOCKER_HOST		| tcp://192.168.64.100:2376
------------------------------------------------------------
DOCKSAL_NFS_PATH	| /Users/rpowell/Projects

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false

███  DOCKER INFO
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.89-boot2docker
Operating System: Boot2Docker 17.09.0-ce (TCL 7.2); HEAD : 06d5c35 - Wed Sep 27 23:22:43 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955GiB
Name: docksal
ID: CAX7:P6ZO:7WQ7:2NBQ:P4TM:2KWO:PSMY:IWBV:JPMQ:WOH6:DHQE:MAGH
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 38
 Goroutines: 45
 System Time: 2018-05-06T13:46:37.011732944Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.19.0
docker-compose version 1.19.0, build 9e633ef
docker-py version: 2.7.0
CPython version: 2.7.10
OpenSSL version: OpenSSL 0.9.8zh 14 Jan 2016

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.09.0-ce   

███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/vhost-proxy   1.2                 a1c980537985        7 weeks ago         166MB
docksal/dns           1.0                 20c7a535479d        15 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        15 months ago       12.2MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
aeb64e5cccb1        docksal/vhost-proxy:1.2   "docker-entrypoint..."   5 minutes ago       Up 5 minutes        192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
0c6112257168        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      5 minutes ago       Up 5 minutes                                                                 docksal-ssh-agent
968a0e6b1104        docksal/dns:1.0           "/opt/entrypoint.s..."   5 minutes ago       Up 5 minutes        192.168.64.100:53->53/udp                                docksal-dns

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.2.4r119785

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.50.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

███  NFS EXPORTS
# VAGRANT-BEGIN: 502 b46b1f4d-9815-4f5b-9b3a-c2c2a416c7ba
"/Users/rpowell/Sites/nys_vagrant" "/Users/rpowell/Sites/nys_vagrant/nys_nysenate" 192.168.50.63 -alldirs -mapall=502:20
# VAGRANT-END: 502 b46b1f4d-9815-4f5b-9b3a-c2c2a416c7ba
# VAGRANT-BEGIN: 502 c862ba31-4cee-471a-b4a7-0339f1584092
"/Users/rpowell/Sites/mis_mediacurrent_d8" 192.168.50.32 -alldirs -mapall=502:20
# VAGRANT-END: 502 c862ba31-4cee-471a-b4a7-0339f1584092
# VAGRANT-BEGIN: 502 753cd649-0201-4624-853e-a7426168575b
"/Users/rpowell/Sites/sra/ric_abilitylab/project/src" 192.168.50.101 -alldirs -mapall=502:20
# VAGRANT-END: 502 753cd649-0201-4624-853e-a7426168575b
# VAGRANT-BEGIN: 502 6ee032a4-cadd-4db4-bc9a-2ac32e68c6ec
"/Users/rpowell/Sites/ma_momentum8" 192.168.50.115 -alldirs -mapall=502:20
# VAGRANT-END: 502 6ee032a4-cadd-4db4-bc9a-2ac32e68c6ec
# VAGRANT-BEGIN: 502 5b9054fa-f398-4a3f-804b-269bda121156
"/Users/rpowell/Sites/logisticscom" 192.168.50.48 192.168.50.4 -alldirs -mapall=502:20
# VAGRANT-END: 502 5b9054fa-f398-4a3f-804b-269bda121156
# VAGRANT-BEGIN: 502 392a1072-8492-4b95-aed8-afca89506e3f
"/Users/rpowell/Sites/gtpe_pe_vagrant" "/Users/rpowell/Sites/gtpe_pe_vagrant/gtpe_pe" 192.168.50.82 -alldirs -mapall=502:20
# VAGRANT-END: 502 392a1072-8492-4b95-aed8-afca89506e3f
# VAGRANT-BEGIN: 502 39bbe240-89ae-4982-8787-29a8f11bc3c9
"/Users/rpowell/Sites/ma_manh8" 192.168.50.48 -alldirs -mapall=502:20
# VAGRANT-END: 502 39bbe240-89ae-4982-8787-29a8f11bc3c9
# <ds-nfs docksal
/Users/rpowell/Projects 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  DOCKSAL MOUNTS
192.168.64.1:/Users/rpowell/Projects on /Users/rpowell/Projects type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.3G    309.6M     43.5G   1% /mnt/sda1

███  RAM Usage
             total       used       free     shared    buffers     cached
Mem:       2050284     407392    1642892     194300       9376     249824
-/+ buffers/cache:     148192    1902092
Swap:      1422320          0    1422320

███  RAM Usage per container
CONTAINER             CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
docksal-vhost-proxy   0.22%               18.66MiB / 1.955GiB   0.93%               2.16kB / 1.36kB     0B / 4.1kB          10
docksal-ssh-agent     0.00%               700KiB / 1.955GiB     0.03%               807B / 0B           0B / 0B             2
docksal-dns           0.22%               15.45MiB / 1.955GiB   0.77%               807B / 133B         0B / 0B             8
  ```

</details>

I also have DrupalVm installed but no VMs running.
