### ISSUE TITLE
Default Example setup fails

### ISSUE THREAD

**Issue by justinlevi** [docksal/docksal#540]
$ `fin init` fails with the following response:

<details>
  <summary>git clone && fin init output</summary>

```
{ sites }  » git clone git@github.com:docksal/drupal8.git                                                                           ~/sites
Cloning into 'drupal8'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
remote: Counting objects: 51937, done.
remote: Compressing objects: 100% (802/802), done.
remote: Total 51937 (delta 302), reused 574 (delta 213), pack-reused 50891
Receiving objects: 100% (51937/51937), 30.59 MiB | 1.80 MiB/s, done.
Resolving deltas: 100% (23534/23534), done.
Checking connectivity... done.
Checking out files: 100% (14901/14901), done.
{ sites }  » cd drupal8/                                                                                                            ~/sites
{ drupal8 } master » ls                                                                                                     ~/sites/drupal8
config  docroot  drush  README.md
{ drupal8 } master » ls -ahl                                                                                                ~/sites/drupal8
total 22K
drwxrwxr-x+ 1 JWinter Domain Users    0 May 21 13:59 .
drwxrwxr-x+ 1 JWinter Domain Users    0 May 21 13:58 ..
drwxrwxr-x+ 1 JWinter Domain Users    0 May 21 13:59 .circleci
drwxrwxr-x+ 1 JWinter Domain Users    0 May 21 13:59 .docksal
drwxrwxr-x+ 1 JWinter Domain Users    0 May 21 13:59 .git
-rw-rwxr--+ 1 JWinter Domain Users  108 May 21 13:59 .gitignore
-rw-rwxr--+ 1 JWinter Domain Users  184 May 21 13:59 .travis.yml
drwxrwxr-x+ 1 JWinter Domain Users    0 May 21 13:59 config
drwxrwxr-x+ 1 JWinter Domain Users    0 May 21 13:59 docroot
drwxrwxr-x+ 1 JWinter Domain Users    0 May 21 13:59 drush
-rw-rwxr--+ 1 JWinter Domain Users 2.3K May 21 13:59 README.md
{ drupal8 } master » fin init                                                                                               ~/sites/drupal8
 Step 1  Initializing stack...
Removing containers...
Removing network drupal8_default
Network drupal8_default not found.
Removing volume drupal8_project_root
Volume drupal8_project_root not found.
Volume docksal_ssh_agent is external, skipping
Identity added: id_rsa (id_rsa)
Starting services...
Creating network "drupal8_default" with the default driver
Creating volume "drupal8_project_root" with local driver
Pulling db (docksal/db:1.1-mysql-5.6)...
1.1-mysql-5.6: Pulling from docksal/db
Digest: sha256:621af7593a933b98f417734c1500db51df43c8900624cb33be098142b1856753
Status: Downloaded newer image for docksal/db:1.1-mysql-5.6
Pulling cli (docksal/cli:2.0-php7.1)...
2.0-php7.1: Pulling from docksal/cli
Digest: sha256:1a0457c147d43b17215d9d5643758738712dcf32105995d42e11b3d0161d304e
Status: Downloaded newer image for docksal/cli:2.0-php7.1
Creating drupal8_db_1  ... error
Creating drupal8_cli_1 ...

ERROR: for drupal8_db_1  Cannot start service db: error while mounting volume '/var/lib/docker/volumes/drupal8_project_root/_data': error while mounting volume with options: type='none' device='/c/Users/JWinter/.babun/cygwin/home/JWinter/sites/drupal8' o='bind': no such file or direcCreating drupal8_cli_1 ... error

ERROR: for drupal8_cli_1  Cannot start service cli: error while mounting volume '/var/lib/docker/volumes/drupal8_project_root/_data': error while mounting volume with options: type='none' device='/c/Users/JWinter/.babun/cygwin/home/JWinter/sites/drupal8' o='bind': no such file or directory

ERROR: for db  Cannot start service db: error while mounting volume '/var/lib/docker/volumes/drupal8_project_root/_data': error while mounting volume with options: type='none' device='/c/Users/JWinter/.babun/cygwin/home/JWinter/sites/drupal8' o='bind': no such file or directory

ERROR: for cli  Cannot start service cli: error while mounting volume '/var/lib/docker/volumes/drupal8_project_root/_data': error while mounting volume with options: type='none' device='/c/Users/JWinter/.babun/cygwin/home/JWinter/sites/drupal8' o='bind': no such file or directory
Encountered errors while bringing up the project.
Waiting 10s for MySQL to initialize...
 Step 2  Initializing site...
Error response from daemon: Container 17d0563ee40cd1a138b6db1293835221dbebf000688aa8ee243c3674f328f436 is not running
{ drupal8 } master »                                                                                                      ~/sites/drupal8 1
{ drupal8 } master »           
```

</details>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
 Microsoft Windows [Version 10.0.15063]
CYGWIN_NT-10.0-WOW W2UA7502F8C 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
Mode: Docker for Windows

███  FIN
fin version: 1.52.0

███  ENVIRONMENT
DOCKER_HOST             |
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      18.03.1-ce
 API version:  1.37 (minimum version 1.12)
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:22:38 2018
 OS/Arch:      linux/amd64
 Experimental: false

███  DOCKER INFO
Containers: 7
 Running: 3
 Paused: 0
 Stopped: 4
Images: 8
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155da00104
ID: 7YYH:NNDY:P44U:PHK2:66AY:MIZL:4R5Y:AJAP:6YQK:J2L3:V6OF:3JBU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 44
 Goroutines: 68
 System Time: 2018-05-21T18:12:29.5950051Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.19.0
docker-compose version 1.21.1, build 7641a569
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine.exe version 0.14.0, build 89b8332

NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS

███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/db            1.2-mysql-5.6       0f0acba4c6d1        6 weeks ago         256MB
docksal/cli           2.1-php7.1          4c7331d4cf77        6 weeks ago         950MB
docksal/cli           2.0-php7.1          9ba7c35bb83f        2 months ago        914MB
docksal/vhost-proxy   1.2                 a1c980537985        2 months ago        166MB
docksal/web           2.1-apache2.4       32c1d32eba6d        9 months ago        87.5MB
docksal/db            1.1-mysql-5.6       6feb79af9597        10 months ago       298MB
docksal/dns           1.0                 20c7a535479d        16 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        16 months ago       12.2MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
4dcce0727fd7        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      26 minutes ago      Up 26 minutes                                                                docksal-ssh-agent
a45676f0e1f0        docksal/dns:1.0           "/opt/entrypoint.s..."   26 minutes ago      Up 26 minutes       192.168.64.100:53->53/udp                                docksal-dns
2a7120c3da0e        docksal/vhost-proxy:1.2   "docker-entrypoint..."   26 minutes ago      Up 26 minutes       192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  HDD Usage
Caption  FreeSpace      Size
C:       191264014336   255086030848
D:       999846891520   1000068870144
E:
O:       6029721669632  24739011624960


███  RAM Usage
find: ‘Available Physical Memory’: No such file or directory

███  RAM Usage per container
CONTAINER             CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
docksal-ssh-agent     0.00%               1.305MiB / 1.934GiB   0.07%               1.56kB / 0B         1.14MB / 0B         2
docksal-dns           0.14%               15.17MiB / 1.934GiB   0.77%               277kB / 472kB       2.42MB / 0B         10
docksal-vhost-proxy   0.12%               18.24MiB / 1.934GiB   0.92%               5.89kB / 2.19kB     8.59MB / 4.1kB      12
{ drupal8 } master »   
  ```

</details>

 
 
 

$ `fin config` output

<details>
```
{ drupal8 } master » fin config                                                                                           ~/sites/drupal8 1
---------------------
COMPOSE_PROJECT_NAME_SAFE: drupal8
COMPOSE_FILE:
C:/Users/JWinter/.babun/cygwin/home/JWinter/.docksal/stacks/volumes-bind.yml
C:/Users/JWinter/.babun/cygwin/home/JWinter/.docksal/stacks/stack-default.yml
C:/Users/JWinter/.babun/cygwin/home/JWinter/sites/drupal8/.docksal/docksal.yml
ENV_FILE:
C:/Users/JWinter/.babun/cygwin/home/JWinter/sites/drupal8/.docksal/docksal.env

PROJECT_ROOT: /c/Users/JWinter/.babun/cygwin/home/JWinter/sites/drupal8
DOCROOT: docroot
VIRTUAL_HOST: drupal8.docksal
VIRTUAL_HOST_ALIASES: *.drupal8.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: null
      HOST_UID: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: drupal8.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.0-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /c/Users/JWinter/.babun/cygwin/home/JWinter/sites/drupal8
      io.docksal.virtual-host: drupal8.docksal,*.drupal8.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/JWinter/.babun/cygwin/home/JWinter/sites/drupal8
      o: bind
      type: none

---------------------

```
</details>
