### ISSUE TITLE
fin db drop and create commands not a replacement for mysql exec command

### ISSUE THREAD

**Issue by shelane** [docksal/docksal#548]
**Description**

In an existing docksal command to create a new multisite, I have the myql query commands as followed in the drupal7-advanced project.

```
local database="${1}"
local mysql_exec="mysql -h db --user=root --password=${MYSQL_ROOT_PASSWORD} -e ";
local query="DROP DATABASE IF EXISTS ${database}; CREATE DATABASE ${database}; GRANT ALL ON ${database}.* TO '${MYSQL_USER}'@'%'"

fin exec "${mysql_exec} \"${query}\""
```
Hoping to simplify and use fin commands, I changed to:
```
local database="${1}"
fin db drop
fin db create ${database}
```
This will fail when the database does not already exist.

**Steps to reproduce the issue:**

1. Use the docksal/drupal7-advanced and replace the lines in the db_create function to those listed as the replacement above
2. Run fin init

**Describe the results you received:**

ERROR 1008 (HY000) at line 1: Can't drop database 'anothersite'; database doesn't exist
ERROR:  Dropping 'anothersite' database failed

**Describe the results you expected:**

fin db drop would execute something similar to "DROP DATABASE IF EXISTS"

**Description
To reverse the above if the database does already exist, having `fin db drop` first works fine. If that is omitted, then a new error occurs:

**Steps to reproduce the issue:**

1. Use the docksal/drupal7-advanced and replace the lines in the db_create function to:
```
local database="${1}"
fin db create ${database}
```
2. Run fin init

**Describe the results you received:**

ERROR 1007 (HY000) at line 1: Can't create database 'anothersite'; database exists
ERROR:  Database 'anothersite' creation failed

**Describe the results you expected:**

Possibly an option to drop if exists.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: mysite
COMPOSE_FILE:
/Volumes/UserDrive/shelane/.docksal/stacks/volumes-unison.yml
/Volumes/UserDrive/shelane/.docksal/stacks/stack-default.yml
/Volumes/UserDrive/shelane/Sites/docksal/mysite/.docksal/docksal.yml
/Volumes/UserDrive/shelane/Sites/docksal/mysite/.docksal/docksal-local.yml
ENV_FILE:
/Volumes/UserDrive/shelane/Sites/docksal/mysite/.docksal/docksal.env
/Volumes/UserDrive/shelane/Sites/docksal/mysite/.docksal/docksal-local.env

PROJECT_ROOT: /Volumes/UserDrive/shelane/Sites/docksal/mysite
DOCROOT: docroot
VIRTUAL_HOST: mysite.docksal
VIRTUAL_HOST_ALIASES: *.mysite.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32769

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 128.15.15.15
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '503'
      SECRET_ACAPI_EMAIL: '[*****]'
      SECRET_ACAPI_KEY: '[*****]'
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SOURCE_ALIAS: '@mysite.dev'
      VIRTUAL_HOST: mysite.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.1-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 128.15.15.15
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  unison:
    environment:
      SYNC_DESTINATION: /destination
      SYNC_MAX_INOTIFY_WATCHES: '524288'
      SYNC_PREFER: newer
      SYNC_VERBOSE: '1'
      UNISON_GID: '20'
      UNISON_GROUP: dialout
      UNISON_UID: '503'
      UNISON_USER: docker
    image: docksal/unison
    privileged: true
    volumes:
    - project_root:/destination:rw
    - /Volumes/UserDrive/shelane/Sites/docksal/mysite:/source:rw
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 128.15.15.15
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Volumes/UserDrive/shelane/Sites/docksal/mysite
      io.docksal.virtual-host: mysite.docksal,*.mysite.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root: {}

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Mac OS X 10.13.4
Darwin vpna-user-128-15-244-62.mysite.gov 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
Mode: Docker for Mac

███  FIN
fin version: 1.55.4

███  ENVIRONMENT
DOCKER_HOST		| 
 WARNING:  Non-default DOCKER_HOST
------------------------------------------------------------
DOCKSAL_NFS_PATH	| 

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true

███  DOCKER INFO
Containers: 21
 Running: 19
 Paused: 0
 Stopped: 2
Images: 23
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 9
Total Memory: 2.933GiB
Name: linuxkit-025000000001
ID: K25P:M2HJ:YRFL:3BS3:G37J:OHEE:HEKO:I7FE:GN3K:H32Y:TIYI:MNCW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 120
 Goroutines: 121
 System Time: 2018-05-23T19:07:12.147274587Z
 EventsListeners: 4
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
default   -        virtualbox   Stopped                 Unknown   
docksal   -        virtualbox   Stopped                 Unknown   

███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
<none>                <none>              a5bc0303e451        8 days ago          950MB
docksal/unison        latest              2f56fa49cc04        12 days ago         16.8MB
nodejs/cli            latest              bce417281c2e        5 weeks ago         885MB
docksal/db            1.2-mysql-5.6       0f0acba4c6d1        6 weeks ago         256MB
docksal/cli           2.1-php7.1          4c7331d4cf77        6 weeks ago         950MB
docksal/cli           latest              b1ca4fa0852d        6 weeks ago         876MB
docksal/cli           2.0-php7.1          9ba7c35bb83f        2 months ago        914MB
docksal/cli           2.0-php5.6          0fea463bfbd9        2 months ago        887MB
docksal/vhost-proxy   1.2                 a1c980537985        2 months ago        166MB
lpeabody/blt-cli      latest              ea0294b1a4ba        2 months ago        1.01GB
drupal                latest              59d778ddb4e9        2 months ago        452MB
docksal/varnish       1.1-varnish5        967b76b88b85        3 months ago        107MB
cweagans/bg-sync      latest              ebeae43e7c96        3 months ago        16.8MB
hello-world           latest              f2a91732366c        6 months ago        1.85kB
docksal/cli           1.3-php7            19bdddfeab89        8 months ago        759MB
docksal/web           2.1-apache2.4       32c1d32eba6d        9 months ago        87.5MB
docksal/vhost-proxy   1.1                 898fb21e7f2d        9 months ago        158MB
docksal/db            1.1-mysql-5.6       6feb79af9597        10 months ago       298MB
memcached             1.4-alpine          273374b463b8        10 months ago       7.68MB
docksal/dns           1.0                 20c7a535479d        16 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        16 months ago       12.2MB
docksal/solr          1.0-solr4           fa6b236caf06        16 months ago       546MB
docksal/varnish       1.0-varnish4        35dae6b91ff9        16 months ago       99.5MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                  PORTS                                                    NAMES
bd2479b206bc        docksal/varnish:1.1-varnish5   "/opt/startup.sh"        25 hours ago        Up 25 hours             80/tcp, 6082/tcp                                         drupal8_varnish_1
325e4c590432        docksal/web:2.1-apache2.4      "httpd-foreground"       25 hours ago        Up 25 hours             80/tcp, 443/tcp                                          drupal8_web_1
753f27542873        lpeabody/blt-cli               "/opt/startup.sh sup…"   25 hours ago        Up 25 hours (healthy)   22/tcp, 3000/tcp, 9000/tcp                               drupal8_cli_1
f798e1a390ac        memcached:1.4-alpine           "docker-entrypoint.s…"   25 hours ago        Up 25 hours             11211/tcp                                                drupal8_memcached_1
d9b4184983aa        docksal/db:1.1-mysql-5.6       "/entrypoint.sh mysq…"   25 hours ago        Up 25 hours             0.0.0.0:32768->3306/tcp                                  drupal8_db_1
6b7e53b158d7        docksal/solr:1.0-solr4         "/opt/solr/bin/solr …"   25 hours ago        Up 25 hours             8983/tcp                                                 drupal8_solr_1
2681f339043c        docksal/vhost-proxy:1.2        "docker-entrypoint.s…"   28 hours ago        Up 27 hours             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
c40cd4687426        docksal/db:1.2-mysql-5.6       "/entrypoint.sh mysq…"   4 days ago          Up 19 hours             0.0.0.0:32769->3306/tcp                                  mysite_db_1
05bf56f46099        docksal/web:2.1-apache2.4      "httpd-foreground"       4 days ago          Up 19 hours             80/tcp, 443/tcp                                          mysite_web_1
70a8e7c05888        docksal/cli:2.1-php7.1         "/opt/startup.sh sup…"   4 days ago          Up 19 hours (healthy)   22/tcp, 3000/tcp, 9000/tcp                               mysite_cli_1
a3ddeea7ecbf        docksal/dns:1.0                "/opt/entrypoint.sh …"   4 days ago          Up 27 hours             192.168.64.100:53->53/udp                                docksal-dns
2ae42a9810b3        docksal/ssh-agent:1.0          "/run.sh ssh-agent"      8 days ago          Up 27 hours                                                                      docksal-ssh-agent
29b1acf6ec0f        docksal/unison                 "bg-sync"                11 days ago         Up 19 hours                                                                      mysite_unison_1

███  VIRTUALBOX
EXPECTED VERSION: 5.2.2
5.1.28r117968

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  HDD Usage
Filesystem                                             Size   Used  Avail Capacity  iused               ifree %iused  Mounted on
/dev/disk4s1                                          238Gi   67Gi  166Gi    29%  1460603 9223372036853315204    0%   /
devfs                                                 197Ki  197Ki    0Bi   100%      682                   0  100%   /dev
/dev/disk4s4                                          238Gi  5.0Gi  166Gi     3%        5 9223372036854775802    0%   /private/var/vm
/dev/disk1s2                                          931Gi  910Gi   21Gi    98% 14534610          4280432669    0%   /Volumes/MacBack
/dev/disk3s2                                          931Gi  519Gi  413Gi    56%  1360520          4293606759    0%   /Volumes/UserDrive
/dev/disk2s2                                          931Gi  420Gi  511Gi    46%    10510          4294956769    0%   /Volumes/UserExtras
map -hosts                                              0Bi    0Bi    0Bi   100%        0                   0  100%   /net
map auto_home                                           0Bi    0Bi    0Bi   100%        0                   0  100%   /home
com.apple.TimeMachine.2018-05-23-115331@/dev/disk4s1  238Gi   67Gi  166Gi    29%  1460591 9223372036853315216    0%   /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/Enterprise/2018-05-23-115331/Mac Pro
com.apple.TimeMachine.2018-05-23-105523@/dev/disk4s1  238Gi   67Gi  166Gi    29%  1460571 9223372036853315236    0%   /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/Enterprise/2018-05-23-105523/Mac Pro

███  RAM Usage
Mach Virtual Memory Statistics: (page size of 4096 bytes)
Pages free:                               10671.
Pages active:                           1604759.
Pages inactive:                         1584898.
Pages speculative:                        26760.
Pages throttled:                              0.
Pages wired down:                        531436.
Pages purgeable:                           9159.
"Translation faults":                1530118009.
Pages copy-on-write:                  129976601.
Pages zero filled:                    446271584.
Pages reactivated:                     58076859.
Pages purged:                            865822.
File-backed pages:                       953662.
Anonymous pages:                        2262755.
Pages stored in compressor:             2896454.
Pages occupied by compressor:            432123.
Decompressions:                        32719800.
Compressions:                          45228709.
Pageins:                               43411658.
Pageouts:                                391479.
Swapins:                               10674911.
Swapouts:                              12152628.

███  RAM Usage per container
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
bd2479b206bc        drupal8_varnish_1     0.58%               8.336MiB / 2.933GiB   0.28%               3.59kB / 0B         26.5MB / 475kB      219
325e4c590432        drupal8_web_1         0.13%               9.035MiB / 2.933GiB   0.30%               2.75MB / 3.4MB      7.48MB / 0B         109
753f27542873        drupal8_cli_1         0.02%               76.18MiB / 2.933GiB   2.54%               170MB / 218MB       73.2MB / 688kB      5
f798e1a390ac        drupal8_memcached_1   0.01%               960KiB / 2.933GiB     0.03%               4.25kB / 0B         1.98MB / 0B         7
d9b4184983aa        drupal8_db_1          0.08%               530.1MiB / 2.933GiB   17.65%              215MB / 143MB       38.8MB / 2.69GB     23
6b7e53b158d7        drupal8_solr_1        0.11%               206.8MiB / 2.933GiB   6.89%               4.32kB / 0B         77.3MB / 81.9kB     37
2681f339043c        docksal-vhost-proxy   0.30%               19.29MiB / 2.933GiB   0.64%               6.27MB / 6.35MB     50MB / 41kB         25
c40cd4687426        mysite_db_1             0.08%               857.4MiB / 2.933GiB   28.55%              524MB / 1.42GB      221MB / 8.98GB      22
05bf56f46099        mysite_web_1            0.15%               11.93MiB / 2.933GiB   0.40%               545kB / 2.63MB      3.41MB / 0B         109
70a8e7c05888        mysite_cli_1            0.06%               54.08MiB / 2.933GiB   1.80%               1.42GB / 525MB      572MB / 5.98MB      5
a3ddeea7ecbf        docksal-dns           0.31%               14.22MiB / 2.933GiB   0.47%               17.6kB / 16.6kB     15.9MB / 4.1kB      17
2ae42a9810b3        docksal-ssh-agent     0.00%               1.207MiB / 2.933GiB   0.04%               4.69kB / 0B         7.64MB / 0B         2
29b1acf6ec0f        mysite_unison_1         0.00%               51.03MiB / 2.933GiB   1.70%               2.03kB / 0B         33.6MB / 6.32MB     4
  ```

</details>
