### ISSUE TITLE
Issue with syncing large number (500+) config files

### ISSUE THREAD

**Issue by ultimike** [docksal/docksal#583]
**Description**

I'm having an odd issue with Drupal 8 config files not appearing to sync properly between the host OS and the Docksal container. My site has 567 config files. 

I think it is easiest to explain with a short video: https://www.youtube.com/watch?v=DZJeGnsiHAQ

**Steps to reproduce the issue:**

(see video)

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: devfloridarealtors
COMPOSE_FILE:
/Users/michael/.docksal/stacks/volumes-bind.yml
/Users/michael/.docksal/stacks/stack-default.yml
/Users/michael/Sites/devfloridarealtors/.docksal/docksal.yml
/Users/michael/Sites/devfloridarealtors/.docksal/docksal-local.yml
ENV_FILE:
/Users/michael/Sites/devfloridarealtors/.docksal/docksal.env
/Users/michael/Sites/devfloridarealtors/.docksal/docksal-local.env

PROJECT_ROOT: /Users/michael/Sites/devfloridarealtors
DOCROOT: web
VIRTUAL_HOST: devfloridarealtors.docksal
VIRTUAL_HOST_ALIASES: *.devfloridarealtors.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: web
      HOST_GID: '20'
      HOST_UID: '501'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: devfloridarealtors.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:edge-php7
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  solr:
    environment:
      DOMAIN_NAME: solr.devfloridarealtors.docksal
    hostname: solr
    image: docksal/solr:1.0-solr3
    ports:
    - 8983:8983/tcp
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/web
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/michael/Sites/devfloridarealtors
      io.docksal.virtual-host: devfloridarealtors.docksal,*.devfloridarealtors.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/michael/Sites/devfloridarealtors
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Mac OS X 10.13.1
Darwin Michaels-MacBook-Air-2.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
Mode: VirtualBox VM

███  FIN
fin version: 1.52.0

███  ENVIRONMENT
DOCKER_HOST		| tcp://192.168.64.100:2376
------------------------------------------------------------
DOCKSAL_NFS_PATH	| 

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false

███  DOCKER INFO
Containers: 17
 Running: 7
 Paused: 0
 Stopped: 10
Images: 24
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 398
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.89-boot2docker
Operating System: Boot2Docker 17.09.0-ce (TCL 7.2); HEAD : 06d5c35 - Wed Sep 27 23:22:43 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8MiB
Name: docksal
ID: TAHF:Q66K:WPV2:ABQ4:MSJ6:HXNY:RF5W:YU4R:L64E:7AF4:JT2X:UNWG
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 81
 Goroutines: 73
 System Time: 2018-06-05T15:04:26.53238058Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.19.0
docker-compose version 1.19.0, build 9e633ef
docker-py version: 2.7.0
CPython version: 2.7.10
OpenSSL version: OpenSSL 0.9.8zh 14 Jan 2016

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.09.0-ce   

███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/db            1.2-mysql-5.6       0f0acba4c6d1        2 months ago        256MB
docksal/vhost-proxy   1.2                 a1c980537985        2 months ago        166MB
docksal/cli           edge-php7           1903c6086d28        7 months ago        799MB
docksal/cli           1.3-php7            19bdddfeab89        8 months ago        759MB
docksal/cli           1.3-php5            80248f5ea845        8 months ago        814MB
docksal/web           2.1-apache2.4       32c1d32eba6d        9 months ago        87.5MB
docksal/web           2.0-apache2.4       7f75db9a6aa7        10 months ago       87.5MB
docksal/vhost-proxy   1.1                 898fb21e7f2d        10 months ago       158MB
docksal/db            1.1-mysql-5.6       6feb79af9597        10 months ago       298MB
memcached             latest              6c32c12d9101        13 months ago       83.9MB
mailhog/mailhog       latest              669347153085        13 months ago       19.1MB
docksal/cli           1.2-php5            11f47dc7d024        14 months ago       845MB
docksal/cli           1.2-php7            aef362412c9f        14 months ago       787MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        15 months ago       164MB
docksal/cli           1.1-php7            bdac44fe25f1        15 months ago       777MB
docksal/cli           1.1-php5            1d82105244d1        15 months ago       834MB
docksal/dns           1.0                 20c7a535479d        16 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        16 months ago       12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        16 months ago       188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        16 months ago       255MB
docksal/cli           1.0-php7            5bc490ae4d93        16 months ago       747MB
docksal/cli           1.0-php5            bde35eb43ad7        16 months ago       801MB
busybox               latest              7968321274dc        16 months ago       1.11MB
docksal/solr          1.0-solr3           628ee3683031        17 months ago       471MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
c54b8c602a81        docksal/web:2.1-apache2.4   "httpd-foreground"       4 weeks ago         Up 20 minutes             80/tcp, 443/tcp                                          devfloridarealtors_web_1
01d61e894957        docksal/cli:edge-php7       "/opt/startup.sh s..."   4 weeks ago         Up 20 minutes (healthy)   22/tcp, 9000/tcp                                         devfloridarealtors_cli_1
bc64eeb749be        docksal/db:1.2-mysql-5.6    "/entrypoint.sh my..."   4 weeks ago         Up 20 minutes             0.0.0.0:32768->3306/tcp                                  devfloridarealtors_db_1
e3107f9d08b7        docksal/vhost-proxy:1.2     "docker-entrypoint..."   4 weeks ago         Up 21 minutes             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
eaffa7f5d841        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      4 weeks ago         Up 21 minutes                                                                      docksal-ssh-agent
a71d1959ac06        docksal/dns:1.0             "/opt/entrypoint.s..."   4 weeks ago         Up 21 minutes             192.168.64.100:53->53/udp                                docksal-dns
566b7f82a48a        docksal/solr:1.0-solr3      "java -jar start.jar"    2 months ago        Up 20 minutes             0.0.0.0:8983->8983/tcp                                   devfloridarealtors_solr_1

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.1.28r117968

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.33.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.88.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       10.13.37.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

Name:            vboxnet3
GUID:            786f6276-656e-4374-8000-0a0027000003
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:03
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet3

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/michael/Sites/devfloridarealtors on /mnt/sda1/var/lib/docker/volumes/devfloridarealtors_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                17.9G     13.8G      3.2G  81% /mnt/sda1

███  RAM Usage
             total       used       free     shared    buffers     cached
Mem:       1019652     929400      90252     197724      12168     298520
-/+ buffers/cache:     618712     400940
Swap:      1172904     384404     788500

███  RAM Usage per container
CONTAINER                   CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
devfloridarealtors_web_1    0.09%               5.215MiB / 995.8MiB   0.52%               2.36MB / 2.52MB     9.69MB / 0B         109
devfloridarealtors_cli_1    0.04%               99.89MiB / 995.8MiB   10.03%              83.5MB / 14.6MB     119MB / 25.3MB      6
devfloridarealtors_db_1     0.07%               241.4MiB / 995.8MiB   24.24%              12.4MB / 83.4MB     68.3MB / 115MB      23
docksal-vhost-proxy         0.15%               19.08MiB / 995.8MiB   1.92%               2.62MB / 2.6MB      44.9MB / 16.4kB     11
docksal-ssh-agent           0.00%               604KiB / 995.8MiB     0.06%               1.75kB / 0B         5.82MB / 0B         2
docksal-dns                 0.36%               12.84MiB / 995.8MiB   1.29%               1.66kB / 0B         17.9MB / 0B         9
devfloridarealtors_solr_1   0.14%               58.03MiB / 995.8MiB   5.83%               2.5kB / 1.08kB      48.3MB / 0B         23

  ```

</details>
