### ISSUE TITLE
Drupal Site not loading

### ISSUE THREAD

**Issue by karanramani1234** [docksal/docksal#617]
**Description**
While trying to install site using fin init <site folder name> after successful site installation, once the url loaded in the web browser the page keeps showing the loading gif, refreshes every 5 seconds and is not redirected to the site page. 

Problem/feature description...

- No drupal site is being loaded.
- Page stays on the "loading demons screen".
<img width="1680" alt="loading screen" src="https://user-images.githubusercontent.com/40276599/41432370-e33930ac-6fe3-11e8-8245-b57eee7affd2.png">

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: fusion
COMPOSE_FILE:
/Users/kr/.docksal/stacks/volumes-bind.yml
/Users/kr/.docksal/stacks/stack-default.yml
/Users/kr/projects/janssen/platforms/fusion/.docksal/docksal.yml
ENV_FILE:
/Users/kr/projects/janssen/platforms/fusion/.docksal/docksal.env

PROJECT_ROOT: /Users/kr/projects/janssen/platforms/fusion
DOCROOT: docroot
VIRTUAL_HOST: jjfusion.docksal,*.jjfusion.docksal
VIRTUAL_HOST_ALIASES: *.jjfusion.docksal,*.jjfusion.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32769

Docker Compose configuration
---------------------
services:
  browser:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    hostname: browser
    image: selenium/standalone-chrome-debug
    ports:
    - 4444/tcp
    - 5900:5900/tcp
    volumes:
    - project_root:/var/www:rw
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '501'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: jjfusion.docksal,*.jjfusion.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.0-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_sites:/sites:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached:1.4-alpine
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/kr/projects/janssen/platforms/fusion
      io.docksal.virtual-host: jjfusion.docksal,*.jjfusion.docksal,*.jjfusion.docksal,*.jjfusion.docksal,jjfusion.docksal,*.jjfusion.docksal.*
    volumes:
    - project_sites:/sites:ro
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/kr/projects/janssen/platforms/fusion
      o: bind
      type: none
  project_sites:
    driver: local
    driver_opts:
      device: /Users/kr/projects/janssen/platforms/fusion/../../sites
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  ███  OS
Darwin Mac OS X 10.13.5
Darwin Karans-MacBook-Pro.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
Mode: VirtualBox VM

███  FIN
fin version: 1.60.2

███  ENVIRONMENT
DOCKER_HOST		| tcp://192.168.64.100:2376
------------------------------------------------------------
DOCKSAL_NFS_PATH	| 

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:03 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER INFO
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 18.03.1-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 118
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-boot2docker
Operating System: Boot2Docker 18.03.1-ce (TCL 8.2.1); HEAD : cb77972 - Thu Apr 26 16:40:36 UTC 2018
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955GiB
Name: docksal
ID: 6URS:UETO:4KVI:5UKJ:S3W3:G5AY:YN73:CQTR:DCCW:MPLO:36S4:BW7V
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.03.1-ce   

███  DOCKER: IMAGES
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
selenium/standalone-chrome-debug   latest              8e501b705367        36 hours ago        892MB
docksal/vhost-proxy                1.2                 a1c980537985        3 months ago        166MB
memcached                          1.4-alpine          273374b463b8        11 months ago       7.68MB
docksal/dns                        1.0                 20c7a535479d        16 months ago       61.6MB
docksal/ssh-agent                  1.0                 148220cc033d        16 months ago       12.2MB
docksal/web                        1.0-apache2.2       a9c03f8a5f0f        17 months ago       188MB
docksal/db                         1.0-mysql-5.5       9fb8c0aed5fc        17 months ago       255MB
docksal/cli                        1.0-php5            bde35eb43ad7        17 months ago       801MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
ca12d31915e9        docksal/web:1.0-apache2.2          "/opt/startup.sh apa…"   41 minutes ago      Up 41 minutes       80/tcp, 443/tcp                                          fusion_web_1
222cdc3d72ff        docksal/cli:1.0-php5               "/opt/startup.sh gos…"   41 minutes ago      Up 41 minutes       22/tcp, 9000/tcp                                         fusion_cli_1
8948f0c07569        selenium/standalone-chrome-debug   "/opt/bin/entry_poin…"   41 minutes ago      Up 41 minutes       0.0.0.0:5900->5900/tcp, 0.0.0.0:32768->4444/tcp          fusion_browser_1
84cd5cf3d7bf        docksal/db:1.0-mysql-5.5           "/entrypoint.sh mysq…"   41 minutes ago      Up 41 minutes       0.0.0.0:32769->3306/tcp                                  fusion_db_1
7643e541550f        memcached:1.4-alpine               "docker-entrypoint.s…"   41 minutes ago      Up 41 minutes       11211/tcp                                                fusion_memcached_1
3dd19f21df35        docksal/ssh-agent:1.0              "/run.sh ssh-agent"      45 minutes ago      Up 45 minutes                                                                docksal-ssh-agent
791356509bed        docksal/dns:1.0                    "/opt/entrypoint.sh …"   45 minutes ago      Up 45 minutes       192.168.64.100:53->53/udp                                docksal-dns
22b0357a8424        docksal/vhost-proxy:1.2            "docker-entrypoint.s…"   45 minutes ago      Up 45 minutes       192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  VIRTUALBOX
EXPECTED VERSION: 5.2.2
5.2.2r119230

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/kr/projects/janssen/platforms/fusion on /mnt/sda1/var/lib/docker/volumes/fusion_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/kr/projects/janssen/sites on /mnt/sda1/var/lib/docker/volumes/fusion_project_sites/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G      2.8G     40.9G   6% /mnt/sda1

███  RAM Usage
             total       used       free     shared    buffers     cached
Mem:       2050184    1505400     544784     229984     274644     599768
-/+ buffers/cache:     630988    1419196
Swap:      1433656      26548    1407108

███  RAM Usage per container
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
ca12d31915e9        fusion_web_1          0.01%               6.898MiB / 1.955GiB   0.34%               1.94kB / 0B         0B / 0B             57
222cdc3d72ff        fusion_cli_1          0.03%               38.71MiB / 1.955GiB   1.93%               997MB / 676MB       65.7MB / 90.1MB     6
8948f0c07569        fusion_browser_1      0.23%               69.98MiB / 1.955GiB   3.50%               2.37kB / 0B         93.7MB / 1.99MB     23
84cd5cf3d7bf        fusion_db_1           0.06%               224.7MiB / 1.955GiB   11.22%              673MB / 905MB       30.5MB / 3GB        17
7643e541550f        fusion_memcached_1    0.01%               884KiB / 1.955GiB     0.04%               2.76kB / 224B       0B / 0B             7
3dd19f21df35        docksal-ssh-agent     0.00%               1.012MiB / 1.955GiB   0.05%               2.66kB / 0B         0B / 0B             2
791356509bed        docksal-dns           0.21%               17.13MiB / 1.955GiB   0.86%               159kB / 218kB       1.67MB / 0B         9
22b0357a8424        docksal-vhost-proxy   0.21%               22.28MiB / 1.955GiB   1.11%               103kB / 154kB       20MB / 8.19kB       12
  ```

</details>

**Comment by lmakarov** [comment]
Looks to be a dupe of #612.

Your project is using very outdated image versions.
At the very minimum, switch to the recent version of the web service image:

```
docksal/web:1.0-apache2.2 => docksal/web:2.1-apache2.4
```

I'd recommend updating the whole stack though or switching to the default one. See https://github.com/docksal/docksal/issues/612#issuecomment-397159723

**Comment by karanramani1234** [comment]
I tried doing so, have now changed the version of the web yet no effect to the site loading still seeing the same issue unfortunately

**Comment by lmakarov** [comment]
@karanramani1234 did you do `fin up` after you switched the image versions?
Please looks through the debugging steps in #612. I'm pretty sure you are having the same issue.

**Comment by karanramani1234** [comment]
Thanks @lmakarov.

yes, after changing the image versions I actually re-installed the site, and ran the following commands afterwards as well,
- fin up

once I ran fin up it asked me to update the image versions so as per that I ran " fin update" and then "fin up" again yet I see the same screen still the same issue.

I have also updated php and sql versions mentioned in the #612 

would mac's local apache setup interfere with this docksal setup?

**Comment by lmakarov** [comment]
> would mac's local apache setup interfere with this docksal setup?

You are getting the loading screen from Docksal, so there is no interference with other services on your Mac.

Please post the output for the following commands:

```
fin config show
```

(run the above one in the project's directory, the rest can be run from anywhere on your host)

```
fin pl -a
```

```
fin docker exec docksal-vhost-proxy nginx -t
```

```
fin docker exec docksal-vhost-proxy cat /etc/nginx/conf.d/vhosts.conf
```

**Comment by ssudhak** [comment]
I am also facing the same issue, as Karan mentioned it was working fine before the docksal got updated.
Now it works for single site set up but not for multi-site setup.

My normal site has following configurations:
WEB_IMAGE='docksal/web:1.0-apache2.2'
DB_IMAGE='docksal/db:1.0-mysql-5.5'
CLI_IMAGE='docksal/cli:1.0-php5'

How I have done the steps mentioned in #612 but still facing the issue.  please find the output of the commands requested.

**$ fin config show**

---------------------
COMPOSE_PROJECT_NAME_SAFE: fusion1295
COMPOSE_FILE:
/Users/a251267/.docksal/stacks/volumes-bind.yml
/Users/a251267/.docksal/stacks/stack-default.yml
/Users/a251267/Sites/fusion1295/.docksal/docksal.yml
ENV_FILE:
/Users/a251267/Sites/fusion1295/.docksal/docksal.env

PROJECT_ROOT: /Users/a251267/Sites/fusion1295
DOCROOT: docroot
VIRTUAL_HOST: fusion1295.docksal,*.fusion1295.docksal
VIRTUAL_HOST_ALIASES: *.fusion1295.docksal,*.fusion1295.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  browser:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    hostname: browser
    image: selenium/standalone-chrome-debug
    ports:
    - 4461/tcp
    - 5961:5961/tcp
    volumes:
    - project_root:/var/www:rw
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '502'
      PHP_IDE_CONFIG: serverName=demo.fusion1295.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: fusion1295.docksal,*.fusion1295.docksal
      XDEBUG_CONFIG: idekey=PHPSTORM remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.2-php5.6
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_sites:/sites:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: demo
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.5
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  memcached:
    environment:
      MEMCACHED_MEMORY_LIMIT: '128'
    hostname: memcached
    image: memcached:1.4-alpine
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/a251267/Sites/fusion1295
      io.docksal.virtual-host: fusion1295.docksal,*.fusion1295.docksal,*.fusion1295.docksal,*.fusion1295.docksal,fusion1295.docksal,*.fusion1295.docksal.*
    volumes:
    - project_sites:/sites:ro
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/a251267/Sites/fusion1295
      o: bind
      type: none
  project_sites:
    driver: local
    driver_opts:
      device: /Users/a251267/Sites/fusion1295/../../sites
      o: bind
      type: none

---------------------

**fin pl -a**
project             STATUS                     virtual host                                                                                                                  project root
fusion1295          Up 6 minutes               fusion1295.docksal,*.fusion1295.docksal,*.fusion1295.docksal,*.fusion1295.docksal,fusion1295.docksal,*.fusion1295.docksal.*   /Users/a251267/Sites/fusion1295
jcr                 Up 19 minutes              jcr.docksal,*.jcr.docksal,jcr.docksal.*                                                                                       /Users/a251267/Sites/jcr
drupal85x           Exited (0) 3 days ago      drupal85x.docksal,*.drupal85x.docksal                                                                                         /Users/a251267/Sites/drupal85x
sudheeshps          Exited (0) 3 days ago      sudheeshps.docksal,*.sudheeshps.docksal                                                                                       /Users/a251267/Sites/sudheeshps
dicom               Exited (255) 4 weeks ago   dicom.docksal,*.dicom.docksal                                                                                                 /Users/a251267/Sites/dicom
fusion1291          Exited (255) 4 weeks ago   jjfusion.docksal,*.jjfusion.docksal,*.jjfusion.docksal,*.jjfusion.docksal                                                     /Users/a251267/Sites/fusion1291
jcrdev              Exited (0) 3 days ago      jcrdev.docksal,*.jcrdev.docksal                                                                                               /Users/a251267/Sites/jcrdev

--------------------------

**fin docker exec docksal-vhost-proxy nginx -t**
nginx: [warn] conflicting server name "*.fusion1295.docksal" on 0.0.0.0:80, ignored
nginx: [warn] conflicting server name "*.fusion1295.docksal" on 0.0.0.0:80, ignored
nginx: [warn] conflicting server name "fusion1295.docksal" on 0.0.0.0:80, ignored
nginx: [emerg] invalid server name or wildcard "*.fusion1295.docksal.*" on 0.0.0.0:80
nginx: configuration file /etc/nginx/nginx.conf test failed

---------------------------------------

**fin docker exec docksal-vhost-proxy cat /etc/nginx/conf.d/vhosts.conf**
	# -------------------------------------------------- #
	# Reachable via "fusion1295_default" network
	upstream fusion1295-web {
		# fusion1295_web_1
		server 172.21.0.7:80;
	}
	## HTTP
	server {
		listen 80;
		server_name fusion1295.docksal;
		server_name *.fusion1295.docksal;
		server_name *.fusion1295.docksal;
		server_name *.fusion1295.docksal;
		server_name fusion1295.docksal;
		server_name *.fusion1295.docksal.*;
		location / {
			proxy_pass http://fusion1295-web;
		}
	}
	## HTTPS
	server {
		listen 443 ssl http2;
		server_name fusion1295.docksal;
		server_name *.fusion1295.docksal;
		server_name *.fusion1295.docksal;
		server_name *.fusion1295.docksal;
		server_name fusion1295.docksal;
		server_name *.fusion1295.docksal.*;
		ssl_certificate           /etc/nginx/server.crt;
		ssl_certificate_key       /etc/nginx/server.key;
		ssl_session_cache  builtin:1000  shared:SSL:10m;
		ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
		ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
		ssl_prefer_server_ciphers on;
		location / {
			proxy_pass http://fusion1295-web;
		}
	}
	# -------------------------------------------------- #
	# -------------------------------------------------- #
	# Reachable via "jcr_default" network
	upstream jcr-web {
		# jcr_web_1
		server 172.23.0.6:80;
	}
	## HTTP
	server {
		listen 80;
		server_name jcr.docksal;
		server_name *.jcr.docksal;
		server_name jcr.docksal.*;
		location / {
			proxy_pass http://jcr-web;
		}
	}
	## HTTPS
	server {
		listen 443 ssl http2;
		server_name jcr.docksal;
		server_name *.jcr.docksal;
		server_name jcr.docksal.*;
		ssl_certificate           /etc/nginx/server.crt;
		ssl_certificate_key       /etc/nginx/server.key;
		ssl_session_cache  builtin:1000  shared:SSL:10m;
		ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
		ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
		ssl_prefer_server_ciphers on;
		location / {
			proxy_pass http://jcr-web;
		}
	}
	# -------------------------------------------------- #

**Comment by achekulaev** [comment]
@ssudhak I will edit your comment for readability but going forward please familiarize yourself with using markdown and use ` ``` ` for blocks of pre-formatted text like code or utilities output.

**Comment by ssudhak** [comment]
@achekulaev wow that worked, let me try installing other subsites and see if its working,.

thanks a lot for the help.

**Comment by ssudhak** [comment]
@lmakarov & @achekulaev 

Projects with following configurations are working.
WEB_IMAGE='docksal/web:1.0-apache2.2'
DB_IMAGE='docksal/db:1.0-mysql-5.5'
CLI_IMAGE='docksal/cli:1.0-php5'

I am now setting the same site in php 7 with the following configuration.
WEB_IMAGE='docksal/web:1.0-apache2.2'
DB_IMAGE='docksal/db:1.0-mysql-5.5'
CLI_IMAGE='docksal/cli:1.0-php5'

But getting 404 error for all the pages.
<img width="759" alt="screen shot 2018-06-19 at 3 07 57 pm" src="https://user-images.githubusercontent.com/7603029/41619006-b6b92b34-73d2-11e8-8dff-4e873ae4cb05.png">

**fin docker exec docksal-vhost-proxy nginx -t**
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

**fin pl -a**
```
project             STATUS                     virtual host                                                                project root
fusion141           Up 2 hours                 jjfusion141.docksal,*.jjfusion141.docksal,jjfusion141.docksal.*             /Users/a251267/Sites/fusion141
fusion1295          Up 22 hours                fusion1295.docksal,*.fusion1295.docksal,fusion1295.docksal.*                /Users/a251267/Sites/fusion1295
jcr                 Up 26 hours                jcr.docksal,*.jcr.docksal,jcr.docksal.*                                     /Users/a251267/Sites/jcr
drupal85x           Exited (0) 4 days ago      drupal85x.docksal,*.drupal85x.docksal                                       /Users/a251267/Sites/drupal85x
sudheeshps          Exited (0) 4 days ago      sudheeshps.docksal,*.sudheeshps.docksal                                     /Users/a251267/Sites/sudheeshps
dicom               Exited (255) 4 weeks ago   dicom.docksal,*.dicom.docksal                                               /Users/a251267/Sites/dicom
fusion1291          Exited (255) 4 weeks ago   jjfusion.docksal,*.jjfusion.docksal,*.jjfusion.docksal,*.jjfusion.docksal   /Users/a251267/Sites/fusion1291
jcrdev              Exited (0) 4 days ago      jcrdev.docksal,*.jcrdev.docksal                                             /Users/a251267/Sites/jcrdev
```

Please help me to identify the issue

**Comment by achekulaev** [comment]
@ssudhak we would need something more than an image with cartoon death.
At least screenshot that will include the hostname.
But as you might have guesses we will need `fin config` output.
Please attach it every time you are reporting an issue with the project.
Thanks.

**Comment by achekulaev** [comment]
@ssudhak you have a deeply customized `web` container and overall config is very custom. I recommend you remove custom configuration for `web` container and run `fin project start`. That should resolve the issue.

**Comment by ssudhak** [comment]
@achekulaev  please find my docksal.yml. Not sure if I have too much custom configurations for web. It would be great if you can let me know which all needs to be removed. Also why is it not working for only php 7 sites. Request you to help me identify the issue.

```
version: "2.1"

services:
  # Web overrides
  web:
    volumes:
      # Sites volume
      - project_sites:/sites:ro

  # DB overrides
  db:

  # CLI overrides
  cli:
    volumes:
      # Sites volume
      - project_sites:/sites:rw

  # Selenium2
  browser:
    hostname: browser
    image: selenium/standalone-chrome-debug
    volumes:
      - project_root:/var/www:rw
    ports:
      - "4544"
      - "5990:5990"
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # Memcached
  memcached:
    hostname: memcached
    image: memcached:1.4-alpine
    environment:
      # Memcached memory limit in megabytes
      - MEMCACHED_MEMORY_LIMIT=${MEMCACHED_MEMORY_LIMIT:-128}

volumes:
  project_sites:
    driver: local
    driver_opts:
      type: none
      device: ${PROJECT_ROOT}/../../sites
      o: bind

```

**Comment by achekulaev** [comment]
What URL you were trying to load which resulted in 404?

**Comment by ssudhak** [comment]
@achekulaev all the urls even the home page is coming as "project not found"
Please check the screenshot below for more details.

<img width="1104" alt="screen shot 2018-06-20 at 2 27 31 pm" src="https://user-images.githubusercontent.com/7603029/41677409-34dd1fca-7496-11e8-9e74-c8976f16d350.png">

**Comment by ssudhak** [comment]
@achekulaev that works. but its going to the installation page.
Ideally for subsites. we will have a "sitename" folder in the site folder, then an entry like $sites["demo.fusion141.docksal"] = "demo"; in the sites.php

Inside demo folder there will be a docksal.env which has contents as shown below
```
# Set site name to be enabled during site install
SITE_FEATURE='fusion_demo_janssenos_com'

# Set to the appropriate site domain
SITE_DOMAIN='demo.fusion141.docksal'

# Set Drupal site name
SITE_NAME='Fusion Demo'

# Load content from JCR, enable Demo or do nothing
# Options: jcr, demo, none
SITE_CONTENT='jcr'
```

and docksal-local.yml with contents 
```
version: "2.1"

services:

  # CLI overrides
  cli:
    volumes:
      # Sites volume
      - project_sites:/sites:rw
    environment:
      - XDEBUG_ENABLED=1
```

this works fine for me for the container which has following configurations
WEB_IMAGE='docksal/web:1.0-apache2.2'
DB_IMAGE='docksal/db:1.0-mysql-5.5'
CLI_IMAGE='docksal/cli:1.0-php5'

only creating issue for the site with php 7
