### ISSUE TITLE
Docksal OpenSSL?

### ISSUE THREAD

**Issue by loopy3025** [docksal/docksal#625]
Our network here at my job has changed rather drastically of late and I've finally been able to get a Drupal 7 and Drupal 8 site running on my local dev using both http and https. I am ecstatic! There's just one more roadblock and that is downloading and enabling modules. 

I run
```
$ frush en examples -y
```
and I get
```
examples was not found.                                                                                                            [warning]
simplexml_load_file(): I/O warning : failed to load external entity "" Project.php:74                                              [warning]
Failed to get available update data from https://updates.drupal.org/release-history/examples/8.x  
```
I googled a bunch and found this telling me to enable the open.ssl extension in php: https://www.drupal.org/project/infrastructure/issues/2661298

And this discussing enabling php modules:
https://github.com/docksal/service-cli/issues/9

When I tried adding this to the site's .docksal\etc\php\php.ini file, drupal got very, very angry with me when I ran cache-rebuild.
```
extension_dir=C:/PHP7/ext
extension=php_openssl.dll
```
I'm wondering if all that is even necessary, though.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: examples
COMPOSE_FILE:
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/.docksal/stacks/volumes-bind.yml
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/.docksal/stacks/stack-default.yml
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/examples/.docksal/docksal.yml
ENV_FILE:
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/examples/.docksal/docksal.env
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/examples/.docksal/docksal-local.env

PROJECT_ROOT: /c/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/examples
DOCROOT: docroot
VIRTUAL_HOST: examples.docksal
VIRTUAL_HOST_ALIASES: *.examples.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32771

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      HOST_GID: null
      HOST_UID: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: examples.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.1-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /c/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/examples
      io.docksal.virtual-host: examples.docksal,*.examples.docksal,examples.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/examples
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Cygwin Windows 10.0
CYGWIN_NT-10.0-WOW W2UA7502F80 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
Mode: Docker for Windows

███  FIN
fin version: 1.60.2

███  ENVIRONMENT
DOCKER_HOST             |
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER INFO
Containers: 12
 Running: 12
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.837GiB
Name: linuxkit-00155de68f3e
ID: 6LBF:Q7ZL:4QZF:3P7W:LYEL:QTSK:KQRP:2R3F:BKKM:EKIJ:4PT7:ANHD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 66
 Goroutines: 76
 System Time: 2018-06-20T13:11:08.000942Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 7641a569
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine.exe version 0.14.0, build 89b8332

NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS

███  DOCKER: IMAGES
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
docksal/cli                2.2-php7.1          f8397b8a269f        2 weeks ago         867MB
docksal/db                 1.2-mysql-5.6       0f0acba4c6d1        2 months ago        256MB
docksal/cli                2.1-php7.1          4c7331d4cf77        2 months ago        950MB
docksal/cli                2.0-php5.6          0fea463bfbd9        3 months ago        887MB
docksal/vhost-proxy        1.2                 a1c980537985        3 months ago        166MB
docker4w/nsenter-dockerd   latest              cae870735e91        7 months ago        187kB
docksal/cli                1.3-php5            80248f5ea845        9 months ago        814MB
docksal/web                2.1-apache2.4       32c1d32eba6d        9 months ago        87.5MB
docksal/db                 1.1-mysql-5.6       6feb79af9597        11 months ago       298MB
docksal/dns                1.0                 20c7a535479d        17 months ago       61.6MB
docksal/ssh-agent          1.0                 148220cc033d        17 months ago       12.2MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                       NAMES
3f9ec9be6394        docksal/web:2.1-apache2.4   "httpd-foreground"       38 minutes ago      Up 38 minutes             80/tcp, 443/tcp                                             examples_web_1
8665fd98d500        docksal/cli:2.1-php7.1      "/opt/startup.sh sup…"   38 minutes ago      Up 38 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                                  examples_cli_1
5f75991cf370        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   19 hours ago        Up 38 minutes             0.0.0.0:32771->3306/tcp                                     examples_db_1
a87734106f95        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      21 hours ago        Up 18 hours                                                                           docksal-ssh-agent
3dc4d718047b        docksal/dns:1.0             "/opt/entrypoint.sh …"   21 hours ago        Up 18 hours               192.168.64.100:53->53/udp                                   docksal-dns
545f134c4716        docksal/vhost-proxy:1.2     "docker-entrypoint.s…"   21 hours ago        Up 18 hours               192.168.64.100:8080->80/tcp, 192.168.64.100:8443->443/tcp   docksal-vhost-proxy

███  HDD Usage
Caption  FreeSpace     Size
C:       141581553664  255086030848
D:       999846887424  1000068870144
E:


███  RAM Usage
find: ‘Available Physical Memory’: No such file or directory

███  RAM Usage per container
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
3f9ec9be6394        examples_web_1        0.03%               5.52MiB / 3.837GiB    0.14%               1.22kB / 0B         0B / 0B             82
8665fd98d500        examples_cli_1        0.01%               30.41MiB / 3.837GiB   0.77%               541kB / 388kB       16MB / 28.7kB       5
5f75991cf370        examples_db_1         0.03%               474.1MiB / 3.837GiB   12.07%              386kB / 540kB       365kB / 5.37MB      22
a87734106f95        docksal-ssh-agent     0.00%               1.367MiB / 3.837GiB   0.03%               4.79kB / 0B         4.91MB / 0B         2
3dc4d718047b        docksal-dns           0.09%               16.52MiB / 3.837GiB   0.42%               576kB / 1.05MB      15.4MB / 0B         10
545f134c4716        docksal-vhost-proxy   0.09%               19.91MiB / 3.837GiB   0.51%               313kB / 315kB       38.3MB / 28.7kB     14

  ```

</details>
