### ISSUE TITLE
Updated fin and project won't load.

### ISSUE THREAD

**Issue by claytron5000** [docksal/docksal#626]
**Description**

Update appears to break.

**Steps to reproduce the issue:**

1. `cd` into project containing `.docksal` directory
1. run `fin status`
1. receive up:
```
       Name                     Command                State                 Ports
---------------------------------------------------------------------------------------------
burgundy-farm_cli_1   /opt/startup.sh supervisord   Up (healthy)   22/tcp, 3000/tcp, 9000/tcp
burgundy-farm_db_1    /entrypoint.sh mysqld         Up             0.0.0.0:32770->3306/tcp
burgundy-farm_web_1   httpd-foreground              Up             443/tcp, 80/tcp
```
1. Navigate to url for site (now with dashes! `http://burgundy-farm.docksal/`)
1. Also restarted the vm with `fin vm restart`

**Describe the results you received:**

The Waiting for the daemons splash-screen on infinite loop.

**Describe the results you expected:**

Site to load

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: burgundy-farm
COMPOSE_FILE:
/Users/clayton/.docksal/stacks/volumes-bind.yml
/Users/clayton/.docksal/stacks/stack-default.yml
/Users/clayton/Sites/burgundy-farm/.docksal/docksal.yml
ENV_FILE:
/Users/clayton/Sites/burgundy-farm/.docksal/docksal.env

PROJECT_ROOT: /Users/clayton/Sites/burgundy-farm
DOCROOT: .
VIRTUAL_HOST: burgundy-farm.docksal
VIRTUAL_HOST_ALIASES: *.burgundy-farm.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32770

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: 27271793-18c5-4867-9e5c-8131a8b3242f
      BLACKFIRE_CLIENT_TOKEN: ec2f961d5fa68ec9c42eca60c1b8fe8eb64c29d4f1c08e2c5c5d52da0769afd7
      DOCROOT: .
      HOST_GID: '20'
      HOST_UID: '501'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: burgundy-farm.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.2-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/.
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/clayton/Sites/burgundy-farm
      io.docksal.virtual-host: burgundy-farm.docksal,*.burgundy-farm.docksal,burgundy-farm.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/clayton/Sites/burgundy-farm
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.13.5
Darwin Claytons-MacBook-Pro.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
Mode: VirtualBox VM

███  FIN
fin version: 1.60.2

███  ENVIRONMENT
DOCKER_HOST		| tcp://192.168.64.100:2376
------------------------------------------------------------
DOCKSAL_NFS_PATH	|

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:03 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER INFO
Containers: 34
 Running: 9
 Paused: 0
 Stopped: 25
Images: 12
Server Version: 18.03.1-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 255
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-boot2docker
Operating System: Boot2Docker 18.03.1-ce (TCL 8.2.1); HEAD : cb77972 - Thu Apr 26 16:40:36 UTC 2018
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955GiB
Name: docksal
ID: UVFA:IP44:4PCI:AXKW:IVQ5:MLDX:BBLM:X6HJ:QU5X:DRAR:7H2V:ZTFF
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.03.1-ce
myvm1     -        virtualbox   Error                                         Unknown       machine does not exist
myvm2     -        virtualbox   Error                                         Unknown       machine does not exist

███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/cli           2.2-php7.1          f8397b8a269f        2 weeks ago         867MB
docksal/db            1.2-mysql-5.6       0f0acba4c6d1        2 months ago        256MB
docksal/cli           2.1-php7.1          4c7331d4cf77        2 months ago        950MB
docksal/vhost-proxy   1.2                 a1c980537985        3 months ago        166MB
docksal/cli           1.3-php7            19bdddfeab89        9 months ago        759MB
docksal/web           2.1-apache2.4       32c1d32eba6d        10 months ago       87.5MB
docksal/vhost-proxy   1.1                 898fb21e7f2d        10 months ago       158MB
docksal/db            1.1-mysql-5.7       8d323c436c28        11 months ago       412MB
docksal/db            1.1-mysql-5.6       6feb79af9597        11 months ago       298MB
mailhog/mailhog       latest              669347153085        14 months ago       19.1MB
docksal/dns           1.0                 20c7a535479d        17 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        17 months ago       12.2MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
d750a365a991        docksal/web:2.1-apache2.4   "httpd-foreground"       12 minutes ago      Up 12 minutes             80/tcp, 443/tcp                                          chesapeake-bay_web_1
a55815bee43b        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   12 minutes ago      Up 12 minutes             0.0.0.0:32769->3306/tcp                                  chesapeake-bay_db_1
f9b8a19e17fc        docksal/cli:2.2-php7.1      "/opt/startup.sh sup…"   12 minutes ago      Up 12 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               chesapeake-bay_cli_1
ae13b8deb599        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      13 minutes ago      Up 13 minutes                                                                      docksal-ssh-agent
2c11f669b11d        docksal/dns:1.0             "/opt/entrypoint.sh …"   13 minutes ago      Up 13 minutes             192.168.64.100:53->53/udp                                docksal-dns
c71d04e4806d        docksal/vhost-proxy:1.2     "docker-entrypoint.s…"   13 minutes ago      Up 13 minutes             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
a2a3794d14e3        docksal/web:2.1-apache2.4   "httpd-foreground"       20 minutes ago      Up 6 minutes              80/tcp, 443/tcp                                          burgundy-farm_web_1
005a70eec57a        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   20 minutes ago      Up 6 minutes              0.0.0.0:32770->3306/tcp                                  burgundy-farm_db_1
34f152ed575a        docksal/cli:2.2-php7.1      "/opt/startup.sh sup…"   20 minutes ago      Up 6 minutes (healthy)    22/tcp, 3000/tcp, 9000/tcp                               burgundy-farm_cli_1

███  VIRTUALBOX
EXPECTED VERSION: 5.2.2
5.2.2r119230

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       192.168.10.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/clayton/Sites/chesapeake-bay on /mnt/sda1/var/lib/docker/volumes/chesapeakebay_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/clayton/Sites/burgundy-farm on /mnt/sda1/var/lib/docker/volumes/burgundy-farm_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.3G     12.3G     31.6G  28% /mnt/sda1

███  RAM Usage
             total       used       free     shared    buffers     cached
Mem:       2050184    1823996     226188     266232      82348     462180
-/+ buffers/cache:    1279468     770716
Swap:      1410204       6324    1403880

███  RAM Usage per container
CONTAINER ID        NAME                   CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
d750a365a991        chesapeake-bay_web_1   0.10%               5.156MiB / 1.955GiB   0.26%               1.74kB / 0B         1.07MB / 0B         82
a55815bee43b        chesapeake-bay_db_1    0.10%               473.9MiB / 1.955GiB   23.67%              1.91kB / 0B         33.9MB / 45.1kB     21
f9b8a19e17fc        chesapeake-bay_cli_1   0.02%               31.27MiB / 1.955GiB   1.56%               2kB / 0B            22.5MB / 41kB       5
ae13b8deb599        docksal-ssh-agent      0.00%               992KiB / 1.955GiB     0.05%               1.3kB / 0B          2.25MB / 0B         2
2c11f669b11d        docksal-dns            0.22%               17.9MiB / 1.955GiB    0.89%               3.65kB / 2.76kB     11.9MB / 0B         9
c71d04e4806d        docksal-vhost-proxy    0.29%               22.26MiB / 1.955GiB   1.11%               106kB / 167kB       16.3MB / 16.4kB     10
a2a3794d14e3        burgundy-farm_web_1    0.11%               5.227MiB / 1.955GiB   0.26%               998B / 0B           1.59MB / 0B         82
005a70eec57a        burgundy-farm_db_1     0.09%               471.8MiB / 1.955GiB   23.57%              1.18kB / 0B         9.92MB / 49.2kB     21
34f152ed575a        burgundy-farm_cli_1    0.03%               30.95MiB / 1.955GiB   1.55%               1.09kB / 0B         8.62MB / 8.19kB     5
  ```

</details>

**Comment by sean-e-dietrich** [comment]
@claytron5000 it sounds like you may be experiencing a bug similar to this https://github.com/docksal/docksal/issues/582 what happens when you run `fin project restart`

**Comment by achekulaev** [comment]
@claytron5000 https://blog.docksal.io/breaking-change-in-docker-compose-1-21-1-c00fda7e1b75

Closing for now since it is a knows breaking change with a known resolution path, but please comment in case of any further questions.

**Comment by claytron5000** [comment]
I'm really not sure what's going on here, whether this is the network issues @sean-e-dietrich linked to or if it's related to the dashes issue @achekulaev linked to. (Note, I have other projects that are running fine on the same computer.)
Here's the steps I took so far
1. Rename the directory `burgundyfarmd`
2. `fin stop && fin project reset`
```
Stopping services...
Stopping burgundyfarmd_web_1 ... done
Stopping burgundyfarmd_db_1  ... done
Stopping burgundyfarmd_cli_1 ... done
 ALERT:  Removing containers and volumes of burgundyfarmd
Continue? [y/n]: y
Removing containers...
Stopping burgundyfarmd_web_1 ... done
Stopping burgundyfarmd_db_1  ... done
Stopping burgundyfarmd_cli_1 ... done
Removing burgundyfarmd_web_1 ... done
Removing burgundyfarmd_db_1  ... done
Removing burgundyfarmd_cli_1 ... done
Removing network burgundyfarmd_default
Removing volume burgundyfarmd_project_root
Volume docksal_ssh_agent is external, skipping
Starting services...
Creating network "burgundyfarmd_default" with the default driver
Creating volume "burgundyfarmd_project_root" with local driver
Creating burgundyfarmd_db_1  ... done
Creating burgundyfarmd_cli_1 ... done
Creating burgundyfarmd_web_1 ... done
Waiting for burgundyfarmd_cli_1 to become ready...
Connected vhost-proxy to "burgundyfarmd_default" network.
burgundyfarmd git:master ❯ fin ps
       Name                     Command                State                 Ports
---------------------------------------------------------------------------------------------
burgundyfarmd_cli_1   /opt/startup.sh supervisord   Up (healthy)   22/tcp, 3000/tcp, 9000/tcp
burgundyfarmd_db_1    /entrypoint.sh mysqld         Up             0.0.0.0:32779->3306/tcp
burgundyfarmd_web_1   httpd-foreground              Up             443/tcp, 80/tcp
```
Still getting the bubbling flask...

**Comment by claytron5000** [comment]
`fin project restart` has the same result.

`fin cleanup && fin start`, same.

**Comment by achekulaev** [comment]
@claytron5000 please attach

1. new `fin config` output
2. screenshot of the tab with bubbling flask

**Comment by claytron5000** [comment]
```
---------------------
COMPOSE_PROJECT_NAME_SAFE: burgundyfarmd
COMPOSE_FILE:
/Users/clayton/.docksal/stacks/volumes-bind.yml
/Users/clayton/.docksal/stacks/stack-default.yml
/Users/clayton/Sites/burgundyfarmd/.docksal/docksal.yml
ENV_FILE:
/Users/clayton/Sites/burgundyfarmd/.docksal/docksal.env

PROJECT_ROOT: /Users/clayton/Sites/burgundyfarmd
DOCROOT: .
VIRTUAL_HOST: burgundyfarmd.docksal
VIRTUAL_HOST_ALIASES: *.burgundyfarmd.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32781

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: 27271793-18c5-4867-9e5c-8131a8b3242f
      BLACKFIRE_CLIENT_TOKEN: ec2f961d5fa68ec9c42eca60c1b8fe8eb64c29d4f1c08e2c5c5d52da0769afd7
      DOCROOT: .
      HOST_GID: '20'
      HOST_UID: '501'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: burgundyfarmd.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.2-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/.
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/clayton/Sites/burgundyfarmd
      io.docksal.virtual-host: burgundyfarmd.docksal,*.burgundyfarmd.docksal,burgundyfarmd.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/clayton/Sites/burgundyfarmd
      o: bind
      type: none

---------------------
```
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/5767672/41731000-402bde9c-754b-11e8-8c36-f64039d40378.png">
