### ISSUE TITLE
fin help can print custom commands in non-alphabetic order

### ISSUE THREAD

**Issue by shelane** [docksal/docksal#631]
**Description**

I have multiple systems where I am working on the same project. They are all Macs running OS 10.13.x. When running `fin help`, one of my systems will show the custom commands in a non-alphabetic order. I'm not sure why they would be correct in one system and not the other, but if there is a way to ensure that the list of commands is output alphabetically, it would make it easier to read through the list.

**Steps to reproduce the issue:**

1. Run `fin help`

Results...

```
Custom commands:
  site-rebuild             	Sync a local site with a dev, stage, or production database
  init                     	Initialize the Docksal environment for Drupal sites
  phpcs                    	Run Code Sniffer (phpcs) against given path
  init-testusers           	Add test-* users
  init-newsite             	Initialize a new multisite
  site-import              	Sync a local site with a dev, stage, or production database
  behat                    	Run project's Behat tests.
  refresh-aliases          	Define all aliases for prod domain sync requirements
  init-onelab              	Build local onelab site
  remove-site              	Remove an existing multisite
  phpcbf                   	Run Code Sniffer (phpcbf) against given path
  site-update              	Update a local site to current code base configuration
  unison                   	Force a resync of the unison volume
  dns                      	Update DNS settings for internal or local network
  init-www                 	Build local www site
  init-nvm                 	Initialize nvm requirements in cli
```
Expected behavior...
```
Custom commands:
  behat                    	Run project's Behat tests.
  dns                      	Update DNS settings for internal or local network
  init                     	Initialize the Docksal environment for Drupal sites
  init-newsite             	Initialize a new multisite
  init-nvm                 	Initialize nvm requirements in cli
  init-onelab              	Build local onelab site
  init-testusers           	Add test-* users
  init-www                 	Build local www site
  phpcbf                   	Run Code Sniffer (phpcbf) against given path
  phpcs                    	Run Code Sniffer (phpcs) against given path
  refresh-aliases          	Define all aliases for prod domain sync requirements
  remove-site              	Remove an existing multisite
  site-import              	Sync a local site with a dev, stage, or production database
  site-rebuild             	Rebuild a site in the cloud with the site profile installation
  site-update              	Update a local site to current code base configuration
  unison                   	Force a resync of the unison volume
```

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
fin config
---------------------
COMPOSE_PROJECT_NAME_SAFE: drupal7
COMPOSE_FILE:
/Users/french/.docksal/stacks/volumes-unison.yml
/Users/french/.docksal/stacks/stack-default.yml
/Users/french/Sites/docksal/drupal7/.docksal/docksal.yml
ENV_FILE:
/Users/french/Sites/docksal/drupal7/.docksal/docksal.env
/Users/french/Sites/docksal/drupal7/.docksal/docksal-local.env

PROJECT_ROOT: /Users/french/Sites/docksal/drupal7
DOCROOT: docroot
VIRTUAL_HOST: drupal7.docksal
VIRTUAL_HOST_ALIASES: *.drupal7.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32769

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 128.15.15.15
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '49799'
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SOURCE_ALIAS: '@drupal7.dev'
      VIRTUAL_HOST: drupal7.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.2-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 128.15.15.15
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  unison:
    environment:
      SYNC_DESTINATION: /destination
      SYNC_MAX_INOTIFY_WATCHES: '524288'
      SYNC_PREFER: newer
      SYNC_VERBOSE: '1'
      UNISON_GID: '20'
      UNISON_GROUP: dialout
      UNISON_UID: '49799'
      UNISON_USER: docker
    image: docksal/unison
    privileged: true
    volumes:
    - project_root:/destination:rw
    - /Users/french/Sites/docksal/drupal7:/source:rw
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 128.15.15.15
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/french/Sites/docksal/drupal7
      io.docksal.virtual-host: drupal7.docksal,*.drupal7.docksal,drupal7.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root: {}
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
fin sysinfo
███  OS
Darwin Mac OS X 10.13.4
Darwin highsparrow.drupal7.gov 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
Mode: Docker for Mac

███  FIN
fin version: 1.61.1

███  ENVIRONMENT
DOCKER_HOST		| 
 WARNING:  Non-default DOCKER_HOST
------------------------------------------------------------
DOCKSAL_NFS_PATH	| 

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true

███  DOCKER INFO
Containers: 21
 Running: 14
 Paused: 0
 Stopped: 7
Images: 29
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 5
Total Memory: 5.818GiB
Name: linuxkit-025000000001
ID: NTLW:M5F5:ZIUQ:6NV6:T32N:MYFH:DR44:DXSR:BQSJ:VNT3:VZX3:KTBV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 139
 Goroutines: 140
 System Time: 2018-06-21T04:47:12.196620801Z
 EventsListeners: 4
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
default   -        virtualbox   Stopped                 Unknown   
docksal   -        virtualbox   Stopped                 Unknown   

███  DOCKER: IMAGES
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
devdocksal/cli          latest              d8a3737b75de        5 days ago          883MB
docksal/cli             2.2-php7.1          f8397b8a269f        2 weeks ago         867MB
docksal/cli             <none>              79758adf1bab        3 weeks ago         867MB
docksal/cli             php7.1              1f969a53745d        3 weeks ago         867MB
phpmyadmin/phpmyadmin   latest              4bdc31ab2ded        3 weeks ago         164MB
docksal/unison          latest              b7d879d0e65e        5 weeks ago         16.8MB
docksal/db              1.2-mysql-5.6       0f0acba4c6d1        2 months ago        256MB
docksal/cli             2.1-php7.1          4c7331d4cf77        2 months ago        950MB
docksal/cli             2.0-php7.1          9ba7c35bb83f        3 months ago        914MB
docksal/cli             2.0-php5.6          0fea463bfbd9        3 months ago        887MB
docksal/vhost-proxy     1.2                 a1c980537985        3 months ago        166MB
wodby/drupal            8-7.1-4.2.2         c0ef0d8545b0        3 months ago        412MB
lpeabody/blt-cli        latest              ea0294b1a4ba        3 months ago        1.01GB
wodby/drupal-nginx      8-1.13-4.0.2        43cdae306275        3 months ago        47.9MB
portainer/portainer     latest              9b9a5552926f        3 months ago        34MB
traefik                 latest              8c72b944d569        3 months ago        49.6MB
wodby/mariadb           10.2-3.1.2          f717bf4d4985        3 months ago        259MB
docksal/varnish         1.1-varnish5        967b76b88b85        4 months ago        107MB
cweagans/bg-sync        latest              ebeae43e7c96        4 months ago        16.8MB
docksal/cli             1.3-php7            19bdddfeab89        9 months ago        759MB
docksal/web             2.1-apache2.4       32c1d32eba6d        10 months ago       87.5MB
docksal/vhost-proxy     1.1                 898fb21e7f2d        10 months ago       158MB
docksal/db              1.1-mysql-5.6       6feb79af9597        11 months ago       298MB
memcached               1.4-alpine          273374b463b8        11 months ago       7.68MB
mailhog/mailhog         latest              669347153085        14 months ago       19.1MB
docksal/dns             1.0                 20c7a535479d        17 months ago       61.6MB
docksal/ssh-agent       1.0                 148220cc033d        17 months ago       12.2MB
docksal/solr            1.0-solr4           fa6b236caf06        17 months ago       546MB
docksal/varnish         1.0-varnish4        35dae6b91ff9        17 months ago       99.5MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                PORTS                                                    NAMES
524d1af150bb        docksal/unison                 "bg-sync"                31 hours ago        Up 31 hours                                                                    drupal7_unison_1
7d774a04dd62        docksal/varnish:1.1-varnish5   "/opt/startup.sh"        5 days ago          Up 5 days             80/tcp, 6082/tcp                                         drupal8_varnish_1
a36207af1930        docksal/web:2.1-apache2.4      "httpd-foreground"       5 days ago          Up 5 days             80/tcp, 443/tcp                                          drupal8_web_1
bc9e15f969d6        docksal/cli:2.2-php7.1         "/opt/startup.sh sup…"   5 days ago          Up 5 days (healthy)   22/tcp, 3000/tcp, 9000/tcp                               drupal8_cli_1
df51e2521a26        devdocksal/cli                 "/opt/startup.sh sup…"   5 days ago          Up 5 days (healthy)   22/tcp, 9000/tcp, 0.0.0.0:3000->3000/tcp                 devdocksal_cli_1
6a1a6bc077d9        docksal/solr:1.0-solr4         "/opt/solr/bin/solr …"   7 days ago          Up 5 days             8983/tcp                                                 drupal8_solr_1
3320591f2421        docksal/db:1.2-mysql-5.6       "/entrypoint.sh mysq…"   7 days ago          Up 5 days             0.0.0.0:32768->3306/tcp                                  drupal8_db_1
0ab5d2e27efb        memcached:1.4-alpine           "docker-entrypoint.s…"   7 days ago          Up 5 days             11211/tcp                                                drupal8_memcached_1
5fc57ef5e6ec        docksal/ssh-agent:1.0          "/run.sh ssh-agent"      9 days ago          Up 5 days                                                                      docksal-ssh-agent
d969fbfb5a6b        docksal/dns:1.0                "/opt/entrypoint.sh …"   9 days ago          Up 5 days             192.168.64.100:53->53/udp                                docksal-dns
3d45391174b3        docksal/vhost-proxy:1.2        "docker-entrypoint.s…"   9 days ago          Up 5 days             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
6d3b1adc7a81        docksal/web:2.1-apache2.4      "httpd-foreground"       2 weeks ago         Up 2 days             80/tcp, 443/tcp                                          drupal7_web_1
397c3fb28167        docksal/cli:2.2-php7.1         "/opt/startup.sh sup…"   2 weeks ago         Up 2 days (healthy)   22/tcp, 3000/tcp, 9000/tcp                               drupal7_cli_1
649db0a58d77        docksal/db:1.2-mysql-5.6       "/entrypoint.sh mysq…"   2 weeks ago         Up 2 days             0.0.0.0:32769->3306/tcp                                  drupal7_db_1

███  VIRTUALBOX
EXPECTED VERSION: 5.2.2
5.2.12r122591

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  HDD Usage
Filesystem      Size   Used  Avail Capacity  iused               ifree %iused  Mounted on
/dev/disk3s1   466Gi  382Gi   79Gi    83%  3841097 9223372036850934710    0%   /
devfs          198Ki  198Ki    0Bi   100%      684                   0  100%   /dev
/dev/disk3s4   466Gi  5.0Gi   79Gi     6%        5 9223372036854775802    0%   /private/var/vm
map -hosts       0Bi    0Bi    0Bi   100%        0                   0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%        0                   0  100%   /home
map -fstab       0Bi    0Bi    0Bi   100%        0                   0  100%   /Network/Servers
/dev/disk0s2   931Gi  848Gi   83Gi    92% 25045580          4269921699    1%   /Volumes/Mac Back
/dev/disk1s2   931Gi  212Gi  719Gi    23%  1157894          4293809385    0%   /Volumes/Mac Genius

███  RAM Usage
Mach Virtual Memory Statistics: (page size of 4096 bytes)
Pages free:                              229050.
Pages active:                           3883328.
Pages inactive:                         3181129.
Pages speculative:                       125326.
Pages throttled:                              0.
Pages wired down:                        900367.
Pages purgeable:                          51636.
"Translation faults":                4290641658.
Pages copy-on-write:                   81356964.
Pages zero filled:                   1897818871.
Pages reactivated:                     68370737.
Pages purged:                           3209224.
File-backed pages:                      2059919.
Anonymous pages:                        5129864.
Pages stored in compressor:             1893699.
Pages occupied by compressor:             68984.
Decompressions:                       133239260.
Compressions:                         156058523.
Pageins:                              267961143.
Pageouts:                               4352082.
Swapins:                               54220552.
Swapouts:                              56033088.

███  RAM Usage per container
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
524d1af150bb        drupal7_unison_1         0.00%               52.25MiB / 5.818GiB   0.88%               6.75kB / 0B         245MB / 56.8MB      4
7d774a04dd62        drupal8_varnish_1       0.42%               8.293MiB / 5.818GiB   0.14%               102kB / 0B          22MB / 475kB        219
a36207af1930        drupal8_web_1           0.07%               10.43MiB / 5.818GiB   0.18%               2.63MB / 7.16MB     0B / 0B             109
bc9e15f969d6        drupal8_cli_1           2.30%               50.23MiB / 5.818GiB   0.84%               826MB / 382MB       36.5MB / 651kB      5
df51e2521a26        devdocksal_cli_1      0.02%               35.17MiB / 5.818GiB   0.59%               68.1MB / 23.1MB     36.5MB / 639kB      5
6a1a6bc077d9        drupal8_solr_1          0.08%               215.1MiB / 5.818GiB   3.61%               103kB / 0B          79.9MB / 65.5kB     37
3320591f2421        drupal8_db_1            0.06%               544.5MiB / 5.818GiB   9.14%               384MB / 843MB       88.5MB / 2.44GB     22
0ab5d2e27efb        drupal8_memcached_1     0.01%               1004KiB / 5.818GiB    0.02%               102kB / 0B          1.35MB / 0B         7
5fc57ef5e6ec        docksal-ssh-agent     0.00%               1.219MiB / 5.818GiB   0.02%               74.7kB / 0B         5.21MB / 0B         2
d969fbfb5a6b        docksal-dns           0.35%               16.64MiB / 5.818GiB   0.28%               177kB / 168kB       15.4MB / 0B         14
3d45391174b3        docksal-vhost-proxy   0.37%               21.98MiB / 5.818GiB   0.37%               29MB / 29.4MB       39.4MB / 53.2kB     19
6d3b1adc7a81        drupal7_web_1            0.08%               16.05MiB / 5.818GiB   0.27%               2.37MB / 16.6MB     4.41MB / 0B         109
397c3fb28167        drupal7_cli_1            2.17%               93.49MiB / 5.818GiB   1.57%               1.36GB / 657MB      673MB / 19MB        14
649db0a58d77        drupal7_db_1             0.07%               931.3MiB / 5.818GiB   15.63%              654MB / 1.32GB      237MB / 8.75GB      24
  ```

</details>
