### ISSUE TITLE
Use Xdebug with windows7 ?

### ISSUE THREAD

**Issue by acteg** [docksal/docksal#646]
**Description :**
After installing correctly docksal on new vm with windows 7 ( See this issue #644 ) i tried to import existing project, varnish, redis, db, https all this services work's good just Xdebug on web ( don't try it yet with drush) don't work.

I follow this doc to enable and configure xdebug with phpstorm https://docs.docksal.io/en/master/tools/xdebug/ but it's ot working.

**My problem :**

I think my problem was this settings ?

xdebug.remote_host 192.168.64.1

What do you think ? my phpstorm ( outside of vm ) is not listing correctely to post 9000

Thanks for you help.

**Comment by achekulaev** [comment]
So you installed Docksal inside your custom Ubuntu VM?

**Comment by acteg** [comment]
Yes, forgive me i updated issue with new description.

**Comment by achekulaev** [comment]
What is your host IP as seen from inside Ubuntu VM?

**Comment by acteg** [comment]
Forgive me i don't understand your question ?

You need ip adresse of windows inside Ubuntu vm ? 

Correct me if iam wrong but from inside vm you can' t see windows host it's not visible ?

If iam wrong how i can find this ip ?

Just for information on virtualbox i choose network mode to **NAT**. 

If i run ifconfig insive vm ubuntu i have this ( After runing fin up ) : 


```
br-432b7235047e Link encap:Ethernet  HWaddr 02:42:17:ca:23:a0
          inet addr:172.21.0.1  Bcast:172.21.255.255  Mask:255.255.0.0
          inet6 addr: fe80::42:17ff:feca:23a0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:648 (648.0 B)

br-4c67be4b549a Link encap:Ethernet  HWaddr 02:42:f5:25:07:bf
          inet addr:172.19.0.1  Bcast:172.19.255.255  Mask:255.255.0.0
          inet6 addr: fe80::42:f5ff:fe25:7bf/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:648 (648.0 B)

br-c59e7f424d49 Link encap:Ethernet  HWaddr 02:42:d4:a8:39:e6
          inet addr:172.18.0.1  Bcast:172.18.255.255  Mask:255.255.0.0
          inet6 addr: fe80::42:d4ff:fea8:39e6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:648 (648.0 B)

docker0   Link encap:Ethernet  HWaddr 02:42:a5:b0:48:7a
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          inet6 addr: fe80::42:a5ff:feb0:487a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:19 errors:0 dropped:0 overruns:0 frame:0
          TX packets:23 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1497 (1.4 KB)  TX bytes:1990 (1.9 KB)

enp0s3    Link encap:Ethernet  HWaddr 08:00:27:59:45:32
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe59:4532/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3411 errors:0 dropped:0 overruns:0 frame:0
          TX packets:493 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4298687 (4.2 MB)  TX bytes:48299 (48.2 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:180 errors:0 dropped:0 overruns:0 frame:0
          TX packets:180 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:13488 (13.4 KB)  TX bytes:13488 (13.4 KB)

lo:docksal Link encap:Local Loopback
          inet addr:192.168.64.1  Mask:255.255.255.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1

veth0706811 Link encap:Ethernet  HWaddr 96:b2:6b:93:d3:ca
          inet6 addr: fe80::94b2:6bff:fe93:d3ca/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:1052 (1.0 KB)

veth03e4f74 Link encap:Ethernet  HWaddr 1a:d3:2f:85:25:b0
          inet6 addr: fe80::18d3:2fff:fe85:25b0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:648 (648.0 B)

veth39fc659 Link encap:Ethernet  HWaddr 42:7a:05:31:8c:59
          inet6 addr: fe80::407a:5ff:fe31:8c59/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:19 errors:0 dropped:0 overruns:0 frame:0
          TX packets:28 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1763 (1.7 KB)  TX bytes:2380 (2.3 KB)

veth72c5103 Link encap:Ethernet  HWaddr fe:f9:c6:44:15:6c
          inet6 addr: fe80::fcf9:c6ff:fe44:156c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:13 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:962 (962.0 B)

veth824da3d Link encap:Ethernet  HWaddr 16:76:e2:e3:f5:be
          inet6 addr: fe80::1476:e2ff:fee3:f5be/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:648 (648.0 B)

veth87ee43b Link encap:Ethernet  HWaddr 22:f4:6e:f8:d2:23
          inet6 addr: fe80::20f4:6eff:fef8:d223/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:1296 (1.2 KB)

veth906b3b5 Link encap:Ethernet  HWaddr 5a:d4:06:d6:d5:29
          inet6 addr: fe80::58d4:6ff:fed6:d529/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:648 (648.0 B)

vethc9ff24b Link encap:Ethernet  HWaddr 2e:d0:82:7d:da:ca
          inet6 addr: fe80::2cd0:82ff:fe7d:daca/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:648 (648.0 B)

vethcea1f55 Link encap:Ethernet  HWaddr 3a:d2:6e:02:52:94
          inet6 addr: fe80::38d2:6eff:fe02:5294/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:1296 (1.2 KB)

vethd38a2c6 Link encap:Ethernet  HWaddr ea:49:2d:e5:52:9b
          inet6 addr: fe80::e849:2dff:fee5:529b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:1296 (1.2 KB)

vethe5ea0e0 Link encap:Ethernet  HWaddr ca:33:b3:aa:67:f0
          inet6 addr: fe80::c833:b3ff:feaa:67f0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:648 (648.0 B)
```

**Comment by achekulaev** [comment]
https://superuser.com/a/619633/140872

**Comment by acteg** [comment]
Ok thanks for this link, i have **nat** value and when i run this command i have this result : 
```
netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.0.2.2        0.0.0.0         UG        0 0          0 enp0s3
10.0.2.0        0.0.0.0         255.255.255.0   U         0 0          0 enp0s3
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-c59e7f424d49
172.19.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-4c67be4b549a
172.21.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-432b7235047e
```
Normally the ip we need is **10.0.2.2 (Ip of host windows)** , But when i run this command docksal are listing to this port  adress ?

```
curl 10.0.2.2
<html>
  <head>
    <title>Project Not Found.</title>

    <style>
    html, body
    {
      height: 100%;
      margin: 0;
      padding: 0;
    }

    body {
      background-color: #bbece6;
    }

    div {
      position: relative;
      height: 100%;
      width: 100%;
    }

    div img {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      margin: auto;
    }
    </style>

  </head>
  <body>
    <div>
      <img src="//i.imgur.com/nt9ZFBt.jpg" alt="Loading..." height="428px" width="640px">
    </div>
  </body>
</html>
```

**Comment by achekulaev** [comment]
Since you have this custom install you will need to override the host that XDebug connects to. 

1.
    ```
    fin config set --global DOCKSAL_HOST_IP="10.0.2.2"
    ```

1. Check `fin project config`, it should have the line `XDEBUG_CONFIG: remote_connect_back=0 remote_host=10.0.2.2` now

1. Restart your project `fin project start`.

Now when you start Php Storm listener XDebug should be able to connect to it.

**Comment by acteg** [comment]
After runing config set i have always this : 
```
 XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
```
My fin project config : 

```

---------------------
COMPOSE_PROJECT_NAME_SAFE: aso
COMPOSE_FILE:
/home/docker/.docksal/stacks/volumes-bind.yml
/home/docker/.docksal/stacks/stack-default.yml
/home/docker/deploy/aso/.docksal/docksal.yml
ENV_FILE:
/home/docker/deploy/aso/.docksal/docksal.env
/home/docker/deploy/aso/.docksal/docksal-local.env

PROJECT_ROOT: /home/docker/deploy/aso
DOCROOT: web
VIRTUAL_HOST: aso.docksal
VIRTUAL_HOST_ALIASES: *.aso.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: web
      HOST_GID: '1000'
      HOST_UID: '1000'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: aso.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.2-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  redis:
    environment:
      REDIS_MAXMEMORY: 256m
    hostname: redis
    image: wodby/redis:4.0
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:1.1-varnish5
    labels:
      io.docksal.virtual-host: varnish.aso.docksal,varnish.aso.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/web
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /home/docker/deploy/aso
      io.docksal.virtual-host: aso.docksal,*.aso.docksal,aso.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/docker/deploy/aso
      o: bind
      type: none

---------------------

```

**Comment by achekulaev** [comment]
What your docksal.yml looks like?

**Comment by acteg** [comment]
Ok My docksal fil : 
```
version: "2.1"

services:
  # Varnish
  varnish:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: varnish
    depends_on:
      - web
  # Redis
  redis:
    hostname: redis
    image: wodby/redis:4.0
    environment:
      - REDIS_MAXMEMORY=256m
```
And my docksal-local.env

```
# Override virtual host (matches project folder name by default)
VIRTUAL_HOST=aso.docksal
# Override document root ('docroot' by default)
DOCROOT=web
# Enable Xdebug
XDEBUG_ENABLED=1
```

**Comment by achekulaev** [comment]
@acteg ah right sorry, it is not configurable yet.

You will have to override it via docksal.yml

```
version: "2.1"

services:
  cli:
    environment:
      - XDEBUG_CONFIG=remote_connect_back=0 remote_host=10.0.2.2
```

and then follow steps 2 and 3 from my comment above.
