### ISSUE TITLE
1.9.1  debugging drush commands (9.2.3) doesn't work.

### ISSUE THREAD

**Issue by vierlex** [docksal/docksal#677]
**Description**

Problem/feature description...

**Steps to reproduce the issue:**

1. Set Up  Xdebug for drush debugging https://docksal.readthedocs.io/en/master/tools/xdebug/
2. Try setting a breakpoint where drush might be concerned (in my case I tried getRoutes() function from a HtmlRouteProvider)
3. Run fin drush cr

**Describe the results you received:**

Breakpoints are not triggered, also there is no message/warning from phpstorm that debugging went through without an event.

**Describe the results you expected:**

triggering the break point

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: netidee_application
COMPOSE_FILE:
/home/alex/.docksal/stacks/volumes-bind.yml
/home/alex/projects/netidee_application/.docksal/docksal.yml
/home/alex/projects/netidee_application/.docksal/docksal-local.yml
ENV_FILE:
/home/alex/projects/netidee_application/.docksal/docksal.env

PROJECT_ROOT: /home/alex/projects/netidee_application
DOCROOT: web
VIRTUAL_HOST: net-app.docksal
VIRTUAL_HOST_ALIASES: *.net-app.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32781

Docker Compose configuration
---------------------
services:
  cli:
    environment:
      DRUSH_ALLOW_XDEBUG: '1'
      PHP_IDE_CONFIG: serverName=net-app.docksal
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:php7.0
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw
  db:
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:mysql-5.7
    ports:
    - 3306/tcp
    volumes:
    - /home/alex/projects/netidee_application/db/current:/var/lib/mysql:rw
  web:
    depends_on:
      cli:
        condition: service_started
    environment:
      APACHE_DOCUMENTROOT: /var/www/web
      VIRTUAL_HOST: net-app.docksal
    hostname: web
    image: docksal/web:apache2.4
    labels:
      io.docksal.project-root: /home/alex/projects/netidee_application
      io.docksal.virtual-host: net-app.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/alex/projects/netidee_application
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  Linux Ubuntu 18.04
Linux alex-HP-Z420-Workstation 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Mode: Linux Kernel

███  FIN
fin version: 1.60.2

███  ENVIRONMENT
DOCKER_HOST             | 
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Wed Jun 20 21:43:51 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Wed Jun 20 21:42:00 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER INFO
Containers: 20
 Running: 11
 Paused: 0
 Stopped: 9
Images: 16
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-23-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.34GiB
Name: alex-HP-Z420-Workstation
ID: ODV2:NKJB:KRGJ:34CN:JTKD:Y7RR:BOKM:JNKM:WJTC:4UQ3:VF3A:QA4Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
WARNING: No swap limit support

███  DOCKER: IMAGES
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
phpmyadmin/phpmyadmin   latest              93d0d7db5ce2        10 days ago         166MB
docksal/cli             php7.1              1f969a53745d        4 weeks ago         867MB
docksal/cli             php7.0              e7a5fd889f26        4 weeks ago         865MB
docksal/db              1.2-mysql-5.7       514af96ffc68        2 months ago        371MB
docksal/db              mysql-5.7           738abb9518d5        2 months ago        371MB
docksal/cli             2.0-php7.2          8f42648197b3        3 months ago        842MB
docksal/vhost-proxy     1.2                 a1c980537985        3 months ago        166MB
docksal/cli             1.3-php7            19bdddfeab89        9 months ago        759MB
docksal/web             2.1-apache2.4       32c1d32eba6d        10 months ago       87.5MB
docksal/web             apache2.2           831d93f02bc2        10 months ago       81MB
docksal/web             apache2.4           15bf93edaf13        10 months ago       87.5MB
docksal/dns             1.0                 20c7a535479d        17 months ago       61.6MB
docksal/ssh-agent       1.0                 148220cc033d        17 months ago       12.2MB
docksal/web             1.0-apache2.2       a9c03f8a5f0f        17 months ago       188MB
docksal/db              1.0-mysql-5.5       9fb8c0aed5fc        17 months ago       255MB
docksal/solr            4.x                 d9925b62e361        18 months ago       546MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                   PORTS                                                    NAMES
adb5d054ccae        docksal/web:apache2.4          "httpd-foreground"       9 minutes ago       Up 9 minutes             80/tcp, 443/tcp                                          netidee_application_web_1
ff3003df6c53        docksal/cli:php7.0             "/opt/startup.sh sup…"   9 minutes ago       Up 9 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               netidee_application_cli_1
7cbcd11daf3e        docksal/db:mysql-5.7           "/entrypoint.sh mysq…"   9 minutes ago       Up 9 minutes             0.0.0.0:32781->3306/tcp                                  netidee_application_db_1
67867206c109        docksal/web:apache2.2          "httpd-foreground"       5 hours ago         Up 5 hours               80/tcp, 443/tcp                                          netidee_web_1
4be2f086692e        docksal/cli:php7.0             "/opt/startup.sh sup…"   5 hours ago         Up 5 hours (healthy)     22/tcp, 3000/tcp, 9000/tcp                               netidee_cli_1
b5a9c06cd171        phpmyadmin/phpmyadmin:latest   "/run.sh supervisord…"   5 days ago          Up 5 hours               80/tcp, 9000/tcp                                         netidee_pma_1
cb0210fd8061        docksal/solr:4.x               "/opt/solr/bin/solr …"   5 days ago          Up 5 hours               8983/tcp                                                 netidee_solr_1
0317b883306f        docksal/db:mysql-5.7           "/entrypoint.sh mysq…"   5 days ago          Up 5 hours               0.0.0.0:32771->3306/tcp                                  netidee_db_1
9a2e4116718b        docksal/dns:1.0                "/opt/entrypoint.sh …"   12 days ago         Up 5 hours               192.168.64.100:53->53/udp                                docksal-dns
cdef7356a7ce        docksal/vhost-proxy:1.2        "docker-entrypoint.s…"   12 days ago         Up 5 hours               192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
35911f9d88b2        docksal/ssh-agent:1.0          "/run.sh ssh-agent"      12 days ago         Up 5 hours                                                                        docksal-ssh-agent

███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
udev             16G     0   16G   0% /dev
tmpfs           3,2G  2,9M  3,2G   1% /run
/dev/sda1       234G   66G  156G  30% /
tmpfs            16G  321M   16G   2% /dev/shm
tmpfs           5,0M  4,0K  5,0M   1% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/loop1       87M   87M     0 100% /snap/core/4830
/dev/loop4      3,4M  3,4M     0 100% /snap/gnome-system-monitor/36
/dev/loop0      141M  141M     0 100% /snap/gnome-3-26-1604/59
/dev/loop2       15M   15M     0 100% /snap/gnome-logs/37
/dev/loop3      1,7M  1,7M     0 100% /snap/gnome-calculator/154
/dev/loop6       13M   13M     0 100% /snap/gnome-characters/69
/dev/loop5       21M   21M     0 100% /snap/gnome-logs/25
/dev/loop7      140M  140M     0 100% /snap/chromium/353
/dev/loop9      2,4M  2,4M     0 100% /snap/gnome-calculator/178
/dev/loop8       87M   87M     0 100% /snap/core/4486
/dev/loop10      13M   13M     0 100% /snap/gnome-characters/101
/dev/loop11      80M   80M     0 100% /snap/keepassxc/38
/dev/loop12     140M  140M     0 100% /snap/gnome-3-26-1604/64
/dev/loop13     144M  144M     0 100% /snap/slack/7
/dev/loop14     3,8M  3,8M     0 100% /snap/gnome-system-monitor/45
/dev/loop15      87M   87M     0 100% /snap/core/4917
tmpfs           3,2G   20K  3,2G   1% /run/user/120
tmpfs           3,2G   48K  3,2G   1% /run/user/1000

███  RAM Usage
              total        used        free      shared  buff/cache   available
Mem:       32862716     6318488    14983880      449216    11560348    25628672
Swap:       2097148           0     2097148

███  RAM Usage per container
CONTAINER ID        NAME                        CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
adb5d054ccae        netidee_application_web_1   0.14%               9.539MiB / 31.34GiB   0.03%               211kB / 656kB       0B / 0B             109
ff3003df6c53        netidee_application_cli_1   0.03%               73.04MiB / 31.34GiB   0.23%               31.1MB / 27.2MB     20.5MB / 156kB      5
7cbcd11daf3e        netidee_application_db_1    0.09%               251.8MiB / 31.34GiB   0.78%               26.9MB / 30.9MB     9.3MB / 491MB       29
67867206c109        netidee_web_1               0.00%               6.855MiB / 31.34GiB   0.02%               110kB / 0B          0B / 0B             6
4be2f086692e        netidee_cli_1               0.03%               35.37MiB / 31.34GiB   0.11%               9.4MB / 13.9MB      0B / 32.8kB         5
b5a9c06cd171        netidee_pma_1               0.03%               29.54MiB / 31.34GiB   0.09%               111kB / 0B          0B / 0B             9
cb0210fd8061        netidee_solr_1              0.08%               215.2MiB / 31.34GiB   0.67%               111kB / 0B          0B / 131kB          37
0317b883306f        netidee_db_1                0.08%               253.5MiB / 31.34GiB   0.79%               41.9MB / 27.9MB     19.1MB / 740MB      28
9a2e4116718b        docksal-dns                 0.33%               21.14MiB / 31.34GiB   0.07%               793kB / 783kB       31.5MB / 0B         16
cdef7356a7ce        docksal-vhost-proxy         0.27%               26.54MiB / 31.34GiB   0.08%               1.57MB / 3.81MB     79.2MB / 434kB      25
35911f9d88b2        docksal-ssh-agent           0.00%               4.719MiB / 31.34GiB   0.01%               127kB / 0B          10.3MB / 0B         2

  ```

</details>
