### ISSUE TITLE
Interpreter not specified or invalid in PHPStorm for xdebug

### ISSUE THREAD

**Issue by purcelltastic** [docksal/docksal#687]
**Description**

Problem/feature description...
I am trying to get xdebug running so I can debug a d7 to d8 migration. It says the interpreter is not specified or invalid
**Steps to reproduce the issue:**

1. Running existing project in docksal
2. Added project to phpstorm
3. Note error when I try to start debug
4. I have no clue about how to configure the remote PHP interpreter and could use some help picking the right settings

**Describe the results you received:**

The edit configuration window says "Error: Interpreter is not specified or invalid. Pres "Fix"...

I'm guessing I should change the PHP language level to 7.1, since I am using image "docksal/cli:2.2-php7.1". When I go to add a remote cli interpreter I think I should probably pick docker or docker compose to specify it, but I don't know which and I don't know which settings. Any help would be much appreciated.

**Describe the results you expected:**

Expected behavior...

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
COMPOSE_PROJECT_NAME_SAFE: tsad8_gov_build
COMPOSE_FILE:
/home/watchmework/.docksal/stacks/volumes-bind.yml
/home/watchmework/.docksal/stacks/stack-default.yml
/home/watchmework/Documents/tsa/D8/tsad8_gov_build/.docksal/docksal.yml
ENV_FILE:
/home/watchmework/Documents/tsa/D8/tsad8_gov_build/.docksal/docksal.env
/home/watchmework/Documents/tsa/D8/tsad8_gov_build/.docksal/docksal-local.env

PROJECT_ROOT: /home/watchmework/Documents/tsa/D8/tsad8_gov_build
DOCROOT: docroot
VIRTUAL_HOST: tsad8.docksal
VIRTUAL_HOST_ALIASES: *.tsad8.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32769

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      HOST_GID: '1001'
      HOST_UID: '1001'
      PHP_IDE_CONFIG: serverName=tsad8.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: tsad8.docksal
      XDEBUG_CONFIG: idekey=PHPSTORM remote_host=192.168.64.100
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.2-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  memcached1:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached1
    image: memcached:1.4-alpine
  memcached2:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached2
    image: memcached:1.4-alpine
  memcached3:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached3
    image: memcached:1.4-alpine
  memcached4:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached4
    image: memcached:1.4-alpine
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /home/watchmework/Documents/tsa/D8/tsad8_gov_build
      io.docksal.virtual-host: tsad8.docksal,*.tsad8.docksal,tsad8.docksal.*
    ports:
    - 80/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/watchmework/Documents/tsa/D8/tsad8_gov_build
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  ➜  docroot git:(develop) ✗ fin sysinfo
WARNING: No swap limit support
███  OS
Linux Ubuntu 16.04
Linux lotus 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Mode: Linux Kernel

███  FIN
fin version: 1.60.2

███  ENVIRONMENT
DOCKER_HOST		| 
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER INFO
Containers: 81
 Running: 17
 Paused: 0
 Stopped: 64
Images: 22
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-130-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 23.26GiB
Name: lotus
ID: A3Q4:4FBD:BDLF:IDMF:BOTV:RQ2D:CYT5:2MMF:OHMI:JY3W:NJGE:4U4I
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
WARNING: No swap limit support

███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/cli           2.2-php7.1          f8397b8a269f        4 weeks ago         867MB
docksal/cli           2.2-php5.6          f7332f798bb1        4 weeks ago         821MB
runwaytest_web        latest              e403623639d7        2 months ago        377MB
php                   7-apache            e403623639d7        2 months ago        377MB
mysql                 5.7                 0d16d0a97dd1        2 months ago        372MB
mysql                 latest              a8a59477268d        2 months ago        445MB
httpd                 latest              fb2f3851a971        2 months ago        178MB
debian                latest              8626492fecd3        2 months ago        101MB
docksal/db            1.2-mysql-5.6       0f0acba4c6d1        3 months ago        256MB
docksal/db            1.2-mysql-5.5       6f53aab3e999        3 months ago        205MB
docksal/cli           2.1-php7.1          4c7331d4cf77        3 months ago        950MB
docksal/cli           2.0-php7.1          9ba7c35bb83f        3 months ago        914MB
docksal/cli           2.0-php7.2          8f42648197b3        3 months ago        842MB
docksal/cli           2.0-php7.0          7c26d9c5e115        3 months ago        912MB
docksal/cli           2.0-php5.6          0fea463bfbd9        3 months ago        887MB
docksal/vhost-proxy   1.2                 a1c980537985        3 months ago        166MB
docksal/web           2.1-apache2.4       32c1d32eba6d        10 months ago       87.5MB
docksal/db            1.1-mysql-5.6       6feb79af9597        11 months ago       298MB
memcached             1.4-alpine          273374b463b8        11 months ago       7.68MB
docksal/dns           1.0                 20c7a535479d        17 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        17 months ago       12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        17 months ago       188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        17 months ago       255MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                       PORTS                                                    NAMES
32b0dd1f5e60        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   2 days ago          Up About an hour             0.0.0.0:32769->3306/tcp                                  tsad8_gov_build_db_1
61b071ba8a78        docksal/web:2.1-apache2.4   "httpd-foreground"       2 days ago          Up About an hour             443/tcp, 0.0.0.0:32768->80/tcp                           tsad8_gov_build_web_1
f22d6e135e0b        docksal/cli:2.2-php7.1      "/opt/startup.sh sup…"   2 days ago          Up About an hour (healthy)   22/tcp, 3000/tcp, 9000/tcp                               tsad8_gov_build_cli_1
c44820fdcefd        docksal/web:2.1-apache2.4   "httpd-foreground"       3 weeks ago         Up About an hour             443/tcp, 0.0.0.0:32771->80/tcp                           tsa2_gov_build_web_1
d0e747ca7d5e        memcached:1.4-alpine        "docker-entrypoint.s…"   3 weeks ago         Up About an hour             11211/tcp                                                tsa2_gov_build_memcached4_1
56267434f0ba        docksal/db:1.2-mysql-5.5    "/entrypoint.sh mysq…"   3 weeks ago         Up About an hour             0.0.0.0:32770->3306/tcp                                  tsa2_gov_build_db_1
ddbb23a9f80e        memcached:1.4-alpine        "docker-entrypoint.s…"   3 weeks ago         Up About an hour             11211/tcp                                                tsa2_gov_build_memcached2_1
685bf0581795        docksal/cli:2.2-php5.6      "/opt/startup.sh sup…"   3 weeks ago         Up About an hour (healthy)   22/tcp, 3000/tcp, 9000/tcp                               tsa2_gov_build_cli_1
38f2ae685504        memcached:1.4-alpine        "docker-entrypoint.s…"   3 weeks ago         Up About an hour             11211/tcp                                                tsa2_gov_build_memcached1_1
0bed8d844f71        memcached:1.4-alpine        "docker-entrypoint.s…"   3 weeks ago         Up About an hour             11211/tcp                                                tsa2_gov_build_memcached3_1
43c96da6ad70        memcached:1.4-alpine        "docker-entrypoint.s…"   3 weeks ago         Up About an hour             11211/tcp                                                tsad8_gov_build_memcached2_1
4dba0e7e6a00        memcached:1.4-alpine        "docker-entrypoint.s…"   3 weeks ago         Up About an hour             11211/tcp                                                tsad8_gov_build_memcached1_1
51c9be351fe7        memcached:1.4-alpine        "docker-entrypoint.s…"   3 weeks ago         Up About an hour             11211/tcp                                                tsad8_gov_build_memcached4_1
36fb0572133a        memcached:1.4-alpine        "docker-entrypoint.s…"   3 weeks ago         Up About an hour             11211/tcp                                                tsad8_gov_build_memcached3_1
220939fb67e3        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      3 weeks ago         Up About an hour                                                                      docksal-ssh-agent
debbc7964b9c        docksal/dns:1.0             "/opt/entrypoint.sh …"   3 weeks ago         Up About an hour             192.168.64.100:53->53/udp                                docksal-dns
70defc90c45d        docksal/vhost-proxy:1.2     "docker-entrypoint.s…"   3 weeks ago         Up About an hour             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  VIRTUALBOX
EXPECTED VERSION: 5.2.2
5.1.34_Ubuntur121010

███  VIRTUALBOX NETWORK INTERFACES

███  HDD Usage
Filesystem                         Size  Used Avail Use% Mounted on
udev                                12G     0   12G   0% /dev
tmpfs                              2.4G   11M  2.4G   1% /run
/dev/mapper/ubuntu--mate--vg-root  664G  137G  494G  22% /
tmpfs                               12G   66M   12G   1% /dev/shm
tmpfs                              5.0M  4.0K  5.0M   1% /run/lock
tmpfs                               12G     0   12G   0% /sys/fs/cgroup
/dev/loop1                         248M  248M     0 100% /snap/phpstorm/32
/dev/loop0                          87M   87M     0 100% /snap/core/4917
/dev/loop4                         249M  249M     0 100% /snap/phpstorm/38
/dev/loop2                          87M   87M     0 100% /snap/core/4650
/dev/loop3                          87M   87M     0 100% /snap/core/4830
/dev/loop5                         252M  252M     0 100% /snap/phpstorm/36
/dev/sda2                          473M  238M  211M  54% /boot
/dev/sda1                          511M  3.5M  508M   1% /boot/efi
tmpfs                              2.4G   36K  2.4G   1% /run/user/1001

███  RAM Usage
              total        used        free      shared  buff/cache   available
Mem:       24385252     3896636    17484340      260144     3004276    19786476
Swap:      24854524           0    24854524

███  RAM Usage per container
CONTAINER ID        NAME                           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
32b0dd1f5e60        tsad8_gov_build_db_1           0.05%               476.4MiB / 23.26GiB   2.00%               700kB / 6.71MB      95.7MB / 37.9MB     23
61b071ba8a78        tsad8_gov_build_web_1          0.08%               5.316MiB / 23.26GiB   0.02%               369kB / 988kB       17.5MB / 0B         109
f22d6e135e0b        tsad8_gov_build_cli_1          1.51%               66.13MiB / 23.26GiB   0.28%               13.5MB / 6.15MB     287MB / 115kB       9
c44820fdcefd        tsa2_gov_build_web_1           0.07%               4.82MiB / 23.26GiB    0.02%               225kB / 864kB       1.6MB / 0B          109
d0e747ca7d5e        tsa2_gov_build_memcached4_1    0.01%               520KiB / 23.26GiB     0.00%               24.5kB / 0B         0B / 0B             7
56267434f0ba        tsa2_gov_build_db_1            0.05%               106.8MiB / 23.26GiB   0.45%               1.38MB / 10.7MB     136MB / 70.5MB      16
ddbb23a9f80e        tsa2_gov_build_memcached2_1    0.01%               528KiB / 23.26GiB     0.00%               24.5kB / 0B         0B / 0B             7
685bf0581795        tsa2_gov_build_cli_1           1.50%               166MiB / 23.26GiB     0.70%               10.7MB / 1.59MB     153MB / 385kB       6
38f2ae685504        tsa2_gov_build_memcached1_1    0.01%               528KiB / 23.26GiB     0.00%               24.5kB / 0B         0B / 0B             7
0bed8d844f71        tsa2_gov_build_memcached3_1    0.01%               528KiB / 23.26GiB     0.00%               24.5kB / 0B         0B / 0B             7
43c96da6ad70        tsad8_gov_build_memcached2_1   0.01%               24.8MiB / 23.26GiB    0.10%               841kB / 1.54MB      0B / 0B             7
4dba0e7e6a00        tsad8_gov_build_memcached1_1   0.01%               27.73MiB / 23.26GiB   0.12%               1.76MB / 2.87MB     0B / 0B             7
51c9be351fe7        tsad8_gov_build_memcached4_1   0.01%               28.66MiB / 23.26GiB   0.12%               1.54MB / 1.2MB      0B / 0B             7
36fb0572133a        tsad8_gov_build_memcached3_1   0.01%               22.89MiB / 23.26GiB   0.10%               830kB / 649kB       3.96MB / 0B         7
220939fb67e3        docksal-ssh-agent              0.00%               660KiB / 23.26GiB     0.00%               31.1kB / 0B         10.1MB / 0B         2
debbc7964b9c        docksal-dns                    0.21%               13.93MiB / 23.26GiB   0.06%               118kB / 96.2kB      30.5MB / 0B         12
70defc90c45d        docksal-vhost-proxy            0.19%               16.89MiB / 23.26GiB   0.07%               2.16MB / 1.96MB     74.7MB / 41kB       16
➜  docroot git:(develop) ✗ 

  ```

</details>
![selection_023](https://user-images.githubusercontent.com/2780689/42337416-a02fefcc-803b-11e8-87ef-0c14be0e2039.png)
![selection_024](https://user-images.githubusercontent.com/2780689/42337426-a533d920-803b-11e8-9c94-696f9dc1b150.png)
![selection_026](https://user-images.githubusercontent.com/2780689/42337435-aa51b68e-803b-11e8-8db1-1b87f19980d0.png)
