### ISSUE TITLE
Cant get fin init to work, ERROR: network ebs_default id ### has active endpoints

### ISSUE THREAD

**Issue by alexandar87** [docksal/docksal#697]
**Description**

I cant get passed `fin init` or `fin project remove` due to error. It happens only in one project.

**Steps to reproduce the issue:**

1. Started VM with `fin vm start`
2. Typed `fin init` or `fin project remove`
3. Error happen

**Describe the results you received:**

``` alex@alexs-mbp  ~/projects/ffw/ebs   master  fin init
 Step 1  Initializing local project configuration...
/Users/alex/projects/ebs/docroot/sites/default/settings.local.php already in place.
 Step 2  Recreating services...
Removing containers...
Removing ebs_web_1     ... done
Removing ebs_cli_1     ... done
Removing ebs_varnish_1 ... done
Removing ebs_db_1      ... done
Removing network ebs_default
ERROR: network ebs_default id de61849dbc2b1bc0c224a5a458e0367b2ad6a2c52b79925e833ea7c0019cac23 has active endpoints
```

**Describe the results you expected:**

I expected my `fin init` command to pass like ususal.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: ebs
COMPOSE_FILE:
/Users/alex/.docksal/stacks/volumes-bind.yml
/Users/alex/projects/ebs/.docksal/docksal.yml
ENV_FILE:
/Users/alex/projects/ebs/.docksal/docksal.env
/Users/alex/projects/ebs/.docksal/docksal-local.env

PROJECT_ROOT: /Users/alex/projects/ebs
DOCROOT: docroot
VIRTUAL_HOST: ebs.docksal
VIRTUAL_HOST_ALIASES: *.ebs.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    environment:
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:1.3-php7
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw
  db:
    environment:
      MYSQL_DATABASE: ebs
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: drupal
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro
  varnish:
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:1.0-varnish4
    labels:
      io.docksal.virtual-host: varnish.ebs.docksal
    volumes:
    - /Users/alex/projects/ebs/.docksal/etc/varnish/default.vcl:/opt/default.vcl:ro
  web:
    depends_on:
      cli:
        condition: service_started
    environment:
      APACHE_DOCUMENTROOT: /var/www/docroot
      VIRTUAL_HOST: ebs.docksal
    hostname: web
    image: docksal/web:1.0-apache2.2
    labels:
      io.docksal.project-root: /Users/alex/projects/ebs
      io.docksal.virtual-host: ebs.docksal
    volumes:
    - project_root:/var/www:ro
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/alex/projects/ebs
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
   alex@alexs-mbp  ~/projects/eastern-bank-micro-site   master  fin sysinfo
███  OS
Darwin Mac OS X 10.13.4
Darwin alexs-mbp 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
Mode: VirtualBox VM

███  FIN
fin version: 1.60.2

███  ENVIRONMENT
DOCKER_HOST		| tcp://192.168.64.100:2376
------------------------------------------------------------
DOCKSAL_NFS_PATH	| 

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.06.0-ce-rc1
  API version:  1.38 (minimum version 1.12)
  Go version:   go1.10.3
  Git commit:   20580f1
  Built:        Thu Jun 28 06:25:00 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER INFO
Containers: 46
 Running: 6
 Paused: 0
 Stopped: 40
Images: 19
Server Version: 18.06.0-ce-rc1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 396
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cbef57047e900aeb2bafe7a634919bec13f4a2a5
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-boot2docker
Operating System: Boot2Docker 18.06.0-ce-rc1 (TCL 8.2.1); HEAD : 17a6556 - Mon Jul  2 17:23:14 UTC 2018
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.764GiB
Name: docksal
ID: ZL7Q:ZB3D:6LNI:VLQI:RFHG:J576:KBAL:QJW4:RWPD:DYUE:HHFU:VDXH
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER            ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.06.0-ce-rc1   

███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
wernight/ngrok        latest              dd5f31fb305e        7 weeks ago         22MB
docksal/db            1.2-mysql-5.6       0f0acba4c6d1        3 months ago        256MB
docksal/cli           2.1-php7.1          4c7331d4cf77        3 months ago        950MB
docksal/cli           2.0-php7.1          9ba7c35bb83f        3 months ago        914MB
docksal/cli           2.0-php7.2          8f42648197b3        3 months ago        842MB
docksal/cli           2.0-php5.6          0fea463bfbd9        3 months ago        887MB
docksal/vhost-proxy   1.2                 a1c980537985        3 months ago        166MB
docksal/cli           1.3-php7            19bdddfeab89        9 months ago        759MB
docksal/cli           1.3-php5            80248f5ea845        9 months ago        814MB
docksal/web           2.1-apache2.4       32c1d32eba6d        10 months ago       87.5MB
docksal/web           2.0-apache2.4       7f75db9a6aa7        11 months ago       87.5MB
docksal/vhost-proxy   1.1                 898fb21e7f2d        11 months ago       158MB
docksal/db            1.1-mysql-5.6       6feb79af9597        11 months ago       298MB
docksal/dns           1.0                 20c7a535479d        17 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        17 months ago       12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        17 months ago       188MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        17 months ago       255MB
docksal/solr          1.0-solr4           fa6b236caf06        18 months ago       546MB
docksal/varnish       1.0-varnish4        35dae6b91ff9        18 months ago       99.5MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
0e6cb6c466bd        docksal/vhost-proxy:1.2   "docker-entrypoint.s…"   2 months ago        Up 15 minutes       192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
03e8d1e6e654        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      2 months ago        Up 15 minutes                                                                docksal-ssh-agent
29a5493f8448        docksal/dns:1.0           "/opt/entrypoint.sh …"   2 months ago        Up 15 minutes       192.168.64.100:53->53/udp                                docksal-dns

███  VIRTUALBOX
EXPECTED VERSION: 5.2.2
5.2.2r119230

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.3G     20.4G     23.4G  47% /mnt/sda1

███  RAM Usage
             total       used       free     shared    buffers     cached
Mem:       3947224     842780    3104444     249680      91880     531300
-/+ buffers/cache:     219600    3727624
Swap:      1878200          0    1878200

███  RAM Usage per container
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
0e6cb6c466bd        docksal-vhost-proxy   0.24%               24.73MiB / 3.764GiB   0.64%               51.1kB / 10.7kB     37.9MB / 32.8kB     10
03e8d1e6e654        docksal-ssh-agent     0.00%               1.09MiB / 3.764GiB    0.03%               2.49kB / 0B         5.82MB / 0B         2
29a5493f8448        docksal-dns           0.25%               19.23MiB / 3.764GiB   0.50%               2.68kB / 358B       14.9MB / 4.1kB      9
 alex@alexs-mbp  ~/projects/eastern-bank-micro-site   master  

  ```

</details>
