### ISSUE TITLE
NFS volumes support for Docker for Mac

### ISSUE THREAD

**Issue by GMTA** [docksal/docksal#711]
**Description**
When using Docker for Mac, `DOCKSAL_HOST_IP` points to `192.168.64.1` but the internal host IP is `192.168.65.2` by default. Because `volume-nfs.yml` uses `DOCKSAL_HOST_IP` as the address and Docker is unable to reach this IP address, NFS mounts fail. The reason for this is that the `192.168.64.x` range is visible for the Mac host while `192.168.65.x` is visible to the Docker for Mac VM.

Unfortunately, it is also not possible to override `DOCKSAL_HOST_IP` through the global `docksal.env`. It can be done using the project's `docksal.env` however. It doesn't work because the global `docksal.env` is loaded before `DOCKSAL_HOST_IP` is set.

**Steps to reproduce the issue:**
1. Install Docker for Mac and Docksal
2. Configure an NFS server on the local machine
3. Set `DOCKSAL_VOLUMES=nfs` on a project
4. Run `fin up`

**Describe the results you received:**
Mounting fails with a message like:
```
ERROR: for cli  Cannot start service cli: error while mounting volume '/var/lib/docker/volumes/my_project_root/_data': error while mounting volume with options: type='nfs' device=':/Users/username/path/to/project' o='addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,tcp,actimeo=1': permission denied
```

**Describe the results you expected:**
Docksal should set the correct internal host IP/address, or at least allow me to override the `DOCKSAL_HOST_IP` value used in `volumes-nfs.yml` using the global `docksal.env`.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: :/Users/username/path/to/project
      o: addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,tcp,actimeo=1
      type: nfs
```

</details>
