### ISSUE TITLE
Updating solr configuration tutorial doesn't work.

### ISSUE THREAD

**Issue by gmakely** [docksal/docksal#717]
**Description**

The tutorial for local customization of solr config for development does not work for me. I have been able to get this to work in the past, but no longer. I'm using the solr config files from my Acquia installation so that I can tweak them and submit for installation.

**Steps to reproduce the issue:**

1. Follow the tutorial at: https://docs.docksal.io/en/master/tools/apache-solr/#updating-solr-configuration
2. Added the following to my .docksal/docksal.yml file:
```
  # Solr
  solr:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/conf:/var/lib/solr/conf:ro
```

**Describe the results you received:**

When trying to visit the solr UI, I receive a massive error message that starts with:
```
{msg=SolrCore 'collection1' is not available due to init failure: Could not load conf for core collection1
```
The server is running but there is no collection.

**Describe the results you expected:**

When I remove the 
```
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/conf:/var/lib/solr/conf:ro
```
lines from my .yml file, solr works fine. But this defeats the purpose for me.

**fin config output**
```
COMPOSE_PROJECT_NAME_SAFE: unexadmin
COMPOSE_FILE:
/Users/user/.docksal/stacks/volumes-bind.yml
/Users/user/Projects/d8/unexadmin/.docksal/docksal.yml
ENV_FILE:
/Users/user/Projects/d8/unexadmin/.docksal/docksal.env

PROJECT_ROOT: /Users/user/Projects/d8/unexadmin
DOCROOT: docroot
VIRTUAL_HOST: unexadmin.docksal
VIRTUAL_HOST_ALIASES: *.unexadmin.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32770

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      HOST_GID: '20'
      HOST_UID: '502'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.1-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.7
    ports:
    - 3306/tcp
    volumes:
    - /Users/user/Projects/d8/unexadmin/db:/docker-entrypoint-initdb.d:ro
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: solr
    image: docksal/solr:1.0-solr4
    labels:
      io.docksal.virtual-host: solr.unexadmin.docksal,solr.unexadmin.docksal.*
      io.docksal.virtual-port: '8983'
    volumes:
    - /Users/user/Projects/d8/unexadmin/.docksal/etc/solr/conf:/var/lib/solr/conf:ro
    - project_root:/var/www:ro,nocopy
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:1.0-varnish4
    labels:
      io.docksal.virtual-host: varnish.unexadmin.docksal
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/user/Projects/d8/unexadmin
      io.docksal.virtual-host: unexadmin.docksal,*.unexadmin.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/user/Projects/d8/unexadmin
      o: bind
      type: none
```
