### ISSUE TITLE
Cannot get ide.*.docksal to work.

### ISSUE THREAD

**Issue by mike-potter** [docksal/docksal#721]
I tried following the instructions for enabling the Cloud9 IDE in my docksal project. Added IDE_ENABLED="1" to docksal.env and restarted.  Verified that when building the cli container it shows:
```
Successfully tagged docksal/cli:edge-php7.1-ide
```
But when I visit http://ide.myproject.docksal I just got a "502 Bad Gateway" error from nginx.  When I do a "fin vhosts" I can see the ide.myproject.docksal entry.  Any advice on how to debug this further?  My site at myproject.docksal is working fine, so it's just the IDE.

(Running on Mac OSX 10.12.4, fin version = 1.60.2 (not sure why this doesn't match the docksal version or how to determine that))

**Comment by lmakarov** [comment]
@mike-potter please post the output from `fin config` and `fin sysinfo` as the issue template suggests. This will help us better understand your environment specifics.

Next, check the cli logs with `fin logs cli` to see if there are any clues. Cloud9 logs will show up there.

**Comment by mike-potter** [comment]
I wasn't comfortable posting the exact output so I've edited some parts for client privacy:
```
% fin config
---------------------
COMPOSE_PROJECT_NAME_SAFE: myproject
COMPOSE_FILE:
/Users/mpotter/.docksal/stacks/overrides-osxfs.yml
/Users/mpotter/.docksal/stacks/volumes-bind.yml
/Users/mpotter/.docksal/stacks/stack-default.yml
/Users/mpotter/Projects/myproject/.docksal/docksal.yml
/Users/mpotter/.docksal/stacks/overrides-ide.yml
ENV_FILE:
/Users/mpotter/Projects/myproject/.docksal/docksal.env

PROJECT_ROOT: /Users/mpotter/Projects/myproject
DOCROOT: build/html
VIRTUAL_HOST: myproject.docksal
VIRTUAL_HOST_ALIASES: *.myproject.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32771

Docker Compose configuration
---------------------
services:
  cli:
    build:
      context: /Users/mpotter/Projects/myproject/.docksal/services/cli
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCKER_ENV: local
      DOCROOT: build/html
      HOST_GID: '20'
      HOST_UID: '501'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: myproject.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:edge-php7.1-ide
    labels:
      io.docksal.virtual-host: ide.myproject.docksal,ide.myproject.docksal.*
      io.docksal.virtual-port: '3000'
    ports:
    - 3001:3001/tcp
    - 3050:3050/tcp
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - /Users/mpotter/Projects/myproject:/var/www:rw,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: drupal
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: admin
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  solr:
    build:
      context: /Users/mpotter/Projects/myproject/env/solr/docker
    hostname: solr
    labels:
      io.docksal.virtual-host: solr.myproject.docksal
    ports:
    - 8983:8983/tcp
    volumes:
    - /Users/mpotter/Projects/myproject/env/solr/cores/sitesearch:/opt/solr/server/solr/sitesearch:rw
    - search-data:/var/lib/solr:rw
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/build/html
      DOCKER_ENV: local
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/mpotter/Projects/myproject
      io.docksal.virtual-host: myproject.docksal,*.myproject.docksal,myproject.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/mpotter/Projects/myproject
      o: bind
      type: none
  search-data: {}

---------------------
```
███  OS
Darwin Mac OS X 10.12.4
Darwin MPotters-MacBook-Pro.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
Mode: Docker for Mac

███  FIN
fin version: 1.60.2

███  ENVIRONMENT
DOCKER_HOST   |
 WARNING:  Non-default DOCKER_HOST
------------------------------------------------------------
DOCKSAL_NFS_PATH  |

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER INFO
Containers: 24
 Running: 8
 Paused: 0
 Stopped: 16
Images: 38
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
default   -        virtualbox   Error                   Unknown   machine does not exist
mepdev    -        xhyve        Stopped                 Unknown

███  DOCKER: IMAGES
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
myproject_solr             latest              f785556c86cf        3 days ago          264MB
docksal/cli            edge-php7.1-ide     e474bd895ae6        9 days ago          927MB
myproject_cli              latest              e474bd895ae6        9 days ago          927MB
docksal/cli            2.2-php7.1          f8397b8a269f        6 weeks ago         867MB
docksal/unison         latest              b7d879d0e65e        2 months ago        16.8MB
docksal/db             1.2-mysql-5.6       0f0acba4c6d1        3 months ago        256MB
docksal/vhost-proxy    1.2                 a1c980537985        4 months ago        166MB
docksal/web            2.1-apache2.4       32c1d32eba6d        10 months ago       87.5MB
docksal/dns            1.0                 20c7a535479d        18 months ago       61.6MB
docksal/ssh-agent      1.0                 148220cc033d        18 months ago       12.2MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                  PORTS                                                                        NAMES
983c63bf90b4        docksal/web:2.1-apache2.4     "httpd-foreground"       16 hours ago        Up 16 hours             80/tcp, 443/tcp                                                              myproject_web_1
461d28545483        docksal/cli:edge-php7.1-ide   "/opt/startup.sh sup…"   16 hours ago        Up 16 hours (healthy)   22/tcp, 0.0.0.0:3001->3001/tcp, 3000/tcp, 9000/tcp, 0.0.0.0:3050->3050/tcp   myproject_cli_1
a2962c20f6d5        docksal/ssh-agent:1.0         "/run.sh ssh-agent"      46 hours ago        Up 46 hours                                                                                          docksal-ssh-agent
77c3bc4bf9d4        docksal/dns:1.0               "/opt/entrypoint.sh …"   46 hours ago        Up 46 hours             192.168.64.100:53->53/udp                                                    docksal-dns
da8561bac1df        docksal/vhost-proxy:1.2       "docker-entrypoint.s…"   46 hours ago        Up 46 hours             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp                       docksal-vhost-proxy
a627f8ce7a33        myproject_solr                    "docker-entrypoint.s…"   2 days ago          Up 16 hours             0.0.0.0:8983->8983/tcp                                                       myproject_solr_1
530d6d596785        docksal/db:1.2-mysql-5.6      "/entrypoint.sh mysq…"   2 days ago          Up 16 hours             0.0.0.0:32771->3306/tcp                                                      myproject_db_1

███  VIRTUALBOX
EXPECTED VERSION: 5.2.2
5.0.16r105871

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

#"/Users" 192.168.64.1 -alldirs -mapall=501:20
# docker-machine-nfs-begin dev #
/Users 192.168.99.100 -alldirs -mapall=501:20
# docker-machine-nfs-end dev #
███  HDD Usage
Filesystem                                                                          Size   Used  Avail Capacity     iused      ifree %iused  Mounted on
/dev/disk1                                                                         233Gi  221Gi   11Gi    96%     4385561 4290581718    0%   /
devfs                                                                              245Ki  245Ki    0Bi   100%         854          0  100%   /dev
map -hosts                                                                           0Bi    0Bi    0Bi   100%           0          0  100%   /net
map auto_home                                                                        0Bi    0Bi    0Bi   100%           0          0  100%   /home

███  RAM Usage
Mach Virtual Memory Statistics: (page size of 4096 bytes)
Pages free:                                7484.
Pages active:                           1329343.
Pages inactive:                         1320748.
Pages speculative:                         6696.
Pages throttled:                              0.
Pages wired down:                        764568.
Pages purgeable:                         323621.
"Translation faults":                 287623947.
Pages copy-on-write:                    7537110.
Pages zero filled:                     94262328.
Pages reactivated:                     36669545.
Pages purged:                            569696.
File-backed pages:                       332561.
Anonymous pages:                        2324226.
Pages stored in compressor:             2863048.
Pages occupied by compressor:            763628.
Decompressions:                        17993104.
Compressions:                          26198513.
Pageins:                                7173587.
Pageouts:                                138083.
Swapins:                                5169043.
Swapouts:                               5698266.

███  RAM Usage per container
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
983c63bf90b4        myproject_web_1           0.23%               5.258MiB / 1.952GiB   0.26%               1.18kB / 0B         0B / 0B             82
461d28545483        myproject_cli_1           0.04%               30.1MiB / 1.952GiB    1.51%               1.3kB / 192B        0B / 8.19kB         5
a2962c20f6d5        docksal-ssh-agent     0.00%               1.055MiB / 1.952GiB   0.05%               6.63kB / 0B         10.2MB / 0B         2
77c3bc4bf9d4        docksal-dns           0.49%               5.539MiB / 1.952GiB   0.28%               46.8kB / 49kB       24.4MB / 0B         13
da8561bac1df        docksal-vhost-proxy   0.36%               10.43MiB / 1.952GiB   0.52%               147MB / 148MB       58.3MB / 61.4kB     16
a627f8ce7a33        myproject_solr_1          0.37%               234.2MiB / 1.952GiB   11.72%              1.18kB / 0B         8.19kB / 180kB      37
530d6d596785        myproject_db_1            0.07%               469.8MiB / 1.952GiB   23.51%              1.18kB / 0B         0B / 49.2kB         21
```
Nothing really in the "fin logs cli" when I go to ide.myproject.docksal.  The 502 Bad Gateway error from nginx implies that it's not even trying to start Cloud9 yet and can't route to the ide vhost.
