### ISSUE TITLE
Documentation around how to free up space in VM

### ISSUE THREAD

**Issue by paulsheldrake** [docksal/docksal#722]
**Description**

Looks like the docker image for one of my projects has run out of space.   What would be cool is if there were some docksal specific documentation around how to free up space

**Steps to reproduce the issue:**

Not sure, sorry

**Describe the results you received:**

```
/var/www/.docksal/commands/refresh: line 10: cannot create temp file for here-document: No space left on device
/var/www/.docksal/commands/refresh: line 11: cannot create temp file for here-document: No space left on device
```

**Describe the results you expected:**

My refresh command to work

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: plpteach4all
COMPOSE_FILE:
/Users/paulsheldrake/.docksal/stacks/volumes-bind.yml
/Users/paulsheldrake/docksal/kanopi_docksal/plpteach4all/.docksal/docksal.yml
ENV_FILE:
/Users/paulsheldrake/docksal/kanopi_docksal/plpteach4all/.docksal/docksal.env

PROJECT_ROOT: /Users/paulsheldrake/docksal/kanopi_docksal/plpteach4all
DOCROOT: docroot
VIRTUAL_HOST: t4a.docksal
VIRTUAL_HOST_ALIASES: *.t4a.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '501'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_BLACKFIRE_CLIENT_ID: null
      SECRET_BLACKFIRE_CLIENT_TOKEN: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      T4A_DB_STRING: gc2016 gc2017 gc2018 nz2015_dev plpteach4all
      T4A_MULTISITE_STRING: gc2016 gc2017 gc2018 gc2015
      VIRTUAL_HOST: t4a.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.0-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /Users/paulsheldrake/docksal/kanopi_docksal/plpteach4all/.docksal/etc/drush:/etc/drush:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.t4a.docksal
    user: root
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: solr
    image: docksal/solr:1.0-solr4
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: solr.t4a.docksal,solr.t4a.docksal.*
      io.docksal.virtual-port: '8983'
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FILE_PROXY: http://portal.teachforall.org
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.project-root: /Users/paulsheldrake/docksal/kanopi_docksal/plpteach4all
      io.docksal.virtual-host: t4a.docksal,*.t4a.docksal,t4a.docksal.*
    volumes:
    - /Users/paulsheldrake/docksal/kanopi_docksal/plpteach4all/.docksal/etc/apache/host.conf:/usr/local/apache2/conf/extra/includes/host.conf:ro
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/paulsheldrake/docksal/kanopi_docksal/plpteach4all
      o: bind
      type: none

---------------------

```

</details>

<br>
**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
 ███  OS
Darwin Mac OS X 10.12.6
Darwin Kanopi-MBP.hitronhub.home 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : /Users/paulsheldrake/docksal
NFS EXPORTS:
# VAGRANT-BEGIN: 501 19ed865d-28dd-4d57-931b-0fc57b856b49
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.88.88 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/pnw/pnw_drupalvm" 192.168.88.88 -alldirs -mapall=501:20
# VAGRANT-END: 501 19ed865d-28dd-4d57-931b-0fc57b856b49
# VAGRANT-BEGIN: 501 29e3522b-b1c7-4494-8aff-83deff88c628
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.33.88 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/zopfli_vm" 192.168.33.88 -alldirs -mapall=501:20
# VAGRANT-END: 501 29e3522b-b1c7-4494-8aff-83deff88c628
# VAGRANT-BEGIN: 501 dadbb7be-2ff1-4237-a61f-4a81ab6cb9ea
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.32.88 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/coit/backups" 192.168.32.88 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/coit/coit-d7" 192.168.32.88 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/coit/drupalvm_coit" 192.168.32.88 -alldirs -mapall=501:20
# VAGRANT-END: 501 dadbb7be-2ff1-4237-a61f-4a81ab6cb9ea
# VAGRANT-BEGIN: 501 409fe48b-b565-4a78-a5b4-5d3e4b7591cd
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.88.88 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/ico/drupalvm_ico" 192.168.88.88 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/ico/ico-rally" 192.168.88.88 -alldirs -mapall=501:20
# VAGRANT-END: 501 409fe48b-b565-4a78-a5b4-5d3e4b7591cd
# VAGRANT-BEGIN: 501 e48f4e7d-f212-4fb7-b14f-5d78fb7df132
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/centos6" 10.20.1.3 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/zuckerman/zuckerman" "/Users/paulsheldrake/Documents/work/kanopi/zuckerman/zuckerman/htdocs" "/Users/paulsheldrake/Documents/work/kanopi/zuckerman/zuckerman/docs/dist" "/Users/paulsheldrake/Documents/work/kanopi/zuckerman/zuckerman/patternlab" 10.20.1.3 -alldirs -mapall=501:20
# VAGRANT-END: 501 e48f4e7d-f212-4fb7-b14f-5d78fb7df132
# VAGRANT-BEGIN: 501 295d1905-cd25-4033-aaf7-68503d0ef346
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1204" 192.168.87.67 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/campbell/campbell_prod" 192.168.87.67 -alldirs -mapall=501:20
# VAGRANT-END: 501 295d1905-cd25-4033-aaf7-68503d0ef346
# VAGRANT-BEGIN: 501 1d73fb9c-f88e-4ecf-9161-ed48e9ee8b18
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.32.33 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/coda/wak/drupalvm_wak" 192.168.32.33 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/coda/wak/wakahuia" 192.168.32.33 -alldirs -mapall=501:20
# VAGRANT-END: 501 1d73fb9c-f88e-4ecf-9161-ed48e9ee8b18
# VAGRANT-BEGIN: 501 d266237d-9b71-4941-9de4-18227948e7ae
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.83.14 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/campbell/campbell_usd_new" 192.168.83.14 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/campbell/drupalvm_build" 192.168.83.14 -alldirs -mapall=501:20
# VAGRANT-END: 501 d266237d-9b71-4941-9de4-18227948e7ae
# VAGRANT-BEGIN: 501 7a01afa1-1699-4a3c-827a-a9636819343f
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.34.29 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/kerstens/drupalvm_kerstens" 192.168.34.29 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/kerstens/kerstens-antiques" 192.168.34.29 -alldirs -mapall=501:20
# VAGRANT-END: 501 7a01afa1-1699-4a3c-827a-a9636819343f

# VAGRANT-BEGIN: 501 012bb458-dc36-44c4-82ae-a56aa52e9025
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.45.21 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/thtbc/drupalvm-thtbccom" 192.168.45.21 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/thtbc/thtbccom" 192.168.45.21 -alldirs -mapall=501:20
# VAGRANT-END: 501 012bb458-dc36-44c4-82ae-a56aa52e9025

# VAGRANT-BEGIN: 501 ae60f4e7-ee00-491d-a138-41cb0d902dec
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.21.12 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/sfcm/drupalvm-sfcm" 192.168.21.12 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/sfcm/sfcm" 192.168.21.12 -alldirs -mapall=501:20
# VAGRANT-END: 501 ae60f4e7-ee00-491d-a138-41cb0d902dec
# VAGRANT-BEGIN: 501 d195ca06-fff4-46d2-a06b-2f8b5c587a1b
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.21.39 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/mcevoy/drupalvm_mcevoy" 192.168.21.39 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/mcevoy/mcevoy" 192.168.21.39 -alldirs -mapall=501:20
# VAGRANT-END: 501 d195ca06-fff4-46d2-a06b-2f8b5c587a1b
# VAGRANT-BEGIN: 501 83c53ace-1b4b-4c2d-bff7-202e2bd2e323
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.29.92 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/happy-tails/drupalvm-happy-tails" 192.168.29.92 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/happy-tails/happy-tails-teeth-cleaning" 192.168.29.92 -alldirs -mapall=501:20
# VAGRANT-END: 501 83c53ace-1b4b-4c2d-bff7-202e2bd2e323





# VAGRANT-BEGIN: 501 344d5c96-d53e-4c08-a644-563d2f51c1b6
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.38.88 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/mises/drupalvm_mises" 192.168.38.88 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/mises/mises.org" 192.168.38.88 -alldirs -mapall=501:20
# VAGRANT-END: 501 344d5c96-d53e-4c08-a644-563d2f51c1b6
# VAGRANT-BEGIN: 501 8ae7354d-589e-4262-8a03-e964bada3fb4
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.99.11 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/sfpl/code" 192.168.99.11 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/sfpl/drupal-vm" 192.168.99.11 -alldirs -mapall=501:20
# VAGRANT-END: 501 8ae7354d-589e-4262-8a03-e964bada3fb4

# VAGRANT-BEGIN: 501 0a322c50-097e-402c-ba45-0d46614f64e0
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.88.11 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/kilroy/drupalvm_kilroy" 192.168.88.11 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/kilroy/kilroy" 192.168.88.11 -alldirs -mapall=501:20
# VAGRANT-END: 501 0a322c50-097e-402c-ba45-0d46614f64e0
# VAGRANT-BEGIN: 501 1d04e324-1a4c-4a3b-a5b9-8b42f1bdc30c
"/Users/paulsheldrake/Documents/work/kanopi/twit/techguylabs-com" 10.20.1.4 -alldirs -mapall=501:20
# VAGRANT-END: 501 1d04e324-1a4c-4a3b-a5b9-8b42f1bdc30c
# VAGRANT-BEGIN: 501 b2c77538-90f0-4e22-9e3c-925c9836ca78
"/Users/paulsheldrake/Documents/work/kanopi/ischool/www-ischool" 10.20.1.2 -alldirs -mapall=501:20
# VAGRANT-END: 501 b2c77538-90f0-4e22-9e3c-925c9836ca78

# VAGRANT-BEGIN: 501 c2016ecd-8a1f-4f1a-8395-914247b50452
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.82.23 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/brain1st/brain-1st" 192.168.82.23 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/brain1st/drupalvm_brain1st" 192.168.82.23 -alldirs -mapall=501:20
# VAGRANT-END: 501 c2016ecd-8a1f-4f1a-8395-914247b50452


# VAGRANT-BEGIN: 501 887771ae-e3e3-404c-a68f-d591e6dac7e8
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.88.54 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/ibew/drupalvm_ibew_46" 192.168.88.54 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/ibew/ibew1269" 192.168.88.54 -alldirs -mapall=501:20
# VAGRANT-END: 501 887771ae-e3e3-404c-a68f-d591e6dac7e8
# VAGRANT-BEGIN: 501 1179c2ee-0215-4462-9ce6-358c457c6148
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.88.44 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/paml/drupalvm_paml" 192.168.88.44 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/paml/paml" 192.168.88.44 -alldirs -mapall=501:20
# VAGRANT-END: 501 1179c2ee-0215-4462-9ce6-358c457c6148


# VAGRANT-BEGIN: 501 6d76c8b5-af98-4ae0-bb3c-55c09c1e9ba2
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.53.88 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/stratford/drupalvm_stratford" 192.168.53.88 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/stratford/stratfordschool" 192.168.53.88 -alldirs -mapall=501:20
# VAGRANT-END: 501 6d76c8b5-af98-4ae0-bb3c-55c09c1e9ba2
# VAGRANT-BEGIN: 501 c8452f93-258e-44b3-8151-d851e03f0dcb
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.23.39 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/ndi/drupalvm-ndi-tech" 192.168.23.39 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/ndi/ndiorg" 192.168.23.39 -alldirs -mapall=501:20
# VAGRANT-END: 501 c8452f93-258e-44b3-8151-d851e03f0dcb
# <ds-nfs docksal
/Users/paulsheldrake/docksal 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
# VAGRANT-BEGIN: 501 07983d3d-e67b-4044-9c10-51ff08ced34b
"/Users/paulsheldrake/Documents/work/kanopi/twit/elroy-twit-tv" 192.168.33.45 -alldirs -mapall=501:20
# VAGRANT-END: 501 07983d3d-e67b-4044-9c10-51ff08ced34b

███  FIN
fin version: 1.65.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:03 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.03.1-ce   

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                    project root
plpteach4all        Up 13 minutes       t4a.docksal,*.t4a.docksal,t4a.docksal.*         /Users/paulsheldrake/docksal/kanopi_docksal/plpteach4all
misesorg            Up 17 hours         mises.docksal,*.mises.docksal,mises.docksal.*   /Users/paulsheldrake/docksal/kanopi_docksal/mises/mises.org

███  DOCKSAL: VIRTUAL HOSTS
http://*.mises.docksal
http://*.t4a.docksal
http://mises.docksal.*
http://mises.docksal
http://solr.t4a.docksal.*
http://solr.t4a.docksal
http://t4a.docksal.*
http://t4a.docksal
http://webmail.mises.docksal
http://webmail.t4a.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
e07d6be81199        docksal/web:2.1-apache2.4   "httpd-foreground"       29 minutes ago      Up 13 minutes             80/tcp, 443/tcp                                          plpteach4all_web_1
f8698801940d        memcached:1.4-alpine        "docker-entrypoint.s…"   29 minutes ago      Up 13 minutes             11211/tcp                                                plpteach4all_memcached_1
216823b93f3d        mailhog/mailhog             "MailHog"                29 minutes ago      Up 13 minutes             80/tcp, 1025/tcp, 8025/tcp                               plpteach4all_mail_1
d03664ab6c75        docksal/cli:2.0-php7.1      "/opt/startup.sh sup…"   29 minutes ago      Up 13 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               plpteach4all_cli_1
ebf2ab60bbcf        docksal/solr:1.0-solr4      "/opt/solr/bin/solr …"   29 minutes ago      Up 13 minutes             8983/tcp                                                 plpteach4all_solr_1
8f7da115565d        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      16 hours ago        Up 16 hours                                                                        docksal-ssh-agent
62e81ec5cede        docksal/dns:1.0             "/opt/entrypoint.sh …"   16 hours ago        Up 16 hours               192.168.64.100:53->53/udp                                docksal-dns
8a2d76fa6343        docksal/vhost-proxy:1.2     "docker-entrypoint.s…"   16 hours ago        Up 16 hours               192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
e697f23385cf        docksal/web:2.1-apache2.4   "httpd-foreground"       17 hours ago        Up 17 hours               80/tcp, 443/tcp                                          misesorg_web_1
2e2499d92889        docksal/cli:1.3-php5        "/opt/startup.sh sup…"   17 hours ago        Up 17 hours (healthy)     22/tcp, 9000/tcp                                         misesorg_cli_1
ae7a685b6ed0        memcached:1.4-alpine        "docker-entrypoint.s…"   17 hours ago        Up 17 hours               11211/tcp                                                misesorg_memcached_1
ebf5085ea89a        mailhog/mailhog             "MailHog"                17 hours ago        Up 17 hours               80/tcp, 1025/tcp, 8025/tcp                               misesorg_mail_1
7b566f99e350        blackfire/blackfire         "blackfire-agent"        17 hours ago        Up 17 hours               8707/tcp                                                 misesorg_blackfire_1
5baf9641b2a5        docksal/db:1.1-mysql-5.7    "/entrypoint.sh mysq…"   17 hours ago        Up 17 hours               0.0.0.0:32784->3306/tcp                                  misesorg_db_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                    DRIVER              SCOPE
dd16fe2e9cf2        _default                bridge              local
6b120b05e63c        bridge                  bridge              local
bc53fca5fec6        elroy-twit-tv_default   bridge              local
0e25f1f2a024        host                    host                local
3a869850a268        misesorg_default        bridge              local
58f0f3d87608        none                    null                local
82024cdf0b40        plpteach4all_default    bridge              local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.2
5.2.2r119230

███  DOCKSAL MOUNTS
192.168.64.1:/Users/paulsheldrake/docksal on /Users/paulsheldrake/docksal type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/paulsheldrake/docksal/kanopi_docksal/mises/mises.org on /mnt/sda1/var/lib/docker/volumes/misesorg_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/paulsheldrake/docksal/kanopi_docksal/plpteach4all on /mnt/sda1/var/lib/docker/volumes/plpteach4all_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.3G     43.8G         0 100% /mnt/sda1

  ```

</details>
