### ISSUE TITLE
Elasticsearch in Docksal

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#725]
Add support for and document using Elasticsearch with Docksal.

**Comment by achekulaev** [comment]
From gitter channel:

```
  elasticsearch:
    hostname: elasticsearch
    image: elasticsearch:1.7.5
    ports:
      - "9200"
```

**Comment by sean-e-dietrich** [comment]
are we looking for just Elastic Search or the whole ELK stack?

**Comment by leoman730** [comment]
For later version of elasticsearch, 

```
  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
      - "9200:9200"
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
```
There's a captcha on setting vm.max_map_count, read: https://www.elastic.co/guide/en/elasticsearch/reference/6.4/docker.html

In my case, i have to run:
```
docker-machine ssh docksal
sudo sysctl -w vm.max_map_count=262144

```

**Comment by lmakarov** [comment]
@leoman730 thanks for the tip!

The page you referred to says:

> 
The vm.max_map_count kernel setting needs to be set to at least 262144 for **production use**.

Where you running into any issues with elasticsearch locally without making that adjustment?

**Comment by achekulaev** [comment]
Marking this as todo to add a service to the services.yml.

**Comment by lmakarov** [comment]
What's the difference between `docker.elastic.co/elasticsearch/elasticsearch` and the official `elasticsearch` images on Docker Hub? Unless there is a strong reason to use the former, I'd prefer to stick with images from Docker Hub.

**Comment by achekulaev** [comment]
@lmakarov the first one is the official one. The latter is the legacy. Have you followed the link from the comment above? https://www.elastic.co/guide/en/elasticsearch/reference/6.4/docker.html

**Comment by lmakarov** [comment]
Looks like images on Docker Hub are still updated and are identical to those from `docker.elastic.co/elasticsearch/elasticsearch`. See https://github.com/docker-library/elasticsearch/blob/ea4c976edb44a00de9ef45f1a4bff50d6aa31e4a/6/Dockerfile

I'd stick with the Docker Hub images to keep things consistent (and have shorter image names). The latest version is: `elasticsearch:6.5.3` (identical to `docker.elastic.co/elasticsearch/elasticsearch:6.5.3`).

**Comment by lmakarov** [comment]
> I would stick to the official documentation

@achekulaev I guess, that is a good point in terms of transparency.
One note, though - the [official MySQL Docker](https://dev.mysql.com/doc/mysql-installation-excerpt/5.6/en/docker-mysql-getting-started.html) docs mention using `docker/mysql-server` image, which is Oracle based, yet we are using `docksal/mysql` - the Official Docker Hub image - as the upstream.

> unless there is a good reason not to.

I see a few (though, I do admit they are nice-to-haves):
- Use Docker Hun as a consistent image source
- shorter image name `elasticsearch:6.5.3`, which will look cleaner in `docker ps` output
- Easy of reviewing available versions (and their size) on https://hub.docker.com/_/elasticsearch/?tab=tags

So, it's a question of following the docs verbatim vs having those nice to haves.
Knowing that the images are identical, I'm choosing the nice-to-haves.

**Comment by achekulaev** [comment]
@lmakarov yeah I don't mind too much. Let's use the ones from the Docker Hub, it's not a big deal.

**Comment by verbeeksteven** [comment]
Elasticsearch will always fail to start with Exit code 78 the

    docker-machine ssh docksal
    sudo sysctl -w vm.max_map_count=262144

needs to be ran each time and then it restarted. Is there anyway to have this happen by default?

**Comment by achekulaev** [comment]
@verbeeksteven as per [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html) you can set it permanently in the config file

> To set this value permanently, update the `vm.max_map_count` setting in `/etc/sysctl.conf`

@lmakarov I guess we need that in docs

**Comment by verbeeksteven** [comment]
How would you add this to docksal so it happens everytime it is booted up? Atm other people on my team need to manually ssh in and do this. Is there a way to have it persist?

**Comment by lmakarov** [comment]
Per https://forums.docker.com/t/how-do-i-make-persistent-settings-sysctl-conf-and-others-changes-to-the-virtual-machine/13149/5

**Docker for Mac**

```
vim ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/etc/sysctl.conf — you can use it like this. And don’t forget to git commit it
```

**Docker Machine (VirtualBox)**

```
docker-machine ssh [machine_name]
sudo vi /var/lib/boot2docker/bootlocal.sh
Add the following command to bootlocal.sh: sysctl -w vm.max_map_count=262144
sudo chmod +x /var/lib/boot2docker/bootlocal.sh
exit
```

I have not tested this myself. If both work,  then we should add instructions in the docs.

**Comment by verbeeksteven** [comment]
I also ran into another issue

There is insufficient memory for the Java Runtime Environment to continue.

Is there a way to set the heap size? `ES_JAVA_OPTS="-Xms512m -Xmx512m"` ?

**Comment by lmakarov** [comment]
Here's a docker-compose definition from the official [elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html):

```
version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
```

The following pieces must be important:

```
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
```

I'm going to add these to the elasticsearch service definition in Docksal.
