### ISSUE TITLE
db create error

### ISSUE THREAD

**Issue by shelane** [docksal/docksal#753]
**Description**
I've tried in two different projects with similar results. There is a failure to create a database using `fin db create` command both where the database already existed and where it did not.

**Steps to reproduce the issue:**

1. run: `fin db create newdbname`

**Describe the results you received:**

/usr/local/bin/fin: line 4650: newdbname: command not found
Warning: Using a password on the command line interface can be insecure.
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci' at line 1
 ERROR:  Database 'newdbname' creation failed

**Describe the results you expected:**

Expected the database to be created as it was with Docksal 1.9.1

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```

---------------------
COMPOSE_PROJECT_NAME_SAFE: drupal
COMPOSE_FILE:
/Users/french8/.docksal/stacks/volumes-unison.yml
/Users/french8/.docksal/stacks/stack-default.yml
/Users/french8/Sites/docksal/drupal/.docksal/docksal.yml
ENV_FILE:
/Users/french8/Sites/docksal/drupal/.docksal/docksal.env
/Users/french8/Sites/docksal/drupal/.docksal/docksal-local.env

PROJECT_ROOT: /Users/french8/Sites/docksal/drupal
DOCROOT: docroot
VIRTUAL_HOST: drupal.docksal
VIRTUAL_HOST_ALIASES: *.drupal.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32773

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '49799'
      SECRET_ACAPI_EMAIL: frenc*****l.gov
      SECRET_ACAPI_KEY: Wr+Ss*****K0qH0
      SECRET_BLACKFIRE_CLIENT_ID: null
      SECRET_BLACKFIRE_CLIENT_TOKEN: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SOURCE_ALIAS: '@drupal.dev'
      VIRTUAL_HOST: drupal.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.4-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  mail:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: mail.drupal.docksal,mail.drupal.docksal.*
      io.docksal.virtual-port: '8025'
    volumes:
    - project_root:/var/www:ro,nocopy
  unison:
    environment:
      SYNC_DESTINATION: /destination
      SYNC_MAX_INOTIFY_WATCHES: '524288'
      SYNC_NODELETE_SOURCE: '0'
      SYNC_PREFER: newer
      SYNC_VERBOSE: '1'
      UNISON_GID: '20'
      UNISON_GROUP: dialout
      UNISON_UID: '49799'
      UNISON_USER: docker
    image: docksal/unison
    privileged: true
    volumes:
    - project_root:/destination:rw
    - /Users/french8/Sites/docksal/drupal:/source:rw
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.project-root: /Users/french8/Sites/docksal/drupal
      io.docksal.virtual-host: drupal.docksal,*.drupal.docksal,drupal.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root: {}

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.13.6
Darwin ******** 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker for Mac

███  FIN
fin version: 1.67.2

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                    project root
drupal                Up 6 minutes        drupal.docksal,*.drupal.docksal,drupal.docksal.*      /Users/french8/Sites/docksal/drupal
drupal8               Up 21 minutes       drupal8.docksal,*.drupal8.docksal,drupal8.docksal.*   /Users/french8/Sites/docksal/drupal8

███  DOCKSAL: VIRTUAL HOSTS
http://*.drupal.docksal
http://*.drupal8.docksal
http://drupal.docksal.*
http://drupal.docksal
http://drupal8.docksal.*
http://drupal8.docksal
http://mail.drupal.docksal.*
http://mail.drupal.docksal
http://mail.drupal8.docksal.*
http://mail.drupal8.docksal
http://solr.drupal8.docksal.*
http://solr.drupal8.docksal
http://varnish.drupal8.docksal.*
http://varnish.drupal8.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
00065ecf275e        docksal/web:2.1-apache2.4      "httpd-foreground"       6 minutes ago       Up 6 minutes              80/tcp, 443/tcp                                          drupal_web_1
2940cee5ad4b        docksal/db:1.2-mysql-5.6       "/entrypoint.sh mysq…"   6 minutes ago       Up 6 minutes              0.0.0.0:32773->3306/tcp                                  drupal_db_1
f92792a32c40        docksal/cli:2.4-php7.1         "/opt/startup.sh sup…"   6 minutes ago       Up 6 minutes (healthy)    22/tcp, 3000/tcp, 9000/tcp                               drupal_cli_1
fbe6bb5f018b        mailhog/mailhog                "MailHog"                6 minutes ago       Up 6 minutes              1025/tcp, 8025/tcp                                       drupal_mail_1
a344ddb075e9        docksal/varnish:1.1-varnish5   "/opt/startup.sh"        21 minutes ago      Up 21 minutes             80/tcp, 6082/tcp                                         drupal8_varnish_1
233995c93924        docksal/solr:1.0-solr4         "/opt/solr/bin/solr …"   21 minutes ago      Up 21 minutes             8983/tcp                                                 drupal8_solr_1
e738187f5f7f        docksal/web:2.1-apache2.4      "httpd-foreground"       21 minutes ago      Up 21 minutes             80/tcp, 443/tcp                                          drupal8_web_1
c6424f06ecbd        docksal/db:1.2-mysql-5.6       "/entrypoint.sh mysq…"   21 minutes ago      Up 21 minutes             0.0.0.0:32772->3306/tcp                                  drupal8_db_1
df88307f32c8        docksal/cli:2.4-php7.1         "/opt/startup.sh sup…"   21 minutes ago      Up 21 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               drupal8_cli_1
73c3737a5a4b        mailhog/mailhog                "MailHog"                21 minutes ago      Up 21 minutes             1025/tcp, 8025/tcp                                       drupal8_mail_1
1d47ef841e6c        memcached:1.4-alpine           "docker-entrypoint.s…"   21 minutes ago      Up 21 minutes             11211/tcp                                                drupal8_memcached_1
62b44a0d7525        docksal/unison                 "bg-sync"                21 minutes ago      Up 21 minutes                                                                      drupal8_unison_1
e63fccdf7292        docksal/unison                 "bg-sync"                2 hours ago         Up 2 hours                                                                         drupal_unison_1
f794cd583b44        docksal/ssh-agent:1.0          "/run.sh ssh-agent"      2 hours ago         Up 2 hours                                                                         docksal-ssh-agent
8b0f2e5bd7b2        docksal/dns:1.0                "/opt/entrypoint.sh …"   2 hours ago         Up 2 hours                192.168.64.100:53->53/udp                                docksal-dns
56249b3ca040        docksal/vhost-proxy:1.3        "docker-entrypoint.s…"   2 hours ago         Up 2 hours                192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                 DRIVER              SCOPE
5957936669aa        _default             bridge              local
3fa19fd52fcd        badcamp_default      bridge              local
ef8141c46a1c        bridge               bridge              local
c0dcabd4f760        d8c_default          bridge              local
91e5377df4a6        d8composer_default   bridge              local
40ecce495155        devdocksal_default   bridge              local
ba48ae3ea160        drupal8_default      bridge              local
675e569c989e        host                 host                local
3a533f16b398        drupal8_default        bridge              local
93e2eb5de61b        drupal_default         bridge              local
b22c5cd8f579        none                 null                local

███  HDD Usage
Filesystem                                             Size   Used  Avail Capacity  iused               ifree %iused  Mounted on
/dev/disk3s1                                          466Gi  345Gi  119Gi    75%  3767599 9223372036851008208    0%   /
devfs                                                 234Ki  234Ki    0Bi   100%      808                   0  100%   /dev
/dev/disk3s4                                          466Gi  1.0Gi  119Gi     1%        1 9223372036854775806    0%   /private/var/vm
map -hosts                                              0Bi    0Bi    0Bi   100%        0                   0  100%   /net
map auto_home                                           0Bi    0Bi    0Bi   100%        0                   0  100%   /home
map -fstab                                              0Bi    0Bi    0Bi   100%        0                   0  100%   /Network/Servers
/dev/disk2s2                                          931Gi  874Gi   57Gi    94% 26978789          4267988490    
  ```

</details>
