### ISSUE TITLE
fin db cli doesn't work properly

### ISSUE THREAD

**Issue by ApacheEx** [docksal/docksal#759]
**Description**

`fin db cli` doesn't work properly for some queries.

**Steps to reproduce the issue:**

1. Run `fin db cli "select name from users where uid=1"`

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/1918108/43568680-ead7a8c2-963d-11e8-9bfd-80e0878d551f.png)

**Describe the results you expected:**

I expect to see name of user with id 1, but instead it opens mysql shell and nothing happened.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: ywv
COMPOSE_FILE:/Users/apacheex/.docksal/stacks/volumes-bind.yml/Users/apacheex/.docksal/stacks/stack-default.yml/Users/apacheex/WEB/ywv/.docksal/docksal.yml
ENV_FILE:
/Users/apacheex/WEB/ywv/.docksal/docksal.env
/Users/apacheex/WEB/ywv/.docksal/docksal-local.env

PROJECT_ROOT: /Users/apacheex/WEB/ywv
DOCROOT: docroot
VIRTUAL_HOST: ywv.docksal
VIRTUAL_HOST_ALIASES: *.ywv.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:33061

Docker Compose configuration
---------------------
services:
  adminer:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    image: adminer:4
    labels:
      io.docksal.virtual-host: pma.ywv.docksal
      io.docksal.virtual-port: '8082'
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '501'
      PHP_IDE_CONFIG: serverName=ywv.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_BLACKFIRE_CLIENT_ID: null
      SECRET_BLACKFIRE_CLIENT_TOKEN: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: ywv.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.4-php5.6
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
    - /Users/apacheex/WEB/ywv-app/public:/var/www/docroot/ywv-app/public:rw
    - /Users/apacheex/WEB/ywv-react/build:/var/www/docroot/ywv-react/build:rw
    - /Users/apacheex/WEB/ywv-sdk/build1:/var/www/docroot/ywv-sdk/build1:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 33061:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.5.9
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.project-root: /Users/apacheex/WEB/ywv
      io.docksal.virtual-host: ywv.docksal,*.ywv.docksal,ywv.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
    - /Users/apacheex/WEB/ywv-app/public:/var/www/docroot/ywv-app/public:rw
    - /Users/apacheex/WEB/ywv-react/build:/var/www/docroot/ywv-react/build:rw
    - /Users/apacheex/WEB/ywv-sdk/build1:/var/www/docroot/ywv-sdk/build1:rw
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/apacheex/WEB/ywv
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  ███  OS
Darwin Mac OS X 10.13.6
Darwin mb15.lutsk.internetdevels.com 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : /Users/apacheex/WEB
NFS EXPORTS:

# <ds-nfs docksal
/Users/apacheex/WEB 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.67.2

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:03 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.03.1-ce

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                       project root
ywv              Up About an hour    ywv.docksal,*.ywv.docksal,ywv.docksal.*   /Users/apacheex/WEB/ywv

███  DOCKSAL: VIRTUAL HOSTS
http://*.ywv.docksal
http://pma.ywv.docksal
http://ywv.docksal.*
http://ywv.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                       PORTS                                                    NAMES
f2499d4bdbb4        docksal/web:2.1-apache2.4   "httpd-foreground"       About an hour ago   Up About an hour             80/tcp, 443/tcp                                          ywv_web_1
805b90090608        docksal/cli:2.4-php5.6      "/opt/startup.sh sup…"   About an hour ago   Up About an hour (healthy)   22/tcp, 3000/tcp, 9000/tcp                               ywv_cli_1
9eebda79b6e5        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   About an hour ago   Up About an hour             0.0.0.0:33061->3306/tcp                                  ywv_db_1
06c81ed38bf1        memcached:1.5.9             "docker-entrypoint.s…"   About an hour ago   Up About an hour             11211/tcp                                                ywv_memcached_1
9c51689a0398        adminer:4                   "entrypoint.sh docke…"   About an hour ago   Up About an hour             8080/tcp                                                 ywv_adminer_1
0aec664ba443        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      2 hours ago         Up 2 hours                                                                            docksal-ssh-agent
0b22bbabfdaf        docksal/dns:1.0             "/opt/entrypoint.sh …"   2 hours ago         Up 2 hours                   192.168.64.100:53->53/udp                                docksal-dns
033db2d2323e        docksal/vhost-proxy:1.3     "docker-entrypoint.s…"   2 hours ago         Up 2 hours                   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
3ccebcd80ffe        _default            bridge              local
4988ba160730        bridge              bridge              local
f98c1ebc5ec0        d8_default          bridge              local
bb379aa982f3        host                host                local
71a567e07883        none                null                local
6129f0569709        ywv_default      bridge              local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.2
5.2.16r123759

███  DOCKSAL MOUNTS
192.168.64.1:/Users/apacheex/WEB on /Users/apacheex/WEB type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/apacheex/WEB/ywv on /mnt/sda1/var/lib/docker/volumes/ywv_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.3G     15.5G     28.4G  35% /mnt/sda1
  ```

</details>
