### ISSUE TITLE
Docker error response when trying to create a new project

### ISSUE THREAD

**Issue by martinaelena** [docksal/docksal#771]
**Description**

when I run fin project create I get an error:

Cloning repository...
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist.
See 'docker run --help'.

I've tried most things. restarting vm. even setting up a new vm. still get the same error.

**Steps to reproduce the issue:**
mac os 10.12.6 ---- virtual box
folder:  /Users/teneramirez/docksal (has all my projects)
1. fin project create: 
2. enter your choice: 1. 
3. do you wish to proceed: y

**Describe the results you received:**
Cloning repository...
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist.
See 'docker run --help'.

**Describe the results you expected:**

expected it to create a drupal project successfully

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>
**this first config is from a working project**

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: bflaw
COMPOSE_FILE:
/Users/teneramirez/.docksal/stacks/volumes-bind.yml
/Users/teneramirez/.docksal/stacks/stack-default.yml
/Users/teneramirez/docksal/bflaw/.docksal/docksal.yml
ENV_FILE:
/Users/teneramirez/docksal/bflaw/.docksal/docksal.env

PROJECT_ROOT: /Users/teneramirez/docksal/bflaw
DOCROOT: docroot
VIRTUAL_HOST: bflaw.docksal
VIRTUAL_HOST_ALIASES: *.bflaw.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '501'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_BLACKFIRE_CLIENT_ID: null
      SECRET_BLACKFIRE_CLIENT_TOKEN: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: bflaw.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.4-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.project-root: /Users/teneramirez/docksal/bflaw
      io.docksal.virtual-host: bflaw.docksal,*.bflaw.docksal,bflaw.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/teneramirez/docksal/bflaw
      o: bind
      type: none

---------------------
```

**this config is from the non working folder**

```
martina:kctg teneramirez$ fin config
---------------------
COMPOSE_PROJECT_NAME_SAFE: kctg
COMPOSE_FILE:
/Users/teneramirez/.docksal/stacks/volumes-bind.yml
/Users/teneramirez/.docksal/stacks/stack-default.yml
/Users/teneramirez/docksal/kctg/.docksal/docksal.yml
ENV_FILE:
/Users/teneramirez/docksal/kctg/.docksal/docksal.env

PROJECT_ROOT: /Users/teneramirez/docksal/kctg
DOCROOT: docroot
VIRTUAL_HOST: kctg.docksal
VIRTUAL_HOST_ALIASES: *.kctg.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '501'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_BLACKFIRE_CLIENT_ID: null
      SECRET_BLACKFIRE_CLIENT_TOKEN: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: kctg.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.4-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.project-root: /Users/teneramirez/docksal/kctg
      io.docksal.virtual-host: kctg.docksal,*.kctg.docksal,kctg.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/teneramirez/docksal/kctg
      o: bind
      type: none

---------------------
```
</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

```
███  OS
Darwin Mac OS X 10.12.6
Darwin martina.home 16.7.0 Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : /Users/teneramirez/docksal
NFS EXPORTS:
# VAGRANT-BEGIN: 501 0ddadf4b-41e1-4f72-8e94-adf0936d86a3
"/Users/teneramirez/Documents/mmgy" 192.168.56.101 -alldirs -mapall=501:20
# VAGRANT-END: 501 0ddadf4b-41e1-4f72-8e94-adf0936d86a3
# VAGRANT-BEGIN: 501 d0c25c58-7314-46f1-a36a-d02090a0cce4
#"/Users/teneramirez/Documents/sites" 192.168.56.101 -alldirs -mapall=501:20
# VAGRANT-END: 501 d0c25c58-7314-46f1-a36a-d02090a0cce4
# VAGRANT-BEGIN: 501 01e64291-b437-4b69-91d9-98778c332ebd
#"/Users/teneramirez/Documents/mesites" 192.168.56.101 -alldirs -mapall=501:20
# VAGRANT-END: 501 01e64291-b437-4b69-91d9-98778c332ebd
# <ds-nfs docksal
/Users/teneramirez/docksal 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.69.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:03 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.03.1-ce
me        -        virtualbox   Stopped                                       Unknown

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                    project root
bflaw               Up 28 hours         bflaw.docksal,*.bflaw.docksal,bflaw.docksal.*   /Users/teneramirez/docksal/bflaw
msb                 Up 23 hours         msb.docksal,*.msb.docksal,msb.docksal.*         /Users/teneramirez/docksal/msb
ops                 Up 25 hours         ops.docksal,*.ops.docksal,ops.docksal.*         /Users/teneramirez/docksal/ops

███  DOCKSAL: VIRTUAL HOSTS
http://*.bflaw.docksal
http://*.msb.docksal
http://*.ops.docksal
http://bflaw.docksal.*
http://bflaw.docksal
http://msb.docksal.*
http://msb.docksal
http://ops.docksal.*
http://ops.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                  PORTS                                                    NAMES
8008df2399a8        docksal/web:2.1-apache2.4   "httpd-foreground"       28 hours ago        Up 28 hours             80/tcp, 443/tcp                                          bflaw_web_1
dbd01ba43a87        docksal/cli:2.4-php7.1      "/opt/startup.sh sup…"   28 hours ago        Up 28 hours (healthy)   22/tcp, 3000/tcp, 9000/tcp                               bflaw_cli_1
0f1328f0e1b0        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   28 hours ago        Up 28 hours             0.0.0.0:32768->3306/tcp                                  bflaw_db_1
4a50cdae0d5e        docksal/web:2.1-apache2.4   "httpd-foreground"       29 hours ago        Up 23 hours             80/tcp, 443/tcp                                          msb_web_1
17f3555cbbd6        docksal/cli:2.4-php7.1      "/opt/startup.sh sup…"   29 hours ago        Up 23 hours (healthy)   22/tcp, 3000/tcp, 9000/tcp                               msb_cli_1
9d2f552acd81        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   29 hours ago        Up 23 hours             0.0.0.0:32770->3306/tcp                                  msb_db_1
d1371acb366c        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      29 hours ago        Up 28 hours                                                                      docksal-ssh-agent
88c061e74ef8        docksal/dns:1.0             "/opt/entrypoint.sh …"   29 hours ago        Up 28 hours             192.168.64.100:53->53/udp                                docksal-dns
84c991193e49        docksal/vhost-proxy:1.3     "docker-entrypoint.s…"   29 hours ago        Up 28 hours             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
0e8c191a743f        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   2 days ago          Up 25 hours             0.0.0.0:32769->3306/tcp                                  ops_db_1
a253e02b20fd        docksal/web:2.1-apache2.4   "httpd-foreground"       2 days ago          Up 25 hours             80/tcp, 443/tcp                                          ops_web_1
b0a922bec14d        docksal/cli:2.4-php7.1      "/opt/startup.sh sup…"   2 days ago          Up 25 hours (healthy)   22/tcp, 3000/tcp, 9000/tcp                               ops_cli_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
656c8071c3f8        _default            bridge              local
98e0404723f7        bflaw_default       bridge              local
9c8185eb4af4        bridge              bridge              local
cd466becbbc9        host                host                local
4bc156715948        kc_default          bridge              local
e34ade02d572        kctg_default        bridge              local
9cc6c7f6f920        maloney_default     bridge              local
807417f11e8f        me_default          bridge              local
322b6aa03b5e        msb_default         bridge              local
bfbe0ecb1d1b        none                null                local
50e9c1660a06        ops_default         bridge              local
f57d2226a2bc        tester_default      bridge              local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.2
5.2.2r119230

███  DOCKSAL MOUNTS
192.168.64.1:/Users/teneramirez/docksal on /Users/teneramirez/docksal type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/teneramirez/docksal/bflaw on /mnt/sda1/var/lib/docker/volumes/bflaw_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/teneramirez/docksal/ops on /mnt/sda1/var/lib/docker/volumes/ops_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/teneramirez/docksal/msb on /mnt/sda1/var/lib/docker/volumes/msb_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G      4.9G     38.8G  11% /mnt/sda1
```

</details>
