### ISSUE TITLE
MySQL locking on simple insert queries

### ISSUE THREAD

**Issue by drubage** [docksal/docksal#775]
We've recently noticed an issue with one of our Drupal 8 sites where MySQL seems to be locking up all the time and queries will not run properly.

The site will completely freeze and eventually time out with MySQL lock errors.

**Steps to reproduce the issue:**

1. Install a Drupal 8 site with default stack.
2. Run it for a while.
3. See that eventually insert queries get stuck locked.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: golfzing-d8
COMPOSE_FILE:
/Users/drewmichael/.docksal/stacks/volumes-bind.yml
/Users/drewmichael/.docksal/stacks/stack-default.yml
/Users/drewmichael/projects/golfzing-d8/.docksal/docksal.yml
ENV_FILE:
/Users/drewmichael/projects/golfzing-d8/.docksal/docksal.env

PROJECT_ROOT: /Users/drewmichael/projects/golfzing-d8
DOCROOT: drupal/web
VIRTUAL_HOST: golfzing-d8.docksal
VIRTUAL_HOST_ALIASES: *.golfzing-d8.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32780

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: drupal/web
      HOST_GID: '20'
      HOST_UID: '502'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_BLACKFIRE_CLIENT_ID: null
      SECRET_BLACKFIRE_CLIENT_TOKEN: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: golfzing-d8.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.4-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.golfzing-d8.docksal
    user: root
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/drupal/web
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.project-root: /Users/drewmichael/projects/golfzing-d8
      io.docksal.virtual-host: golfzing-d8.docksal,*.golfzing-d8.docksal,golfzing-d8.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/drewmichael/projects/golfzing-d8
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.10.5
Darwin Drews-MacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : 
NFS EXPORTS:

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.69.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:03 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.03.1-ce   

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                                      project root
golfzing-d8         Up 6 minutes        golfzing-d8.docksal,*.golfzing-d8.docksal,golfzing-d8.docksal.*   /Users/drewmichael/projects/golfzing-d8
golfzing            Up About an hour    golfzing.docksal,*.golfzing.docksal,golfzing.docksal.*            /Users/drewmichael/projects/golfzing

███  DOCKSAL: VIRTUAL HOSTS
http://*.golfzing-d8.docksal
http://*.golfzing.docksal
http://golfzing-d8.docksal.*
http://golfzing-d8.docksal
http://golfzing.docksal.*
http://golfzing.docksal
http://webmail.golfzing-d8.docksal
http://webmail.golfzing.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                       PORTS                                                    NAMES
0fe181b7ee9b        docksal/web:2.1-apache2.4    "httpd-foreground"       6 minutes ago       Up 6 minutes                 80/tcp, 443/tcp                                          golfzing-d8_web_1
257a2aeaf158        docksal/cli:2.4-php7.1       "/opt/startup.sh sup…"   6 minutes ago       Up 6 minutes (healthy)       22/tcp, 3000/tcp, 9000/tcp                               golfzing-d8_cli_1
43e1787dc2e8        docksal/db:1.2-mysql-5.6     "/entrypoint.sh mysq…"   6 minutes ago       Up 6 minutes                 0.0.0.0:32780->3306/tcp                                  golfzing-d8_db_1
c3e5cc40a5e0        memcached:1.4-alpine         "docker-entrypoint.s…"   6 minutes ago       Up 6 minutes                 11211/tcp                                                golfzing-d8_memcached_1
999fc8aa04ac        mailhog/mailhog              "MailHog"                6 minutes ago       Up 6 minutes                 80/tcp, 1025/tcp, 8025/tcp                               golfzing-d8_mail_1
6b203868995a        docksal/web:2.1-apache2.2    "httpd-foreground"       2 hours ago         Up About an hour             80/tcp, 443/tcp                                          golfzing_web_1
b2618f0bd10f        docksal/cli:1.3-php5         "/opt/startup.sh sup…"   2 hours ago         Up About an hour (healthy)   22/tcp, 9000/tcp                                         golfzing_cli_1
e6d00c7c2df3        docksal/db:1.1-mysql-5.5     "/entrypoint.sh mysq…"   2 hours ago         Up About an hour             0.0.0.0:32772->3306/tcp                                  golfzing_db_1
d71c80c68f16        docksal/ssh-agent:1.0        "/run.sh ssh-agent"      2 hours ago         Up 2 hours                                                                            docksal-ssh-agent
dd80f8a5f560        docksal/dns:1.0              "/opt/entrypoint.sh …"   2 hours ago         Up 2 hours                   192.168.64.100:53->53/udp                                docksal-dns
deb70ea55a70        docksal/vhost-proxy:1.3      "docker-entrypoint.s…"   2 hours ago         Up 2 hours                   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
ac3f9ec33621        selenium/standalone-chrome   "/opt/bin/entry_poin…"   2 months ago        Up About an hour             4444/tcp                                                 golfzing_browser_1
e68386644d25        mailhog/mailhog              "MailHog"                2 months ago        Up About an hour             80/tcp, 1025/tcp, 8025/tcp                               golfzing_mail_1
b5e4283de7a0        memcached                    "docker-entrypoint.s…"   2 months ago        Up About an hour             11211/tcp                                                golfzing_memcached_1
394173861a47        backstopjs/backstopjs        "top -b"                 2 months ago        Up About an hour                                                                      golfzing_backstop_1
c8c25b5a7fd9        blackfire/blackfire          "blackfire-agent"        2 months ago        Up About an hour             8707/tcp                                                 golfzing_blackfire_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                            DRIVER              SCOPE
273fdb600388        _default                        bridge              local
f2b38f971188        agc-leads_default               bridge              local
e27855ccd966        bridge                          bridge              local
c5c128028e9b        budandbreakfast_default         bridge              local
fdbc27a28551        cemcosteel_default              bridge              local
68e5006d6041        cropking-2_default              bridge              local
b6adc3378b98        cropking-final_default          bridge              local
431feb6c7ce6        cropking_default                bridge              local
63e0bd1d0335        dentacard_default               bridge              local
af2f0779e79b        dfwplasticsinc_default          bridge              local
54523da59c6d        docksal-7_default               bridge              local
71adc25b189b        docksal-8_default               bridge              local
2fbc66e0182e        es2_default                     bridge              local
f3e4c504510a        esciencelabs_default            bridge              local
06834c4ae7a1        fruition-net_default            bridge              local
486cbd245783        fruition-sem-2_default          bridge              local
6256cfb11c7a        golfzing-d8_default             bridge              local
7087949df1ed        golfzing_default                bridge              local
579536d8c3f5        gzcentral_default               bridge              local
b41eb0dab52c        host                            host                local
ae0660186526        jira-restore_default            bridge              local
70bdae170fef        lai_default                     bridge              local
8ce2e15ae01b        nathab-blog_default             bridge              local
31b6606b8789        national_default                bridge              local
f281bdb7ebca        neha_default                    bridge              local
31b03246d398        networkfinancialprint_default   bridge              local
0267c50942a6        none                            null                local
d1ba9912cc11        the-monroe-institute_default    bridge              local
a1db52fcb36e        wordpress-template_default      bridge              local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.2
5.2.2r119230

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/drewmichael/projects/golfzing on /mnt/sda1/var/lib/docker/volumes/golfzing_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/drewmichael/projects/golfzing-d8 on /mnt/sda1/var/lib/docker/volumes/golfzing-d8_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1               140.0G     69.5G     63.2G  52% /mnt/sda1
  ```

</details>
