### ISSUE TITLE
How to have Docksal share the host's git config?

### ISSUE THREAD

**Issue by mikecrittenden** [docksal/docksal#776]
I'd like Docksal to share the git config of the host, so that I can git commit from within the cli container (for scripting, etc.) without getting this:

```
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
```

**Comment by lmakarov** [comment]
We can add two new env variables in `docksal/cli` and pass them from the host:

- `GIT_USER_EMAIL`
- `GIT_USER_NAME`

They would be set in `$HOME/.docksal/docksal.env` and thus shared globally will all Docksal projects.
Additionally, we can read these when installing Docksal and set them automatically, so this process is transparent to the user.

**Comment by lmakarov** [comment]
@mikecrittenden for now, you can configure these at the repo level, which will be visible to git inside cli:

```
git config user.email "you@example.com"
git config user.name "Your Name"
```

**Comment by mikecrittenden** [comment]
Fantastic, thanks a ton for the quick workaround and for the fixes pushed less than an hour from my initial report!

**Comment by frederickjh** [comment]
You can also easily do this in the Docksal project's `docksal-local.yml with:

```yaml
services:
    volumes:
      - ${HOME}/.gitconfig:/home/docker/.gitconfig
      - ${HOME}/.gitignore_global:/home/docker/.gitignore_global
```
I have been using this for a while. The last line is for those that do not like to polute their project files but like to have a global git ignore file to keep OS and editor temporary files and such from ending up in git repos.

I run Docker on a server and ssh into it. I am using ssh agent forwarding and also need to have the public keys in the containers for it to find the correct private key in the ssh agent. This can be done with:

```yaml
services:
  cli:
    environment:
      - SSH_AUTH_SOCK=/tmp/agent.sock   # SSH Agent Forwarding
    volumes:
      - ${SSH_AUTH_SOCK}:/tmp/agent.sock  # SSH Agent Forwarding
      - ${HOME}/.ssh/config:/home/docker/.ssh/config
      - ${HOME}/.ssh/id_rsa-bitbucket.pub:/home/docker/.ssh/id_rsa-bitbucket.pub
      - ${HOME}/.ssh/id_rsa-github.pub:/home/docker/.ssh/id_rsa-github.pub
```
In the example above have added my github and bitbucket public keys added to the container, so I can use my private keys from the ssh agent to access those accounts.
