### ISSUE TITLE
Some kind of DNS Issue

### ISSUE THREAD

**Issue by croane** [docksal/docksal#788]
So we are trying to get [selenoid](https://github.com/aerokube/selenoid) (similar to selenium hub). We are accessing selenoid with nightwatchjs. We are close, but we are having some issues. I got something to work with adding this to our docksal-local.yml file:

```
services:
  selenoid:
    hostname: selenoid
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "${PROJECT_ROOT}:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PROJECT_ROOT}/video:/opt/selenoid/video"
    labels:
      - io.docksal.virtual-host=selenoid.${VIRTUAL_HOST}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
  selenoid-ui:
    hostname: selenoid-ui
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid.${VIRTUAL_HOST}:4444"]
    labels:
      - io.docksal.virtual-host=selenoid-ui.${VIRTUAL_HOST}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
  selenoid-chrome:
    image: selenoid/chrome:65.0
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
  selenoid-firefox:
    image: selenoid/firefox:58.0
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
```

This "works" but I have to run fin share on the local project and use the ngrok url to access the local docksal site in selenoid. I tried using the urls "http://web" and the docksal url and neither of those worked. I also spent a lot of time testing removing the `network_mode: bridge` option so it is on the same network as the other containers, but then I can't seem to get access to the `selenoid` container when I try to run our Nightwatch.js tests from the cli container.

Any ideas in how I can update this config to bet able to do one of the following?

1. Be able to access the dockal local site without using ngrok when using network: bridge mode.
2. Be able to add these containers to the main network and get access to the `selenoid` container. I tried setting the host to `selenoid` and `selenoid.${VIRTUAL_HOST}`, but it doesn't seem to work. However, the host entry `selenoid` works when I have the network:bridge option set....I just can't get to the local docksal site.

My knowledge with docker is fairly limited. Any help would be appreciated. Thanks! :)
