### ISSUE TITLE
Acquia/BLT Project - Running behat tests 

### ISSUE THREAD

**Issue by justinlevi** [docksal/docksal#791]
Looking for some advice running behat tests with an Acquia BLT project. 

Here is my `tests/behat/local.yml` file:

```
# To generate a local.yml file using this the example template, execute:
# `blt tests:behat:init:config` from the project root.
imports:
  - behat.yml

local:
  suites:
    default:
      paths:
        # Set features to repo root so that .feature files belonging to contrib
        # modules, themes, and profiles can be discovered.
        features: /var/www/tests
      contexts:
        - Drupal\FeatureContext:
          parameters:
            environment:
              # absolute path to local directory to store screenshots - do not include trailing slash
              screenshot_dir: /var/www/reports
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\ConfigContext
  extensions:
    Behat\MinkExtension:
      browser_name: chrome
      javascript_session: selenium2
      # configure the base url for your site
      base_url: http://web
      # set default command for "Show last response" step.
      show_cmd: "open %s"
      # use the following lines to disable SSL authentication for goutte.
      # goutte:
      #   guzzle_parameters:
      #     redirect.disable: true
      #     ssl.certificate_authority: system
      #     curl.options:
      #       CURLOPT_SSL_VERIFYPEER: false
      #       CURLOPT_SSL_VERIFYHOST: false
      #       CURLOPT_CERTINFO: false
      #       CURLOPT_TIMEOUT: 120
      selenium2:
        wd_host: http://127.0.0.1:4444/wd/hub
        browser: chrome
      sessions:
        default:
          chrome:
            api_url: "http://localhost:9222"
    Drupal\DrupalExtension:
      drupal:
        # This must be an absolute path.
        drupal_root: /var/www/docroot
      drush:
        alias: '@self'

```

Here's my `behat.yml` file:

```
default:
  suites:
    default:
      paths:
        - %paths.base%/features
  extensions:
    Behat\MinkExtension:
      default_session: goutte
      browser_name: chrome
      javascript_session: default
      goutte: ~
      files_path: "%paths.base%/media"
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: "drupal"
    jarnaiz\JUnitFormatter\JUnitFormatterExtension:
        filename: report.xml
        outputDir: %paths.base%/build/tests
    Bex\Behat\ScreenshotExtension:
      screenshot_taking_mode: failed_steps
      image_drivers:
        local:
          screenshot_directory: /tmp

```

If I run this via: 

$ `fin behat -p local --config /var/www/tests/behat/local.yml -dl`

I see the following error: 

`Unrecognized option "chrome" under "testwork.mink.sessions.default" `

??? - where is testwork.mink coming from? that's not defined in my local.yml anywhere. 

If I go ahead and remove the following lines from my local.yml file: 

```
sessions:
        default:
          chrome:
            api_url: "http://localhost:9222"
```

I then see this error: 

```
SQLSTATE[HY000] [1130] Host '172.22.0.3' is not allowed to connect to this MySQL server  

```

Any thoughts on how I can minimally modify the default local.yml file to get my behat tests up and running with an Acquia BLT project? 

References: 
https://github.com/docksal/behat

https://docs.docksal.io/en/develop/tools/behat/

I've added the following to my docksal.yml file to try and get the selenium container up and running too

```
# Browser
browser:
  hostname: browser
  image: selenium/standalone-chrome
  dns:
    - ${DOCKSAL_DNS1}
    - ${DOCKSAL_DNS2}
```

After getting this far, I remembered working on this previously for another project and found the below `behat.docksal.yml` file: 

```
# Default profile.
# Common settings for all profiles
default:
  suites:
    default:
      contexts:
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\FeatureContext
  extensions:
    Behat\MinkExtension:
      base_url: http://web
      browser_name: chrome
      goutte: ~
      selenium2:
        wd_host: http://browser:4444/wd/hub
        capabilities: { "browser": "chrome", "version": "*" }
      # Use goutte (basic PHP browser, super fast) as the default driver.
      default_session: goutte
      # For real browser testing and tests requiring JS use selenium2 driver.
      # Tag features/scenarious with @javascript to use the selenium2 driver.
      javascript_session: selenium2
    Drupal\DrupalExtension:
      blackbox: ~
      drush:
        # Site docroot inside Docksal.
        root: /var/www/docroot
        alias: '@self'
      drupal:
        # Site docroot inside Docksal.
        drupal_root: /var/www/docroot
      # API driver [drupal|drush]
      api_driver: "drupal"
      # Map template regions.
      region_map:
        header: "#header"
        content: "#content"
        footer: "#footer"
      # Map selectors.
      selectors:
        message_selector: '#messages'
        error_message_selector: '#messages .messages.error'
        success_message_selector: '#messages .messages.status'

```

I try to run this via: 

$ `fin behat  --config /var/www/tests/behat/behat.docksal.yml -dl`

Unfortunately, I'm still seeing the same MYSQL error as above:

` SQLSTATE[HY000] [1130] Host '172.22.0.3' is not allowed to connect to this MySQL server `

**Comment by justinlevi** [comment]
I'm pretty green when it comes to docker so I'm just shooting in the dark here, but wonder if this is related? 

https://www.jeffgeerling.com/blog/2017/how-fix-host-1721801-not-allowed-connect-mysql-docker

**Comment by justinlevi** [comment]
LOL - well, after banging my head on the wall for a bit, I realized I had this working previously. The following setup works for me: 

`local.yml`

```
imports:
  - behat.docksal.yml

local:
  suites:
    default:
      paths:
        # Set features to repo root so that .feature files belonging to contrib
        # modules, themes, and profiles can be discovered.
        features: /var/www/tests/behat/features
      contexts:
        - Drupal\FeatureContext:
          parameters:
            environment:
              # absolute path to local directory to store screenshots - do not include trailing slash
              screenshot_dir: /var/www/reports
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\ConfigContext
  extensions:
    DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
    Behat\MinkExtension:
      browser_name: chrome
      javascript_session: default
      # configure the base url for your site
      base_url: http://web
      # set default command for "Show last response" step.
      show_cmd: "open %s"
      # use the following lines to disable SSL authentication for goutte.
      # goutte:
      #   guzzle_parameters:
      #     redirect.disable: true
      #     ssl.certificate_authority: system
      #     curl.options:
      #       CURLOPT_SSL_VERIFYPEER: false
      #       CURLOPT_SSL_VERIFYHOST: false
      #       CURLOPT_CERTINFO: false
      #       CURLOPT_TIMEOUT: 120
      selenium2:
        wd_host: http://browser:4444/wd/hub
        browser: chrome
      sessions:
        default:
          chrome:
            api_url: "http://localhost:9222"
    Drupal\DrupalExtension:
      drupal:
        # This must be an absolute path.
        drupal_root: /var/www/docroot
      drush:
        root: /var/www/docroot
        alias: '@self'
```

`behat.docksal.yml`

```
# Default profile.
# Common settings for all profiles
default:
  suites:
    default:
      contexts:
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\FeatureContext
  extensions:
    Behat\MinkExtension:
      base_url: http://web
      browser_name: chrome
      goutte: ~
      selenium2:
        wd_host: http://browser:4444/wd/hub
        capabilities: { "browser": "chrome", "version": "*" }
      # Use goutte (basic PHP browser, super fast) as the default driver.
      default_session: goutte
      # For real browser testing and tests requiring JS use selenium2 driver.
      # Tag features/scenarious with @javascript to use the selenium2 driver.
      javascript_session: selenium2
    Drupal\DrupalExtension:
      blackbox: ~
      drush:
        # Site docroot inside Docksal.
        root: /var/www/docroot
        alias: '@self'
      drupal:
        # Site docroot inside Docksal.
        drupal_root: /var/www/docroot
      # API driver [drupal|drush]
      api_driver: "drupal"
      # Map template regions.
      region_map:
        header: "#header"
        content: "#content"
        footer: "#footer"
      # Map selectors.
      selectors:
        message_selector: '#messages'
        error_message_selector: '#messages .messages.error'
        success_message_selector: '#messages .messages.status'
```

Running the following command executes successfully. 
$ `fin behat --config=/var/www/tests/behat/local.yml`
