### ISSUE TITLE
Package drupal/coder is not installed.

### ISSUE THREAD

**Issue by artemdotsenko** [docksal/docksal#793]
Looks like drupal/coder is not installer out-of-box. Documentation says it's available: https://docksal.readthedocs.io/en/master/tools/phpcs/#using-php-code-sniffer

**Steps to reproduce the issue:**

1. Run `fin bash`
2. Run `composer global show drupal/coder | grep version`

**Received result:**
![image](https://user-images.githubusercontent.com/4688363/46302412-ab61d980-c5b1-11e8-9d88-f7ec7498447b.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/4688363/46302477-d77d5a80-c5b1-11e8-8c7d-ff2196f9f29c.png)

Fixed by running:
1. `fin bash`
2. `composer global require drupal/coder:8.2.*`

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: ac
COMPOSE_FILE:
/Users/artemdotsenko/.docksal/stacks/volumes-bind.yml
/Users/artemdotsenko/.docksal/stacks/stack-default.yml
/Users/artemdotsenko/Sites/cw/ac/.docksal/docksal.yml
/Users/artemdotsenko/Sites/cw/ac/.docksal/docksal-local.yml
ENV_FILE:
/Users/artemdotsenko/Sites/cw/ac/.docksal/docksal.env
/Users/artemdotsenko/Sites/cw/ac/.docksal/docksal-local.env

PROJECT_ROOT: /Users/artemdotsenko/Sites/cw/ac
DOCROOT: docroot
VIRTUAL_HOST: cw.docksal
VIRTUAL_HOST_ALIASES: *.cw.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:3317

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '20'
      HOST_UID: '501'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_BLACKFIRE_CLIENT_ID: null
      SECRET_BLACKFIRE_CLIENT_TOKEN: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SITE_DIRECTORY: null
      SOURCE_ALIAS: '@ymcacw.dev'
      VIRTUAL_HOST: cw.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.4-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 3317:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.project-root: /Users/artemdotsenko/Sites/cw/ac
      io.docksal.virtual-host: cw.docksal,*.cw.docksal,cw.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/artemdotsenko/Sites/cw/ac
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  ███  OS
Darwin Mac OS X 10.14
Darwin Artems-MacBook-Pro.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : 
NFS EXPORTS:

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.69.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:03 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.03.1-ce   

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                          project root
ac                  Up 12 minutes       cw.docksal,*.cw.docksal,cw.docksal.*                  /Users/artemdotsenko/Sites/cw/ac
pfizer-medinfo      Up About an hour    medinfo.docksal,*.medinfo.docksal,medinfo.docksal.*   /Users/artemdotsenko/Sites/medinfo/pfizer-medinfo

███  DOCKSAL: VIRTUAL HOSTS
http://*.cw.docksal
http://*.medinfo.docksal
http://cw.docksal.*
http://cw.docksal
http://medinfo.docksal.*
http://medinfo.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                       PORTS                                                    NAMES
5e8643296347        docksal/web:2.1-apache2.4   "httpd-foreground"       12 minutes ago      Up 12 minutes                80/tcp, 443/tcp                                          ac_web_1
623694520ef0        docksal/cli:2.4-php7.1      "/opt/startup.sh sup…"   12 minutes ago      Up 12 minutes (healthy)      22/tcp, 3000/tcp, 9000/tcp                               ac_cli_1
c68da1dd9d7d        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   12 minutes ago      Up 12 minutes                0.0.0.0:3317->3306/tcp                                   ac_db_1
bd704ef39d88        docksal/web:2.1-apache2.4   "httpd-foreground"       About an hour ago   Up About an hour             80/tcp, 443/tcp                                          pfizer-medinfo_web_1
05624d3df0d6        docksal/cli:2.4-php7.1      "/opt/startup.sh sup…"   About an hour ago   Up About an hour (healthy)   3000/tcp, 9000/tcp, 0.0.0.0:2221->22/tcp                 pfizer-medinfo_cli_1
acab49e6d4f6        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   About an hour ago   Up About an hour             0.0.0.0:3307->3306/tcp                                   pfizer-medinfo_db_1
8cb304fff51f        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      About an hour ago   Up About an hour                                                                      docksal-ssh-agent
265088b43be9        docksal/dns:1.0             "/opt/entrypoint.sh …"   About an hour ago   Up About an hour             192.168.64.100:53->53/udp                                docksal-dns
71b524d7e971        docksal/vhost-proxy:1.3     "docker-entrypoint.s…"   About an hour ago   Up About an hour             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
8d491f162421        memcached                   "docker-entrypoint.s…"   About an hour ago   Up About an hour             11211/tcp                                                pfizer-medinfo_memcached_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                     DRIVER              SCOPE
af7b229bac26        _default                 bridge              local
1d915f36795d        ac_default               bridge              local
ab3ba1e308d9        bridge                   bridge              local
523d6e7937cc        d8_default               bridge              local
7a91da5e07c8        drupal_project_default   bridge              local
87f3164fdca1        host                     host                local
50ee8b71d5f1        none                     null                local
4cc7928a5f92        pfhworld_default         bridge              local
fee89ae08cf7        pfizer-ghsh-d8_default   bridge              local
ca312854359c        pfizer-medinfo_default   bridge              local
01abd0655c67        pfizermedinfo_default    bridge              local
32bd4159b8bc        pfmiforms2_default       bridge              local
def78e15bbc5        pfmiforms_default        bridge              local
651b941e93cc        ygd_default              bridge              local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.2
5.2.18r124319

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/artemdotsenko/Sites/medinfo/pfizer-medinfo on /mnt/sda1/var/lib/docker/volumes/pfizermedinfo_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/artemdotsenko/Sites/cw/ac on /mnt/sda1/var/lib/docker/volumes/ac_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.3G     19.8G     24.0G  45% /mnt/sda1
  ```

</details>
