### ISSUE TITLE
C9 IDE support interfering with virtual host routing

### ISSUE THREAD

**Issue by mike-potter** [docksal/docksal#797]
**Description**

When enabling IDE support ``IDE_ENABLED="1"`` our custom virtual host bindings for the cli container stop working.

We have a webpack-dev-server running within the cli container and have the following added to our ``docksal.yml`` file:
```
  cli:
    labels:
      # Set host and port of CLI container for Pattern Lab.
      - io.docksal.virtual-host=design.${VIRTUAL_HOST}
      - io.docksal.virtual-port=8080
    expose:
      - "8080"
```
This allows us to use "design.sitename.docksal" in the browser to connect to port 8080 within the cli container where webpack-dev-server is running.  This works great when IDE is disabled, but when IDE support is enabled, visiting "design.sitename.docksal" sends us to the normal "sitename.docksal" site (Drupal site in our case).

Seems like the cli-ide image must be doing something special with the network routing, maybe to allow ide.sitename.docksal to work?

Looks like the C9 IDE is at port 3000, so maybe it's not possible to reference two different servers in the containers with different ports?
