### ISSUE TITLE
Xdebug not working on Ubuntu 18 + Docker 18 CE

### ISSUE THREAD

**Issue by amjad-wp** [docksal/docksal#800]
**Description**

Xdebug not working with PHP Strom 2018.2.5

Problem/feature description... 

Clean box install with nothing install.

**Steps to reproduce the issue:**

1. fin start
2. Add breakpoint to index.php (of drupal 8 )
3. Start PHP Stroms debug listner.

**Describe the results you received:**

Nothing comes up

**Describe the results you expected:**

A dialog of incoming connection request should come up.
Or should see debug console with variables etc.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
COMPOSE_PROJECT_NAME_SAFE: limba
COMPOSE_FILE:
/home/amjad/.docksal/stacks/volumes-bind.yml
/home/amjad/.docksal/stacks/stack-default.yml
/var/www/limba/.docksal/docksal.yml
ENV_FILE:
/var/www/limba/.docksal/docksal.env

PROJECT_ROOT: /var/www/limba
DOCROOT: web
VIRTUAL_HOST: limba.docksal
VIRTUAL_HOST_ALIASES: *.limba.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32775

Docker Compose configuration
---------------------
services:
  adminer:
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: price
      ADMINER_PLUGINS: tables-filter tinymce
    hostname: adminer
    image: adminer
    labels:
      io.docksal.virtual-host: adminer.limba.docksal
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: web
      HOST_GID: '999'
      HOST_UID: '1000'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_BLACKFIRE_CLIENT_ID: null
      SECRET_BLACKFIRE_CLIENT_TOKEN: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: limba.docksal
      XDEBUG_CONFIG: remote_connect_back=1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.4-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.limba.docksal
    user: root
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/web
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.project-root: /var/www/limba
      io.docksal.virtual-host: limba.docksal,*.limba.docksal,limba.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /var/www/limba
      o: bind
      type: none

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Linux Ubuntu 18.04
Linux amjad-Aspire-TC-780 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST : 

███  FIN
fin version: 1.69.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:51 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:15 2018
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                    project root
limba               Up 10 minutes       limba.docksal,*.limba.docksal,limba.docksal.*   /var/www/limba

███  DOCKSAL: VIRTUAL HOSTS
http://*.limba.docksal
http://adminer.limba.docksal
http://limba.docksal.*
http://limba.docksal
http://webmail.limba.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
6a797559cfdb        docksal/web:2.1-apache2.4   "httpd-foreground"       10 minutes ago      Up 10 minutes             80/tcp, 443/tcp                                          limba_web_1
34add36666ae        docksal/cli:2.4-php7.1      "/opt/startup.sh sup…"   10 minutes ago      Up 10 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               limba_cli_1
4a347c483eb0        adminer                     "entrypoint.sh docke…"   3 hours ago         Up 10 minutes             8080/tcp                                                 limba_adminer_1
6bcf0558de16        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      4 hours ago         Up 4 hours                                                                         docksal-ssh-agent
ee4bb9faa0c8        docksal/dns:1.0             "/opt/entrypoint.sh …"   4 hours ago         Up 4 hours                192.168.64.100:53->53/udp                                docksal-dns
5ed172d9e559        docksal/vhost-proxy:1.3     "docker-entrypoint.s…"   4 hours ago         Up 4 hours                192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
809de736a4e3        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   2 days ago          Up 10 minutes             0.0.0.0:32775->3306/tcp                                  limba_db_1
b687c0d445ba        mailhog/mailhog             "MailHog"                3 days ago          Up 10 minutes             80/tcp, 1025/tcp, 8025/tcp                               limba_mail_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
b811e5d36261        _default            bridge              local
a7bd8fe53553        bridge              bridge              local
dffa610d47a1        host                host                local
17981c985b80        limba_default       bridge              local
7cd02b569798        none                null                local

███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G  2.6M  1.6G   1% /run
/dev/sda2       439G   68G  349G  17% /
tmpfs           7.9G  280M  7.6G   4% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/loop2       11M   11M     0 100% /snap/chromium-ffmpeg/5
/dev/loop1      3.8M  3.8M     0 100% /snap/gnome-system-monitor/57
/dev/loop0       35M   35M     0 100% /snap/gtk-common-themes/319
/dev/loop5      2.4M  2.4M     0 100% /snap/gnome-calculator/180
/dev/loop3      141M  141M     0 100% /snap/gnome-3-26-1604/70
/dev/loop7      161M  161M     0 100% /snap/mailspring/244
/dev/loop4      118M  118M     0 100% /snap/vscode/62
/dev/loop6      479M  479M     0 100% /snap/libreoffice/86
/dev/loop8       15M   15M     0 100% /snap/gnome-logs/37
/dev/loop9       87M   87M     0 100% /snap/core/4917
/dev/loop11     479M  479M     0 100% /snap/libreoffice/85
/dev/loop13     115M  115M     0 100% /snap/vscode/63
/dev/loop10     136M  136M     0 100% /snap/chromium/494
/dev/loop12      13M   13M     0 100% /snap/gnome-characters/124
/dev/loop14      43M   43M     0 100% /snap/gtk-common-themes/701
/dev/loop16     3.8M  3.8M     0 100% /snap/gnome-system-monitor/51
/dev/loop17     140M  140M     0 100% /snap/opera/11
/dev/loop15     118M  118M     0 100% /snap/vscode/59
/dev/loop18      17M   17M     0 100% /snap/communitheme/1273
/dev/loop19     142M  142M     0 100% /snap/slack/9
/dev/loop20      13M   13M     0 100% /snap/gnome-characters/103
/dev/loop21     5.0M  5.0M     0 100% /snap/canonical-livepatch/50
/dev/loop22     479M  479M     0 100% /snap/libreoffice/84
/dev/loop24      15M   15M     0 100% /snap/gnome-logs/43
/dev/loop23      15M   15M     0 100% /snap/gnome-logs/45
/dev/loop25      17M   17M     0 100% /snap/communitheme/1226
/dev/loop28     4.8M  4.8M     0 100% /snap/canonical-livepatch/49
/dev/loop26      88M   88M     0 100% /snap/core/5548
/dev/loop27     2.3M  2.3M     0 100% /snap/gnome-calculator/238
/dev/sda1       511M  4.7M  507M   1% /boot/efi
tmpfs           1.6G   16K  1.6G   1% /run/user/121
tmpfs           1.6G   64K  1.6G   1% /run/user/1000

  ```

</details>
