### ISSUE TITLE
AzureDevOps ssh - bash: npm: command not found

### ISSUE THREAD

**Issue by gconry18** [docksal/docksal#805]
**Description**

During deployment of a docksal site we need to ssh into and Ubuntu Server to download and build our application.

One of the build steps is `fin exec npm install --global npm@latest`

When I ssh into the Ubuntu Server using Git Bash the command works perfectly as expected.
When I use Azure DevOps to ssh into the server and run the script I get `bash: npm: command not found`

Both methods use the same user.

What could be causing the command to fail when run via Azure DevOps

**Steps to reproduce the issue:**

1. SSH into Ubuntu Server and Download docksal site onto it
2. Run `fin start`, then `fin exec npm install --global npm@latest`. This should work
3. Run `fin stop`
4. Setup an Azure DevOps build
5. Add SSH build task with inline script
6. Inline script should `cd` into correct directory and run `fin start`, then `fin exec npm install --global npm@latest`. This will fail on the latter step.

**Describe the results you received:**

`fin exec npm install --global npm@latest` fails when running in Azure DevOps ssh step

**Describe the results you expected:**

`fin exec npm install --global npm@latest` should work

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: related-rentals_build
COMPOSE_FILE:
/home/DevOps/.docksal/stacks/volumes-bind.yml
/home/DevOps/.docksal/stacks/stack-acquia.yml
/docksal/projects/related/related-rentals_build/.docksal/docksal.yml
/docksal/projects/related/related-rentals_build/.docksal/docksal-local.yml
ENV_FILE:
/docksal/projects/related/related-rentals_build/.docksal/docksal.env
/docksal/projects/related/related-rentals_build/.docksal/docksal-local.env

PROJECT_ROOT: /docksal/projects/related/related-rentals_build
DOCROOT: docroot
VIRTUAL_HOST: related-rentals-build.docksal
VIRTUAL_HOST_ALIASES: *.related-rentals-build.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      COMPOSER_CACHE_DIR: /cache
      DOCROOT: docroot
      HOST_GID: '1001'
      HOST_UID: '1001'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_BLACKFIRE_CLIENT_ID: null
      SECRET_BLACKFIRE_CLIENT_TOKEN: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: related-rentals-build.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.2-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - composer_cache:/cache:rw
    - db_backup:/db_backup:rw
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: solr
    image: docksal/solr:1.0-solr4
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: solr.related-rentals-build.docksal,solr.related-rentals-build.docksal.*
      io.docksal.virtual-port: '8983'
    volumes:
    - project_root:/var/www:ro,nocopy
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:1.1-varnish5
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: varnish.related-rentals-build.docksal,varnish.related-rentals-build.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.project-root: /docksal/projects/related/related-rentals_build
      io.docksal.virtual-host: related-rentals-build.docksal,*.related-rentals-build.docksal,related-rentals-build.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  composer_cache:
    external: true
    name: composer_cache
  db_backup:
    external: true
    name: db_backup
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /docksal/projects/related/related-rentals_build
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Linux Ubuntu 18.04
Linux GarethUbuntuServer 4.15.0-1025-azure #26-Ubuntu SMP Tue Sep 25 09:20:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST :

███  FIN
fin version: 1.69.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Wed Jun 20 21:43:51 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Wed Jun 20 21:42:00 2018
  OS/Arch:      linux/amd64
  Experimental: false
WARNING: No swap limit support

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
f77351ed8185        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      39 minutes ago      Up 39 minutes                                                                docksal-ssh-agent
0d73b108eae1        docksal/dns:1.0           "/opt/entrypoint.sh …"   39 minutes ago      Up 39 minutes       192.168.64.100:53->53/udp                                docksal-dns
e0cfc1db7990        docksal/vhost-proxy:1.3   "docker-entrypoint.s…"   39 minutes ago      Up 39 minutes       192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                              DRIVER              SCOPE
196f95cd3bd4        _default                          bridge              local
c4ac06cd7fdd        bridge                            bridge              local
de35c83009cf        host                              host                local
fb929fdfbde3        none                              null                local
97bc1ac277e2        related-acsf_dev_default          bridge              local
d2510c65bb71        related-acsf_release_default      bridge              local
ad2d0931fc78        related-rentals_build_default     bridge              local
fbbe64fe1ac4        related-rentals_dev_default       bridge              local
3b563158c928        related-rentals_release_default   bridge              local

███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           798M  936K  797M   1% /run
/dev/sda1        29G   11G   19G  36% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda15      105M  3.4M  102M   4% /boot/efi
/dev/sdb1        16G   45M   15G   1% /mnt
tmpfs           798M     0  798M   0% /run/user/1001
  ```

</details>
