### ISSUE TITLE
Docksal update 1.79.4 causing different DB container names

### ISSUE THREAD

**Issue by mike-potter** [docksal/docksal#848]
**Description**

After doing a `fin update` to get 1.79.4, when doing a `fin start` in a project, our DB container seems to have a different name.  Previously it was `projectname_db_1` and now it is `abe69dd6448e_projectname_db_1` (the "abe69dd6448e" is a different uuid for each project).

**Steps to reproduce the issue:**

1. `fin stop`
2. `fin update`
3. `fin start`

**Describe the results you received:**

DB containers have a UUID added to them.  This causes the `fin db dump filename` command to error with: `Error: No such container: projectname_db_1`

**Describe the results you expected:**

I expected containers to retain their proper names.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: projectname
COMPOSE_FILE:
/Users/michaelpotter/.docksal/stacks/overrides-osxfs.yml
/Users/michaelpotter/.docksal/stacks/volumes-bind.yml
/Users/michaelpotter/.docksal/stacks/stack-default.yml
/Users/michaelpotter/Projects/projectname/.docksal/docksal.yml
ENV_FILE:
/Users/michaelpotter/Projects/projectname/.docksal/docksal.env

PROJECT_ROOT: /Users/michaelpotter/Projects/projectname
DOCROOT: build/html
VIRTUAL_HOST: projectname.docksal
VIRTUAL_HOST_ALIASES: *.projectname.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32817

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCKER_ENV: local
      DOCROOT: build/html
      HOST_GID: '20'
      HOST_UID: '501'
      PHP_IDE_CONFIG: serverName=projectname.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: projectname.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.4-php7.2
    ports:
    - 3001:3001/tcp
    - 3050:3050/tcp
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /Users/michaelpotter/Projects/projectname:/var/www:rw,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: projectname_d8_drupal
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  mail:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: mail.projectname.docksal,mail.projectname.docksal.*
      io.docksal.virtual-port: '8025'
    volumes:
    - project_root:/var/www:ro,nocopy
  memcached:
    command:
    - -m
    - '256'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  solr:
    build:
      context: /Users/michaelpotter/Projects/projectname/env/solr/docker
    hostname: solr
    labels:
      io.docksal.virtual-host: solr.projectname.docksal
    ports:
    - 8983:8983/tcp
    volumes:
    - /Users/michaelpotter/Projects/projectname/env/solr/cores/sitesearch:/opt/solr/server/solr/sitesearch:rw
    - search-data:/var/lib/solr:rw
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/build/html
      DOCKER_ENV: local
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/michaelpotter/Projects/projectname
      io.docksal.virtual-host: projectname.docksal,*.projectname.docksal,projectname.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/michaelpotter/Projects/projectname
      o: bind
      type: none
  search-data: {}

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
 ███  OS
Darwin Mac OS X 10.14.1
Darwin Michaels-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker for Mac

███  FIN
fin version: 1.79.4

███  DOCKER COMPOSE
EXPECTED VERSION: 1.22.0
docker-compose version 1.22.0, build f46880f
docker-py version: 3.4.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.06.1-ce

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                    project root
projectname               Up 11 minutes       projectname.docksal,*.projectname.docksal,projectname.docksal.*   /Users/michaelpotter/Projects/projectname

███  DOCKSAL: VIRTUAL HOSTS
*.projectname.docksal
mail.projectname.docksal.*
mail.projectname.docksal
projectname.docksal.*
projectname.docksal
solr.projectname.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                                        NAMES
fa3d3d7b2893        docksal/web:2.1-apache2.4   "httpd-foreground"       4 days ago          Up 11 minutes             80/tcp, 443/tcp                                                              projectname_web_1
a11231f0c46a        docksal/cli:2.4-php7.2      "/opt/startup.sh sup…"   4 days ago          Up 11 minutes (healthy)   22/tcp, 0.0.0.0:3001->3001/tcp, 3000/tcp, 9000/tcp, 0.0.0.0:3050->3050/tcp   projectname_cli_1
961b4285cd28        memcached:1.4-alpine        "docker-entrypoint.s…"   4 days ago          Up 11 minutes             11211/tcp                                                                    projectname_memcached_1
fd2b85c9ead3        mailhog/mailhog             "MailHog"                4 days ago          Up 11 minutes             1025/tcp, 8025/tcp                                                           projectname_mail_1
f278f7d666a9        docksal/ssh-agent:1.2       "docker-entrypoint.s…"   4 days ago          Up 4 days (healthy)                                                                                    docksal-ssh-agent
f49615592d7d        docksal/dns:1.1             "docker-entrypoint.s…"   4 days ago          Up 4 days (healthy)       192.168.64.100:53->53/udp                                                    docksal-dns
7bc3f8f0f7a3        docksal/vhost-proxy:1.4     "docker-entrypoint.s…"   4 days ago          Up 4 days (healthy)       192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp                       docksal-vhost-proxy
abe69dd6448e        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   5 weeks ago         Up 11 minutes             0.0.0.0:32817->3306/tcp                                                      abe69dd6448e_projectname_db_1
ca3b55a9c586        projectname_solr                  "docker-entrypoint.s…"   3 months ago        Up 11 minutes             0.0.0.0:8983->8983/tcp                                                       projectname_solr_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
032ae12f78b0        _default            bridge              local
56c8e4015e03        bridge              bridge              local
046e164056ec        host                host                local
2f84910e460e        projectname_default       bridge              local
ebc10e967fd5        none                null                local

███  HDD Usage
Filesystem                                                                          Size   Used  Avail Capacity     iused               ifree %iused  Mounted on
/dev/disk1s1                                                                       932Gi  376Gi  548Gi    41%     6194157 9223372036848581650    0%   /
devfs                                                                              235Ki  235Ki    0Bi   100%         812                   0  100%   /dev
/dev/disk1s4                                                                       932Gi  7.0Gi  548Gi     2%           7 9223372036854775800    0%   /private/var/vm
map -hosts                                                                           0Bi    0Bi    0Bi   100%           0                   0  100%   /net
map auto_home                                                                        0Bi    0Bi    0Bi   100%           0                   0  100%   /home
  ```

</details>
