### ISSUE TITLE
"Error: No such container"

### ISSUE THREAD

**Issue by Matroskeen** [docksal/docksal#852]
**Description**

After updating to the latest version (1.79.4) I can't import database anymore and have the following erorr:

`Error: No such container: drupal8_db_1`

I noticed there are some differences in containers naming after the last update.
On 1.69.1 version we had the following pattern: [project_name]_[service_name]_[number].
Now we have [project_name]_[service_name]_[number]_[some_hash].

Maybe this is the reason.

**Steps to reproduce the issue:**

1. Install the latest docksal (1.79.4) on Mac OS Mojave or High Sierra.
2. Run any project with db service.
3. Try to execute the following commmand `fin db list` or `fin db import`.

**Describe the results you received:**

`Error: No such container: drupal8_db_1`

**Describe the results you expected:**

I expected to be happy and do not have such errors.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: drupal8
COMPOSE_FILE:
/Users/matroskeen/.docksal/stacks/volumes-bind.yml
/Users/matroskeen/.docksal/stacks/stack-default.yml
/Users/matroskeen/Projects/drupal8/.docksal/docksal.yml
ENV_FILE:
/Users/matroskeen/Projects/drupal8/.docksal/docksal.env

PROJECT_ROOT: /Users/matroskeen/Projects/drupal8
DOCROOT: codebase/web
VIRTUAL_HOST: drupal8.docksal
VIRTUAL_HOST_ALIASES: *.drupal8.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: codebase/web
      HOST_GID: '20'
      HOST_UID: '502'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: drupal8.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.5-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/codebase/web
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/matroskeen/Projects/drupal8
      io.docksal.virtual-host: drupal8.docksal,*.drupal8.docksal,drupal8.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/matroskeen/Projects/drupal8
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
 ███  OS
Darwin Mac OS X 10.14
Darwin Matroskeen.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH :
NFS EXPORTS:

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.79.4

███  DOCKER COMPOSE
EXPECTED VERSION: 1.22.0
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.06.1-ce

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKER MACHINE
EXPECTED VERSION: 0.15.0
docker-machine version 0.16.0, build 702c267f

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.06.1-ce

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                          project root
drupal8             Up 14 minutes       drupal8.docksal,*.drupal8.docksal,drupal8.docksal.*   /Users/matroskeen/Projects/drupal8

███  DOCKSAL: VIRTUAL HOSTS
*.drupal8.docksal
drupal8.docksal.*
drupal8.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
27194462668c        docksal/ssh-agent:1.2       "docker-entrypoint.s…"   18 minutes ago      Up 18 minutes (healthy)                                                            docksal-ssh-agent
e19fb0ba64d8        docksal/dns:1.1             "docker-entrypoint.s…"   18 minutes ago      Up 18 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
d93a1d438734        docksal/vhost-proxy:1.4     "docker-entrypoint.s…"   18 minutes ago      Up 18 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
e7798f256c5a        docksal/web:2.1-apache2.4   "httpd-foreground"       About an hour ago   Up 14 minutes             80/tcp, 443/tcp                                          drupal8_web_1_81ac190843f6
02c1e6794c5d        docksal/cli:2.5-php7.1      "/opt/startup.sh sup…"   About an hour ago   Up 14 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               drupal8_cli_1_a48207e06ab1
a886669657da        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   About an hour ago   Up 14 minutes             0.0.0.0:32768->3306/tcp                                  drupal8_db_1_bf3f788a3e35

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
1149d2484c78        _default            bridge              local
f578bc86891e        bridge              bridge              local
62ffaf69d632        drupal8_default     bridge              local
0ed65a5cdc2d        host                host                local
14cd5ad064f5        none                null                local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.20
5.2.22r126460

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/matroskeen/Projects/drupal8 on /mnt/sda1/var/lib/docker/volumes/drupal8_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G      4.3G     39.4G  10% /mnt/sda1
  ```

</details>
