### ISSUE TITLE
Error "bad substitution" after trying to add ssh key

### ISSUE THREAD

**Issue by botanic** [docksal/docksal#855]
**Description**

With latest fin 1.79.4 after trying to add ssh key to the agent using command
```fin ssh-key add key_name```
I get error
```/usr/local/bin/fin: line 3180: SECRET_SSH_KEY_${2^^}=${2}: bad substitution```

I am using built-in bash on Mac (Mojave)

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: panasonic-drupal-b2b
COMPOSE_FILE:
/Users/botanic/.docksal/stacks/volumes-bind.yml
/Users/botanic/.docksal/stacks/stack-default.yml
/Users/botanic/www/panasonic-drupal-b2b/.docksal/docksal.yml
/Users/botanic/www/panasonic-drupal-b2b/.docksal/docksal-local.yml
ENV_FILE:
/Users/botanic/www/panasonic-drupal-b2b/.docksal/docksal.env
/Users/botanic/www/panasonic-drupal-b2b/.docksal/docksal-local.env

PROJECT_ROOT: /Users/botanic/www/panasonic-drupal-b2b
DOCROOT: docroot
VIRTUAL_HOST: pna.docksal
VIRTUAL_HOST_ALIASES: *.pna.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  browser:
    hostname: browser
    image: selenium/standalone-chrome
    volumes:
    - /Users/botanic/www/panasonic-drupal-b2b:/var/www:rw
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      GIT_USER_EMAIL: vzdravkovic83@gmail.com
      GIT_USER_NAME: Vladimir
      HOST_GID: '20'
      HOST_UID: '501'
      PHP_IDE_CONFIG: serverName=pna.docksal
      PROJECT_ROOT: /var/www
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: pna.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.0-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 32768:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.0-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/botanic/www/panasonic-drupal-b2b
      io.docksal.virtual-host: pna.docksal,*.pna.docksal,pna.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/botanic/www/panasonic-drupal-b2b
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  ███  OS
Darwin Mac OS X 10.14
Darwin Vladimirs-MacBook-Pro.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : 
NFS EXPORTS:

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.79.4

███  DOCKER COMPOSE
EXPECTED VERSION: 1.22.0
docker-compose version 1.22.0, build f46880f
docker-py version: 3.4.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.06.1-ce

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKER MACHINE
EXPECTED VERSION: 0.15.0
docker-machine version 0.15.0, build b48dc28d

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.06.1-ce   

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                   PORTS                                                    NAMES
1043d0940d1d        docksal/ssh-agent:1.2     "docker-entrypoint.s…"   8 minutes ago       Up 8 minutes (healthy)                                                            docksal-ssh-agent
12303856384c        docksal/dns:1.1           "docker-entrypoint.s…"   8 minutes ago       Up 8 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
e0ddbbb509ce        docksal/vhost-proxy:1.4   "docker-entrypoint.s…"   8 minutes ago       Up 8 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
28d7430d3688        _default            bridge              local
b76f30d4f8ca        bridge              bridge              local
ca7bc41fd930        host                host                local
4612fbdae5ab        none                null                local
7d343c1e2ce7        pna_pbp_default     bridge              local
b2ca44ae680d        pnabr_default       bridge              local
0da0d65d8d43        pnaca_default       bridge              local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.20
5.2.22r126460

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G     32.9G     10.8G  75% /mnt/sda1
  ```

</details>
