### ISSUE TITLE
This site can’t be reached ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by maestro888** [docksal/docksal#870]
**Description**

I use Docksal on Ubuntu (16.04) Chromium (70.0.3538.110). When I open http://drupal8.docksal in the browser, the following error occurs:

ERR_CONNECTION_REFUSED

Service Apache was uninstalled

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: drupal8
COMPOSE_FILE:
/home/user/.docksal/stacks/volumes-bind.yml
/home/user/.docksal/stacks/stack-default.yml
/home/user/Projects/drupal8/.docksal/docksal.yml
ENV_FILE:
/home/user/Projects/drupal8/.docksal/docksal.env

PROJECT_ROOT: /home/user/Projects/drupal8
DOCROOT: docroot
VIRTUAL_HOST: drupal8.docksal
VIRTUAL_HOST_ALIASES: *.drupal8.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32771

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      GIT_USER_EMAIL: ''
      GIT_USER_NAME: ''
      HOST_GID: '1000'
      HOST_UID: '1000'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: drupal8.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.5-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /home/user/Projects/drupal8
      io.docksal.virtual-host: drupal8.docksal,*.drupal8.docksal,drupal8.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/user/Projects/drupal8
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
 ███  OS
Linux Ubuntu 16.04
Linux user-pc 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST : 

███  FIN
fin version: 1.80.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.1
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

███  DOCKER
EXPECTED VERSION: 18.06.1-ce

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
WARNING: No swap limit support

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                          project root
drupal8             Up 39 minutes       drupal8.docksal,*.drupal8.docksal,drupal8.docksal.*   /home/user/Projects/drupal8

███  DOCKSAL: VIRTUAL HOSTS
*.drupal8.docksal
drupal8.docksal.*
drupal8.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                         PORTS                                                    NAMES
991b82b47284        docksal/ssh-agent:1.2       "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)                                                              docksal-ssh-agent
ff644f7c731e        docksal/dns:1.1             "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)     192.168.64.100:53->53/udp                                docksal-dns
c34acfe87a79        docksal/vhost-proxy:1.4     "docker-entrypoint.s…"   About an hour ago   Up About an hour (unhealthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
6f3fb28cf3bc        docksal/web:2.1-apache2.4   "httpd-foreground"       About an hour ago   Up 39 minutes                  80/tcp, 443/tcp                                          drupal8_web_1_f830d1bc9b97
e7228585e19f        docksal/cli:2.5-php7.1      "/opt/startup.sh sup…"   About an hour ago   Up 39 minutes (healthy)        22/tcp, 3000/tcp, 9000/tcp                               drupal8_cli_1_11260c39153e
92e89cfc4ae5        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   2 hours ago         Up 39 minutes                  0.0.0.0:32771->3306/tcp                                  drupal8_db_1_a439a828ee7c

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
9534dc762302        _default            bridge              local
02f6b3b524aa        bridge              bridge              local
b4c805107489        drupal8_default     bridge              local
bf4688f07786        host                host                local
0ed371f49445        none                null                local

███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
udev            3,8G     0  3,8G   0% /dev
tmpfs           773M  9,8M  763M   2% /run
/dev/sda1       458G  9,1G  426G   3% /
tmpfs           3,8G   10M  3,8G   1% /dev/shm
tmpfs           5,0M  4,0K  5,0M   1% /run/lock
tmpfs           3,8G     0  3,8G   0% /sys/fs/cgroup
/dev/loop0       89M   89M     0 100% /snap/core/5897
/dev/loop1       46M   46M     0 100% /snap/core18/442
/dev/loop2       35M   35M     0 100% /snap/gtk-common-themes/818
/dev/loop3      143M  143M     0 100% /snap/chromium/516
tmpfs           773M   68K  773M   1% /run/user/1000
/dev/sdb1       2,0G  1,6G  387M  81% /media/user/Flash
/dev/loop4       88M   88M     0 100% /snap/keepassxc/49
/dev/loop5      170M  170M     0 100% /snap/gimp/70
  ```

</details>
