### ISSUE TITLE
Error starting service - network not found

### ISSUE THREAD

**Issue by mikecrittenden** [docksal/docksal#875]
**Description**

Our project uses Blackfire, and recently we've all (about 6 different people) started getting the following error during `fin start`:

```
❯ fin start
Key 'id_rsa' already loaded in the agent. Skipping.
Starting services...
Creating network "projectname_default" with the default driver
Starting projectname_blackfire_1 ... error
Starting projectname_mail_1      ...
Starting projectname_cli_1       ...
Starting projectname_db_1        ...
Starting projectname_mail_1      ... done
Starting projectname_cli_1       ... done
Starting projectname_db_1        ... done
Starting projectname_solr_1      ... done
Starting projectname_memcached_1 ... done
Starting projectname_web_1       ... done
Starting projectname_varnish_1   ... done

ERROR: for blackfire  Cannot start service blackfire: network a352e167afc8fb2b72cd8687347572482b85deb1a57e10ba2783155f908489bb not found
ERROR: Encountered errors while bringing up the project.;
```

That said, we aren't able to reproduce the issue on a new empty Docksal project so I'm not sure what is unique about ours. 

Here's the docksal-local.yml:

```
version: "2.1"

services:
  cli:
    environment:
      - PHP_IDE_CONFIG=serverName=${VIRTUAL_HOST}
  blackfire:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: blackfire
```

And the docksal.yml:

```
version: '2.1'
services:
  cli:
    labels:
      - io.docksal.virtual-host=design.${VIRTUAL_HOST}
      - io.docksal.virtual-port=3000
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail
```

We have tried `fin reset blackfire` as well as just `fin reset` and both complete without issue, but then `fin start` still throws the error afterwards.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: fanniemae
COMPOSE_FILE:
/Users/mcrittenden/.docksal/stacks/overrides-osxfs.yml
/Users/mcrittenden/.docksal/stacks/volumes-bind.yml
/Users/mcrittenden/.docksal/stacks/stack-acquia.yml
/Users/mcrittenden/Dropbox/Code/fanniemae/.docksal/docksal.yml
/Users/mcrittenden/Dropbox/Code/fanniemae/.docksal/docksal-local.yml
ENV_FILE:
/Users/mcrittenden/Dropbox/Code/fanniemae/.docksal/docksal.env
/Users/mcrittenden/Dropbox/Code/fanniemae/.docksal/docksal-local.env

PROJECT_ROOT: /Users/mcrittenden/Dropbox/Code/fanniemae
DOCROOT: docroot
VIRTUAL_HOST: fanniemae.docksal
VIRTUAL_HOST_ALIASES: *.fanniemae.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32787

Docker Compose configuration
---------------------
services:
  blackfire:
    environment:
      BLACKFIRE_SERVER_ID: null
      BLACKFIRE_SERVER_TOKEN: null
    image: blackfire/blackfire
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      GIT_USER_EMAIL: mikecrittenden@gmail.com
      GIT_USER_NAME: Mike Crittenden
      HOST_GID: '20'
      HOST_UID: '502'
      PHP_IDE_CONFIG: serverName=fanniemae.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: fanniemae.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.5-php7.1
    labels:
      io.docksal.virtual-host: ' design.fanniemae.docksal'
      io.docksal.virtual-port: '3000'
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /Users/mcrittenden/Dropbox/Code/fanniemae:/var/www:rw,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  mail:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: mail.fanniemae.docksal,mail.fanniemae.docksal.*
      io.docksal.virtual-port: '8025'
    volumes:
    - project_root:/var/www:ro,nocopy
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: solr
    image: docksal/solr:1.0-solr4
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: solr.fanniemae.docksal,solr.fanniemae.docksal.*
      io.docksal.virtual-port: '8983'
    volumes:
    - project_root:/var/www:ro,nocopy
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:1.1-varnish5
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: varnish.fanniemae.docksal,varnish.fanniemae.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/mcrittenden/Dropbox/Code/fanniemae
      io.docksal.virtual-host: fanniemae.docksal,*.fanniemae.docksal,fanniemae.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/mcrittenden/Dropbox/Code/fanniemae
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.14.1
Darwin Mike-Crittendens-New-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker for Mac

███  FIN
fin version: 1.80.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.1
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.06.1-ce

Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                                project root
fanniemae           Up 2 minutes        fanniemae.docksal,*.fanniemae.docksal,fanniemae.docksal.*   /Users/mcrittenden/Dropbox/Code/fanniemae

███  DOCKSAL: VIRTUAL HOSTS
[0;32mdesign.fanniemae.docksal[0m
[0;32m*.fanniemae.docksal[0m
[0;32mfanniemae.docksal.*[0m
[0;32mfanniemae.docksal[0m
[0;32mmail.fanniemae.docksal.*[0m
[0;32mmail.fanniemae.docksal[0m
[0;32msolr.fanniemae.docksal.*[0m
[0;32msolr.fanniemae.docksal[0m
[0;32mvarnish.fanniemae.docksal.*[0m
[0;32mvarnish.fanniemae.docksal[0m

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                   PORTS                                                    NAMES
3e8c06b198c8        docksal/varnish:1.1-varnish5   "/opt/startup.sh"        4 days ago          Up 2 minutes             80/tcp, 6082/tcp                                         fanniemae_varnish_1
b78de3033a1c        docksal/web:2.1-apache2.4      "httpd-foreground"       4 days ago          Up 2 minutes             80/tcp, 443/tcp                                          fanniemae_web_1
a6b5916f427c        docksal/cli:2.5-php7.1         "/opt/startup.sh sup…"   4 days ago          Up 2 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               fanniemae_cli_1
70157f91864c        memcached:1.4-alpine           "docker-entrypoint.s…"   4 days ago          Up 2 minutes             11211/tcp                                                fanniemae_memcached_1
c9127ee1e987        mailhog/mailhog                "MailHog"                4 days ago          Up 2 minutes             1025/tcp, 8025/tcp                                       fanniemae_mail_1
8d7effd3f370        docksal/solr:1.0-solr4         "/opt/solr/bin/solr …"   4 days ago          Up 2 minutes             8983/tcp                                                 fanniemae_solr_1
cc7a7f5a0522        docksal/db:1.2-mysql-5.6       "/entrypoint.sh mysq…"   4 days ago          Up 2 minutes             0.0.0.0:32787->3306/tcp                                  fanniemae_db_1
3c14cd0795c9        docksal/ssh-agent:1.2          "docker-entrypoint.s…"   5 days ago          Up 5 days (healthy)                                                               docksal-ssh-agent
03ee1f6b0730        docksal/dns:1.1                "docker-entrypoint.s…"   5 days ago          Up 5 days (healthy)      192.168.64.100:53->53/udp                                docksal-dns
6eb7d010506b        docksal/vhost-proxy:1.4        "docker-entrypoint.s…"   5 days ago          Up 5 days (unhealthy)    192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                                                                         DRIVER              SCOPE
b224e98fdda1        _default                                                                     bridge              local
710943d98afb        bostonvocations_default                                                      bridge              local
0ac57d52f530        bridge                                                                       bridge              local
41066da053d2        docksaltest_default                                                          bridge              local
9996a58b411a        dosomethingindonesia_default                                                 bridge              local
7e6274eccb20        faithmag_default                                                             bridge              local
d3046dcdef78        fanniemae_default                                                            bridge              local
b58d3d9f5e4b        haxcms_default                                                               bridge              local
4d5fcec96029        host                                                                         host                local
9bf681ca0a21        lando_bridge_network                                                         bridge              local
c317fee5918f        landocasetupkenobi38ahsokabb021307b4190300c7b11bea76bb7c78b8e0feb4_default   bridge              local
18df2abfe561        landoinitdosomethingindonesia_default                                        bridge              local
36805f8848f9        landoproxyhyperion5000gandalfedition_edge                                    bridge              local
2316d3950f66        lineage_default                                                              bridge              local
0baa722c1de2        mp8_default                                                                  bridge              local
e5dbd15d735b        none                                                                         null                local
8fcf455fa8d9        particle-docksal_default                                                     bridge              local
26ff77bc12c8        particle_default                                                             bridge              local
9c1c0dd14e52        personal-blog_default                                                        bridge              local
22fe3e82db4c        saginaw_default                                                              bridge              local

███  HDD Usage
Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1   234Gi  210Gi   19Gi    92% 3982302 9223372036850793505    0%   /
devfs          186Ki  186Ki    0Bi   100%     644                   0  100%   /dev
/dev/disk1s4   234Gi  4.0Gi   19Gi    18%       4 9223372036854775803    0%   /private/var/vm
map -hosts       0Bi    0Bi    0Bi   100%       0                   0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0                   0  100%   /home
/dev/disk1s3   234Gi  489Mi   19Gi     3%      20 9223372036854775787    0%   /Volumes/Recovery
  ```

</details>

**Comment by lmakarov** [comment]
Blackfire container is the first one in the list, right after the network creation:

```
...
Creating network "projectname_default" with the default driver
Starting projectname_blackfire_1 ... error
...
```

I wonder if there is some kind of race condition in Docker 18.09.0 / Docker Compose 1.23.1.

Next time you run into this, note the output from `fin docker network ls | grep projectname_default` as well as the `ERROR: for blackfire  Cannot start service blackfire: network <netid> not found`.
If the two match, then blackfire starts before the network is ready. If they don't - then blackfire somehow is still attached to the old network, which gets destroyed when you do `fin p stop`

**Comment by mikecrittenden** [comment]
@lmakarov:

```
.....
ERROR: for blackfire  Cannot start service blackfire: network 54033d638d8967eee18e909707a6dcf4d2acfb93c49cd9e007e1d4651a8e400d not found
ERROR: Encountered errors while bringing up the project.

❯ fin docker network ls | grep projectname_default
c5764329b20a        projectname_default            bridge              local
```

Looks like they don't match. Is there any way for me to manually un-attach it from the old network or something?

@achekulaev Things I have tried:

- `fin reset`
- `fin reset blackfire`
- `fin project stop && fin project start`
- `fin restart`

So far no luck with any of those.

**Comment by lmakarov** [comment]
Try this

```
fin docker network disconnect 54033d638d8967eee18e909707a6dcf4d2acfb93c49cd9e007e1d4651a8e400d projectname_blackfire_1
```

**Comment by achekulaev** [comment]
@lmakarov but then you'd need to manually attach it to the proper one? Or maybe `fin reset blackfire`?

**Comment by lmakarov** [comment]
@mikecrittenden what do you get from `fin project reset blackfire`?

**Comment by mikecrittenden** [comment]
So this is odd. The reset worked fine, and a restart right afterwards worked fine (which recreated the blackfire container), but then if I restart AGAIN (once the blackfire container already exists), I get the error. See here:

```
❯ fin project reset blackfire
Going to remove projectname_blackfire_1_371324db877a
Removing projectname_blackfire_1_371324db877a ... done

❯ fin project restart
Key 'id_rsa' already loaded in the agent. Skipping.
Disconnecting project network...
Stopping services...
Stopping projectname_varnish_1_ccaaac232fbd   ... done
Stopping projectname_web_1_af95efa2c74d       ... done
Stopping projectname_solr_1_42b26250132d      ... done
Stopping projectname_mail_1_f2df4a3c3859      ... done
Stopping projectname_memcached_1_8a04b438d423 ... done
Stopping projectname_cli_1_f03a65ca270a       ... done
Stopping projectname_db_1_8758649f9626        ... done
Starting services...
Creating network "projectname_default" with the default driver
Starting projectname_db_1_8758649f9626        ... done
Starting projectname_solr_1_42b26250132d      ... done
Starting projectname_cli_1_f03a65ca270a       ... done
Starting projectname_memcached_1_8a04b438d423 ... done
Starting projectname_mail_1_f2df4a3c3859      ... done
Creating projectname_blackfire_1_37422c50ec8a ... done
Starting projectname_web_1_af95efa2c74d       ... done
Starting projectname_varnish_1_ccaaac232fbd   ... done
Waiting 10s for container to start...
Connected vhost-proxy to "projectname_default" network.

❯ fin project restart
Key 'id_rsa' already loaded in the agent. Skipping.
Disconnecting project network...
Stopping services...
Stopping projectname_varnish_1_ccaaac232fbd   ... done
Stopping projectname_web_1_af95efa2c74d       ... done
Stopping projectname_solr_1_42b26250132d      ... done
Stopping projectname_mail_1_f2df4a3c3859      ... done
Stopping projectname_memcached_1_8a04b438d423 ... done
Stopping projectname_cli_1_f03a65ca270a       ... done
Stopping projectname_db_1_8758649f9626        ... done
Starting services...
Creating network "projectname_default" with the default driver
Starting projectname_solr_1_42b26250132d ... 
Starting projectname_blackfire_1_556f4128604f ... error
Starting projectname_mail_1_f2df4a3c3859      ... 
Starting projectname_solr_1_42b26250132d      ... done
Starting projectname_db_1_8758649f9626        ... 
Starting projectname_mail_1_f2df4a3c3859      ... done
Starting projectname_cli_1_f03a65ca270a       ... done
Starting projectname_db_1_8758649f9626        ... done
Starting projectname_memcached_1_8a04b438d423 ... done
Starting projectname_web_1_af95efa2c74d       ... done
Starting projectname_varnish_1_ccaaac232fbd   ... done

ERROR: for blackfire  Cannot start service blackfire: network 6fd77d52fdf6f0c99af70471c3f52bd6368ca15c968208291d9393c9b18a79dd not found
ERROR: Encountered errors while bringing up the project.
```

**Comment by achekulaev** [comment]
Whoa! it did not stop blackfire!

**Comment by achekulaev** [comment]
Can you show output of 
```
fin project rm blackfire
fin p start
fin p stop
fin ps
```
?

**Comment by mikecrittenden** [comment]
Sure:

```
❯ fin project rm blackfire
Going to remove projectname_blackfire_1_556f4128604f
Removing projectname_blackfire_1_556f4128604f ... done

❯ fin p start
Key 'id_rsa' already loaded in the agent. Skipping.
Starting services...
projectname_cli_1_f03a65ca270a is up-to-date
projectname_memcached_1_8a04b438d423 is up-to-date
projectname_mail_1_f2df4a3c3859 is up-to-date
projectname_solr_1_42b26250132d is up-to-date
projectname_db_1_8758649f9626 is up-to-date
projectname_web_1_af95efa2c74d is up-to-date
projectname_varnish_1_ccaaac232fbd is up-to-date
Creating projectname_blackfire_1_fa1161cce574 ... done
Waiting 10s for container to start...
Connected vhost-proxy to "projectname_default" network.
Virtual Host: http://projectname.docksal

❯ fin p stop
Disconnecting project network...
Stopping services...
Stopping projectname_varnish_1_ccaaac232fbd   ... done
Stopping projectname_web_1_af95efa2c74d       ... done
Stopping projectname_solr_1_42b26250132d      ... done
Stopping projectname_mail_1_f2df4a3c3859      ... done
Stopping projectname_memcached_1_8a04b438d423 ... done
Stopping projectname_cli_1_f03a65ca270a       ... done
Stopping projectname_db_1_8758649f9626        ... done

❯ fin ps
               Name                            Command              State     Ports
-----------------------------------------------------------------------------------
projectname_blackfire_1_ae846a08dec4   blackfire-agent               Exit 1          
projectname_cli_1_f03a65ca270a         /opt/startup.sh supervisord   Exit 0          
projectname_db_1_8758649f9626          /entrypoint.sh mysqld         Exit 0          
projectname_mail_1_f2df4a3c3859        MailHog                       Exit 2          
projectname_memcached_1_8a04b438d423   docker-entrypoint.sh -m 128   Exit 0          
projectname_solr_1_42b26250132d        /opt/solr/bin/solr -f         Exit 137        
projectname_varnish_1_ccaaac232fbd     /opt/startup.sh               Exit 137        
projectname_web_1_af95efa2c74d         httpd-foreground              Exit 0          

❯ fin p start
Key 'id_rsa' already loaded in the agent. Skipping.
Starting services...
Creating network "projectname_default" with the default driver
Starting projectname_memcached_1_8a04b438d423 ... 
Starting projectname_solr_1_42b26250132d      ... 
Starting projectname_mail_1_f2df4a3c3859      ... 
Starting projectname_memcached_1_8a04b438d423 ... done
Starting projectname_solr_1_42b26250132d      ... done
Starting projectname_mail_1_f2df4a3c3859      ... done
Starting projectname_db_1_8758649f9626        ... done
ERROR: for projectname_blackfire_1_ae846a08dec4  Cannot start service blackfire: netwStarting projectname_cli_1_f03a65ca270a       ... done
Starting projectname_web_1_af95efa2c74d       ... done
Starting projectname_varnish_1_ccaaac232fbd   ... done

ERROR: for blackfire  Cannot start service blackfire: network 4dfc7ac9e5a15f3e14d988c04621fc979d982eead7ab004ced624374d4d687c4 not found
ERROR: Encountered errors while bringing up the project.
```

Thanks for taking a look at this with me! I'm sure we could work around it with `fin rm` and then clone the repo in a directory with a different name and start from scratch, but it'd be fantastic to get to the bottom of this instead.

**Comment by mikecrittenden** [comment]
Aha! I can reliably reproduce it with the following config. It seems that using the acquia stack is the key here.

`.docksal/docksal.yml`:

```
version: '2.1'
services:
  blackfire:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: blackfire
```

`.docksal/docksal.env`:

```
DOCKSAL_STACK=acquia
```

Using both of those in an otherwise empty directory, I can run `fin start && fin restart` and see the error.
