### ISSUE TITLE
Can't move existing site from Acquia Dev Desktop to Docksal

### ISSUE THREAD

**Issue by turpentyne** [docksal/docksal#885]
Issue: Existing site imported, but can only see 'new site' set up (from Dev Desktop to Docksal)

First, an apology: This is likely Not the correct place to put this, but I don't know where else to go. I'm not expecting a reply on Stackoverflow. I'm trying to move an existing site out of Acquia Dev Desktop and into Docksal. I'm sure there's just code to change somewhere, but don't know where. The site loads, but only as a new install. It's ignoring the existing database I've imported. 

**Steps to reproduce the issue:**

1. create Drupal 8 website, using PHP 7.1.12, locally on Acquia dev desktop.
2.  steps below follow instructions here: https://www.youtube.com/watch?v=C1YIHtrMzZU
2. Set up docksal. copy existing D8 site code into a new ~/projects/projectname folder
3. run fin start on new projectname folder
4. clone existing site's sql database to desktop. change drupal settings.php file to  
5. from command line, in site's new Docksal folder, import database.
6. navigate to site. (in code below, it's the "projectname.docksal" project.

**Describe the results you received:**

Results...It appears as a new website install, ignoring the existing database.

**Describe the results you expected:**

Expected behavior...It should show the existing website, and pull from the database.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: projectname
COMPOSE_FILE:
/Users/myname/.docksal/stacks/overrides-osxfs.yml
/Users/myname/.docksal/stacks/volumes-bind.yml
/Users/myname/.docksal/stacks/stack-default.yml
/Users/myname/projects/projectname/.docksal/docksal.yml
ENV_FILE:
/Users/myname/projects/projectname/.docksal/docksal.env

PROJECT_ROOT: /Users/myname/projects/projectname
DOCROOT: docroot
VIRTUAL_HOST: projectname.docksal
VIRTUAL_HOST_ALIASES: *.projectname.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      GIT_USER_EMAIL: ''
      GIT_USER_NAME: turpentyne
      HOST_GID: '20'
      HOST_UID: '916464642'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: projectname.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.5-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /Users/myname/projects/projectname:/var/www:rw,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/myname/projects/projectname
      io.docksal.virtual-host: projectname.docksal,*.projectname.docksal,projectname.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/myname/projects/projectname
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.13.3
Darwin SDLML00360.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker for Mac

███  FIN
fin version: 1.80.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.1
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.06.1-ce

Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKSAL: PROJECTS
project                   STATUS              virtual host                                                                                          project root
projectname              Up 37 minutes       projectname.docksal,*.projectname.docksal,projectname.docksal.*                                    /Users/myname/projects/projectname
drupal8-master            Up 35 minutes       drupal8-master.docksal,*.drupal8-master.docksal,drupal8-master.docksal.*                              /Users/myname/projects/drupal8-master
projectname-on-docksal   Up 24 minutes       projectname-on-docksal.docksal,*.projectname-on-docksal.docksal,projectname-on-docksal.docksal.*   /Users/myname/projects/projectname-on-docksal

███  DOCKSAL: VIRTUAL HOSTS
*.projectname-on-docksal.docksal
*.projectname.docksal
*.drupal8-master.docksal
projectname-on-docksal.docksal.*
projectname-on-docksal.docksal
projectname.docksal.*
projectname.docksal
drupal8-master.docksal.*
drupal8-master.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
458483546cd8        docksal/web:2.1-apache2.4   "httpd-foreground"       37 minutes ago      Up 37 minutes             80/tcp, 443/tcp                                          projectname_web_1
41e2179d43d1        docksal/cli:2.5-php7.1      "/opt/startup.sh sup…"   37 minutes ago      Up 37 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               projectname_cli_1
7dfa588b4543        docksal/ssh-agent:1.2       "docker-entrypoint.s…"   37 minutes ago      Up 37 minutes (healthy)                                                            docksal-ssh-agent
4ea7d636fa12        docksal/dns:1.1             "docker-entrypoint.s…"   37 minutes ago      Up 37 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
e37d5c9e0491        docksal/vhost-proxy:1.4     "docker-entrypoint.s…"   37 minutes ago      Up 37 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
dadf47e4adc6        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   11 hours ago        Up 37 minutes             0.0.0.0:32768->3306/tcp                                  projectname_db_1
8aa2436feadd        docksal/web:2.1-apache2.4   "httpd-foreground"       12 hours ago        Up 35 minutes             80/tcp, 443/tcp                                          drupal8-master_web_1
23306d92a204        docksal/cli:2.5-php7.1      "/opt/startup.sh sup…"   12 hours ago        Up 35 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               drupal8-master_cli_1
38f9e75ca981        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   12 hours ago        Up 35 minutes             0.0.0.0:32769->3306/tcp                                  drupal8-master_db_1
4fcc3c6a317b        docksal/web:2.1-apache2.4   "httpd-foreground"       16 hours ago        Up 24 minutes             80/tcp, 443/tcp                                          projectname-on-docksal_web_1
edef2bca2d57        docksal/cli:2.5-php7.1      "/opt/startup.sh sup…"   16 hours ago        Up 24 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               projectname-on-docksal_cli_1
abb4c0542b26        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   16 hours ago        Up 24 minutes             0.0.0.0:32770->3306/tcp                                  projectname-on-docksal_db_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                              DRIVER              SCOPE
dca08a0c3008        _default                          bridge              local
1e777e8b7e6d        bridge                            bridge              local
d623d79de6c0        projectname-on-docksal_default   bridge              local
a65070381c72        projectname_default              bridge              local
e6d3194d966e        drupal8-master_default            bridge              local
c360682d777b        host                              host                local
1090383f54e5        none                              null                local

███  HDD Usage
Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1   234Gi  216Gi   16Gi    93% 2547061 9223372036852228746    0%   /
devfs          186Ki  186Ki    0Bi   100%     642                   0  100%   /dev
/dev/disk1s4   234Gi  1.0Gi   16Gi     6%       1 9223372036854775806    0%   /private/var/vm
map -hosts       0Bi    0Bi    0Bi   100%       0                   0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0                   0  100%   /home
map -fstab       0Bi    0Bi    0Bi   100%       0                   0  100%   /Network/Servers
  ```

</details>
