### ISSUE TITLE
SMB mount failed Windows 10 babun Virtual Box

### ISSUE THREAD

**Issue by Lolodrom** [docksal/docksal#901]
**Description**

During the first installment of docksal, I received the SMB share mount failed on Windows 10.
After uninstall / install of docksal mentioned in the following thread: https://github.com/docksal/docksal/issues/842 it started to work fine.

After a few days, I am not able to start the vm anymore.
The SMB share mount failed again, but now the steps mentioned in the above post do not work anymore.

Steps from following Threads applied, still the same issue:
- https://docs.docksal.io/troubleshooting/windows-smb/
- https://superuser.com/questions/443329/windows-7-file-and-printer-sharing-doesnt-work-for-me/446500#446500

I am currently stuck at the point again, where I am not able to access the docksal IP via Explorer. (\\192.168.64.1\)

Checked other threads regarding SMB mount failed but I could not find a solution yet.

**Steps to reproduce the issue:**

1. start babun
2. run fin vm start

**Describe the results you received:**

Adding docker SMB share...
mount: mounting //192.168.64.1/docksal-c on /c failed: Operation now in progress
exit status 255
Mount command failed... Trying an alternative method...
mount: mounting //192.168.64.1/docksal-c on /c failed: Operation now in progress
exit status 255
 ERROR:  SMB share mount failed.
         Make sure your Windows password is correct and run fin vm restart to try again.
         For troubleshooting instructions see https://docs.docksal.io/troubleshooting/windows-smb/

**Describe the results you expected:**

A working environment

**Output of `fin config`:**

User and project name exchanged with dummy.

<details>
  <summary>fin config output</summary>

```
COMPOSE_PROJECT_NAME_SAFE: project1
COMPOSE_FILE:
C:/Users/username/.babun/cygwin/home/username/.docksal/stacks/volumes-bind.yml
C:/Users/username/.babun/cygwin/home/username/.docksal/stacks/stack-default.yml
C:/Users/username/.babun/cygwin/home/username/projects/project1/.docksal/docksal.yml
ENV_FILE:
C:/Users/username/.babun/cygwin/home/username/projects/project1/.docksal/docksal.env

PROJECT_ROOT: /c/Users/username/.babun/cygwin/home/username/projects/project1
DOCROOT: site/web
VIRTUAL_HOST: project1.company.net
VIRTUAL_HOST_ALIASES: *.project1.company.net
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: site/web
      GIT_USER_EMAIL: null
      GIT_USER_NAME: null
      HOST_GID: null
      HOST_UID: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: project1.company.net
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:2.4-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: project1db
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: demo
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_USER: project1usr
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/site/web
    hostname: web
    image: docksal/web:2.0-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /c/Users/username/.babun/cygwin/home/username/projects/project1
      io.docksal.virtual-host: project1.company.net,*.project1.company.net
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/username/.babun/cygwin/home/username/projects/project1
      o: bind
      type: none
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary> fin sysinfo output
</summary>

  ```
  Cygwin Windows 10.0.17134
CYGWIN_NT-10.0-WOW DESKTOP-CLC1C7F 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376

███  FIN
fin version: 1.80.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.1
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.06.1-ce

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKER MACHINE
EXPECTED VERSION: 0.15.0
docker-machine.exe version 0.15.0, build b48dc28d

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.06.1-ce

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS
No virtual hosts found

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                   PORTS                                                    NAMES
e44a3eca0f18        docksal/ssh-agent:1.2     "docker-entrypoint.s…"   3 days ago          Up 7 minutes (healthy)                                                            docksal-ssh-agent
1b7bb31de460        docksal/dns:1.1           "docker-entrypoint.s…"   3 days ago          Up 7 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
18338b8212d0        docksal/vhost-proxy:1.4   "docker-entrypoint.s…"   3 days ago          Up 7 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
e0b8f2470293        _default            bridge              local
4efdc0a45068        bridge              bridge              local
8deb544dda76        host                host                local
6624e9127534        project1_default      bridge              local
74e2a79d0062        none                null                local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.20
5.2.20r125813

███  DOCKSAL MOUNTS
 ERROR:  Mounts matching 192.168.64* were not found!

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G      1.7G     42.1G   4% /mnt/sda1

  ```

</details>
