### ISSUE TITLE
How to debug error: Connecting to test.docksal (test.docksal)|192.168.64.100|:80... failed: Connection refused.

### ISSUE THREAD

**Issue by jessehs** [docksal/docksal#939]
**Description**

I have an issue which I believe is a system-wide config problem. I have not seen this with the "common problems" troubleshooting section, and I'm at a loss as to the next debugging steps.

By posting this issue I'm hoping to get some more suggestions on the next debugging steps. I believe I have a problem with my system where I always get the same error:

`Connecting to test.docksal (test.docksal)|192.168.64.100|:80... failed: Connection refused.`

**Steps to reproduce the issue and debugging steps performed:**

I installed Docksal with Docker 4 Mac.

Some steps I've tried:

Performing "fin system stop; fin system start"
Restarting the host computer (macbook OS X v. 10.14.1)
Resetting Docker for mac to factory defaults.

I've tried creating a few different project and get the same error. To break it down to the most simple case, I've created a very simple directory "test" with 4 files:

test/.docksal/docksal.env (DOCKSAL_STACK=default / DOCROOT=docroot)
test/.docksal/docksal.yml (version 2.1)
test/docroot/index.php (phpinfo();)
test/docroot/index.html (Hello world)

In my ~/.docksal/docksal.env I have:

DOCKER_NATIVE=1
DOCKSAL_UUID=f0788bf1-1ef3-4aef-33c8-f2bfa7c80bb3
DOCKSAL_DNS_DEBUG=true

```
$ fin system start
Starting Docksal system services...
Configuring network settings...
Password:
Resetting Docksal services...
 ➔ proxy
 ➔ dns
   upstream 8.8.8.8
 ➔ ssh-agent
Identity added: id_rsa (id_rsa)
```

```
$ fin start
Key 'id_rsa' already loaded in the agent. Skipping.
Starting services...
Creating network "test_default" with the default driver
Starting test_cli_1 ... done
Starting test_db_1  ... done
Starting test_web_1 ... done
Waiting 10s for container to start...
Connected vhost-proxy to "test_default" network.
Virtual Host: http://test.docksal
```

```
$ wget test.docksal
--2019-01-23 17:17:11--  http://test.docksal/
Resolving test.docksal... 192.168.64.100
Connecting to test.docksal|192.168.64.100|:80... failed: Connection refused.
```

In the log for the dns container:

```
$ docker logs -f docksal-dns
2019-01-24 00:14:52 | Generating configuration in /etc/dnsmasq.d/docksal.conf
2019-01-24 00:14:52 | Passing execution to: dnsmasq
dnsmasq: started, version 2.79 cachesize 150
dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
dnsmasq: reading /etc/resolv.conf
dnsmasq: using nameserver 8.8.8.8#53
dnsmasq: using nameserver 9.9.9.9#53
dnsmasq: read /etc/hosts - 7 addresses

dnsmasq: query[A] test.docksal from 172.17.0.1
dnsmasq: config test.docksal is 192.168.64.100
```

Output for "docker ps":

```
$ docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                   PORTS                                                    NAMES
3e04f80f7bb5        docksal/ssh-agent:1.2       "docker-entrypoint.s…"   4 minutes ago       Up 4 minutes (healthy)                                                            docksal-ssh-agent
7125bce24b63        docksal/dns:1.1             "docker-entrypoint.s…"   4 minutes ago       Up 4 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
c7d3aa490f28        docksal/vhost-proxy:1.4     "docker-entrypoint.s…"   4 minutes ago       Up 4 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
79c405329799        docksal/web:2.1-apache2.4   "httpd-foreground"       17 minutes ago      Up 3 minutes             80/tcp, 443/tcp                                          test_web_1
4f8f2fd567d7        docksal/cli:2.5-php7.1      "/opt/startup.sh sup…"   17 minutes ago      Up 3 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               test_cli_1
8932de182cb2        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   17 minutes ago      Up 3 minutes             0.0.0.0:32770->3306/tcp                                  test_db_1

```

The command "fin docker inspect test_web_1" reveals "IPAddress": "172.21.0.4".

Then I try accessing the test file from within the "cli" container:

```
$ fin bash cli

$ wget -O - 172.21.0.4/index.html

```
I see the "Hello World" output from my index.html file. Same thing goes for the index.php file. I see the output of the phpinfo command. There is no DNS logging reported during these 2 tests.

Then I also try from inside the cli container:

```
$ wget -O - test.docksal/index.php
--2019-01-24 00:27:04--  http://test.docksal/index.php
Resolving test.docksal (test.docksal)... 192.168.64.100
Connecting to test.docksal (test.docksal)|192.168.64.100|:80... failed: Connection refused.

```
This is associated with the DNS logs:

```
dnsmasq: query[AAAA] test.docksal from 172.17.0.1
dnsmasq: config test.docksal is NODATA-IPv6
dnsmasq: query[A] test.docksal from 172.17.0.1
dnsmasq: config test.docksal is 192.168.64.100
```

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: test
COMPOSE_FILE:
/Users/jhofmann-smith/.docksal/stacks/overrides-osxfs.yml
/Users/jhofmann-smith/.docksal/stacks/volumes-bind.yml
/Users/jhofmann-smith/.docksal/stacks/stack-default.yml
/Users/jhofmann-smith/projects/test/.docksal/docksal.yml
ENV_FILE:
/Users/jhofmann-smith/projects/test/.docksal/docksal.env

PROJECT_ROOT: /Users/jhofmann-smith/projects/test
DOCROOT: docroot
VIRTUAL_HOST: test.docksal
VIRTUAL_HOST_ALIASES: *.test.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32770

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      GIT_USER_EMAIL: jhofmann-smith@phase2technology.com
      GIT_USER_NAME: Jesse Hofmann-Smith
      HOST_GID: '20'
      HOST_UID: '502'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: test.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.5-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /Users/jhofmann-smith/projects/test:/var/www:rw,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/jhofmann-smith/projects/test
      io.docksal.virtual-host: test.docksal,*.test.docksal,test.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/jhofmann-smith/projects/test
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.14.1
Darwin Jesses-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker for Mac

███  FIN
fin version: 1.80.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.1
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.06.1-ce

Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:33:12 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                 project root
test                Up 27 minutes       test.docksal,*.test.docksal,test.docksal.*   /Users/jhofmann-smith/projects/test

███  DOCKSAL: VIRTUAL HOSTS
*.test.docksal
test.docksal.*
test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
3e04f80f7bb5        docksal/ssh-agent:1.2       "docker-entrypoint.s…"   27 minutes ago      Up 27 minutes (healthy)                                                            docksal-ssh-agent
7125bce24b63        docksal/dns:1.1             "docker-entrypoint.s…"   27 minutes ago      Up 27 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
c7d3aa490f28        docksal/vhost-proxy:1.4     "docker-entrypoint.s…"   27 minutes ago      Up 27 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
79c405329799        docksal/web:2.1-apache2.4   "httpd-foreground"       40 minutes ago      Up 27 minutes             80/tcp, 443/tcp                                          test_web_1
4f8f2fd567d7        docksal/cli:2.5-php7.1      "/opt/startup.sh sup…"   40 minutes ago      Up 27 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               test_cli_1
8932de182cb2        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   40 minutes ago      Up 27 minutes             0.0.0.0:32770->3306/tcp                                  test_db_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
87d4c0a2c663        _default            bridge              local
9f1bc838e705        bridge              bridge              local
04368a091cad        host                host                local
97cb73f99ffc        none                null                local
cdd269845c12        test_default        bridge              local

███  HDD Usage
Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1   466Gi  398Gi   66Gi    86% 3591776 9223372036851184031    0%   /
devfs          352Ki  352Ki    0Bi   100%    1218                   0  100%   /dev
/dev/disk1s4   466Gi  1.0Gi   66Gi     2%       1 9223372036854775806    0%   /private/var/vm
map -hosts       0Bi    0Bi    0Bi   100%       0                   0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0                   0  100%   /home
/dev/disk1s3   466Gi  489Mi   66Gi     1%      20 9223372036854775787    0%   /Volumes/Recovery  ```

</details>
