### ISSUE TITLE
vm start does not work as part of fin up

### ISSUE THREAD

**Issue by paulsheldrake** [docksal/docksal#949]
If you're in a project that is not "up" and the Virtualbox machine is not running and you run `fin up`, the VM never starts correctly on the first try.   I always have to run `fin vm restart` when it errors out.   this happens on all my projects

```
Kanopi-MBP:mises.org paulsheldrake$ fin up
It looks like 'docksal' docker machine is not running.
Run 'fin vm start' to start it now? [y/n]: y
Starting "docksal"...
(docksal) Waiting for an IP...
Machine "docksal" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
Password:
Configuring NFS shares...
NFS shares are already configured
Mounting NFS shares...
/usr/local/sbin/rpcbind is already running
3552
/usr/local/sbin/rpc.statd is already running
3554
Starting nfs client utilities.
Mounting local /Users/paulsheldrake/docksal to /Users/paulsheldrake/docksal
Importing ssh keys...
Key 'id_rsa' already loaded in the agent. Skipping.
 ERROR:  Your Docker client is unable to talk to the Docker server.
         WHAT TO DO?
         1. Try fin vm restart.
         2. If #1 did not help, run fin update to update.
         3. Check errors you see in troubleshooting doc https://docs.docksal.io/troubleshooting/common-issues/
Kanopi-MBP:mises.org paulsheldrake$ fin vm restart
Stopping "docksal"...
Machine "docksal" was stopped.
Starting "docksal"...
(docksal) Check network to re-create if needed...
(docksal) Waiting for an IP...
Machine "docksal" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
Configuring NFS shares...
NFS shares are already configured
Mounting NFS shares...
Starting nfs client utilities.
Mounting local /Users/paulsheldrake/docksal to /Users/paulsheldrake/docksal
Importing ssh keys...
Identity added: id_rsa (id_rsa)
Kanopi-MBP:mises.org paulsheldrake$
```

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: misesorg
COMPOSE_FILE:
/Users/paulsheldrake/.docksal/stacks/volumes-bind.yml
/Users/paulsheldrake/docksal/kanopi_docksal/mises/mises.org/.docksal/docksal.yml
ENV_FILE:
/Users/paulsheldrake/docksal/kanopi_docksal/mises/mises.org/.docksal/docksal.env
/Users/paulsheldrake/docksal/kanopi_docksal/mises/mises.org/.docksal/docksal-local.env

PROJECT_ROOT: /Users/paulsheldrake/docksal/kanopi_docksal/mises/mises.org
DOCROOT: .
VIRTUAL_HOST: mises.docksal
VIRTUAL_HOST_ALIASES: *.mises.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  blackfire:
    environment:
      BLACKFIRE_SERVER_ID: aa4ac*****92704
      BLACKFIRE_SERVER_TOKEN: b2876*****0ac71
    image: blackfire/blackfire
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: .
      GIT_USER_EMAIL: paul.sheldrake@gmail.com
      GIT_USER_NAME: Paul Sheldrake
      HOST_GID: '20'
      HOST_UID: '501'
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: mises.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /Users/paulsheldrake/docksal/kanopi_docksal/mises/mises.org/.docksal/etc/drush:/etc/drush:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.7
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.mises.docksal
    user: root
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/.
      APACHE_FILE_PROXY: https://mises.org
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/paulsheldrake/docksal/kanopi_docksal/mises/mises.org
      io.docksal.virtual-host: mises.docksal,*.mises.docksal,mises.docksal.*
    volumes:
    - /Users/paulsheldrake/docksal/kanopi_docksal/mises/mises.org/.docksal/etc/apache/host.conf:/usr/local/apache2/conf/extra/includes/host.conf:ro
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/paulsheldrake/docksal/kanopi_docksal/mises/mises.org
      o: bind
      type: none

---------------------
```

</details>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

```
███  OS
Darwin Mac OS X 10.12.6
Darwin Kanopi-MBP.hitronhub.home 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : /Users/paulsheldrake/docksal
NFS EXPORTS:
# VAGRANT-BEGIN: 501 19ed865d-28dd-4d57-931b-0fc57b856b49
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.88.88 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/pnw/pnw_drupalvm" 192.168.88.88 -alldirs -mapall=501:20
# VAGRANT-END: 501 19ed865d-28dd-4d57-931b-0fc57b856b49
# VAGRANT-BEGIN: 501 29e3522b-b1c7-4494-8aff-83deff88c628
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.33.88 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/zopfli_vm" 192.168.33.88 -alldirs -mapall=501:20
# VAGRANT-END: 501 29e3522b-b1c7-4494-8aff-83deff88c628
# VAGRANT-BEGIN: 501 409fe48b-b565-4a78-a5b4-5d3e4b7591cd
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.88.88 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/ico/drupalvm_ico" 192.168.88.88 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/ico/ico-rally" 192.168.88.88 -alldirs -mapall=501:20
# VAGRANT-END: 501 409fe48b-b565-4a78-a5b4-5d3e4b7591cd
# VAGRANT-BEGIN: 501 e48f4e7d-f212-4fb7-b14f-5d78fb7df132
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/centos6" 10.20.1.3 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/zuckerman/zuckerman" "/Users/paulsheldrake/Documents/work/kanopi/zuckerman/zuckerman/htdocs" "/Users/paulsheldrake/Documents/work/kanopi/zuckerman/zuckerman/docs/dist" "/Users/paulsheldrake/Documents/work/kanopi/zuckerman/zuckerman/patternlab" 10.20.1.3 -alldirs -mapall=501:20
# VAGRANT-END: 501 e48f4e7d-f212-4fb7-b14f-5d78fb7df132


# VAGRANT-BEGIN: 501 ae60f4e7-ee00-491d-a138-41cb0d902dec
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.21.12 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/sfcm/drupalvm-sfcm" 192.168.21.12 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/sfcm/sfcm" 192.168.21.12 -alldirs -mapall=501:20
# VAGRANT-END: 501 ae60f4e7-ee00-491d-a138-41cb0d902dec





# VAGRANT-BEGIN: 501 8ae7354d-589e-4262-8a03-e964bada3fb4
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.99.11 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/sfpl/code" 192.168.99.11 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/sfpl/drupal-vm" 192.168.99.11 -alldirs -mapall=501:20
# VAGRANT-END: 501 8ae7354d-589e-4262-8a03-e964bada3fb4


# VAGRANT-BEGIN: 501 c2016ecd-8a1f-4f1a-8395-914247b50452
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.82.23 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/brain1st/brain-1st" 192.168.82.23 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/brain1st/drupalvm_brain1st" 192.168.82.23 -alldirs -mapall=501:20
# VAGRANT-END: 501 c2016ecd-8a1f-4f1a-8395-914247b50452


# VAGRANT-BEGIN: 501 887771ae-e3e3-404c-a68f-d591e6dac7e8
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.88.54 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/ibew/drupalvm_ibew_46" 192.168.88.54 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/ibew/ibew1269" 192.168.88.54 -alldirs -mapall=501:20
# VAGRANT-END: 501 887771ae-e3e3-404c-a68f-d591e6dac7e8






# VAGRANT-BEGIN: 501 eba2a7d3-3c8e-4b21-a354-31a5e34b0d19
"/Users/paulsheldrake/Documents/work/kanopi/ischool/www-ischool" 10.20.1.2 -alldirs -mapall=501:20
# VAGRANT-END: 501 eba2a7d3-3c8e-4b21-a354-31a5e34b0d19


# VAGRANT-BEGIN: 501 c8452f93-258e-44b3-8151-d851e03f0dcb
"/Users/paulsheldrake/.vagrant.d/cache/geerlingguy/ubuntu1604" 192.168.23.39 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/ndi/drupalvm-ndi-tech" 192.168.23.39 -alldirs -mapall=501:20
"/Users/paulsheldrake/Documents/work/kanopi/ndi/ndiorg" 192.168.23.39 -alldirs -mapall=501:20
# VAGRANT-END: 501 c8452f93-258e-44b3-8151-d851e03f0dcb
# <ds-nfs docksal
/Users/paulsheldrake/docksal 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.80.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.1
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.06.1-ce

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKER MACHINE
EXPECTED VERSION: 0.15.0
docker-machine version 0.15.0, build b48dc28d

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.06.1-ce

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                   PORTS                                                    NAMES
da7ff7ff1933        docksal/ssh-agent:1.2     "docker-entrypoint.s…"   4 weeks ago         Up 7 minutes (healthy)                                                            docksal-ssh-agent
ccebaee64fc1        docksal/dns:1.1           "docker-entrypoint.s…"   4 weeks ago         Up 7 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
00eafcb5c679        docksal/vhost-proxy:1.4   "docker-entrypoint.s…"   4 weeks ago         Up 7 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
a742459a8d4b        _default            bridge              local
593aa4211c33        bridge              bridge              local
30ecf1e71b43        host                host                local
f6e97f927454        none                null                local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.20
5.2.2r119230

███  DOCKSAL MOUNTS
192.168.64.1:/Users/paulsheldrake/docksal on /Users/paulsheldrake/docksal type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                93.2G     37.7G     50.7G  43% /mnt/sda1
```

</details>
