### ISSUE TITLE
`fin drush sql-drop` running but not dropping db

### ISSUE THREAD

**Issue by froboy** [docksal/docksal#950]
**Description**

Running `fin drush sql-drop` seems to succeed, but doesn't actually drop any tables. I initially encountered this when trying to refresh my db and revert features and ran into some conflicting tables, which I was sure weren't in my `dev` db. It turned out the local db was never getting dropped.

I thought this might be related to #795 but I tried disabling XDEBUG and `fin restart`ing and experience the same issue.

**Steps to reproduce the issue:**

(Assuming you have a db in place)
1. `fin restart` (for good measure)
2. `fin sequelpro` and check to see the db tables exist
3. `fin drush sql-drop -y`
4. refresh SequelPro and see the tables still there.

**Describe the results you received:**

This seems right...
```
$ fin drush sql-drop -y -vvvv
Executing: cd /var/www/docroot && git rev-parse --show-toplevel 2> /dev/null
Do you really want to drop all tables in the database default? (y/n): y
Executing: mysql --defaults-extra-file=/tmp/drush_JrMrs9 --database=default --host=db --silent  < /tmp/drush_BUCzfr
Executing: mysql --defaults-extra-file=/tmp/drush_OGpUUz --database=default --host=db --silent  < /tmp/drush_lh9EGR
Command dispatch complete                       
```
But doesn't actually drop tables

**Describe the results you expected:**

I expect all my tables to be dropped.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      GIT_USER_EMAIL: xxxxx
      GIT_USER_NAME: Avi Schwab
      HOST_GID: '20'
      HOST_UID: '502'
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: xxxxx.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.5-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /Users/avi/Projects/xxxxx/.docksal/etc/drush:/etc/drush:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  pma:
    environment:
      PMA_HOST: db
      PMA_PASSWORD: root
      PMA_USER: root
    hostname: pma
    image: phpmyadmin/phpmyadmin
    labels:
      io.docksal.virtual-host: pma.xxxxx.docksal
  redis:
    environment:
      REDIS_MAXMEMORY: 256m
    hostname: redis
    image: wodby/redis:4.0
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FILE_PROXY: https://xxxxxxxx.devcloud.acquia-sites.com/
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/avi/Projects/xxxxx
      io.docksal.virtual-host: xxxxxx.docksal,*.xxxxx.docksal,xxxxx.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/avi/Projects/xxxxx
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.14.2
Darwin durandal2.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : 
NFS EXPORTS:

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.80.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.1
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.06.1-ce

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKER MACHINE
EXPECTED VERSION: 0.15.0
docker-machine version 0.15.0, build b48dc28d

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.06.1-ce   

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                    project root
xxxxx               Up 15 minutes       xxxxx.docksal,*.xxxxx.docksal,xxxxx.docksal.*   /Users/avi/Projects/xxxxx

███  DOCKSAL: VIRTUAL HOSTS
*.xxxxx.docksal
xxxxx.docksal.*
xxxxx.docksal
pma.xxxxx.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
eb303f3b71b4        docksal/web:2.1-apache2.4   "httpd-foreground"       23 minutes ago      Up 15 minutes             80/tcp, 443/tcp                                          xxxxx_web_1_529a4f52f3c0
b8777dd6b790        docksal/cli:2.5-php7.1      "/opt/startup.sh sup…"   23 minutes ago      Up 15 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               xxxxx_cli_1_868a79a0ed21
b87e65bebf81        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   23 minutes ago      Up 15 minutes             0.0.0.0:32774->3306/tcp                                  xxxxx_db_1_56f4a83e2338
fdc92298d079        phpmyadmin/phpmyadmin       "/run.sh supervisord…"   6 days ago          Up 15 minutes             80/tcp, 9000/tcp                                         xxxxx_pma_1_fd0ee765ed2a
618d2c60c54c        wodby/redis:4.0             "/docker-entrypoint.…"   6 days ago          Up 15 minutes             6379/tcp                                                 xxxxx_redis_1_fd2e9a00e98b
aec33359c216        docksal/ssh-agent:1.2       "docker-entrypoint.s…"   2 weeks ago         Up 8 days (healthy)                                                                docksal-ssh-agent
444622d419f9        docksal/dns:1.1             "docker-entrypoint.s…"   2 weeks ago         Up 8 days (healthy)       192.168.64.100:53->53/udp                                docksal-dns
84f7529307bb        docksal/vhost-proxy:1.4     "docker-entrypoint.s…"   2 weeks ago         Up 8 days (healthy)       192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
32af53bc9685        _default            bridge              local
76dfc9ad5c81        bridge              bridge              local
07f75f471957        xxxxx_default       bridge              local
cb28150c36b2        host                host                local
e93d23d59da4        none                null                local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.20
6.0.2r128162

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/avi/Projects/xxxxx on /mnt/sda1/var/lib/docker/volumes/xxxxx_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G      2.9G     40.8G   7% /mnt/sda1

  ```

</details>
