### ISSUE TITLE
How to enable webp GD library support

### ISSUE THREAD

**Issue by marknatividad** [docksal/docksal#983]
**Description**

I'm trying to install the WebP Drupal contrib module (https://www.drupal.org/project/webp), however I am getting the error `Error: Call to undefined function Drupal\webp\imagewebp() in Drupal\webp\Webp->createWebpCopy()`. 

Could I please get assistance on how to enable WebP support within Docksal?

**Steps to reproduce the issue:**

1. Install and enable the WebP module
2. Upload an image with an image style applied

**Describe the results you received:**

Results...

**Describe the results you expected:**

Expected behavior...

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: pearson
COMPOSE_FILE:
/Users/lc0162/.docksal/stacks/overrides-osxfs.yml
/Users/lc0162/.docksal/stacks/volumes-bind.yml
/Users/lc0162/.docksal/stacks/stack-default.yml
/Users/lc0162/Workspace/pearson-online/.docksal/docksal.yml
ENV_FILE:
/Users/lc0162/Workspace/pearson-online/.docksal/docksal.env
/Users/lc0162/Workspace/pearson-online/.docksal/docksal-local.env

PROJECT_ROOT: /Users/lc0162/Workspace/pearson-online
DOCROOT: docroot
VIRTUAL_HOST: pearson.docksal
VIRTUAL_HOST_ALIASES: *.pearson.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      GIT_USER_EMAIL: Mark.Natividad@loudclear.com.au
      GIT_USER_NAME: Mark Natividad
      HOST_GID: '20'
      HOST_UID: '501'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: pearson.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.5-php7.2
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /Users/lc0162/Workspace/pearson-online:/var/www:rw,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: drupal
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 33061:3306/tcp
    volumes:
    - mysql_initdb_d:/docker-entrypoint-initdb.d:ro,nocopy
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  mail:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: mail.pearson.docksal,mail.pearson.docksal.*
      io.docksal.virtual-port: '8025'
    volumes:
    - project_root:/var/www:ro,nocopy
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/lc0162/Workspace/pearson-online
      io.docksal.virtual-host: pearson.docksal,*.pearson.docksal,pearson.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  mysql_initdb_d:
    driver: local
    driver_opts:
      device: /Users/lc0162/Workspace/pearson-online/.docksal/mysql/initdb.d
      o: bind
      type: none
  project_root:
    driver: local
    driver_opts:
      device: /Users/lc0162/Workspace/pearson-online
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  ███  OS
Darwin Mac OS X 10.12.6
Darwin AMAC02TK39DHF1R 16.7.0 Darwin Kernel Version 16.7.0: Thu Dec 20 21:53:35 PST 2018; root:xnu-3789.73.31~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker for Mac

███  FIN
fin version: 1.80.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.1
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.06.1-ce

Client:
 Version:           18.06.1-ce
 API version:       1.37 (downgraded from 1.38)
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.03.1-ce
  API version:      1.37 (minimum version 1.12)
  Go version:       go1.9.5
  Git commit:       9ee9f40
  Built:            Thu Apr 26 07:22:38 2018
  OS/Arch:          linux/amd64
  Experimental:     true

███  DOCKSAL: PROJECTS
project             STATUS              virtual host                                          project root
pearson             Up 7 days           pearson.docksal,*.pearson.docksal,pearson.docksal.*   /Users/lc0162/Workspace/pearson-online

███  DOCKSAL: VIRTUAL HOSTS
*.pearson.docksal
mail.pearson.docksal.*
mail.pearson.docksal
pearson.docksal.*
pearson.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                PORTS                                                    NAMES
7c156c86ca6f        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   7 days ago          Up 7 days             0.0.0.0:32768->3306/tcp                                  pearson_db_1_c5ef5855c67a
885e97ac7198        docksal/ssh-agent:1.2       "docker-entrypoint.s…"   7 days ago          Up 7 days (healthy)                                                            docksal-ssh-agent
00eeb4e4a206        docksal/dns:1.1             "docker-entrypoint.s…"   7 days ago          Up 7 days (healthy)   192.168.64.100:53->53/udp                                docksal-dns
f1cef9e0ee81        docksal/vhost-proxy:1.4     "docker-entrypoint.s…"   7 days ago          Up 7 days (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
571aa4cd4176        docksal/web:2.1-apache2.4   "httpd-foreground"       2 weeks ago         Up 7 days             80/tcp, 443/tcp                                          pearson_web_1_327307eba259
4c076b9d28f6        docksal/cli:2.5-php7.2      "/opt/startup.sh sup…"   2 weeks ago         Up 7 days (healthy)   22/tcp, 3000/tcp, 9000/tcp                               pearson_cli_1_bbb82f6c852d
40f53d9bc4a0        mailhog/mailhog             "MailHog"                6 weeks ago         Up 7 days             1025/tcp, 8025/tcp                                       pearson_mail_1_541ff41baf8a
da38c93723d0        memcached:1.4-alpine        "docker-entrypoint.s…"   6 weeks ago         Up 7 days             11211/tcp                                                pearson_memcached_1_d80422c1d9a3

███  DOCKER: NETWORKS
NETWORK ID          NAME                                                                         DRIVER              SCOPE
3ea6f808e7c9        _default                                                                     bridge              local
9536e7607f67        bridge                                                                       bridge              local
b8d52297547a        host                                                                         host                local
19738ca6273a        lando_bridge_network                                                         bridge              local
26b01c3ef5bf        landocasetupkenobi38ahsokacea473268995409e2276c8ab5c8cee96454cf314_default   bridge              local
f3d3b8900f6e        landoproxyhyperion5000gandalfedition_edge                                    bridge              local
a0d545461ec6        none                                                                         null                local
e57d729e89cf        pearson_default                                                              bridge              local
96a6d9fc955e        sol_default                                                                  bridge              local

███  HDD Usage
Filesystem      Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1     465Gi  242Gi  222Gi    53% 2058191 4292909088    0%   /
devfs          194Ki  194Ki    0Bi   100%     672          0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%       0          0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0          0  100%   /home
/dev/disk0s3   620Mi  554Mi   66Mi    90%      74 4294967205    0%   /Volumes/Recovery HD
  ```

</details>
